### ISSUE TITLE
dvc status error with S3 output

### ISSUE THREAD

**Issue by chwonghk01** [iterative/dvc#1048]
DVC version 0.17.1, installed with pip.

Running `dvc status` shows
```
Failed to obtain data status: 'OutputS3' object has no attribute 'rel_path'
```
and nothing else (e.g. files that are not output to S3)

My .dvc/config:
```
['remote "data"']
url = s3://xxxxx/data
[core]
remote = data
['remote "s3cache"']
url = s3://xxxxx/cache
[cache]
s3 = s3cache
```

**Comment by chwonghk01** [comment]
@efiop I have updated the dvc and got the same error message.
```$ dvc --version
0.18.2
$ dvc status --verbose
Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dvc/command/status.py", line 31, in do_run
    remote=self.args.remote)
  File "/usr/local/lib/python3.6/site-packages/dvc/project.py", line 496, in status
    return self._local_status(target)
  File "/usr/local/lib/python3.6/site-packages/dvc/project.py", line 457, in _local_status
    status.update(stage.status())
  File "/usr/local/lib/python3.6/site-packages/dvc/stage.py", line 399, in status
    ret.update(self._status(self.outs, 'outs'))
  File "/usr/local/lib/python3.6/site-packages/dvc/stage.py", line 386, in _status
    ret.update(entry.status())
  File "/usr/local/lib/python3.6/site-packages/dvc/dependency/base.py", line 62, in status
    return {self.rel_path: 'changed'}
AttributeError: 'OutputS3' object has no attribute 'rel_path'

Error: Failed to obtain data status: 'OutputS3' object has no attribute 'rel_path'```

**Comment by efiop** [comment]
Thank you! Already preparing a patch. Will release 0.18.3 in an hour or so with the fix.

**Comment by efiop** [comment]
@chwonghk01 0.18.3 is out. Please feel free to upgrade. Thank you again for the feedback!

**Comment by zb0th** [comment]
I'm getting this error on dvc 0.30.1. In my case the dependencies are gs ones.
