### ISSUE TITLE
dvc exp run: with import-db fails with `'NoneType' object has no attribute 'isabs'`

### ISSUE THREAD

**Issue by kychoi-veesion** [iterative/dvc#10496]
# Bug Report

## Description

I am using a postgresql input source in my pipeline using the experimental `import-db` command.
Everything run fine when using the `dvc repro` command but fails when trying to run an experiments, even though the input source has not changed. 

### Reproduce

Unfortunately, I can't share a database connection to reproduce the problem but here are the steps to reproduce the problem:
 
1. dvc init
2. dvc import-db ... -o data/unbiased.csv
3. dvc repro (works)
4. dvc exp run -n test ... : fails with the following error

```
2024-08-01 09:58:32,210 ERROR: failed to reproduce 'data/unbiased.csv.dvc': 'NoneType' object has no attribute 'isabs'                                                                       
Traceback (most recent call last):                                                                                                                                                           
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/reproduce.py", line 187, in _reproduce                                                                     
    ret = repro_fn(stage, upstream=upstream, force=force_stage, **kwargs)                                                                                                                    
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/experiments/executor/base.py", line 538, in _repro_and_track
    if not kwargs.get("dry") and (paths := _get_stage_files(stage)):
                                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/stage/utils.py", line 301, in _get_stage_files
    not dep.use_scm_ignore
        ^^^^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/output.py", line 504, in use_scm_ignore
    if not self.is_in_repo:
           ^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/output.py", line 497, in is_in_repo
    if self.fs.isabs(self.def_path):
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'isabs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/cli/__init__.py", line 211, in main
    ret = cmd.do_run()
          ^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/cli/command.py", line 27, in do_run
    return self.run()
           ^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/commands/experiments/run.py", line 14, in run
    self.repo.experiments.run(
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/experiments/__init__.py", line 354, in run
    return run(self.repo, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/__init__.py", line 58, in wrapper
    return f(repo, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/experiments/run.py", line 77, in run
    return repo.experiments.reproduce_one(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/experiments/__init__.py", line 126, in reproduce_one
    results = self._reproduce_queue(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/experiments/utils.py", line 62, in wrapper
    ret = f(exp, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/experiments/__init__.py", line 249, in _reproduce_queue
    exec_results = queue.reproduce(copy_paths=copy_paths, message=message)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/experiments/queue/workspace.py", line 93, in reproduce
    self._reproduce_entry(
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/experiments/queue/workspace.py", line 116, in _reproduce_entry
    exec_result = executor.reproduce(
                  ^^^^^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/experiments/executor/base.py", line 509, in reproduce
    stages = dvc.reproduce(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/__init__.py", line 58, in wrapper
    return f(repo, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/scm_context.py", line 143, in run
    return method(repo, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/reproduce.py", line 248, in reproduce
    return _reproduce(steps, graph=graph, on_error=on_error or "fail", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/reproduce.py", line 191, in _reproduce
    _raise_error(exc, stage)
  File "/ssd2/kchoi/miniforge3/envs/triplet/lib/python3.12/site-packages/dvc/repo/reproduce.py", line 155, in _raise_error
    raise ReproductionError(f"failed to reproduce{segment} {names}") from exc
dvc.exceptions.ReproductionError: failed to reproduce 'data/unbiased.csv.dvc'
```

### Expected

The experiment succeds

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.51.2 (conda)
---------------------------
Platform: Python 3.12.4 on Linux-5.15.0-89-generic-x86_64-with-glibc2.35
Subprojects:
        dvc_data = 3.15.1
        dvc_objects = 5.1.0
        dvc_render = 1.0.2
        dvc_task = 0.4.0
        scmrepo = 3.3.6
Supports:
        http (aiohttp = 3.9.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.9.5, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2024.6.1, boto3 = 1.34.131)
Config:
        Global: /home/veesion/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda1
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/sda1
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/dd4f961a1db160863afb59c1974f92e8
```

**Additional Information (if any):**

**Comment by skshetry** [comment]
Fixed and released in 3.53.1.
