### ISSUE TITLE
dvc==3.53.0 import fails with No such file or directory when cache.dir configured and cache.dir symlink

### ISSUE THREAD

**Issue by petrchmelar** [iterative/dvc#10500]
# Bug Report

## Description

dvc==3.53.0 ends with "No such file or directory" error when cache type configured to symlink and cache.dir configured to other value than default. With default dir everything seems to be working as expected.

### Reproduce

```console
╰─❯ pip install dvc==3.53.0
╰─❯ mkdir reproducer  
╰─❯ cd reproducer 
╰─❯ mkdir cache
╰─❯ git init
╰─❯ dvc init
╰─❯ dvc config cache.dir cache 
╰─❯ dvc config cache.type symlink
╰─❯ dvc import https://github.com/iterative/example-get-started/ data/prepared --verbose
```

### Expected

`data/prepared` data to be imported as a symlink to cache dir

### Environment information

**Output of `dvc doctor`:**

```console
╰─❯ dvc doctor                                                                             
DVC version: 3.53.0 (pip)
-------------------------
Platform: Python 3.10.12 on Linux-5.15.0-97-generic-x86_64-with-glibc2.35
Subprojects:
	dvc_data = 3.15.1
	dvc_objects = 5.0.0
	dvc_render = 1.0.1
	dvc_task = 0.3.0
	scmrepo = 3.3.6
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2024.2.0, boto3 = 1.28.17)
Config:
	Global: /home/pchmelar/.config/dvc
	System: /etc/xdg/dvc
Cache types: reflink, hardlink, symlink
Cache directory: xfs on /dev/mapper/data-srv
Caches: local
Remotes: None
Workspace directory: xfs on /dev/mapper/data-srv
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/8072c2aab2b83cb03b4c02ef3a589d3c

```

**Additional Information (if any):**

<details>
<summary>Verbose log</summary>

```
╰─❯ dvc import https://github.com/iterative/example-get-started/ data/prepared --verbose
2024-08-02 12:16:37,530 DEBUG: v3.53.0 (pip), CPython 3.10.12 on Linux-5.15.0-97-generic-x86_64-with-glibc2.35
2024-08-02 12:16:37,530 DEBUG: command: /home/pchmelar/.local/bin/dvc import https://github.com/iterative/example-get-started/ data/prepared --verbose
2024-08-02 12:16:39,251 DEBUG: Removing output 'prepared' of stage: 'prepared.dvc'.
2024-08-02 12:16:39,251 DEBUG: Removing '/mnt/srv.local/workplace/pchmelar/repos/reproducer/prepared'
Importing 'data/prepared (https://github.com/iterative/example-get-started/)' -> 'prepared'
2024-08-02 12:16:39,253 DEBUG: Computed stage: 'prepared.dvc' md5: '9c259d24c440efed1204e1c1502f6849'
2024-08-02 12:16:39,253 DEBUG: 'md5' of stage: 'prepared.dvc' changed.
2024-08-02 12:16:39,254 DEBUG: Creating external repo https://github.com/iterative/example-get-started/@None
2024-08-02 12:16:39,254 DEBUG: erepo: git clone 'https://github.com/iterative/example-get-started/' to a temporary dir
2024-08-02 12:16:41,668 DEBUG: Creating external repo https://github.com/iterative/example-get-started/@06ea48980a34ef57041c9b905cafcb40d9c3ddbc
2024-08-02 12:16:42,057 DEBUG: failed to load ('data', 'prepared') from storage local (/mnt/srv.local/workplace/pchmelar/repos/reproducer/cache/files/md5) - [Errno 2] No such file or directory: '/mnt/srv.local/workplace/pchmelar/repos/reproducer/cache/files/md5/15/3aad06d376b6595932470e459ef42a.dir'
Traceback (most recent call last):
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc_data/index/index.py", line 611, in _load_from_storage
    _load_from_object_storage(trie, entry, storage)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc_data/index/index.py", line 547, in _load_from_object_storage
    obj = Tree.load(storage.odb, root_entry.hash_info, hash_name=storage.odb.hash_name)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc_data/hashfile/tree.py", line 193, in load
    with obj.fs.open(obj.path, "r") as fobj:
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 329, in open
    return self.fs.open(path, mode=mode, **kwargs)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc_objects/fs/local.py", line 131, in open
    return open(path, mode=mode, encoding=encoding)  # noqa: SIM115
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/srv.local/workplace/pchmelar/repos/reproducer/cache/files/md5/15/3aad06d376b6595932470e459ef42a.dir'

2024-08-02 12:16:43,227 DEBUG: built tree 'object 153aad06d376b6595932470e459ef42a.dir'
2024-08-02 12:16:43,229 DEBUG: Removing '/mnt/srv.local/workplace/pchmelar/repos/reproducer/.FWTtodOeWf6B2-Rv0sa7Gg.tmp'
2024-08-02 12:16:43,229 DEBUG: Removing '/mnt/srv.local/workplace/pchmelar/repos/reproducer/cache/files/md5/.SBSoHmCjXccENVLT4jay9g.tmp'
2024-08-02 12:16:43,234 ERROR: unexpected error - [Errno 2] No such file or directory: '/mnt/srv.local/workplace/pchmelar/repos/reproducer/prepared/train.tsv'
Traceback (most recent call last):
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc/cli/__init__.py", line 211, in main
    ret = cmd.do_run()
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc/cli/command.py", line 27, in do_run
    return self.run()
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc/commands/imp.py", line 15, in run
    self.repo.imp(
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc/repo/imp.py", line 44, in imp
    return self.imp_url(path, out=out, erepo=erepo, frozen=True, **kwargs)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc/repo/__init__.py", line 58, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc/repo/scm_context.py", line 143, in run
    return method(repo, *args, **kw)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc/repo/imp_url.py", line 86, in imp_url
    stage.run(jobs=jobs, no_download=no_download)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc/stage/decorators.py", line 44, in rwlocked
    return call()
  File "/home/pchmelar/.local/lib/python3.10/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc/stage/__init__.py", line 612, in run
    self._sync_import(dry, force, kwargs.get("jobs", None), no_download)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc/stage/decorators.py", line 44, in rwlocked
    return call()
  File "/home/pchmelar/.local/lib/python3.10/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc/stage/__init__.py", line 645, in _sync_import
    sync_import(self, dry, force, jobs, no_download)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc/stage/imports.py", line 61, in sync_import
    stage.deps[0].download(stage.outs[0], jobs=jobs)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc/dependency/repo.py", line 109, in download
    checkout(
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc_data/hashfile/checkout.py", line 266, in checkout
    _checkout(
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc_data/hashfile/checkout.py", line 213, in _checkout
    _checkout_file(
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc_data/hashfile/checkout.py", line 115, in _checkout_file
    state.save(path, fs, change.new.oid)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc_data/hashfile/state.py", line 110, in save
    info = info or fs.info(path)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 597, in info
    return self.fs.info(path, **kwargs)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/dvc_objects/fs/local.py", line 39, in info
    return self.fs.info(path)
  File "/home/pchmelar/.local/lib/python3.10/site-packages/fsspec/implementations/local.py", line 90, in info
    out = os.stat(path, follow_symlinks=True)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/srv.local/workplace/pchmelar/repos/reproducer/prepared/train.tsv'

2024-08-02 12:16:43,296 DEBUG: Removing '/mnt/srv.local/workplace/pchmelar/repos/.wzU6vqSQUODPJgsQ6mGNMQ.tmp'
2024-08-02 12:16:43,296 DEBUG: Removing '/mnt/srv.local/workplace/pchmelar/repos/.wzU6vqSQUODPJgsQ6mGNMQ.tmp'
2024-08-02 12:16:43,296 DEBUG: Removing '/mnt/srv.local/workplace/pchmelar/repos/.wzU6vqSQUODPJgsQ6mGNMQ.tmp'
2024-08-02 12:16:43,296 DEBUG: Removing '/mnt/srv.local/workplace/pchmelar/repos/reproducer/cache/files/md5/.fBGKXnV3de3417BbCuJvvQ.tmp'
2024-08-02 12:16:43,415 DEBUG: Version info for developers:
DVC version: 3.53.0 (pip)
-------------------------
Platform: Python 3.10.12 on Linux-5.15.0-97-generic-x86_64-with-glibc2.35
Subprojects:
	dvc_data = 3.15.1
	dvc_objects = 5.0.0
	dvc_render = 1.0.1
	dvc_task = 0.3.0
	scmrepo = 3.3.6
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2024.2.0, boto3 = 1.28.17)
Config:
	Global: /home/pchmelar/.config/dvc
	System: /etc/xdg/dvc
Cache types: reflink, hardlink, symlink
Cache directory: xfs on /dev/mapper/data-srv
Caches: local
Remotes: None
Workspace directory: xfs on /dev/mapper/data-srv
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/8072c2aab2b83cb03b4c02ef3a589d3c

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2024-08-02 12:16:43,417 DEBUG: Analytics is enabled.
2024-08-02 12:16:43,603 DEBUG: Trying to spawn ['daemon', 'analytics', '/tmp/tmpwtb7hqui', '-v']
2024-08-02 12:16:43,611 DEBUG: Spawned ['daemon', 'analytics', '/tmp/tmpwtb7hqui', '-v'] with pid 682791
2024-08-02 12:16:43,613 DEBUG: Removing '/tmp/tmp7p119nl_dvc-clone'
2024-08-02 12:16:43,616 DEBUG: Removing '/tmp/tmpa7s88u9fdvc-cache'
```
</details>

**Comment by Honzys** [comment]
The fix is acutally a one-liner. I tried to create a PR, could you please take a look at it?
https://github.com/iterative/dvc/pull/10501

**Comment by shcheklein** [comment]
@Honzys thanks for looking into this. @petrchmelar thanks for a great report and the script to reproduce this.

I think we need to go deeper first and understand why it fails only when a custom cache dir is specified. It makes me think that we don't download a file into cache properly on import? or we don't locate it properly?

W/o some research it's hard to understand if catching the error is the right way or not.

**Comment by Honzys** [comment]
I totally agree with you.

But for now, wouldn't it be easier to release a dirty hot fix `3.53.1` and do the real investigation thoroughly afterwards?

From my point of view the `download` logic is like "Try the checkout, if there's any fail, fallback to the current behaviour of the `download`", maybe I can change the catched exception from `CheckoutError` to `Exception` in general, I guess?

**Comment by dberenbaum** [comment]
@Honzys I think you have summarized the logic from #10388 well. However, I also think it's worth investigating why the error occurs.

In this case, it has nothing to do with the custom cache directory. It's only about the cache type. When using `copy`, the transfer step during checkout fails to copy from the cache and raises the expected `CheckoutError`. When using `symlink`, the transfer step creates broken links to the cache for files that don't exist there without raising any error (`fs.symlink()` and `os.symlink()` will succeed even if the link target does not exist). Since the error is not caught during transfer, it causes the downstream error. I think it might be best to check that the link target (`from_path`) exists before calling transfer [here](https://github.com/iterative/dvc-data/blob/09be16ba25506a5ac90cb7e57a5c94cd811cb3a8/src/dvc_data/hashfile/checkout.py#L160-L178).

**Comment by dberenbaum** [comment]
Opened https://github.com/iterative/dvc-data/pull/542, but it looks like it can hurt performance, so I think maybe #10501 is the best way to go. @shcheklein @skshetry WDYT?

**Comment by petrchmelar** [comment]
Thanks a lot!
