### ISSUE TITLE
dvc add fails with "Unexp

### ISSUE THREAD

**Issue by crmne** [iterative/dvc#1207]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

**Comment by crmne** [comment]
Upgraded to 0.19.9 and have the same error

**Comment by efiop** [comment]
Hi @crmne !

Could you please run that command again but with the `-v` flag added? It will enable more verbose output, so we can see better where the error was raised.

Thanks,
Ruslan

**Comment by crmne** [comment]
```
Error: Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/main.py", line 22, in main
    ret = cmd.run_cmd()
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/command/base.py", line 40, in run_cmd
    return self.run()
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/command/add.py", line 10, in run
    self.project.add(target, recursive=self.args.recursive)
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/project.py", line 173, in add
    stage.save()
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/stage.py", line 393, in save
    out.save()
  File "/home/ubuntu/.local/share/virtualenvs/comms-reco-9eeOrpBx/lib/python3.7/site-packages/dvc/output/local.py", line 113, in save
    self.info = self.project.cache.local.save(self.path_info)
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/remote/local.py", line 325, in save
    return self._save_file(path_info)
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/remote/local.py", line 276, in _save_file
    md5 = self.state.update(path)
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/state.py", line 265, in update
    return self._do_update(path)[0]
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/state.py", line 238, in _do_update
    int(nanotime.timestamp(time.time()))))
sqlite3.IntegrityError: datatype mismatch

Error: Unexpected error: datatype mismatch
```

**Comment by efiop** [comment]
Thank you! Looks like some value that we are trying to insert doesn't have a right type. Looking into it right now.

**Comment by efiop** [comment]
I've pushed a patch to my repository that will show us more details of what is going on. Could you please install it and run `dvc add` with `-v` flag once more? E.g.:
```
pip uninstall dvc
pip install git+https://github.com/efiop/dvc.git
```

**Comment by crmne** [comment]
Thanks for the help Ruslan!

```
Debug: PRAGMA user_version;
Debug: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
Debug: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
Debug: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
Debug: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
Debug: PRAGMA user_version = 0;
Adding 'data/training/events.csv' to 'data/training/.gitignore'.
Saving 'data/training/events.csv' to cache '../efs/dvc-cache'.
Debug: SELECT * from state WHERE inode=13179763115544939846
Computing md5 for a large file data/training/events.csv. This is only done once.
[##############################] 100% data/training/events.csv
Debug: INSERT INTO state(inode, mtime, md5, timestamp) VALUES (13179763115544939846, "1539295462717999872", "7644a112b656993f67c5697ff0e2abb8", "1539302880543382272")
Debug: SELECT count from state_info WHERE rowid=1
Debug: UPDATE state_info SET count = 4 WHERE rowid = 1
Error: Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/main.py", line 22, in main
    ret = cmd.run_cmd()
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/command/base.py", line 40, in run_cmd
    return self.run()
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/command/add.py", line 10, in run
    self.project.add(target, recursive=self.args.recursive)
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/project.py", line 173, in add
    stage.save()
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/stage.py", line 393, in save
    out.save()
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/output/local.py", line 113, in save
    self.info = self.project.cache.local.save(self.path_info)
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/remote/local.py", line 325, in save
    return self._save_file(path_info)
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/remote/local.py", line 276, in _save_file
    md5 = self.state.update(path)
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/state.py", line 269, in update
    return self._do_update(path)[0]
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/state.py", line 242, in _do_update
    int(nanotime.timestamp(time.time()))))
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/state.py", line 87, in _execute
    return self.c.execute(cmd)
sqlite3.IntegrityError: datatype mismatch

Error: Unexpected error: datatype mismatch
```
Note that this file is quite large (~40GB) and the problem doesn't occur with smaller files.

**Comment by efiop** [comment]
Aha, got it. Here is a script to reproduce the issue:

```
import os
import sqlite3


if os.path.isfile('db'):
    os.unlink('db')

db = sqlite3.connect('db')
c = db.cursor()
c.execute("CREATE TABLE IF NOT EXISTS MYTABLE (inode INTEGER PRIMARY KEY)")
c.execute("INSERT INTO MYTABLE(inode) VALUES(13179763115544939846)")
```

we are storing inode in the INTEGER PRIMARY KEY column, and turns out it doesn't allow values that are bigger than 2**63, even though I expected it to support up to 2**64, because regular INTEGER column does. Looking into solving this right now.

**Comment by efiop** [comment]
I'm about to merge a patch for this issue and will release 0.19.10 that should be ready in an hour or so. If you want to, you can install dvc from my repository once again(with commands from above) and try it out while the release is getting prepared.

**Comment by efiop** [comment]
0.19.10 is out. Feel free to upgrade.

**Comment by crmne** [comment]
Thank you Ruslan for the amazing support. I can confirm that it in fact works!
