### ISSUE TITLE
ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by villasv** [iterative/dvc#1210]
Using latest version (`0.19.9`) will install `asciimatics` instead of `asciicanvas` (which seems intended), but running `dvc repro ...` will result in:
```

Traceback (most recent call last):
  File "/home/villasv/.local/share/virtualenvs/red-education-RQhbWawp/bin/dvc", line 7, in <module>
    from dvc.main import main
  File "/home/villasv/.local/share/virtualenvs/red-education-RQhbWawp/lib/python3.6/site-packages/dvc/main.py", line 2, in <module>
    from dvc.cli import parse_args
  File "/home/villasv/.local/share/virtualenvs/red-education-RQhbWawp/lib/python3.6/site-packages/dvc/cli.py", line 27, in <module>
    from dvc.command.pipeline import CmdPipelineShow
  File "/home/villasv/.local/share/virtualenvs/red-education-RQhbWawp/lib/python3.6/site-packages/dvc/command/pipeline.py", line 5, in <module>
    from dvc.dagascii import Dagascii
  File "/home/villasv/.local/share/virtualenvs/red-education-RQhbWawp/lib/python3.6/site-packages/dvc/dagascii.py", line 5, in <module>
    from asciimatics.screen import Screen
  File "/home/villasv/.local/share/virtualenvs/red-education-RQhbWawp/lib/python3.6/site-packages/asciimatics/screen.py", line 1927, in <module>
    import curses
  File "/home/villasv/.pyenv/versions/3.6.5/lib/python3.6/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by efiop** [comment]
Hi @villasv !

Long time no see! :)

You are running Linux here, right? Could you please show output of `ldd $(which python)`?

Thanks,
Ruslan

**Comment by efiop** [comment]
Ah, wait, nevermind. Python loads ncurses dynamically, so `ldd` shouldn't show it either way.

What I'm guessing here is that there is no libncurses in your environment for some reason. Do you run pyenv or something? If so, could you try running `import curses` in your system's python just to see if that will work?

Thanks,
Ruslan

**Comment by efiop** [comment]
On *nix curses is considered to be a part of standard library for python, but with pyenv it is not included if you don't have libncurses dev package installed, since Python is being built on your machine. The solution in the link you've provided should work.

**Comment by efiop** [comment]
Created a patch https://github.com/iterative/dvc/pull/1211 that dynamically loads asciimatics only when needed, so absence of curses will no longer be affecting commands that don't use it. Please let me know If you don't need `pipeline show --ascii` and don't want to bother with libncurses, so I could release 0.19.10 ASAP.

**Comment by villasv** [comment]
No need to rush, I was able to reinstall the pyenv distribution with the required dependencies. Just confirmed, it solves the issue. ;) Thanks!

PS if I'm showing up here less and less, it's because `dvc` is so much smooth ;)

**Comment by efiop** [comment]
Glad it worked for you :) Thank you for all your feedback!

**Comment by efiop** [comment]
0.19.10 is out. Feel free to upgrade.

**Comment by Akshay050592** [comment]
Traceback (most recent call last):
  File "D:/practice/project/snake.py", line 3, in <module>
    import curses
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by efiop** [comment]
Hi @Akshay050592 ! Are you using dvc? Where does that traceback come from?

**Comment by Kostyadolbilov** [comment]
Hello!

I have similar problem but with modul 'cursor'.

I worked on the project using PyCharm on my Mac. But, when I try to edit code on the Windows PC, it prints me mistake that I don't have modul 'cursor'. But when I go to check is it installed or not in the command it prints that cursor is already installed.
How to solve this problem?

Thank you

**Comment by RadiantUwU** [comment]
>>> import curses
Traceback (most recent call last):
  File "c:\Users\User\Desktop\Files\python scripts\mms4.0 emulator\enhanced.py", line 235, in shellc
    print(eval(c,self.globals,self.locals))
  File "<string>", line 1
    import curses
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\User\Desktop\Files\python scripts\mms4.0 emulator\enhanced.py", line 240, in shellc
    exec(c,self.globals,self.locals)
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\curses\__init__.py", line 13, in <module>      
    from _curses import *
ModuleNotFoundError: No module named '_curses'
This is running on windows 10, in a pseudo python shell made by me
