### ISSUE TITLE
Error: failed to push data to the cloud

### ISSUE THREAD

**Issue by crmne** [iterative/dvc#1225]
Hi again!

I'm having the following problem:
```bash
$ dvc push -v
Debug: PRAGMA user_version;
Debug: CREATE TABLE IF NOT EXISTS state (inode UNSIGNED INTEGER PRIMARY KEY, mtime TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
Debug: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
Debug: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode UNSIGNED INTEGER NOT NULL, mtime TEXT NOT NULL)
Debug: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
Debug: PRAGMA user_version = 1;
Preparing to push data to s3://redacted/redacted
[###                           ] 10% Collecting informationDebug: SELECT * from state WHERE inode=7505163933931234253
Debug: UPDATE state SET timestamp = "1539626698545023488" WHERE inode = 7505163933931234253
Debug: SELECT * from state WHERE inode=5912987791212950678
Debug: UPDATE state SET timestamp = "1539626698545638400" WHERE inode = 5912987791212950678
Debug: SELECT * from state WHERE inode=7086292011979178256
Debug: UPDATE state SET timestamp = "1539626698546188800" WHERE inode = 7086292011979178256
Debug: SELECT * from state WHERE inode=2039092171743050023
Debug: UPDATE state SET timestamp = "1539626698546865408" WHERE inode = 2039092171743050023
Debug: SELECT * from state WHERE inode=11883370550676727332
Debug: SELECT count from state_info WHERE rowid=1
Debug: UPDATE state_info SET count = 22 WHERE rowid = 1
Error: Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/command/data_sync.py", line 45, in do_run
    with_deps=self.args.with_deps)
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/project.py", line 544, in push
    show_checksums=show_checksums)
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/data_cloud.py", line 108, in push
    show_checksums=show_checksums)
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/remote/local.py", line 621, in push
    checksum_infos = list(filter(func, checksum_infos))
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/remote/local.py", line 620, in func
    return not self.changed_cache(info[self.PARAM_MD5])
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/remote/local.py", line 86, in changed_cache
    if self.state.changed(cache, md5=md5):
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/state.py", line 78, in changed
    actual = self.update(path)
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/state.py", line 269, in update
    return self._do_update(path)[0]
  File "/home/ubuntu/.local/share/virtualenvs/9eeOrpBx/lib/python3.7/site-packages/dvc/state.py", line 248, in _do_update
    assert i == inode
AssertionError

Error: Failed to push data to the cloud:
```

DVC 0.19.11, installed through Pipenv (pip)

Any ideas?

**Comment by efiop** [comment]
Hi @crmne !

I've pushed a patch that will help us to debug this issue to my repo. Could you please install it from there, and run your command again? I.e.:
```
pip uninstall dvc
pip install git+https://github.com/efiop/dvc.git
```

Thanks,
Ruslan

**Comment by efiop** [comment]
Ok, was able to reproduce this issue. Preparing a patch right now.

**Comment by efiop** [comment]
@crmne 0.19.12 with a fix is out. Please try it out :) Thanks again for your feedback!

**Comment by crmne** [comment]
Hey @efiop !

Thank you again for the fast response and fix! I'm trying it out right now and I'll let you know soon.
