### ISSUE TITLE
An attempt was made to create more links on a file than the file system supports

### ISSUE THREAD

**Issue by gcoter** [iterative/dvc#1244]
Hello,

I tried to `dvc add` a folder containing 529 118 images and got this error:

```
Error: Traceback (most recent call last):
  File "c:\devtools\miniconda3\lib\site-packages\dvc\main.py", line 22, in main
    ret = cmd.run_cmd()
  File "c:\devtools\miniconda3\lib\site-packages\dvc\command\base.py", line 40, in run_cmd
    return self.run()
  File "c:\devtools\miniconda3\lib\site-packages\dvc\command\add.py", line 10, in run
    self.project.add(target, recursive=self.args.recursive)
  File "c:\devtools\miniconda3\lib\site-packages\dvc\project.py", line 173, in add
    stage.save()
  File "c:\devtools\miniconda3\lib\site-packages\dvc\stage.py", line 393, in save
    out.save()
  File "c:\devtools\miniconda3\lib\site-packages\dvc\output\local.py", line 113, in save
    self.info = self.project.cache.local.save(self.path_info)
  File "c:\devtools\miniconda3\lib\site-packages\dvc\remote\local.py", line 344, in save
    return self._save_dir(path_info)
  File "c:\devtools\miniconda3\lib\site-packages\dvc\remote\local.py", line 327, in _save_dir
    self.link(c, p)
  File "c:\devtools\miniconda3\lib\site-packages\dvc\remote\local.py", line 126, in link
    self.CACHE_TYPE_MAP[self.cache_types[0]](cache, path)
  File "c:\devtools\miniconda3\lib\site-packages\dvc\system.py", line 24, in hardlink
    raise ctypes.WinError()
OSError: [WinError 1142] An attempt was made to create more links on a file than the file system supports.

Error: Unexpected error: [WinError 1142] An attempt was made to create more links on a file than the file system supports.
```

How should I treat this kind of folder containing so many files? Maybe I should use a database instead of DVC in that case?

For information, I use DVC version 0.19.12 on Windows (installed with pip).

**Comment by efiop** [comment]
What fs are you using? NTFS? Does simply copying directory yourself work?

**Comment by efiop** [comment]
Hm, interesting. Does you directory have a lot of identical files by any chance(or maybe files in common with what you already have in a cache, e.g. something like empty files)? I suspect that we might be hitting maximum number of hardlinks: [`"but note that NTFS limits the maximum number of hardlinks per file to 1023"`](https://www.mercurial-scm.org/wiki/HardlinkedClones). Could you try switching cache type to symlinks(`dvc config cache.type symlink,copy`) and try adding the directory again?

**Comment by efiop** [comment]
Ah, wait a second, dvc should not have raised that exception, but rather tried to symlink after it. Let me prepare a patch...

**Comment by efiop** [comment]
I've pushed a patch to master. Could you please install from upstream and give it a try? I.e. `pip uninstall dvc` + `pip install git+https://github.com/iterative/dvc.git`.

**Comment by gcoter** [comment]
Looks like it worked. Thank you!

**Comment by efiop** [comment]
Glad it worked! Do you have the log of `dvc add` that worked? Just need to make sure what specifically worked :)

**Comment by gcoter** [comment]
Sorry, I forgot to answer you! I didn't keep the logs unfortunately. However, if I remember well, I saw that it switched to symlink.
