### ISSUE TITLE
Handle KeyboardInterrupt gracefully

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1389]
Currently, when you send a `SIGINT` to a running instance of DVC, it doesn't terminate properly.

```bash
dvc run 'sleep 999s'
# Ctrl+C
#   or
# pkill -INT dvc
```

Error:
```
Traceback (most recent call last):
  File "/home/mroutis/src/iterative/dvc/.venv/bin/dvc", line 11, in <module>
    load_entry_point('dvc', 'console_scripts', 'dvc')()
  File "/home/mroutis/src/iterative/dvc/dvc/main.py", line 22, in main
    ret = cmd.run_cmd()
  File "/home/mroutis/src/iterative/dvc/dvc/command/base.py", line 41, in run_cmd
    return self.run()
  File "/home/mroutis/src/iterative/dvc/dvc/command/run.py", line 34, in run
    no_exec=self.args.no_exec)
  File "/home/mroutis/src/iterative/dvc/dvc/project.py", line 355, in run
    stage.run()
  File "/home/mroutis/src/iterative/dvc/dvc/stage.py", line 488, in run
    self._run()
  File "/home/mroutis/src/iterative/dvc/dvc/stage.py", line 460, in _run
    p.communicate()
  File "/usr/lib/python3.7/subprocess.py", line 925, in communicate
    self.wait()
  File "/usr/lib/python3.7/subprocess.py", line 984, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1618, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.7/subprocess.py", line 1576, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by dmpetrov** [comment]
With `--verbose` option DVC still should show the stack trace I guess.
