### ISSUE TITLE
Pyfiglet is missing

### ISSUE THREAD

**Issue by anotherbugmaster** [iterative/dvc#1518]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

OS: Arch Linux
Package manager: yay
DVC couldn't find the package pyfiglet when run:

```
 ~/Documents/scaleway_ansible  dvc               
Traceback (most recent call last):
  File "/usr/bin/dvc", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/anotherbugmaster/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3105, in <module>
    @_call_aside
  File "/home/anotherbugmaster/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3089, in _call_aside
    f(*args, **kwargs)
  File "/home/anotherbugmaster/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3118, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/anotherbugmaster/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/home/anotherbugmaster/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/anotherbugmaster/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyfiglet>=0.7.2' distribution was not found and is required by asciimatics
```
Everything works after manual installation of pyfiglet.

**Comment by anotherbugmaster** [comment]
There's no pyfiglet in requirements.txt, maybe that causes the issue.

**Comment by efiop** [comment]
Hi @anotherbugmaster !

Seems like an issue with the yay package itself. As a workaround, you could try installing it with pip `pip install dvc`(probably a good idea to uninstall yay package first so that `dvc` paths don't overlap). @mroutis is a maintainer of that yay package, so maybe he could try to reproduce this issue.

Thanks for the feedback! 🙂
