### ISSUE TITLE
pip install for development version fails

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#1535]
https://dvc.org/doc/user-guide/development fails with:

```
Collecting git+git://github.com/iterative/dvc
  Cloning git://github.com/iterative/dvc to /private/var/folders/_1/dxrf7_f15sn4r01jvqvr5b6h0000gn/T/pip-req-build-NS8S38
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_1/dxrf7_f15sn4r01jvqvr5b6h0000gn/T/pip-req-build-NS8S38/setup.py", line 5, in <module>
        from dvc import VERSION
      File "dvc/__init__.py", line 53, in <module>
        __version__ = _update_version_file()
      File "dvc/__init__.py", line 20, in _update_version_file
        from git import Repo
    ImportError: No module named git

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_1/dxrf7_f15sn4r01jvqvr5b6h0000gn/T/pip-req-build-NS8S38/
```

**Comment by shcheklein** [comment]
obvious workaround: `pip install gitpython` before running that command.

**Comment by efiop** [comment]
Added that to our doc along with a note/explanation https://dvc.org/doc/user-guide/development .
