### ISSUE TITLE
Exception is raised when adding the same data again

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#1581]
**DVC version:** 0.24.3

**Steps to reproduce:**

```
echo 'test' > foo
dvc add foo
dvc add foo
```

**Output:**
```Debug: UPDATE state_info SET count = 13 WHERE rowid = 1
Error: unexpected error - 'NoneType' object has no attribute 'dump'
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ivan/Projects/cookiecutter-data-science/dvc/.venv/lib/python2.7/site-packages/dvc/main.py", line 30, in main
    ret = cmd.run_cmd()
  File "/Users/ivan/Projects/cookiecutter-data-science/dvc/.venv/lib/python2.7/site-packages/dvc/command/base.py", line 50, in run_cmd
    return self.run()
  File "/Users/ivan/Projects/cookiecutter-data-science/dvc/.venv/lib/python2.7/site-packages/dvc/command/add.py", line 10, in run
    self.project.add(target, recursive=self.args.recursive)
  File "/Users/ivan/Projects/cookiecutter-data-science/dvc/.venv/lib/python2.7/site-packages/dvc/project.py", line 226, in add
    stage.dump()
AttributeError: 'NoneType' object has no attribute 'dump'
------------------------------------------------------------

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

**Comment by anotherbugmaster** [comment]
Hi guys, just encountered the same issue.

**Comment by efiop** [comment]
Hi @anotherbugmaster !

Fix is ready https://github.com/iterative/dvc/pull/1583 . Will merge and release it ASAP.

Thanks for the feedback :slightly_smiling_face:

**Comment by anotherbugmaster** [comment]
:rocket:
