### ISSUE TITLE
UNIQUE constraint failed: state.inode

### ISSUE THREAD

**Issue by gregfriedland** [iterative/dvc#1707]
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

Version is ```0.30.1+3c659b``` although I've also tried ```0.30.1```. Installed with pip3 on python 3.6.7

Hello,
I'm getting the above error message when running a fairly simple `dvc run`.  I had previously run `dvc cache dir /tmp/dvc_cache`. It seems to fail only on the `train` directory. If I copy that dir to another name (e.g. `dvc_test`), it does not fail anymore. Any ideas what's going on?

Debug output is below.

Brest,
Greg

```
dvc run -f test.dvc -d train  "python -c 'print()'"
Debug: PRAGMA user_version;
Debug: fetched: [(3,)]
Debug: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
Debug: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
Debug: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
Debug: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
Debug: PRAGMA user_version = 3;
Debug: Path /home/greg/src/atp/train inode 12123207390858225349
Debug: SELECT mtime, size, md5, timestamp from state WHERE inode=12123207390858225349
Debug: fetched: []
Debug: Path /home/greg/src/atp/train/Dockerfile inode 10698461848281723475
Debug: SELECT mtime, size, md5, timestamp from state WHERE inode=10698461848281723475
Debug: fetched: []
Debug: INSERT INTO state(inode, mtime, size, md5, timestamp) VALUES (-1475089811426947668, "1552167285616000000", "318", "ad609def7b88b8145a8e74c6cb622597", "1552172098641832448")
Debug: SELECT count from state_info WHERE rowid=1
Debug: fetched: [(53,)]
Debug: UPDATE state_info SET count = 53 WHERE rowid = 1
Debug: Path /tmp/dvc_cache inode 519743
Debug: INSERT OR REPLACE INTO state(inode, size, mtime, timestamp, md5) VALUES (519743, "22099", "1552171956826519296", "1552172098646104832", "")
Error: unexpected error - UNIQUE constraint failed: state.inode
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/main.py", line 32, in main
    ret = cmd.run_cmd()
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/command/base.py", line 53, in run_cmd
    return self.run()
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/command/run.py", line 45, in run
    no_commit=self.args.no_commit,
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/repo/run.py", line 48, in run
    remove_outs=remove_outs,
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/stage.py", line 462, in create
    if not ignore_build_cache and stage.is_cached:
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/stage.py", line 366, in is_cached
    dep.save()
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/output/local.py", line 99, in save
    self.info = self.remote.save_info(self.path_info)
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/remote/local.py", line 451, in save_info
    return {self.PARAM_CHECKSUM: self.state.update(path_info["path"])}
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 431, in update
    return self._do_update(path, known_checksum)[0]
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 320, in _do_update
    path, actual_inode, actual_mtime, actual_size, known_checksum
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 391, in _insert_new_state_record
    md5, info = self._collect(path)
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 114, in _collect
    return self.repo.cache.local.collect_dir_cache(path)
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/remote/local.py", line 226, in collect_dir_cache
    md5 = self.state.update(path)
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 431, in update
    return self._do_update(path, known_checksum)[0]
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 320, in _do_update
    path, actual_inode, actual_mtime, actual_size, known_checksum
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 403, in _insert_new_state_record
    current_timestamp(),
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 139, in _execute
    return self.cursor.execute(cmd)
sqlite3.IntegrityError: UNIQUE constraint failed: state.inode
------------------------------------------------------------
```

**Comment by shcheklein** [comment]
@gregfriedland hi, do you have an existing DVC stage file `test.dvc` (when `dvc run` fails)? do you mind sharing it with us, please?

**Comment by shcheklein** [comment]
also, could you run please `ls -la ./train/`?

**Comment by shcheklein** [comment]
I'm just wondering why is it trying to insert a checksum for the cache dir itself `Path /tmp/dvc_cache inode 519743`.

**Comment by shcheklein** [comment]
I think the bug itself with the failing UNIQUE CONSTRAINT is that in `get_state_record_for_inode` we don't aplly `self._to_sqlite(inode)` before running the check. @efiop can confirm that. But even with that I don't quite understand what's happening here. Would be great if you could share a sequence of steps to reproduce it from the very beginning.

**Comment by gregfriedland** [comment]
Thanks for your reply.

To answer your questions:
1. No, there is no existing `test.dvc`
2. There was nothing of note in that directory. I can't share the contents, but it's all regular files plus `.` and `..`
3. Sure, I was able to reproduce it:
`dvc destroy`
`dvc init`
`dvc run --remove-outs --overwrite-dvcfile  -f test.dvc -d train "python -c 'print()'"`
no issues.
`dvc run --remove-outs --overwrite-dvcfile  -f test.dvc -d train  "python -c 'print()'"`
fails again with logs:
```
Debug: PRAGMA user_version;
Debug: fetched: [(3,)]
Debug: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
Debug: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
Debug: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
Debug: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
Debug: PRAGMA user_version = 3;
Warning: Build cache is ignored when using --remove-outs.
Debug: SELECT count from state_info WHERE rowid=1
Debug: fetched: [(17,)]
Debug: UPDATE state_info SET count = 17 WHERE rowid = 1
Debug: Path /home/greg/src/atp/.dvc/cache inode 9570647174405735397
Debug: INSERT OR REPLACE INTO state(inode, size, mtime, timestamp, md5) VALUES (-347275137550959590, "19510", "1552193541334000128", "1552193625560392960", "")
Debug: PRAGMA user_version;
Debug: fetched: [(3,)]
Debug: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
Debug: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
Debug: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
Debug: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
Debug: PRAGMA user_version = 3;
Running command:
	python -c 'print()'
Debug: Computed stage 'test.dvc' md5: '9a408e6705937b95d1f6b21f63ad24ed'

Debug: Path /home/greg/src/atp/train inode 12123207390858225349
Debug: SELECT mtime, size, md5, timestamp from state WHERE inode=12123207390858225349
Debug: fetched: []
Debug: Path /home/greg/src/atp/train/Dockerfile inode 10698461848281723475
Debug: SELECT mtime, size, md5, timestamp from state WHERE inode=10698461848281723475
Debug: fetched: []
Debug: INSERT INTO state(inode, mtime, size, md5, timestamp) VALUES (-1475089811426947668, "1552167285616000000", "318", "ad609def7b88b8145a8e74c6cb622597", "1552193631371008256")
Debug: SELECT count from state_info WHERE rowid=1
Debug: fetched: [(17,)]
Debug: UPDATE state_info SET count = 17 WHERE rowid = 1
Debug: Path /home/greg/src/atp/.dvc/cache inode 9570647174405735397
Debug: INSERT OR REPLACE INTO state(inode, size, mtime, timestamp, md5) VALUES (-347275137550959590, "19510", "1552193541334000128", "1552193631382847488", "")
Error: unexpected error - UNIQUE constraint failed: state.inode
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/main.py", line 32, in main
    ret = cmd.run_cmd()
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/command/base.py", line 53, in run_cmd
    return self.run()
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/command/run.py", line 45, in run
    no_commit=self.args.no_commit,
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/repo/run.py", line 59, in run
    stage.run(no_commit=no_commit)
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/stage.py", line 724, in run
    self.save()
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/stage.py", line 582, in save
    dep.save()
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/output/local.py", line 99, in save
    self.info = self.remote.save_info(self.path_info)
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/remote/local.py", line 451, in save_info
    return {self.PARAM_CHECKSUM: self.state.update(path_info["path"])}
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 431, in update
    return self._do_update(path, known_checksum)[0]
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 320, in _do_update
    path, actual_inode, actual_mtime, actual_size, known_checksum
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 391, in _insert_new_state_record
    md5, info = self._collect(path)
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 114, in _collect
    return self.repo.cache.local.collect_dir_cache(path)
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/remote/local.py", line 226, in collect_dir_cache
    md5 = self.state.update(path)
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 431, in update
    return self._do_update(path, known_checksum)[0]
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 320, in _do_update
    path, actual_inode, actual_mtime, actual_size, known_checksum
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 403, in _insert_new_state_record
    current_timestamp(),
  File "/home/greg/.virtualenv/dvc/lib/python3.6/site-packages/dvc/state.py", line 139, in _execute
    return self.cursor.execute(cmd)
sqlite3.IntegrityError: UNIQUE constraint failed: state.inode
------------------------------------------------------------
```

I have a workaround so it's not urgent for me at the moment, but happy to try other things if you like.

**Comment by efiop** [comment]
@shcheklein Yep, that is precisely the cause. Great catch!
