### ISSUE TITLE
tests: python -m tests is not working on Python 2.7

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#1748]
I use python2 as in my development environment (to maintain compatibility with every feature)

```bash
ERROR: usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: -n=4 --timeout=600 --timeout_method=thread --cov=dvc
  inifile: None
  rootdir: /home/mroutis/src/iterative/dvc

Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mroutis/src/iterative/dvc/tests/__main__.py", line 24, in <module>
    check_call(cmd, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'py.test -v -n=4 --timeout=600 --timeout_method=thread --cov=dvc  ' returned non-zero exit status 4
```

**Comment by mroutis** [comment]
My bad, need to run `pip install -r tests/requirements.txt` again to have the following plugins:

```
setuptools registered plugins:
  pytest-xdist-1.26.1 at /home/mroutis/src/iterative/dvc/.venv3/lib/python3.7/site-packages/xdist/plugin.py
  pytest-xdist-1.26.1 at /home/mroutis/src/iterative/dvc/.venv3/lib/python3.7/site-packages/xdist/looponfail.py
  pytest-timeout-1.3.3 at /home/mroutis/src/iterative/dvc/.venv3/lib/python3.7/site-packages/pytest_timeout.py
  pytest-forked-1.0.2 at /home/mroutis/src/iterative/dvc/.venv3/lib/python3.7/site-packages/pytest_forked/__init__.py
  pytest-cov-2.6.1 at /home/mroutis/src/iterative/dvc/.venv3/lib/python3.7/site-packages/pytest_cov/plugin.py
  flaky-3.5.3 at /home/mroutis/src/iterative/dvc/.venv3/lib/python3.7/site-packages/flaky/flaky_pytest_plugin.py
```
