### ISSUE TITLE
dvc: handle error for unsupported external deps/outs

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#1755]
See https://discordapp.com/channels/485586884165107732/485596304961962003/557935811761537044 . I.e., when importing from unsupported scheme (e.g. azure), user gets
```
Traceback (most recent call last):                                              
  File "/usr/lib/python3.5/site-packages/dvc/main.py", line 32, in main         
    ret = cmd.run_cmd()                                                         
  File "/usr/lib/python3.5/site-packages/dvc/command/base.py", line 53, in run_cmd
    return self.run()                                                           
  File "/usr/lib/python3.5/site-packages/dvc/command/imp.py", line 18, in run   
    self.repo.imp(self.args.url, out, self.args.resume)                         
  File "/usr/lib/python3.5/site-packages/dvc/scm/__init__.py", line 39, in run  
    raise e                                                                     
  File "/usr/lib/python3.5/site-packages/dvc/scm/__init__.py", line 33, in run  
    result = method(*args, **kw)                                                
  File "/usr/lib/python3.5/site-packages/dvc/repo/imp.py", line 9, in imp       
    stage = Stage.create(repo=self, cmd=None, deps=[url], outs=[out])           
  File "/usr/lib/python3.5/site-packages/dvc/stage.py", line 434, in create     
    stage.deps = dependency.loads_from(stage, deps)                             
  File "/usr/lib/python3.5/site-packages/dvc/dependency/__init__.py", line 73, in loads_from
    ret.append(_get(stage, s, {}))                                              
  File "/usr/lib/python3.5/site-packages/dvc/dependency/__init__.py", line 54, in _get
    return DEP_MAP[remote.scheme](stage, p, info, remote=remote)                
KeyError: 'azure'                                                               
```

which is a bad way to handle this error.

**Comment by efiop** [comment]
No longer able to reproduce. We've changed the way we handle deps a while ago, so this issue was mitigated.
