### ISSUE TITLE
ERROR: failed to push data to the cloud - [Errno 13] Permission denied

### ISSUE THREAD

**Issue by jacopo-chevallard** [iterative/dvc#2023]
Hi, first of all, thanks for this great piece of software ! :-) 

I'm having troubles in pushing to a remote via SSH, I think that the problem is related to a confusion between ssh password and key passphrase, but I'm unable to sort it out... I'm on a Mac OS 10.13.6, using dvc version 0.40.2.

My ``.dvc/config`` file contains 
```
['remote "PULL_FTP"']
url = https://neogal.iap.fr/github.com/jacopo-chevallard/JAGUAR_Euclid
['remote "PUSH_SSH"']
url = ssh://chevalla@neogal.iap.fr/mnt/shares/public/github.com/jacopo-chevallard/JAGUAR_Euclid
ask_password = true
```

and when running the command ``dvc push -v -r PUSH_SSH`` I get the following error
```
DEBUG: PRAGMA user_version;
DEBUG: fetched: [(3,)]
DEBUG: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
DEBUG: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
DEBUG: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
DEBUG: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
DEBUG: PRAGMA user_version = 3;
Preparing to upload data to 'ssh://chevalla@neogal.iap.fr/mnt/shares/public/github.com/jacopo-chevallard/JAGUAR_Euclid'
Preparing to collect status from ssh://chevalla@neogal.iap.fr/mnt/shares/public/github.com/jacopo-chevallard/JAGUAR_Euclid
[#########                     ] 30% Collecting information
DEBUG: Path /Users/jchevall/Coding/JAGUAR_Euclid/.dvc/cache/27/bee7257c5514b96caa86074d671ad1 inode 29562460

DEBUG: SELECT mtime, size, md5, timestamp from state WHERE inode=29562460

DEBUG: fetched: [(u'1555413702692534272', u'193688706', u'27bee7257c5514b96caa86074d671ad1', u'1558362311073005056')]

DEBUG: UPDATE state SET timestamp = "1558362582820764160" WHERE inode = 29562460

DEBUG: cache '.dvc/cache/27/bee7257c5514b96caa86074d671ad1' expected '27bee7257c5514b96caa86074d671ad1' actual '27bee7257c5514b96caa86074d671ad1'
[############                  ] 40% Collecting information
DEBUG: Establishing ssh connection with 'neogal.iap.fr' through port '22' as user 'chevalla'

Enter a private key passphrase or a password for host 'neogal.iap.fr' port '22' user 'chevalla':


DEBUG: SELECT count from state_info WHERE rowid=1

DEBUG: fetched: [(2,)]

DEBUG: UPDATE state_info SET count = 2 WHERE rowid = 1

DEBUG: Path /Users/jchevall/Coding/JAGUAR_Euclid/.dvc/cache inode 30780665

DEBUG: INSERT OR REPLACE INTO state(inode, size, mtime, timestamp, md5) VALUES (30780665, "193688898", "1558360345291680512", "1558362586846743040", "")

ERROR: failed to push data to the cloud - [Errno 13] Permission denied: '/Users/jchevall/.ssh/github_rsa'
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/command/data_sync.py", line 66, in do_run
  File "dvc/repo/push.py", line 27, in push
  File "dvc/data_cloud.py", line 136, in push
  File "dvc/remote/local/__init__.py", line 486, in push
  File "dvc/remote/local/__init__.py", line 461, in _process
  File "dvc/remote/local/__init__.py", line 371, in status
  File "dvc/remote/base.py", line 559, in cache_exists
  File "dvc/remote/base.py", line 482, in all
  File "dvc/remote/ssh/__init__.py", line 246, in list_cache_paths
  File "dvc/remote/ssh/__init__.py", line 128, in ssh
  File "dvc/remote/ssh/connection.py", line 54, in __init__
  File "site-packages/paramiko/client.py", line 437, in connect
  File "site-packages/paramiko/client.py", line 662, in _auth
  File "site-packages/paramiko/client.py", line 571, in _key_from_filepath
  File "site-packages/paramiko/pkey.py", line 206, in from_private_key_file
  File "site-packages/paramiko/rsakey.py", line 55, in __init__
  File "site-packages/paramiko/rsakey.py", line 175, in _from_private_key_file
  File "site-packages/paramiko/pkey.py", line 278, in _read_private_key_file
IOError: [Errno 13] Permission denied: '/Users/jchevall/.ssh/github_rsa'
------------------------------------------------------------
```
I can use the same password to login on the server, while from the output above it looks like dvc is reading some ssh key... Any idea on how to fix this?

**Comment by efiop** [comment]
Hi @jacopo-chevallard !

Could you please show us:
```
ls -la /Users/jchevall/.ssh/github_rsa
```
I suspect you simply have bad permissions set on that key file. Perms should look something like:
```
-rw------- 1 efiop efiop
```

**Comment by jacopo-chevallard** [comment]
Permissions seem ok 
```
-rw-------  1 root  staff
```

**Comment by efiop** [comment]
@jacopo-chevallard Well, not really :slightly_smiling_face: Those permissions mean that only root has read and write access. And I don't think you are running from root :slightly_smiling_face: Try chowning that file to your user.
