### ISSUE TITLE
Unable to run tests as per documentations page

### ISSUE THREAD

**Issue by J0** [iterative/dvc#2097]
I'm currently using zsh and mac osx mojave

I am trying to run tests for a PR that I just opened. I created a fresh fork of DVC.
As per the [documentation page](https://dvc.org/doc/user-guide/contributing#development-environment) I ran

```
cd dvc
virtualenv --python python3 .env
source .env/bin/activate
export DVC_HOME=/Users/joel/Desktop/projects/dvc
export PATH=$PATH:$DVC_HOME/bin
```
I then ran `pip install -e .[all,tests]` but this produced the following error: 
`zsh: no matches found: .[all,tests]`
so I directly ran `pip install -e.`

Unfortunately, when I run `python -m tests`
I get the following error:

```
ImportError while loading conftest '/Users/joel/Desktop/projects/dvc/tests/conftest.py'.
tests/conftest.py:2: in <module>
    import mockssh
E   ModuleNotFoundError: No module named 'mockssh'
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/joel/Desktop/projects/dvc/tests/__main__.py", line 20, in <module>
    check_call(cmd, shell=True)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'py.test -v -n=4 --timeout=600 --timeout_method=thread --log-level=debug --cov=dvc  --durations=0' returned non-zero exit status 4.
```
I consulted @dmpetrov but I was unable to resolve this. Does anyone have any suggestions as to how I might get around this?

Thanks!

**Comment by shcheklein** [comment]
@J0 can you try to escape [ and ] with \ in the `pip install ...` command?
