### ISSUE TITLE
Error with "dvc pull" on Windows when local cache is not on the same drive as git repo

### ISSUE THREAD

**Issue by sremm** [iterative/dvc#2119]
**Setup Info**
DVC version: 0.41.3                                                                                                                                  
Python version: 3.6.7                                                                                                                                
Platform: Windows-10-10.0.16299-SP0      
Installed with pip

A problem tightly related to [Issue 1976](https://github.com/iterative/dvc/issues/1976)

I have the local dvc cache on drive F:, but the source code is on drive C:.

When calling "dvc pull" in the repo I'm greeted with the following error.
```
ERROR: failed to pull data from the cloud - path is on mount 'F:', start on mount 'C:'                                                                                                                                             
Traceback (most recent call last):                                                                                                                    
File "c:\users\srg\appdata\local\continuum\anaconda3\envs\tf-keras\lib\site-packages\dvc\command\data_sync.py", line 46, in 
   do_run recursive=self.args.recursive,                                                                                                                    
File "c:\users\srg\appdata\local\continuum\anaconda3\envs\tf-keras\lib\site-packages\dvc\repo\pull.py", line 24, in pull                               
   recursive=recursive,                                                                                                                               
File "c:\users\srg\appdata\local\continuum\anaconda3\envs\tf-keras\lib\site-packages\dvc\repo\fetch.py", line 27, in fetch                             
   used, jobs, remote=remote, show_checksums=show_checksums                                                                                          
File "c:\users\srg\appdata\local\continuum\anaconda3\envs\tf-keras\lib\site-packages\dvc\data_cloud.py", line 144, in pull                                  
   show_checksums=show_checksums,                                                                                                                     
File "c:\users\srg\appdata\local\continuum\anaconda3\envs\tf-keras\lib\site-packages\dvc\remote\local\__init__.py", line 493, in pull                  
   download=True,                                                                                                                                     
File "c:\users\srg\appdata\local\continuum\anaconda3\envs\tf-keras\lib\site-packages\dvc\remote\local\__init__.py", line 459, in _process             
    download=download,                                                                                                                                 
File "c:\users\srg\appdata\local\continuum\anaconda3\envs\tf-keras\lib\site-packages\dvc\remote\local\__init__.py", line 358, in status        
     local_exists = self.cache_exists(md5s)                                                                                                          
File "c:\users\srg\appdata\local\continuum\anaconda3\envs\tf-keras\lib\site-packages\dvc\remote\local\__init__.py", line 232, in cache_exists       
   return list(filter(lambda md5: not self.changed_cache_file(md5), md5s))                                                                           
 File "c:\users\srg\appdata\local\continuum\anaconda3\envs\tf-keras\lib\site-packages\dvc\remote\local\__init__.py", line 232, in <lambda>           
   return list(filter(lambda md5: not self.changed_cache_file(md5), md5s))                                                                            
File "c:\users\srg\appdata\local\continuum\anaconda3\envs\tf-keras\lib\site-packages\dvc\remote\base.py", line 518, in changed_cache_file           
   actual = self.get_checksum(cache_info)                                                                                                            
 File "c:\users\srg\appdata\local\continuum\anaconda3\envs\tf-keras\lib\site-packages\dvc\remote\base.py", line 275, in get_checksum                 
   checksum = self.get_file_checksum(path_info)                                                                                                       
File "c:\users\srg\appdata\local\continuum\anaconda3\envs\tf-keras\lib\site-packages\dvc\remote\local\__init__.py", line 208, in get_file_checksum  
   return file_md5(path_info.path)[0]                                                                                                                 
File "c:\users\srg\appdata\local\continuum\anaconda3\envs\tf-keras\lib\site-packages\dvc\utils\__init__.py", line 48, in file_md5                      logger.info(msg.format(os.path.relpath(fname)))                                                                                                    
File "c:\users\srg\appdata\local\continuum\anaconda3\envs\tf-keras\lib\ntpath.py", line 584, in relpath                                             
   path_drive, start_drive))                                                                                                                        ValueError: path is on mount 'F:', start on mount 'C:'
```

**Comment by pared** [comment]
I am unable to reproduce,
@sremm  would it be a problem to show me your `.dvc/config` ?
Also, you have been pulling after modification, or deletion of file in `C:` repository?
