### ISSUE TITLE
timeout pushing a file of size 52mb to s3

### ISSUE THREAD

**Issue by bayethiernodiop** [iterative/dvc#2326]
dvc version : 0.50.1
os : ubuntu
it stops randomly at some percentage when pushing with this error :
```
ERROR: failed to upload '.dvc/cache/3a/a27ed52c92faca305a2c67f3283e25' to 's3://justice-ai/3a/a27ed52c92faca305a2c67f3283e25' - Could not connect to the endpoint URL: "https://***-ai.s3.amazonaws.com/3a/a27ed52c92faca305a2c67f3283e25?uploadId=ZQaDCo7YSdDU_nLfZh6_WefPkg5Rd3XB4wLmdZqg1R1izOkMlP72cmnphJR0c4j1vPXYT06Oeh4kYnzJxTab7et1vg0n22wVBD0jzKwU6dqHTWPBpFZznikXqooHl9_5&partNumber=1"
------------------------------------------------------------
Traceback (most recent call last):
  File "site-packages/urllib3/connection.py", line 160, in _new_conn
  File "site-packages/urllib3/util/connection.py", line 57, in create_connection
  File "socket.py", line 748, in getaddrinfo
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/botocore/httpsession.py", line 262, in send
  File "site-packages/urllib3/connectionpool.py", line 641, in urlopen
  File "site-packages/urllib3/util/retry.py", line 344, in increment
  File "site-packages/urllib3/packages/six.py", line 686, in reraise
  File "site-packages/urllib3/connectionpool.py", line 603, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 344, in _make_request
  File "site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
  File "site-packages/urllib3/connection.py", line 316, in connect
  File "site-packages/urllib3/connection.py", line 169, in _new_conn
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7f9ba220b2b0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc/remote/base.py", line 417, in upload
  File "dvc/remote/s3.py", line 254, in _upload
  File "site-packages/boto3/s3/inject.py", line 131, in upload_file
  File "site-packages/boto3/s3/transfer.py", line 279, in upload_file
  File "site-packages/s3transfer/futures.py", line 106, in result
  File "site-packages/s3transfer/futures.py", line 265, in result
  File "site-packages/botocore/httpsession.py", line 262, in send
  File "site-packages/urllib3/connectionpool.py", line 603, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 355, in _make_request
  File "http/client.py", line 1229, in request
  File "site-packages/botocore/awsrequest.py", line 125, in _send_request
  File "http/client.py", line 1275, in _send_request
  File "http/client.py", line 1224, in endheaders
  File "site-packages/botocore/awsrequest.py", line 159, in _send_output
  File "site-packages/botocore/awsrequest.py", line 202, in _handle_expect_response
  File "site-packages/botocore/awsrequest.py", line 229, in _send_message_body
  File "site-packages/botocore/awsrequest.py", line 236, in send
  File "http/client.py", line 969, in send
  File "site-packages/s3transfer/utils.py", line 474, in read
  File "site-packages/s3transfer/upload.py", line 85, in read
  File "site-packages/s3transfer/tasks.py", line 126, in __call__
  File "site-packages/s3transfer/tasks.py", line 150, in _execute_main
  File "site-packages/s3transfer/upload.py", line 722, in _main
  File "site-packages/botocore/client.py", line 357, in _api_call
  File "site-packages/botocore/client.py", line 648, in _make_api_call
  File "site-packages/botocore/client.py", line 667, in _make_request
  File "site-packages/botocore/endpoint.py", line 102, in make_request
  File "site-packages/botocore/endpoint.py", line 137, in _send_request
  File "site-packages/botocore/endpoint.py", line 231, in _needs_retry
  File "site-packages/botocore/hooks.py", line 356, in emit
  File "site-packages/botocore/hooks.py", line 228, in emit
  File "site-packages/botocore/hooks.py", line 211, in _emit
  File "site-packages/botocore/retryhandler.py", line 183, in __call__
  File "site-packages/botocore/retryhandler.py", line 251, in __call__
  File "site-packages/botocore/retryhandler.py", line 277, in _should_retry
  File "site-packages/botocore/retryhandler.py", line 317, in __call__
  File "site-packages/botocore/retryhandler.py", line 223, in __call__
  File "site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
  File "site-packages/botocore/endpoint.py", line 200, in _do_get_response
  File "site-packages/botocore/endpoint.py", line 244, in _send
  File "site-packages/botocore/httpsession.py", line 282, in send
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://***.s3.amazonaws.com/3a/a27ed52c92faca305a2c67f3283e25?uploadId=ZQaDCo7YSdDU_nLfZh6_WefPkg5Rd3XB4wLmdZqg1R1izOkMlP72cmnphJR0c4j1vPXYT06Oeh4kYnzJxTab7et1vg0n22wVBD0jzKwU6dqHTWPBpFZznikXqooHl9_5&partNumber=1"
------------------------------------------------------------

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!

DEBUG: SELECT count from state_info WHERE rowid=?

DEBUG: fetched: [(1099,)]

DEBUG: UPDATE state_info SET count = ? WHERE rowid = ?

ERROR: failed to push data to the cloud - 1 file(s) failed to upload
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/command/data_sync.py", line 67, in do_run
  File "dvc/repo/push.py", line 27, in push
  File "dvc/data_cloud.py", line 124, in push
  File "dvc/remote/local/__init__.py", line 426, in push
  File "dvc/remote/local/__init__.py", line 415, in _process
dvc.exceptions.DvcException: 1 file(s) failed to upload
------------------------------------------------------------
```

**Comment by efiop** [comment]
Hi @bayethiernodiop ! Could you please upgrade and try the new dvc version? Also, are you on some unstable network?

**Comment by bayethiernodiop** [comment]
Thanks @efiop for your answer, i would say that my upload speed is not that fast even though it's stable. but today looks like the push is going well. thanks
