### ISSUE TITLE
repro -s fails in dvc-0.53.2

### ISSUE THREAD

**Issue by prihoda** [iterative/dvc#2354]
In dvc version `0.53.2`, command `dvc repro -sf stage.dvc` fails on any stage:

```
(base) ➜  dvc-example git:(master) ✗ dvc repro -sf test.txt.dvc --verbose
DEBUG: Trying to spawn '['/Users/prihodad/anaconda3/bin/python', '-m', 'dvc', 'daemon', '-q', 'updater']'
DEBUG: Spawned '['/Users/prihodad/anaconda3/bin/python', '-m', 'dvc', 'daemon', '-q', 'updater']'
DEBUG: PRAGMA user_version;
DEBUG: fetched: [(3,)]
DEBUG: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
DEBUG: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
DEBUG: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
DEBUG: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
DEBUG: PRAGMA user_version = 3;
Reproducing 'test.txt.dvc'
DEBUG: SELECT count from state_info WHERE rowid=?
DEBUG: fetched: [(8,)]
DEBUG: UPDATE state_info SET count = ? WHERE rowid = ?
ERROR: unexpected error - run() got an unexpected keyword argument 'ignore_build_cache'
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/prihodad/anaconda3/lib/python3.6/site-packages/dvc/main.py", line 40, in main
    ret = cmd.run_cmd()
  File "/Users/prihodad/anaconda3/lib/python3.6/site-packages/dvc/command/base.py", line 63, in run_cmd
    return self.run()
  File "/Users/prihodad/anaconda3/lib/python3.6/site-packages/dvc/command/repro.py", line 42, in run
    recursive=self.args.recursive,
  File "/Users/prihodad/anaconda3/lib/python3.6/site-packages/dvc/repo/scm_context.py", line 4, in run
    result = method(repo, *args, **kw)
  File "/Users/prihodad/anaconda3/lib/python3.6/site-packages/dvc/repo/reproduce.py", line 80, in reproduce
    stages = _reproduce(self, target, **kwargs)
  File "/Users/prihodad/anaconda3/lib/python3.6/site-packages/dvc/repo/reproduce.py", line 96, in _reproduce
    ret = _reproduce_stage(stages, node, **kwargs)
  File "/Users/prihodad/anaconda3/lib/python3.6/site-packages/dvc/repo/reproduce.py", line 22, in _reproduce_stage
    stage = stage.reproduce(**kwargs)
  File "/Users/prihodad/anaconda3/lib/python3.6/site-packages/dvc/stage.py", line 331, in reproduce
    self.run(**kwargs)
TypeError: run() got an unexpected keyword argument 'ignore_build_cache'
------------------------------------------------------------
```

**Comment by prihoda** [comment]
Reproducing:

```
mkdir dvc-example
cd dvc-example
git init
pip install dvc==0.53.2
dvc init
dvc run -o test.txt touch test.txt
dvc repro -sf test.txt
```

**Comment by efiop** [comment]
@prihoda Thank you so much for reporting this! Preparing a fix right now.

**Comment by efiop** [comment]
@prihoda FYI: 0.54.0 is out. Please upgrade :)
