### ISSUE TITLE
fetch/pull: download cache for imported data from external repos

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#2423]
```
#!/bin/bash                                                          
                                                                     
set -e                                                               
set -x                                                               
                                                                     
rm -rf myrepo                                                        
mkdir myrepo                                                         
cd myrepo                                                            
git init                                                             
dvc init                                                             
                                                                     
dvc import https://github.com/iterative/dvc scripts/innosetup/dvc.ico
                                                                     
rm -rf .dvc/cache                                                    
rm -f dvc.ico                                                        
                                                                     
dvc pull                                                             
                                                                     
ls -la dvc.ico                                                       
```

Currently, the only way to re-import is to run `dvc repro dvc.ico.dvc`, which is inconvenient.

**Comment by efiop** [comment]
By default external repo imports are not cached locally, unlike `import-url`s which are. Though it might make sense to trigger non-cached `import-url`s too the same way for convenience.

**Comment by shcheklein** [comment]
`import-url` feels different to me. They are way more "external" in a sense that you usually have less control, can't expect them to be reliable, etc. Thus my intuition suggests that we should keep caching them. 

Remember we had a discussion about the `dvc install` - not the one we have now, but the one which can `install` "external" dependencies in a way `pip install` is doing that? It looks like we are missing something like this, right?

May be we can modify `dvc pull` to handle this?

**Comment by Suor** [comment]
I don't see any problem running `dvc repro`. And don't see anything related to `dvc install`.

I would say we should cache both, to be safe. If people don't want to do that we may provide an option, to import command and dvc file, again no need to resurrect `dvc install`.

**Comment by Suor** [comment]
@efiop what is better way than `dvc repro` anyway?

**Comment by dashohoxha** [comment]
> Currently, the only way to re-import is to run dvc repro dvc.ico.dvc, which is inconvenient.

I am confused. The man page (https://dvc.org/doc/commands-reference/import) says:

> Note that import stages are considered always "locked", meaning that if you run dvc repro, they won't be updated. Use dvc update on them to update the downloaded data artifact from the external DVC repo.

Is the man page outdated?

In general I find the commands `import`/`import-url`/`get`/`get-url`/`update` confusing and difficult to understand.

**Comment by pared** [comment]
@dashohoxha 
man page does not seem to be outdated. I can `dvc update dvc.ico.dvc`.

**Comment by pared** [comment]
That doesn't change the fact that `pull` should work in this case.

**Comment by shcheklein** [comment]
@Suor you are potentially duplicating a lot of data by saving imports to remote. I would not do this.

I don't like running `dvc repro` to pull data - it's a broken UI. For example, `dvc repro` is not checkouting data for regular DVC-files as far as I remember. Why would I expect it to be doing it in this case? Will I have to read the docs about repro if I have a singe import and I need to pull the data for it?

There are commands that are specifically made to get you data to the workspace - pull, checkout. Don't see any reasons to not use them in this case either. May be we can introduce a special option to keep the granularity option.

**Comment by shcheklein** [comment]
@dashohoxha disregard import-url and get-url for now. What do you find confusing about `import`, `get` and `update`? Any suggestions on how can we improve it? Please, don't answer here. It's better to create a ticket on iterative/dvc.org to discuss and incorporate improvements.

**Comment by mroutis** [comment]
@efiop , in your example, I can't `dvc repro` to pull the data:

```
❯ dvc repro -v dvc.ico.dvc
DEBUG: PRAGMA user_version;
DEBUG: fetched: [(3,)]
DEBUG: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT
NOT NULL)
DEBUG: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
DEBUG: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
DEBUG: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
DEBUG: PRAGMA user_version = 3;
WARNING: DVC-file 'dvc.ico.dvc' is locked. Its dependencies are not going to be reproduced.
DEBUG: Computed stage 'dvc.ico.dvc' md5: 'c2a2f172fbda50e9f5d9ad31a70df21e'
DEBUG: cache '.dvc/cache/90/104d9e83cfb825cf45507e90aadd27' expected '90104d9e83cfb825cf45507e90aadd27' actual 'None'
WARNING: Output 'dvc.ico' of 'dvc.ico.dvc' changed because it is 'not in cache'
WARNING: Stage 'dvc.ico.dvc' changed.
Verifying outputs in locked stage 'dvc.ico.dvc'
DEBUG: SELECT count from state_info WHERE rowid=?
DEBUG: fetched: [(2,)]
DEBUG: UPDATE state_info SET count = ? WHERE rowid = ?
ERROR: failed to reproduce 'dvc.ico.dvc': missing data source: dvc.ico
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mroutis/src/iterative/dvc/dvc/repo/reproduce.py", line 161, in _reproduce_stages
    ret = _reproduce_stage(stages, n, **kwargs)
  File "/home/mroutis/src/iterative/dvc/dvc/repo/reproduce.py", line 22, in _reproduce_stage
    stage = stage.reproduce(**kwargs)
  File "/home/mroutis/src/iterative/dvc/dvc/stage.py", line 337, in reproduce
    self.run(**kwargs)
  File "/home/mroutis/src/iterative/dvc/dvc/stage.py", line 831, in run
    self.check_missing_outputs()
  File "/home/mroutis/src/iterative/dvc/dvc/stage.py", line 872, in check_missing_outputs
    raise MissingDataSource(paths)
dvc.stage.MissingDataSource: missing data source: dvc.ico

Traceback (most recent call last):
  File "/home/mroutis/src/iterative/dvc/dvc/repo/reproduce.py", line 161, in _reproduce_stages
    ret = _reproduce_stage(stages, n, **kwargs)
  File "/home/mroutis/src/iterative/dvc/dvc/repo/reproduce.py", line 22, in _reproduce_stage
    stage = stage.reproduce(**kwargs)
  File "/home/mroutis/src/iterative/dvc/dvc/stage.py", line 337, in reproduce
    self.run(**kwargs)
  File "/home/mroutis/src/iterative/dvc/dvc/stage.py", line 831, in run
    self.check_missing_outputs()
  File "/home/mroutis/src/iterative/dvc/dvc/stage.py", line 872, in check_missing_outputs
    raise MissingDataSource(paths)
dvc.stage.MissingDataSource: missing data source: dvc.ico

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mroutis/src/iterative/dvc/dvc/command/repro.py", line 42, in run
    recursive=self.args.recursive,
  File "/home/mroutis/src/iterative/dvc/dvc/repo/scm_context.py", line 4, in run
    result = method(repo, *args, **kw)
  File "/home/mroutis/src/iterative/dvc/dvc/repo/reproduce.py", line 80, in reproduce
    stages = _reproduce(self, target, **kwargs)
  File "/home/mroutis/src/iterative/dvc/dvc/repo/reproduce.py", line 95, in _reproduce
    return _reproduce_stages(G, stages, node, **kwargs)
  File "/home/mroutis/src/iterative/dvc/dvc/repo/reproduce.py", line 173, in _reproduce_stages
    raise ReproductionError(stages[n].relpath, ex)
dvc.exceptions.ReproductionError: failed to reproduce 'dvc.ico.dvc'
------------------------------------------------------------

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!
```

Am I missing something?

**Comment by efiop** [comment]
@mroutis Yes, since then we've made it locked by default. You need to `dvc unlock` it first and then `dvc repro`.
