### ISSUE TITLE
dvc: any operation with progress bar fails with KeyError

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#2486]
On master branch.

Steps to reproduce:
- make a dvc repo
- make a dir with 101 file
- `dvc add` it

**Comment by Suor** [comment]
@casperdcl can you take a look?

**Comment by Suor** [comment]
Here is a stack trace:
```
Traceback (most recent call last):
  File "/home/suor/projects/dvc/dvc/main.py", line 40, in main
    ret = cmd.run_cmd()
  File "/home/suor/projects/dvc/dvc/command/base.py", line 63, in run_cmd
    return self.run()
  File "/home/suor/projects/dvc/dvc/command/add.py", line 24, in run
    fname=self.args.file,
  File "/home/suor/projects/dvc/dvc/repo/scm_context.py", line 4, in run
    result = method(repo, *args, **kw)
  File "/home/suor/projects/dvc/dvc/repo/add.py", line 34, in add
    stages = _create_stages(repo, targets, fname, no_commit)
  File "/home/suor/projects/dvc/dvc/repo/add.py", line 61, in _create_stages
    stage = Stage.create(repo, outs=[out], add=True, fname=fname)
  File "/home/suor/projects/dvc/dvc/stage.py", line 524, in create
    and stage.is_cached
  File "/home/suor/projects/dvc/dvc/stage.py", line 405, in is_cached
    if old._changed_outs():
  File "/home/suor/projects/dvc/dvc/stage.py", line 269, in _changed_outs
    status = out.status()
  File "/home/suor/projects/dvc/dvc/output/base.py", line 175, in status
    if self.checksum and self.use_cache and self.changed_cache():
  File "/home/suor/projects/dvc/dvc/output/base.py", line 172, in changed_cache
    return self.cache.changed_cache(self.checksum)
  File "/home/suor/projects/dvc/dvc/remote/base.py", line 679, in changed_cache
    return self._changed_dir_cache(checksum)
  File "/home/suor/projects/dvc/dvc/remote/base.py", line 674, in _changed_dir_cache
    self._update_unpacked_dir(checksum)
  File "/home/suor/projects/dvc/dvc/remote/local/__init__.py", line 512, in _update_unpacked_dir
    self._create_unpacked_dir(checksum, dir_info, unpacked_dir_info)
  File "/home/suor/projects/dvc/dvc/remote/local/__init__.py", line 521, in _create_unpacked_dir
    for entry in Tqdm(dir_info, desc="Creating unpacked dir", unit="file"):
  File "/home/suor/projects/dvc/dvc/progress.py", line 92, in __init__
    self.refresh()
  File "/home/suor/.virtualenvs/dvc/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1227, in refresh
    self.display()
  File "/home/suor/.virtualenvs/dvc/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1350, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/home/suor/.virtualenvs/dvc/lib/python3.7/site-packages/tqdm/_tqdm.py", line 996, in __repr__
    return self.format_meter(**self.format_dict)
  File "/home/suor/projects/dvc/dvc/progress.py", line 116, in format_dict
    ncols_desc = ncols - len(self.format_meter(ncols_desc=1, **d)) + 1
  File "/home/suor/.virtualenvs/dvc/lib/python3.7/site-packages/tqdm/_tqdm.py", line 419, in format_meter
    return bar_format.format(**format_dict)
KeyError: 'bar'
```

**Comment by Suor** [comment]
Updating `tqdm` helped, sorry).

**Comment by casperdcl** [comment]
```
dvc (master)$ pip install .
```

should've installed an appropriate version of `tqdm`, otherwise this is some sort of bug.
