### ISSUE TITLE
failed to push data to the cloud

### ISSUE THREAD

**Issue by amajidsinar** [iterative/dvc#2491]
Hi guys, I'm using dvc version 0.59.2 however for some reason I suddenly couldn't push to the remote. Here's the output 

```
DEBUG: PRAGMA user_version;
DEBUG: fetched: [(3,)]
DEBUG: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
DEBUG: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
DEBUG: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
DEBUG: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
DEBUG: PRAGMA user_version = 3;
DEBUG: Preparing to upload data to 'ssh://ai-nf@10.7.2.99/nodeflux/dvc_repo'
DEBUG: Preparing to collect status from ssh://ai-nf@10.7.2.99/nodeflux/dvc_repo
DEBUG: Collecting information from local cache...
DEBUG: Path .dvc/cache/07/b1553ef310b37e5a8c472c015de6d0 inode 3323910                                                                                                  
DEBUG: SELECT mtime, size, md5, timestamp from state WHERE inode=?                                                                                                      
DEBUG: fetched: [('1568278442584690688', '105107', '07b1553ef310b37e5a8c472c015de6d0', '1568280752658456832')]                                                          
DEBUG: UPDATE state SET timestamp = ? WHERE inode = ?                                                                                                                   
DEBUG: cache '.dvc/cache/07/b1553ef310b37e5a8c472c015de6d0' expected '07b1553ef310b37e5a8c472c015de6d0' actual '07b1553ef310b37e5a8c472c015de6d0'                       
DEBUG: Path .dvc/cache/8f/feb2e1abdec93c74d5dc5fa87387b1 inode 3323914                                                                                                  
DEBUG: SELECT mtime, size, md5, timestamp from state WHERE inode=?                                                                                                      
DEBUG: fetched: [('1568278444232690176', '27232', '8ffeb2e1abdec93c74d5dc5fa87387b1', '1568280752659387648')]                                                           
DEBUG: UPDATE state SET timestamp = ? WHERE inode = ?                                                                                                                   
DEBUG: cache '.dvc/cache/8f/feb2e1abdec93c74d5dc5fa87387b1' expected '8ffeb2e1abdec93c74d5dc5fa87387b1' actual '8ffeb2e1abdec93c74d5dc5fa87387b1'                       
DEBUG: Path .dvc/cache/c3/3b921dd4a45e04e75beda32f41a24d inode 3323907                                                                                                  
DEBUG: SELECT mtime, size, md5, timestamp from state WHERE inode=?                                                                                                      
DEBUG: fetched: [('1568278413796704768', '28390', 'c33b921dd4a45e04e75beda32f41a24d', '1568280752660283136')]                                                           
DEBUG: UPDATE state SET timestamp = ? WHERE inode = ?                                                                                                                   
DEBUG: cache '.dvc/cache/c3/3b921dd4a45e04e75beda32f41a24d' expected 'c33b921dd4a45e04e75beda32f41a24d' actual 'c33b921dd4a45e04e75beda32f41a24d'                       
DEBUG: Path .dvc/cache/fd/a6fd6c4345641f3e33b6f4086aaabc inode 3323908                                                                                                  
DEBUG: SELECT mtime, size, md5, timestamp from state WHERE inode=?                                                                                                      
DEBUG: fetched: [('1568278413800704768', '7358', 'fda6fd6c4345641f3e33b6f4086aaabc', '1568280752661145600')]                                                            
DEBUG: UPDATE state SET timestamp = ? WHERE inode = ?                                                                                                                   
DEBUG: cache '.dvc/cache/fd/a6fd6c4345641f3e33b6f4086aaabc' expected 'fda6fd6c4345641f3e33b6f4086aaabc' actual 'fda6fd6c4345641f3e33b6f4086aaabc'                       
DEBUG: Collecting information from remote cache...`

`
Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!
ERROR: failed to upload '.dvc/cache/c3/3b921dd4a45e04e75beda32f41a24d' to 'ssh://ai-nf@10.7.2.99/nodeflux/dvc_repo/c3/3b921dd4a45e04e75beda32f41a24d' - [Errno 13] Permission denied
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dvc/remote/base.py", line 447, in upload
    no_progress_bar=no_progress_bar,
  File "/usr/local/lib/python3.6/dist-packages/dvc/remote/ssh/__init__.py", line 205, in _upload
    no_progress_bar=no_progress_bar,
  File "/usr/local/lib/python3.6/dist-packages/dvc/remote/ssh/connection.py", line 183, in upload
    self.makedirs(posixpath.dirname(dest))
  File "/usr/local/lib/python3.6/dist-packages/dvc/remote/ssh/connection.py", line 94, in makedirs
    self.makedirs(head)
  File "/usr/local/lib/python3.6/dist-packages/dvc/remote/ssh/connection.py", line 94, in makedirs
    self.makedirs(head)
  File "/usr/local/lib/python3.6/dist-packages/dvc/remote/ssh/connection.py", line 98, in makedirs
    self.sftp.mkdir(path)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/sftp_client.py", line 460, in mkdir
    self._request(CMD_MKDIR, path, attr)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/sftp_client.py", line 813, in _request
    return self._read_response(num)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/sftp_client.py", line 865, in _read_response
    self._convert_status(msg)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/sftp_client.py", line 896, in _convert_status
    raise IOError(errno.EACCES, text)
PermissionError: [Errno 13] Permission denied
------------------------------------------------------------

Having any troubles?. Hit us up at https://dvc.org/support, we are always happy to help!
DEBUG: SELECT count from state_info WHERE rowid=?
DEBUG: fetched: [(11,)]
DEBUG: UPDATE state_info SET count = ? WHERE rowid = ?
ERROR: failed to push data to the cloud - 4 files failed to upload
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dvc/command/data_sync.py", line 50, in run
    recursive=self.args.recursive,
  File "/usr/local/lib/python3.6/dist-packages/dvc/repo/push.py", line 25, in push
    return self.cloud.push(used, jobs, remote=remote)
  File "/usr/local/lib/python3.6/dist-packages/dvc/data_cloud.py", line 88, in push
    show_checksums=show_checksums,
  File "/usr/local/lib/python3.6/dist-packages/dvc/remote/local/__init__.py", line 445, in push
    download=False,
  File "/usr/local/lib/python3.6/dist-packages/dvc/remote/local/__init__.py", line 434, in _process
    msg.format(fails, "download" if download else "upload")
dvc.exceptions.DvcException: 4 files failed to upload
```

Thanks a lot guys. I really appreciate it!!!

**Comment by efiop** [comment]
@pared Good point! Closing for now. @amajidsinar Please be sure to let us know if you have any problems. :slightly_smiling_face:
