### ISSUE TITLE
error upgrading cask

### ISSUE THREAD

**Issue by AlJohri** [iterative/dvc#2585]
I first ran just `brew cask upgrade` which was upgrading all my casks:

```
$ brew cask upgrade
==> Upgrading dvc
==> Satisfying dependencies
==> Downloading https://github.com/iterative/dvc/releases/download/0.61.2/dvc-0.
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> No SHA-256 checksum defined for Cask 'dvc', skipping verification.
==> Uninstalling packages:
com.iterative.dvc
Password:
cp -p /Users/johria/Library/Caches/Homebrew/downloads/dc9b270cb4019cd8249481328d01ed08912586c2c8bb9722f71cb3190e7a3242--dvc-0.61.2.pkg /usr/local/Caskroom/dvc/0.61.2/dvc-0.61.2.pkg
==> Running installer for dvc; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are i
installer: Package name is dvc-0.61.2
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing dvc-0.61.2…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%8.967266
installer:PHASE:Writing files…
installer:%13.758304
installer:PHASE:Writing files…
installer:%18.549343
installer:PHASE:Writing files…
installer:%40.109016
installer:PHASE:Writing files…
installer:%42.504535
installer:PHASE:Writing files…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 0.61.2 of Cask dvc
Error: Failure while executing; `/usr/bin/sudo -E -- env LOGNAME=johria USER=johria USERNAME=johria /usr/sbin/installer -pkg /usr/local/Caskroom/dvc/0.61.2/dvc-0.61.2.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is dvc-0.61.2
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing dvc-0.61.2…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%8.967266
installer:PHASE:Writing files…
installer:%13.758304
installer:PHASE:Writing files…
installer:%18.549343
installer:PHASE:Writing files…
installer:%40.109016
installer:PHASE:Writing files…
installer:%42.504535
installer:PHASE:Writing files…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:178:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:65:in `with_choices_file'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:214:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:205:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:103:in `upgrade_cask'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:49:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:47:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:47:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

Ran into the above error and then tried to upgrade DVC specifically:

```
$ brew cask upgrade dvc
==> Upgrading 1 outdated package:
iterative/dvc/dvc 0.59.2 -> 0.61.2
==> Upgrading dvc
==> Satisfying dependencies
==> Downloading https://github.com/iterative/dvc/releases/download/0.61.2/dvc-0.61.2.pkg
Already downloaded: /Users/johria/Library/Caches/Homebrew/downloads/dc9b270cb4019cd8249481328d01ed08912586c2c8bb9722f71cb3190e7a3242--dvc-0.61.2.pkg
==> No SHA-256 checksum defined for Cask 'dvc', skipping verification.
==> Uninstalling packages:
Error: No such file or directory @ rb_file_s_rename - (/usr/local/Caskroom/dvc/0.59.2, /usr/local/Caskroom/dvc/0.59.2.upgrading)
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:395:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:395:in `rename'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:395:in `backup'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:391:in `start_upgrade'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:96:in `upgrade_cask'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:49:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:47:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:47:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

Not sure what happened

**Comment by efiop** [comment]
Moved to the main dvc repository, since it is not homebrew-specific issue.

**Comment by efiop** [comment]
@AlJohri Releasing 0.62.0 right now, will be ready in an hour or so. Thanks again for reporting this! :slightly_smiling_face:
