### ISSUE TITLE
broken installation using: pip install dvc[ssh] 

### ISSUE THREAD

**Issue by JoshuaPostel** [iterative/dvc#2927]
**Please provide information about your setup**
dvc version 0.75.0
python 3.6.9
[GCC 8.3.0] on linux

Built with the following dockerfile:
```
from ubuntu:18.04

run apt-get update && apt-get install -y \
    python3.6 \
    python3-pip

run pip3 install dvc[ssh]
```

<details>
  <summary>Details of docker build Step 3/4</summary>

```
Step 3/4 : run pip3 install dvc[ssh]                                                                                                                                                                               
 ---> Running in f80af2bd27aa                                                                                                                                                                                      
Collecting dvc[ssh]                                                                                                                                                                                                
  Downloading https://files.pythonhosted.org/packages/1a/04/4543067396b8bea4c962ffcb34f38c8d2ce5c4c4c7142b6f3eb7449637fe/dvc-0.75.0-py2.py3-none-any.whl (289kB)                                                   
Collecting gitpython>=2.1.8 (from dvc[ssh])                                                                                                                                                                        
  Downloading https://files.pythonhosted.org/packages/20/8c/4543981439d23c4ff65b2e62dddd767ebc84a8e664a9b67e840d1e2730d3/GitPython-3.0.5-py3-none-any.whl (455kB)                                                  
Collecting jsonpath-ng>=1.4.3 (from dvc[ssh])                                                                                                                                                                      
  Downloading https://files.pythonhosted.org/packages/95/32/ab29fef829c129e5847b8241541bec858515af2bd57a845fad78efde25f5/jsonpath_ng-1.4.3-py2.py3-none-any.whl                                                    
Collecting inflect>=2.1.0 (from dvc[ssh])                                                                                                                                                                          
  Downloading https://files.pythonhosted.org/packages/2a/14/49a8afaaa66fb49cda8e60512f0fc07594232fb10ea6aa8995c069172cf6/inflect-3.0.2-py2.py3-none-any.whl                                                        
Collecting distro>=1.3.0 (from dvc[ssh])                                                                                                                                                                           
  Downloading https://files.pythonhosted.org/packages/ea/35/82f79b92fa4d937146c660a6482cee4f3dfa1f97ff3d2a6f3ecba33e712e/distro-1.4.0-py2.py3-none-any.whl                                                         
Collecting appdirs>=1.4.3 (from dvc[ssh])                                                                                                                                                                          
  Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl                                                        
Collecting pyasn1>=0.4.1 (from dvc[ssh])                                                                                                                                                                           
  Downloading https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl (77kB)                                                  
Collecting flufl.lock>=3.2; python_version >= "3.0" (from dvc[ssh])                                                                                                                                                
  Downloading https://files.pythonhosted.org/packages/1e/68/393c148df629f90a919de653ebb967a8bd8c83d07d2bc3150ca0faff3940/flufl.lock-3.2.tar.gz                                                                     
Collecting tqdm<5,>=4.40.0 (from dvc[ssh])                                                                                                                                                                         
  Downloading https://files.pythonhosted.org/packages/71/b0/6d63e33dbf5935dccd334ee2b83cc4d3828817de6faaa3a3f7f5b8cc5141/tqdm-4.40.1-py2.py3-none-any.whl (55kB)                                                   
Collecting shortuuid>=0.5.0 (from dvc[ssh])                                                                                                                                                                        
  Downloading https://files.pythonhosted.org/packages/80/d7/2bfc9332e68d3e15ea97b9b1588b3899ad565120253d3fd71c8f7f13b4fe/shortuuid-0.5.0.tar.gz                                                                    
Collecting packaging>=19.0 (from dvc[ssh])                                                                                                                                                                         
  Downloading https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl                                                       
Collecting python-dateutil<2.8.1,>=2.1 (from dvc[ssh])                                                                                                                                                             
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)                                        
Collecting voluptuous>=0.11.7 (from dvc[ssh])                                                                                                                                                                      
  Downloading https://files.pythonhosted.org/packages/24/3b/fe531688c0d9e057fccc0bc9430c0a3d4b90e0d2f015326e659c2944e328/voluptuous-0.11.7.tar.gz (45kB)                                                           
Collecting configobj>=5.0.6 (from dvc[ssh])                                                                                                                                                                        
  Downloading https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz                                                                    
Collecting funcy>=1.14 (from dvc[ssh])                                                                                                                                                                             
  Downloading https://files.pythonhosted.org/packages/ce/4b/6ffa76544e46614123de31574ad95758c421aae391a1764921b8a81e1eae/funcy-1.14.tar.gz (548kB)                                                                 
Collecting gitdb2>=2.0.6 (from dvc[ssh])                                                                                                                                                                           
  Downloading https://files.pythonhosted.org/packages/03/6c/99296f89bad2ef85626e1df9f677acbee8885bb043ad82ad3ed4746d2325/gitdb2-2.0.6-py2.py3-none-any.whl (63kB) 
Collecting humanize>=0.5.1 (from dvc[ssh])                                                                                                                                                                         
  Downloading https://files.pythonhosted.org/packages/8c/e0/e512e4ac6d091fc990bbe13f9e0378f34cf6eecd1c6c268c9e598dcf5bb9/humanize-0.5.1.tar.gz                                                                     
Collecting grandalf==0.6 (from dvc[ssh])                                                                                                                                                                           
  Downloading https://files.pythonhosted.org/packages/54/f4/a0b6a4c6d616d0a838b2dd0bc7bf74d73e8e8cdc880bab7fdb5fdc3d0e06/grandalf-0.6-py3-none-any.whl                                                             
Collecting ply>=3.9 (from dvc[ssh])                                                                                                                                                                                
  Downloading https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl (49kB)                                                      
Collecting colorama>=0.3.9 (from dvc[ssh])                                                                                                                                                                         
  Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl                                                       
Collecting configparser>=3.5.0 (from dvc[ssh])                                                                                                                                                                     
  Downloading https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl                                                   
Collecting ruamel.yaml>=0.16.1 (from dvc[ssh])                                                                                                                                                                     
  Downloading https://files.pythonhosted.org/packages/fa/90/ecff85a2e9c497e2fa7142496e10233556b5137db5bd46f3f3b006935ca8/ruamel.yaml-0.16.5-py2.py3-none-any.whl (123kB)                                           
Collecting networkx<2.4,>=2.1 (from dvc[ssh])                                                                                                                                                                      
  Downloading https://files.pythonhosted.org/packages/85/08/f20aef11d4c343b557e5de6b9548761811eb16e438cee3d32b1c66c8566b/networkx-2.3.zip (1.7MB)                                                                  
Collecting pathspec>=0.6.0 (from dvc[ssh])                                                                                                                                                                         
  Downloading https://files.pythonhosted.org/packages/7a/68/5902e8cd7f7b17c5879982a3a3ee2ad0c3b92b80c79989a2d3e1ca8d29e1/pathspec-0.6.0.tar.gz                                                                     
Collecting requests>=2.22.0 (from dvc[ssh])                                                                                                                                                                        
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)                                               
Collecting future>=0.16.0 (from dvc[ssh])                                                                                                                                                                          
  Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)                                                              
Collecting treelib>=1.5.5 (from dvc[ssh])                                                                                                                                                                          
  Downloading https://files.pythonhosted.org/packages/17/47/0a8e745a1982ca82ef2149903fc77d5bbf08c4d566f8d238dca7eaf59837/treelib-1.5.5.tar.gz                                                                      
Requirement already satisfied: setuptools>=34.0.0 in /usr/lib/python3/dist-packages (from dvc[ssh])                                                                                                                
Collecting PyYAML<5.2,>=5.1.2 (from dvc[ssh])                                                                                                                                                                      
  Downloading https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz (265kB)                                                               
Collecting nanotime>=0.5.2 (from dvc[ssh])                                                                                                                                                                         
  Downloading https://files.pythonhosted.org/packages/d5/54/6d5924f59cf671326e7809f4b3f70fa8df535d67e952ad0b6fea02f52faf/nanotime-0.5.2.tar.gz                                                                     
Collecting paramiko>=2.5.0; extra == "ssh" (from dvc[ssh])                                                                                                                                                         
  Downloading https://files.pythonhosted.org/packages/1c/d8/50243699d41d6eabd19efb86fb00d99f89580e5cb795b577a5c32ce39ae7/paramiko-2.7.0-py2.py3-none-any.whl (206kB)                                               
Collecting decorator (from jsonpath-ng>=1.4.3->dvc[ssh])                                                                                                                                                           
  Downloading https://files.pythonhosted.org/packages/8f/b7/f329cfdc75f3d28d12c65980e4469e2fa373f1953f5df6e370e84ea2e875/decorator-4.4.1-py2.py3-none-any.whl                                                      
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from jsonpath-ng>=1.4.3->dvc[ssh])                                                                                                           
Collecting importlib-metadata (from inflect>=2.1.0->dvc[ssh])                                                                                                                                                      
  Downloading https://files.pythonhosted.org/packages/e7/59/cc2a91f71957dfb32f25e6b19d8c6dfdbe524e0998e7f7a58a75126ce0cd/importlib_metadata-1.2.0-py2.py3-none-any.whl                                             
Collecting atpublic (from flufl.lock>=3.2; python_version >= "3.0"->dvc[ssh])                                                                                                                                      
  Downloading https://files.pythonhosted.org/packages/1d/71/125eefdde54cf640eb2c22f868158fb0595fce1512c6c51201b105c44e63/atpublic-1.0.tar.gz                                                                       
Collecting pyparsing>=2.0.2 (from packaging>=19.0->dvc[ssh])                                                                                                                                                       
  Downloading https://files.pythonhosted.org/packages/c0/0c/fc2e007d9a992d997f04a80125b0f183da7fb554f1de701bbb70a8e7d479/pyparsing-2.4.5-py2.py3-none-any.whl (67kB)                                               
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.6->dvc[ssh])                                                                                                                                                            
  Downloading https://files.pythonhosted.org/packages/55/d2/866d45e3a121ee15a1dc013824d58072fd5c7799c9c34d01378eb262ca8f/smmap2-2.0.5-py2.py3-none-any.whl                                                         
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" (from ruamel.yaml>=0.16.1->dvc[ssh])                                                                    
  Downloading https://files.pythonhosted.org/packages/53/77/4bcd63f362bcb6c8f4f06253c11f9772f64189bf08cf3f40c5ccbda9e561/ruamel.yaml.clib-0.2.0-cp36-cp36m-manylinux1_x86_64.whl (548kB)                           
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.22.0->dvc[ssh])                                                                                                                                                 
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)                                                
Collecting certifi>=2017.4.17 (from requests>=2.22.0->dvc[ssh])                                                                                                                                                    
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)                                           
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.22.0->dvc[ssh])                                                                                                                               
  Downloading https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl (125kB)                                               
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.22.0->dvc[ssh])                                                                                                  
Collecting pynacl>=1.0.1 (from paramiko>=2.5.0; extra == "ssh"->dvc[ssh])                                                                                                                                          
  Downloading https://files.pythonhosted.org/packages/27/15/2cd0a203f318c2240b42cd9dd13c931ddd61067809fee3479f44f086103e/PyNaCl-1.3.0-cp34-abi3-manylinux1_x86_64.whl (759kB)                                      
Collecting cryptography>=2.5 (from paramiko>=2.5.0; extra == "ssh"->dvc[ssh])                                                                                                                                      
  Downloading https://files.pythonhosted.org/packages/45/73/d18a8884de8bffdcda475728008b5b13be7fbef40a2acc81a0d5d524175d/cryptography-2.8-cp34-abi3-manylinux1_x86_64.whl (2.3MB)                                  
Collecting bcrypt>=3.1.3 (from paramiko>=2.5.0; extra == "ssh"->dvc[ssh])                                                                                                                                          
  Downloading https://files.pythonhosted.org/packages/8b/1d/82826443777dd4a624e38a08957b975e75df859b381ae302cfd7a30783ed/bcrypt-3.1.7-cp34-abi3-manylinux1_x86_64.whl (56kB)                                       
Collecting zipp>=0.5 (from importlib-metadata->inflect>=2.1.0->dvc[ssh])                                                                                                                                           
  Downloading https://files.pythonhosted.org/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl                                                           
Collecting cffi>=1.4.1 (from pynacl>=1.0.1->paramiko>=2.5.0; extra == "ssh"->dvc[ssh])                                                                                                                             
  Downloading https://files.pythonhosted.org/packages/49/72/0d42f94fe94afa8030350c26e9d787219f3f008ec9bf6b86c66532b29236/cffi-1.13.2-cp36-cp36m-manylinux1_x86_64.whl (397kB)                                      
Collecting more-itertools (from zipp>=0.5->importlib-metadata->inflect>=2.1.0->dvc[ssh])                                                                                                                           
  Downloading https://files.pythonhosted.org/packages/68/03/0604cec1ea13c9f063dd50f900d1a36160334dd3cfb01fd0e638f61b46ba/more_itertools-8.0.2-py3-none-any.whl (40kB)                                              
Collecting pycparser (from cffi>=1.4.1->pynacl>=1.0.1->paramiko>=2.5.0; extra == "ssh"->dvc[ssh])                                                                                                                  
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)  
Building wheels for collected packages: flufl.lock, shortuuid, voluptuous, configobj, funcy, humanize, networkx, pathspec, future, treelib, PyYAML, nanotime, atpublic, pycparser                                  
  Running setup.py bdist_wheel for flufl.lock: started                                                                                                                                                             
  Running setup.py bdist_wheel for flufl.lock: finished with status 'done'                                                                                                                                         
  Stored in directory: /root/.cache/pip/wheels/4f/51/d7/f65a7b7f37da7594f7021b122fe677187667ad21f1171d2514                                                                                                         
  Running setup.py bdist_wheel for shortuuid: started                                                                                                                                                              
  Running setup.py bdist_wheel for shortuuid: finished with status 'done'                                                                                                                                          
  Stored in directory: /root/.cache/pip/wheels/3f/eb/fd/69e5177f67b505e44acbd1aedfbe44b91768ee0c4cd5636576                                                                                                         
  Running setup.py bdist_wheel for voluptuous: started                                                                                                                                                             
  Running setup.py bdist_wheel for voluptuous: finished with status 'done'                                                                                                                                         
  Stored in directory: /root/.cache/pip/wheels/e8/e3/d0/a2d476b9cd09b8f5979789e0aaf07119726a3cfb19ee67aa1e                                                                                                         
  Running setup.py bdist_wheel for configobj: started                                                                                                                                                              
  Running setup.py bdist_wheel for configobj: finished with status 'done'                                                                                                                                          
  Stored in directory: /root/.cache/pip/wheels/f1/e4/16/4981ca97c2d65106b49861e0b35e2660695be7219a2d351ee0                                                                                                         
  Running setup.py bdist_wheel for funcy: started                                                                                                                                                                  
  Running setup.py bdist_wheel for funcy: finished with status 'done'                                                                                                                                              
  Stored in directory: /root/.cache/pip/wheels/20/5a/d8/1d875df03deae6f178dfdf70238cca33f948ef8a6f5209f2eb                                                                                                         
  Running setup.py bdist_wheel for humanize: started                                                                                                                                                               
  Running setup.py bdist_wheel for humanize: finished with status 'done'                                                                                                                                           
  Stored in directory: /root/.cache/pip/wheels/69/86/6c/f8b8593bc273ec4b0c653d3827f7482bb2001a2781a73b7f44                                                                                                         
  Running setup.py bdist_wheel for networkx: started                                                                                                                                                               
  Running setup.py bdist_wheel for networkx: finished with status 'done'                                                                                                                                           
  Stored in directory: /root/.cache/pip/wheels/de/63/64/3699be2a9d0ccdb37c7f16329acf3863fd76eda58c39c737af                                                                                                         
  Running setup.py bdist_wheel for pathspec: started                                                                                                                                                               
  Running setup.py bdist_wheel for pathspec: finished with status 'done'                                                                                                                                           
  Stored in directory: /root/.cache/pip/wheels/62/b8/e1/e2719465b5947c40cd85d613d6cb33449b86a1ca5a6c574269                                                                                                         
  Running setup.py bdist_wheel for future: started                                                                                                                                                                 
  Running setup.py bdist_wheel for future: finished with status 'done'                                                                                                                                             
  Stored in directory: /root/.cache/pip/wheels/8b/99/a0/81daf51dcd359a9377b110a8a886b3895921802d2fc1b2397e                                                                                                         
  Running setup.py bdist_wheel for treelib: started                                                                                                                                                                
  Running setup.py bdist_wheel for treelib: finished with status 'done'                                                                                                                                            
  Stored in directory: /root/.cache/pip/wheels/e4/1f/b0/8730974894530362affb8a242aee8f3b42d55ec822c9e2a520
  Running setup.py bdist_wheel for PyYAML: started
  Running setup.py bdist_wheel for PyYAML: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/d9/45/dd/65f0b38450c47cf7e5312883deb97d065e030c5cca0a365030
  Running setup.py bdist_wheel for nanotime: started
  Running setup.py bdist_wheel for nanotime: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/41/99/17/7135f635215e1f61e906295afd11f4f791cfe4ab45f3bfdca2
  Running setup.py bdist_wheel for atpublic: started
  Running setup.py bdist_wheel for atpublic: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/e1/26/5d/fb4b06bb9bb028e49b117b9bdb93c9875e751ff52f6b08aa27
  Running setup.py bdist_wheel for pycparser: started
  Running setup.py bdist_wheel for pycparser: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built flufl.lock shortuuid voluptuous configobj funcy humanize networkx pathspec future treelib PyYAML nanotime atpublic pycparser
Installing collected packages: smmap2, gitdb2, gitpython, ply, decorator, jsonpath-ng, more-itertools, zipp, importlib-metadata, inflect, distro, appdirs, pyasn1, atpublic, flufl.lock, tqdm, shortuuid, pyparsing
, packaging, python-dateutil, voluptuous, configobj, funcy, humanize, future, grandalf, colorama, configparser, ruamel.yaml.clib, ruamel.yaml, networkx, pathspec, chardet, certifi, urllib3, requests, treelib, Py
YAML, nanotime, pycparser, cffi, pynacl, cryptography, bcrypt, paramiko, dvc
  Found existing installation: cryptography 2.1.4
    Not uninstalling cryptography at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed PyYAML-5.1.2 appdirs-1.4.3 atpublic-1.0 bcrypt-3.1.7 certifi-2019.11.28 cffi-1.13.2 chardet-3.0.4 colorama-0.4.3 configobj-5.0.6 configparser-4.0.2 cryptography-2.8 decorator-4.4.1 distro-
1.4.0 dvc-0.75.0 flufl.lock-3.2 funcy-1.14 future-0.18.2 gitdb2-2.0.6 gitpython-3.0.5 grandalf-0.6 humanize-0.5.1 importlib-metadata-1.2.0 inflect-3.0.2 jsonpath-ng-1.4.3 more-itertools-8.0.2 nanotime-0.5.2 netw
orkx-2.3 packaging-19.2 paramiko-2.7.0 pathspec-0.6.0 ply-3.11 pyasn1-0.4.8 pycparser-2.19 pynacl-1.3.0 pyparsing-2.4.5 python-dateutil-2.8.0 requests-2.22.0 ruamel.yaml-0.16.5 ruamel.yaml.clib-0.2.0 shortuuid-0
.5.0 smmap2-2.0.5 tqdm-4.40.1 treelib-1.5.5 urllib3-1.25.7 voluptuous-0.11.7 zipp-0.6.0

```
</details>

**Error:**
```
$docker run -it 85763ae54a00 bash
root@a254fc2e4836:/# dvc
Traceback (most recent call last):
  File "/usr/local/bin/dvc", line 7, in <module>
    from dvc.main import main
  File "/usr/local/lib/python3.6/dist-packages/dvc/main.py", line 7, in <module>
    from dvc.cli import parse_args
  File "/usr/local/lib/python3.6/dist-packages/dvc/cli.py", line 29, in <module>
    import dvc.command.remote as remote
  File "/usr/local/lib/python3.6/dist-packages/dvc/command/remote.py", line 9, in <module>
    from dvc.remote.config import RemoteConfig
  File "/usr/local/lib/python3.6/dist-packages/dvc/remote/__init__.py", line 12, in <module>
    from dvc.remote.s3 import RemoteS3
  File "/usr/local/lib/python3.6/dist-packages/dvc/remote/s3.py", line 8, in <module>
    from botocore.exceptions import ClientError
ModuleNotFoundError: No module named 'botocore'
```

**Comment by efiop** [comment]
@JoshuaPostel Thanks! Fixed by https://github.com/iterative/dvc/commit/9c2c2b307dc44e5d3b9fc0f306d2f0a79a7b1d11

**Comment by efiop** [comment]
@JoshuaPostel We will release 0.75.1 soon, but for now you could `pip install botocore` as a workaround.

**Comment by mroutis** [comment]
@efiop, could you release this one today?

**Comment by efiop** [comment]
@mroutis yes, will try to do it right now.

**Comment by efiop** [comment]
Release is building:  https://github.com/iterative/dvc/releases/tag/0.75.1 . Pip will be ready in an hour or so, other packages later today/tomorrow.

**Comment by mroutis** [comment]
Thanks a lot, @efiop :slightly_smiling_face:
