### ISSUE TITLE
travis: osx failure

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#2970]
https://travis-ci.com/iterative/dvc/jobs/268202342

```
+fpm -s dir -f -t osxpkg --description 'Data Version Control - datasets, models, and experiments versioning for ML or data science projects' --osxpkg-identifier-prefix com.iterative --after-install scripts/fpm/after-install.sh --after-remove scripts/fpm/after-remove.sh -n dvc -v 0.77.3+a4dc2e -C build usr

/Users/travis/.rvm/gems/ruby-2.4.3@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:84:in `setup': undefined method `plain_specs' for #<Bundler::RubygemsIntegration:0x00007fd94e929530> (NoMethodError)
	from /Users/travis/.rvm/gems/ruby-2.4.3@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:124:in `check'
	from /Users/travis/.rvm/gems/ruby-2.4.3@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:131:in `<top (required)>'
	from /Users/travis/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /Users/travis/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /Users/travis/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/travis/.rvm/gems/ruby-2.4.3@global/gems/rubygems-bundler-1.4.4/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.4.3@global/gems/executable-hooks-1.4.2/lib/executable-hooks/hooks.rb:50:in `block in run'
	from /Users/travis/.rvm/gems/ruby-2.4.3@global/gems/executable-hooks-1.4.2/lib/executable-hooks/hooks.rb:49:in `each'
	from /Users/travis/.rvm/gems/ruby-2.4.3@global/gems/executable-hooks-1.4.2/lib/executable-hooks/hooks.rb:49:in `run'
	from /Users/travis/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:10:in `<main>'
```

**Comment by mroutis** [comment]
https://github.com/bundler/bundler/issues/7492

**Comment by efiop** [comment]
@mroutis Thanks for the research! Indeed, that fixed it for now.
