### ISSUE TITLE
Ignored exception in destructor when pushing to ssh remote

### ISSUE THREAD

**Issue by byaka** [iterative/dvc#3248]
DVC version 0.82.3
Platform Linux Ubuntu 18.04
Installed with pip3

Inited new repo and added some files to dvc, now im try to push them.

```
user@dev5:~/projects/recsys_similar_new$ dvc remote list --global
myremote	ssh://user@10.192.2.16/srv/dvc/storage
user@dev5:~/projects/recsys_similar_new$ dvc push -r myremote
Everything is up to date.                                                                                                                                 
Exception ignored in: <bound method Pool.__del__ of <dvc.remote.pool.Pool object at 0x7f7594a35f98>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dvc/remote/pool.py", line 42, in __del__
  File "/usr/local/lib/python3.6/dist-packages/dvc/remote/pool.py", line 46, in close
  File "/usr/local/lib/python3.6/dist-packages/dvc/remote/ssh/connection.py", line 59, in close
  File "/usr/local/lib/python3.6/dist-packages/paramiko/sftp_client.py", line 195, in close
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 666, in close
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 1255, in _close_internal
  File "/usr/local/lib/python3.6/dist-packages/paramiko/channel.py", line 1246, in _send_eof
  File "/usr/local/lib/python3.6/dist-packages/paramiko/message.py", line 232, in add_int
TypeError: 'NoneType' object is not callable
```

**Comment by efiop** [comment]
Hi @byaka !

`dvc push` succeeded, but there has been a hickup when the interpreter was shutting down, that doesn't really affect the functionality but is indeed really ugly. We will take a closer look ASAP.

Thanks for the feedback!

**Comment by byaka** [comment]
@efiop ah, ok, so this not a fatal error. thx for answer!

**Comment by efiop** [comment]
@byaka Btw, are you able to reliably reproduce? Or does it happen just once in a while?

**Comment by byaka** [comment]
no, it happens for me on every push, pull or status but only on servers where dvc installed via pip
on my centos servers dvc installed via yam and this problem not happens

**Comment by efiop** [comment]
@byaka yum packages are a bit different, they are built with pyinstaller, so it might be swallowing such hickups. Thanks for clarifying! We will try to take look soon. Let us know if you'll have any other issues :slightly_smiling_face:

**Comment by efiop** [comment]
For the record: another user is experiencing the same issue https://discordapp.com/channels/485586884165107732/485596304961962003/672421181185589275

**Comment by e3bo** [comment]
I'm also experiencing this issue.

Ubuntu 19.04 and Arch Linux 
DVC version 0.82.6.
Installed via pip

Additionally, I have gotten 

    Exception ignored in: <function Pool.__del__ at 0x7fb429b86e50>                                                    
    Traceback (most recent call last):                                                                                 
     File "/home/eamon/venv2/lib/python3.8/site-packages/dvc/remote/pool.py", line 42, in __del__                     
     File "/home/eamon/venv2/lib/python3.8/site-packages/dvc/remote/pool.py", line 46, in close                       
     File "/home/eamon/venv2/lib/python3.8/site-packages/dvc/remote/ssh/connection.py", line 59, in close
     File "/home/eamon/venv2/lib/python3.8/site-packages/paramiko/sftp_client.py", line 195, in close
     File "/home/eamon/venv2/lib/python3.8/site-packages/paramiko/channel.py", line 671, in close
     File "/home/eamon/venv2/lib/python3.8/site-packages/paramiko/transport.py", line 1846, in _send_user_message
     AttributeError: 'NoneType' object has no attribute 'time'

following `dvc pull`. But this does not occur every time I run that command.

**Comment by efiop** [comment]
For the record: can reproduce with paramiko 2.5.0, 2.6.0 and 2.7.1, so it is something else that broke. Looking into it.

**Comment by efiop** [comment]
Fixed by #3274. Releasing new version right now.

**Comment by efiop** [comment]
@byaka @e3bo @aprimostka Guys, 0.82.8 is out. Please upgrade and give it a try. Let us know if the issue still persists or not :slightly_smiling_face:

**Comment by byaka** [comment]
@efiop thank u and dvc-team, ill check it tomorrow

**Comment by aprimostka** [comment]
I had not time to fully test but first run gone smoothly

**Comment by e3bo** [comment]
Upgrading to 82.8 from 82.6 resolved the issue for me too.
