### ISSUE TITLE
SFTP destructor error

### ISSUE THREAD

**Issue by aprimostka** [iterative/dvc#3273]
dvc --version
0.82.6
Windows 10 x64, pip
Ubuntu 19.04, pip, conda
When do 'dvc pull' with address `ssh://<server-name>/<path>` where ssh detailed config are taken from `.ssh/config` exception raised (windows system):
```
Exception ignored in: <function Pool.__del__ at 0x000001C14C2A4AF8>
Traceback (most recent call last):
  File "d:\programs\miniconda3\envs\fastai\lib\site-packages\dvc\remote\pool.py", line 42, in __del__
  File "d:\programs\miniconda3\envs\fastai\lib\site-packages\dvc\remote\pool.py", line 46, in close
  File "d:\programs\miniconda3\envs\fastai\lib\site-packages\dvc\remote\ssh\connection.py", line 59, in close
  File "d:\programs\miniconda3\envs\fastai\lib\site-packages\paramiko\sftp_client.py", line 194, in close
  File "d:\programs\miniconda3\envs\fastai\lib\site-packages\paramiko\sftp_client.py", line 185, in _log
  File "d:\programs\miniconda3\envs\fastai\lib\site-packages\paramiko\sftp.py", line 158, in _log
  File "d:\programs\miniconda3\envs\fastai\lib\logging\__init__.py", line 1443, in log
  File "d:\programs\miniconda3\envs\fastai\lib\logging\__init__.py", line 1621, in isEnabledFor
TypeError: 'NoneType' object is not callable
```

Stacktrace is the same on both systems. With version 0.80.0 all works smoothly

**Comment by efiop** [comment]
Hi @aprimostka !

Thanks for reporting this bug! I'll close this issue in favor of https://github.com/iterative/dvc/issues/3248 . We are looking into it right now.
