### ISSUE TITLE
ERROR: unexpected error - No module named 'jsonpath_ng.bin'; 'jsonpath_ng'

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/dvc#3456]
Suddenly I have this error

```
ERROR: unexpected error - No module named 'jsonpath_ng.bin'; 'jsonpath_ng' is not a package
    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12) {
  killed: false,
  code: 255,
  signal: null,
  cmd: 'dvc metrics diff  --show-json origin/master 42e3fcbefe1f4b68fd9462ef1f79bcdeed0fd3fc',
  stdout: '\n' +
    'Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!\n',
  stderr: "ERROR: unexpected error - No module named 'jsonpath_ng.bin'; 'jsonpath_ng' is not a package\n"
```

**Please provide information about your setup**
DVC version: 0.87.0
Python version: 3.6.10
Platform: Linux-5.0.0-1032-azure-x86_64-with-debian-buster-sid
Binary: False
Package: pip

**Comment by skshetry** [comment]
Caused by https://github.com/h2non/jsonpath-ng/issues/36.

We can either pin it to `1.4.3` or upgrade to `1.5.1` which is already released. Or, just disallow `1.5.0`.
