### ISSUE TITLE
Pushing files to GCS remote repo results in unexpected error - 503 GET

### ISSUE THREAD

**Issue by dldx** [iterative/dvc#3504]
UPDATE: after waiting a while, this now works without error. It's possible that there were too many files being added.

I have added a number of files to DVC and am now trying to push them to the remote GCS folder via:
`dvc push -v -r remote_folder -R folder_with_dvc_files`

It initially managed to upload a number of the files to GCS. However, after a certain period of time, it gave me this error. When I try to rerun the same command again, it does the remote folder scan, and then keeps giving me this error.

I am running dvc 0.88.0 on a google cloud engine instance.
 
```
2020-03-18 12:59:15,243 DEBUG: UPDATE state SET timestamp = ? WHERE inode = ?                                                                                                               
2020-03-18 12:59:15,244 DEBUG: cache '../../../.dvc/cache/46/47a9d2a8017ed316a1681595c5e6c6' expected '4647a9d2a8017ed316a1681595c5e6c6' actual '4647a9d2a8017ed316a1681595c5e6c6'          
2020-03-18 12:59:15,245 DEBUG: Path ../../../.dvc/cache/ae/b08b20dcf32716f25b71a6ce3a2361 inode 3834903                                                                                     
2020-03-18 12:59:15,246 DEBUG: SELECT mtime, size, md5, timestamp from state WHERE inode=?                                                                                                  
2020-03-18 12:59:15,252 DEBUG: fetched: [('1583177561000000000', '1106254', 'aeb08b20dcf32716f25b71a6ce3a2361', '1584535679709167104')]                                                     
2020-03-18 12:59:15,252 DEBUG: UPDATE state SET timestamp = ? WHERE inode = ?                                                                                                               
2020-03-18 12:59:15,253 DEBUG: cache '../../../.dvc/cache/ae/b08b20dcf32716f25b71a6ce3a2361' expected 'aeb08b20dcf32716f25b71a6ce3a2361' actual 'aeb08b20dcf32716f25b71a6ce3a2361'          
2020-03-18 12:59:15,259 DEBUG: Collecting information from remote cache...                                                                                                                  
2020-03-18 13:06:28,790 DEBUG: SELECT count from state_info WHERE rowid=?                                                                                                                   
2020-03-18 13:06:28,792 DEBUG: fetched: [(39251,)]
2020-03-18 13:06:28,792 DEBUG: UPDATE state_info SET count = ? WHERE rowid = ?
2020-03-18 13:06:28,848 ERROR: unexpected error - 503 GET https://www.googleapis.com/storage/v1/b/example_project/o/dvc%2Ftest%2Fc2%2Fc921afb4655d64fdb7f8baa611c42b?fields=name: Backend Error
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/site-packages/dvc/main.py", line 50, in main
    ret = cmd.run()
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/site-packages/dvc/command/data_sync.py", line 49, in run
    recursive=self.args.recursive,
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/site-packages/dvc/repo/__init__.py", line 27, in wrapper
    ret = f(repo, *args, **kwargs)
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/site-packages/dvc/repo/push.py", line 25, in push
    return self.cloud.push(used, jobs, remote=remote)
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/site-packages/dvc/data_cloud.py", line 66, in push
    show_checksums=show_checksums,
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/site-packages/dvc/remote/local.py", line 369, in push
    download=False,
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/site-packages/dvc/remote/local.py", line 342, in _process
    download=download,
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/site-packages/dvc/remote/local.py", line 263, in status
    md5s, jobs=jobs, name=str(remote.path_info)
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/site-packages/dvc/remote/base.py", line 827, in cache_exists
    ret = list(itertools.compress(checksums, in_remote))
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/site-packages/dvc/remote/base.py", line 820, in exists_with_progress
    ret = self.exists(path_info)
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/site-packages/dvc/remote/gs.py", line 167, in exists
    return self.isfile(path_info) or self.isdir(path_info)
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/site-packages/dvc/remote/gs.py", line 159, in isfile
    return blob.exists()
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 513, in exists
    _target_object=None,
  File "/home/jupyter/anaconda3/envs/sats/lib/python3.7/site-packages/google/cloud/_http.py", line 393, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.ServiceUnavailable: 503 GET https://www.googleapis.com/storage/v1/b/example_project/o/dvc%2Ftest%2Fc2%2Fc921afb4655d64fdb7f8baa611c42b?fields=name: Backend Error
------------------------------------------------------------
```

**Comment by efiop** [comment]
Hi @dldx !

How many files are we talking about? Looks like we are hitting some limit or something. Could you try:
```
dvc remote modify remote_folder no_traverse false
```
and run your `dvc push` again?

**Comment by dldx** [comment]
Hi! I added about 38,000 files so quite a few. I will give that a try, thanks!

**Comment by shcheklein** [comment]
@efiop I wonder if we should just retry on certain errors like we do with GDrive?

`ServiceUnalavilabe looks like a temporary server error` - Google usually returns 403 if limits are hit.

@dldx @pmrowla is also working on removing this no-traverse thingy. Stay tuned here #3501 .

**Comment by efiop** [comment]
> @efiop I wonder if we should just retry on certain errors like we do with GDrive?

@shcheklein Sure we should, same with other remotes. We didn't hear about any problems with those remotes until now, but we definitely did expect to get them in the future, so here we go.

**Comment by shcheklein** [comment]
Also, I would first check if the library itself has a way to specify the number of retries. I've seen this in some Google libraries.

**Comment by dldx** [comment]
`dvc remote modify remote_folder no_traverse false` does indeed work, thanks!  What exactly is the compromise here?

**Comment by pmrowla** [comment]
For GCS, by default (when `no_traverse` is true) DVC checks to see if each individual local file exists in the remote cache to determine what data needs to be pushed or pulled. When `no_traverse` is false, DVC fetches the entire listing of files in the remote cache, and then compares that to the list of local files. Which method is optimal depends on the sizes of both your local and remote caches - for *very large* remote caches, setting `no_traverse` to false can be very slow.

After #3501 is completed, DVC will automatically determine which method to use without relying on the user to configure the `no_traverse` option themselves

**Comment by dldx** [comment]
Thanks for the info! Much appreciated!

**Comment by shcheklein** [comment]
@dldx the new version have been as far as I understand - please give a try!

**Comment by efiop** [comment]
@dldx I'll close this issue for, please give the latest version a try and let us know if that fixed it for you or not. Thanks for the feedback!

**Comment by dldx** [comment]
It does look it fixed it. Sorry for the delayed response!
