### ISSUE TITLE
list: raises an ugly exception on a dir path

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#3776]
Note: this is pre-release testing.

```
DVC version: 1.0.0a1+666e20
Python version: 3.7.7
Platform: Darwin-18.2.0-x86_64-i386-64bit
Binary: False
Package: None
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache: reflink - supported, hardlink - supported, symlink - supported
Filesystem type (cache directory): ('apfs', '/dev/disk1s1')
Repo: dvc, git
Filesystem type (workspace): ('apfs', '/dev/disk1s1')
```

On the `example-get-started`:

```
(.env) [ivan@ivan ~/Projects/example-repos-dev/example-get-started/build/example-get-started]$ dvc list . data/features
ERROR: failed to list '.' - The path 'data/features' does not exist in the target repository 'ExternalRepo: '/private/var/folders/_1/dxrf7_f15sn4r01jvqvr5b6h0000gn/T/tmpmvo7qgk1dvc-erepo'' neither as a DVC output nor as a Git-tracked file.
```

while listing of a single output works fine:

```
(.env) [ivan@ivan ~/Projects/example-repos-dev/example-get-started/build/example-get-started]$ dvc list . data/data.xml
data.xml
```

---------

**Problems:**

1. Message reveals a lot of internal info that is not relevant.
2. Directory actually exists. At least we should show its name if not the full content.

**Comment by pmrowla** [comment]
I think this may end up being fixed after the `ls` changes in #3716

**Comment by jorgeorpinel** [comment]
Hi! This error got worst it seems.

```console
λ dvc list .
ERROR: unexpected error - 'none'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
Traceback (most recent call last):
  File "shutil.py", line 402, in _rmtree_unsafe
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\poj12\\AppData\\Local\\Temp\\tmpcuw5fhqddvc-clone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc\__main__.py", line 7, in <module>
  File "dvc\main.py", line 127, in main
  File "dvc\external_repo.py", line 71, in clean_repos
  File "dvc\external_repo.py", line 368, in _remove
  File "site-packages\funcy\decorators.py", line 39, in wrapper
  File "site-packages\funcy\flow.py", line 122, in retry
  File "site-packages\funcy\decorators.py", line 60, in __call__
  File "dvc\utils\fs.py", line 136, in remove
  File "shutil.py", line 516, in rmtree
  File "shutil.py", line 404, in _rmtree_unsafe
  File "dvc\utils\fs.py", line 121, in _chmod
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\usr\\AppData\\Local\\Temp\\tmpcuw5fhqddvc-clone'
[21952] Failed to execute script __main__
```

Plus a possibly Windows-specific exception there ^ (can you guys try from another OS?)

```console
λ dvc version
DVC version: 1.6.1 (exe)
---------------------------------
Platform: Python 3.7.5 on Windows-10-10.0.18362-SP0
Supports: All remotes
Cache types: hardlink
Cache directory: NTFS on C:\
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Comment by jorgeorpinel** [comment]
Is this a duplicate of #3590? They can probably be merged.

**Comment by efiop** [comment]
> Plus a possibly Windows-specific exception there ^ (can you guys try from another OS?)

Not able to reproduce. Need to take a closer look at windows.

**Comment by efiop** [comment]
> Is this a duplicate of #3590? They can probably be merged.

Doesn't look like a duplicate.
