### ISSUE TITLE
`KeyError: 'md5'` when running `dvc commit`

### ISSUE THREAD

**Issue by courentin** [iterative/dvc#3829]
Hello,

I'm pretty new with dvc and I'm facing an issue when running `dvc commit`. Here is the verbose log:

<details>
<summary>Details</summary>

```
2020-05-20 09:30:14,791 ERROR: unexpected error - 'md5'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.6/site-packages/dvc/main.py", line 48, in main
    ret = cmd.run()
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.6/site-packages/dvc/command/commit.py", line 21, in run
    force=self.args.force,
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.6/site-packages/dvc/repo/__init__.py", line 30, in wrapper
    ret = f(repo, *args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.6/site-packages/dvc/repo/commit.py", line 11, in commit
    stage.commit()
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.6/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.6/site-packages/dvc/stage/decorators.py", line 35, in rwlocked
    return call()
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.6/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.6/site-packages/dvc/stage/__init__.py", line 535, in commit
    out.commit()
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.6/site-packages/dvc/output/base.py", line 259, in commit
    self.cache.save(self.path_info, self.info)
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.6/site-packages/dvc/remote/base.py", line 551, in save
    checksum = checksum_info[self.PARAM_CHECKSUM]
KeyError: 'md5'
------------------------------------------------------------
```

</details>

Tell me if you need more information for investigations.

Btw, the `dvc commit` is taking more than 5 minutes to complete, is it normal, did I miss something ? I have a directory of +10000 files that is tracked by `dvc`.

I'm using the 1.0.0a1 version of dvc on linux and mac, I installed dvc with pip.

Thank you for working on this project !

Update: I'm using an EFS to share the dvc cache between EC2 instances, this might explain the ~5 min time to complete the `dvc commit`.

**Comment by efiop** [comment]
Hi @courentin !

Please show your `dvc version` output. I think this bug is fixed in the current master, but unreleased yet.

**Comment by courentin** [comment]
Thank you for your answer, `dvc version` gives me:
```
DVC version: 1.0.0a1
Python version: 3.6.8
Platform: Darwin-19.3.0-x86_64-i386-64bit
Binary: False
Package: pip
Supported remotes: http, https, s3
Cache: reflink - supported, hardlink - supported, symlink - supported
Filesystem type (cache directory): ('apfs', '/dev/disk1s2')
Repo: dvc, git
Filesystem type (workspace): ('apfs', '/dev/disk1s2')
```

**Comment by efiop** [comment]
@courentin Got it. So yeah, it is fixed in the current master by https://github.com/iterative/dvc/pull/3816. We didn't release 1.0.0a2 yet. I'll trigger the new * alpha * release right now.

Closing since it is fixed. Thank you for the feedback! :pray:

**Comment by efiop** [comment]
@courentin 1.0.0a2 will be out on pypi in a few minutes. Please note that this is still a pre-release, so some degree of instability is expected. But we will really appreciate the bug reports :wink:

**Comment by courentin** [comment]
Yes, I expect some instability.
I'm impressed by your responsiveness, thank you very much !
