### ISSUE TITLE
`dvc get` / `dvc import` don't work with subdirectories

### ISSUE THREAD

**Issue by pokey** [iterative/dvc#3900]
## Bug Report

`dvc get` doesn't seem to support a subrepo, as initialized with `dvc init --subdir`.  I created a dummy repo https://github.com/pokey/dvc-subdir-test to test this one out.  The following command should work, based on my understanding of subdirs, but I get the following error:

```sh
➜ dvc get --verbose git@github.com:pokey/dvc-subdir-test.git foo/hello.txt
2020-05-28 16:35:40,149 DEBUG: Creating external repo git@github.com:pokey/dvc-subdir-test.git@None
2020-05-28 16:35:40,263 DEBUG: erepo: git clone git@github.com:pokey/dvc-subdir-test.git to a temporary dir
2020-05-28 16:35:42,571 DEBUG: erepo: making a copy of git@github.com:pokey/dvc-subdir-test.git clone
2020-05-28 16:35:42,592 DEBUG: Removing '/Users/pokey/src/globality-ai-prototyping/projects/case-study-annotation-ui/.MWfewsCDsnVyBss9q5sbd8'
2020-05-28 16:35:42,592 ERROR: failed to get 'foo/hello.txt' from 'git@github.com:pokey/dvc-subdir-test.git' - The path 'foo/hello.txt' does not exist in the target repository 'git@github.com:pokey/dvc-subdir-test.git' neither as a DVC output nor as a Git-tracked file.
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pokey/.pyenv/versions/3.8.0/envs/dvc/lib/python3.8/site-packages/dvc/external_repo.py", line 187, in pull_to
    fs_copy(os.path.join(self.root_dir, path), fspath(to_info))
  File "/Users/pokey/.pyenv/versions/3.8.0/envs/dvc/lib/python3.8/site-packages/dvc/utils/fs.py", line 28, in fs_copy
    shutil.copy2(src, dst)
  File "/Users/pokey/.pyenv/versions/3.8.0/lib/python3.8/shutil.py", line 426, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/pokey/.pyenv/versions/3.8.0/lib/python3.8/shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/yb/k48gsy1s3qg1gdd72v9y6rdr0000gn/T/tmp4xb038tsdvc-erepo/foo/hello.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pokey/.pyenv/versions/3.8.0/envs/dvc/lib/python3.8/site-packages/dvc/command/get.py", line 37, in _get_file_from_repo
    Repo.get(
  File "/Users/pokey/.pyenv/versions/3.8.0/envs/dvc/lib/python3.8/site-packages/dvc/repo/get.py", line 55, in get
    repo.pull_to(path, PathInfo(out))
  File "/Users/pokey/.pyenv/versions/3.8.0/envs/dvc/lib/python3.8/site-packages/dvc/external_repo.py", line 189, in pull_to
    raise PathMissingError(path, self.url)
dvc.exceptions.PathMissingError: The path 'foo/hello.txt' does not exist in the target repository 'git@github.com:pokey/dvc-subdir-test.git' neither as a DVC output nor as a Git-tracked file.
------------------------------------------------------------
```

### Please provide information about your setup
**Output of `dvc version`:**
```sh
$ dvc version
DVC version: 0.93.0
Python version: 3.8.0
Platform: macOS-10.14.6-x86_64-i386-64bit
Binary: False
Package: pip
Supported remotes: http, https, s3
```

**Additional Information (if any):**

**Comment by pokey** [comment]
actually, thinking this one is maybe a duplicate of https://github.com/iterative/dvc/issues/3369?  That thread seemed to get mixed with other concerns but I think the request is the same, so feel free to close this as duplicate if so

**Comment by efiop** [comment]
@pokey Thanks for the request! Closing in favor of https://github.com/iterative/dvc/issues/3369 . We plan to work on it next week, so stay tuned :slightly_smiling_face:
