### ISSUE TITLE
DVC repro/pull/checkout hangs on sshfs

### ISSUE THREAD

**Issue by geblanco** [iterative/dvc#4259]
### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.1.11
Python version: 3.8.3
Platform: Linux-5.7.7-arch1-1-x86_64-with-glibc2.2.5
Binary: False
Package: pip
Supported remotes: http, https, s3, ssh
Filesystem type (workspace): ('ext4', '/dev/sda1')
```

**Additional Information (if any):**

Setup:
Experiments are run in a server with GPUs, with a local directory as cache, setup with: `type = "hardlink,symlink"`. I run everything with `dvc repro`, then `dvc push`. It runs as expected and caches all files.
Afterwards, I run evaluation in my local machine, to do so, the cache directory is setup the same, but the local cache directory is mounted through sshfs against the server (I do it this way because of #3815).

The thing is that it only hangs with a certain project and not the rest. My guess is that it has to do with the number of files involved. In the case of the project working correctly there are only 75 files, whereas the one hanging up has 28005 files (RACE dataset is scattered across multiple files).

When running `dvc pull` or `dvc checkout`, dvc hangs indefinitely (or at least for >5minutes) without any prompt (`-v` option doesn't yield any output either).

Best,

**Comment by efiop** [comment]
Hi @geblanco . Could you try to kill it and show the traceback?

**Comment by geblanco** [comment]
Hello @efiop,

Yesterday I left it running and the command finished correctly, though it took very, very long time and every time I run it happens the same.

Killing the process just yields (ctrl+c):
```console
$ dvc pull
^CERROR: interrupted by the user

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

**Comment by Suor** [comment]
Maybe related, have SSH hanging out for me during pull with missing key:
```
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/suor/projects/viewer/backend/repos/management/commands/parse_repo.py", line 29, in handle
    parse_repo(repo.pk, user.pk)
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/celery/app/task.py", line 392, in __call__
    return self.run(*args, **kwargs)
  File "/home/suor/projects/viewer/backend/repos/tasks.py", line 59, in parse_repo
    parse_local_repo(repo, dirname)
  File "/home/suor/projects/viewer/backend/repos/parsing.py", line 51, in parse_local_repo
    _fetch_cache(repo, to_add)
  File "/home/suor/projects/viewer/backend/repos/parsing.py", line 172, in _fetch_cache
    downloaded = repo.cloud.pull(cache)
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/dvc/data_cloud.py", line 84, in pull
    downloaded_items_num = self.repo.cache.local.pull(
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/dvc/remote/base.py", line 79, in wrapper
    return f(obj, named_cache, remote, *args, **kwargs)
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/dvc/remote/local.py", line 705, in pull
    return self._process(
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/dvc/remote/local.py", line 605, in _process
    dir_status, file_status, dir_contents = self._status(
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/dvc/remote/local.py", line 468, in _status
    remote.hashes_exist(
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/dvc/remote/ssh/__init__.py", line 347, in hashes_exist
    return ret
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 636, in __exit__
    self.shutdown(wait=True)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 236, in shutdown
    t.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by efiop** [comment]
@Suor This is about sshfs, not ssh. So unlikely.

@geblanco Could you try `dvc push -v` and then kill it and show traceback? Sorry, I forgot to mention `-v`.

Btw, do you have giant untracked directories that are not in `.dvcignore`?

**Comment by geblanco** [comment]
Hi @efiop,

Here is the output from `dvc pull -v`
```bash
^C2020-07-24 10:39:16,083 ERROR: interrupted by the user
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/main.py", line 52, in main
    cmd = args.func(args)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/command/base.py", line 35, in __init__
    self.repo = Repo()
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/repo/__init__.py", line 101, in __init__
    self.config = Config(self.dvc_dir, tree=self.tree)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/config.py", line 254, in __init__
    self.load(validate=validate)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/config.py", line 300, in load
    conf = self.load_config_to_level()
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/config.py", line 390, in load_config_to_level
    _merge(merged_conf, self.load_one(merge_level))
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/config.py", line 337, in load_one
    conf = self._load_config(level)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/config.py", line 316, in _load_config
    if tree.exists(filename):
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/tree/local.py", line 81, in exists
    return not self.dvcignore.is_ignored_file(
  File "/usr/lib/python3.8/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/tree/local.py", line 64, in dvcignore
    ret = DvcIgnoreFilter(self, root)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/ignore.py", line 186, in __init__
    for root, dirs, _ in self.tree.walk(self.root_dir):
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/tree/local.py", line 108, in walk
    for root, dirs, files in os.walk(
  File "/usr/lib/python3.8/os.py", line 413, in walk
    yield from walk(new_path, topdown, onerror, followlinks)
  File "/usr/lib/python3.8/os.py", line 413, in walk
    yield from walk(new_path, topdown, onerror, followlinks)
  File "/usr/lib/python3.8/os.py", line 413, in walk
    yield from walk(new_path, topdown, onerror, followlinks)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.8/os.py", line 371, in walk
    is_dir = entry.is_dir()
KeyboardInterrupt
------------------------------------------------------------

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

And no, I have no giant directory, the only big directory I have is tracked by DVC, which is the dataset.
Best,

**Comment by efiop** [comment]
@geblanco Thanks! Sorry for the delay. We've introduced some optimizations a few days ago, could you please upgrade to the latest version and try again?

**Comment by geblanco** [comment]
Hi @efiop!

No worries, it seems there is a lot of work on your side. I bring new logs!

dvc fetch -v
---
Comments:
The process first queries the cache and then fetches all files:
- Querying cache: Faaaaster than before, there are lots of files, progress bar seems to work at ~160-180file/s more than acceptable.
- Fetching files. A bit slower than querying, but without a progress bar, it is a bit obscure, without `-v` flag, there is no output here, so it seems to be hanged. Maybe add progress? With verbose it outputs:

```command
DEBUG: Path '....' inode '4241' # with a real file path to cache
DEBUG: fetched: [('...', '...', '...', '...')] # with actual numbers
```
Finishes correctly

dvc pull -v
---
It first queries cache, then fetches files and then checkout them.
Comments:
- Quering cache: Idem
- Fetching files: Idem
- Checkout: With `-v` flag enabled it outputs:
`Assuming ... is unchanged since it is read-only`
It has a progress bar, but it does not progress, slows to ~1-5s/file (vs ~160-180s/files). After a while it hangs with no message
When `Ctrl-c`'ed:

```command
DEBUG: fetched: [(56063,)] 
ERROR: interrupted by the user
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/main.py", line 53, in main
    ret = cmd.run()
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/command/data_sync.py", line 26, in run
    stats = self.repo.pull(
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/repo/__init__.py", line 34, in wrapper
    ret = f(repo, *args, **kwargs)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/repo/pull.py", line 36, in pull
    stats = self._checkout(  # pylint: disable=protected-access
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/repo/checkout.py", line 91, in _checkout
    result = stage.checkout(
  File "/usr/lib/python3.8/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/stage/decorators.py", line 35, in rwlocked
    return call()
  File "/usr/lib/python3.8/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/stage/__init__.py", line 450, in checkout
    key, outs = self._checkout(out, **kwargs)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/stage/__init__.py", line 458, in _checkout
    result = out.checkout(**kwargs)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/output/base.py", line 334, in checkout
    return self.cache.checkout(
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/cache/base.py", line 488, in checkout
    elif not relink and not self.changed(path_info, hash_info):
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/cache/base.py", line 130, in changed
    actual = self.tree.get_hash(path_info)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/tree/base.py", line 252, in get_hash
    hash_ = self.state.get(path_info)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/state.py", line 405, in get
    actual_mtime, actual_size = get_mtime_and_size(path, self.tree)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/utils/fs.py", line 40, in get_mtime_and_size
    stats = tree.stat(file_path)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/tree/local.py", line 153, in stat
    return os.stat(path)
KeyboardInterrupt
```
More comments:
- What is the difference between fetch and pull?
- Why does it output a `DEBUG: fetched: [(56063,)] ` when `Ctrl-c` is hit? Does it hang on fetching a file? Isn't it the same interface for fetching files than before? Does it wait for some condition is never met and so hangs forever?

dvc checkout -v:
---
It seems to only checkout (that appears to be the bottleneck)
Outputs: `Assuming ... is unchanged since it is read-only`. The progress bar does not progress but it says it works at 190file/s. The file being checked out is always the same.

When `Ctrl-c`'ed, outputs:
```command
DEBUG: fetched: [(56063,)] 
ERROR: interrupted by the user
Traceback (most recent call last):
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/main.py", line 53, in main
    ret = cmd.run()
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/command/checkout.py", line 44, in run
    stats = self.repo.checkout(
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/repo/__init__.py", line 34, in wrapper
    ret = f(repo, *args, **kwargs)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/repo/__init__.py", line 608, in checkout
    return self._checkout(*args, **kwargs)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/repo/checkout.py", line 91, in _checkout
    result = stage.checkout(
  File "/usr/lib/python3.8/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/stage/decorators.py", line 35, in rwlocked
    return call()
  File "/usr/lib/python3.8/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/stage/__init__.py", line 450, in checkout
    key, outs = self._checkout(out, **kwargs)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/stage/__init__.py", line 458, in _checkout
    result = out.checkout(**kwargs)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/output/base.py", line 334, in checkout
    return self.cache.checkout(
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/cache/base.py", line 488, in checkout
    elif not relink and not self.changed(path_info, hash_info):
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/cache/base.py", line 130, in changed
    actual = self.tree.get_hash(path_info)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/tree/base.py", line 252, in get_hash
    hash_ = self.state.get(path_info)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/state.py", line 405, in get
    actual_mtime, actual_size = get_mtime_and_size(path, self.tree)
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/utils/fs.py", line 38, in get_mtime_and_size
    for file_path in tree.walk_files(path):
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/tree/local.py", line 117, in walk_files
    for root, _, files in self.walk(path_info):
  File "/home/gb/.local/lib/python3.8/site-packages/dvc/tree/local.py", line 106, in walk
    for root, dirs, files in os.walk(
  File "/usr/lib/python3.8/os.py", line 413, in walk
    yield from walk(new_path, topdown, onerror, followlinks)
  File "/usr/lib/python3.8/os.py", line 413, in walk
    yield from walk(new_path, topdown, onerror, followlinks)
  File "/usr/lib/python3.8/os.py", line 371, in walk
    is_dir = entry.is_dir()
KeyboardInterrupt
```
Comments: Same as with pull

Contact back if you need any more logs, outputs or help! :)

Best,
Guillermo
