### ISSUE TITLE
ERROR: unexpected error - cannot import name 'BaseRemoteTree'

### ISSUE THREAD

**Issue by shawnlee103** [iterative/dvc#4306]
### Please provide information about your setup

```
dvc==1.2.2
dvc version --verbose

2020-07-30 16:20:51,008 ERROR: unexpected error - cannot import name 'BaseRemoteTree'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/XXX/.local/lib/python3.6/site-packages/dvc/main.py", line 53, in main
    ret = cmd.run()
  File "/home/XXX/.local/lib/python3.6/site-packages/dvc/command/version.py", line 40, in run
    repo = Repo()
  File "/home/XXX/.local/lib/python3.6/site-packages/dvc/repo/__init__.py", line 74, in __init__
    from dvc.data_cloud import DataCloud
  File "/home/XXX/.local/lib/python3.6/site-packages/dvc/data_cloud.py", line 6, in <module>
    from dvc.remote import get_remote
  File "/home/XXX/.local/lib/python3.6/site-packages/dvc/remote/__init__.py", line 4, in <module>
    from .ssh import SSHRemote
  File "/home/XXX/.local/lib/python3.6/site-packages/dvc/remote/ssh/__init__.py", line 17, in <module>
    from dvc.remote.base import BaseRemoteTree, Remote
ImportError: cannot import name 'BaseRemoteTree'
------------------------------------------------------------
```

Thanks.

**Comment by pmrowla** [comment]
@shawnlee103 it looks like there is something wrong going on with your DVC installation, as the file `/dvc/remote/ssh/__init__.py` should not exist in DVC 1.2.2 (but it did exist in older versions): https://github.com/iterative/dvc/tree/1.2.2/dvc/remote

Could you try uninstalling and then reinstalling DVC and see if that fixes your issue?

**Comment by shawnlee103** [comment]
after pip install dvc[ssh].  It works.  Thanks.
