### ISSUE TITLE
TOML no included as a dependency in the conda build for dvc

### ISSUE THREAD

**Issue by yfarjoun** [iterative/dvc#4318]
when attempting to install dvc using the conda build `dvc=1.3.1=py37hc8dfbb8_0` I ended up with a non working dvc as it was missing the `toml` package, as reported by the error:

```
$ dvc
<SNIP>
    import toml
ModuleNotFoundError: No module named 'toml'
```

It seems that `toml` wasn't added to the prerequisites of the dvc conda build. 

I would like to suggest two things:

1. Add toml (v0.10.1 seems to work) to the conda recipe.
2. Add a test that creates a conda environment for dvc and tests it as part of the CI so that this doesn't happen again and that the recipes remain uptodate.

THANKS!

**Comment by efiop** [comment]
@yfarjoun Coul you please show full traceback?

**Comment by yfarjoun** [comment]
```
Traceback (most recent call last):
  File "/ROOT/bin/dvc", line 7, in <module>
    from dvc.main import main
  File "/ROOT/lib/python3.7/site-packages/dvc/main.py", line 6, in <module>
    from dvc import analytics
  File "/ROOT/lib/python3.7/site-packages/dvc/analytics.py", line 17, in <module>
    from dvc.repo import Repo
  File "/ROOT/lib/python3.7/site-packages/dvc/repo/__init__.py", line 9, in <module>
    from dvc.dvcfile import PIPELINE_FILE, Dvcfile, is_valid_filename
  File "/ROOT/lib/python3.7/site-packages/dvc/dvcfile.py", line 9, in <module>
    from dvc.stage import serialize
  File "/ROOT/lib/python3.7/site-packages/dvc/stage/__init__.py", line 8, in <module>
    import dvc.dependency as dependency
  File "/ROOT/lib/python3.7/site-packages/dvc/dependency/__init__.py", line 11, in <module>
    from dvc.dependency.param import ParamsDependency
  File "/ROOT/lib/python3.7/site-packages/dvc/dependency/param.py", line 5, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
```
