### ISSUE TITLE
pylint: crashing on commit

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4357]
## Bug Report

I've followed https://dvc.org/doc/user-guide/contributing/core#development-environment but I get this when trying to commit:

```
$ git commit
...
pylint...................................................................Failed
- hook id: pylint
- exit code: 1

Traceback (most recent call last):
  File "C:\Users\poj12\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\poj12\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\poj12\dvc\.venv\Scripts\pylint.EXE\__main__.py", line 9, in <module>
  File "c:\users\poj12\dvc\.venv\lib\site-packages\pylint\__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "c:\users\poj12\dvc\.venv\lib\site-packages\pylint\lint\run.py", line 303, in __init__
    linter.load_plugin_modules(plugins)
  File "c:\users\poj12\dvc\.venv\lib\site-packages\pylint\lint\pylinter.py", line 499, in load_plugin_modules
    module.register(self)
  File "c:\users\poj12\dvc\.venv\lib\site-packages\pylint_pytest\__init__.py", line 24, in register
    checker = importlib.import_module(module, package=os.path.basename(dirname))
  File "C:\Users\poj12\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '\\checkers\\class_attr_loader'
```
### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
WARNING: Unable to detect supported link types, as cache directory '.dvc\cache' doesn't exist. It is usually auto-created by commands such as `dvc add/fetch/pull/run/import`, but you could create it manually to enable this check.
DVC version: 1.4.0
---------------------------------
Platform: Python 3.8.2 on Windows-10-10.0.18362-SP0
Supports: All remotes
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by skshetry** [comment]
Related to https://github.com/reverbc/pylint-pytest/issues/1
