### ISSUE TITLE
push: uninformative error when no remote is set [qa]

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4394]
## Report

Conditions: No remote exists or none is set as default. Some data is tracked.

This probably applies to other sync commands, BTW:

```console
λ ls
data   data.dvc

λ dvc push dvc.yaml
ERROR: unexpected error - 'none'
```

### Please provide information about your setup

```console
λ dvc version
DVC version: 1.5.0+8cd4ee
---------------------------------
Platform: Python 3.8.2 on Windows-10-10.0.18362-SP0
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: NTFS on C:\
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Comment by efiop** [comment]
@jorgeorpinel Not able to reproduce, if there is no remote, this error is shown:
```
➜  myrepo git:(master) ✗ dvc push dvc.yaml                                                                 
ERROR: failed to push data to the cloud - config file error: no remote specified. Setup default remote with
    dvc remote default <remote name>                                                                       
or use:                                                                                                    
    dvc push -r <remote name>                                                                              
                                                                                                           
Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!                    
```

Could you post a verbose log?

**Comment by jorgeorpinel** [comment]
Sure, sorry for the delay:

```console
λ dvc push dvc.yaml
ERROR: unexpected error - 'none'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
(.venv) poj12@AP-QDVJ7BLR ~/DVC-repos/test (master)
λ dvc push dvc.yaml -v
2020-08-18 11:34:53,801 DEBUG: Check for update is enabled.
2020-08-18 11:34:54,149 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2020-08-18 11:34:54,467 DEBUG: Spawned '['daemon', '-q', 'updater']'
2020-08-18 11:34:54,512 DEBUG: fetched: [(3,)]
2020-08-18 11:34:54,527 DEBUG: fetched: [(3,)]
2020-08-18 11:34:54,532 ERROR: unexpected error - 'none'
------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\poj12\dvc\dvc\main.py", line 54, in main
    ret = cmd.run()
  File "c:\users\poj12\dvc\dvc\command\data_sync.py", line 50, in run
    processed_files_count = self.repo.push(
  File "c:\users\poj12\dvc\dvc\repo\__init__.py", line 34, in wrapper
    ret = f(repo, *args, **kwargs)
  File "c:\users\poj12\dvc\dvc\repo\push.py", line 35, in push
    return len(used_run_cache) + self.cloud.push(used, jobs, remote=remote)
  File "c:\users\poj12\dvc\dvc\data_cloud.py", line 63, in push
    remote = self.get_remote(remote, "push")
  File "c:\users\poj12\dvc\dvc\data_cloud.py", line 30, in get_remote
    return self._init_remote(name)
  File "c:\users\poj12\dvc\dvc\data_cloud.py", line 48, in _init_remote
    return get_remote(self.repo, name=name)
  File "c:\users\poj12\dvc\dvc\remote\__init__.py", line 8, in get_remote
    tree = get_cloud_tree(repo, **kwargs)
  File "c:\users\poj12\dvc\dvc\tree\__init__.py", line 81, in get_cloud_tree
    remote_conf = _get_conf(repo, **kwargs)
  File "c:\users\poj12\dvc\dvc\tree\__init__.py", line 43, in _get_conf
    remote_conf = repo.config["remote"][name.lower()]
KeyError: 'none'
------------------------------------------------------------

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2020-08-18 11:34:54,610 DEBUG: Analytics is disabled.
```

**Comment by efiop** [comment]
@jorgeorpinel And could you show your `.dvc/config`?

**Comment by jorgeorpinel** [comment]
Sorry, deleted the repo already but it was a simple test repo with a non-default local remote. I think it was:

```
λ dvc remote add local /tmp/dvc-storage/
λ cat .dvc/config
['remote "local"']
    url = C:/Users/poj12/AppData/Local/Temp/dvc-storage
```

**Comment by jorgeorpinel** [comment]
Maybe a problem in the path interpretation? Git Bash sees `/tmp/dvc-storage/` but the actual Windows location is `C:/Users/poj12/AppData/Local/Temp/dvc-storage`.

**Comment by efiop** [comment]
@jorgeorpinel I'm not sure. The fact that it tried to get a `none` remote might mean that your config was broken. Are you able to reproduce still?

**Comment by jorgeorpinel** [comment]
Yes @efiop, I can reproduce this in a dummy repo (created with 1.5) with any simple dvc.yaml file (even without outputs). On Windows/ Git Bash

**Comment by efiop** [comment]
Ok, need to take a closer look.

**Comment by jorgeorpinel** [comment]
Thanks

**Comment by efiop** [comment]
Closing as stale
