### ISSUE TITLE
unable to open database on mapped network drive

### ISSUE THREAD

**Issue by timbp** [iterative/dvc#4420]
I just installed dvc. My repository is on a mapped network drive, and dvc cannot open the database file. It seems to work perfectly if the repository is on the local C: drive. for the example below, I just made a repositiory on my home network storage, which is mapped to the Z: drive.

```
timbp@Eucalypt MINGW64 /z/MyVideos
$ git init
Initialized empty Git repository in //192.168.29.3/MyLibrary/MyVideos/.git/

timbp@Eucalypt MINGW64 /z/MyVideos (master)
$ dvc init

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|              https://dvc.org/doc/user-guide/analytics               |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: https://dvc.org/doc
- Get help and share ideas: https://dvc.org/chat
- Star us on GitHub: https://github.com/iterative/dvc

timbp@Eucalypt MINGW64 /z/MyVideos (master)
$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   .dvc/.gitignore
        new file:   .dvc/config
        new file:   .dvc/plots/confusion.json
        new file:   .dvc/plots/default.json
        new file:   .dvc/plots/scatter.json
        new file:   .dvc/plots/smooth.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        chasings.mp4

timbp@Eucalypt MINGW64 /z/MyVideos (master)
$ git commit -m "testing"
[master (root-commit) 1f5f95a] testing
 6 files changed, 128 insertions(+)
 create mode 100644 .dvc/.gitignore
 create mode 100644 .dvc/config
 create mode 100644 .dvc/plots/confusion.json
 create mode 100644 .dvc/plots/default.json
 create mode 100644 .dvc/plots/scatter.json
 create mode 100644 .dvc/plots/smooth.json

timbp@Eucalypt MINGW64 /z/MyVideos (master)
$ dvc add chasings.mp4
ERROR: unexpected error - unable to open database file

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!

timbp@Eucalypt MINGW64 /z/MyVideos (master)
$ dvc status
ERROR: failed to obtain data status - unable to open database file

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!

timbp@Eucalypt MINGW64 /z/MyVideos (master)
$ dvc version
WARNING: Unable to detect supported link types, as cache directory '\\192.168.29.3\MyLibrary\MyVideos\.dvc\cache' doesn't exist. It is usually auto-created by commands such as `dvc add/fetch/pull/run/import`, but you could create it manually to enable this check.
DVC version: 1.5.0 (pip)
---------------------------------
Platform: Python 3.8.3 on Windows-10-10.0.19041-SP0
Supports: http, https
Repo: dvc, git

timbp@Eucalypt MINGW64 /z/MyVideos (master)
$ ls -l .dvc
total 0
-rw-r--r-- 1 timbp 197121 0 Aug 19 12:21 config
drwxr-xr-x 1 timbp 197121 0 Aug 19 12:21 plots/
drwxr-xr-x 1 timbp 197121 0 Aug 19 12:32 tmp/

timbp@Eucalypt MINGW64 /z/MyVideos (master)
$ ls -l .dvc/tmp/
total 2048
drwxr-xr-x 1 timbp 197121 0 Aug 19 12:21 index/
-rw-r--r-- 1 timbp 197121 7 Aug 19 12:33 lock
-rw-r--r-- 1 timbp 197121 7 Aug 19 12:33 updater.lock

```

**Comment by pared** [comment]
Hi @timbp, it seems that `Sqlite` has problem handling state database over network. 
What is your setup? Maybe we could propose different setup for your use case?
Why would you store projects on network disc? Upon running something, wouldn't you still use the resources of your machine? Maybe you could use the network drive as a data cache?

**Comment by timbp** [comment]
The situation is I recently joined a university health research group. Lots of people with minimal statistics or data management training working on different aspects of the project. No formal data management or version control.  Everyone has their own informal system of making and naming backup copies. One of my input files is "Copy of Copy of  Denom final_corrected-v2.xlsx". I had to replicate some results produced a year ago -- but my numbers (produced in R) were completely different. I tracked down what I think are the correct versions of the original analyst's SAS programs and ran them. Results not identical to mine, but very close. Most likely the data have changed, but nobody knows when, why, or how.

I don't think I'm in a position to change practice yet. But I do want to track what input data I am using, and be able to replicate any of my results any time in the future. So I did a search and discovered dvc, which seems ideal.

Much of the data is fully identified medical data. It must be stored on the network drive. I am happy to have the git repo on my local drive, and have the programs read and write data on the network drive. But I am not in a position to change other people's practice (yet). I need to leave the data files in the various directories where other people are using them, I have read the User Guide section on external data, but it's not clear to me how to set up for my situation.

**Comment by pared** [comment]
@timbp 
I understand this scenario makes perfect sense.
I don't think we can work around `state`, which seems to be an issue here. 
It seems to me that in that case, the best fit for you would be to use the external data.
I've got a question though: is this network storage mounted on a constant path, on users' machines?

**Comment by shcheklein** [comment]
@pared @timbp how about doing a cache (`dvc cache dir`) on that drive and use symlinks semantics to read files?

This way we get duplication for files that we put into DVC, but at least we won't have to deal with `--external`, which is nice.

**Comment by gamis** [comment]
It would be really nice if we can at least get some meaningful error message. I just spent a bunch of time to figure out why a perfectly fine looking clone of my repo couldn't `dvc pull` anything. It was because it's a remote mount. 

We set up a nice 10gbps switch so that we can keep most of our stuff on a centralized file server. It's a shame that dvc can't come along with us.

**Comment by pared** [comment]
@gamis 
The error you get is `unable to open database file`?

**Comment by gamis** [comment]
That's correct. And I keep checking to see if there's something wrong with the state file (not even created yet) or the permissions on the tmp directory or something. No leads until I search for this error message on github.

Apart from a more meaningful error message, I wonder if (at least for this situation), the sqlite database could be moved to %TEMP% instead, which is surely on a local drive.

**Comment by efiop** [comment]
@gamis Could you show a verbose log for the error you are getting?

**Comment by gamis** [comment]
```
dvc status --verbose
2021-02-01 15:40:34,009 DEBUG: Check for update is disabled.
2021-02-01 15:40:34,040 ERROR: unexpected error - unable to open database file
------------------------------------------------------------
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\dvc\main.py", line 90, in main
    ret = cmd.run()
  File "c:\program files\python38\lib\site-packages\dvc\command\status.py", line 49, in run
    st = self.repo.status(
  File "c:\program files\python38\lib\site-packages\dvc\repo\__init__.py", line 53, in wrapper
    with lock_repo(repo):
  File "c:\program files\python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "c:\program files\python38\lib\site-packages\dvc\repo\__init__.py", line 41, in lock_repo
    with repo.lock, repo.state:
  File "c:\program files\python38\lib\site-packages\dvc\state.py", line 65, in __enter__
    self.load()
  File "c:\program files\python38\lib\site-packages\dvc\state.py", line 259, in load
    self.database = _connect_sqlite(self.state_file, {"nolock": 1})
  File "c:\program files\python38\lib\site-packages\dvc\state.py", line 527, in _connect_sqlite
    return sqlite3.connect(uri, uri=True)
sqlite3.OperationalError: unable to open database file
------------------------------------------------------------
2021-02-01 15:40:35,087 DEBUG: Version info for developers:
DVC version: 1.11.10 (pip)
---------------------------------
Platform: Python 3.8.6 on Windows-10-10.0.18362-SP0
Supports: All remotes
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: local, ssh, ssh
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-02-01 15:40:35,087 DEBUG: Analytics is enabled.
2021-02-01 15:40:35,446 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\AmisG01\\AppData\\Local\\Temp\\tmp18ye29i5']'
2021-02-01 15:40:35,524 DEBUG: Spawned '['daemon', '-q', 'analytics', 'C:\\Users\\AmisG01\\AppData\\Local\\Temp\\tmp18ye29i5']'
```

**Comment by MohammadsAdrA-AI** [comment]
I have the same issue, in our company we prefer to use our map network. Is this feature going to add soon?

**Comment by ivsanro1** [comment]
This is also happening to me, when working with DvC inside a docker and my repository is mounted as a volume. Very easy to reproduce. I think it's a sqlite problem more than DvC's

**Comment by efiop** [comment]
@ivsanro1 Could you show `dvc doctor` output, please?

**Comment by ivsanro1** [comment]
@efiop 
```
root@ec3f6e13f0c7:~/work/data_extraction_quickstart# dvc doctor
DVC version: 1.11.16 (pip)
---------------------------------
Platform: Python 3.7.10 on Linux-4.19.121-linuxkit-x86_64-with-Ubuntu-18.04-bionic
Supports: All remotes
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Repo: dvc, git

```
I have the error if I run `dvc init` inside the docker though.
However, I fixed it by running `dvc init` on the repo in the host machine, and then doing `dvc status` inside the docker container does not report any error so far.

**Comment by efiop** [comment]
@ivsanro1 Thanks! We are aware of this problem on nfs, cifs, overlayfs, etc and will be looking into it deeply in the coming weeks as 2.0 QA. Thank you for the feedback and stay tuned! :pray:

**Comment by ivsanro1** [comment]
Thank you @efiop 

Just for the record, today I tried to make a `dvc push` from inside the docker and it has a similar problem. Since this is not just a one-time command as `dvc init`, I will not be able to use DVC inside this docker environment with mounted repository for now, unfortunately.

```
root@441ff821e349:~/work/data_extraction_quickstart# dvc push
ERROR: unexpected error                                                         
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dvc/main.py", line 50, in main
    ret = cmd.run()
  File "/usr/local/lib/python3.7/dist-packages/dvc/command/data_sync.py", line 66, in run
    glob=self.args.glob,
  File "/usr/local/lib/python3.7/dist-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/dvc/repo/push.py", line 38, in push
    revs=revs,
  File "/usr/local/lib/python3.7/dist-packages/dvc/repo/__init__.py", line 397, in used_cache
    filter_info=filter_info,
  File "/usr/local/lib/python3.7/dist-packages/dvc/stage/__init__.py", line 621, in get_used_cache
    cache.update(out.get_used_cache(*args, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/dvc/output/base.py", line 608, in get_used_cache
    self.hash_info.value, self.collect_used_dir_cache(**kwargs),
  File "/usr/local/lib/python3.7/dist-packages/dvc/output/base.py", line 533, in collect_used_dir_cache
    self.get_dir_cache(jobs=jobs, remote=remote)
  File "/usr/local/lib/python3.7/dist-packages/dvc/output/base.py", line 492, in get_dir_cache
    objects.check(self.odb, self.odb.get(self.hash_info))
  File "/usr/local/lib/python3.7/dist-packages/dvc/objects/__init__.py", line 198, in check
    odb.check(obj.hash_info)
  File "/usr/local/lib/python3.7/dist-packages/dvc/objects/db/base.py", line 109, in check
    obj.check(self)
  File "/usr/local/lib/python3.7/dist-packages/dvc/objects/__init__.py", line 39, in check
    actual = get_hash(self.path_info, self.fs, odb.fs.PARAM_CHECKSUM, odb)
  File "/usr/local/lib/python3.7/dist-packages/dvc/objects/stage.py", line 106, in get_hash
    hash_info = state.get(path_info, fs)
  File "/usr/local/lib/python3.7/dist-packages/dvc/state.py", line 138, in get
    value = self.md5s.get(inode)
  File "/usr/local/lib/python3.7/dist-packages/diskcache/core.py", line 1189, in get
    with self._transact(retry) as (sql, _):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/dist-packages/diskcache/core.py", line 733, in _transact
    raise Timeout from None
diskcache.core.Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dvc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/dvc/main.py", line 83, in main
    dvc_info = get_dvc_info()
  File "/usr/local/lib/python3.7/dist-packages/dvc/info.py", line 34, in get_dvc_info
    repo = Repo()
  File "/usr/local/lib/python3.7/dist-packages/dvc/repo/__init__.py", line 189, in __init__
    self.state = State(self.root_dir, self.tmp_dir)
  File "/usr/local/lib/python3.7/dist-packages/dvc/state.py", line 80, in __init__
    self.links = Cache(directory=os.path.join(tmp_dir, "links"), **config)
  File "/usr/local/lib/python3.7/dist-packages/diskcache/core.py", line 481, in __init__
    self.reset(key, value, update=False)
  File "/usr/local/lib/python3.7/dist-packages/diskcache/core.py", line 2446, in reset
    'PRAGMA %s' % (pragma)
sqlite3.OperationalError: unable to open database file
```

I also tried upgrading to the new 2.0.1 version, but still the same error:

```
root@441ff821e349:~/work/data_extraction_quickstart# dvc doctor
DVC version: 2.0.1 (pip)
---------------------------------
Platform: Python 3.7.10 on Linux-4.19.121-linuxkit-x86_64-with-Ubuntu-18.04-bionic
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: fuse.grpcfuse on grpcfuse
Caches: local
Remotes: gs
Workspace directory: fuse.grpcfuse on grpcfuse
Repo: dvc, git
```

Let me know if I can help with anything regarding this issue.

**Comment by efiop** [comment]
@ivsanro1 We've created an umbrella issue #5562 for this and will be looking at it closely in the following weeks. Thanks again for the feedback!

**Comment by agurtovoy** [comment]
If anyone is looking for a workaround for this while the team is working on a more permanent fix, installing DVC from [this fork](https://github.com/agurtovoy/dvc) will allow you to configure DVC to store its SQLite-based state and remote indexes somewhere else:

```
python -m pip install "git+https://github.com/agurtovoy/dvc.git#egg=dvc[s3]"

dvc config state.dir /tmp
dvc config index.dir /tmp
```

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/dvc/pull/6419
