### ISSUE TITLE
import/get: broken for local repos on Windows?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4421]
## Bug Report

UPDATE: May be a sub-case of #4423 but the error is different.

```console
λ dvc import ../test/ data
Importing 'data (../test/)' -> 'data'
ERROR: unexpected error - 'none'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
Traceback (most recent call last):
  File "C:\Users\poj12\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 617, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\poj12\\AppData\\Local\\Temp\\tmp1vkpjhz7dvc-clone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\poj12\dvc\.venv\Scripts\dvc-script.py", line 12, in <module>
    sys.exit(main())
  File "c:\users\poj12\dvc\dvc\main.py", line 106, in main
    clean_repos()
  File "c:\users\poj12\dvc\dvc\external_repo.py", line 71, in clean_repos
    _remove(path)
  File "c:\users\poj12\dvc\dvc\external_repo.py", line 368, in _remove
    os_retry(remove)(path)
  File "c:\users\poj12\dvc\.venv\lib\site-packages\funcy\decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "c:\users\poj12\dvc\.venv\lib\site-packages\funcy\flow.py", line 122, in retry
    return call()
  File "c:\users\poj12\dvc\.venv\lib\site-packages\funcy\decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "c:\users\poj12\dvc\dvc\utils\fs.py", line 136, in remove
    shutil.rmtree(path, onerror=_chmod)
  File "C:\Users\poj12\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\poj12\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\poj12\dvc\dvc\utils\fs.py", line 121, in _chmod
    func(p)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\poj12\\AppData\\Local\\Temp\\tmp1vkpjhz7dvc-clone'
```

### Please provide information about your setup

**Output of `dvc version`:**

```console
λ dvc version
DVC version: 1.5.0+8cd4ee
---------------------------------
Platform: Python 3.8.2 on Windows-10-10.0.18362-SP0
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: NTFS on C:\
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Comment by jorgeorpinel** [comment]
p.s. I tried several files, so I don't think it's a weird Win lock on that one particularly.

**Comment by skshetry** [comment]
@jorgeorpinel, can you please post the verbose log?

**Comment by jorgeorpinel** [comment]
Sure, see below. Also, note that it may be a sub-case of #4423 but the error is different.

<details>

```console
λ dvc import ../test/ data -v
2020-08-18 23:31:03,738 DEBUG: Check for update is enabled.
2020-08-18 23:31:04,475 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2020-08-18 23:31:05,082 DEBUG: Spawned '['daemon', '-q', 'updater']'
2020-08-18 23:31:05,110 DEBUG: fetched: [(3,)]
2020-08-18 23:31:06,146 DEBUG: Removing output 'data' of stage: 'data.dvc'.
Importing 'data (../test/)' -> 'data'
2020-08-18 23:31:06,155 DEBUG: Computed stage: 'data.dvc' md5: '906d4db6e2ef191224bd0e7462f7d73c'
2020-08-18 23:31:06,158 DEBUG: 'md5' of stage: 'data.dvc' changed.
2020-08-18 23:31:06,160 DEBUG: Creating external repo ../test/@None
2020-08-18 23:31:06,162 DEBUG: erepo: git clone '../test/' to a temporary dir
2020-08-18 23:31:08,041 DEBUG: fetched: [(45,)]
2020-08-18 23:31:08,052 ERROR: unexpected error - 'none'
------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\poj12\dvc\dvc\main.py", line 54, in main
    ret = cmd.run()
  File "c:\users\poj12\dvc\dvc\command\imp.py", line 14, in run
    self.repo.imp(
  File "c:\users\poj12\dvc\dvc\repo\imp.py", line 6, in imp
    return self.imp_url(path, out=out, erepo=erepo, frozen=True)
  File "c:\users\poj12\dvc\dvc\repo\__init__.py", line 34, in wrapper
    ret = f(repo, *args, **kwargs)
  File "c:\users\poj12\dvc\dvc\repo\scm_context.py", line 4, in run
    result = method(repo, *args, **kw)
  File "c:\users\poj12\dvc\dvc\repo\imp_url.py", line 54, in imp_url
    stage.run()
  File "c:\users\poj12\dvc\.venv\lib\site-packages\funcy\decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "c:\users\poj12\dvc\dvc\stage\decorators.py", line 36, in rwlocked
    return call()
  File "c:\users\poj12\dvc\.venv\lib\site-packages\funcy\decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "c:\users\poj12\dvc\dvc\stage\__init__.py", line 429, in run
    sync_import(self, dry, force)
  File "c:\users\poj12\dvc\dvc\stage\imports.py", line 30, in sync_import
    stage.deps[0].download(stage.outs[0])
  File "c:\users\poj12\dvc\dvc\dependency\repo.py", line 91, in download
    with self._make_repo() as repo:
  File "C:\Users\poj12\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "c:\users\poj12\dvc\dvc\external_repo.py", line 40, in external_repo
    repo = ExternalRepo(path, url, rev, for_write=for_write)
  File "c:\users\poj12\dvc\dvc\external_repo.py", line 182, in __init__
    self._fix_upstream()
  File "c:\users\poj12\dvc\dvc\external_repo.py", line 210, in _fix_upstream
    self._fix_local_remote(src_repo, remote_name)
  File "c:\users\poj12\dvc\dvc\external_repo.py", line 220, in _fix_local_remote
    new_remote = self.config["remote"][remote_name]
KeyError: 'none'
------------------------------------------------------------

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2020-08-18 23:31:08,139 DEBUG: Analytics is disabled.
Traceback (most recent call last):
  File "C:\Users\poj12\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 617, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\poj12\\AppData\\Local\\Temp\\tmpfjdih7y_dvc-clone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\poj12\dvc\.venv\Scripts\dvc-script.py", line 12, in <module>
    sys.exit(main())
  File "c:\users\poj12\dvc\dvc\main.py", line 106, in main
    clean_repos()
  File "c:\users\poj12\dvc\dvc\external_repo.py", line 71, in clean_repos
    _remove(path)
  File "c:\users\poj12\dvc\dvc\external_repo.py", line 368, in _remove
    os_retry(remove)(path)
  File "c:\users\poj12\dvc\.venv\lib\site-packages\funcy\decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "c:\users\poj12\dvc\.venv\lib\site-packages\funcy\flow.py", line 122, in retry
    return call()
  File "c:\users\poj12\dvc\.venv\lib\site-packages\funcy\decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "c:\users\poj12\dvc\dvc\utils\fs.py", line 136, in remove
    shutil.rmtree(path, onerror=_chmod)
  File "C:\Users\poj12\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\poj12\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\poj12\dvc\dvc\utils\fs.py", line 121, in _chmod
    func(p)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\poj12\\AppData\\Local\\Temp\\tmpfjdih7y_dvc-clone'
```

</details>

**Comment by jorgeorpinel** [comment]
Just re-tried this in the same setup but DVC 2.3.0

```console
λ dvc version
DVC version: 2.3.0 (exe)
---------------------------------
Platform: Python 3.8.10 on Windows-10-10.0.19042-SP0
Supports: All remotes
```

And it's no longer happening 🤷
