### ISSUE TITLE
ImportError: cannot import name 'check_if_numbers_are_consecutive'

### ISSUE THREAD

**Issue by raimannma** [iterative/dvc#4499]
# Bug Report

## Behavior

If there is a folder named "util" in your path, then the dvc repro command fails with this error message using the cml docker image:

```
2020-08-30 08:57:43,226 DEBUG: fetched: [(3,)]
 2020-08-30 08:57:43,228 DEBUG: fetched: [(21770,)]
 2020-08-30 08:57:43,246 ERROR: unexpected error - cannot import name 'check_if_numbers_are_consecutive'
 ------------------------------------------------------------
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/dist-packages/dvc/main.py", line 75, in main
     ret = cmd.run()
   File "/usr/local/lib/python3.6/dist-packages/dvc/command/repro.py", line 47, in run
     params=self.args.params,
   File "/usr/local/lib/python3.6/dist-packages/dvc/repo/__init__.py", line 34, in wrapper
     ret = f(repo, *args, **kwargs)
   File "/usr/local/lib/python3.6/dist-packages/dvc/repo/scm_context.py", line 4, in run
     result = method(repo, *args, **kw)
   File "/usr/local/lib/python3.6/dist-packages/dvc/repo/reproduce.py", line 74, in reproduce
     params = _parse_params(kwargs.pop("params", []))
   File "/usr/local/lib/python3.6/dist-packages/dvc/repo/reproduce.py", line 122, in _parse_params
     from flatten_json import unflatten
   File "/usr/local/lib/python3.6/dist-packages/flatten_json.py", line 13, in <module>
     from util import check_if_numbers_are_consecutive
 ImportError: cannot import name 'check_if_numbers_are_consecutive'
 ------------------------------------------------------------
 Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
 2020-08-30 08:57:43,249 DEBUG: Analytics is enabled.
 2020-08-30 08:57:43,279 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpkskduifx']'
 2020-08-30 08:57:43,280 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpkskduifx']'
```

## Possible Solution

Remove or rename the util directory.

A better solution would be to fix the dependency flatten_json.
Since flatten_json has a bad import statement here: [https://github.com/amirziai/flatten/blob/e48fe4932e6ad3d397546f711f7dad4470287810/flatten_json.py#L13](https://github.com/amirziai/flatten/blob/e48fe4932e6ad3d397546f711f7dad4470287810/flatten_json.py#L13)

## Context (Environment)
This only occurs if you are using dvc and cml in your pipeline while having a folder named util in the same directory as the dvc.yaml file you are trying to reproduce in the CI.

**Output of `dvc version`:**
```console
$ dvc version
 DVC version: 1.6.4 (pip)
 ---------------------------------
 Platform: Python 3.8.2 on Linux-4.19.0-9-amd64-x86_64-with-glibc2.29
 Supports: All remotes
 Workspace directory: ext4 on /dev/sda2
 Repo: dvc, git
```

**Comment by efiop** [comment]
Discord context: https://discordapp.com/channels/485586884165107732/485596304961962003/749742779516584077

For the record, that bug was fixed in flatten_json 1.8.0 but it had another bug, which made them yank the 1.8.0 off of pypi: https://github.com/amirziai/flatten/issues/65 . Our options are:

1) wait for a new release (bug is mitigated by not having that dir in your project)
2) monkey patch the bug (not worth the hustle)
3) move to another library (e.g. flatten-dict). This one might be the simplest one, but need to double-check.

**Comment by efiop** [comment]
Ok, flatten-dict works nicely and has everything we need (at least so far). Moving to it.

**Comment by efiop** [comment]
@raimannma 1.6.6 is out with the fix. Please upgrade and give it a try :slightly_smiling_face: Thank you so much for the feedback! :pray:
