### ISSUE TITLE
dvc fails on LocalTree.protect() on files owned by other users when shared cache is enabled

### ISSUE THREAD

**Issue by aartaria** [iterative/dvc#4545]
We are currently facing an issue while trying to run dvc commands (e.g. status or checkout) when some of cache files are owned by other users in the same user group even if we enable the shared cache in the dvc config file.

### Scenario
user `arr` runs
```
$ dvc status -v
2020-09-08 11:53:50,966 DEBUG: Check for update is enabled.
+-----------------------------------------+
|                                         |
|     Update available 1.6.0 -> 1.6.1     |
|     Run `pip install dvc --upgrade`     |
|                                         |
+-----------------------------------------+

2020-09-08 11:53:51,144 DEBUG: Path '/home/arr/repos/repo/.dvc/cache/56/060bde8ada1765fdd36071811c1859' inode '18331067'
2020-09-08 11:53:51,144 DEBUG: fetched: [('1599464491994896384', '221', '56060bde8ada1765fdd36071811c1859', '1599558826898213120')]
2020-09-08 11:53:51,144 DEBUG: cache '/home/arr/repos/repo/.dvc/cache/56/060bde8ada1765fdd36071811c1859' expected '56060bde8ada1765fdd36071811c1859' actual '56060bde8ada1765fdd36071811c1859'
2020-09-08 11:53:51,151 DEBUG: fetched: [(381516,)]
2020-09-08 11:53:51,194 ERROR: failed to obtain data status - [Errno 1] Operation not permitted: '/home/arr/repos/repo/.dvc/cache/56/060bde8ada1765fdd36071811c1859'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/dvc/command/status.py", line 51, in run
    recursive=self.args.recursive,
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/dvc/repo/__init__.py", line 34, in wrapper
    ret = f(repo, *args, **kwargs)
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/dvc/repo/status.py", line 150, in status
    self, targets, with_deps=with_deps, recursive=recursive
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/dvc/repo/status.py", line 37, in _local_status
    return _joint_status(stages)
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/dvc/repo/status.py", line 23, in _joint_status
    status_info.update(stage.status(check_updates=True))
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/dvc/stage/__init__.py", line 478, in status
    self._status_outs(ret)
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/dvc/stage/__init__.py", line 498, in _status_outs
    outs_status = self._status(self.outs)
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/dvc/stage/__init__.py", line 488, in _status
    ret.update(entry.status())
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/dvc/output/base.py", line 223, in status
    if self.checksum and self.use_cache and self.changed_cache():
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/dvc/output/base.py", line 208, in changed_cache
    return self.cache.changed_cache(self.checksum, filter_info=filter_info)
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/dvc/cache/base.py", line 365, in changed_cache
    return self.changed_cache_file(hash_)
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/dvc/cache/base.py", line 334, in changed_cache_file
    self.tree.protect(cache_info)
  File "/home/arr/.conda/envs/myenv/lib/python3.7/site-packages/dvc/tree/local.py", line 292, in protect
    os.chmod(path, mode)
PermissionError: [Errno 1] Operation not permitted: '/home/arr/repos/repo/.dvc/cache/56/060bde8ada1765fdd36071811c1859'
------------------------------------------------------------

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2020-09-08 11:53:51,201 DEBUG: Analytics is enabled.
2020-09-08 11:53:51,264 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpae54wzfw']'
2020-09-08 11:53:51,265 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpae54wzfw']'
```
while the file where it fails has following permissions

```
$ ls /home/arr/repos/repo/.dvc/cache/56/060bde8ada1765fdd36071811c1859
 -rw-rw-r-- 1 koi DataScientists 221 Sep  7 09:41 /home/arr/repos/repo/.dvc/cache/56/060bde8ada1765fdd36071811c1859
```

note that all the users accessing the cache belong to the same user group

### Context
To contextualize the issue

- `.dvc/config`
```
[cache]
    dir = cache
    shared = group
['remote "my_remote"']
    url = s3://my-remote-cache/
```
`.dvc/cache` is symlinked to the shared cache folder (we have also tried to reference in .dvc/config to the actual directory path but the problem persists)

```
$ dvc version
DVC version: 1.6.0 (pip)
---------------------------------
Platform: Python 3.7.7 on Linux-5.4.0-45-generic-x86_64-with-debian-buster-sid
Supports: http, https, s3
Cache types: hardlink, symlink
Cache directory: xfs on /dev/sda
Workspace directory: xfs on /dev/sda
Repo: dvc, git
```

### Final Thoughts
I'm not familiar with the dvc code base but I guess this might have something to do with the permission set here:
https://github.com/iterative/dvc/blob/61bf1194c3b461a9ad044ad7cc463d7538142e45/dvc/tree/local.py#L286

tried changing that line of code with
```
        if self.isfile(path_info):
            mode = self.file_mode
        else:
            mode = self.dir_mode
```

and this let the operations run, but I can hardly judge if it won't destroy anything else.

**Comment by wdixon** [comment]
We relatively new to using DVC - and have just gone through some iteration using shared cache - that I will share.

We are using a single cache for several projects (for data registries, as well as projects that use DVC import to position the data relative to training/model building scripts).  For the shared cache, you need to make sure that all the aa..ff cache sub directories are 0775, and you likely have users in multiple groups, so you should also set the group sticky bit (g+s) on the cache sub directories.

We have also found that the use of "hardlinks" are problematic with permissions - and have opted to use "symlinks" as the cache.type (which is likely the issue you are facing).

Our .dvc/config file has a cache entry:
```bash
[cache]
    type = "symlink,copy"
    shared = group
```

and we have a non tracked (.dvc/cache.local) - that sets the user and machine specific location to the shared cache.  It was important for us not to add machine specific paths/configuration to the git repository; however, this does mean that folks need to remember to add this to their local configuration.
 
```bash
[cache]
    dir = /projects/xxx/shared_dvc_cache
```

We have submitted a [feature request](https://github.com/iterative/dvc/issues/4545) that would allow project specific overrides to appear in the users global configuration.

You may also want to be on dvc 1.6.4 or better - the dvc folks did make some significant performance improvements that were important for us.

**Comment by aartaria** [comment]
Hey thank you @wdixon for your feedback,

- about the link type: The current link strategy adopted in our project is the `copy` strategy (since reflink are not supported from our filesystem and dvc will fallback to `copy`), but anyway I guess that independently from the link type the `shared=group` attribute should allow members of the same user group to run dvc commands on the shared cache, and I don't even know how relevant the link type is to this issue since my guess is that it relates to the dvc cache and not the project artifacts.
- about the sticky bit: I thought that with dvc 1.x would not be necessary anymore to use the sticky bit operation, but on some tests I've run yes, it looks like it is still necessary, or I'm I setting something wrong? Even though I think that this should not relate to the reported case since the user permission of the file look proper to my understanding.
- Finally about your feature request (btw the link is wrong) I guess could be useful for us too. How we addressed it currently is just to symlink the cache folder explicitly, but yes it is just another manual step.

**Comment by wdixon** [comment]
I believe chmod requires you own the file (or you are root) - so from your exception above - perhaps you are not the user "koi"...    When using shared=group - I think it tries to set the file attributes readonly (which can't happen if you are not the owner) - was this perhaps added to the cache before setting it to be shared?

We are not using copy - as it duplicates the storage between the cache and the checkout...  I suppose using a shared cache/copy mode might reduce the duplication from (N + N) to (N + 1), where N is the number of user checkouts on the system and 1 = the cache copy).  If you use links (reflink/hardlink/symlink) - you only have 1 copy and all the checkouts point into the cache to prevent duplication.

While reflinks (copy on write) - would be ideal - DVC does attempt to protect the links by making the files read only (though there still would be a risk of cache corruption if a user forcibly modified the read-only file).... Not having reflinks either, we had initially opted for hardlinks; however, soon ran into permission issues - and later switched to symlinks (so far so good!)

**Comment by aartaria** [comment]
yes that's the issue, LocalTree.protect() tries to change the mode to readonly though in a shared cache by construction you will not own all the files, so this Exception has to be treated accordingly I guess (or it should not even try to protect the file).
I've also tried to reinit the cache from scratch to make sure that the group flag was set at cache folder creation time, but no luck still same issue when trying to access it with other users.

**Comment by efiop** [comment]
Hi @aartaria ! Sorry for the delay. Dvc expects all cache files to have 0444 permissions, to be protected from corruption. That particular file was probably added by someone using an old (pre-1.0) dvc version. Could you try chmoding all cache files to 0444 and run your command again to see if it works?

**Comment by aartaria** [comment]
@efiop thank you for the suggestion, it looks to have solved our issues! I must have done something wrong while recreating the cache from the remote storage when upgrading to dvc 1.x
