### ISSUE TITLE
dvc repro -e crashes when executed on detached head

### ISSUE THREAD

**Issue by yogi81** [iterative/dvc#4585]
### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
```
1.7.2
**Additional Information (if any):**
execute dvc repro -e on a detached HEAD you get an error that origin/HEAD was not found

Here is stack trace

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.
```
2020-09-21 16:46:48,685 DEBUG: Check for update is enabled.
2020-09-21 16:46:48,686 DEBUG: assuming default target 'dvc.yaml'.
2020-09-21 16:46:48,687 DEBUG: fetched: [(3,)]                        
2020-09-21 16:46:48,720 DEBUG: fetched: [(68,)]
2020-09-21 16:46:48,728 ERROR: unexpected error - No item found with id 'origin/HEAD': 'IterableList' object has no attribute 'origin/HEAD'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/git/util.py", line 881, in __getitem__
    return getattr(self, index)
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/git/util.py", line 874, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'origin/HEAD'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/main.py", line 76, in main
    ret = cmd.run()
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/command/repro.py", line 47, in run
    params=self.args.params,
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/repo/scm_context.py", line 4, in run
    result = method(repo, *args, **kw)
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/repo/reproduce.py", line 89, in reproduce
    **kwargs,
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/repo/reproduce.py", line 151, in _reproduce_experiments
    return repo.experiments.reproduce_one(**kwargs)
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/repo/experiments/__init__.py", line 274, in reproduce_one
    stash_rev = self.new(**kwargs)
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/repo/experiments/__init__.py", line 36, in wrapper
    return f(exp, *args, **kwargs)
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/repo/experiments/__init__.py", line 306, in new
    self._scm_checkout(rev)
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/repo/experiments/__init__.py", line 168, in _scm_checkout
    self._checkout_default_branch()
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/repo/experiments/__init__.py", line 178, in _checkout_default_branch
    ref = origin_refs["HEAD"].reference
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/git/util.py", line 883, in __getitem__
    raise IndexError("No item found with id %r" % (self._prefix + index)) from e
IndexError: No item found with id 'origin/HEAD'
```

**Comment by pmrowla** [comment]
To clarify, this will occur if the initial experiments clone happens while the parent repo is on a detached head, since `.git/refs/heads` in the clone will end up empty in this scenario. For the case where `.dvc/experiments` has already been cloned and then the parent workspace is switched to a detached head, experiments repro appears to work correctly for me.
