### ISSUE TITLE
dvc exp show -T crashes with unknown Git revision <revision>, <tag name>

### ISSUE THREAD

**Issue by yogi81** [iterative/dvc#4587]
### Please provide information about your setup

when running dvc exp show -T, the program crashes 

**Output of `dvc version`:**

```console
$ dvc version
```
1.7.2
**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.
```
dvc exp show -T -v
2020-09-21 17:33:07,541 DEBUG: Check for update is enabled.
2020-09-21 17:33:07,570 DEBUG: fetched: [(3,)]                        
2020-09-21 17:33:08,049 DEBUG: fetched: [(75,)]
2020-09-21 17:33:08,058 ERROR: failed to show experiments - unknown Git revision 'f97e3cca64d10c299f7e9e54dd22889c6ee7a1b4, decouple/base'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/command/experiments.py", line 258, in run
    sha_only=self.args.sha,
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/repo/experiments/__init__.py", line 616, in show
    return show(self.repo, *args, **kwargs)
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/repo/experiments/show.py", line 73, in show
    repo, rev, sha_only=sha_only
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/repo/experiments/show.py", line 16, in _collect_experiment
    for rev in repo.brancher(revs=[branch]):
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/repo/brancher.py", line 49, in brancher
    for sha, names in group_by(scm.resolve_rev, revs).items():
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/funcy/seqs.py", line 317, in group_by
    result[f(item)].append(item)
  File "/home/roman/miniconda3/envs/tensorflow/lib/python3.6/site-packages/dvc/scm/git.py", line 432, in resolve_rev
    raise RevError(f"unknown Git revision '{rev}'")
dvc.scm.base.RevError: unknown Git revision 'f97e3cca64d10c299f7e9e54dd22889c6ee7a1b4, decouple/base'
```

**Comment by yogi81** [comment]
This happens when some tag and experiment base commit have same git commit hash

**Comment by pmrowla** [comment]
Issue here is that we aren't accounting for case where brancher returns comma separated string containing both hexsha and branch/tag names
