### ISSUE TITLE
`dvc pull --run-cache` does not work if remote path is a relative path

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4637]
## Bug Report

`dvc push --run-cache` or plain `dvc push/pull` works though.
### Please provide information about your setup

**Additional Information (if any):**
```console
❯ dvc pull --run-cache -v
2020-09-29 16:50:06,143 DEBUG: Check for update is enabled.
2020-09-29 16:50:06,148 DEBUG: fetched: [(3,)]
2020-09-29 16:50:06,149 DEBUG: fetched: [(6,)]
2020-09-29 16:50:06,230 ERROR: unexpected error - '../storage/runs/f4/f4d96ea9e3a842c243baf6a9ba72c2e95cf67d129159eafb813efa6859aa0a59/09eac8a46ebb889acde085a8ec7d617deb9179ae54908323ca451ce7a3612f8c' does not start with '/home/saugat/dvc_try/stage_cache/folder1/.dvc/../../storage'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/saugat/repos/iterative/dvc/dvc/main.py", line 76, in main
    ret = cmd.run()
  File "/home/saugat/repos/iterative/dvc/dvc/command/data_sync.py", line 26, in run
    stats = self.repo.pull(
  File "/home/saugat/repos/iterative/dvc/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/saugat/repos/iterative/dvc/dvc/repo/pull.py", line 25, in pull
    processed_files_count = self.fetch(
  File "/home/saugat/repos/iterative/dvc/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/saugat/repos/iterative/dvc/dvc/repo/fetch.py", line 39, in fetch
    used_run_cache = self.stage_cache.pull(remote) if run_cache else []
  File "/home/saugat/repos/iterative/dvc/dvc/stage/cache.py", line 217, in pull
    return self._transfer(
  File "/home/saugat/repos/iterative/dvc/dvc/stage/cache.py", line 196, in _transfer
    rel = src.relative_to(from_remote.path_info)
  File "/usr/lib/python3.8/pathlib.py", line 904, in relative_to
    raise ValueError("{!r} does not start with {!r}"
ValueError: '../storage/runs/f4/f4d96ea9e3a842c243baf6a9ba72c2e95cf67d129159eafb813efa6859aa0a59/09eac8a46ebb889acde085a8ec7d617deb9179ae54908323ca451ce7a3612f8c' does not start with '/home/saugat/dvc_try/stage_cache/folder1/.dvc/../../storage'
------------------------------------------------------------

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
DVC version: 1.7.9+bb5b2a.mod
---------------------------------
Platform: Python 3.8.5 on Linux-5.8.11-arch1-1-x86_64-with-glibc2.2.5
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda9
Workspace directory: ext4 on /dev/sda9
Repo: dvc, git
2020-09-29 16:50:06,898 DEBUG: Analytics is enabled.
2020-09-29 16:50:07,000 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmp8vs2s28d']'
2020-09-29 16:50:07,003 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmp8vs2s28d']'

```

#### Example Config
```ini
[core]
    remote = local
['remote "local"']
    url = ../../storage

```

**Comment by musa-atlihan** [comment]
I tried to replicate this here https://gist.github.com/musa-atlihan/e01e652a291bd3d36f4ccee5fe04836b
no error though - any ideas?

**Comment by musa-atlihan** [comment]
So this is how to replicate it:

https://gist.github.com/musa-atlihan/b7307d8a33f01a7f2cc8343273dfd976

happens when the cache folder is the local remote

and when there is the "runs" folder in the cache created via a dvc run command.

@skshetry 

replacing rel = src.relative_to(from_remote.path_info)
with rel = Path(os.path.relpath(src, from_remote.path_info)) fixes it.

would you like me to do the pr?

**Comment by skshetry** [comment]
@musa-atlihan, sorry for the late reply. Looks like you've figured out the replication, and thank you so much for creating a PR. :slightly_smiling_face:
