### ISSUE TITLE
dvc init fails with  ERROR: unexpected error - [WinError 2] The system cannot find the file specified: '.dvc\\.gitignore'

### ISSUE THREAD

**Issue by xdhmoore** [iterative/dvc#4683]
## Bug Report

Hello, I'm having some trouble setting up on windows. When I try to dvc-ize my git project with `dvc init`, it fails with:

```console
 ERROR: unexpected error - [WinError 2] The system cannot find the file specified: '.dvc\\.gitignore'
```

Using the `--force` flag results in the same message, as does running from both PowerShell core and cmd. This was installed with the installer, but I get the same error when installed via pipx (and when run via pipx/Run as Admin).

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.8.1 (exe)
---------------------------------
Platform: Python 3.7.9 on Windows-10-10.0.19041-SP0
Supports: azure, gdrive, gs, hdfs, http, https, s3, oss, webdav, webdavs
Cache types: <https://error.dvc.org/no-dvc-cache>
Workspace directory: NTFS on D:\
Repo: dvc, git
```

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.
```console
$ dvc init --verbose
2020-10-08 07:47:19,059 ERROR: unexpected error - [WinError 2] The system cannot find the file specified: '.dvc\\.gitignore'
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc\main.py", line 76, in main
  File "dvc\command\init.py", line 19, in run
  File "dvc\repo\__init__.py", line 218, in init
  File "dvc\repo\init.py", line 108, in init
  File "dvc\scm\git.py", line 246, in add
  File "site-packages\git\index\base.py", line 740, in add
  File "site-packages\git\util.py", line 68, in wrapper
  File "site-packages\git\index\util.py", line 91, in set_git_working_dir
  File "site-packages\git\index\base.py", line 626, in _entries_for_paths
  File "site-packages\git\index\base.py", line 587, in _store_path
FileNotFoundError: [WinError 2] The system cannot find the file specified: '.dvc\\.gitignore'
------------------------------------------------------------

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
DVC version: 1.8.1 (exe)
---------------------------------
Platform: Python 3.7.9 on Windows-10-10.0.19041-SP0
Supports: azure, gdrive, gs, hdfs, http, https, s3, oss, webdav, webdavs
Cache types: <https://error.dvc.org/no-dvc-cache>
Workspace directory: NTFS on D:\
Repo: dvc, git
2020-10-08 07:47:22,144 DEBUG: Analytics is enabled.
2020-10-08 07:47:22,315 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\username\\AppData\\Local\\Temp\\tmp3rbu7ykk']'
```

**Comment by pared** [comment]
@xdhmoore 
could you try removing `.dvc` directory and trying to reinitialize?

If its happening again, could you check if ".dvc\.gitignore" exists?

**Comment by xdhmoore** [comment]
Today, for some reason it seems to have solved itself. Maybe my machine needed a reboot. I guess I'll post again if it comes back.

**Comment by pared** [comment]
@xdhmoore Glad that issue got resolved, thanks for closing the issue. Feel free to reopen if it comes back. :)
