### ISSUE TITLE
Error when re-importing directory with -o flag

### ISSUE THREAD

**Issue by davesteps** [iterative/dvc#4723]
## Bug Report

If I import a directory like so `dvc import . --rev v0.1.0 model -o initial_weights`. And then later want to overwrite this with a new version  `dvc import . --rev v0.2.0 model -o initial_weights` I get below error. It does not happen with files, only directories and it does not seem to happen if you do not use the -o flag. 

```
2020-10-14 20:42:54,969 DEBUG: Check for update is enabled.
2020-10-14 20:42:54,971 DEBUG: fetched: [(3,)]                        
2020-10-14 20:42:55,324 DEBUG: fetched: [(8,)]
2020-10-14 20:42:55,344 ERROR: failed to import 'model' from '.'. - Paths for outs:
'initial_weights'('initial_weights.dvc')
'initial_weights/model'('initial_weights/model.dvc')
overlap. To avoid unpredictable behaviour, rerun command with non overlapping outs paths.
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/david/miniconda/lib/python3.7/site-packages/dvc/command/imp.py", line 19, in run
    rev=self.args.rev,
  File "/home/david/miniconda/lib/python3.7/site-packages/dvc/repo/imp.py", line 6, in imp
    return self.imp_url(path, out=out, fname=fname, erepo=erepo, frozen=True)
  File "/home/david/miniconda/lib/python3.7/site-packages/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/david/miniconda/lib/python3.7/site-packages/dvc/repo/scm_context.py", line 4, in run
    result = method(repo, *args, **kw)
  File "/home/david/miniconda/lib/python3.7/site-packages/dvc/repo/imp_url.py", line 47, in imp_url
    self.check_modified_graph([stage])
  File "/home/david/miniconda/lib/python3.7/site-packages/dvc/repo/__init__.py", line 263, in check_modified_graph
    self._collect_graph(self.stages + new_stages)
  File "/home/david/miniconda/lib/python3.7/site-packages/dvc/repo/__init__.py", line 501, in _collect_graph
    raise OverlappingOutputPathsError(parent, overlapping, msg)
dvc.exceptions.OverlappingOutputPathsError: Paths for outs:
'initial_weights'('initial_weights.dvc')
'initial_weights/model'('initial_weights/model.dvc')
overlap. To avoid unpredictable behaviour, rerun command with non overlapping outs paths.
------------------------------------------------------------
2020-10-14 20:42:55,348 DEBUG: Analytics is enabled.
2020-10-14 20:42:55,431 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpi2v9myto']'
2020-10-14 20:42:55,433 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpi2v9myto']'


```

**Output of `dvc version`:**

```console
DVC version: 1.8.2 (pip)
---------------------------------
Platform: Python 3.7.4 on Linux-5.4.0-48-generic-x86_64-with-debian-buster-sid
Supports: http, https, s3
Cache types: hardlink, symlink
Repo: dvc, git

```

**Comment by pared** [comment]
For the record, original discussion: https://discuss.dvc.org/t/use-previous-version-of-model-as-initial-weights/525/9

**Comment by efiop** [comment]
closing as stale
