### ISSUE TITLE
broken symlink breaking dvc add

### ISSUE THREAD

**Issue by kaleidoescape** [iterative/dvc#4763]
## Bug Report

When you have a folder with a broken symlink inside of it, `dvc add` fails with an unexpected error. Below is the traceback error, with the dvc version at the end. Beneath that, I have written steps to reproduce the issue from a fresh run.

```
$ dvc add data -v
2020-10-21 10:26:33,688 DEBUG: Check for update is enabled.
2020-10-21 10:26:33,740 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2020-10-21 10:26:33,741 DEBUG: Spawned '['daemon', '-q', 'updater']'
2020-10-21 10:26:33,976 DEBUG: Adding 'data' to '.gitignore'.                                                                                                                
2020-10-21 10:26:33,981 DEBUG: Path '/mnt/filepath/dvctest/data' inode '266633530'
2020-10-21 10:26:33,982 DEBUG: fetched: []
2020-10-21 10:26:33,986 DEBUG: Path '/mnt/filepath/dvctest/data/real_file' inode '266633531'
2020-10-21 10:26:33,986 DEBUG: fetched: []
2020-10-21 10:26:34,033 DEBUG: Uploading '../../../../../../tmp/tmp4fpfn1fx' to '.dvc/cache/.NqT4oirozy3XcQxbEoc8zE.tmp'
2020-10-21 10:26:34,042 DEBUG: cache '/mnt/filepath/dvctest/.dvc/cache/a7/23858b94e2ae50b82ae15aaa2bb59a.dir' expected 'HashInfo(name='md5', value='a723858b94e2ae50b82ae15aaa2bb59a.dir', dir_info={'fake_file': HashInfo(name='md5', value=None, dir_info=None), 'real_file': HashInfo(name='md5', value='d41d8cd98f00b204e9800998ecf8427e', dir_info=None)})' actual 'None'
2020-10-21 10:26:34,046 DEBUG: Path '.dvc/cache/a7/23858b94e2ae50b82ae15aaa2bb59a.dir' inode '266633589'
2020-10-21 10:26:34,047 DEBUG: fetched: []
2020-10-21 10:26:34,048 DEBUG: Path 'data' inode '266633530'
2020-10-21 10:26:34,049 DEBUG: fetched: []
2020-10-21 10:26:34,049 DEBUG: Assuming '/mnt/filepath/dvctest/.dvc/cache/a7/23858b94e2ae50b82ae15aaa2bb59a.dir' is unchanged since it is read-only
2020-10-21 10:26:34,050 DEBUG: {'data': 'modified'}
2020-10-21 10:26:34,051 DEBUG: Path '/mnt/filepath/dvctest/data' inode '266633530'
2020-10-21 10:26:34,051 DEBUG: fetched: [('b3a13d53d284250ffbb7240021e89496', '0', 'a723858b94e2ae50b82ae15aaa2bb59a.dir', '1603275994049438976')]
2020-10-21 10:26:34,053 DEBUG: Assuming '/mnt/filepath/dvctest/.dvc/cache/a7/23858b94e2ae50b82ae15aaa2bb59a.dir' is unchanged since it is read-only
2020-10-21 10:26:34,053 DEBUG: Computed stage: 'data.dvc' md5: 'None'
2020-10-21 10:26:34,058 DEBUG: Saving 'data' to '.dvc/cache/a7/23858b94e2ae50b82ae15aaa2bb59a.dir'.
2020-10-21 10:26:34,058 DEBUG: Assuming '/mnt/filepath/dvctest/.dvc/cache/a7/23858b94e2ae50b82ae15aaa2bb59a.dir' is unchanged since it is read-only
Adding...
2020-10-21 10:26:34,065 DEBUG: fetched: [(0,)]                                                                                                                               
2020-10-21 10:26:34,070 ERROR: unexpected error
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/dvc/main.py", line 76, in main
    ret = cmd.run()
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/dvc/command/add.py", line 22, in run
    external=self.args.external,
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/dvc/repo/scm_context.py", line 4, in run
    result = method(repo, *args, **kw)
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/dvc/repo/add.py", line 96, in add
    stage.commit()
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/dvc/stage/__init__.py", line 421, in commit
    out.commit()
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/dvc/output/base.py", line 287, in commit
    self.cache.save(self.path_info, self.cache.tree, self.hash_info)
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/dvc/cache/base.py", line 50, in use_state
    return call()
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/dvc/cache/base.py", line 341, in save
    self._save(path_info, tree, hash_info, save_link, **kwargs)
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/dvc/cache/base.py", line 348, in _save
    self._save_dir(path_info, tree, hash_info, save_link, **kwargs)
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/dvc/cache/base.py", line 322, in _save_dir
    entry_info, tree, entry_hash, save_link=False, **kwargs
  File "/home/filepath/anaconda3/envs/faen/lib/python3.7/site-packages/dvc/cache/base.py", line 208, in _save_file
    assert hash_info
AssertionError
------------------------------------------------------------
2020-10-21 10:26:34,600 DEBUG: Version info for developers:
DVC version: 1.8.4 (conda)
---------------------------------
Platform: Python 3.7.9 on Linux-4.4.0-189-generic-x86_64-with-debian-stretch-sid
Supports: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache types: hardlink, symlink
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2020-10-21 10:26:34,603 DEBUG: Analytics is enabled.
2020-10-21 10:26:34,605 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmphwuw8i1d']'
2020-10-21 10:26:34,609 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmphwuw8i1d']'
```

**Additional Information (if any):**

To reproduce from a fresh folder:

```
mkdir dvctest
cd dvctest
mkdir data
touch data/real_file
ln -s data/real_file data/fake_file
git init
dvc init
dvc add data -v
```

**Comment by efiop** [comment]
Discord context: https://discordapp.com/channels/485586884165107732/485596304961962003/768424218017660960
