### ISSUE TITLE
import-url support for Google Drive

### ISSUE THREAD

**Issue by Askannz** [iterative/dvc#4807]
## Bug Report

When trying to use `import-url` with a GDrive folder, this error happens:

```console
$ dvc import-url gdrive://someFolderId data/my_gdrive_data/
2020-10-26 11:43:27,552 DEBUG: Check for update is enabled.
2020-10-26 11:43:27,554 DEBUG: fetched: [(3,)]                                  
2020-10-26 11:43:27,655 DEBUG: Removing output 'data/my_gdrive_data' of stage: 'data/my_gdrive_data.dvc'.
Importing 'data/gdrive:/someFolderId' -> 'data/my_gdrive_data'
2020-10-26 11:43:27,656 DEBUG: Computed stage: 'data/my_gdrive_data.dvc' md5: '91f08d0421a8cfbc30888d78110b1a3c'
2020-10-26 11:43:27,656 DEBUG: 'md5' of stage: 'data/my_gdrive_data.dvc' changed.
2020-10-26 11:43:27,656 DEBUG: fetched: [(2,)]
2020-10-26 11:43:27,662 ERROR: failed to import gdrive://someFolderId. You could also try downloading it manually, and adding it with `dvc add`. - dependency 'data/gdrive:/someFolderId' does not exist
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/robin/Prog/Environments/dvc-env/lib/python3.8/site-packages/dvc/command/imp_url.py", line 14, in run
    self.repo.imp_url(
  File "/home/robin/Prog/Environments/dvc-env/lib/python3.8/site-packages/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/robin/Prog/Environments/dvc-env/lib/python3.8/site-packages/dvc/repo/scm_context.py", line 4, in run
    result = method(repo, *args, **kw)
  File "/home/robin/Prog/Environments/dvc-env/lib/python3.8/site-packages/dvc/repo/imp_url.py", line 54, in imp_url
    stage.run()
  File "/home/robin/Prog/Environments/dvc-env/lib/python3.8/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/robin/Prog/Environments/dvc-env/lib/python3.8/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/home/robin/Prog/Environments/dvc-env/lib/python3.8/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/robin/Prog/Environments/dvc-env/lib/python3.8/site-packages/dvc/stage/__init__.py", line 445, in run
    sync_import(self, dry, force)
  File "/home/robin/Prog/Environments/dvc-env/lib/python3.8/site-packages/dvc/stage/imports.py", line 29, in sync_import
    stage.save_deps()
  File "/home/robin/Prog/Environments/dvc-env/lib/python3.8/site-packages/dvc/stage/__init__.py", line 393, in save_deps
    dep.save()
  File "/home/robin/Prog/Environments/dvc-env/lib/python3.8/site-packages/dvc/output/base.py", line 255, in save
    raise self.DoesNotExistError(self)
dvc.dependency.base.DependencyDoesNotExistError: dependency 'data/gdrive:/someFolderId' does not exist
------------------------------------------------------------
2020-10-26 11:43:27,664 DEBUG: Analytics is enabled.
2020-10-26 11:43:27,707 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpzkd1zj4_']'
2020-10-26 11:43:27,709 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpzkd1zj4_']'
```

I was told on Discord that`import-url` does not support GDrive yet and that I should open a ticket here.

**Output of `dvc version`:**

```console
DVC version: 1.9.1 (pip)
---------------------------------
Platform: Python 3.8.6 on Linux-5.9.1-6-tkg-pds-x86_64-with-glibc2.2.5
Supports: http, https, s3
Cache types: hardlink, symlink
Repo: dvc, git
```

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/2865 .

The message `dvc.dependency.base.DependencyDoesNotExistError: dependency 'data/gdrive:/someFolderId' does not exist` looks odd too, will be handled when implementing.
