### ISSUE TITLE
Unexpected error on `dvc diff`

### ISSUE THREAD

**Issue by courentin** [iterative/dvc#4825]
## Bug Report
When running `dvc diff staging`, I got a KeyError, here is the traceback:
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.7/site-packages/dvc/main.py", line 76, in main
    ret = cmd.run()
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.7/site-packages/dvc/command/diff.py", line 130, in run
    diff = self.repo.diff(self.args.a_rev, self.args.b_rev)
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.7/site-packages/dvc/repo/__init__.py", line 54, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.7/site-packages/dvc/repo/diff.py", line 43, in diff
    missing = sorted(_filter_missing(self, deleted_or_missing))
  File "/home/ubuntu/.local/share/virtualenvs/speech-api-EI_ft4iY/lib/python3.7/site-packages/dvc/repo/diff.py", line 125, in _filter_missing
    if out.status()[str(out)] == "not in cache":
KeyError: 'data/KPI/KPI_from_dvc/en/post_probs'
```

It only happens when I give a specific revision.

Any ideas? Could it be my data?

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.9.1 (pip)
---------------------------------
Platform: Python 3.7.3 on Linux-5.4.0-1029-aws-x86_64-with-debian-buster-sid
Supports: http, https, s3
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p1
Workspace directory: ext4 on /dev/nvme0n1p1
Repo: dvc, git
```

**Comment by courentin** [comment]
UPDATE:
It only happens when I do `dvc diff staging`, `dvc diff staging other_branch` works. As well as `dvc diff other_branch staging`

**Comment by pmrowla** [comment]
This is a `diff` bug for the case where we compare workspaces, it's not any problem with your setup or data. Should be fixed shortly in master

**Comment by courentin** [comment]
That was very fast, thank you 💪
