### ISSUE TITLE
remote: exception ignored on python exit

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#4863]
## Bug Report

When downloading cache from SSH remote via `Repo` API I see some exception ignored on python exit:
```
Exception ignored in: <function Pool.__del__ at 0x7fe9adabb790>
Traceback (most recent call last):
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/dvc/tree/pool.py", line 42, in __del__
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/dvc/tree/pool.py", line 46, in close
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/dvc/tree/ssh/connection.py", line 68, in close
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/paramiko/sftp_client.py", line 195, in close
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/paramiko/channel.py", line 671, in close
  File "/home/suor/.virtualenvs/viewer/lib/python3.8/site-packages/paramiko/transport.py", line 1846, in _send_user_message
AttributeError: 'NoneType' object has no attribute 'time'
```

### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.6.6+67ddb7 
---------------------------------
Platform: Python 3.8.2 on Linux-5.4.0-51-generic-x86_64-with-glibc2.27
Supports: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
```

**Comment by skshetry** [comment]
Related Issue: https://github.com/paramiko/paramiko/issues/1617

**Comment by efiop** [comment]
Closing as stale
