### ISSUE TITLE
`dvc get . ` fails for specific file

### ISSUE THREAD

**Issue by Seanny123** [iterative/dvc#4874]
## Bug Report

When I run:
```
dvc get . data/path/to/my/very/specific_file.pdb -v
```
It crashes with the following stack-trace:
```
Traceback (most recent call last):
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/main.py", line 76, in main
    ret = cmd.run()
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/command/get.py", line 31, in run
    return self._get_file_from_repo()
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/command/get.py", line 37, in _get_file_from_repo
    Repo.get(
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/repo/get.py", line 53, in get
    repo.get_external(path, out)
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/external_repo.py", line 205, in get_external
    save_info = self._fetch_to_cache(path_info, repo, None)
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/external_repo.py", line 139, in _fetch_to_cache
    hash_info = tree.get_hash(
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/tree/base.py", line 45, in use_state
    return call()
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/tree/base.py", line 271, in get_hash
    hash_info = self.get_dir_hash(path_info, **kwargs)
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/tree/repo.py", line 380, in get_dir_hash
    return dvc_tree.get_dir_hash(path_info, **kwargs)
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/tree/dvc.py", line 258, in get_dir_hash
    return super().get_dir_hash(path_info, **kwargs)
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/tree/base.py", line 45, in use_state
    return call()
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/tree/base.py", line 339, in get_dir_hash
    dir_info = self._collect_dir(path_info, **kwargs)
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/tree/base.py", line 309, in _collect_dir
    for fname in self.walk_files(path_info, **kwargs):
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/tree/dvc.py", line 230, in walk_files
    for root, _, files in self.walk(path_info):
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/tree/dvc.py", line 227, in walk
    yield from self._walk(root, trie, topdown=topdown, **kwargs)
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/dvc/tree/dvc.py", line 185, in _walk
    for key, out in trie.iteritems(prefix=root.parts):  # noqa: B301
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/pygtrie.py", line 640, in iteritems
    node, _ = self._get_node(prefix)
  File "/home/sean/.local/pipx/venvs/dvc/lib64/python3.9/site-packages/pygtrie.py", line 552, in _get_node
    raise KeyError(key)
KeyError: ('/', 'tmp', 'tmpm6l4yg7jdvc-clone', 'data', 'path, 'to', 'my', 'very', 'specific_file.pdb')
```

I don't think it's a cache problem, because my co-worker also get the same error on her machine and she has a very different cache state than I do.

My setup:
```
Version info for developers:
DVC version: 1.9.1 (pip)
---------------------------------
Platform: Python 3.9.0 on Linux-5.8.17-300.fc33.x86_64-x86_64-with-glibc2.32
Supports: http, https, s3
Cache types: hardlink, symlink
Repo: dvc, git
```

Her setup:
```
Platform: Python 3.7.8 on Linux-5.7.15-100.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
Supports: http, https, s3
Cache types: hardlink, symlink
Repo: dvc, git
```

**Comment by pared** [comment]
reproduction script:
```
#!/bin/bash

rm -rf wspace

mkdir wspace
pushd wspace

mkdir repo
main=$(pwd)

pushd repo

git init --quiet
dvc init --quiet

dvc remote add -d str $main/storage

git commit -am "init"

mkdir data
echo 1 >> data/1
dvc add data
git add -A

git commit -am "add data"
dvc get . data/1  -v
```
Note 1: We definitely could handle this issue more gracefully. It seems to me that the origin of the problem is that we are not looking into cache, just to remote.

Note 2: If `data` is file and not dir, we also get very confusing (yet different) error, so when handling this issue:
- [ ] - fix when `data` is a directory
- [ ] - fix when `data` is file

@Seanny123 if you require this functionality, the workaround for that would be to `dvc push` before trying `dvc get` - if a file is in remote, DVC should not have problem importing it.

**Comment by jorgeorpinel** [comment]
> It seems to me that the origin of the problem is that we are not looking into cache, just to remote.

Same as https://github.com/iterative/dvc/issues/5967#issuecomment-833754281?

**Comment by efiop** [comment]
Fixed
