### ISSUE TITLE
unexpected error for aws training machine 

### ISSUE THREAD

**Issue by marksein07** [iterative/dvc#5030]
## Bug Report
dvc pull and reproduce raise a unexpected error on aws gpu training machine

I use gitlab on aws g3xlarge and try to dvc pull data from gdrive

$ dvc version 1.10.0
$ git version 2.17.1

```console
$ dvc repro
ERROR: unexpected error - expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/main.py", line 89, in main
    cmd = args.func(args)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/command/base.py", line 40, in __init__
    self.repo = Repo(uninitialized=self.UNINITIALIZED)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/repo/__init__.py", line 177, in __init__
    self._ignore()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/repo/__init__.py", line 256, in _ignore
    self.scm.ignore_list(flist)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/base.py", line 81, in ignore_list
    return [self.ignore(path) for path in p_list]
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/base.py", line 81, in <listcomp>
    return [self.ignore(path) for path in p_list]
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/git.py", line 195, in ignore
    entry, gitignore = self._get_gitignore(path)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/git.py", line 181, in _get_gitignore
    if not path_isin(os.path.realpath(gitignore), self.root_dir):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/utils/fs.py", line 156, in path_isin
    parent = os.path.join(normalize_path(parent), "")
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/utils/fs.py", line 154, in normalize_path
    return os.path.normpath(path)
  File "/home/ubuntu/anaconda3/lib/python3.7/posixpath.py", line 340, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/dvc", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/main.py", line 119, in main
    dvc_info = get_dvc_info()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/info.py", line 37, in get_dvc_info
    repo = Repo()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/repo/__init__.py", line 177, in __init__
    self._ignore()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/repo/__init__.py", line 256, in _ignore
    self.scm.ignore_list(flist)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/base.py", line 81, in ignore_list
    return [self.ignore(path) for path in p_list]
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/base.py", line 81, in <listcomp>
    return [self.ignore(path) for path in p_list]
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/git.py", line 195, in ignore
    entry, gitignore = self._get_gitignore(path)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/git.py", line 181, in _get_gitignore
    if not path_isin(os.path.realpath(gitignore), self.root_dir):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/utils/fs.py", line 156, in path_isin
    parent = os.path.join(normalize_path(parent), "")
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/utils/fs.py", line 154, in normalize_path
    return os.path.normpath(path)
  File "/home/ubuntu/anaconda3/lib/python3.7/posixpath.py", line 340, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType


```
the error raised before any verbose output

**Comment by skshetry** [comment]
@marksein07, could you please provide complete `dvc version` output? It has more information than `dvc --version`. Thanks.

**Comment by marksein07** [comment]
In fact There is the same Error

```code
$ dvc version
ERROR: unexpected error - expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/main.py", line 90, in main
    ret = cmd.run()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/command/version.py", line 12, in run
    dvc_info = get_dvc_info()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/info.py", line 37, in get_dvc_info
    repo = Repo()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/repo/__init__.py", line 177, in __init__
    self._ignore()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/repo/__init__.py", line 256, in _ignore
    self.scm.ignore_list(flist)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/base.py", line 81, in ignore_list
    return [self.ignore(path) for path in p_list]
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/base.py", line 81, in <listcomp>
    return [self.ignore(path) for path in p_list]
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/git.py", line 195, in ignore
    entry, gitignore = self._get_gitignore(path)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/git.py", line 181, in _get_gitignore
    if not path_isin(os.path.realpath(gitignore), self.root_dir):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/utils/fs.py", line 156, in path_isin
    parent = os.path.join(normalize_path(parent), "")
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/utils/fs.py", line 154, in normalize_path
    return os.path.normpath(path)
  File "/home/ubuntu/anaconda3/lib/python3.7/posixpath.py", line 340, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/dvc", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/main.py", line 119, in main
    dvc_info = get_dvc_info()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/info.py", line 37, in get_dvc_info
    repo = Repo()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/repo/__init__.py", line 177, in __init__
    self._ignore()
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/repo/__init__.py", line 256, in _ignore
    self.scm.ignore_list(flist)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/base.py", line 81, in ignore_list
    return [self.ignore(path) for path in p_list]
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/base.py", line 81, in <listcomp>
    return [self.ignore(path) for path in p_list]
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/git.py", line 195, in ignore
    entry, gitignore = self._get_gitignore(path)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/scm/git.py", line 181, in _get_gitignore
    if not path_isin(os.path.realpath(gitignore), self.root_dir):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/utils/fs.py", line 156, in path_isin
    parent = os.path.join(normalize_path(parent), "")
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/dvc/utils/fs.py", line 154, in normalize_path
    return os.path.normpath(path)
  File "/home/ubuntu/anaconda3/lib/python3.7/posixpath.py", line 340, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

**Comment by skshetry** [comment]
@marksein0, can you please upgrade to the latest version and see if it works.

**Comment by marksein07** [comment]
I tried it, and It doesn't work.

**Comment by skshetry** [comment]
@marksein07, can you provide more information? Does this happen when running inside a dvc/git repo?
And, what's there location are? Are they same?

It would be easier to debug if you could provide a script.

**Comment by marksein07** [comment]
In fact, I can operate dvc perfectly inside private gitlab in local pc with ubuntu 18.04 and conda.

However, after I do the same operation on aws cloud machine, the every dvc command is just crashed except for --help work well.

There is even no any other verbose I could provide, and I also confused.

**Comment by efiop** [comment]
@marksein07 Anything about the path where you run `dvc` in on your aws machine? What is the absolute path to it? E.g. could you show `$ pwd` output?

**Comment by marksein07** [comment]
<code>ubuntu@ip-10-0-1-126:~/git/vnpc-dialog-service/sa$ pwd
/home/ubuntu/git/vnpc-dialog-service/sa
</code>

**Comment by efiop** [comment]
@marksein07 Any symlinks in that path?

**Comment by marksein07** [comment]
@efiop No

**Comment by skshetry** [comment]
@marksein07, could you please try 1.11.6 version? We have made some changes there, so maybe that'll work (though a slim chance). Thanks.

**Comment by efiop** [comment]
@marksein07 Hard to tell what is going on here. Please try @skshetry 's suggestion and if it still fails, and you are familiar with pdb and keen on debugging a bit, try running `dvc version --pdb` and seeing what went wrong. Without us being able to reproduce it, it will take a longer to try to figure out what went wrong. This does make us think about including additional debugging info into our error logs (e.g. args in the stack) to be able to quicker tell what broke. :slightly_frowning_face:

**Comment by marksein07** [comment]
@efiop @skshetry , hi, I'm sorry for the late reply.
1.11.6 doesn't work, and the error message is still the same.

I tried to debug with pdb, and this error might be related with git object
![13240213785606](https://user-images.githubusercontent.com/4708597/102746802-f4242980-4399-11eb-8177-f6e48bbf87bb.png)
 
I'm not sure what the scm object is, I could refer the source code to debug and offer you some more valuable logs

**Comment by skshetry** [comment]
@marksein07, yup, `scm` to be class `Git` means it is instantiated as a git repo.
The place to debug is the following place (in addition to why `scm.root_dir` is `None`):

https://github.com/iterative/dvc/blob/5db7a4cab6262c91e837711b42e23bd5b7253c0f/dvc/repo/__init__.py#L89

**Comment by skshetry** [comment]
That is weird, `scm.root_dir` is an alias for `scm._root_dir`. So, it should never be None. hmm

**Comment by skshetry** [comment]
Another thing to point out is that `_root_dir` and gitpython's `repo` are in different path, `/sa` vs `/` whereas it should have been `/sa` and `/sa/.git` or (`/` vs `/.git`).

**Comment by marksein07** [comment]
I use dvc init --subdir in project subdirectory, but it works well.
I can observe it on local machine.

**Comment by pmrowla** [comment]
@marksein07 can you run these commands on your aws machine and post the output (from the same directory you are trying to init DVC in):
```
$ git rev-parse --git-dir
$ git rev-parse --show-toplevel
```

**Comment by marksein07** [comment]
@pmrowla 
the result is shown below,
![13258692204513](https://user-images.githubusercontent.com/4708597/103078902-cc3cfc00-460d-11eb-8003-b29470d14367.png)

**Comment by pmrowla** [comment]
@marksein07 it looks like there is something strange going on in your git repo/environment. `git rev-parse --git-dir` should return the path to a `.git` directory, and `git rev-parse --show-toplevel` should return the root of your git repo. If `--show-toplevel` isn't returning anything it means git does not think it is inside a git working directory, which in turn will break DVC.

Are you inside a bare git repository (a server-side repo that you normally `clone`/`push`/`pull` from and not a working `git clone`'d repo)?

Alternatively, do you have `$GIT_DIR` set in your environment? If so try unsetting it and then retrying those commands?

**Comment by efiop** [comment]
Closing as stale. Please feel free to reopen.
