### ISSUE TITLE
UTF-8 codec error while using dvc pull (surrogates not allowed)

### ISSUE THREAD

**Issue by vss96** [iterative/dvc#5083]
# Bug Report

## Description
While using dvc pull, the task errors out with:
`ERROR: unexpected error - 'utf-8' codec can't encode characters in position 103-110: surrogates not allowed
`

### Reproduce
1. Try to push files with special characters in it. Ex: sydney-australia-â€“-january-â€“.txt
2. Set dvc cache type to reflink.
3. Try running dvc pull on the files that were pushed.

### Environment information

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.10.2 (brew)
---------------------------------
Platform: Python 3.9.0 on macOS-10.15.7-x86_64-i386-64bit
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs
Cache types: reflink, hardlink, symlink
Caches: local
Remotes: s3
Repo: dvc, git
```

### Fix
By default on MacOS, the cache type used by DVC is reflink. By changing it to either symlink, hardlink or copy we can avoid the codec error. You can change the cache type this by using `dvc config cache.type <type>`

More on the cache types: https://dvc.org/doc/user-guide/large-dataset-optimization

```
2020-12-11 16:32:04,319 DEBUG: 'aug_set/annotations/sydney-australia-â€“-january-â€“-red-bull-energy-drink-mini-cooper-publicity-car-can-red-bull-drink-behind-used-123644712-0.json' doesn't exist.
2020-12-11 16:32:04,321 DEBUG: fetched: [(92173,)]
4:33
2020-12-11 16:32:04,325 ERROR: unexpected error - 'utf-8' codec can't encode characters in position 103-110: surrogates not allowed
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/main.py", line 90, in main
    ret = cmd.run()
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/command/data_sync.py", line 26, in run
    stats = self.repo.pull(
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/repo/__init__.py", line 60, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/repo/pull.py", line 36, in pull
    stats = self.checkout(
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/repo/__init__.py", line 60, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/repo/checkout.py", line 96, in checkout
    result = stage.checkout(
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/stage/__init__.py", line 502, in checkout
    key, outs = self._checkout(out, **kwargs)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/stage/__init__.py", line 510, in _checkout
    result = out.checkout(**kwargs)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/output/base.py", line 356, in checkout
    return self.cache.checkout(
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/cache/base.py", line 40, in use_state
    return call()
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/cache/base.py", line 555, in checkout
    return self._checkout(
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/cache/base.py", line 578, in _checkout
    return self._checkout_dir(
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/cache/base.py", line 472, in _checkout_dir
    self.link(entry_cache_info, entry_info)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/cache/base.py", line 141, in link
    self._link(from_info, to_info, self.cache_types)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/cache/base.py", line 148, in _link
    self._try_links(from_info, to_info, link_types)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/remote/slow_link_detection.py", line 38, in wrapper
    result = f(remote, *args, **kwargs)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/cache/base.py", line 166, in _try_links
    self._do_link(from_info, to_info, link_method)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/cache/base.py", line 182, in _do_link
    link_method(from_info, to_info)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/tree/local.py", line 240, in reflink
    System.reflink(from_info, tmp_info)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/system.py", line 108, in reflink
    ret = System._reflink_darwin(source, link_name)
  File "/usr/local/Cellar/dvc/1.10.2/libexec/lib/python3.9/site-packages/dvc/system.py", line 75, in _reflink_darwin
    ctypes.c_char_p(dst.encode("utf-8")),
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 103-110: surrogates not allowed
------------------------------------------------------------
2020-12-11 16:32:04,710 DEBUG: Version info for developers:
DVC version: 1.10.2 (brew)
---------------------------------
Platform: Python 3.9.0 on macOS-10.15.7-x86_64-i386-64bit
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs
Cache types: reflink, hardlink, symlink
Caches: local
Remotes: s3
Repo: dvc, git
Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2020-12-11 16:32:04,712 DEBUG: Analytics is disabled.
```

**Comment by pared** [comment]
@vss96 Thanks for great summary!

Our original discussion: https://discord.com/channels/485586884165107732/485596304961962003/786905389722501120

It seems like trying to encode the `dst` causes fail.

**Comment by efiop** [comment]
Nice catch! Ok, our issue here seems to be caused by us not encoding paths we pass to clonefile the correct way. We should've used fsencode(because os.* methods that have supplied us with that base directory used fsdecode to decode bytes into utf-8), but for some reason we use utf-8. Looks like a pretty naive bug :( We also have a potential for a similar bug in `inode` method for windows, might want to check it too...

Regarding the fix, I've created a WIP at https://github.com/iterative/dvc/pull/5085 . We'll backport for v1.11 too ASAP and will release a new version, so you could upgrade. You could try installing from that PR and running `dvc pull`, but you have to be aware that this is a development branch for 2.0 release, which is compatible with your repo for the most part for now, but soon might not be, as we are rolling out some breaking changes.

**Comment by efiop** [comment]
@vss96 Could you please run
```
brew uninstall dvc
```
to uninstall dvc and then run
```
pip install dvc==1.11.4
```
to install the latest version from pypi? Then try `dvc pull` again and let us know how it goes.

1.11.4 is safe to continue using onwards. Brew release for 1.11.4 won't be available for a few days, looks like, as there [are some problems with dependency packages on osx 11](https://github.com/Homebrew/homebrew-core/pull/66130). 

Thanks again for reporting the bug! :pray:
