### ISSUE TITLE
exp: tries to checkout not existing output

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#5155]
# Bug Report

```bash
#! /bin/bash

# init
cd "$(mktemp -d)"
git init && dvc init
git add -A
git commit -m "initial commit"

# track dependency
echo "foo" > foo
dvc add foo
git add -A
git commit -m "second commit"

# creating YAML file
dvc run --no-exec -n copy-foo-bar -d foo -o bar "cp foo bar"

# experiments run
dvc exp run
```

### Expected:
command is run and `bar` is produced which is then checked out.

### Actual:
```
ERROR: Checkout failed for following targets:                                                             
bar
Is your cache up to date?
<https://error.dvc.org/missing-files>
```

Maybe I am doing something wrong here?

**Comment by skshetry** [comment]
If I do `git add dvc.yaml` before running `dvc exp run --temp`, I get following error:

<details>
<summary>Details</summary>
ERROR: Failed to reproduce experiment '650b0e9' - Checkout failed for following targets:                  
C
h
e
c
k
o
u
t
 
f
a
i
l
e
d
 
f
o
r
 
f
o
l
l
o
w
i
n
g
 
t
a
r
g
e
t
s
:


b
a
r


I
s
 
y
o
u
r
 
c
a
c
h
e
 
u
p
 
t
o
 
d
a
t
e
?


<

[
3
6
m
h
t
t
p
s
:
/
/
e
r
r
o
r
.
d
v
c
.
o
r
g
/
m
i
s
s
i
n
g
-
f
i
l
e
s

[
3
9
m
>
Is your cache up to date?
<https://error.dvc.org/missing-files>: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/saugat/repos/iterative/dvc/dvc/repo/experiments/executor/base.py", line 281, in reproduce
    dvc_checkout(dvc, force=True, quiet=True)
  File "/home/saugat/repos/iterative/dvc/dvc/repo/__init__.py", line 53, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/saugat/repos/iterative/dvc/dvc/repo/checkout.py", line 121, in checkout
    raise CheckoutError(stats["failed"], stats)
dvc.exceptions.CheckoutError: Checkout failed for following targets:
bar
Is your cache up to date?
<https://error.dvc.org/missing-files>
"""
</details>

**Comment by skshetry** [comment]
Another minor thing, when I do `git add dvc.yaml` and do `dvc exp run`, it fails with the following error:
```console
ERROR: unexpected error - Cmd('git') failed due to: exit code(1)      
  cmdline: git stash apply 2b12c166333f77b44ab68e8af921dc8c9ec3102b
  stderr: 'error: The following untracked working tree files would be overwritten by merge:
	dvc.yaml
Please move or remove them before you merge.
Aborting'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

And, if I do `git status`, it shows up as not staged (i.e. untracked).
