### ISSUE TITLE
experiments: full traceback sometimes dumped in executor without `-v`

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#5176]
And, if I don't add `dvc.yaml`, it fails with:
```console
$ dvc exp run --temp
ERROR: Failed to reproduce experiment '3355c7e' - ''dvc.yaml' does not exist.' does not exist.: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/saugat/repos/iterative/dvc/dvc/repo/experiments/executor/base.py", line 288, in reproduce
    stages = dvc_reproduce(
  File "/home/saugat/repos/iterative/dvc/dvc/repo/__init__.py", line 53, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/saugat/repos/iterative/dvc/dvc/repo/scm_context.py", line 4, in run
    result = method(repo, *args, **kw)
  File "/home/saugat/repos/iterative/dvc/dvc/repo/reproduce.py", line 116, in reproduce
    self.stage.collect(
  File "/home/saugat/repos/iterative/dvc/dvc/repo/stage.py", line 257, in collect
    stages = self.from_target(target, accept_group=accept_group, glob=glob)
  File "/home/saugat/repos/iterative/dvc/dvc/repo/stage.py", line 100, in from_target
    return self.load_all(
  File "/home/saugat/repos/iterative/dvc/dvc/repo/stage.py", line 171, in load_all
    stages = dvcfile.stages  # type: ignore
  File "/home/saugat/repos/iterative/dvc/dvc/dvcfile.py", line 240, in stages
    data, _ = self._load()
  File "/home/saugat/repos/iterative/dvc/dvc/dvcfile.py", line 107, in _load
    raise StageFileDoesNotExistError(self.path)
dvc.stage.exceptions.StageFileDoesNotExistError: 'dvc.yaml' does not exist.
"""
```

(Why is the traceback there without `-v`?)

_Originally posted by @skshetry in https://github.com/iterative/dvc/issues/5175#issuecomment-752022888_

**Comment by pmrowla** [comment]
Log level probably isn't being copied over properly after we init the DVC logger inside executors (DVC logger has to be explicitly re-inited in the multiprocessing child processes since `main()` is never run in the child).

**Comment by pmrowla** [comment]
The issue here is that `futures.ProcessPoolExecutor` includes a [hack](https://hg.python.org/cpython/rev/a36b402b099b) where the full traceback for exceptions in a child process will be dumped as a string in the `msg` field for the outer exception that gets raised in the parent process. So `str(exc)` will include the multi-line original traceback instead of just the simple message.

Workaround for us should be to handle logging for all experiment exceptions inside the executor child processes.
