### ISSUE TITLE
s3: osx: NoSuchKey Error,  when calling the ListObjects operation

### ISSUE THREAD

**Issue by Dr-Gandalf** [iterative/dvc#5276]
# Bug Report

## Description

when pushing data to s3 bucket from MAC os installation. it gives the following error

unexpected error - An error occurred (NoSuchKey) when calling the ListObjects operation: The specified key does not exist.

### Reproduce

Step list of how to reproduce the bug

1. dvc init
2. dvc add some.file
4. dvc remote add -d s3ctv s3://some_bucket/some_path
5.  dvc remote modify s3ctv endpointurl  https://some_bucket.s3.us-east-2.amazonaws.com/
6. dvc push

### Expected

A clear and concise description of what you expect to happen.

### Environment information

$ dvc doctor
DVC version: 1.11.10 (pip)
---------------------------------
Platform: Python 3.7.3 on Darwin-20.1.0-x86_64-i386-64bit
Supports: http, https, s3
Cache types: reflink, hardlink, symlink
Caches: local
Remotes: s3
Repo: dvc, git

$ pip freeze | grep boto
boto3==1.16.54
botocore==1.19.54

**Output of `dvc version`:**

```console
$ dvc version
```

**Additional Information (if any):**

<details>
<summary>Traceback</summary>

```
$ dvc status -c -v
2021-01-13 11:18:35,390 DEBUG: Check for update is enabled.
2021-01-13 11:18:35,392 DEBUG: '/Users/xxxxxxx/Documents/proyectos/rr/.dvc/tmp/updater' is outdated
2021-01-13 11:18:35,541 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-01-13 11:18:35,543 DEBUG: Spawned '['daemon', '-q', 'updater']'
2021-01-13 11:18:35,550 DEBUG: fetched: [(3,)]
2021-01-13 11:18:35,739 DEBUG: Preparing to collect status from s3://xxxx-xxxxxas/test_dvc/
2021-01-13 11:18:35,739 DEBUG: Collecting information from local cache...
2021-01-13 11:18:35,740 DEBUG: Assuming '/Users/xxxxxx/Documents/proyectos/rr/.dvc/cache/ce/ac801dd224d11a1e0b58f20b37e84d' is unchanged since it is read-only
2021-01-13 11:18:35,740 DEBUG: Collecting information from remote cache...
2021-01-13 11:18:35,741 DEBUG: Matched '0' indexed hashes
2021-01-13 11:18:35,741 DEBUG: Querying 1 hashes via object_exists
2021-01-13 11:18:36,810 DEBUG: fetched: [(3,)]
2021-01-13 11:18:36,812 ERROR: unexpected error - An error occurred (NoSuchKey) when calling the ListObjects operation: The specified key does not exist.
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/main.py", line 90, in main
    ret = cmd.run()
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/command/status.py", line 49, in run
    st = self.repo.status(
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/repo/init.py", line 54, in wrapper
return f(repo, *args, kwargs)
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/repo/status.py", line 131, in status
    return _cloud_status(
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/repo/status.py", line 94, in _cloud_status
    status_info = self.cloud.status(
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/data_cloud.py", line 116, in status
    return remote.status(
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/remote/base.py", line 56, in wrapper
    return f(obj, *args, kwargs)
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/remote/base.py", line 113, in status
    dir_status, filestatus,  = self._status(
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/remote/base.py", line 175, in _status
    self.hashes_exist(
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/remote/base.py", line 132, in hashes_exist
    return indexed_hashes + self.cache.hashes_exist(list(hashes), **kwargs)
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/cache/base.py", line 905, in hashes_exist
    remote_hashes = self.list_hashes_exists(hashes, jobs, name)
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/cache/base.py", line 863, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 600, in result_iterator
    yield fs.pop().result()
File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.get_result()
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 389, in get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, self.kwargs)
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/cache/base.py", line 854, in exists_with_progress
    ret = self.tree.exists(path_info)
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/tree/s3.py", line 169, in exists
    return self.isfile(path_info) or self.isdir(path_info)
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/tree/s3.py", line 199, in isfile
    return path_info.path in self._list_paths(path_info)
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/dvc/tree/s3.py", line 207, in _list_paths
    for obj_summary in bucket.objects.filter(kwargs):
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/boto3/resources/collection.py", line 83, in iter
    for page in self.pages():
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/botocore/paginate.py", line 255, in iter
    response = self._make_request(current_kwargs)
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the ListObjects operation: The specified key does not exist.
------------------------------------------------------------
2021-01-13 11:18:37,553 DEBUG: Version info for developers:
DVC version: 1.11.10 (brew)
---------------------------------
Platform: Python 3.9.1 on macOS-11.0.1-x86_64-i386-64bit
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs
Cache types: reflink, hardlink, symlink
Caches: local
Remotes: s3
Repo: dvc, git
Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-01-13 11:18:37,555 DEBUG: Analytics is enabled.
2021-01-13 11:18:37,556 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/lj/hk_7xt910_d6jydzsyssxb7h0000gn/T/tmpkp3ix6it']'
2021-01-13 11:18:37,558 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/lj/hk_7xt910_d6jydzsyssxb7h0000gn/T/tmpkp3ix6it']'

$ dvc push -v --pdb
2021-01-13 15:14:40,208 DEBUG: Check for update is enabled.
2021-01-13 15:14:40,213 DEBUG: fetched: [(3,)]
2021-01-13 15:14:40,384 DEBUG: Preparing to upload data to 's3://xxxx-xxxxxas/test_dvc/'
2021-01-13 15:14:40,384 DEBUG: Preparing to collect status from s3://xxxx-xxxxxas/test_dvc/
2021-01-13 15:14:40,384 DEBUG: Collecting information from local cache...
2021-01-13 15:14:40,385 DEBUG: Assuming '/Users/xxxxx/Documents/proyectos/rr/.dvc/cache/ce/ac801dd224d11a1e0b58f20b37e84d' is unchanged since it is read-only
2021-01-13 15:14:40,386 DEBUG: Collecting information from remote cache...
2021-01-13 15:14:40,386 DEBUG: Matched '0' indexed hashes
2021-01-13 15:14:40,386 DEBUG: Querying 1 hashes via object_exists
2021-01-13 15:14:41,243 DEBUG: fetched: [(3,)]
/usr/local/Cellar/dvc/1.11.10/libexec/lib/python3.9/site-packages/botocore/client.py(676)_make_api_call()
-> raise error_class(parsed_response, operation_name)
(Pdb)
```
</details>

**Comment by efiop** [comment]
Closing as stale.
