### ISSUE TITLE
get: temp. file left on failure

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#5355]
```console
$ dvc get https://github.com/iterative/dvc README.md -o readme2.md -v
2021-01-28 20:51:17,174 DEBUG: Creating external repo https://github.com/iterative/dvc@None
2021-01-28 20:51:17,175 DEBUG: erepo: git clone 'https://github.com/iterative/dvc' to a temporary dir
2021-01-28 20:51:55,517 DEBUG: Downloading '../../../../../tmp/tmpn5toyfvkdvc-clone/README.md' to 'readme2.md'
2021-01-28 20:51:55,519 DEBUG: Removing '/home/saugat/repos/iterative/dvc/.VbeVvQcXF9aAvGjm7cMR6u'
2021-01-28 20:51:55,527 ERROR: unexpected error - : Unable to find DVC-file with output '../../../../../tmp/tmpn5toyfvkdvc-clone/README.md'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/saugat/repos/iterative/dvc/dvc/tree/dvc.py", line 60, in open
    outs = self._find_outs(path, strict=False)
  File "/home/saugat/repos/iterative/dvc/dvc/tree/dvc.py", line 33, in _find_outs
    outs = self.repo.find_outs_by_path(path, *args, **kwargs)
  File "/home/saugat/repos/iterative/dvc/dvc/repo/__init__.py", line 450, in find_outs_by_path
    raise OutputNotFoundError(path, self)
dvc.exceptions.OutputNotFoundError: Unable to find DVC-file with output '../../../../../tmp/tmpn5toyfvkdvc-clone/README.md'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/saugat/repos/iterative/dvc/dvc/main.py", line 50, in main
    ret = cmd.run()
  File "/home/saugat/repos/iterative/dvc/dvc/command/get.py", line 31, in run
    return self._get_file_from_repo()
  File "/home/saugat/repos/iterative/dvc/dvc/command/get.py", line 37, in _get_file_from_repo
    Repo.get(
  File "/home/saugat/repos/iterative/dvc/dvc/repo/get.py", line 55, in get
    repo.repo_tree.download(from_info, to_info, follow_subrepos=False)
  File "/home/saugat/repos/iterative/dvc/dvc/tree/base.py", line 396, in download
    return self._download_file(from_info, to_info, name, no_progress_bar,)
  File "/home/saugat/repos/iterative/dvc/dvc/tree/base.py", line 447, in _download_file
    self._download(  # noqa, pylint: disable=no-member
  File "/home/saugat/repos/iterative/dvc/dvc/tree/repo.py", line 415, in _download
    with self.open(from_info, "rb", **kwargs) as from_fobj:
  File "/home/saugat/repos/iterative/dvc/dvc/tree/repo.py", line 142, in open
    return dvc_tree.open(path_info, mode=mode, encoding=encoding, **kwargs)
  File "/home/saugat/repos/iterative/dvc/dvc/tree/dvc.py", line 62, in open
    raise FileNotFoundError from exc
FileNotFoundError
------------------------------------------------------------
2021-01-28 20:51:56,264 DEBUG: Version info for developers:
DVC version: 2.0.0a0+bb4604
---------------------------------
Platform: Python 3.9.1 on Linux-5.10.7-arch1-1-x86_64-with-glibc2.32
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs, webhdfs
Cache types: symlink
Cache directory: tmpfs on tmpfs
Caches: local
Remotes: https
Workspace directory: ext4 on /dev/sda9
Repo: dvc, git

$ ls
readme2.md.nNfdnWXzqGpSNRAJdUccnm.tmp
```

**Comment by skshetry** [comment]
The file wasnot even downloaded as it does not exist, yet there is a temp. file.

**Comment by efiop** [comment]
Good catch, @skshetry !

Also, for the record:
```
    raise FileNotFoundError from exc
FileNotFoundError
```
better messages for such exceptions are coming soon.

**Comment by jorgeorpinel** [comment]
Noticed this too recently.
