### ISSUE TITLE
get: unexpected error, if the file to download already exists

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#5387]
# Bug Report
```console
$ dvc get https://github.com/iterative/dvc README.rst -o reamde2.rst
$ dvc get https://github.com/iterative/dvc README.rst -o reamde2.rst -v
2021-02-02 16:10:25,831 ERROR: unexpected error - [Errno 17] File exists: 'reamde2.rst'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/saugat/repos/iterative/dvc/dvc/main.py", line 50, in main
    ret = cmd.run()
  File "/home/saugat/repos/iterative/dvc/dvc/command/get.py", line 31, in run
    return self._get_file_from_repo()
  File "/home/saugat/repos/iterative/dvc/dvc/command/get.py", line 37, in _get_file_from_repo
    Repo.get(
  File "/home/saugat/repos/iterative/dvc/dvc/repo/get.py", line 26, in get
    out = resolve_output(path, out)
  File "/home/saugat/repos/iterative/dvc/dvc/utils/__init__.py", line 366, in resolve_output
    raise FileExistsError(errno.EEXIST, os.strerror(errno.EEXIST), ret)
FileExistsError: [Errno 17] File exists: 'reamde2.rst'
------------------------------------------------------------
2021-02-02 16:10:26,617 DEBUG: Version info for developers:
DVC version: 2.0.0a0+d05be3.mod 
---------------------------------
Platform: Python 3.9.1 on Linux-5.10.11-arch1-1-x86_64-with-glibc2.32
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs, webhdfs
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda9
Caches: local
Remotes: https
Workspace directory: ext4 on /dev/sda9
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-02-02 16:10:26,619 DEBUG: Analytics is disabled.
```

**Comment by dberenbaum** [comment]
@skshetry The error should not be "unexpected," but can you clarify whether there is there any other issue here?

**Comment by skshetry** [comment]
@dberenbaum, it's a UI issue, and a regression introduced in 2.0, that's why it was tagged https://github.com/iterative/dvc/labels/p1-important, but can be lowered now to https://github.com/iterative/dvc/labels/p2-medium.

**Comment by dberenbaum** [comment]
I didn't realize that it was possible to overwrite an existing output with `dvc get` before 2.0. Not sure which behavior is more expected. Maybe we need a `--force` option or similar to handle this?
