### ISSUE TITLE
exp: git worktree is unsupported

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/dvc#5456]
# Bug Report

## Description

When running `dvc exp run --queue -s <stage_name> -n <exp_name>`, I get error:

```
> python -m dvc exp run --queue -s train_patches -n exp_name
ERROR: unexpected error - [Errno 2] No such file or directory: '<prefix>/.git/worktrees/<name>/logs/refs/stash'
```

The first time, I created a directory at this path (including parent folder which was non-existent before), after which I seem to have been able to queue one experiment. But when trying to queue another experiment, I initially got the below error:

```
> python -m dvc exp run --queue -s train_patches
ERROR: unexpected error - [Errno 21] Is a directory: '<prefix>/.git/worktrees/<name>/logs/refs/stash'
```

I then deleted the `logs/refs/stash` directory that I created, but not the parent folder `logs/refs/`, which now had a `logs/refs/exps/stash` file with the first queued experiment. Afterwards, I get again the above "No such file or directory" error and am not able to queue further experiments.

Also note that the error occurs and no experiment appears to have been added to `logs/refs/exps/stash`, but my worktree has been reset still even though the recording of the experiment failed [Update: I can see `git stash list` shows a number of stashed changes, presumably the ones created by `dvc exp run --queue`; maybe `git stash pop` should be done if queuing of experiment failed]

### Environment information

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 2.0.0a0+273b02
---------------------------------
Platform: Python 3.7.9 on Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-centos-7.8.2003-Core
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: xfs on /dev/sda1
Caches: local
Remotes: s3, s3
Workspace directory: xfs on /dev/sda1
Repo: dvc (subdir), git
```

**Additional Information (if any):**

```
> python -m dvc exp run --queue -s train_patches -n exp_name -v -v
2021-02-12 09:33:58,180 TRACE: Namespace(all_pipelines=False, cd='.', checkpoint_resume=None, cmd='run', cprofile=False, cprofile_dump=None, downstream=False, dry=False, force=False, force_downstream=False, func=<class 'dvc.command.experiments.CmdExperimentsRun'>, glob=False, instrument=False, instrument_open=False, interactive=False, jobs=None, metrics=False, name='exp_name', no_commit=False, no_run_cache=False, params=[], pdb=False, pipeline=False, pull=False, queue=True, quiet=0, recursive=False, reset=False, run_all=False, single_item=True, targets=['train_patches'], tmp_dir=False, verbose=2, version=None)
2021-02-12 09:33:58,386 DEBUG: Check for update is enabled.
2021-02-12 09:33:58,408 TRACE: PRAGMA user_version;
2021-02-12 09:33:58,408 TRACE: fetched: [(3,)]
2021-02-12 09:33:58,408 TRACE: CREATE TABLE IF NOT EXISTS state (inode INTEGER PRIMARY KEY, mtime TEXT NOT NULL, size TEXT NOT NULL, md5 TEXT NOT NULL, timestamp TEXT NOT NULL)
2021-02-12 09:33:58,409 TRACE: CREATE TABLE IF NOT EXISTS state_info (count INTEGER)
2021-02-12 09:33:58,409 TRACE: CREATE TABLE IF NOT EXISTS link_state (path TEXT PRIMARY KEY, inode INTEGER NOT NULL, mtime TEXT NOT NULL)
2021-02-12 09:33:58,409 TRACE: INSERT OR IGNORE INTO state_info (count) SELECT 0 WHERE NOT EXISTS (SELECT * FROM state_info)
2021-02-12 09:33:58,409 TRACE: PRAGMA user_version = 3;
2021-02-12 09:33:58,411 DEBUG: Detaching HEAD at 'HEAD'
2021-02-12 09:33:58,537 DEBUG: Stashing workspace
2021-02-12 09:33:58,665 DEBUG: Stashing changes in 'refs/stash'
2021-02-12 09:33:59,021 DEBUG: Restore HEAD to 'istn'
2021-02-12 09:33:59,037 TRACE: SELECT count from state_info WHERE rowid=?
2021-02-12 09:33:59,037 TRACE: fetched: [(308875,)]
2021-02-12 09:33:59,037 TRACE: UPDATE state_info SET count = ? WHERE rowid = ?
2021-02-12 09:33:59,064 ERROR: unexpected error - [Errno 2] No such file or directory: '/data/aschuh/hfresearch/.git/worktrees/hfresearch-istn/logs/refs/stash'
------------------------------------------------------------
Traceback (most recent call last):
  File "$HOME/source/dvc/dvc/main.py", line 50, in main
    ret = cmd.run()
  File "$HOME/source/dvc/dvc/command/experiments.py", line 528, in run
    **self._repro_kwargs,
  File "/hf/home/aschuh/source/dvc/dvc/repo/experiments/__init__.py", line 833, in run
    return run(self.repo, *args, **kwargs)
  File "/hf/home/aschuh/source/dvc/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/hf/home/aschuh/source/dvc/dvc/repo/experiments/run.py", line 38, in run
    targets=targets, params=params, tmp_dir=tmp_dir, **kwargs
  File "/hf/home/aschuh/source/dvc/dvc/repo/experiments/__init__.py", line 375, in reproduce_one
    stash_rev = self.new(checkpoint_resume=checkpoint_resume, **kwargs)
  File "/hf/home/aschuh/source/dvc/dvc/repo/experiments/__init__.py", line 46, in wrapper
    return f(exp, *args, **kwargs)
  File "/hf/home/aschuh/source/dvc/dvc/repo/experiments/__init__.py", line 438, in new
    return self._stash_exp(*args, **kwargs)
  File "/hf/home/aschuh/source/dvc/dvc/repo/experiments/__init__.py", line 171, in _stash_exp
    with self.scm.stash_workspace() as workspace:
  File "/hf/home/aschuh/tools/conda/envs/istn/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/hf/home/aschuh/source/dvc/dvc/scm/git/__init__.py", line 451, in stash_workspace
    rev = self.stash.push(**kwargs)
  File "/hf/home/aschuh/source/dvc/dvc/scm/git/stash.py", line 43, in push
    self.ref, message=message, include_untracked=include_untracked
  File "/hf/home/aschuh/source/dvc/dvc/scm/git/__init__.py", line 338, in _backend_func
    return func(*args, **kwargs)
  File "/hf/home/aschuh/source/dvc/dvc/scm/git/backend/gitpython.py", line 480, in _stash_push
    commit = self.resolve_commit("stash@{0}")
  File "/hf/home/aschuh/source/dvc/dvc/scm/git/backend/gitpython.py", line 322, in resolve_commit
    commit = self.repo.rev_parse(rev)
  File "/hf/home/aschuh/tools/conda/envs/istn/lib/python3.7/site-packages/git/repo/fun.py", line 261, in rev_parse
    entry = ref.log_entry(revlog_index)
  File "/hf/home/aschuh/tools/conda/envs/istn/lib/python3.7/site-packages/git/refs/symbolic.py", line 408, in log_entry
    return RefLog.entry_at(RefLog.path(self), index)
  File "/hf/home/aschuh/tools/conda/envs/istn/lib/python3.7/site-packages/git/refs/log.py", line 209, in entry_at
    with open(filepath, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/data/aschuh/hfresearch/.git/worktrees/hfresearch-istn/logs/refs/stash'
------------------------------------------------------------
2021-02-12 09:34:10,637 DEBUG: Version info for developers:
DVC version: 2.0.0a0+273b02
---------------------------------
Platform: Python 3.7.9 on Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-centos-7.8.2003-Core
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: xfs on /dev/sda1
Caches: local
Remotes: s3, s3
Workspace directory: xfs on /dev/sda1
Repo: dvc (subdir), git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-02-12 09:34:10,641 DEBUG: Analytics is disabled.
```

**Comment by pmrowla** [comment]
So experiments has not been tested in any `git worktree` scenarios, so this should probably be considered unsupported for the time being. Are you able to just use a "regular" git clone (with the single default working tree) as a workaround for the time being?

This will require a bit of research on our end, since I'm fairly sure refs and reflogs are not actually supposed to be stored in `.git/worktrees/.../refs/...` (rather it's something like all of the worktrees are supposed to share `.git/refs/...`). This also might require some more upstream patches for our git backends, since worktrees have probably also not been thoroughlytested  there either.

**Comment by schuhschuh** [comment]
Thanks, indeed the issue seems to be because of the use of `git worktree`. I don't have this error when I run in the main repo.

**Comment by pmrowla** [comment]
from #7149, we should consider detecting that we are in a worktree and warn users that it's unsupported, but this will probably still require making some changes in scmrepo backends

**Comment by skshetry** [comment]
Worktrees are now supported if [`dulwich>=0.24.2`](https://github.com/jelmer/dulwich/pull/1749) is installed. Will work OOTB on the next release.
