### ISSUE TITLE
exp: cleanup error during finalization

### ISSUE THREAD

**Issue by pared** [iterative/dvc#5478]
When running experiments in `tmp`, we get `FileNotFoundError` during cleanup.
```
#!/bin/bash

main=$(pwd)
rm -rf repo
mkdir repo
pushd repo

git init --quiet
dvc init --quiet

git add -A
git commit -am "init"
echo "param: 2" > params.yaml
echo "data" > data
dvc add data

dvc run -d data --params param -n train -o out 'cat params.yaml > out'
git add -A
git commit -am "run"

dvc exp run train -S param=3 --queue
dvc exp run --run-all
```

Result:
```
Queued experiment '17c7e16' for future execution.                     
'data.dvc' didn't change, skipping                                                                                                                
Running stage 'train':                                                                                                                            
> cat params.yaml > out
Updating lock file 'dvc.lock'                                                                                                                     
Exception ignored in: <finalize object at 0x7fb899ec3410; dead>                                                                                   
Traceback (most recent call last):
  File "/home/prd/development/venvs/dvc3.7/lib/python3.7/weakref.py", line 572, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/prd/development/venvs/dvc3.7/lib/python3.7/tempfile.py", line 934, in _cleanup
    _rmtree(name)
  File "/home/prd/development/venvs/dvc3.7/lib/python3.7/shutil.py", line 485, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/home/prd/development/venvs/dvc3.7/lib/python3.7/shutil.py", line 483, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/prd/development/playground/5741_exp_ext_cache_symlink/repo/.dvc/tmp/exps/tmpjco8_3pa'

Reproduced experiment(s): exp-2f709
To apply the results of an experiment to your workspace run:

	dvc exp apply <exp>

To promote an experiment to a Git branch run:

	dvc exp branch <exp>
```
Expected result:

no error message

dvc version:
```
DVC version: 2.0.0a0+66f24b 
---------------------------------
Platform: Python 3.7.5 on Linux-5.4.0-65-generic-x86_64-with-Ubuntu-18.04-bionic
Supports: All remotes
```

**Comment by pared** [comment]
Also, error shows up a lot while running `test_experiments`

**Comment by pmrowla** [comment]
Looks like https://github.com/iterative/dvc/issues/5374 was not actually fixed

**Comment by pared** [comment]
Thought in this case it was Linux

**Comment by pmrowla** [comment]
After investigation, this is not actually an error, it's just logged as a skipped/handled exception in python `tempfile.TemporaryDirectory` internals. Will submit a follow up to #5374 to make the new cleanup behavior happen in a subclass of `TemporaryDirectory` so that the skipped exception no longer occurs
