### ISSUE TITLE
push: hangs and reports impossible upload speeds

### ISSUE THREAD

**Issue by ajovanov95** [iterative/dvc#5488]
# Bug Report

push: hangs and reports impossible upload speeds

## Description

DVC hangs when pushing large files to google cloud storage.

### Reproduce

1. Make a cloud bucket for Google Cloud Storage (dvc remote add gcs ...)
2. Have a .ptx file from pytorch of size 69 MB (dvc commit models/file.ptx)
3. Have it partially uploaded up to 10 MB (dvc push)
4. The command hangs and displays unrealistic upload speeds (36 MB/s while my upload is tops 100 KB/s)
5. Force quit the script after a few minutes and get the following output showing a possible thread deadlock.

```
0% Uploading|                                                                                                                                                  |0/1 [00:00<?,     ?file/s^ERROR: interrupted by the user
^CError in atexit._run_exitfuncs:                                                                                                                      10.0M/69.0M [02:59<00:01,    36.0MB/s]
Traceback (most recent call last):
File "/var/lib/snapd/snap/dvc/1282/usr/lib/python3.6/concurrent/futures/thread.py", line 40, in _python_exit
t.join()
File "/var/lib/snapd/snap/dvc/1282/usr/lib/python3.6/threading.py", line 1056, in join
self._wait_for_tstate_lock()
File "/var/lib/snapd/snap/dvc/1282/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
elif lock.acquire(block, timeout):
KeyboardInterrupt
```

The push worked properly for my images but it shows this odd behaviour for the model file.

### Expected

My large .ptx files are pushed and stored on Google Cloud Storage Bucket.

### Environment information

```console
$ dvc version

DVC version: 1.11.13 (snap)
---------------------------------
Platform: Python 3.6.9 on Linux-5.10.15-1-MANJARO-x86_64-with-arch-Manjaro-Linux
Supports: All remotes
Cache types: hardlink, symlink
Caches: local
Remotes: gs
Repo: dvc, git
```

**Additional Information (if any):**

Here is `dvc push --verbose`

```
... (hashes of the sucessfully pushed png images)
2021-02-17 16:43:04,129 DEBUG: Collecting information from remote cache...
2021-02-17 16:43:04,129 DEBUG: Querying 2 hashes via object_exists
2021-02-17 16:43:04,709 DEBUG: Querying 0 hashes via object_exists
2021-02-17 16:43:04,720 DEBUG: Matched '0' indexed hashes
2021-02-17 16:43:04,898 DEBUG: Estimated remote size: 8192 files
2021-02-17 16:43:04,899 DEBUG: Large remote ('3' hashes < '8.192' traverse weight), using object_exists for remaining hashes
2021-02-17 16:43:04,899 DEBUG: Querying 3 hashes via object_exists
2021-02-17 16:43:05,442 DEBUG: Uploading '.dvc/cache/0d/37367448a475d8787ee4d97688a7b3' to 'gs://gcs-bucket-name/0d/37367448a475d8787ee4d97688a7b3'
2021-02-17 16:43:05,443 DEBUG: Uploading '.dvc/cache/7b/47f419afe7f734f824ef2d2ef5e85f' to 'gs://gcs-bucket-name/7b/47f419afe7f734f824ef2d2ef5e85f'
0% Uploading|                                                                                                                                                  |0/2 [00:00<?,     ?file/s]
14%|█▍        |models/file.ptx                                                                                                                       10.0M/69.0M [00:00<00:01,    37.7MB/s]
6%|▌         |models/file2.ptx                                                                                                               10.0M/179M [00:00<00:04,    43.1MB/s]
```

**Comment by isidentical** [comment]
I can't reproduce this on master branch.
```
dd if=/dev/urandom of=bigfile bs=500000 count=150
dvc add bigfile
dvc push bigfile
```

**Comment by isidentical** [comment]
@ajovanov95 if you are able to use a newer version, please feel free to test the upstream and let us know whether this case still occurs. It comes with a newer implementation for google cloud storage which might help in your situation.

**Comment by ajovanov95** [comment]
Hi,

Thanks for looking into this :)

I found the problem. My pipeline step was failed for this output file (exit code != 0). Once the pipeline step was completed the push went successfully.

It seems the problem was in dvc.lock actually and not in the push itself.

**Comment by efiop** [comment]
@ajovanov95 That should not have caused the original issues though. Glad it works now, but if you run into this again - please let us know, we'll try to take another look. Thanks for the feedback!
