### ISSUE TITLE
get: trying to get a folder containing outs is throwing an error

### ISSUE THREAD

**Issue by sjawhar** [iterative/dvc#5501]
# Bug Report

## Description

My repo contains a `dist` folder which is ignored by git. This dist folder is not itself an output of any dvc stage, but it contains other folders and files that are. Running `dvc get` on this folder returns an error:

```
2021-02-19 17:58:16,018 ERROR: unexpected error - too many values to unpack (expected 1)
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dvc/main.py", line 90, in main
    ret = cmd.run()
  File "/usr/local/lib/python3.8/dist-packages/dvc/command/get.py", line 31, in run
    return self._get_file_from_repo()
  File "/usr/local/lib/python3.8/dist-packages/dvc/command/get.py", line 37, in _get_file_from_repo
    Repo.get(
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/get.py", line 52, in get
    repo.get_external(path, out)
  File "/usr/local/lib/python3.8/dist-packages/dvc/external_repo.py", line 205, in get_external
    save_info = self._fetch_to_cache(path_info, repo, None)
  File "/usr/local/lib/python3.8/dist-packages/dvc/external_repo.py", line 139, in _fetch_to_cache
    hash_info = tree.get_hash(
  File "/usr/local/lib/python3.8/dist-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/usr/local/lib/python3.8/dist-packages/dvc/tree/base.py", line 45, in use_state
    return call()
  File "/usr/local/lib/python3.8/dist-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dvc/tree/base.py", line 267, in get_hash
    if not self.exists(path_info):
  File "/usr/local/lib/python3.8/dist-packages/dvc/tree/repo.py", line 170, in exists
    (out,) = meta.outs
ValueError: too many values to unpack (expected 1)
------------------------------------------------------------
2021-02-19 17:58:16,168 DEBUG: Version info for developers:
DVC version: 1.11.15 (pip)
```

In `RepoTree.exists()`, meta.outs does not have length 1. Instead, it contains a list of the subdirectories of `dist`, each of which are themselves outs of some stage in the pipeline.

### Reproduce

If I have the time, I'll try to create an example repo to recreate the issue.

### Expected

I'd like dvc to download the dist folder and its contents.

### Environment information

**Output of `dvc version`:**

```console
DVC version: 1.11.15 (pip)
---------------------------------
Platform: Python 3.8.0 on Linux-5.8.0-43-generic-x86_64-with-glibc2.27
Supports: hdfs, http, https, s3
Cache types: symlink
Cache directory: ext4 on /dev/nvme0n1p6
Caches: local
Remotes: s3, s3
Workspace directory: ext4 on /dev/nvme0n1p6
Repo: dvc, git
```

Also tried on the latest master

**Additional Information (if any):**

**Comment by efiop** [comment]
Discord context https://discord.com/channels/485586884165107732/485596304961962003/812383150034518066

**Comment by dberenbaum** [comment]
This appears to have been fixed at some point.

Reproduction script:

```
mkdir repo
cd repo
git init
dvc init -q
mkdir dist
echo "dist" > .gitignore
dvc run -q -n foo -o dist/foo "echo foo > dist/foo"
dvc run -q -n bar -o dist/bar "echo bar > dist/bar"
git add .
git commit -q -m "repro dist outputs"
dvc get -o newdist . dist
```

With version 1.11.15, I get `ERROR: unexpected error - too many values to unpack (expected 1)`. I get no errors with version 2.9.5.
