### ISSUE TITLE
config: allow_agent is not taken into account (in 2.0.0a0)

### ISSUE THREAD

**Issue by gcoter** [iterative/dvc#5510]
# Bug Report

## Description

I am trying the pre-release of 2.0.0. I have set the option `allow_agent` (to configure an SSH remote) in the config file of DVC as I did with the previous versions but it doesn't seem to take it into account.

### Reproduce
Unfortunately the error ("No existing session") is specific to my environment and I don't know how you could reproduce it, but you might try to:

0. Start from some repository
1. Set `allow_agent` to `false`: `dvc remote modify myremote allow_agent false`
2. Check whether Paramiko receives the value `False` [here](https://github.com/iterative/dvc/blob/d587d41d6c73147be19fe207c9d0881392417f8f/dvc/fs/ssh/__init__.py#L147)

I didn't have much time to investigate but if you look at the `config` object which is passed to create the SSH connection, this object doesn't contain `allow_agent` and as a consequence the default value `True` is used (I want it to be `False`).

### Expected

Normally, the value `False` should be passed to create the connection (which would prevent the error "No existing session") instead of the default value `True`.

### Environment information

**Output of `dvc version`:**
```console
$ dvc version
DVC version: 2.0.0a0 (pip)
---------------------------------
Platform: Python 3.7.9 on Linux-4.15.0-122-generic-x86_64-with-debian-stretch-sid
Supports: http, https, ssh
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda1
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/sda1
Repo: dvc, git
```

**Comment by pmrowla** [comment]
Hi @gcoter, I'm unable to reproduce this issue in both 2.0.0a0 and current master.

```
#!/bin/bash

REPO="test-repo"
REMOTE="test-remote"
ROOT=`pwd`


rm -r -f $REPO $REMOTE
mkdir -p $REPO $REMOTE

cd $REPO

git init
dvc init

dvc remote add -d myremote ssh://localhost$ROOT/$REMOTE
dvc remote modify myremote allow_agent false

echo foo > foo.txt
dvc add foo.txt

dvc push -vv
```

Using this script and adding these lines in our SSH connection method (that you noted), I see that `allow_agent` is being set to False as expected

```py
        assert not self.allow_agent
        logger.debug(f"allow_agent: {self.allow_agent}")
```

```
...
2021-02-24 14:58:37,844 DEBUG: allow_agent: False
2021-02-24 14:58:37,845 DEBUG: Establishing ssh connection with 'localhost' through port '22' as user 'pmrowla'
2021-02-24 14:58:38,089 DEBUG: Uploading '.dvc/cache/d3/b07384d113edec49eaa6238ad5ff00' to 'ssh://pmrowla@localhost/Users/pmrowla/git/scratch/5510/test-remote/d3/b07384d113edec49eaa6238ad5ff00'
2021-02-24 14:58:38,089 DEBUG: allow_agent: False
2021-02-24 14:58:38,094 TRACE: SELECT count from state_info WHERE rowid=?
2021-02-24 14:58:38,095 TRACE: fetched: [(2,)]
2021-02-24 14:58:38,095 TRACE: UPDATE state_info SET count = ? WHERE rowid = ?
1 file pushed
...
```

**Comment by pmrowla** [comment]
Could you share the actual DVC commands that you are using, and the error that occurs (run the command with `-v` and include the traceback)?

**Comment by gcoter** [comment]
Hi @pmrowla, sorry for my late reply...

The command that I wanted to run was `dvc status`. Here are the tracebacks of the errors:
```
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/output/base.py", line 487, in get_dir_cache
    objects.check(self.odb, self.odb.get(self.hash_info))
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/objects/__init__.py", line 197, in check
    odb.check(obj.hash_info)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/objects/db/base.py", line 110, in check
    obj.check(self)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/objects/__init__.py", line 39, in check
    actual = get_hash(self.path_info, self.fs, odb.fs.PARAM_CHECKSUM)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/objects/stage.py", line 108, in get_hash
    errno.ENOENT, os.strerror(errno.ENOENT), path_info
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp1g_6kl_ldvc-cache/e8/de0ef20b41e244c604cc81a0696bf8.dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/main.py", line 50, in main
    ret = cmd.run()
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/command/status.py", line 58, in run
    recursive=self.args.recursive,
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/repo/status.py", line 154, in status
    self, targets, with_deps=with_deps, recursive=recursive
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/repo/status.py", line 38, in _local_status
    return _joint_status(pairs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/repo/status.py", line 23, in _joint_status
    stage.status(check_updates=True, filter_info=filter_info)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/stage/__init__.py", line 560, in status
    self._status_deps(ret)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/stage/__init__.py", line 576, in _status_deps
    deps_status = self._status(self.deps)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/stage/__init__.py", line 571, in _status
    ret.update(entry.status())
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/dependency/repo.py", line 68, in status
    return self.workspace_status()
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/dependency/repo.py", line 59, in workspace_status
    current = self._get_hash(locked=True)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/dependency/repo.py", line 55, in _get_hash
    path_info, repo.repo_fs, "md5", follow_subrepos=False
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/objects/stage.py", line 135, in get_hash
    hash_info = get_dir_hash(path_info, fs, name, **kwargs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/objects/stage.py", line 94, in get_dir_hash
    dir_info = _collect_dir(path_info, fs, name, **kwargs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/objects/stage.py", line 74, in _collect_dir
    for fi, hi in _iter_hashes(path_info, fs, name, **kwargs):
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/objects/stage.py", line 57, in _iter_hashes
    for file_info in fs.walk_files(path_info, **kwargs):
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/fs/repo.py", line 370, in walk_files
    for root, _, files in self.walk(top, **kwargs):
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/fs/repo.py", line 361, in walk
    yield from dvc_fs.walk(top, topdown=topdown, **kwargs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/fs/dvc.py", line 200, in walk
    self._add_dir(trie, out, **kwargs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/fs/dvc.py", line 145, in _add_dir
    self._fetch_dir(out, **kwargs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/fs/dvc.py", line 132, in _fetch_dir
    out.get_dir_cache(**kwargs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/output/base.py", line 492, in get_dir_cache
    **kwargs,
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/data_cloud.py", line 92, in pull
    show_checksums=show_checksums,
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/remote/base.py", line 56, in wrapper
    return f(obj, *args, **kwargs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/remote/base.py", line 492, in pull
    download=True,
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/remote/base.py", line 328, in _process
    download=download,
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/remote/base.py", line 176, in _status
    md5s, jobs=jobs, name=str(self.fs.path_info)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/remote/base.py", line 132, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/objects/db/ssh.py", line 73, in hashes_exist
    ret = list(itertools.compress(hashes, in_remote))
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/objects/db/ssh.py", line 64, in exists_with_progress
    return self.batch_exists(chunks, callback=pbar.update_msg)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/objects/db/ssh.py", line 31, in batch_exists
    with self.fs.ssh(path_infos[0]) as ssh:
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/fs/pool.py", line 11, in get_connection
    conn = pool.get_connection()
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/fs/pool.py", line 53, in get_connection
    return self._conn_func(*self._conn_args, **self._conn_kwargs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/dvc/fs/ssh/connection.py", line 57, in __init__
    self._ssh.connect(host, *args, **kwargs)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/paramiko/client.py", line 446, in connect
    passphrase,
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/paramiko/client.py", line 764, in _auth
    raise saved_exception
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/paramiko/client.py", line 751, in _auth
    self._transport.auth_password(username, password)
  File "/home/rd/anaconda3/envs/my-project/lib/python3.7/site-packages/paramiko/transport.py", line 1498, in auth_password
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session
```

One hypothesis that I have is that in my case, I need to connect to a remote repository that I use as a data registry. Maybe that could be a difference between my setup and yours, which would explain why you could not reproduce my issue?

Thanks for your help :)

**Comment by pmrowla** [comment]
> One hypothesis that I have is that in my case, I need to connect to a remote repository that I use as a data registry. Maybe that could be a difference between my setup and yours, which would explain why you could not reproduce my issue?

Do you mean that this is in a DVC repo where you have `dvc import`ed from another data registry?

Or that this DVC repo is used as a data registry (and other repos `dvc import` from this one)?

If it's the 2nd case, that should still work the same way as my test setup.

**Comment by gcoter** [comment]
I have `dvc import`ed from another data registry :slightly_smiling_face:

**Comment by pmrowla** [comment]
Then the problem is that when you use `dvc import`, the default remote configuration from the source repo is used (so `.dvc/config` in the repo you are importing from), not the remote configuration for the repo you are importing into.

Do you have the `allow_agent false` remote setting git-committed in `.dvc/config` for the data registry repo?

**Comment by gcoter** [comment]
Oh I see! That might be the cause of the issue. Indeed, `allow_agent false` is not commited in git, this is a parameter that I set in `.dvc/config.local` because it is specific to my personal development environment

**Comment by pmrowla** [comment]
One workaround would be to do `dvc remote modify --global <remote> allow_agent false`, this should get dvc to set `allow_agent` to false in any repo that you are using `remote` (even on import). On import, the repo level config from your data registry will still be merged with your machine's `--global` and `--system` level configs. (But your machine's repo and `--local` level configs will be ignored, as noted earlier)

**Comment by gcoter** [comment]
But I don't know if that makes sense since my case is maybe very particular, anyway your workaround works for me and I can keep on working :slightly_smiling_face:

**Comment by pmrowla** [comment]
There is not currently a way to configure a value in DVC in order to make it apply to all remotes of a certain type (`ssh` in this case). You could open a feature request for us to consider in the future.

Regarding the specific URL in `--global`, you do need to provide a URL for the `dvc remote add` command to work, and the remote section needs to exist in the config file in order for `dvc remote modify` to work, but the URL itself is not necessary. So you could edit the global config file (`$HOME/.dvc/config` [on linux](https://dvc.org/doc/command-reference/config#description)) to just contain:

```
['remote "myremote"']
    allow_agent = true
```

Either by running `remote add --global`, `remote modify --global`, and then removing the `url` field yourself, or by just manually editing the config file. This would make `allow_agent` set to True in all remotes named `myremote` across any DVC repo, and the URL field would be read from each specific repo level config. So if all of your SSH remotes use the same `myremote` name (but with different URLs) this would give you consistent behavior across all of your projects.

**Comment by gcoter** [comment]
That would indeed work for me as I use the same remote name for all my projects. Thank you :slightly_smiling_face:
