### ISSUE TITLE
gdrive: looking for user credentials when configured with service account

### ISSUE THREAD

**Issue by john-heyer** [iterative/dvc#5551]
# Bug Report

dvc push looking for user credentials when configured with service account
## Description

I have set up dvc with gdrive, created a google cloud project, and then created a service account according to: https://dvc.org/doc/user-guide/setup-google-drive-remote. I then `dvc add` a file and `dvc push`, and receive an error indicating that my gdrive user credentials file is missing.

here is the trace when running `dvc push -v`:
```
2021-03-04 18:47:25,775 DEBUG: Check for update is enabled.
2021-03-04 18:47:26,472 DEBUG: Preparing to upload data to 'gdrive://1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m'
2021-03-04 18:47:26,472 DEBUG: Preparing to collect status from gdrive://1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m
2021-03-04 18:47:26,472 DEBUG: Collecting information from local cache...
2021-03-04 18:47:26,475 DEBUG: Collecting information from remote cache...                                         
2021-03-04 18:47:26,475 DEBUG: Querying 1 hashes via object_exists
2021-03-04 18:47:28,678 DEBUG: GDrive remote auth with config '{'client_config_backend': 'settings', 'client_config_file': 'client_secrets.json', 'save_credentials': True, 'oauth_scope': ['https://www.googleapis.com/auth/drive', 'https://www.googleapis.com/auth/drive.appdata'], 'save_credentials_file': '/home/jaheyer/chipbrain/chipbrain-transformers/.dvc/tmp/gdrive-user-credentials.json', 'get_refresh_token': True, 'save_credentials_backend': 'json', 'service_config': {'client_user_email': 'dvc-remote-storage@dvc-remote-storage-305303.iam.gserviceaccount.com', 'client_json_file_path': '/home/jaheyer/chipbrain/chipbrain-transformers/.dvc/dvc-remote-storage-305303-2331a8a33e40.json'}}'.
2021-03-04 18:47:28,680 ERROR: failed to push data to the cloud - Failed to authenticate GDrive remote: [Errno 2] No such file or directory: '/home/jaheyer/chipbrain/chipbrain-transformers/.dvc/tmp/gdrive-user-credentials.json'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jaheyer/miniconda3/envs/transformers/lib/python3.7/site-packages/dvc/fs/gdrive.py", line 258, in _drive
    gauth.ServiceAuth()
  File "/home/jaheyer/miniconda3/envs/transformers/lib/python3.7/site-packages/pydrive2/auth.py", line 98, in _decorated
    self.LoadCredentials()
  File "/home/jaheyer/miniconda3/envs/transformers/lib/python3.7/site-packages/pydrive2/auth.py", line 329, in LoadCredentials
    self.LoadCredentialsFileJson()
  File "/home/jaheyer/miniconda3/envs/transformers/lib/python3.7/site-packages/pydrive2/auth.py", line 366, in LoadCredentialsFileJson
    filename=credentials_file, scopes=scopes
  File "/home/jaheyer/miniconda3/envs/transformers/lib/python3.7/site-packages/oauth2client/service_account.py", line 219, in from_json_keyfile_name
    with open(filename, 'r') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jaheyer/chipbrain/chipbrain-transformers/.dvc/tmp/gdrive-user-credentials.json'
```
### Reproduce
N/A - don't know how to create a MWE involving service accounts and credentials. 

### Expected

I expect DVC to push my files to the gdrive.
### Environment information

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 2.0.1 (pip)
---------------------------------
Platform: Python 3.7.10 on Linux-4.15.0-46-generic-x86_64-with-debian-buster-sid
Supports: gdrive, http, https
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda
Caches: local
Remotes: gdrive
Workspace directory: ext4 on /dev/sda
Repo: dvc, git
```

**Additional Information (if any):**
contents of my .dvc/config:
```
[core]
    remote = storage
['remote "storage"']
    url = gdrive://1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m
    gdrive_use_service_account = true
    gdrive_service_account_json_file_path = dvc-remote-storage-305303-2331a8a33e40.json
    gdrive_service_account_user_email = dvc-remote-storage@dvc-remote-storage-305303.iam.gserviceaccount.com
```

I have used user credentials to authenticate and push to this drive folder in the past, but since then I have `rm -rf .dvc/`, uninstalled dvc 1.3 and installed dvc 2.0.1

**Comment by efiop** [comment]
Discord context https://discord.com/channels/485586884165107732/563406153334128681/817180163988652052

**Comment by shcheklein** [comment]
It can be a regression in the latest PyDrive2 PR that introduced JSON support - https://github.com/iterative/PyDrive2/issues/96 . Waiting for @isidentical response to see if I'm missing something.

**Comment by john-heyer** [comment]
After updating, the missing file error is missing, but I still cannot access my drive via a service accout:

```
dvc push -v
2021-03-09 21:27:20,450 DEBUG: Check for update is enabled.
2021-03-09 21:27:20,466 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-03-09 21:27:20,467 DEBUG: Spawned '['daemon', '-q', 'updater']'
2021-03-09 21:27:20,720 DEBUG: Preparing to upload data to 'gdrive://1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m'
2021-03-09 21:27:20,720 DEBUG: Preparing to collect status from gdrive://1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m
2021-03-09 21:27:20,720 DEBUG: Collecting information from local cache...
2021-03-09 21:27:20,722 DEBUG: Collecting information from remote cache...                                                                                                                                                                                                                                                                             
2021-03-09 21:27:20,722 DEBUG: Querying 1 hashes via object_exists
2021-03-09 21:27:20,908 DEBUG: GDrive remote auth with config '{'client_config_backend': 'settings', 'client_config_file': 'client_secrets.json', 'save_credentials': True, 'oauth_scope': ['https://www.googleapis.com/auth/drive', 'https://www.googleapis.com/auth/drive.appdata'], 'save_credentials_backend': 'file', 'save_credentials_file': '/home/jaheyer/chipbrain/chipbrain-transformers/.dvc/tmp/gdrive-user-credentials.json', 'get_refresh_token': True, 'service_config': {'client_user_email': 'dvc-remote-storage@dvc-remote-storage-305303.iam.gserviceaccount.com', 'client_json_file_path': '/home/jaheyer/chipbrain/chipbrain-transformers/.dvc/dvc-remote-storage-305303-2331a8a33e40.json'}}'.
2021-03-09 21:27:21,305 ERROR: failed to push data to the cloud - '1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m' for 'gdrive://1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m':                                                                                                                                                                                                

1. Confirm the directory exists and you can access it.
2. Make sure that credentials in '/home/jaheyer/chipbrain/chipbrain-transformers/.dvc/tmp/gdrive-user-credentials.json'
   are correct for this remote e.g. use the `gdrive_user_credentials_file` config
   option if you use multiple GDrive remotes with different email accounts.

Details: <HttpError 404 when requesting https://www.googleapis.com/drive/v2/files/1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m?fields=driveId&supportsAllDrives=true&alt=json returned "File not found: 1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m". Details: "File not found: 1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m">
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jaheyer/miniconda3/envs/transformers/lib/python3.7/site-packages/pydrive2/files.py", line 464, in FetchMetadata
    .execute(http=self.http)
  File "/home/jaheyer/miniconda3/envs/transformers/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/jaheyer/miniconda3/envs/transformers/lib/python3.7/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v2/files/1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m?fields=driveId&supportsAllDrives=true&alt=json returned "File not found: 1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m". Details: "File not found: 1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m">
```

**Comment by isidentical** [comment]
@john-heyer can you try to do `dvc remote modify storage url gdrive://root/1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m` (or whatever directory that you are using and let us know whether it still fails or works?

**Comment by shcheklein** [comment]
I think we had a discussion on Discord (unless I'm missing something) and the issue is that we are getting 404 and we agreed that to resolve this we need to give the service account email access to the `1qOaTb9rdhBlUdHeilikWMzAu7PI_KH7m`.

**Comment by efiop** [comment]
Closing as stale.
