### ISSUE TITLE
Issue with fetch from azure remote "no current event loop in thread"

### ISSUE THREAD

**Issue by friggog** [iterative/dvc#5556]
# Bug Report

I'm getting this error
```
ERROR: failed to download 'azure://container/***' to '.dvc\cache\***' - There is no current event loop in thread 'ThreadPoolExecutor-127_0
...
ERROR: failed to download 'azure://container/***' to '.dvc\cache\***' - There is no current event loop in thread 'ThreadPoolExecutor-127_14
ERROR: failed to fetch data from the cloud - 53 files failed to download
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002159F326E88
```
For a number of files (not all as far I can tell) when running 
`dvc fetch [some_files]` on Azure devops windows CI machine with SPA auth.

DVC v2.0.3, everything seems to run fine on my local windows machine

This still fails if I set the number of jobs to 1

This is working fine with DVC v1.11.10

**Comment by efiop** [comment]
@friggog Please post verbose log for that command. E.g. `dvc fetch -v`. Also, please post `dvc doctor` output.

**Comment by friggog** [comment]
```
DVC version: 2.0.3 (pip)
---------------------------------
Platform: Python 3.7.9 on Windows-10-10.0.14393-SP0
Supports: azure, hdfs, http, https, ssh
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: azure
Workspace directory: NTFS on D:\
Repo: dvc (subdir), git
2021-03-05 16:23:34,513 DEBUG: Check for update is enabled.
2021-03-05 16:23:34,540 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-03-05 16:23:34,590 DEBUG: Spawned '['daemon', '-q', 'updater']'
2021-03-05 16:23:34,619 DEBUG: Checking if stage 'FILE_1' is in 'dvc.yaml'
2021-03-05 16:23:35,958 DEBUG: Checking if stage 'FILE_2' is in 'dvc.yaml'
2021-03-05 16:23:35,959 DEBUG: Checking if stage 'FILE_3' is in 'dvc.yaml'
2021-03-05 16:23:35,960 DEBUG: Checking if stage 'DIR\FILE_4' is in 'dvc.yaml'
2021-03-05 16:23:36,759 DEBUG: Preparing to download data from 'azure://CONTAINER_NAME'
2021-03-05 16:23:36,760 DEBUG: Preparing to collect status from azure://CONTAINER_NAME
2021-03-05 16:23:36,760 DEBUG: Collecting information from local cache...
2021-03-05 16:23:36,760 DEBUG: Collecting information from remote cache...
2021-03-05 16:23:36,761 DEBUG: Matched '0' indexed hashes
2021-03-05 16:23:36,761 DEBUG: Querying 1 hashes via object_exists
2021-03-05 16:23:36,765 DEBUG: failed to pull cache for 'DIR'
2021-03-05 16:23:35,960 DEBUG: Checking if stage 'DIR\FILE_5' is in 'dvc.yaml'
2021-03-05 16:23:36,759 DEBUG: Preparing to download data from 'azure://CONTAINER_NAME'
2021-03-05 16:23:36,760 DEBUG: Preparing to collect status from azure://CONTAINER_NAME
2021-03-05 16:23:36,760 DEBUG: Collecting information from local cache...
2021-03-05 16:23:36,760 DEBUG: Collecting information from remote cache...
2021-03-05 16:23:36,761 DEBUG: Matched '0' indexed hashes
2021-03-05 16:23:36,761 DEBUG: Querying 1 hashes via object_exists
2021-03-05 16:23:36,765 DEBUG: failed to pull cache for 'DIR'

... many times ....

-----------------------------------------------------------
2021-03-05 16:24:56,944 ERROR: failed to download 'azure://CONTAINER_NAME/e4/deb4d2426b0b5fd5919319e3eca7e7' to '.dvc\cache\e4\deb4d2426b0b5fd5919319e3eca7e7' - There is no current event loop in thread 'ThreadPoolExecutor-127_2'.
------------------------------------------------------------
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\dvc\remote\base.py", line 35, in wrapper
    func(from_info, to_info, *args, **kwargs)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\dvc\fs\base.py", line 280, in download
    return self._download_file(from_info, to_info, name, no_progress_bar,)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\dvc\fs\base.py", line 332, in _download_file
    from_info, tmp_file, name=name, no_progress_bar=no_progress_bar
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\dvc\fs\fsspec_wrapper.py", line 104, in _download
    with self.open(from_info, "rb") as fobj:
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\dvc\fs\fsspec_wrapper.py", line 48, in open
    return self.fs.open(self._with_bucket(path_info), mode=mode)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\fsspec\spec.py", line 943, in open
    **kwargs,
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\adlfs\spec.py", line 1445, in _open
    **kwargs,
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\adlfs\spec.py", line 1509, in __init__
    fs.service_client.get_container_client(self.container_name)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\azure\storage\blob\aio\_blob_service_client_async.py", line 591, in get_container_client
    key_resolver_function=self.key_resolver_function, loop=self._loop)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\azure\storage\blob\aio\_container_client_async.py", line 118, in __init__
    **kwargs)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\azure\storage\blob\_container_client.py", line 149, in __init__
    super(ContainerClient, self).__init__(parsed_url, service='blob', credential=credential, **kwargs)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\azure\storage\blob\_shared\base_client.py", line 114, in __init__
    self._config, self._pipeline = self._create_pipeline(self.credential, storage_sdk=service, **kwargs)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\azure\storage\blob\_shared\base_client_async.py", line 71, in _create_pipeline
    self._credential_policy = AsyncBearerTokenCredentialPolicy(credential, STORAGE_OAUTH_SCOPE)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\azure\core\pipeline\policies\_authentication_async.py", line 24, in __init__
    self._lock = asyncio.Lock()
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\asyncio\locks.py", line 161, in __init__
    self._loop = events.get_event_loop()
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\asyncio\events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-127_2'.

... many times ...

------------------------------------------------------------
2021-03-05 16:24:56,993 ERROR: failed to fetch data from the cloud - 53 files failed to download
------------------------------------------------------------
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\dvc\command\data_sync.py", line 89, in run
    run_cache=self.args.run_cache,
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\dvc\repo\__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\dvc\repo\fetch.py", line 77, in fetch
    raise DownloadError(failed)
dvc.exceptions.DownloadError: 53 files failed to download
------------------------------------------------------------
2021-03-05 16:24:56,997 DEBUG: Analytics is enabled.
2021-03-05 16:24:57,000 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpy3i7nnwh']'
2021-03-05 16:24:57,052 DEBUG: Spawned '['daemon', '-q', 'analytics', 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpy3i7nnwh']'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000016651F9DEC8>
```

I'm pretty sure it is only files that are within a directory that is tracked (rather than the file itself being tracked) that are failing.

Also tried a fresh clone on my local machine and I'm getting auth errors with DefaultAzureCredentials :(

**Comment by friggog** [comment]
Update that this problem persists on the latest version (2.0.13) and happens both locally and on CI

**Comment by friggog** [comment]
After some further investigation, this issue seems to arise because `adlfs` uses `azure.identity.aio` and `azure.storage.blob.aio ` which both use `asyncio`. Because DVC uses `ThreadPoolExecutor` at various points (e.g. [here](https://github.com/iterative/dvc/blob/a1aab35f997a1f9175f945f8266cf4038a5715b8/dvc/remote/base.py#L364) and [here](https://github.com/iterative/dvc/blob/a1aab35f997a1f9175f945f8266cf4038a5715b8/dvc/fs/base.py#L306)) without any handling for `asyncio` this causes the failures above where there is no event loop available to `aysncio` within threads of the `ThreadPoolExecutor`. Disabling uses of `ThreadPoolExecutor` within DVC results in pulls from Azure succeeding. 

@isidentical @efiop 
I'm a little confused why nobody else seems to have this issue? Also not sure what is the best path for a reliable fix - I have no experience with `asyncio`...

**Comment by skshetry** [comment]
@friggog, could you please try installing adlfs from the master?  It could have been fixed in upstream.
```console
$ pip install git+https://github.com/dask/adlfs.git
```

**Comment by friggog** [comment]
Nope same error @skshetry

**Comment by friggog** [comment]
@isidentical have you managed to repro this at all?

**Comment by isidentical** [comment]
> @isidentical have you managed to repro this at all?

No, unfortunately, I haven't encounter this error. If you can share your specific conditions (which login method are you using, which operation it is exactly failing etc) I'll try to work on it.

**Comment by friggog** [comment]
I'm using the DefaultAzureCredential with cached azure CLI credentials (run `az login` before DVC commands) and also ServicePrincipleAuth on Devops CI. Both have the same error with `dvc fetch some_files`

**Comment by isidentical** [comment]
I've reproduced your issue @friggog via using `DefaultCredentials`. The fix is simple though it is a bit in the gray line on whether we should fix it on the dvc itself or on the adlfs so I've opened a question on the adlfs upstream dask/adlfs#218

**Comment by friggog** [comment]
@isidentical In the interest of making this functional for DVC users can we fix it here now even if not the perfect solution, then if eventually it gets fixed in adlfs the alterations can be removed from DVC?
