### ISSUE TITLE
dvc.api.open: HTTPError

### ISSUE THREAD

**Issue by hugo-ricateau-tiime** [iterative/dvc#5558]
### Bug Report
`dvc.api.open` fails with an `HTTPError` while `dvc pull` works just fine.

### Setup
```console
$ dvc version
DVC version: 2.0.2 (pip)
---------------------------------
Platform: Python 3.6.10 on Darwin-20.3.0-x86_64-i386-64bit
Supports: http, https, s3, ssh
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
```

### Steps to reproduce
Considering the situation already exposed [here](https://github.com/iterative/dvc/issues/4667), the following code
```python3
import logging
from dvc.api import open

logger = logging.getLogger('dvc')
logger.setLevel(logging.DEBUG)

with open('foo', mode='rb') as file:
    bar = file.read()
```
fails (without any log) with the following uncaught exception:
```python3
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-X-XXXXXXXXXXXX> in <module>
----> 1 with open('foo', mode='rb') as file:
      2     bar = file.read()
      3

.../python3.6/contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

.../python3.6/site-packages/dvc/api.py in _open(path, repo, rev, remote, mode, encoding)
     76     with Repo.open(repo, rev=rev, subrepos=True, uninitialized=True) as _repo:
     77         with _repo.open_by_relpath(
---> 78             path, remote=remote, mode=mode, encoding=encoding
     79         ) as fd:
     80             yield fd

.../python3.6/contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

.../python3.6/site-packages/dvc/repo/__init__.py in open_by_relpath(self, path, remote, mode, encoding)
    479         try:
    480             with fs.open(
--> 481                 path, mode=mode, encoding=encoding, remote=remote,
    482             ) as fobj:
    483                 yield fobj

.../python3.6/contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

.../python3.6/site-packages/dvc/utils/http.py in open_url(url, mode, encoding, **iter_opts)
     14     assert mode in {"r", "rt", "rb"}
     15
---> 16     with iter_url(url, **iter_opts) as (response, it):
     17         bytes_stream = IterStream(it)
     18

.../python3.6/contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

.../python3.6/site-packages/dvc/utils/http.py in iter_url(url, chunk_size)
     57             response.close()
     58
---> 59     response = request()
     60     it = gen(response)
     61     try:

.../python3.6/site-packages/dvc/utils/http.py in request(headers)
     34         if response.status_code == 404:
     35             raise FileNotFoundError(f"Can't open {the_url}")
---> 36         response.raise_for_status()
     37         return response
     38

.../python3.6/site-packages/requests/models.py in raise_for_status(self)
    941
    942         if http_error_msg:
--> 943             raise HTTPError(http_error_msg, response=self)
    944
    945     def close(self):

HTTPError: 400 Client Error: Bad Request for url: https://bucket-name.s3-eu-west-1.amazonaws.com/bucket-name/XX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX%2FXXXXXXXX%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210305T184008Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
(note the incoherent `eu-west-1` and `us-east-1` localisations present in the url). In the meantime, `dvc pull foo` perfectly works. Note that it suddenly stopped to work (with a previous `dvc` version before upgrading) with the following exception:
```
HTTPError: 403 Client Error: Forbidden for url: https://bucket-name.s3-eu-west-1.amazonaws.com/bucket-name/XX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX?AWSAccessKeyId=XXXXXXXXXXXXXXXXXXXX&Signature=XXXXXXXXXXXXXXXXXXXX%2FXXXXXX%3D&Expires=1614884948
```
Any idea what's going on?

**Comment by isidentical** [comment]
>  In the meantime, dvc pull foo perfectly works. Note that it suddenly stopped to work (with a previous dvc version before upgrading) with the following exception:

This seems like a problem related with our signed URL generation, which might be affected by forcing the signature version to `s3v4`.

**Comment by hugo-ricateau-tiime** [comment]
> which might be affected by forcing the signature version to `s3v4`.

@isidentical, how to try this?

**Comment by hugo-ricateau-tiime** [comment]
@isidentical, this is a critical bug on our side as it blocks our CI / CD pipeline; we would like avoiding an ugly workaround. Any idea on when this might be fixed? I've seen [this issue](https://github.com/iterative/dvc/issues/5555) that seems highly related and scheduled within the current sprint; is likely to be released on March 9?

**Comment by isidentical** [comment]
Possibly next week when we migrate to s3fs @hugo-ricateau-tiime it will be fully resolved. For now I am not exactly sure that this is because of that hardcoded constant though it seems like the most reasonable explanation considering nothing else changed on the signature generation that I am aware of. I'll create a PR for addressing that signature issue ASAP (as I said, might not be relevant). 

@hugo-ricateau-tiime can you also open that link (the one that you masked as `https://bucket-name.s3-eu-west-1.amazonaws.com/bucket-name/XX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX?AWSAccessKeyId=XXXXXXXXXXXXXXXXXXXX&Signature=XXXXXXXXXXXXXXXXXXXX%2FXXXXXX%3D&Expires=1614884948`) on your browser and send me the full XML (or crop if anything is private) so that I can see the error message.

**Comment by isidentical** [comment]
> (note the incoherent eu-west-1 and us-east-1 localisations present in the URL).

Does it work when you set the region though, like `dvc remote modify remote_name region eu-west-1`?

**Comment by hugo-ricateau-tiime** [comment]
> @hugo-ricateau-tiime can you also open that link (the one that you masked as `https://bucket-name.s3-eu-west-1.amazonaws.com/bucket-name/XX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX?AWSAccessKeyId=XXXXXXXXXXXXXXXXXXXX&Signature=XXXXXXXXXXXXXXXXXXXX%2FXXXXXX%3D&Expires=1614884948`) on your browser and send me the full XML (or crop if anything is private) so that I can see the error message.

Sure, seems to be a signature mismatch:
```xml
<Error>
  <Code>SignatureDoesNotMatch</Code>
  <Message>
    The request signature we calculated does not match the signature you provided. Check your key and signing method.
  </Message>
  <AWSAccessKeyId>XXXXXXXXXXXXXXXXXXXX</AWSAccessKeyId>
  <StringToSign>
    GET 1615231775 /bucket-name/bucket-name/XX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  </StringToSign>
  <SignatureProvided>XXXXXXXXXXXXXXXXXXXXXXXXXXXX</SignatureProvided>
  <StringToSignBytes>
    XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX
  </StringToSignBytes>
  <RequestId>XXXXXXXXXXXXXXXX</RequestId>
  <HostId>
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  </HostId>
</Error>
```

> Does it work when you set the region though, like dvc remote modify remote_name region eu-west-1?

Interestingly, the exception differs:
```python3
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
.../python3.6/site-packages/dvc/repo/__init__.py in open_by_relpath(self, path, remote, mode, encoding)
    480             with fs.open(
--> 481                 path, mode=mode, encoding=encoding, remote=remote,
    482             ) as fobj:

.../python3.6/contextlib.py in __enter__(self)
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:

.../python3.6/site-packages/dvc/utils/http.py in open_url(url, mode, encoding, **iter_opts)
     15
---> 16     with iter_url(url, **iter_opts) as (response, it):
     17         bytes_stream = IterStream(it)

.../python3.6/contextlib.py in __enter__(self)
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:

.../python3.6/site-packages/dvc/utils/http.py in iter_url(url, chunk_size)
     58
---> 59     response = request()
     60     it = gen(response)

.../python3.6/site-packages/dvc/utils/http.py in request(headers)
     34         if response.status_code == 404:
---> 35             raise FileNotFoundError(f"Can't open {the_url}")
     36         response.raise_for_status()

FileNotFoundError: Can't open https://bucket-name.s3-eu-west-1.amazonaws.com/bucket-name/XX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXXXXXXXXX%2FXXXXXXXX%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210305T184008Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

The above exception was the direct cause of the following exception:

FileMissingError                          Traceback (most recent call last)
<ipython-input-X-XXXXXXXXXXXX> in <module>
----> 1 with open('foo', mode='rb') as file:
      2     bar = file.read()
      3

.../python3.6/contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

.../python3.6/site-packages/dvc/api.py in _open(path, repo, rev, remote, mode, encoding)
     76     with Repo.open(repo, rev=rev, subrepos=True, uninitialized=True) as _repo:
     77         with _repo.open_by_relpath(
---> 78             path, remote=remote, mode=mode, encoding=encoding
     79         ) as fd:
     80             yield fd

.../python3.6/contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

.../python3.6/site-packages/dvc/repo/__init__.py in open_by_relpath(self, path, remote, mode, encoding)
    483                 yield fobj
    484         except FileNotFoundError as exc:
--> 485             raise FileMissingError(path) from exc
    486         except IsADirectoryError as exc:
    487             raise DvcIsADirectoryError(f"'{path}' is a directory") from exc

FileMissingError: Can't find 'foo' neither locally nor on remote
```

And even more interestingly, now `dvc pull --verbose foo` fails:
```shell
2021-03-08 19:45:28,551 DEBUG: Check for update is enabled.
2021-03-08 19:45:28,616 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-03-08 19:45:28,617 DEBUG: Spawned '['daemon', '-q', 'updater']'
2021-03-08 19:45:28,683 DEBUG: Checking if stage 'foo' is in 'dvc.yaml'
2021-03-08 19:45:30,547 DEBUG: Preparing to download data from 's3://bucket-name'
2021-03-08 19:45:30,548 DEBUG: Preparing to collect status from s3://bucket-name
2021-03-08 19:45:30,548 DEBUG: Collecting information from local cache...
2021-03-08 19:45:30,551 DEBUG: Collecting information from remote cache...
2021-03-08 19:45:30,552 DEBUG: Matched '0' indexed hashes
2021-03-08 19:45:30,552 DEBUG: Querying 1 hashes via object_exists
2021-03-08 19:45:31,017 ERROR: unexpected error - An error occurred (NoSuchKey) when calling the ListObjects operation: The specified key does not exist.
------------------------------------------------------------
Traceback (most recent call last):
  File ".../python3.6/site-packages/dvc/main.py", line 50, in main
    ret = cmd.run()
  File ".../python3.6/site-packages/dvc/command/data_sync.py", line 40, in run
    glob=self.args.glob,
  File ".../python3.6/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File ".../python3.6/site-packages/dvc/repo/pull.py", line 38, in pull
    run_cache=run_cache,
  File ".../python3.6/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File ".../python3.6/site-packages/dvc/repo/fetch.py", line 63, in fetch
    used, jobs, remote=remote, show_checksums=show_checksums,
  File ".../python3.6/site-packages/dvc/data_cloud.py", line 92, in pull
    show_checksums=show_checksums,
  File ".../python3.6/site-packages/dvc/remote/base.py", line 56, in wrapper
    return f(obj, *args, **kwargs)
  File ".../python3.6/site-packages/dvc/remote/base.py", line 491, in pull
    download=True,
  File ".../python3.6/site-packages/dvc/remote/base.py", line 328, in _process
    download=download,
  File ".../python3.6/site-packages/dvc/remote/base.py", line 176, in _status
    md5s, jobs=jobs, name=str(self.fs.path_info)
  File ".../python3.6/site-packages/dvc/remote/base.py", line 132, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File ".../python3.6/site-packages/dvc/objects/db/base.py", line 380, in hashes_exist
    remote_hashes = self.list_hashes_exists(hashes, jobs, name)
  File ".../python3.6/site-packages/dvc/objects/db/base.py", line 338, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File ".../python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File ".../python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File ".../python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File ".../python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File ".../python3.6/site-packages/dvc/objects/db/base.py", line 329, in exists_with_progress
    ret = self.fs.exists(path_info)
  File ".../python3.6/site-packages/dvc/fs/s3.py", line 231, in exists
    return self.isfile(path_info) or self.isdir(path_info)
  File ".../python3.6/site-packages/dvc/fs/s3.py", line 261, in isfile
    return path_info.path in self._list_paths(path_info)
  File ".../python3.6/site-packages/dvc/fs/s3.py", line 282, in _list_paths
    for obj_summary in obj_summaries:
  File ".../python3.6/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File ".../python3.6/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File ".../python3.6/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File ".../python3.6/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File ".../python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File ".../python3.6/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the ListObjects operation: The specified key does not exist.
------------------------------------------------------------
2021-03-08 19:45:31,636 DEBUG: Version info for developers:
DVC version: 2.0.3 (pip)
---------------------------------
Platform: Python 3.6.10 on Darwin-20.3.0-x86_64-i386-64bit
Supports: http, https, s3, ssh
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-03-08 19:45:31,639 DEBUG: Analytics is enabled.
2021-03-08 19:45:31,642 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/cs/gpn2tgnx6g5_89hg13ss77sh0000gp/T/tmpfjmabd8s']'
2021-03-08 19:45:31,643 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/cs/gpn2tgnx6g5_89hg13ss77sh0000gp/T/tmpfjmabd8s']'
```

**Comment by isidentical** [comment]
What do you mean by `Sure, seems to be a signature mismatch [this is with dvc==1.11.16]:`? Does `dvc==1.11.16` is also problematic?

**Comment by hugo-ricateau-tiime** [comment]
> What do you mean by `Sure, seems to be a signature mismatch [this is with dvc==1.11.16]:`? Does `dvc==1.11.16` is also problematic?

Yes, that is what makes me dubitative: it was perfectly working with `dvc==1.11.16` until it suddenly stopped to work (last thursday; with the `HTTPError: 403 Client Error: Forbidden for url: ...` exception); without any change in the environment concerning `dvc` or one of its requirements. Then, I upgraded `dvc` (as well as its requirements of course) in order to report with the latest version (which resulted in the `HTTPError: 400 Client Error: Bad Request for url: ...` exception). Note that nothing changed within `s3` / users configurations in the meantime.

I realise that my initial report was not that clear concerning this point; sorry about that.

**Comment by hugo-ricateau-tiime** [comment]
Note that with both versions, `dvc pull` works fine in the exact same environment that makes the `python` snippet failing.

**Comment by isidentical** [comment]
> Note that with both versions, dvc pull works fine in the exact same environment that makes the python snippet failing.

pull doesn't depend on pre-signed URLs, that's the expected case.

**Comment by isidentical** [comment]
> Note that with both versions, dvc pull works fine in the exact same environment that makes the python snippet failing.

That's really weird. Are you sure that none of the dependencies changed (like did you insta//upgrade any boto* related package, or something that might be depending on a newer version of boot)?

**Comment by hugo-ricateau-tiime** [comment]
Okay, so, I've spotted the issue I think:
- With `dvc==1.11.16`, re-running the exact same CI container that was working a few days ago, still works as expected. The problem appears on my local environment, where the only difference is the fact that the `.dvc/config` has an extra `endpointurl` key; removing it solved the issue.
- With `dvc==2.0.3`, the problem disappears when removing `endpointurl = ...` and adding `region = eu-west-1` within `.dvc/config`.

So, I think there was a combinations of two unrelated issues:
- `endpointurl = ...` probably stopped working a while ago (certainly due to an `boto_` upgrade); but was not caught until now as we use this key on our local environments only.
- The problem you initially identified with the static hard-coded region in url generation (fixed with `dvc remote modify <remote> region eu-west-1`).

I let you decide what to do with this issue.

**Comment by isidentical** [comment]
Hey @hugo-ricateau-tiime can you try to installl dvc from the master and give it a shot? `pip install "dvc[s3] @ git+https://github.com/iterative/dvc"`

**Comment by efiop** [comment]
Closing as stale. Please let us know if the issue is fixed for you or not. Thanks for the feedback.

**Comment by hugo-ricateau** [comment]
Hi @isidentical, sorry for the late answer. As of `dvc==2.5.4`, explicitly specifying `region = eu-west-1` in `.dvc/config` is no longer required in order to avoid the failure; so the issue can indeed be considered closed.
