### ISSUE TITLE
import-url: fails if neither of `ETag` nor `Content-MD5` headers are in response

### ISSUE THREAD

**Issue by deanmalmgren** [iterative/dvc#5560]
# Bug Report

## Description

As shared on [StackOverflow](https://stackoverflow.com/q/66505949/564709) and in [our Discord chat](https://discord.com/channels/485586884165107732/563406153334128681/817744903323910165), Running `dvc import-url` on a Google Sheets export url isn't working properly. Per @isidentical's comment, it appears to be an issue with situations where "the http response doesn't include an ETag or a Content-MD5 header."

### Reproduce

1. dvc init
2. Set up a Google spreadsheet to have public access
3. dvc import-url https://docs.google.com/spreadsheets/d/MY-GOOGLE-DOC-ID/export?exportFormat=csv data.csv

### Expected

Expected this to download the data into `data.csv` as specified

### Environment information

**Output of `dvc doctor`:**

```console
$ poetry run dvc doctor
DVC version: 2.0.1 (pip)
---------------------------------
Platform: Python 3.8.7 on macOS-10.15.7-x86_64-i386-64bit
Supports: gdrive, http, https
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5
Caches: local
Remotes: gdrive
Workspace directory: apfs on /dev/disk1s5
Repo: dvc, git
```

**Additional Information (if any):**

Here's the output from `dvc import-url -vv`:

```
$ dvc import-url -vv https://docs.google.com/spreadsheets/d/MY-GOOGLE-DOC-ID/export?exportFormat=csv data.csv
2021-03-06 07:11:06,264 TRACE: Namespace(cd='.', cmd='import-url', cprofile=False, cprofile_dump=None, desc=None, file=None, func=<class 'dvc.command.imp_url.CmdImportUrl'>, instrument=False, instrument_open=False, jobs=None, no_exec=False, out='data.csv', pdb=False, quiet=0, remote=None, to_remote=False, url='https://docs.google.com/spreadsheets/d/MY-GOOGLE-DOC-ID/export?exportFormat=csv', verbose=2, version=None)
2021-03-06 07:11:06,406 DEBUG: Check for update is enabled.
2021-03-06 07:11:06,795 DEBUG: Removing output 'data.csv' of stage: 'data.csv.dvc'.
2021-03-06 07:11:06,795 DEBUG: Removing 'data.csv'
Importing 'https://docs.google.com/spreadsheets/d/MY-GOOGLE-DOC-ID/export?exportFormat=csv' -> 'data.csv'
2021-03-06 07:11:06,797 DEBUG: Computed stage: 'data.csv.dvc' md5: 'e0e382ca354ea00ddbb7df054235a3a2'
2021-03-06 07:11:06,797 DEBUG: 'md5' of stage: 'data.csv.dvc' changed.
2021-03-06 07:11:09,400 ERROR: unexpected error - 'NoneType' object has no attribute 'endswith'
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/main.py", line 50, in main
    ret = cmd.run()
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/command/imp_url.py", line 14, in run
    self.repo.imp_url(
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/repo/scm_context.py", line 14, in run
    return method(repo, *args, **kw)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/repo/imp_url.py", line 81, in imp_url
    stage.run(jobs=jobs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/stage/__init__.py", line 506, in run
    sync_import(self, dry, force, jobs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/stage/imports.py", line 47, in sync_import
    stage.save_deps()
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/stage/__init__.py", line 444, in save_deps
    dep.save()
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/output/base.py", line 297, in save
    self.hash_info = self.get_hash()
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/output/base.py", line 196, in get_hash
    return get_hash(
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/objects/stage.py", line 130, in get_hash
    hash_info = get_file_hash(path_info, fs, name)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/objects/stage.py", line 15, in get_file_hash
    assert not info[name].endswith(".dir")
AttributeError: 'NoneType' object has no attribute 'endswith'
------------------------------------------------------------
2021-03-06 07:11:09,470 DEBUG: Version info for developers:
DVC version: 2.0.1 (pip)
---------------------------------
Platform: Python 3.8.7 on macOS-10.15.7-x86_64-i386-64bit
Supports: gdrive, http, https
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5
Caches: local
Remotes: gdrive
Workspace directory: apfs on /dev/disk1s5
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-03-06 07:11:09,473 DEBUG: Analytics is disabled.
```

**Comment by isidentical** [comment]
Just for the reference dvc < 2 used to raise an error when there is no etag/content-md5 header;
https://github.com/iterative/dvc/blob/55bf18d8f92832610c816f2bbe25f804bd2c1338/dvc/tree/http.py#L158-L162

but the new `.info()` method just returns even if it is empty;
https://github.com/iterative/dvc/blob/47bcb02ef1749d057889c643631a205cdbf004b9/dvc/fs/http.py#L151-L153

So we should either bring back the old guard and forbid this case, or maybe we could allow falling back to double-download + md5 hashing of content in the get_file_hash (less efficient, but at least gives a proper hash in this case instead of just not supporting the case at all);
https://github.com/iterative/dvc/blob/47bcb02ef1749d057889c643631a205cdbf004b9/dvc/objects/stage.py#L22-L27

The bad side about the latter is when considering directories (this won't be an HTTP specific case, so like in general) hash types might be different which would be a huge inconsistency. So I guess we would just put the old guard. 

@deanmalmgren one of the easiest ways is either creating that stage with dvc run curl bla bla, or just doing `dvc get-url ...` and then `dvc add` (if you don't want to track the dependency).

**Comment by efiop** [comment]
@dberenbaum That's just a bug though that we need to fix. Verbose log:

```
2022-07-05 19:45:57,647 ERROR: unexpected error - argument of type 'int' is not iterable
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/efiop/git/efiop/dvc/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/Users/efiop/git/efiop/dvc/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/Users/efiop/git/efiop/dvc/dvc/commands/imp_url.py", line 15, in run
    self.repo.imp_url(
  File "/Users/efiop/git/efiop/dvc/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/efiop/git/efiop/dvc/dvc/repo/scm_context.py", line 152, in run
    return method(repo, *args, **kw)
  File "/Users/efiop/git/efiop/dvc/dvc/repo/imp_url.py", line 83, in imp_url
    stage.run(jobs=jobs)
  File "/Users/efiop/.pyenv/versions/3.9.7/envs/dvc-py3.9.7/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/efiop/git/efiop/dvc/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/Users/efiop/.pyenv/versions/3.9.7/envs/dvc-py3.9.7/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/efiop/git/efiop/dvc/dvc/stage/__init__.py", line 535, in run
    self._sync_import(dry, force, jobs)
  File "/Users/efiop/.pyenv/versions/3.9.7/envs/dvc-py3.9.7/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/efiop/git/efiop/dvc/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/Users/efiop/.pyenv/versions/3.9.7/envs/dvc-py3.9.7/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/efiop/git/efiop/dvc/dvc/stage/__init__.py", line 559, in _sync_import
    sync_import(self, dry, force, jobs)
  File "/Users/efiop/git/efiop/dvc/dvc/stage/imports.py", line 46, in sync_import
    stage.save_deps()
  File "/Users/efiop/git/efiop/dvc/dvc/stage/__init__.py", line 470, in save_deps
    dep.save()
  File "/Users/efiop/git/efiop/dvc/dvc/output.py", line 552, in save
    _, self.meta, obj = ostage(
  File "/Users/efiop/git/efiop/dvc-data/src/dvc_data/stage.py", line 248, in stage
    meta, obj = _stage_file(
  File "/Users/efiop/git/efiop/dvc-data/src/dvc_data/stage.py", line 64, in _stage_file
    meta, hash_info = hash_file(path, fs, name, state=state)
  File "/Users/efiop/git/efiop/dvc-data/src/dvc_data/hashfile/hash.py", line 176, in hash_file
    assert ".dir" not in hash_info.value
TypeError: argument of type 'int' is not iterable
------------------------------------------------------------
```

The old message was there because our implementation was very limited compared to what we have now. Except for some edge cases, we should be able to download anything reasonably well. Let's get back to the message after we fix this bug.

**Comment by dberenbaum** [comment]
My concern was that it's currently p3 and https://github.com/iterative/dvc/issues/6163#issuecomment-1172915694 made it seem like it might not be that straightforward. Are we planning to prioritize fixing it?

**Comment by efiop** [comment]
@dberenbaum Yeah, I took a closer look along the way and will submit a fix shortly. Thank you!

**Comment by efiop** [comment]
Seems like the error we are getting is a bit different though. Could you post your verbose log, please? @dberenbaum

**Comment by dberenbaum** [comment]
Thanks @efiop! Here's the verbose log:

```bash
$ dvc import-url -v http://www.google.com google
2022-07-05 13:31:32,682 DEBUG: Removing output 'google' of stage: 'google.dvc'.
2022-07-05 13:31:32,682 DEBUG: Removing '/Users/dave/repo/google'
Importing 'http://www.google.com' -> 'google'
2022-07-05 13:31:32,682 DEBUG: Computed stage: 'google.dvc' md5: 'c9cfc7746ec272daa23ebabb3057c6ff'
2022-07-05 13:31:32,682 DEBUG: 'md5' of stage: 'google.dvc' changed.
2022-07-05 13:31:33,201 ERROR: unexpected error - argument of type 'int' is not iterable
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dave/Code/dvc/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/Users/dave/Code/dvc/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/Users/dave/Code/dvc/dvc/commands/imp_url.py", line 15, in run
    self.repo.imp_url(
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/scm_context.py", line 156, in run
    return method(repo, *args, **kw)
  File "/Users/dave/Code/dvc/dvc/repo/imp_url.py", line 83, in imp_url
    stage.run(jobs=jobs)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/dave/Code/dvc/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/dave/Code/dvc/dvc/stage/__init__.py", line 535, in run
    self._sync_import(dry, force, jobs)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/dave/Code/dvc/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/dave/Code/dvc/dvc/stage/__init__.py", line 559, in _sync_import
    sync_import(self, dry, force, jobs)
  File "/Users/dave/Code/dvc/dvc/stage/imports.py", line 42, in sync_import
    stage.save_deps()
  File "/Users/dave/Code/dvc/dvc/stage/__init__.py", line 470, in save_deps
    dep.save()
  File "/Users/dave/Code/dvc/dvc/output.py", line 552, in save
    _, self.meta, obj = ostage(
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_data/stage.py", line 248, in stage
    meta, obj = _stage_file(
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_data/stage.py", line 64, in _stage_file
    meta, hash_info = hash_file(path, fs, name, state=state)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_data/hashfile/hash.py", line 180, in hash_file
    assert ".dir" not in hash_info.value
TypeError: argument of type 'int' is not iterable
------------------------------------------------------------
2022-07-05 13:31:34,005 DEBUG: Version info for developers:
DVC version: 2.12.1.dev13+geed6a8483
---------------------------------
Platform: Python 3.10.2 on macOS-12.4-arm64-arm-64bit
Supports:
        azure (adlfs = 2022.4.0, knack = 0.9.0, azure-identity = 1.7.1),
        gdrive (pydrive2 = 1.10.1),
        gs (gcsfs = 2022.5.0),
        hdfs (fsspec = 2022.5.0, pyarrow = 7.0.0),
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.5),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.5),
        s3 (s3fs = 2022.5.0, boto3 = 1.21.21),
        ssh (sshfs = 2022.6.0),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.4),
        webdavs (webdav4 = 0.9.4)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: local
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

**Comment by dberenbaum** [comment]
Just to close the loop, I can confirm it works with `dvc-data==0.0.19`.
