### ISSUE TITLE
import: failed to authenticate to gdrive

### ISSUE THREAD

**Issue by deanmalmgren** [iterative/dvc#5561]
# Bug Report

## Description

I have a separate dvc project that is using gdrive remote storage and I am trying to import data from that project into my current project with:

```console
$ dvc import https://github.com/econudge/econudge-scraper data/out/mydata.jsonl -o data/in/mydata.jsonl
```

I go through the authentication steps with Google and receive a "Authentication successful." message before I get the following error:

```
ERROR: failed to import 'data/out/mydata.jsonl' from 'https://github.com/econudge/econudge-scraper'. - Failed to authenticate GDrive remote: name: drive  version: v2
```

From inspecting the verbose logs (see below), it appears that this is a misleading error message. It was clearly able to authenticate but was in fact a `googleapiclient.errors.UnknownApiNameOrVersion` problem. Perhaps something changed in the v2 rollout to cause this?

### Reproduce

1. Create a dvc project with gdrive as the remote and a file `mydata.jsonl`. dvc push this file to remote storage
2. In a separate dvc project, `dvc import` the `mydata.jsonl` from the first project

### Expected

Expected this data to download and be managed by dvc in my pipeline, but got an error (see verbose output below)

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.0.3 (pip)
---------------------------------
Platform: Python 3.8.7 on macOS-10.15.7-x86_64-i386-64bit
Supports: gdrive, http, https
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5
Caches: local
Remotes: gdrive
Workspace directory: apfs on /dev/disk1s5
Repo: dvc, git
```

**Additional Information (if any):**

Here is the output from my command:

```console
dvc import -vv https://github.com/econudge/econudge-scraper data/out/mydata.jsonl -o data/in/mydata.jsonl
2021-03-07 05:23:12,479 TRACE: Namespace(cd='.', cmd='import', cprofile=False, cprofile_dump=None, desc=None, file=None, func=<class 'dvc.command.imp.CmdImport'>, instrument=False, instrument_open=False, jobs=None, no_exec=False, out='data/in/mydata.jsonl', path='data/out/mydata.jsonl', pdb=False, quiet=0, rev=None, url='https://github.com/econudge/econudge-scraper', verbose=2, version=None)
2021-03-07 05:23:12,733 DEBUG: Check for update is enabled.
2021-03-07 05:23:12,822 TRACE: params.yaml does not exist, it won't be used in parametrization
2021-03-07 05:23:12,823 TRACE: Context during resolution of stage download_food_db:
{}
2021-03-07 05:23:13,179 DEBUG: Removing output 'data/in/mydata.jsonl' of stage: 'data/in/mydata.jsonl.dvc'.
2021-03-07 05:23:13,179 DEBUG: Removing 'data/in/mydata.jsonl'
Importing 'data/out/mydata.jsonl (https://github.com/econudge/econudge-scraper)' -> 'data/in/mydata.jsonl'
2021-03-07 05:23:13,181 DEBUG: Computed stage: 'data/in/mydata.jsonl.dvc' md5: 'f068d10d27ce04967227e490629f8b48'
2021-03-07 05:23:13,181 DEBUG: 'md5' of stage: 'data/in/mydata.jsonl.dvc' changed.
2021-03-07 05:23:13,182 DEBUG: Creating external repo https://github.com/econudge/econudge-scraper@None
2021-03-07 05:23:13,183 DEBUG: erepo: git clone 'https://github.com/econudge/econudge-scraper' to a temporary dir
2021-03-07 05:23:14,310 DEBUG: Checking if stage '/private/var/folders/tx/xb88fln971s3jzzzmw5f7_f80000gp/T/tmprr3nysykdvc-clone/data/out/mydata.jsonl' is in 'dvc.yaml'
2021-03-07 05:23:14,318 TRACE: params.yaml does not exist, it won't be used in parametrization
2021-03-07 05:23:14,324 TRACE: ../../../../private/var/folders/tx/xb88fln971s3jzzzmw5f7_f80000gp/T/tmprr3nysykdvc-clone/params.yaml does not exist, it won't be used in parametrization
2021-03-07 05:23:14,325 TRACE: Context during resolution of stage grubhub_menu_items:
{}
2021-03-07 05:23:14,327 TRACE: Context during resolution of stage epicurious_recipes:
{}
2021-03-07 05:23:14,343 DEBUG: Preparing to download data from 'gdrive://12gj6yGS3kgV6EnxoLAyiZ0aoOjglMo4f'
2021-03-07 05:23:14,343 DEBUG: Preparing to collect status from gdrive://12gj6yGS3kgV6EnxoLAyiZ0aoOjglMo4f
2021-03-07 05:23:14,344 DEBUG: Collecting information from local cache...
2021-03-07 05:23:14,345 DEBUG: Collecting information from remote cache...
2021-03-07 05:23:14,345 DEBUG: Matched '0' indexed hashes
2021-03-07 05:23:14,346 DEBUG: Querying 1 hashes via object_exists
2021-03-07 05:23:14,670 DEBUG: GDrive remote auth with config '{'client_config_backend': 'settings', 'client_config_file': 'client_secrets.json', 'save_credentials': True, 'oauth_scope': ['https://www.googleapis.com/auth/drive', 'https://www.googleapis.com/auth/drive.appdata'], 'save_credentials_file': '/private/var/folders/tx/xb88fln971s3jzzzmw5f7_f80000gp/T/tmprr3nysykdvc-clone/.dvc/tmp/gdrive-user-credentials.json', 'get_refresh_token': True, 'save_credentials_backend': 'file', 'client_config': {'client_id': '710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com', 'client_secret': 'a1Fz59uTpVNeG_VGuSKDLJXv', 'auth_uri': 'https://accounts.google.com/o/oauth2/auth', 'token_uri': 'https://oauth2.googleapis.com/token', 'revoke_uri': 'https://oauth2.googleapis.com/revoke', 'redirect_uri': ''}}'.
  0% Querying cache in gdrive://12gj6yGS3kgV6EnxoLAyiZ0aoOjglMo4f| |0/1 [00:00<?Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/auth?client_id=710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.appdata&access_type=offline&response_type=code&approval_prompt=force

Enter verification code: 4/1AY0e-g6Bv6QCChWFINFX3oTVsrAxZ6pFiCrGvfJPMJY3kyvZWXahz9Ucse8
Authentication successful.
2021-03-07 05:23:37,644 ERROR: failed to import 'data/out/mydata.jsonl' from 'https://github.com/econudge/econudge-scraper'. - Failed to authenticate GDrive remote: name: drive  version: v2
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/fs/gdrive.py", line 260, in _drive
    gauth.CommandLineAuth()
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/pydrive2/auth.py", line 135, in _decorated
    self.Auth(code)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/pydrive2/auth.py", line 599, in Auth
    self.Authorize()
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/pydrive2/auth.py", line 644, in Authorize
    self.service = build(
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/googleapiclient/discovery.py", line 273, in build
    content = _retrieve_discovery_doc(
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/googleapiclient/discovery.py", line 387, in _retrieve_discovery_doc
    raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
googleapiclient.errors.UnknownApiNameOrVersion: name: drive  version: v2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/command/imp.py", line 14, in run
    self.repo.imp(
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/repo/imp.py", line 6, in imp
    return self.imp_url(
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/repo/scm_context.py", line 14, in run
    return method(repo, *args, **kw)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/repo/imp_url.py", line 81, in imp_url
    stage.run(jobs=jobs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/stage/__init__.py", line 506, in run
    sync_import(self, dry, force, jobs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/stage/imports.py", line 48, in sync_import
    stage.deps[0].download(stage.outs[0], jobs=jobs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/dependency/repo.py", line 93, in download
    repo.fetch([path_info.fspath], jobs=jobs, recursive=True)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/repo/fetch.py", line 62, in fetch
    downloaded += self.cloud.pull(
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/data_cloud.py", line 88, in pull
    return remote.pull(
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/remote/base.py", line 56, in wrapper
    return f(obj, *args, **kwargs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/remote/base.py", line 486, in pull
    ret = self._process(
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/remote/base.py", line 323, in _process
    dir_status, file_status, dir_contents = self._status(
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/remote/base.py", line 175, in _status
    self.hashes_exist(
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/remote/base.py", line 132, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/objects/db/base.py", line 380, in hashes_exist
    remote_hashes = self.list_hashes_exists(hashes, jobs, name)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/objects/db/base.py", line 338, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/objects/db/base.py", line 329, in exists_with_progress
    ret = self.fs.exists(path_info)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/fs/gdrive.py", line 508, in exists
    self._get_item_id(path_info)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/fs/gdrive.py", line 499, in _get_item_id
    item_ids = self._path_to_item_ids(path_info.path, create, use_cache)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/fs/gdrive.py", line 482, in _path_to_item_ids
    item_ids = self._get_cached_item_ids(path, use_cache)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/fs/gdrive.py", line 478, in _get_cached_item_ids
    return self._ids_cache["dirs"].get(path, [])
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/funcy/objects.py", line 50, in __get__
    return prop.__get__(instance, type)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/fs/gdrive.py", line 290, in _ids_cache
    for item in self._gdrive_list(
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/fs/gdrive.py", line 425, in _gdrive_list
    param.update(self._list_params)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/fs/gdrive.py", line 308, in _list_params
    drive_id = self._gdrive_shared_drive_id(self._bucket)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/funcy/flow.py", line 125, in retry
    return call()
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/fs/gdrive.py", line 325, in _gdrive_shared_drive_id
    item = self._drive.CreateFile(param)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/funcy/objects.py", line 50, in __get__
    return prop.__get__(instance, type)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/Users/dmalmgren/Library/Caches/pypoetry/virtualenvs/econudge-calculator-YNe2YVhh-py3.8/lib/python3.8/site-packages/dvc/fs/gdrive.py", line 268, in _drive
    raise GDriveAuthError(self.credentials_location) from exc
dvc.fs.gdrive.GDriveAuthError: Failed to authenticate GDrive remote
------------------------------------------------------------
2021-03-07 05:23:37,654 DEBUG: Analytics is disabled.
```

**Comment by deanmalmgren** [comment]
UPDATE: there must have been a bug in one of the underlying client libraries a the following were updated on `poetry update`:

```
  • Updating protobuf (3.15.4 -> 3.15.5)
  • Updating google-auth (1.27.0 -> 1.27.1)
  • Updating google-api-core (1.26.0 -> 1.26.1)
  • Updating google-auth-httplib2 (0.0.4 -> 0.1.0)
  • Updating tqdm (4.58.0 -> 4.59.0)
  • Updating google-api-python-client (2.0.0 -> 2.0.2)
  • Updating pygments (2.8.0 -> 2.8.1)
  • Updating peewee (3.14.1 -> 3.14.2)
  • Updating rich (9.12.4 -> 9.13.0)
  • Updating ruamel.yaml (0.16.12 -> 0.16.13)
```

My best guess is [the update to google-api-core](https://github.com/googleapis/python-api-core/releases/tag/v1.26.1) fixed the problem. Closing for now.
