### ISSUE TITLE
dvc pull <filename> - TypeError: expected str, bytes or os.PathLike object, not tuple

### ISSUE THREAD

**Issue by BMarcin** [iterative/dvc#5574]
# Bug Report

## Description
When I try to pull a file from my remote (s3 compatible storage) I get the error: `TypeError: expected str, bytes or os.PathLike object, not tuple`. It occurs on the downloaded Deb package of DVC v2.0.1. I didn't have such an issue on DVC v 1.11.10.

### Reproduce
In my case, I tried to download file under path: ./models/model/model_step_100000.pt, so the command I've used was: `dvc pull ./models/model/model_step_100000.pt`. 

### Expected
I've expected DVC to download that file.

### Environment information
**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.0.1 (deb)
---------------------------------
Platform: Python 3.7.10 on Linux-4.19.104-microsoft-standard-x86_64-with-debian-buster-sid
Supports: All remotes
```

```console
$ dvc pull ./models/model/model_step_100000.pt --verbose
2021-03-09 10:20:03,887 DEBUG: Check for update is enabled.
2021-03-09 10:20:03,922 DEBUG: Checking if stage './models/model/model_step_100000.pt' is in 'dvc.yaml'
2021-03-09 10:20:05,134 DEBUG: Preparing to download data from 's3://dvc-data/dvc'
2021-03-09 10:20:05,134 DEBUG: Preparing to collect status from s3://dvc-data/dvc
2021-03-09 10:20:05,135 DEBUG: Collecting information from local cache...
2021-03-09 10:20:05,190 DEBUG: state save (8725724278153712, 1615217664258785536, 396) 62044d444077b4563837c4bf5f9c35d7.dir
2021-03-09 10:20:05,210 DEBUG: state save (18577348462990276, 1615279168759099904, 996316153) 3d95992f34ae6c96d77158a9549780ae
2021-03-09 10:20:05,219 DEBUG: Checking if stage './models/model/model_step_100000.pt' is in 'dvc.yaml'
2021-03-09 10:20:05,266 ERROR: unexpected error - expected str, bytes or os.PathLike object, not tuple
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/main.py", line 50, in main
  File "dvc/command/data_sync.py", line 40, in run
  File "dvc/repo/__init__.py", line 49, in wrapper
  File "dvc/repo/pull.py", line 44, in pull
  File "dvc/repo/__init__.py", line 49, in wrapper
  File "dvc/repo/checkout.py", line 104, in checkout
  File "dvc/repo/checkout.py", line 46, in get_all_files_numbers
  File "dvc/repo/checkout.py", line 46, in <genexpr>
  File "dvc/stage/__init__.py", line 613, in get_all_files_number
  File "dvc/stage/__init__.py", line 613, in <genexpr>
  File "dvc/output/base.py", line 479, in get_files_number
  File "site-packages/funcy/seqs.py", line 105, in ilen
  File "dvc/output/base.py", line 479, in <genexpr>
  File "pathlib.py", line 925, in __truediv__
  File "pathlib.py", line 704, in _make_child
  File "pathlib.py", line 658, in _parse_args
TypeError: expected str, bytes or os.PathLike object, not tuple
------------------------------------------------------------
2021-03-09 10:20:06,005 DEBUG: Version info for developers:
DVC version: 2.0.1 (deb)
---------------------------------
Platform: Python 3.7.10 on Linux-4.19.104-microsoft-standard-x86_64-with-debian-buster-sid
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: 9p on C:\
Caches: local
Remotes: webdav, s3
Workspace directory: 9p on C:\
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-03-09 10:20:06,012 DEBUG: Analytics is enabled.
2021-03-09 10:20:06,119 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpxrep7ft1']'
2021-03-09 10:20:06,121 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpxrep7ft1']'
```

**Train stage from my dvc.yaml file**
```yaml
train:
  cmd: ./src/train_eval/train.sh
  deps:
    - src/train_eval/train.sh
    - data/preprocessing/source_train
    - data/preprocessing/source_test
    - data/preprocessing/target_train
    - data/preprocessing/target_test
    - models/model.sp
  params:
    - Training.batch_size
  outs:
    - ./models/model
```

I get this error in WSL and in docker ubuntu container.

**Comment by BMarcin** [comment]
The same issue I've encountered on DVC v2.0.3.

**Comment by efiop** [comment]
Thanks for reporting the bug! :pray: Closing in favor of #5577 . Stay tuned for the fix.
