### ISSUE TITLE
Pull / Push Failed for azure remote storage - Authentification issue with DVC 2.0.X 

### ISSUE THREAD

**Issue by rbreunev** [iterative/dvc#5589]
# Bug Report

## Pull / Push Failed for azure remote storage - Authentification issue with DVC 2.0.X 

When using classical commands (push, pul....) with azure remote storage there is the following error : 

**ERROR: failed to pull data from the cloud - Authentication to Azure Blob Storage via connection string failed.**

### Prerequisite : 

dvc init on git repo and  several azure remote storage configured using : 

```
dvc remote add myremote1 "azure://<CONTAINER_NAME>/DVC"
dvc remote modify myremote1  connection_string  "BlobEndpoint=<URL_STORAGE;SharedAccessSignature=<SAS_KEY>" 

```
Repo already contained tracked data (.dvc files already there). 

### Reproduce

1. git pull
2. dvc pull -r myremote1

### Expected

```console
+-------------------------------------------+
|                                           |
|     Update available 1.11.16 -> 2.0.1     |
|      Run `pip install dvc --upgrade`      |
|                                           |
+-------------------------------------------+

A       data/models-3/                                                                                                                       
A       data/training-set/                                                                                                                 
A       data/models/                                                                                                                       
A       data/dvc-training-set/                                                                                                             
4 files added and 174 files fetched 
```

### Environment information

```console
DVC version: 2.0.3 (pip)
---------------------------------
Platform: Python 3.8.5 on Linux-5.4.0-1039-azure-x86_64-with-glibc2.29
Supports: azure, http, https
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: azure, azure, azure
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
```

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

```console
DVC version: 2.0.3 (pip)
---------------------------------
Platform: Python 3.8.5 on Linux-5.4.0-1039-azure-x86_64-with-glibc2.29
Supports: azure, http, https
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: azure, azure, azure
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
```

**Additional Information (if any):**

When installing previous version (1.11.16) it works.

**Comment by rbreunev** [comment]
Ok just update to 2.0.5 and seems to solve the issue. I am waiting to have confirmation of all my users to close the bug.

**Comment by isidentical** [comment]
@rbreunev any updates?

**Comment by rbreunev** [comment]
Hello, 

Thanks for the reminder. 

Unfortunately version 2.0.5 is not solving the issue. v 2.0.12 (latest) neither. See below. 

```
rootuser:~/packages/mypackage$ dvc version
DVC version: 2.0.5 (pip)
---------------------------------
Platform: Python 3.8.5 on Linux-5.4.0-1039-azure-x86_64-with-glibc2.29
Supports: azure, http, https
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
rootuser:~/packages/mypackage$ dvc pull
Everything is up to date.                                                                                                                                                  
ERROR: failed to pull data from the cloud - Authentication to Azure Blob Storage via connection string failed.
Learn more about configuration settings at <https://man.dvc.org/remote/modify>: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:6b9c0705-f01e-002c-2f87-240a28000000
Time:2021-03-29T10:34:46.1717624Z
ErrorCode:AuthenticationFailed
Error:None
AuthenticationErrorDetail:The specified signed resource is not allowed for the this resource level

rootuser:~/packages/mypackage$ dvc version
DVC version: 2.0.12 (pip)
---------------------------------
Platform: Python 3.8.5 on Linux-5.4.0-1039-azure-x86_64-with-glibc2.29
Supports: azure, http, https
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
rootuser:~/packages/mypackage$ dvc pull
Everything is up to date.                                                                                                                                                  
ERROR: failed to pull data from the cloud - Authentication to Azure Blob Storage via connection string failed.
Learn more about configuration settings at <https://man.dvc.org/remote/modify>: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:4d153fd4-501e-0025-1f87-244ffb000000
Time:2021-03-29T10:36:43.9433592Z
ErrorCode:AuthenticationFailed
Error:None
AuthenticationErrorDetail:The specified signed resource is not allowed for the this resource level
```

Interesting fact : rolling back to version 1.11.16 (with `pip3 uninstall dvc` and then `pip3 install dvc==1.11.16`) and then reinstalling latest dvc version (again `pip3 uninstall dvc` and `pip3 install dvc`) do the trick. 

For now my team and I run with 1.11.16

**Comment by isidentical** [comment]
Can you run pip freeze and post the result here (in the working environment with dvcv2 and in the broken environment with dvcv2). It seems like a problem regarding with one of our dependencies

**Comment by rbreunev** [comment]
For sure. See attached files : 
[python_deps_dvc_working_env.txt](https://github.com/iterative/dvc/files/6223045/python_deps_dvc_working_env.txt)
[python_deps_dvc_bugged_env.txt](https://github.com/iterative/dvc/files/6223046/python_deps_dvc_bugged_env.txt)

**Comment by isidentical** [comment]
It is really weird that there aren't any differences on azure related packages;
```
 $ diff python_deps_dvc_bugged_env.txt python_deps_dvc_working_env.txt 
27c27
< docker==4.4.4
---
> docker==4.4.2
29,30c29,30
< dulwich==0.20.21
< dvc==2.0.13
---
> dulwich==0.20.20
> dvc==2.0.12
53c53
< networkx==2.5
---
> networkx==2.4
58d57
< pandas==1.2.3
83d81
< pytz==2021.1
88c86
< rich==9.12.0
---
> rich==9.11.1
92c90
< shtab==1.3.5
---
> shtab==1.3.4
99c97
< tqdm==4.58.0
---
> tqdm==4.57.0
```

How did you generate your SAS token? Can you also check https://github.com/Azure/azure-storage-azcopy/issues/1292 this issue and verify that your token is generated properly and have access (unlike the one on the issue)

**Comment by jpvlerbe** [comment]
I can confirm the same issue
With v1.11.9 I was able to use Azure storage with a connection_string formatted like this:
`DefaultEndpointsProtocol=https;BlobEndpoint=https://<accountname>.blob.core.windows.net;Accountname=<accountname>;SharedAccessSignature=sv=...rest_of_SAS_token`

while after upgrading to version 2.0.17 I get the error
`AuthenticationErrorDetail:The specified signed resource is not allowed for the this resource level`

Does a different type of connection_string needs to be used. I am confused with what is in #5511

**Comment by jpvlerbe** [comment]
I think I have figured it out. So in Azure Blob Storage you have the Account and in that account you create containers. SAS tokens can be limited to containers.

In configuring azure in dvc I have done (as per the documentation)
`dvc remote add -d myremote azure://mycontainer/path
dvc remote modify --local myremote connection_string 'mystring'`

Checking the code and testing in an interactive python session I can replicate the error when doing:
`from adlfs import AzureBlobFileSystem
fs = AzureBlobFileSystem(connection_string=mystring)
fs.ls("/")`
At this point no reference has been made to the container and I think it tries to list all containers. Which I indeed have no access to.

When I replace the last line with `fs.ls("<mycontainer>")` it succesfully lists the content of that container.
So the issue is in line 116 of dvc/fs/azure.py

**Comment by isidentical** [comment]
Thanks for triaging the error @jpvlerbe, it makes sense for that line to violate container-level priviliged tokens. I think it is going to better for us to just do a try/except to check the container's existence rather than listing all containers and checking whether if the name is present in that list or not. If you'd like to submit a pull request, would be amazing! (instead of the if condition there, a try except that calls `fs.info(bucket_name)` and if it fails with `FileNotFoundError` executes the `mkdir()`)

**Comment by jpvlerbe** [comment]
Well that would be my first pull request then. Let me give that a try in the morning!

**Comment by jpvlerbe** [comment]
I am having all sorts of issues when creating the fix.
So `bucket_name` is only the container name.

`fs.info()` from adlfs actually uses `ls` on the parent in the background. So it tries to list all containers again.
`fs.isdir()` same story.

however
`fs.isdir(self.bucket +"/"+ self.path_info.name)` did work for me. `isdir` does ls on the container and so that worked. Funny enough if afterwards you try `fs.isdir(self.bucket)` it does work. I guess in the background the full path is cached and that is used to deduct that this subpath will also exist.

So it tought of using that but then trying some scenarios
`mkdir` first checks if the container exist, trying to list all containers again...which of course fails again and brings us back to the original error.
I would expect that to create the folders in the hash-structure mkdir is also used, so we would run into the same issue after that.

**Comment by isidentical** [comment]
It appears to be that, we first need to fix this on upstream adlfs. `mkdir()` shouldn't list all containers (at least there should be a way of preventing it to do so).

**Comment by isidentical** [comment]
@jpvlerbe can you convert your patch to use `exists()` instead of `info()` and try it with an adlfs installed from the master `pip install git+https://github.com/dask/adlfs.git`. If it is working then, you can submit the PR and when we bump our adlfs version we'll merge your PR too!

**Comment by jpvlerbe** [comment]
It took some time for me to get back to it.

I am actually suffering from an error in the exists() callstack of adlfs now. `exists(container_name)` still fails with my specific set of permissions on `get_container_properties()` [](https://github.com/dask/adlfs/blob/3874b3e536fe6b24c824ee096566c8620b623dfa/adlfs/spec.py#L1046)
FYI: I have Read, add, create, write, delete, list, move, execute permissions described as "racwlme" in the SAS token.
The `get_container_properties` function throws "httpResponseError: This request is not authorized to perform this operation". However if I try `exists` with a non-existing container (or one I do not have access to) it actually throws a different error "ClientAuthenticationError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature"

`exists(self.bucket +"/"+ self.path_info.name)` worked for me (I am putting the dvc repo in a subfolder in the container). However in case the subfolder does not exists the call to `mkdir` fails on the same issue _container_exists() function.
However every call to `put_file` to upload files however deeply nested in non-existing subdirs works without issues.
So:
as long as the dvc repo is not in the root of the container but in a subfolder
I think a fix with a warning and a pass instead of mkdir might work in most of those cases.

**Comment by jpvlerbe** [comment]
Created my own container and was that way able to try a SAS token with full set of privileges (also ownership and permissions) limited to that container and still failed at the `get_container_properties`.

I will open an issue at adlfs again.

**Comment by isidentical** [comment]
> Created my own container and was that way able to try a SAS token with full set of privileges (also ownership and permissions) limited to that container and still failed at the get_container_properties.

Can you also post the traceback? (which exact line it fails with the error)

**Comment by jpvlerbe** [comment]
This is a stacktrace from a interactive python sesson running fs.exists()
`a.exists("dvc")
Traceback (most recent call last):
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/azure/storage/blob/aio/_container_client_async.py", line 331, in get_container_properties
    **kwargs)
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/azure/storage/blob/_generated/aio/operations_async/_container_operations_async.py", line 195, in get_properties
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'This request is not authorized to perform this operation.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/adlfs/spec.py", line 1243, in exists
    return sync(self.loop, self._exists, path)
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/fsspec/asyn.py", line 53, in sync
    raise result[0]
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/fsspec/asyn.py", line 20, in _runner
    result[0] = await coro
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/adlfs/spec.py", line 1259, in _exists
    return await self._container_exists(container_name)
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/adlfs/spec.py", line 1046, in _container_exists
    await client.get_container_properties()
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/azure/core/tracing/decorator_async.py", line 74, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/azure/storage/blob/aio/_container_client_async.py", line 333, in get_container_properties
    process_storage_error(error)
  File "/home/slm/Desktop/dvc_demo/venv/lib/python3.6/site-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation.
RequestId:94e1a562-201e-0035-677e-30f9a5000000
Time:2021-04-13T16:01:22.6663870Z
ErrorCode:AuthorizationFailure
Error:None
`

**Comment by jpvlerbe** [comment]
I have opened an issue here: [](https://github.com/Azure/azure-sdk-for-python/issues/18012#issue-857151255)

**Comment by isidentical** [comment]
This is an upstream bug on the `azure-sdk-for-python`, which is being stale at the moment (2 months without any response from the MSFT team). The temporary solution might be just using a token with extended privileges. I'm subscribed to the upstream issue, but for now there isn't much we can do about this, so closing it.

**Comment by efiop** [comment]
@andriihomiak Please share full verbose log and `dvc doctor` output.

**Comment by andriihomiak** [comment]
```
$ dvc push -v
2022-07-06 16:51:30,440 DEBUG: Preparing to transfer data from '/home/andrii/projects/my-dvc-repo/.dvc/cache' to 'neuro-pl-e5ed7d5443-andriikhomiak-dvc-backend56d6b764d92f'
2022-07-06 16:51:30,440 DEBUG: Preparing to collect status from 'neuro-pl-e5ed7d5443-andriikhomiak-dvc-backend56d6b764d92f'
2022-07-06 16:51:30,440 DEBUG: Collecting status from 'neuro-pl-e5ed7d5443-andriikhomiak-dvc-backend56d6b764d92f'
2022-07-06 16:51:30,441 DEBUG: Querying 1 oids via object_exists
2022-07-06 16:51:32,098 DEBUG: 'neuro-pl-e5ed7d5443-andriikhomiak-dvc-backend56d6b764d92f/00' doesn't look like a cache file, skipping
2022-07-06 16:51:32,098 DEBUG: Estimated remote size: 4096 files
2022-07-06 16:51:32,098 DEBUG: Querying '7' oids via traverse
2022-07-06 16:51:32,605 ERROR: unexpected error - Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:4e7ce89f-401e-0056-563f-91544a000000
Time:2022-07-06T13:51:32.5438921Z
ErrorCode:AuthenticationFailed
Error:None
AuthenticationErrorDetail:The specified signed resource is not allowed for the this resource level
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:4e7ce89f-401e-0056-563f-91544a000000
Time:2022-07-06T13:51:32.5438921Z</Message><AuthenticationErrorDetail>The specified signed resource is not allowed for the this resource level</AuthenticationErrorDetail></Error>
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/azure/storage/blob/aio/_models.py", line 53, in _get_next_cb
    return await self._command(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/azure/storage/blob/_generated/aio/operations_async/_service_operations_async.py", line 336, in list_containers_segment
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:4e7ce89f-401e-0056-563f-91544a000000
Time:2022-07-06T13:51:32.5438921Z</Message><AuthenticationErrorDetail>The specified signed resource is not allowed for the this resource level</AuthenticationErrorDetail></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc/commands/data_sync.py", line 58, in run
    processed_files_count = self.repo.push(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc/repo/push.py", line 68, in push
    pushed += self.cloud.push(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc/data_cloud.py", line 109, in push
    return self.transfer(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc/data_cloud.py", line 88, in transfer
    return transfer(src_odb, dest_odb, objs, **kwargs)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_data/transfer.py", line 158, in transfer
    status = compare_status(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_data/status.py", line 179, in compare_status
    dest_exists, dest_missing = status(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_data/status.py", line 151, in status
    odb.oids_exist(hashes, jobs=jobs, progress=pbar.callback)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 361, in oids_exist
    return list(oids & set(wrap_iter(remote_oids, callback)))
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 26, in wrap_iter
    for index, item in enumerate(iterable, start=1):
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 244, in _list_oids_traverse
    yield from itertools.chain.from_iterable(in_remote)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 147, in _list_oids
    for path in self._list_paths(prefix):
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 131, in _list_paths
    yield from self.fs.find(self.fs.path.join(*parts), prefix=bool(prefix))
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/fs/base.py", line 562, in find
    files = self.fs.find(with_prefix, prefix=self.path.parts(path)[-1])
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/adlfs/spec.py", line 964, in find
    return sync(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/fsspec/asyn.py", line 66, in sync
    raise return_result
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/fsspec/asyn.py", line 26, in _runner
    result[0] = await coro
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/adlfs/spec.py", line 1020, in _find
    file = await self._info(full_path)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/adlfs/spec.py", line 648, in _info
    out = await self._ls(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/adlfs/spec.py", line 812, in _ls
    containers = [c async for c in contents]
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/adlfs/spec.py", line 812, in <listcomp>
    containers = [c async for c in contents]
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/azure/core/async_paging.py", line 154, in __anext__
    return await self.__anext__()
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/azure/core/async_paging.py", line 157, in __anext__
    self._page = await self._page_iterator.__anext__()
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/azure/core/async_paging.py", line 99, in __anext__
    self._response = await self._get_next(self.continuation_token)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/azure/storage/blob/aio/_models.py", line 59, in _get_next_cb
    process_storage_error(error)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.ClientAuthenticationError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:4e7ce89f-401e-0056-563f-91544a000000
Time:2022-07-06T13:51:32.5438921Z
ErrorCode:AuthenticationFailed
Error:None
AuthenticationErrorDetail:The specified signed resource is not allowed for the this resource level
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:4e7ce89f-401e-0056-563f-91544a000000
Time:2022-07-06T13:51:32.5438921Z</Message><AuthenticationErrorDetail>The specified signed resource is not allowed for the this resource level</AuthenticationErrorDetail></Error>
------------------------------------------------------------
2022-07-06 16:51:32,695 DEBUG: [Errno 95] no more link types left to try out: [Errno 95] Operation not supported
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/azure/storage/blob/aio/_models.py", line 53, in _get_next_cb
    return await self._command(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/azure/storage/blob/_generated/aio/operations_async/_service_operations_async.py", line 336, in list_containers_segment
    raise models.StorageErrorException(response, self._deserialize)
azure.storage.blob._generated.models._models_py3.StorageErrorException: Operation returned an invalid status 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:4e7ce89f-401e-0056-563f-91544a000000
Time:2022-07-06T13:51:32.5438921Z</Message><AuthenticationErrorDetail>The specified signed resource is not allowed for the this resource level</AuthenticationErrorDetail></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc/commands/data_sync.py", line 58, in run
    processed_files_count = self.repo.push(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc/repo/push.py", line 68, in push
    pushed += self.cloud.push(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc/data_cloud.py", line 109, in push
    return self.transfer(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc/data_cloud.py", line 88, in transfer
    return transfer(src_odb, dest_odb, objs, **kwargs)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_data/transfer.py", line 158, in transfer
    status = compare_status(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_data/status.py", line 179, in compare_status
    dest_exists, dest_missing = status(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_data/status.py", line 151, in status
    odb.oids_exist(hashes, jobs=jobs, progress=pbar.callback)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 361, in oids_exist
    return list(oids & set(wrap_iter(remote_oids, callback)))
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 26, in wrap_iter
    for index, item in enumerate(iterable, start=1):
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 244, in _list_oids_traverse
    yield from itertools.chain.from_iterable(in_remote)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 147, in _list_oids
    for path in self._list_paths(prefix):
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 131, in _list_paths
    yield from self.fs.find(self.fs.path.join(*parts), prefix=bool(prefix))
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/fs/base.py", line 562, in find
    files = self.fs.find(with_prefix, prefix=self.path.parts(path)[-1])
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/adlfs/spec.py", line 964, in find
    return sync(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/fsspec/asyn.py", line 66, in sync
    raise return_result
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/fsspec/asyn.py", line 26, in _runner
    result[0] = await coro
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/adlfs/spec.py", line 1020, in _find
    file = await self._info(full_path)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/adlfs/spec.py", line 648, in _info
    out = await self._ls(
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/adlfs/spec.py", line 812, in _ls
    containers = [c async for c in contents]
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/adlfs/spec.py", line 812, in <listcomp>
    containers = [c async for c in contents]
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/azure/core/async_paging.py", line 154, in __anext__
    return await self.__anext__()
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/azure/core/async_paging.py", line 157, in __anext__
    self._page = await self._page_iterator.__anext__()
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/azure/core/async_paging.py", line 99, in __anext__
    self._response = await self._get_next(self.continuation_token)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/azure/storage/blob/aio/_models.py", line 59, in _get_next_cb
    process_storage_error(error)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.ClientAuthenticationError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:4e7ce89f-401e-0056-563f-91544a000000
Time:2022-07-06T13:51:32.5438921Z
ErrorCode:AuthenticationFailed
Error:None
AuthenticationErrorDetail:The specified signed resource is not allowed for the this resource level
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:4e7ce89f-401e-0056-563f-91544a000000
Time:2022-07-06T13:51:32.5438921Z</Message><AuthenticationErrorDetail>The specified signed resource is not allowed for the this resource level</AuthenticationErrorDetail></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/fs/generic.py", line 68, in _try_links
    return _link(link, from_fs, from_path, to_fs, to_path)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/fs/generic.py", line 28, in _link
    func(from_path, to_path)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/fs/base.py", line 288, in reflink
    return self.fs.reflink(from_info, to_info)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/fs/implementations/local.py", line 157, in reflink
    return system.reflink(path1, path2)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/fs/system.py", line 105, in reflink
    _reflink_linux(source, link_name)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/fs/system.py", line 91, in _reflink_linux
    fcntl.ioctl(d.fileno(), FICLONE, s.fileno())
OSError: [Errno 95] Operation not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/fs/generic.py", line 127, in _test_link
    _try_links([link], from_fs, from_file, to_fs, to_file)
  File "/home/andrii/projects/my-dvc-repo/venv/lib/python3.9/site-packages/dvc_objects/fs/generic.py", line 76, in _try_links
    raise OSError(
OSError: [Errno 95] no more link types left to try out
------------------------------------------------------------
2022-07-06 16:51:32,697 DEBUG: Removing '/home/andrii/projects/.gbg5NdWsDrBS4nNE7NxdzM.tmp'
2022-07-06 16:51:32,697 DEBUG: Removing '/home/andrii/projects/.gbg5NdWsDrBS4nNE7NxdzM.tmp'
2022-07-06 16:51:32,697 DEBUG: Removing '/home/andrii/projects/.gbg5NdWsDrBS4nNE7NxdzM.tmp'
2022-07-06 16:51:32,697 DEBUG: Removing '/home/andrii/projects/my-dvc-repo/.dvc/cache/.U7KsVsB2o96GnP4fAKMgnJ.tmp'
2022-07-06 16:51:32,705 DEBUG: Version info for developers:
DVC version: 2.12.1 (pip)
---------------------------------
Platform: Python 3.9.7 on Linux-5.17.9-051709-generic-x86_64-with-glibc2.31
Supports:
	azure (adlfs = 2022.4.0, knack = 0.9.0, azure-identity = 1.10.0),
	hdfs (fsspec = 2022.5.0, pyarrow = 8.0.0),
	webhdfs (fsspec = 2022.5.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.5.1),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.5.1)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p6
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/nvme0n1p6
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-07-06 16:51:32,706 DEBUG: Analytics is enabled.
2022-07-06 16:51:32,751 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpcczhg1qy']'
2022-07-06 16:51:32,753 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpcczhg1qy']'
```
```
$ dvc doctor
DVC version: 2.12.1 (pip)
---------------------------------
Platform: Python 3.9.7 on Linux-5.17.9-051709-generic-x86_64-with-glibc2.31
Supports:
        azure (adlfs = 2022.4.0, knack = 0.9.0, azure-identity = 1.10.0),
        hdfs (fsspec = 2022.5.0, pyarrow = 8.0.0),
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.5.1),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.5.1)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p6
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/nvme0n1p6
Repo: dvc, git
```

**Comment by andriihomiak** [comment]
Turns out, i was using root of the azure container with container-level credentials. Adding a subpath like `azure://<container>/<subpath>` in `.dvc/config` seems to have solved the issue.
