### ISSUE TITLE
push: fails for second push on shared Google folder

### ISSUE THREAD

**Issue by hunse** [iterative/dvc#5630]
# Bug Report

## Issue name

`push: fails for second push on shared Google folder`

## Description

I'm trying to use dvc with Google Drive, specifically with a folder that is shared with me in someone else's drive. (Note that I do not have access to the whole drive, just this specific folder.)

I've got it set up, and was able to add a first data file with `dvc add` and then do a `dvc push` to successfully push it to the drive (it shows up in the folder I've created there). However, when I tried to add a second file, I get the following
```
Enter verification code: ***
Authentication successful.
ERROR: unexpected error - <HttpError 403 when requesting https://www.googleapis.com/drive/v2/files?q=*** returned "The attempted action requires shared drive membership.". Details: "The attempted action requires shared drive membership.">
```

If I follow the URL (which I've shortened with *** above, but is actually quite long, see the "additional information" for the full URL), it shows me the following:
```
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
```

Furthermore, if I create a new project, I'm able to add the first file and dvc push it fine, but when I do the second one I get the same message.

I've followed the instructions [here](https://dvc.org/doc/user-guide/setup-google-drive-remote#using-a-custom-google-cloud-project-recommended) to use a custom google cloud project; unfortunately, that hasn't helped.

I do not think I've done enough with the drive that I should exceed any limits, particularly because I'm also trying with a Google Cloud project (which I understand often gets around these issues). I also do not think that anybody else using the drive has exceeded any limits. I also encountered this problem on Friday, so limits would have to have been exceeded both days, which seems unlikely.

I asked about this on Discord, and @jorgeorpinel suggested it might be a bug and I should file a report.

### Reproduce

1. dvc init
2. dvc add anyfile
3. dvc remote add -d gdrive-remote gdrive://<sha1>  # <sha1> is replaced with the SHA hash for the folder
4. dvc push
5. dvc add secondfile
6. dvc push  # this is when the error happens

Note that this just happens when I use a shared folder. It does not happen with my personal drive. Also note that I do not have access to the entire shared drive, only to a specific folder; the folder indicated by `<sha1>` is a subfolder within this specific folder.

### Expected

It should work.

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.0.5 (pip)
---------------------------------
Platform: Python 3.8.0 on Linux-4.15.0-135-generic-x86_64-with-glibc2.27
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb1
Caches: local
Remotes: gdrive
Workspace directory: ext4 on /dev/sdb1
Repo: dvc, git
```

**Additional Information (if any):**

Full output from the failing `dvc push --verbose``
```
(full38) user@user-lappy2:~/workspace/testproject$ dvc push --verbose
2021-03-15 16:15:04,339 DEBUG: Check for update is enabled.
2021-03-15 16:15:04,448 DEBUG: Preparing to upload data to 'gdrive://<sha1>'
2021-03-15 16:15:04,448 DEBUG: Preparing to collect status from gdrive://<sha1>
2021-03-15 16:15:04,448 DEBUG: Collecting information from local cache...
2021-03-15 16:15:04,449 DEBUG: Collecting information from remote cache...
2021-03-15 16:15:04,449 DEBUG: Querying 1 hashes via object_exists
2021-03-15 16:15:04,732 DEBUG: GDrive remote auth with config '{'client_config_backend': 'settings', 'client_config_file': 'client_secrets.json', 'save_credentials': True, 'oauth_scope': ['https://www.googleapis.com/auth/drive', 'https://www.googleapis.com/auth/drive.appdata'], 'save_credentials_backend': 'file', 'save_credentials_file': '/data/user/workspace/testproject/.dvc/tmp/gdrive-user-credentials.json', 'get_refresh_token': True, 'client_config': {'client_id': '<client_id>', 'client_secret': '<client_secret>', 'auth_uri': 'https://accounts.google.com/o/oauth2/auth', 'token_uri': 'https://oauth2.googleapis.com/token', 'revoke_uri': 'https://oauth2.googleapis.com/revoke', 'redirect_uri': ''}}'.
2021-03-15 16:15:05,036 DEBUG: GDrive remote 'gdrive://<sha1>' is using shared drive id '<sha2>'.
2021-03-15 16:15:05,485 DEBUG: Matched '0' indexed hashes
2021-03-15 16:15:05,485 DEBUG: Estimated remote size: 256 files
2021-03-15 16:15:05,486 DEBUG: Querying '8' hashes via traverse
2021-03-15 16:15:05,761 ERROR: unexpected error - <HttpError 403 when requesting https://www.googleapis.com/drive/v2/files?q=%28%27<sha1>%27+in+parents+or+%27<sha3>%27+in+parents+or+%27<sha4>%27+in+parents%29+and+trashed%3Dfalse&maxResults=1000&corpora=drive&driveId=<sha2>&supportsAllDrives=true&includeItemsFromAllDrives=true&alt=json returned "The attempted action requires shared drive membership.". Details: "The attempted action requires shared drive membership.">
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/venv/full38/lib/python3.8/site-packages/pydrive2/files.py", line 85, in _GetList
    self.auth.service.files()
  File "/home/user/venv/full38/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/user/venv/full38/lib/python3.8/site-packages/googleapiclient/http.py", line 920, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v2/files?q=%28%27<sha1>%27+in+parents+or+%27<sha3>%27+in+parents+or+%27<sha4>%27+in+parents%29+and+trashed%3Dfalse&maxResults=1000&corpora=drive&driveId=<sha2>&supportsAllDrives=true&includeItemsFromAllDrives=true&alt=json returned "The attempted action requires shared drive membership.". Details: "The attempted action requires shared drive membership.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/main.py", line 50, in main
    ret = cmd.run()
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/command/data_sync.py", line 56, in run
    processed_files_count = self.repo.push(
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/repo/push.py", line 41, in push
    return len(used_run_cache) + self.cloud.push(used, jobs, remote=remote)
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/data_cloud.py", line 66, in push
    return remote.push(
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/remote/base.py", line 56, in wrapper
    return f(obj, *args, **kwargs)
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/remote/base.py", line 466, in push
    ret = self._process(
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/remote/base.py", line 323, in _process
    dir_status, file_status, dir_contents = self._status(
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/remote/base.py", line 175, in _status
    self.hashes_exist(
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/remote/base.py", line 132, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/objects/db/base.py", line 409, in hashes_exist
    remote_hashes = set(
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/objects/db/base.py", line 269, in list_hashes_traverse
    yield from itertools.chain.from_iterable(in_remote)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/objects/db/base.py", line 259, in list_with_update
    return list(
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/objects/db/base.py", line 150, in list_hashes
    for path in self._list_paths(prefix, progress_callback):
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/objects/db/base.py", line 130, in _list_paths
    for file_info in self.fs.walk_files(path_info, prefix=prefix):
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/fs/gdrive.py", line 608, in walk_files
    for filename in self.ls(path_info, recursive=True):
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/fs/gdrive.py", line 576, in ls
    yield from self._ls_recursive(path_info, detail=detail)
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/fs/gdrive.py", line 554, in _ls_recursive
    for item in self._gdrive_list_ids(query_ids):
  File "/home/user/venv/full38/lib/python3.8/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/user/venv/full38/lib/python3.8/site-packages/funcy/flow.py", line 125, in retry
    return call()
  File "/home/user/venv/full38/lib/python3.8/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/user/venv/full38/lib/python3.8/site-packages/dvc/fs/gdrive.py", line 443, in <lambda>
    get_list = _gdrive_retry(lambda: next(file_list, None))
  File "/home/user/venv/full38/lib/python3.8/site-packages/pydrive2/apiattr.py", line 150, in __next__
    result = self._GetList()
  File "/home/user/venv/full38/lib/python3.8/site-packages/pydrive2/auth.py", line 84, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/home/user/venv/full38/lib/python3.8/site-packages/pydrive2/files.py", line 90, in _GetList
    raise ApiRequestError(error)
pydrive2.files.ApiRequestError: <HttpError 403 when requesting https://www.googleapis.com/drive/v2/files?q=%28%27<sha1>%27+in+parents+or+%27<sha3>%27+in+parents+or+%27<sha4>%27+in+parents%29+and+trashed%3Dfalse&maxResults=1000&corpora=drive&driveId=<sha2>&supportsAllDrives=true&includeItemsFromAllDrives=true&alt=json returned "The attempted action requires shared drive membership.". Details: "The attempted action requires shared drive membership.">
------------------------------------------------------------
2021-03-15 16:15:06,585 DEBUG: Version info for developers:
DVC version: 2.0.5 (pip)
---------------------------------
Platform: Python 3.8.0 on Linux-4.15.0-135-generic-x86_64-with-glibc2.27
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb1
Caches: local
Remotes: gdrive
Workspace directory: ext4 on /dev/sdb1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-03-15 16:15:06,586 DEBUG: Analytics is enabled.
2021-03-15 16:15:06,672 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpkf9p61_a']'
2021-03-15 16:15:06,674 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpkf9p61_a']'
```
Note that I've replaced all SHA hashes with <sha1>, <sha2>, <sha3>, and <sha4>. However, I've done this consistently (the same identifier always refers to the same hash), and `<sha1>` matches the `<sha1>` used in the instructions to reproduce.

**Comment by pared** [comment]
Discord context:
https://discord.com/channels/485586884165107732/485596304961962003/820049193723887667
