### ISSUE TITLE
dvc update : DVC can no longer download data from AWS remotes

### ISSUE THREAD

**Issue by BeatWolf** [iterative/dvc#5636]
## Description

Since DVC 2.0 i can no longer download any data from AWS remotes. I can still download using DVC 1.0 and also upload to the remote using DVC 2.0.

### Reproduce

dvc push
dvc update -R imported_data

### Expected

Download works

### Environment information

```
DVC version: 2.0.5 (deb)
---------------------------------
Platform: Python 3.7.10 on Linux-5.0.0-21-generic-x86_64-with-debian-buster-sid
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda1
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/sda1
Repo: dvc, git
```
**Additional Information (if any):**

Full output of dvc update -v
```
dvc update -R imported/ -v
2021-03-16 14:31:12,563 DEBUG: Check for update is enabled.
2021-03-16 14:31:12,999 DEBUG: Creating external repo https://gitlab.forge.hefr.ch/document-analysis/converters/detext-converter.git@None
2021-03-16 14:31:13,001 DEBUG: erepo: git clone 'https://gitlab.forge.hefr.ch/document-analysis/converters/detext-converter.git' to a temporary dir
2021-03-16 14:31:13,802 DEBUG: Computed stage: 'imported/detext.dvc' md5: '4c232edc1349c721a636676dc1ea4aaa'
2021-03-16 14:31:13,803 DEBUG: 'md5' of stage: 'imported/detext.dvc' changed.
2021-03-16 14:31:13,803 DEBUG: stage: 'imported/detext.dvc' changed.
2021-03-16 14:31:13,804 DEBUG: Removing output 'imported/detext' of stage: 'imported/detext.dvc'.
2021-03-16 14:31:13,805 DEBUG: Removing 'imported/detext'
Importing 'dataset/ (https://gitlab.forge.hefr.ch/document-analysis/converters/detext-converter.git)' -> 'imported/detext'
2021-03-16 14:31:13,806 DEBUG: Computed stage: 'imported/detext.dvc' md5: '4c232edc1349c721a636676dc1ea4aaa'
2021-03-16 14:31:13,806 DEBUG: 'md5' of stage: 'imported/detext.dvc' changed.
2021-03-16 14:31:13,806 DEBUG: Creating external repo https://gitlab.forge.hefr.ch/document-analysis/converters/detext-converter.git@eec08d397fd921ea5de1ae268d3833332afb028a
2021-03-16 14:31:13,812 DEBUG: Checking if stage '/tmp/tmp1jsknrlidvc-clone/dataset' is in 'dvc.yaml'
2021-03-16 14:31:14,048 DEBUG: Preparing to download data from 's3://XXXXXX/DVC/detext'
2021-03-16 14:31:14,048 DEBUG: Preparing to collect status from s3://XXXXXX/DVC/detext
2021-03-16 14:31:14,048 DEBUG: Collecting information from local cache...
2021-03-16 14:31:16,325 ERROR: unexpected error - 400 Client Error: Bad Request for url: https://XXXXXXXX.s3.amazonaws.com/DVC/detext/6e/ebd8a2f59ce214cf16d182b0625a63?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXXXX&X-Amz-Date=20210316T133115Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=XXXXXXXXXXXXXXXXXXXXXXXXX
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/main.py", line 50, in main
  File "dvc/command/update.py", line 21, in run
  File "dvc/repo/__init__.py", line 49, in wrapper
  File "dvc/repo/update.py", line 34, in update
  File "dvc/stage/__init__.py", line 417, in update
  File "dvc/stage/imports.py", line 29, in update_import
  File "site-packages/funcy/decorators.py", line 39, in wrapper
  File "dvc/stage/decorators.py", line 36, in rwlocked
  File "site-packages/funcy/decorators.py", line 60, in __call__
  File "dvc/stage/__init__.py", line 407, in reproduce
  File "site-packages/funcy/decorators.py", line 39, in wrapper
  File "dvc/stage/decorators.py", line 36, in rwlocked
  File "site-packages/funcy/decorators.py", line 60, in __call__
  File "dvc/stage/__init__.py", line 506, in run
  File "dvc/stage/imports.py", line 48, in sync_import
  File "dvc/dependency/repo.py", line 99, in download
  File "dvc/objects/__init__.py", line 194, in save
  File "dvc/objects/__init__.py", line 174, in save
  File "dvc/objects/__init__.py", line 57, in save
  File "dvc/objects/db/base.py", line 58, in add
  File "contextlib.py", line 112, in __enter__
  File "dvc/utils/http.py", line 16, in open_url
  File "contextlib.py", line 112, in __enter__
  File "dvc/utils/http.py", line 59, in iter_url
  File "dvc/utils/http.py", line 36, in request
  File "site-packages/requests/models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://xxxx.s3.amazonaws.com/DVC/detext/6e/ebd8a2f59ce214cf16d182b0625a63?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXXXXXXXX&X-Amz-Date=20210316T133115Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=XXXXXXXXXXXXXXXXXXXXXXXXXXXX
------------------------------------------------------------
2021-03-16 14:31:17,124 DEBUG: Version info for developers:
DVC version: 2.0.5 (deb)
---------------------------------
Platform: Python 3.7.10 on Linux-5.0.0-21-generic-x86_64-with-debian-buster-sid
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda1
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/sda1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

**Comment by BeatWolf** [comment]
Additional information. When using the URL given by DVC that throws the 400 error, i get that useful information:
<Message>Error parsing the X-Amz-Credential parameter; the region 'eu-west-1' is wrong; expecting 'us-east-2'</Message>
I tried setting the default region on the machine that downloads the data using:
AWS_DEFAULT_REGION=us-east-2

This did not help. I just now got it to work by editing the remote setting in the dvc repository that handles the data, there i had to explicitely set "region = us-east-2" in the config file.

I still think this is a bug, this was not required in DVC 1.0

**Comment by isidentical** [comment]
We are switching our s3 backend from our own written implementation to s3fs, which probably would automatically solve this issue. (The cause of the issue is boto trying to set the region to `us-east-2` by default when it sees signature_version set to s3v4 (change on 2.0) when generating a signed download url).

**Comment by isidentical** [comment]
@BeatWolf can you try to install dvc from the github, and give it a shot? `pip install 'dvc[s3] @ git+https://github.com/iterative/dvc.git'`
