### ISSUE TITLE
exp:Error "cannot stash changes - there is nothing to stash" on windows

### ISSUE THREAD

**Issue by gdiepen** [iterative/dvc#5684]
# Bug Report

## Description

After creating a new project and initializing dvc on it I would like to run an experiment with setting a parameter value. If I run this command on a linux machine it works, running the same command on windows gives me the following error:

```
ERROR: unexpected error - 'cannot stash changes - there is nothing to stash.'
```
The full output of the different command are:
![image](https://user-images.githubusercontent.com/2786853/112284660-c21caf00-8c89-11eb-9c99-567876cce258.png)

If I run exactly the same commands on exactly the same clean repo under linux, this works, as you can see in the screenshot below:
![image](https://user-images.githubusercontent.com/2786853/112284790-e6788b80-8c89-11eb-9a16-0c772a29839e.png)

### Reproduce

I created a very small demo project that depends on a value y (taken from y.txt) and a parameter x from params.yaml and it calculates the product as a 'metric'.

The steps will clone this test repository and initiate an experiment with setting the x parameter value to 40

1. git clone https://github.com/gdiepen/test_experiments_dvc
2. cd test_experiments_dvc
3. dvc exp run --set-param settings.x=40

If you run these steps on windows, you will get the error message about stash

### Expected

Under windows I would expect the same to happen, namely that an experiment is created which you can see in the `dvc exp show` command.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.0.6 (pip)
---------------------------------
Platform: Python 3.8.8 on Windows-10-10.0.18362-SP0
Supports: hdfs, http, https, s3
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Additional Information (if any):**

Using the same version of git and the same version of dvc on a linux machine everything works, it only appears to happen on my windows machine.

**Comment by gdiepen** [comment]
Did see that I made small mistake in the original dvc.yaml configuration and not include settings.x as a parameter on which the stage was depending. Just updated the repository I refer to for this (otherwise changing the parameters might not trigger a new run)

**Comment by gdiepen** [comment]
After chat on discord, got asked to run the command:
`dvc exp run --set-param settings.x=40 -vv`
to get more verbose information.

The output of this command on a clean clone of the repo is the following:
```
(dvc_test_guido) ~\Documents\Projects\test_experiments_dvc [master ≡]> dvc exp run --set-param settings.x=40 -vv
2021-03-25 09:06:44,370 TRACE: Namespace(all_pipelines=False, cd='.', checkpoint_resume=None, cmd='run', cprofile=False, cprofile_dump=None, downstream=False, dry=False, force=False, force_downstream=False, func=<class 'dvc.command.experiments.CmdExperimentsRun'>, glob=False, instrument=False, instrument_open=False, interactive=False, jobs=None, metrics=False, name=None, no_commit=False, no_run_cache=False, pdb=False, pipeline=False, pull=False, queue=False, quiet=0, recursive=False, reset=False, run_all=False, set_param=['settings.x=40'], single_item=False, targets=[], tmp_dir=False, verbose=2, version=None)
2021-03-25 09:06:45,135 DEBUG: Check for update is enabled.
2021-03-25 09:06:45,478 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-03-25 09:06:45,712 DEBUG: Spawned '['daemon', '-q', 'updater']'
2021-03-25 09:06:46,072 DEBUG: Detaching HEAD at 'HEAD'
2021-03-25 09:06:46,279 DEBUG: Stashing workspace
2021-03-25 09:06:46,318 DEBUG: Stashing changes in 'refs/stash'
2021-03-25 09:06:46,344 DEBUG: Restore HEAD to 'master'
2021-03-25 09:06:46,394 ERROR: unexpected error - 'cannot stash changes - there is nothing to stash.'
------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\dvc\main.py", line 50, in main
    ret = cmd.run()
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\dvc\command\experiments.py", line 525, in run
    results = self.repo.experiments.run(
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\dvc\repo\experiments\__init__.py", line 815, in run
    return run(self.repo, *args, **kwargs)
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\dvc\repo\__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\dvc\repo\experiments\run.py", line 32, in run
    return repo.experiments.reproduce_one(
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\dvc\repo\experiments\__init__.py", line 351, in reproduce_one
    stash_rev = self.new(
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\dvc\repo\experiments\__init__.py", line 46, in wrapper
    return f(exp, *args, **kwargs)
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\dvc\repo\experiments\__init__.py", line 416, in new
    return self._stash_exp(*args, **kwargs)
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\dvc\repo\experiments\__init__.py", line 169, in _stash_exp
    with self.scm.stash_workspace() as workspace:
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\dvc\scm\git\__init__.py", line 463, in stash_workspace
    rev = self.stash.push(**kwargs)
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\dvc\scm\git\stash.py", line 40, in push
    rev, reset = self.scm._stash_push(  # pylint: disable=protected-access
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\dvc\scm\git\__init__.py", line 335, in _backend_func
    return func(*args, **kwargs)
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\dvc\scm\git\backend\pygit2.py", line 330, in _stash_push
    oid = self.repo.stash(
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\pygit2\repository.py", line 1089, in stash
    check_error(err)
  File "c:\users\guido\anaconda3\envs\dvc_test_guido\lib\site-packages\pygit2\errors.py", line 56, in check_error
    raise KeyError(message)
KeyError: 'cannot stash changes - there is nothing to stash.'
------------------------------------------------------------
2021-03-25 09:06:48,008 DEBUG: Version info for developers:
DVC version: 2.0.6 (pip)
---------------------------------
Platform: Python 3.8.8 on Windows-10-10.0.18362-SP0
Supports: hdfs, http, https, s3
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-03-25 09:06:48,014 DEBUG: Analytics is enabled.
2021-03-25 09:06:48,024 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\guido\\AppData\\Local\\Temp\\tmpigif9v7k']'
2021-03-25 09:06:48,266 DEBUG: Spawned '['daemon', '-q', 'analytics', 'C:\\Users\\guido\\AppData\\Local\\Temp\\tmpigif9v7k']'
(dvc_test_guido) ~\Documents\Projects\test_experiments_dvc [master ≡]>

```

**Comment by gdiepen** [comment]
One small workaround I have for this at the moment is make a small change to any file that is under git version control (but not related to any of the stages,etc).

After that, it will run without any error (and when all the experiment runs are done, it will still have the same modified file ready to be staged for commit)

**Comment by pmrowla** [comment]
Things to investigate for this issue:

1. For some reason this check (via dulwich's `porcelain.status()`) is returning that the workspace state is dirty on Windows, even though it should be clean
https://github.com/iterative/dvc/blob/d87ace0968656912db9e6de3b638b594ceeda43b/dvc/scm/git/stash.py#L35-L37

2. In our pygit `_stash_push`, we should catch this exception (nothing to stash) and then just return `(None, False)` if there is nothing to be stashed (`None` for no stash commit made)
https://github.com/iterative/dvc/blob/d87ace0968656912db9e6de3b638b594ceeda43b/dvc/scm/git/backend/pygit2.py#L339-L343

**Comment by gdiepen** [comment]
Is there anything I can help testing/investigating for this @pmrowla ?

**Comment by pmrowla** [comment]
@gdiepen it's in our current sprint so hopefully a team member should get to it within the next week or 2, but if you want to investigate as well, feel free. Just see my previous comment for info on where to get started

**Comment by pmrowla** [comment]
Upstream dulwich bug report: https://github.com/dulwich/dulwich/issues/865

**Comment by pmrowla** [comment]
A temporary workaround for this issue is to just explicitly do

```
git config core.autocrlf true
```
in your repository on Windows.

Windows Git sets this by default in the system level .gitconfig, but the upstream bug is that dulwich currently only checks the repo and global (user home directory) level configs (and not system level) for `core.autocrlf`.

**Comment by pmrowla** [comment]
This issue is fixed in upstream dulwich master, waiting on release
