### ISSUE TITLE
pull: doesn't get the data from azure blob storage

### ISSUE THREAD

**Issue by HyanBatista** [iterative/dvc#5686]
# Bug Report

## Description

I installed dvc using pip and try to get the data from azure blob storage in a preset project that I had. Using the .deb installation in the version 2.0.5 it doesn't happen though.

### Reproduce

1. Clone preset project using azure as the dvc remote.
2. pip install dvc==2.0.7
3. dvc pull

### Expected

I expeted that the data would be downloaded from the azure blob storage.

### Environment information

**Output of `dvc doctor`:**
```console
DVC version: 2.0.7 (pip)
---------------------------------
Platform: Python 3.6.11 on Linux-5.8.0-45-generic-x86_64-with-debian-10.5
Supports: azure, http, https
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/sda6
Repo: dvc, git
```

**Output of `pip freeze | grep adlfs`:**
```console
adlfs==0.6.3
```
**Output of `dvc pull -v`:**
```console
2021-03-24 02:05:33,430 DEBUG: Check for update is enabled.
2021-03-24 02:05:33,499 DEBUG: '/app/.dvc/tmp/updater' is outdated
2021-03-24 02:05:33,545 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-03-24 02:05:33,546 DEBUG: Spawned '['daemon', '-q', 'updater']'
2021-03-24 02:05:40,514 DEBUG: Preparing to download data from 'azure://niniciais-storage/'
2021-03-24 02:05:40,515 DEBUG: Preparing to collect status from azure://niniciais-storage/
2021-03-24 02:05:40,516 DEBUG: Collecting information from local cache...
2021-03-24 02:05:40,520 DEBUG: Collecting information from remote cache...
2021-03-24 02:05:40,524 DEBUG: Matched '0' indexed hashes
2021-03-24 02:05:41,763 DEBUG: Estimated remote size: 4096 files
2021-03-24 02:05:41,764 DEBUG: Querying '30' hashes via traverse
2021-03-24 02:05:41,920 ERROR: unexpected error - 'niniciais-storage/'
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dvc/main.py", line 50, in main
    ret = cmd.run()
  File "/usr/local/lib/python3.6/site-packages/dvc/command/data_sync.py", line 40, in run
    glob=self.args.glob,
  File "/usr/local/lib/python3.6/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dvc/repo/pull.py", line 38, in pull
    run_cache=run_cache,
  File "/usr/local/lib/python3.6/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dvc/repo/fetch.py", line 63, in fetch
    used, jobs, remote=remote, show_checksums=show_checksums,
  File "/usr/local/lib/python3.6/site-packages/dvc/data_cloud.py", line 92, in pull
    show_checksums=show_checksums,
  File "/usr/local/lib/python3.6/site-packages/dvc/remote/base.py", line 56, in wrapper
    return f(obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dvc/remote/base.py", line 491, in pull
    download=True,
  File "/usr/local/lib/python3.6/site-packages/dvc/remote/base.py", line 328, in _process
    download=download,
  File "/usr/local/lib/python3.6/site-packages/dvc/remote/base.py", line 176, in _status
    md5s, jobs=jobs, name=str(self.fs.path_info)
  File "/usr/local/lib/python3.6/site-packages/dvc/remote/base.py", line 132, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File "/usr/local/lib/python3.6/site-packages/dvc/objects/db/base.py", line 410, in hashes_exist
    self.list_hashes_traverse(remote_size, remote_hashes, jobs, name)
  File "/usr/local/lib/python3.6/site-packages/dvc/objects/db/base.py", line 269, in list_hashes_traverse
    yield from itertools.chain.from_iterable(in_remote)
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/dvc/objects/db/base.py", line 261, in list_with_update
    prefix=prefix, progress_callback=pbar.update
  File "/usr/local/lib/python3.6/site-packages/dvc/objects/db/base.py", line 150, in list_hashes
    for path in self._list_paths(prefix, progress_callback):
  File "/usr/local/lib/python3.6/site-packages/dvc/objects/db/base.py", line 130, in _list_paths
    for file_info in self.fs.walk_files(path_info, prefix=prefix):
  File "/usr/local/lib/python3.6/site-packages/dvc/fs/fsspec_wrapper.py", line 113, in walk_files
    for file in self.ls(path_info, recursive=True):
  File "/usr/local/lib/python3.6/site-packages/dvc/fs/fsspec_wrapper.py", line 99, in ls
    if self.isdir(path_info) and self.is_empty(path_info):
  File "/usr/local/lib/python3.6/site-packages/dvc/fs/fsspec_wrapper.py", line 80, in is_empty
    entry = self.info(path_info)
  File "/usr/local/lib/python3.6/site-packages/dvc/fs/fsspec_wrapper.py", line 120, in info
    info = self.fs.info(self._with_bucket(path_info)).copy()
  File "/usr/local/lib/python3.6/site-packages/adlfs/spec.py", line 534, in info
    fetch_from_azure = (path and self._ls_from_cache(path) is None) or refresh
  File "/usr/local/lib/python3.6/site-packages/fsspec/spec.py", line 343, in _ls_from_cache
    return self.dircache[path]
  File "/usr/local/lib/python3.6/site-packages/fsspec/dircache.py", line 62, in __getitem__
    return self._cache[item]  # maybe raises KeyError
KeyError: 'niniciais-storage/'
```

**Comment by isidentical** [comment]
Can you try with installing adlfs from the source

```
pip install git+https://github.com/dask/adlfs.git
```

**Comment by efiop** [comment]
Closing in favor of https://github.com/iterative/dvc/issues/5717 .

@HyanBatista The recipe @isidentical shared worked for other users, so you might want to try it out too. We are waiting for adlfs release to update dvc requirements. Thanks again for the feedback! :pray:
