### ISSUE TITLE
dvc repro: failed to reproduce 'dvc.yaml'

### ISSUE THREAD

**Issue by lefos99** [iterative/dvc#5691]
# Bug Report

## Description
After upgrading to DVC 2.0, I tried to reproduce a stage in my pipeline. The stage looks like this (I introduced the [new template format](https://dvc.org/doc/user-guide/project-structure/pipelines-files#templating)):
```
  generate_testing_data:
    desc: 'Generates the testing data'
    cmd: PYTHONPATH='../../.' python3 data/run_generate_hotspots_data.py --path_hotspots_csv=${paths.raw.hotspot_infos}
      --dir_cell_classifications=${paths.raw.annotations} --dir_dot_annotations=${paths.raw.images}
      --class_scenario_version=${class_scenario_version} --dir_out=${paths.generated.test_hotspots} --is_test=true
    deps:
      - ${paths.raw.hotspot_infos}
      - ${paths.raw.annotations}
      - ${paths.raw.images}
      - ../base/data/run_generate_hotspots_data.py
      - ../base/util/util_data.py
    params:
      - data/config/generate_hotspots_data.ini:
          - mpp_lst
          - offset_px
    outs:
      - ${paths.generated.test_hotspots}:
          cache: true
```
So when I reproduce the stage:
```
dvc repro generate_testing_data -v
```
My script seems to run fine but in the end, I get this from DVC (I activated the verbose flag for that)
```
2021-03-25 13:09:13,260 ERROR: failed to reproduce 'dvc.yaml':        
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/reproduce.py", line 196, in _reproduce_stages
    ret = _reproduce_stage(stage, **kwargs)
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/reproduce.py", line 39, in _reproduce_stage
    stage = stage.reproduce(**kwargs)
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/stage/__init__.py", line 407, in reproduce
    self.run(**kwargs)
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/stage/__init__.py", line 520, in run
    self.save(allow_missing=allow_missing)
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/stage/__init__.py", line 437, in save
    self.save_outs(allow_missing=allow_missing)
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/stage/__init__.py", line 451, in save_outs
    out.save()
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/output/base.py", line 289, in save
    self.ignore()
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/output/base.py", line 266, in ignore
    if self.repo.scm.is_tracked(self.fspath):
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/scm/git/__init__.py", line 335, in _backend_func
    return func(*args, **kwargs)
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/scm/git/backend/dulwich.py", line 224, in is_tracked
    for path in self.repo.open_index():
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dulwich/repo.py", line 1238, in open_index
    return Index(self.index_path())
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dulwich/index.py", line 290, in __init__
    self.read()
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dulwich/index.py", line 315, in read
    for x in read_index(f):
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dulwich/index.py", line 210, in read_index
    assert version in (1, 2)
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/main.py", line 55, in main
    ret = cmd.run()
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/command/repro.py", line 14, in run
    stages = self.repo.reproduce(**self._repro_kwargs)
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/scm_context.py", line 14, in run
    return method(repo, *args, **kw)
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/reproduce.py", line 135, in reproduce
    return _reproduce_stages(self.graph, list(stages), **kwargs)
  File "/home/deep/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/reproduce.py", line 213, in _reproduce_stages
    raise ReproductionError(stage.relpath) from exc
dvc.exceptions.ReproductionError: failed to reproduce 'dvc.yaml'
------------------------------------------------------------
2021-03-25 13:09:13,265 DEBUG: Analytics is enabled.
2021-03-25 13:09:13,306 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpa8hdfokl']'
2021-03-25 13:09:13,308 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpa8hdfokl']'

```
### Environment information
**Output of `dvc doctor`:**
```
DVC version: 2.0.10 (pip)
---------------------------------
Platform: Python 3.8.5 on Linux-4.15.0-139-generic-x86_64-with-glibc2.10
Supports: http, https, ssh
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git
```

Thank you in advance for your help :smiley_cat:

**Comment by lefos99** [comment]
Okay so I found how this happened, but I have no idea why this happened.
By running in my project's top-level folder the following command:
`xxd .git/index | head -1`
I get back
`00000000: 4449 5243 0000 0003 0000 012d 5fd8 a515  DIRC.......-_...`.

The important part here is the `0003`,  which triggers the assertion `assert version in (1, 2)` in the above debug_output.

**Solution**
 So what I did to fix this, I recloned my repository and reran the command `xxd .git/index | head -1`.
 Now what I got back was
`00000000: 4449 5243 0000 0002 0000 012b 605d c6f7  DIRC.......+`]..` 

`0003` was changed to `0002` and DVC seems to run fine once again!

Still, I have no idea, why this happened in the first place! :confused:

**Comment by pared** [comment]
@lefos99 How did you found out that this particular line triggered the version check? Is it possible that you reinstalled `dvc` in the meantime?

**Comment by lefos99** [comment]
Hello @pared,
So I installed DVC 2.0 in my local machine and in another server machine (runs Ubuntu server).
In both of them, I created an anaconda environment, in which I installed exactly the same requirements.txt. Thus, I didn't install DVC through apt or snap, but with pip in both of the machines. I created an environment from scratch for that.

What happened was:
- In my local machine, everything worked fine.
- In my remote machine, the above error happened. I tried creating an anaconda environment from scratch and reinstalling DVC with pip, but with no luck - the same error appeared.

After asking a colleague of mine, he told me that [dulwich](https://pypi.org/project/dulwich/), is a library which 
`aims to provide an interface to git repos (both local and remote) that doesn’t call out to git directly but instead uses pure Python.` That library also checks the [git-index](https://git-scm.com/docs/git-show-index), and my colleague told me that all you need to do is reclone the repo. (I don't know if there is a faster fix than that..)
