### ISSUE TITLE
Support for list in params.yaml

### ISSUE THREAD

**Issue by lefos99** [iterative/dvc#5789]
Hello everyone,
My team and I are just shifted from using DVC 1.0 to DVC 2.0 and we are already really pleased! :smiley_cat: 

What we really like is the **ML pipelines parametrization**, as we now can have a `params.yaml`, which we can configure as we want.

One thing that seems missing, is the support for lists in the params.yaml.

I have already tried two ways:

```
example_list:
  - 1
  - 2
  - 3
```

and 
```
example_list: [1, 2, 3]
```

But I always get the following error by running `dvc repro stage_name -v`:
```
2021-04-09 10:28:26,234 DEBUG: Check for update is enabled.
2021-04-09 10:28:26,246 DEBUG: Assuming 'compute_train_stats' to be a stage inside 'dvc.yaml'
2021-04-09 10:28:26,296 ERROR: failed to parse 'stages.generate_training_data.cmd' in 'dvc.yaml':
Cannot interpolate data of type 'list': Cannot interpolate data of type 'list'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/parsing/__init__.py", line 301, in _resolve
    return context.resolve(
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/parsing/context.py", line 531, in resolve
    return func(src, unwrap, skip_interpolation_checks)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/parsing/interpolate.py", line 115, in wrapper
    return f(data, *args)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/parsing/context.py", line 554, in resolve_str
    return str_interpolate(
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/parsing/interpolate.py", line 165, in str_interpolate
    raise ParseError(
dvc.parsing.interpolate.ParseError: Cannot interpolate data of type 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/main.py", line 55, in main
    ret = cmd.run()
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/command/repro.py", line 14, in run
    stages = self.repo.reproduce(**self._repro_kwargs)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/scm_context.py", line 14, in run
    return method(repo, *args, **kw)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/reproduce.py", line 135, in reproduce
    return _reproduce_stages(self.graph, list(stages), **kwargs)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/__init__.py", line 415, in graph
    return build_graph(self.stages, self.outs_trie)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/__init__.py", line 437, in stages
    return self.stage.collect_repo(onerror=error_handler)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/stage.py", line 474, in collect_repo
    new_stages = self.load_file(file_path)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/stage.py", line 300, in load_file
    return self.load_all(path)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/stage.py", line 280, in load_all
    return [stages[key] for key in keys]
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/repo/stage.py", line 280, in <listcomp>
    return [stages[key] for key in keys]
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/stage/loader.py", line 123, in __getitem__
    resolved_data = self.resolver.resolve_one(name)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/parsing/__init__.py", line 176, in resolve_one
    return definition.resolve()
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/parsing/__init__.py", line 247, in resolve
    return self.resolve_stage(**kwargs)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/parsing/__init__.py", line 289, in resolve_stage
    resolved = {
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/parsing/__init__.py", line 290, in <dictcomp>
    key: self._resolve(context, value, key, skip_checks)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/parsing/__init__.py", line 305, in _resolve
    format_and_raise(
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/parsing/__init__.py", line 81, in format_and_raise
    _reraise_err(ResolveError, message, from_exc=exc)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection/lib/python3.8/site-packages/dvc/parsing/__init__.py", line 89, in _reraise_err
    raise err from from_exc
dvc.parsing.ResolveError: failed to parse 'stages.generate_training_data.cmd' in 'dvc.yaml':
Cannot interpolate data of type 'list'
------------------------------------------------------------
2021-04-09 10:28:26,299 DEBUG: Analytics is enabled.
2021-04-09 10:28:26,318 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpw0gw8c95']'
2021-04-09 10:28:26,319 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpw0gw8c95']'

```

**DVC doctor output**
```
DVC version: 2.0.17 (pip)
---------------------------------
Platform: Python 3.8.8 on Linux-5.4.0-70-generic-x86_64-with-glibc2.10
Supports: http, https, ssh
Cache types: symlink
Cache directory: ext4 on /dev/sda
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/nvme1n1p6
Repo: dvc, git
```

**Comment by skshetry** [comment]
@lefos99, the problem is not with the support for the list in `params.yaml`, but with the use of it in the `cmd`. Could you please share the example `cmd` and the one you expect after it is substituted?

**Comment by lefos99** [comment]
Hey @skshetry,
Thanks for your reply.

You are right, I managed to make it work like this:

- params.yaml
```
mpp_lst: 1.0 0.5 0.25
```

- dvc.yaml
```
stages:
  generate_training_data:
    desc: 'Generates the training data'
    cmd: python data/run_generate_hotspots_data.py --mpp_lst ${mpp_lst}
```

And my configparser in my python code looks like that:
```
    p = configargparse.ArgParser(default_config_files=[config_file_path])
    p.add('--mpp_lst', default=[], nargs='+', type=float, help='List of microns per pixel to generate data for')
```


Thanks for your help! :smile_cat:

**Comment by skshetry** [comment]
@lefos99, we could support this, but there are different ways that you'd like to join the items, so we are not sure what to do in this case. 

Someone might expect it as space/dot/comma separated, and some may expect the literal list value.
