### ISSUE TITLE
dvc add --external <s3_bucket>: requests.exceptions.HTTPError: 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by csnick93** [iterative/dvc#5820]
# Bug Report

## Description

I am following the guide at https://dvc.org/doc/user-guide/managing-external-data to version a dataset sitting on s3. As a small toy example I have created a bucket, which contains a subdirectory that holds the images to be versioned, and another subdirectory for the cache. I.e. the structure is identical to what's provided in the example guide. I have configured the cache according to the commands

```
dvc remote add s3cache s3://mybucket/cache
dvc config cache.s3 s3cache
```

However, when attempting to run the command `dvc add --external s3://mybucket/existing-data` , I am getting an `requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: error`. The provided url seems to be a pre-signed url to the cache directory of the bucket. I can see that the correct aws key is being used in the url as well, so it is not (at least not an obvious) credentials problem. Following the url shows me this error:

```
2021-04-15 14:29:50,114 DEBUG: Check for update is enabled.
2021-04-15 14:29:57,713 DEBUG: {'s3://<my_bucket>/image-rotation': 'modified'}
Adding...
2021-04-15 14:30:03,930 ERROR: unexpected error - 403 Client Error: Forbidden for url: https://<mybucket>.s3.eu-central-1.amazonaws.com/cache/b4/<aws_signature>

------------------------------------------------------------
Traceback (most recent call last):                                                                                                                                                File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/main.py", line 55, in main                                               ret = cmd.run()
File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/command/add.py", line 21, in run
	self.repo.add(
File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/repo/scm_context.py", line 14, in run
    return method(repo, *args, **kw)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/repo/add.py", line 123, in add
    _process_stages(
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/repo/add.py", line 195, in _process_stages
    stage.save()
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/stage/__init__.py", line 437, in save
    self.save_outs(allow_missing=allow_missing)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/stage/__init__.py", line 451, in save_outs
    out.save()
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/output/base.py", line 308, in save
    self.obj = ostage(
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/objects/stage.py", line 177, in stage
    obj = _get_tree_obj(path_info, fs, name, odb, state, **kwargs)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/objects/stage.py", line 118, in _get_tree_obj
    odb.add(tree.path_info, tree.fs, tree.hash_info)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/objects/db/base.py", line 47, in add
    self.check(hash_info)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/objects/db/base.py", line 109, in check
    obj.check(self)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/objects/file.py", line 40, in check
    actual = get_file_hash(
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/objects/stage.py", line 43, in get_file_hash
    hash_info = _get_file_hash(path_info, fs, name)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/objects/stage.py", line 24, in _get_file_hash
    name, file_md5(path_info, fs), size=fs.getsize(path_info)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/utils/__init__.py", line 50, in file_md5
    binary = not istextfile(fname, fs=fs)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/istextfile.py", line 31, in istextfile
    with fs.open(fname, "rb") as fobj:
  File "/Users/<me>/.pyenv/versions/3.8.0/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/utils/http.py", line 16, in open_url
    with iter_url(url, **iter_opts) as (response, it):
  File "/Users/<me>/.pyenv/versions/3.8.0/lib/python3.8/contextlib.py", line 113, in __enter__

  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/stage/__init__.py", line 451, in save_outs
    out.save()
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/output/base.py", line 308, in save
    self.obj = ostage(
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/objects/stage.py", line 177, in stage
    obj = _get_tree_obj(path_info, fs, name, odb, state, **kwargs)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/objects/stage.py", line 118, in _get_tree_obj
    odb.add(tree.path_info, tree.fs, tree.hash_info)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/objects/db/base.py", line 47, in add
    self.check(hash_info)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/objects/db/base.py", line 109, in check
    obj.check(self)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/objects/file.py", line 40, in check
    actual = get_file_hash(
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/objects/stage.py", line 43, in get_file_hash
    hash_info = _get_file_hash(path_info, fs, name)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/objects/stage.py", line 24, in _get_file_hash
    name, file_md5(path_info, fs), size=fs.getsize(path_info)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/utils/__init__.py", line 50, in file_md5
    binary = not istextfile(fname, fs=fs)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/istextfile.py", line 31, in istextfile
    with fs.open(fname, "rb") as fobj:
  File "/Users/<me>/.pyenv/versions/3.8.0/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/utils/http.py", line 16, in open_url
    with iter_url(url, **iter_opts) as (response, it):
  File "/Users/<me>/.pyenv/versions/3.8.0/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/utils/http.py", line 59, in iter_url
    response = request()
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/dvc/utils/http.py", line 36, in request
    response.raise_for_status()
  File "/Users/<me>/.pyenv/versions/3.8.0/envs/image_rotation/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://<mybucket>.s3.eu-central-1.amazonaws.com/cache/b4/<aws_signature>

------------------------------------------------------------
2021-04-15 14:30:04,081 DEBUG: Version info for developers:
DVC version: 2.0.17 (pip)
---------------------------------
Platform: Python 3.8.0 on macOS-11.2.3-x86_64-i386-64bit
Supports: http, https, s3
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local, s3
Remotes: s3
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-04-15 14:30:04,083 DEBUG: Analytics is enabled.
2021-04-15 14:30:04,213 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/7h/bh5m2mnj3bvd2d8jz39636h00000gp/T/tmpltj3eqs9']'
2021-04-15 14:30:04,215 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/7h/bh5m2mnj3bvd2d8jz39636h00000gp/T/tmpltj3eqs9']'
```

### Reproduce

1. `dvc init`
2. Create a bucket `my-bucket` on s3
3. Upload some images into `my-bucket/data/`
4. Configure the s3-cache via `dvc remote add s3cache s3://my-bucket/cache && dvc config cache.s3 s3cache` 
5. Set the appropriate region for where the bucket is: `dvc remote modify s3cache region <region_name>`
6. Try to version external dataset: `dvc add --external s3://my-bucket/data --verbose`

### Expected

I expected some kind of success message that the data on s3 has been successfully added to data versioning control.

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.0.17 (pip)
---------------------------------
Platform: Python 3.8.0 on macOS-11.2.3-x86_64-i386-64bit
Supports: http, https, s3
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local, s3
Remotes: s3
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by csnick93** [comment]
Hey @isidentical,
so the `bug` label means that it's a confirmed bug on your end I assume? Also I see that this bug has been removed from the sprint list, does that mean its fix is postponed to a later date? Just asking so that I can plan my activities accordingly :)

**Comment by dberenbaum** [comment]
@efiop Thoughts?

**Comment by isidentical** [comment]
> Also I see that this bug has been removed from the sprint list, does that mean its fix is postponed to a later date?

Yep, it is a bug. The reason that it got removed from the sprint is that, we already track the issue in a separate one (which is rewriting all our s3 backend). Hopefully it will be gone after that. I assigned my self to this issue, and will let you know when it gets landed.

> @efiop Thoughts?

This is probably going to be resolved with the s3fs PR.

**Comment by csnick93** [comment]
@isidentical Thanks a lot! :)

**Comment by isidentical** [comment]
Hey @csnick93, can you try to install DVC from the GitHub, and give it a shot? `pip install 'dvc[s3] @ git+https://github.com/iterative/dvc.git'`

**Comment by csnick93** [comment]
Hey @isidentical, 
thanks for the notification, it works now! Thanks a lot to everyone involved! :)

**Comment by efiop** [comment]
Thank you @isidentical ! :pray:
