### ISSUE TITLE
config modify: doesn't respect bash expansions.

### ISSUE THREAD

**Issue by ashutosh-dwivedi-e3502** [iterative/dvc#5848]
`dvc remote modify staging credentialpath ~/.aws/staging_credentials` results in a `.dvc/config` file like this : 

```
['remote "staging"']                                                                                                   
    url = s3://bucket_path
    credentialpath = /home/username_1/.aws/staging_credentials  
```
However this won't work for any other user. Manually replasing the value of credentialpath to `~/.aws/staging_credentials` also doesn't work.
DVC version: 1.11.16.

**Comment by ashutosh-dwivedi-e3502** [comment]
In the latest version = 2.0.18, pull works but push doesn't. It results in a `ERROR: unexpected error - An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied ` error.

**Comment by isidentical** [comment]
@ashutosh-dwivedi-e3502 can you share the full output of `dvc doctor` and `dvc push -v`

**Comment by shcheklein** [comment]
`dvc remote modify staging credentialpath ~/.aws/staging_credentials` I think `~` is being substituted even before it hits DVC. Probably you should take into quotes and/or escape. If I'm not missing anything :)

If we allow or not `~` in the config - good question. Would be great to have it. Like @isidentical mentioned would be great to see the DVC version and logs.

**Comment by ashutosh-dwivedi-e3502** [comment]
Here are the output for the version = 2.0.18

`dvc doctor`
```
DVC version: 2.0.18 (pip)
---------------------------------
Platform: Python 3.8.8 on Linux-4.14.198-152.320.amzn2.x86_64-x86_64-with-glibc2.10
Supports: http, https, s3
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/xvdcu
Caches: local
Remotes: s3, s3
Workspace directory: ext4 on /dev/xvdcu
Repo: dvc, git
```
`dvc push -v`
```
2021-04-21 06:13:20,135 DEBUG: Check for update is enabled.
2021-04-21 06:13:20,136 DEBUG: '/home/jovyan/project_name/.dvc/tmp/updater' is outdated
2021-04-21 06:13:20,160 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-04-21 06:13:20,161 DEBUG: Spawned '['daemon', '-q', 'updater']'
2021-04-21 06:13:20,412 DEBUG: Preparing to upload data to 's3://path_to_s3_bucket'
2021-04-21 06:13:20,413 DEBUG: Preparing to collect status from s3://path_to_3_bucket
2021-04-21 06:13:20,413 DEBUG: Collecting information from local cache...
2021-04-21 06:13:20,414 DEBUG: Collecting information from remote cache...                                             
2021-04-21 06:13:20,414 DEBUG: Matched '0' indexed hashes
2021-04-21 06:13:21,564 DEBUG: Estimated remote size: 4096 files                                                       
2021-04-21 06:13:21,564 DEBUG: Querying '16' hashes via traverse                                                       
Everything is up to date.                                                                                              
2021-04-21 06:13:22,847 DEBUG: Analytics is enabled.
2021-04-21 06:13:22,848 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpc53ibvjd']'
2021-04-21 06:13:22,851 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpc53ibvjd']'
```

**Comment by ashutosh-dwivedi-e3502** [comment]
@shcheklein The default value of this parameter is `~/.aws/config, according to the docs. Not allowing the ~ in the user setting makes for a bad experience.

The alternative would be having to store the credential file etc in a location whose path is independent of the username, since the absolute path like /home/user_name1/.aws/some_credential_file would be different for every user, which doesn't seem like a great option.

**Comment by isidentical** [comment]
> In the latest version = 2.0.18, pull works but push doesn't. It results in a ERROR: unexpected error - An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied error.

> Here are the output for the version = 2.0.18

It seems like the operation now succeeds, right?

**Comment by ashutosh-dwivedi-e3502** [comment]
@isidentical pull succeeds but push doesn't.

**Comment by isidentical** [comment]
> @isidentical pull succeeds but push doesn't.

I can't see any failure-related tracebacks in the logs of command `dvc push -v` that you just sent. How it isn't suceedding?

**Comment by ashutosh-dwivedi-e3502** [comment]
`dvc push` succeeded because of it was pushing to the default remote.  Here the output of `dvc push -v -r staging` which fails.

```
2021-04-22 09:34:24,709 DEBUG: Check for update is enabled.
2021-04-22 09:34:24,948 DEBUG: Preparing to upload data to 's3://path_to_s3_bucket
2021-04-22 09:34:24,948 DEBUG: Preparing to collect status from s3://path_to_s3_bucket
2021-04-22 09:34:24,949 DEBUG: Collecting information from local cache...
2021-04-22 09:34:24,949 DEBUG: Collecting information from remote cache...                                             
2021-04-22 09:34:24,950 DEBUG: Matched '0' indexed hashes
2021-04-22 09:34:26,179 ERROR: unexpected error - An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
------------------------------------------------------------
Traceback (most recent call last):
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/main.py", line 55, in main
    ret = cmd.run()
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/command/data_sync.py", line 56, in run
    processed_files_count = self.repo.push(
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/repo/push.py", line 41, in push
    return len(used_run_cache) + self.cloud.push(used, jobs, remote=remote)
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/data_cloud.py", line 66, in push
    return remote.push(
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/remote/base.py", line 56, in wrapper
    return f(obj, *args, **kwargs)
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/remote/base.py", line 466, in push
    ret = self._process(
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/remote/base.py", line 323, in _process
    dir_status, file_status, dir_contents = self._status(
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/remote/base.py", line 175, in _status
    self.hashes_exist(
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/remote/base.py", line 132, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/objects/db/base.py", line 384, in hashes_exist
    remote_size, remote_hashes = self._estimate_remote_size(hashes, name)
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/objects/db/base.py", line 206, in _estimate_remote_size
    remote_hashes = set(hashes)
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/objects/db/base.py", line 160, in _hashes_with_limit
    for hash_ in self.list_hashes(prefix, progress_callback):
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/objects/db/base.py", line 150, in list_hashes
    for path in self._list_paths(prefix, progress_callback):
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/objects/db/base.py", line 130, in _list_paths
    for file_info in self.fs.walk_files(path_info, prefix=prefix):
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/fs/s3.py", line 290, in walk_files
    for fname in self._list_paths(path_info, **kwargs):
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/dvc/fs/s3.py", line 284, in _list_paths
    for obj_summary in obj_summaries:
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/miniconda3/envs/itom/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
------------------------------------------------------------
2021-04-22 09:34:26,240 DEBUG: Version info for developers:
DVC version: 2.0.18 (pip)
---------------------------------
Platform: Python 3.8.8 on Linux-4.14.198-152.320.amzn2.x86_64-x86_64-with-glibc2.10
Supports: http, https, s3
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/xvdcu
Caches: local
Remotes: s3, s3
Workspace directory: ext4 on /dev/xvdcu
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-04-22 09:34:26,242 DEBUG: Analytics is enabled.
2021-04-22 09:34:26,288 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpxouue02u']'
2021-04-22 09:34:26,290 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpxouue02u']'
```

**Comment by isidentical** [comment]
Can you access the location of the `staging` via `aws s3 ls s3://path/to/staging`? It seems like you might have insufficient permissions or typed the wrong path

**Comment by ashutosh-dwivedi-e3502** [comment]
@isidentical I can access it. 
The same command works fine when I give the full path in the `credentialpath` setting instead of the one with ~
