### ISSUE TITLE
add: unexpected error - read length must be positive

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc#5851]
Discord context: https://discord.com/channels/485586884165107732/563406153334128681/833985098234986536
DVC doctor;
```
$ dvc doctor
DVC version: 2.0.18 (pip)
---------------------------------
Platform: Python 3.6.10 on Linux-5.8.0-48-generic-x86_64-with-debian-bullseye-sid
Supports: http, https, s3
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3, s3
Workspace directory: ext4 on /dev/mapper/vgubuntu-root
Repo: dvc, git
```
Full output:
```
$ dvc add -v --remote myremote2 --to-remote file_stored_in_remote2.txt
2021-04-20 09:41:05,816 DEBUG: Check for update is enabled.
Adding...                                                                                                                                                                       
2021-04-20 09:41:06,054 ERROR: unexpected error - read length must be positive                                                                                                  
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/dvc/main.py", line 55, in main
    ret = cmd.run()
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/dvc/command/add.py", line 32, in run
    jobs=self.args.jobs,
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/dvc/repo/scm_context.py", line 14, in run
    return method(repo, *args, **kw)
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/dvc/repo/add.py", line 131, in add
    **kwargs,
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/dvc/repo/add.py", line 172, in _process_stages
    command="add",
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/dvc/data_cloud.py", line 111, in transfer
    return remote.transfer(from_fs, from_fs.path_info, jobs=jobs)
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/dvc/remote/base.py", line 516, in transfer
    no_progress_bar=no_progress_bar,
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/dvc/objects/transfer.py", line 90, in transfer
    tmp_info, hash_info = _transfer_file(odb, from_fs, from_info)
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/dvc/objects/transfer.py", line 30, in _transfer_file
    desc=from_info.name,
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/dvc/fs/base.py", line 252, in upload_fobj
    self._upload_fobj(wrapped, to_info)  # pylint: disable=no-member
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/dvc/fs/s3.py", line 437, in _upload_fobj
    obj.upload_fileobj(fobj, Config=self._transfer_config)
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/boto3/s3/inject.py", line 621, in object_upload_fileobj
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/boto3/s3/inject.py", line 539, in upload_fileobj
    return future.result()
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/s3transfer/upload.py", line 556, in _submit
    upload_input_manager)
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/s3transfer/upload.py", line 578, in _submit_upload_request
    transfer_future),
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/s3transfer/upload.py", line 395, in get_put_object_body
    self._initial_data + fileobj.read(), callbacks, close_callbacks)
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/tqdm/utils.py", line 184, in read
    data = func(*args, **kwargs)
  File "/home/pierodallepezze/venv-dvc/lib/python3.6/site-packages/dvc/utils/stream.py", line 89, in read
    chunk = self._reader(n)
ValueError: read length must be positive
------------------------------------------------------------
2021-04-20 09:41:06,085 DEBUG: Version info for developers:
DVC version: 2.0.18 (pip)
---------------------------------
Platform: Python 3.6.10 on Linux-5.8.0-48-generic-x86_64-with-debian-bullseye-sid
Supports: http, https, s3
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3, s3
Workspace directory: ext4 on /dev/mapper/vgubuntu-root
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-04-20 09:41:06,088 DEBUG: Analytics is enabled.
2021-04-20 09:41:06,126 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpaq21pyqf']'
2021-04-20 09:41:06,127 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpaq21pyqf']'

```

**Comment by isidentical** [comment]
This issue seems to be specific to 3.6 https://discord.com/channels/485586884165107732/563406153334128681/833990073787482112
