### ISSUE TITLE
diff: with `--targets` and `--hide-missing` produces `KeyError: 'not in cache'`

### ISSUE THREAD

**Issue by courentin** [iterative/dvc#5869]
# Bug Report

## Description

When passing both `--targets` and `--hide-missing` to `dvc diff`, I have the following error:

```
------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/.venv/lib/python3.7/site-packages/dvc/main.py", line 55, in main
    ret = cmd.run()
  File "/root/project/.venv/lib/python3.7/site-packages/dvc/command/diff.py", line 143, in run
    del diff["not in cache"]
KeyError: 'not in cache'
------------------------------------------------------------
```
Ran: `dvc diff --hide-missing --targets dvc.yaml -v`

**Additional Information (if any):**

<details>
<summary>Full log</summary>

```
2021-04-23 14:49:49,376 ERROR: unexpected error - 'not in cache'
------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/.venv/lib/python3.7/site-packages/dvc/main.py", line 55, in main
    ret = cmd.run()
  File "/root/project/.venv/lib/python3.7/site-packages/dvc/command/diff.py", line 143, in run
    del diff["not in cache"]
KeyError: 'not in cache'
------------------------------------------------------------
2021-04-23 14:49:49,451 DEBUG: Version info for developers:
DVC version: 2.0.18 (pip)
---------------------------------
Platform: Python 3.7.5 on Linux-4.15.0-1092-aws-x86_64-with-Ubuntu-18.04-bionic
Supports: http, https, s3
Cache types: hardlink, symlink
Cache directory: overlay on overlay
Caches: local
Remotes: s3
Workspace directory: overlay on overlay
Repo: dvc, git
```

</details>

**Comment by pared** [comment]
Seems like the problem occurs if we return empty dictionary from within [repo/diff](https://github.com/iterative/dvc/blob/54c0675fc664cd97394a1f789aaa385a5205a304/dvc/repo/diff.py#L99). If we provide `--hide-missing` option, we try to delete non existing entry. Simple solution would be to just delete the key only if it exists. Other one, probably more appropriate would be to check whether diff can return empty dict, or should it return dict with empty statuses entries.

Repro script:

```
#!/bin/bash

rm -rf wspace
mkdir wspace
pushd wspace

set -ex

main=$(pwd)
mkdir repo
pushd repo

git init --quiet
dvc init --quiet

git add -A
git commit -am "init"

echo something >> random_git_file
git add -A
git commit -am "add git-only file"

dvc diff --hide-missing
```

**Comment by skshetry** [comment]
This has been fixed by https://github.com/iterative/dvc/pull/7406, and released in [`2.10.0`](https://github.com/iterative/dvc/releases/tag/2.10.0).
