### ISSUE TITLE
dvc add causes ERROR without saying that's the problem

### ISSUE THREAD

**Issue by Diyago** [iterative/dvc#5870]
# Bug Report

## Description
dvc add causes ERROR without saying that's the problem. 
We need clear explanation that is wrong

### Reproduce

(venv) (base) insaf@MacBook-Pro-Insaf test_gan % dvc add ../tabgan/Research/data/credit/credit.gz
Adding...                                                                                                                                                  
ERROR: /Users/insaf/Desktop/ml projects/tabgan/Research/data/credit/credit.gz

### Expected
Add file to dvc config file

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```
(venv) (base) insaf@MacBook-Pro-Insaf test_gan % dvc doctor
DVC version: 2.0.18 (osxpkg)
---------------------------------
Platform: Python 3.8.9 on macOS-10.16-x86_64-i386-64bit
Supports: All remotes
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git

Please check https://github.com/iterative/dvc/wiki/Debugging-DVC on ways to gather more information regarding the issue.

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.
If the issue is regarding the performance, please attach the profiling information and the benchmark comparisons.
-->

**Comment by efiop** [comment]
Hi @Diyago Please add `-v` to the command you are running and post full log for it.

**Comment by Diyago** [comment]
(venv) (base) insaf@MacBook-Pro-Insaf test_gan % dvc doctor -v      
DVC version: 2.0.18 (osxpkg)
---------------------------------
Platform: Python 3.8.9 on macOS-10.16-x86_64-i386-64bit
Supports: All remotes
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git
2021-04-26 00:29:35,091 DEBUG: Analytics is enabled.
2021-04-26 00:29:35,241 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/s7/khxd34ns2jxbbvl4tbcdcv5w0000gn/T/tmpq1x_cxax']'
2021-04-26 00:29:35,243 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/s7/khxd34ns2jxbbvl4tbcdcv5w0000gn/T/tmpq1x_cxax']'

**Comment by Diyago** [comment]
(venv) (base) insaf@MacBook-Pro-Insaf test_gan % dvc add ../tabgan/Research/data/credit/credit.gz --verbose
2021-04-26 00:30:46,405 DEBUG: Check for update is enabled.
Adding...                                                                   
2021-04-26 00:30:46,661 ERROR: /Users/insaf/Desktop/ml projects/tabgan/Research/data/credit/credit.gz
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/command/add.py", line 21, in run
  File "dvc/repo/__init__.py", line 49, in wrapper
  File "dvc/repo/scm_context.py", line 14, in run
  File "dvc/repo/add.py", line 123, in add
  File "dvc/repo/add.py", line 195, in _process_stages
  File "dvc/stage/__init__.py", line 437, in save
  File "dvc/stage/__init__.py", line 451, in save_outs
  File "dvc/output/base.py", line 289, in save
  File "dvc/output/base.py", line 269, in ignore
  File "dvc/scm/git/__init__.py", line 153, in ignore
  File "dvc/scm/git/__init__.py", line 148, in _get_gitignore
dvc.scm.base.FileNotInRepoError: /Users/insaf/Desktop/ml projects/tabgan/Research/data/credit/credit.gz
------------------------------------------------------------
2021-04-26 00:30:46,663 DEBUG: Analytics is enabled.
2021-04-26 00:30:46,741 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/s7/khxd34ns2jxbbvl4tbcdcv5w0000gn/T/tmpd8btdh0j']'
2021-04-26 00:30:46,743 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/s7/khxd34ns2jxbbvl4tbcdcv5w0000gn/T/tmpd8btdh0j']'

**Comment by efiop** [comment]
@Diyago Thanks! Ok, so the issue is that the file you are trying to add is outside of your dvc project. Could you elaborate on what you are trying to do?

We should improve the error message for that exception, that's for sure.

**Comment by Diyago** [comment]
The file outside of your dvc project - yes, that's right. But is the problem of doing? 

Im trying to add file to track for the dvc

**Comment by efiop** [comment]
@Diyago Yeah, `dvc add` is similar to `git add` in that it expects you to add files/dirs that are inside of your project. You could copy/move it into your repo and then

```
dvc add credit.gz
```

or you could tell dvc that you want it to take that file and put it as `credit.gz` into your repo, e.g.:

```
dvc add ../tabgan/Research/data/credit/credit.gz -o credit.gz
```

**Comment by karajan1001** [comment]
Maybe we can make a more friendly message.

**Comment by efiop** [comment]
@Diyago Did one of those commands work for you?

Keeping this issue open for error message fix.
