### ISSUE TITLE
dvc.api.open: fails if streaming a .h5 file (dvc 2.1)

### ISSUE THREAD

**Issue by AnnKatrinBecker** [iterative/dvc#5990]
## Description

Streaming the identical model in h5py format works in dvc version 1.11.16,
but raises the following exception in dvc version 2.1

`Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7f82676084f0> returned a result with an error set`

code snippet:
```
with dvc.api.open('data/saved_model/model.h5',
                      repo=config_env['REPO'],
                      rev=config_env['REV'],
                      remote=config_env['REMOTE'],
                      mode='rb') as model_file:
        h5_fileobject = h5py.File(model_file, 'r')
        model = tf.keras.models.load_model(h5_fileobject)
```

**Output of `dvc doctor`:**

```console
DVC version: 2.1.0 (pip)
---------------------------------
Platform: Python 3.8.6 on Linux-5.4.0-66-generic-x86_64-with-glibc2.29
Supports: http, https, webdav, webdavs
```

**Comment by AnnKatrinBecker** [comment]
Tried installing latest version `DVC version: 2.1.0+b349b3 `

The issue persists:

```
Traceback (most recent call last):                                                                                                                                                                                                                                                                                  
  File "h5py/h5fd.pyx", line 160, in h5py.h5fd.H5FD_fileobj_read                                                                                                                                                                                                                                                    
  File "/home/akb/.pyenv/versions/3.8.6/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/.../predict_app.py", line 59, in <module>
    model = load_model()
  File "/.../predict_app.py", line 54, in load_model
    h5_fileobject = h5py.File(model_file, 'r')
  File "/.../.venv/lib/python3.8/site-packages/h5py/_hl/files.py", line 406, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/.../.venv/lib/python3.8/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
  File "h5py/defs.pyx", line 666, in h5py.defs.H5Fopen
  File "h5py/h5fd.pyx", line 155, in h5py.h5fd.H5FD_fileobj_read
SystemError: <built-in method flush of _io.BytesIO object at 0x7efdeb35a810> returned a result with an error set
```

**Comment by efiop** [comment]
@AnnKatrinBecker Could you show `dvc doctor` output inside of the config_env['REPO'], please?

**Comment by AnnKatrinBecker** [comment]
```
DVC version: 2.1.0 (pip)
---------------------------------
Platform: Python 3.8.6 on Linux-5.4.0-73-generic-x86_64-with-glibc2.29
Supports: hdfs, http, https, webdav, webdavs
Cache types: reflink, hardlink, symlink
Cache directory: btrfs on /dev/nvme0n1p1
Caches: local
Remotes: webdav, webdav, webdav, webdav
Workspace directory: btrfs on /dev/nvme0n1p1
Repo: dvc, git
```

**Comment by efiop** [comment]
@AnnKatrinBecker Are you able to `dvc pull` and open and load that file like that without api.open?

**Comment by AnnKatrinBecker** [comment]
If I `dvc pull` the model in the config_env['REPO'] I can load it.
Similarly if I initialize dvc in the initial repo and `dvc import` the model, I can successfully load it.

Sorry, that I did not state this clearly before.

**Comment by pmrowla** [comment]
@AnnKatrinBecker what type of remote are you streaming from

**Comment by AnnKatrinBecker** [comment]
we are using a webdav server

**Comment by efiop** [comment]
Interesting that https://github.com/iterative/dvc/issues/6041 is also a webdav one. Might be a different type of bug, but still. Maybe time to move to webdav4 first instead of investigating all of the `webdav3` issues. CC @skshetry

**Comment by skshetry** [comment]
Hi, @AnnKatrinBecker. Could you please try installing from the latest master and see if it fixes any issue?
```console
pip install git+https://github.com/iterative/dvc.git#egg=dvc[webdav]
```

**Comment by AnnKatrinBecker** [comment]
Thanks for the update.
I updated to the lastest master including webdav4, now the issue is a different one.
Our Server does not support ranges, which seem to be required.

```
File "h5py/h5fd.pyx", line 150, in h5py.h5fd.H5FD_fileobj_get_eof
  File "h5py/h5fd.pyx", line 150, in h5py.h5fd.H5FD_fileobj_get_eof
  File "/.../.venv/lib/python3.8/site-packages/webdav4/fsspec.py", line 409, in seek
    return self.reader.seek(loc, whence=whence)
  File "/.../.venv/lib/python3.8/site-packages/webdav4/stream.py", line 195, in seek
    raise ValueError("server does not support ranges")
ValueError: server does not support ranges
```

**Comment by skshetry** [comment]
@AnnKatrinBecker, could you please provide more information about the server?  Thanks.

It might be tricky, but I'll try later this week to solve this.

**Comment by AnnKatrinBecker** [comment]
Thank you for your concern.

Server Infos:
FreeBSD 11.3-RELEASE-p14 (FreeNAS.amd64) #0 r325575+c936002dbe2(HEAD): Mon Sep 28 10:46:56 EDT 2020
nginx version: nginx/1.16.1

In case you require additional information, please specify and I can consult with our infrastructure team.

**Comment by efiop** [comment]
@AnnKatrinBecker @skshetry is asking about the type of webdav server that you are using. Is it owncloud, yandex or something else?

**Comment by AnnKatrinBecker** [comment]
Apache/2.4.41 with WebDav Extension
https://httpd.apache.org/docs/current/mod/mod_dav.html

**Comment by skshetry** [comment]
I looked into this. The reason why it works in 1.11.x is that we did not use to implement `open` method for WebDAV, so we were falling back to "fetch-to-cache and open" logic.
https://github.com/iterative/dvc/blob/55bf18d8f92832610c816f2bbe25f804bd2c1338/dvc/tree/dvc.py#L92-L100

Starting with 2.x, we implemented `open` for the straight-to-remote use case which works in a similar way, in that it downloads the file completely and tries to give you the file object (which has been buggy as you pointed out).

From 2.4 onwards, we use `webdav4` which provides an `open` function that streams. I looked into `h5py` and it seems that it's not going to be straightforward to support it if the server does not support `Ranges` headers (as it requires `seek`).

Also, `webdav4` uses the `Ranges` header to retry/reconnect on connection failures and timeouts automatically. So, @AnnKatrinBecker, I'd suggest you ask to support the `Ranges`/`Accept-Ranges` header. 

You can have the 1.11.x behavior in the following ways:
```python
from io import BytesIO

buff = BytesIO(
    dvc.api.read('data/saved_model/model.h5',
        repo=config_env['REPO'],
        rev=config_env['REV'],
        remote=config_env['REMOTE'],
        mode='rb'
    )
)

h5_fileobject = h5py.File(buff, 'r')
model = tf.keras.models.load_model(h5_fileobject)
```

**Comment by AnnKatrinBecker** [comment]
Thank you very much.

Invoking the 1.11.x behavior is successful.
Additionally we planned to support the `Ranges` header in the future.
