### ISSUE TITLE
dvc push/pull ImportError

### ISSUE THREAD

**Issue by kwon-young** [iterative/dvc#5995]
# Bug Report

## Description

Here is my setup:

* `datasets` git repository
  * this repo serves as a data registry as described in [the doc](https://dvc.org/doc/use-cases/data-registries)
  * the remote is a ssh remote with a path like `user@myserver:/path/to/datasets/cache`

* `isolating-gan` git repository
  * this repo is my current dev project which imports datasets from the `datasets` repo using `dvc import` using the gitlab url of the `datasets` project
  * this repo also has a ssh remote with a path like `user@myserver:/path/to/isolating-gan/cache`

Then, the command `dvc push` or `dvc pull` done in `my-project` can crash, but not always with the following traceback:

```
$ dvc push -v                                                                                                                                             
2021-05-12 09:06:23,899 DEBUG: Check for update is enabled.
2021-05-12 09:06:23,945 DEBUG: Lockfile 'dvc.lock' needs to be updated.                                                                                                                                          
2021-05-12 09:06:23,969 WARNING: Output 'data/syntheticdetection'(stage: 'traindetector') is missing version info. Cache for it will not be collected. Use `dvc repro` to get your pipeline up to date.
2021-05-12 09:06:23,969 WARNING: Output 'data/dvclive/syntheticdetection'(stage: 'traindetector') is missing version info. Cache for it will not be collected. Use `dvc repro` to get your pipeline up to date.  
2021-05-12 09:06:24,075 DEBUG: Preparing to upload data to 'ssh://kchoi@sabre/temp_dd/imadoc_2/users/kchoi/isolating-gan'
2021-05-12 09:06:24,075 DEBUG: Preparing to collect status from ssh://kchoi@sabre/temp_dd/imadoc_2/users/kchoi/isolating-gan                                                                                     
2021-05-12 09:06:24,076 DEBUG: Collecting information from local cache...    
2021-05-12 09:06:24,077 DEBUG: Collecting information from remote cache...                                                                                                                                       
2021-05-12 09:06:24,078 DEBUG: Matched '0' indexed hashes               
2021-05-12 09:06:24,082 DEBUG: Establishing ssh connection with 'sabre' through port '22' as user 'kchoi'                                                                                                        
2021-05-12 09:06:24,083 DEBUG: Establishing ssh connection with 'sabre' through port '22' as user 'kchoi'                                                                      
2021-05-12 09:06:24,083 DEBUG: Establishing ssh connection with 'sabre' through port '22' as user 'kchoi'                                                                                                        
2021-05-12 09:06:24,661 ERROR: unexpected error - cannot import name 'SSHConnection' from partially initialized module 'dvc.fs.ssh.connection' (most likely due to a circular import) (/srv/longdd/kchoi/mambaforg
e/envs/isolating-gan/lib/python3.9/site-packages/dvc/fs/ssh/connection.py)                                                                                                                                       
------------------------------------------------------------                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                               
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/site-packages/dvc/main.py", line 55, in main                                                                                                
    ret = cmd.run()                                                                                                                                                                                              
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/site-packages/dvc/command/data_sync.py", line 56, in run
    processed_files_count = self.repo.push(                                                                                                                                                                      
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)                                                                                                                                                                              
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/site-packages/dvc/repo/push.py", line 41, in push                                                                
    return len(used_run_cache) + self.cloud.push(used, jobs, remote=remote)                                                                                                                                      
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/site-packages/dvc/data_cloud.py", line 66, in push
    return remote.push(                                                                                                                                                                                          
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/site-packages/dvc/remote/base.py", line 56, in wrapper
    return f(obj, *args, **kwargs)                                                                                                                                                                                  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/site-packages/dvc/remote/base.py", line 466, in push                                                                                     
    ret = self._process(                                                                                                 
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/site-packages/dvc/remote/base.py", line 323, in _process
    dir_status, file_status, dir_contents = self._status(                
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/site-packages/dvc/remote/base.py", line 175, in _status
    self.hashes_exist(                                               
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/site-packages/dvc/remote/base.py", line 132, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)                                
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/site-packages/dvc/objects/db/ssh.py", line 73, in hashes_exist                                                                             
    ret = list(itertools.compress(hashes, in_remote))                                                                                                                                                             
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/concurrent/futures/_base.py", line 600, in result_iterator
    yield fs.pop().result()                                                                                                                                                                                      
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()                                                                                    
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception                                                                                                     
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/site-packages/dvc/objects/db/ssh.py", line 64, in exists_with_progress
    return self.batch_exists(chunks, callback=pbar.update_msg)
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/site-packages/dvc/objects/db/ssh.py", line 31, in batch_exists
    with self.fs.ssh(path_infos[0]) as ssh:
  File "/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/site-packages/dvc/fs/ssh/__init__.py", line 135, in ssh
    from .connection import SSHConnection
ImportError: cannot import name 'SSHConnection' from partially initialized module 'dvc.fs.ssh.connection' (most likely due to a circular import) (/srv/longdd/kchoi/mambaforge/envs/isolating-gan/lib/python3.9/si
te-packages/dvc/fs/ssh/connection.py)
------------------------------------------------------------
2021-05-12 09:06:24,851 DEBUG: Version info for developers:
DVC version: 2.1.0 (conda)
---------------------------------
Platform: Python 3.9.2 on Linux-4.19.0-16-amd64-x86_64-with-glibc2.28
Supports: http, https, ssh
Cache types: hardlink, symlink
Cache directory: ceph on 131.254.135.54:6789,131.254.135.55:6789,131.254.135.56:6789:/volumes/csi/csi-vol-c100e9b9-3eb0-11ea-9c3b-fed11c850da8
Caches: local
Remotes: ssh, local
Workspace directory: ceph on 131.254.135.54:6789,131.254.135.55:6789,131.254.135.56:6789:/volumes/csi/csi-vol-c100e9b9-3eb0-11ea-9c3b-fed11c850da8
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

If I use `dvc push/pull -j 1` it works everytime, which leads me to thing that it is a concurrency issue.

### Reproduce

Setup a data registry using a ssh remote.

The in the isolating-gan git directory, import data from the data registry:

1. dvc init
2. dvc import https://mygitlabserver.com/kchoi/isolating-gan.git data/mydatasets
3. git add mydatasets.dvc; git commit ...
4. dvc pull or dvc push

### Expected

Data is pushed or pulled normally

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.1.0 (conda)
---------------------------------
Platform: Python 3.9.2 on Linux-4.19.0-16-amd64-x86_64-with-glibc2.28
Supports: http, https, ssh
Cache types: hardlink, symlink
Cache directory: ceph on 131.254.135.54:6789,131.254.135.55:6789,131.254.135.56:6789:/volumes/csi/csi-vol-c100e9b9-3eb0-11ea-9c3b-fed11c850da8
Caches: local
Remotes: ssh, local
Workspace directory: ceph on 131.254.135.54:6789,131.254.135.55:6789,131.254.135.56:6789:/volumes/csi/csi-vol-c100e9b9-3eb0-11ea-9c3b-fed11c850da8
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by pmrowla** [comment]
For the record, it looks like the problem was this core Python bug (affects 3.9 and 3.10 only) - https://bugs.python.org/issue43517

The solution is to upgrade Python to 3.9.4 or later (or run any 3.7 or 3.8)

**Comment by kwon-young** [comment]
thank you very much for your help
