### ISSUE TITLE
TypeError: walk() got an unexpected keyword argument 'detail'

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc#6048]
```
Traceback (most recent call last):
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/command/base.py", line 50, in do_run
    return self.run()
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/command/data_sync.py", line 66, in run
    glob=self.args.glob,
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/repo/push.py", line 41, in push
    return len(used_run_cache) + self.cloud.push(used, jobs, remote=remote)
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/data_cloud.py", line 68, in push
    show_checksums=show_checksums,
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/remote/base.py", line 56, in wrapper
    return f(obj, *args, **kwargs)
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/remote/base.py", line 469, in push
    download=False,
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/remote/base.py", line 326, in _process
    download=download,
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/remote/base.py", line 174, in _status
    md5s, jobs=jobs, name=str(self.fs.path_info)
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/remote/base.py", line 130, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/objects/db/base.py", line 408, in hashes_exist
    remote_size, remote_hashes = self._estimate_remote_size(hashes, name)
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/objects/db/base.py", line 230, in _estimate_remote_size
    remote_hashes = set(hashes)
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/objects/db/base.py", line 184, in _hashes_with_limit
    for hash_ in self.list_hashes(prefix, progress_callback):
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/objects/db/base.py", line 174, in list_hashes
    for path in self._list_paths(prefix, progress_callback):
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/objects/db/base.py", line 154, in _list_paths
    for file_info in self.fs.walk_files(path_info, prefix=prefix):
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/fs/fsspec_wrapper.py", line 106, in walk_files
    for file in self.find(path_info):
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/dvc/fs/fsspec_wrapper.py", line 172, in find
    files = self.fs.find(path, detail=detail)
  File "/Users/opt/anaconda3/lib/python3.7/site-packages/fsspec/spec.py", line 439, in find
    for _, dirs, files in self.walk(path, maxdepth, detail=True, **kwargs):
TypeError: walk() got an unexpected keyword argument 'detail'
```

Discord Context: https://discord.com/channels/485586884165107732/563406153334128681/844706071964155947

**Comment by isidentical** [comment]
This seems like fixed on the upstream: https://github.com/dask/s3fs/issues/299

**Comment by isidentical** [comment]
I assume this was a dependency mismatch, and the user did not correctly install the dvc (`dvc[s3]`) since there is no other explanation I was able to infer. Our dependencies are pinned, and the conflict doesn't happen on the environments I tested, so closing this issue. (Also informing the user to double check)
