### ISSUE TITLE
diff: fails with `NonType` error

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#6088]
# Bug Report

## Description

In the repo that I've been using to test VS code I see that `dvc diff --show-json` fails with:

```python
AttributeError: 'NoneType' object has no attribute 'trie'
```

https://www.dropbox.com/s/u09dhsgli3r7qxi/repo-6088.tgz?dl=0

### Reproduce

I can bundle the repo if we can't see the reason immediately from the stack trace.

### Expected

Don't fail, show as much information as possible.

### Information

```
(.env) ?255 Projects/dvc-get-started-mnist % dvc diff --show-json -v
2021-05-31 17:59:22,799 DEBUG: Check for update is enabled.
2021-05-31 17:59:23,831 DEBUG: Preparing to download data from 'https://remote.dvc.org/dataset-registry'
2021-05-31 17:59:23,831 DEBUG: Preparing to collect status from https://remote.dvc.org/dataset-registry
2021-05-31 17:59:23,831 DEBUG: Collecting information from local cache...
2021-05-31 17:59:23,832 DEBUG: Collecting information from remote cache...
2021-05-31 17:59:23,832 DEBUG: Matched '0' indexed hashes
2021-05-31 17:59:23,832 DEBUG: Querying 1 hashes via object_exists
2021-05-31 17:59:25,206 WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:
name: data/prepared, md5: fdd497e942a056bc13b98b2e63d4fbe9.dir
2021-05-31 17:59:25,218 ERROR: unexpected error - 'NoneType' object has no attribute 'trie'
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ivan/Projects/dvc/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/Users/ivan/Projects/dvc/dvc/command/base.py", line 50, in do_run
    return self.run()
  File "/Users/ivan/Projects/dvc/dvc/command/diff.py", line 137, in run
    diff = self.repo.diff(
  File "/Users/ivan/Projects/dvc/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/ivan/Projects/dvc/dvc/repo/diff.py", line 68, in diff
    missing = sorted(_filter_missing(repo_fs, deleted_or_missing))
  File "/Users/ivan/Projects/dvc/dvc/repo/diff.py", line 175, in _filter_missing
    metadata = repo_fs.metadata(path)
  File "/Users/ivan/Projects/dvc/dvc/fs/repo.py", line 394, in metadata
    dvc_meta = dvc_fs.metadata(path_info)
  File "/Users/ivan/Projects/dvc/dvc/fs/dvc.py", line 229, in metadata
    meta.isdir = meta.isdir or self.check_isdir(meta.path_info, meta.outs)
  File "/Users/ivan/Projects/dvc/dvc/fs/dvc.py", line 123, in check_isdir
    self._get_granular_hash(path_info, out)
  File "/Users/ivan/Projects/dvc/dvc/fs/dvc.py", line 52, in _get_granular_hash
    obj = out.obj.trie.get(key)
AttributeError: 'NoneType' object has no attribute 'trie'
------------------------------------------------------------
2021-05-31 17:59:25,790 DEBUG: Version info for developers:
DVC version: 2.2.0+488a6f
---------------------------------
Platform: Python 3.8.9 on macOS-10.15.6-x86_64-i386-64bit
Supports: All remotes
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-05-31 17:59:25,792 DEBUG: Analytics is enabled.
2021-05-31 17:59:26,000 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/rw/vfwscnts4vn0d10gl7v510640000gn/T/tmpwv2028of']'
2021-05-31 17:59:26,002 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/rw/vfwscnts4vn0d10gl7v510640000gn/T/tmpwv2028of']'
```

**Comment by shcheklein** [comment]
Also, question. I see this second time (previous was `dvc exp run` that was not consistent with `repro`) that DVC is accessing remote data registry.  Is it done to download `.dir` in this case? But if they already exist, why do we need to clone repo again? It would show:

```
  0% Querying cache in https://remote.dvc.org/dataset-registry|
```

is it local operation, or does it clone it every time? 

(Feel free to close this comment as irrelevant here - but would be nice to have an answer, Slack works)

**Comment by skshetry** [comment]
@shcheklein, we access remote storage if the .dir files are not available locally (in case of `diff` without target, it will need to access all .dir files specified in .dvc and dvc.yaml files). But, after that, they are cached, so successive `dvc diff` should not query for cache again. 


> But if they already exist, why do we need to clone repo again?

It's not cloning the repo, it's just querying the cache. It *may* not happen again.

**Comment by dberenbaum** [comment]
@shcheklein Do you know if this is still an issue and what the priority is? I downloaded the attached repo and ran `dvc diff --show-json`, and I was unable to reproduce the error.
