### ISSUE TITLE
azure - dvc fetch with SPA fails on DVC 2.3.0

### ISSUE THREAD

**Issue by friggog** [iterative/dvc#6108]
After updating from DVC 2.2.0 to DVC 2.3.0 I get the following error when running `dvc fetch` on Azure Devops CI with Service Principal Authentication

```
ERROR: unexpected error - Task <Task pending coro=<_runner() running at /opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/fsspec/asyn.py:20> cb=[_chain_future.<locals>._call_set_state() at /opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/asyncio/futures.py:358]> got Future <Future pending> attached to a different loop
```

DVC 2.2.0 works fine in this scenario, and using DefaultAzureCredential with DVC 2.3.0 on my local machine also works.

Don't have time to get a full stacktrace right now but wanted to log this to come back to at some point - locking to DVC 2.2.0 also fixes my problems so this isn't critical for now!

**Comment by pared** [comment]
@friggog would it be possible to attach the log for `dvc fetch -v` on failing machine-dvc configuration?

**Comment by friggog** [comment]
Happens specifically when fetching a file inside a directory which is tracked with DVC (not for files tracked directly).

```
> dvc fetch -v directory\file.ext
2021-06-04 17:44:32,598 DEBUG: Check for update is enabled.
2021-06-04 17:44:32,623 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-06-04 17:44:32,707 DEBUG: Spawned '['daemon', '-q', 'updater']'
2021-06-04 17:44:32,762 DEBUG: Checking if stage 'directory\file.ext' is in 'dvc.yaml'
2021-06-04 17:44:35,363 DEBUG: Preparing to download data from 'azure://container-name'
2021-06-04 17:44:35,364 DEBUG: Preparing to collect status from azure://container-name
2021-06-04 17:44:35,365 DEBUG: Collecting information from local cache...
2021-06-04 17:44:35,368 DEBUG: Collecting information from remote cache...
2021-06-04 17:44:35,369 DEBUG: Matched '1' indexed hashes
2021-06-04 17:44:35,375 DEBUG: Downloading 'azure://container-name/6d/ebd69d8dd4cdd3227620803140111e.dir' to '.dvc\cache\6d\ebd69d8dd4cdd3227620803140111e.dir'
2021-06-04 17:44:37,362 DEBUG: state save (3301544505273768948, 1622825077330897664, 74262) 6debd69d8dd4cdd3227620803140111e.dir
2021-06-04 17:44:37,433 DEBUG: Preparing to download data from 'azure://container-name'
2021-06-04 17:44:37,435 DEBUG: Preparing to collect status from azure://container-name
2021-06-04 17:44:37,437 DEBUG: Collecting information from local cache...
2021-06-04 17:44:37,442 DEBUG: Collecting information from remote cache...
2021-06-04 17:44:37,445 DEBUG: Querying 224 hashes via object_exists
2021-06-04 17:45:23,825 ERROR: unexpected error - Task <Task pending coro=<_runner() running at ...\lib\site-packages\fsspec\asyn.py:20> cb=[_chain_future.<locals>._call_set_state() at ...\lib\asyncio\futures.py:358]> got Future <Future pending> attached to a different loop
------------------------------------------------------------
Traceback (most recent call last):
  File "...\lib\site-packages\dvc\main.py", line 55, in main
    ret = cmd.do_run()
  File "...\lib\site-packages\dvc\command\base.py", line 50, in do_run
    return self.run()
  File "...\lib\site-packages\dvc\command\data_sync.py", line 89, in run
    run_cache=self.args.run_cache,
  File "...\lib\site-packages\dvc\repo\__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "...\lib\site-packages\dvc\repo\fetch.py", line 63, in fetch
    used, jobs, remote=remote, show_checksums=show_checksums
  File "...\lib\site-packages\dvc\data_cloud.py", line 88, in pull
    show_checksums=show_checksums,
  File "...\lib\site-packages\dvc\remote\base.py", line 56, in wrapper
    return f(obj, *args, **kwargs)
  File "...\lib\site-packages\dvc\remote\base.py", line 489, in pull
    download=True,
  File "...\lib\site-packages\dvc\remote\base.py", line 326, in _process
    download=download,
  File "...\lib\site-packages\dvc\remote\base.py", line 168, in _status
    self._indexed_dir_hashes(cache, named_cache, dir_md5s)
  File "...\lib\site-packages\dvc\remote\base.py", line 228, in _indexed_dir_hashes
    self.odb.list_hashes_exists(indexed_dirs)
  File "...\lib\site-packages\dvc\objects\db\base.py", line 362, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "...\lib\concurrent\futures\_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "...\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "...\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "...\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "...\lib\site-packages\dvc\objects\db\base.py", line 353, in exists_with_progress
    ret = self.fs.exists(path_info)
  File "...\lib\site-packages\dvc\fs\fsspec_wrapper.py", line 92, in exists
    return self.fs.exists(self._with_bucket(path_info))
  File "...\lib\site-packages\adlfs\spec.py", line 1259, in exists
    return sync(self.loop, self._exists, path)
  File "...\lib\site-packages\fsspec\asyn.py", line 53, in sync
    raise result[0]
  File "...\lib\site-packages\fsspec\asyn.py", line 20, in _runner
    result[0] = await coro
  File "...\lib\site-packages\adlfs\spec.py", line 1278, in _exists
    exists = await bc.exists()
  File "...\lib\site-packages\azure\core\tracing\decorator_async.py", line 74, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "...\lib\site-packages\azure\storage\blob\aio\_blob_client_async.py", line 481, in exists
    **kwargs)
  File "...\lib\site-packages\azure\storage\blob\_generated\aio\operations_async\_blob_operations_async.py", line 391, in get_properties
    pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
  File "...\lib\site-packages\azure\core\pipeline\_base_async.py", line 215, in run
    return await first_node.send(pipeline_request)
  File "...\lib\site-packages\azure\core\pipeline\_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "...\lib\site-packages\azure\core\pipeline\_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "...\lib\site-packages\azure\core\pipeline\_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  [Previous line repeated 3 more times]
  File "...\lib\site-packages\azure\core\pipeline\_base_async.py", line 81, in send
    await _await_result(self._policy.on_request, request)
  File "...\lib\site-packages\azure\core\pipeline\_tools_async.py", line 32, in await_result
    return await result  # type: ignore
  File "...\lib\site-packages\azure\core\pipeline\policies\_authentication_async.py", line 35, in on_request
    async with self._lock:
  File "...\lib\asyncio\locks.py", line 92, in __aenter__
    await self.acquire()
  File "...\lib\asyncio\locks.py", line 192, in acquire
    await fut
RuntimeError: Task <Task pending coro=<_runner() running at ...\lib\site-packages\fsspec\asyn.py:20> cb=[_chain_future.<locals>._call_set_state() at ...\lib\asyncio\futures.py:358]> got Future <Future pending> attached to a different loop
------------------------------------------------------------
2021-06-04 17:45:23,970 DEBUG: Version info for developers:
DVC version: 2.3.0 (pip)
---------------------------------
Platform: Python 3.7.10 on Windows-10-10.0.19041-SP0
Supports: azure, http, https
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: azure
Workspace directory: NTFS on C:\
Repo: dvc (subdir), git
```

**Comment by isidentical** [comment]
@friggog can you post `pip freeze | grep adlfs`?
