### ISSUE TITLE
Getting invalid syntax issue with Python 3.8 

### ISSUE THREAD

**Issue by jaiswalvineet** [iterative/dvc#6110]
I am getting this issue and not able to resolve it 

```
base) ➜  abc git:(master) ✗ dvc init
ERROR: failed to initiate DVC - '.dvc' exists. Use `-f` to force.
(base) ➜  abc git:(master) ✗ Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/opt/anaconda3/lib/python3.8/site-packages/dvc/command/base.py", line 64, in do_run
    return self.run()
  File "/opt/anaconda3/lib/python3.8/site-packages/dvc/command/daemon.py", line 32, in run
    analytics.send(self.args.target)
  File "/opt/anaconda3/lib/python3.8/site-packages/dvc/analytics.py", line 69, in send
    report.update(_runtime_info())
  File "/opt/anaconda3/lib/python3.8/site-packages/dvc/analytics.py", line 104, in _runtime_info
    "scm_class": _scm_in_use(),
  File "/opt/anaconda3/lib/python3.8/site-packages/dvc/analytics.py", line 81, in _scm_in_use
    from dvc.repo import Repo
  File "/opt/anaconda3/lib/python3.8/site-packages/dvc/repo/__init__.py", line 12, in <module>
    from dvc.ignore import DvcIgnoreFilter
  File "/opt/anaconda3/lib/python3.8/site-packages/dvc/ignore.py", line 10, in <module>
    from dvc.fs.base import BaseFileSystem
  File "/opt/anaconda3/lib/python3.8/site-packages/dvc/fs/__init__.py", line 5, in <module>
    from .azure import AzureFileSystem
  File "/opt/anaconda3/lib/python3.8/site-packages/dvc/fs/azure.py", line 1, in <module>
    import asyncio
  File "/opt/anaconda3/lib/python3.8/site-packages/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/opt/anaconda3/lib/python3.8/site-packages/asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/dvc", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.8/site-packages/dvc/main.py", line 84, in main
    from dvc.info import get_dvc_info
  File "/opt/anaconda3/lib/python3.8/site-packages/dvc/info.py", line 10, in <module>
    from dvc.fs import FS_MAP, get_fs_cls, get_fs_config
  File "/opt/anaconda3/lib/python3.8/site-packages/dvc/fs/__init__.py", line 5, in <module>
    from .azure import AzureFileSystem
  File "/opt/anaconda3/lib/python3.8/site-packages/dvc/fs/azure.py", line 1, in <module>
    import asyncio
  File "/opt/anaconda3/lib/python3.8/site-packages/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/opt/anaconda3/lib/python3.8/site-packages/asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^
SyntaxError: invalid syntax
```
python version : Python 3.8.5
pip version : pip 21.1.2 from /opt/anaconda3/lib/python3.8/site-packages/pip (python 3.8)

let me know if other information needed

**Comment by skshetry** [comment]
@jaiswalvineet, you have asyncio as a 3rd party package. It's not needed in 3.8, it shouldn't be installed. Please try uninstalling it and see if it works.

**Comment by jaiswalvineet** [comment]
> @jaiswalvineet, you have asyncio as a 3rd party package. It's not needed in 3.8, it shouldn't be installed. Please try uninstalling it and see if it works.

thanks for the reply, I am not getting this error now, just curious why it conflicted, I believe I installed this asyncio when I was working Azure CLI, where it was required
