### ISSUE TITLE
dvc pull: Missing dependenies [pyarrow] but it is installed

### ISSUE THREAD

**Issue by JeremiasThun** [iterative/dvc#6114]
# Bug Report

## Description

With `dvc pull` on my Macbook, I can't connect to a HDFS because there appears to be a missing dependency: `pyarrow`, even though pyarrow is installed and up to date.

`pip install pyarrow` returns:
```
Requirement already satisfied: pyarrow in /usr/local/lib/python3.9/site-packages (4.0.1)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.9/site-packages (from pyarrow) (1.20.3)
```

### Reproduce

1. git clone https://neemgit.informatik.uni-bremen.de/neems/ease-2020-avatar-fetch-and-place-episode
2. dvc pull

### Expected

To download the data or at least tell me that I am not allowed to, when I am not in the university's network

### Environment information

With or without being in the University's network, I get the same error. So it seems to be reproducible for everyone.

**Output of `dvc doctor`:**

```
DVC version: 2.3.0 (brew)
---------------------------------
Platform: Python 3.9.5 on macOS-11.2.3-x86_64-i386-64bit
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: hdfs
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
```

**Output of `dvc pull -v`:**

```
2021-06-04 11:13:22,308 DEBUG: Check for update is enabled.
2021-06-04 11:13:22,339 DEBUG: failed to pull cache for 'episode'     
Everything is up to date.
2021-06-04 11:13:22,340 ERROR: failed to pull data from the cloud - URL 'hdfs://hadoop@134.102.137.65:9000/neems/ease-20-avatar-fetch-and-place-episode/' is supported but requires these missing dependencies: ['pyarrow']. Please report this bug to <https://github.com/iterative/dvc/issues>. Thank you!
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/dvc/2.3.0/libexec/lib/python3.9/site-packages/dvc/command/data_sync.py", line 29, in run
    stats = self.repo.pull(
  File "/usr/local/Cellar/dvc/2.3.0/libexec/lib/python3.9/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/Cellar/dvc/2.3.0/libexec/lib/python3.9/site-packages/dvc/repo/pull.py", line 29, in pull
    processed_files_count = self.fetch(
  File "/usr/local/Cellar/dvc/2.3.0/libexec/lib/python3.9/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/Cellar/dvc/2.3.0/libexec/lib/python3.9/site-packages/dvc/repo/fetch.py", line 62, in fetch
    downloaded += self.cloud.pull(
  File "/usr/local/Cellar/dvc/2.3.0/libexec/lib/python3.9/site-packages/dvc/data_cloud.py", line 82, in pull
    remote = self.get_remote(remote, "pull")
  File "/usr/local/Cellar/dvc/2.3.0/libexec/lib/python3.9/site-packages/dvc/data_cloud.py", line 29, in get_remote
    return self._init_remote(name)
  File "/usr/local/Cellar/dvc/2.3.0/libexec/lib/python3.9/site-packages/dvc/data_cloud.py", line 49, in _init_remote
    return get_remote(self.repo, name=name)
  File "/usr/local/Cellar/dvc/2.3.0/libexec/lib/python3.9/site-packages/dvc/remote/__init__.py", line 8, in get_remote
    fs = cls(**config)
  File "/usr/local/Cellar/dvc/2.3.0/libexec/lib/python3.9/site-packages/dvc/fs/hdfs.py", line 69, in __init__
    super().__init__(**config)
  File "/usr/local/Cellar/dvc/2.3.0/libexec/lib/python3.9/site-packages/dvc/fs/base.py", line 56, in __init__
    self._check_requires(**kwargs)
  File "/usr/local/Cellar/dvc/2.3.0/libexec/lib/python3.9/site-packages/dvc/fs/base.py", line 110, in _check_requires
    raise RemoteMissingDepsError(
dvc.fs.base.RemoteMissingDepsError: URL 'hdfs://hadoop@134.102.137.65:9000/neems/ease-20-avatar-fetch-and-place-episode/' is supported but requires these missing dependencies: ['pyarrow']. Please report this bug to <https://github.com/iterative/dvc/issues>. Thank you!
------------------------------------------------------------
2021-06-04 11:13:22,342 DEBUG: Analytics is enabled.
2021-06-04 11:13:22,413 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/fh/fxx8gmpj5jn3hd3byx3cvmnh0000gn/T/tmpexridhzx']'
2021-06-04 11:13:22,414 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/fh/fxx8gmpj5jn3hd3byx3cvmnh0000gn/T/tmpexridhzx']'

```

**Comment by JeremiasThun** [comment]
`pip install pyarrow` returns
```
Requirement already satisfied: pyarrow in /usr/local/lib/python3.9/site-packages (4.0.1)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.9/site-packages (from pyarrow) (1.20.3)
```

**Comment by pmrowla** [comment]
Looks like there is some issue with the DVC homebrew package not recognizing homebrew's apache-arrow/pyarrow installation.

In the meantime, you can workaround this by just installing DVC via pip instead of homebrew

```
$ pip install dvc[all]
```
or if you only want HDFS remote support:
```
$ pip install dvc[hdfs]
```

**Comment by JeremiasThun** [comment]
Using `pip install` leaves me with the same error. Using `pipx install`, I get a different problem: #6116

**Comment by efiop** [comment]
IIRC, the problem is that libhdfs is not available through homebrew https://github.com/iterative/dvc/issues/4656 , so one needs to compile it,

An alternative is to use `webhdfs` instead. Is it available for you?

**Comment by karajan1001** [comment]
I'm using Macbook with (M1 chip) which has a lot of compatibility issues, I remember that `pyarrow` was one of them. Install from `conda` works for me.

**Comment by efiop** [comment]
closing as stale
