### ISSUE TITLE
dvc pull: Unable to load libjvm

### ISSUE THREAD

**Issue by JeremiasThun** [iterative/dvc#6116]
# Bug Report

## Description

With `dvc pull` on my Macbook, I can't connect to a HDFS because it is "unable to load libjvm". Connecting via SSH is working.

*Error-Message:*

`ERROR: unexpected error - Unable to load libjvm: dlopen(/lib/server/libjvm.dylib, 6): image not found`

### Reproduce

1. git clone https://neemgit.informatik.uni-bremen.de/neems/ease-2020-avatar-fetch-and-place-episode
2. dvc pull

### Expected

To download the data or at least tell me that I am not allowed to, when I am not in the university's network

### Environment information

With or without being in the University's network, I get the same error. So it seems to be reproducible for everyone.

**Output of `dvc doctor`:**

```
DVC version: 2.3.0 (pip)
---------------------------------
Platform: Python 3.9.5 on macOS-11.2.3-x86_64-i386-64bit
Supports: All remotes
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: hdfs
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
```

**Output of `dvc pull -v`:**

```
2021-06-04 12:07:02,643 DEBUG: Check for update is enabled.
2021-06-04 12:07:02,822 DEBUG: Preparing to download data from 'hdfs://hadoop@134.102.137.65:9000/neems/vr-set-breakfast-table'
2021-06-04 12:07:02,822 DEBUG: Preparing to collect status from hdfs://hadoop@134.102.137.65:9000/neems/vr-set-breakfast-table
2021-06-04 12:07:02,822 DEBUG: Collecting information from local cache...
2021-06-04 12:07:02,822 DEBUG: Collecting information from remote cache...                      
2021-06-04 12:07:02,822 DEBUG: Matched '0' indexed hashes
2021-06-04 12:07:02,822 DEBUG: Querying 1 hashes via object_exists
2021-06-04 12:07:02,854 ERROR: unexpected error - Unable to load libjvm: dlopen(/lib/server/libjvm.dylib, 6): image not found
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/output.py", line 796, in get_dir_cache
    objects.check(self.odb, self.odb.get(self.hash_info))
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/objects/__init__.py", line 35, in check
    odb.check(obj.hash_info)
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/objects/db/base.py", line 133, in check
    obj.check(self, check_hash=check_hash)
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/objects/file.py", line 51, in check
    actual = get_file_hash(
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/objects/stage.py", line 56, in get_file_hash
    raise FileNotFoundError(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/apfelbaum/Library/Mobile Documents/com~apple~CloudDocs/Uni/BA/playground/vr-set-breakfast-table/.dvc/cache/97/4b6be1bf3eda9e08f578d8ad9daae6.dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/command/base.py", line 50, in do_run
    return self.run()
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/command/data_sync.py", line 29, in run
    stats = self.repo.pull(
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/repo/pull.py", line 29, in pull
    processed_files_count = self.fetch(
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/repo/fetch.py", line 43, in fetch
    used = self.used_cache(
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/repo/__init__.py", line 395, in used_cache
    used_cache = stage.get_used_cache(
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/stage/__init__.py", line 630, in get_used_cache
    cache.update(out.get_used_cache(*args, **kwargs))
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/output.py", line 911, in get_used_cache
    self.hash_info.value, self.collect_used_dir_cache(**kwargs)
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/output.py", line 836, in collect_used_dir_cache
    self.get_dir_cache(jobs=jobs, remote=remote)
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/output.py", line 798, in get_dir_cache
    self.repo.cloud.pull(
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/data_cloud.py", line 84, in pull
    return remote.pull(
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/remote/base.py", line 56, in wrapper
    return f(obj, *args, **kwargs)
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/remote/base.py", line 484, in pull
    ret = self._process(
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/remote/base.py", line 321, in _process
    dir_status, file_status, dir_contents = self._status(
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/remote/base.py", line 173, in _status
    self.hashes_exist(
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/remote/base.py", line 130, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/objects/db/base.py", line 411, in hashes_exist
    remote_hashes = self.list_hashes_exists(hashes, jobs, name)
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/objects/db/base.py", line 362, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/objects/db/base.py", line 353, in exists_with_progress
    ret = self.fs.exists(path_info)
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/fs/hdfs.py", line 129, in exists
    with self.hdfs(path_info) as hdfs:
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/fs/pool.py", line 11, in get_connection
    conn = pool.get_connection()
  File "/Users/apfelbaum/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/fs/pool.py", line 53, in get_connection
    return self._conn_func(*self._conn_args, **self._conn_kwargs)
  File "pyarrow/_hdfs.pyx", line 83, in pyarrow._hdfs.HadoopFileSystem.__init__
  File "pyarrow/error.pxi", line 141, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
OSError: Unable to load libjvm: dlopen(/lib/server/libjvm.dylib, 6): image not found
------------------------------------------------------------
2021-06-04 12:07:03,581 DEBUG: Version info for developers:
DVC version: 2.3.0 (pip)
---------------------------------
Platform: Python 3.9.5 on macOS-11.2.3-x86_64-i386-64bit
Supports: All remotes
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: hdfs
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-06-04 12:07:03,582 DEBUG: Analytics is enabled.
2021-06-04 12:07:03,774 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/fh/fxx8gmpj5jn3hd3byx3cvmnh0000gn/T/tmpiyegdsb4']'
2021-06-04 12:07:03,776 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/fh/fxx8gmpj5jn3hd3byx3cvmnh0000gn/T/tmpiyegdsb4']'
```

**Comment by pared** [comment]
Hello @JeremiasThun!
This seems to be related to how pyarrow handles lack of libjvm. If you rerun command with verbose option (`dvc pull -v`) You can see that it is `pyarrow` throwing and error. So the problem here is not lack of connection to university network, but lack of proper libraries required for `pyarrow` to work properly. Do you have `hdfs` configured on your computer?

**Comment by efiop** [comment]
Closing as stale.
