### ISSUE TITLE
dvc add --external s3://mybucket/existing-data: The specified key does not exist.: An error occurred (NoSuchKey) when calling the CopyObject operation: The specified key does not exist.

### ISSUE THREAD

**Issue by seunboy1** [iterative/dvc#6119]
# Description
I have been trying to version a directory(S3 key) containing various tfrecord on S3 bucket but each time I try it always end up with this error " ERROR: unexpected error - The specified key does not exist.: An error occurred (NoSuchKey) when calling the CopyObject operation: The specified key does not exist."

However, what I noticed is that it deletes the actual data from `s3://mybucket/existing-data` and creates the pointer in the `s3://mybucket/cache`. It dosen't create the data.dvc file on my local which I could git tract.
### Reproduce

```
$ dvc remote add s3cache s3://mybucket/cache
$ dvc config cache.s3 s3cache
$ dvc add --external s3://mybucket/existing-data
```

### Error
```
Adding...                                                                       
ERROR: unexpected error - The specified key does not exist.: An error occurred (NoSuchKey) when calling the CopyObject operation: The specified key does not exist.
```

### Expected
 A data.dvc file for tracking

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.3.0 (snap)
---------------------------------
Platform: Python 3.6.9 on Linux-5.4.0-71-generic-x86_64-with-Ubuntu-18.04-bionic
Supports: azure, gdrive, gs, http, https, s3, ssh
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local, s3
Remotes: s3
Workspace directory: ext4 on /dev/sda5
Repo: dvc, git

```

**Comment by efiop** [comment]
Hi @seunboy1

Please note that `--external` is an experimental feature, we do not recommend using it in production for now.

Please add `-v` to the command you are running and show us full log.

> However, what I noticed is that it deletes the actual data from s3://mybucket/existing-data and creates the pointer in the s3://mybucket/cache. It dosen't create the data.dvc file on my local which I could git tract.

That is correct behavior, `--external` artifacts are never brought locally and things like `dvc pull/push/etc` do not affect them. Maybe you are actually looking for `dvc add --to-remote`?

**Comment by seunboy1** [comment]
Hi @efiop 
> That is correct behavior, `--external` artifacts are never brought locally and things like `dvc pull/push/etc` do not affect them. Maybe you are actually looking for `dvc add --to-remote`?

That is quite strange because i reverted back to version 2.0.17, `--external` works and a data.dvc file was created locally. Does that mean that in version 2.3.0 `--external` should be replaced with dvc add --to-remote` and there is no need for an external cache directory?

**Comment by efiop** [comment]
@seunboy1 Ah, sorry, I thought you meant that `data` is not created locally. You are right, `data.dvc` should be created locally.

**Comment by seunboy1** [comment]
@efiop Thank you for the clarity. So i am guessing that's a bug in v 2.3.0 with versioning data on s3.

**Comment by efiop** [comment]
@seunboy1 Could you add `-v` to the command you are running and show us full log, please?

**Comment by seunboy1** [comment]
@efiop 
```
2021-06-06 15:38:51,108 DEBUG: Computed stage: 'files.dvc' md5: 'None'
Adding...
2021-06-06 15:38:56,380 ERROR: unexpected error - The specified key does not exist.: An error occurred (NoSuchKey) when calling the CopyObject operation: The specified key does not exist.
------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/dvc/1305/lib/python3.6/site-packages/s3fs/core.py", line 233, in _call_s3
    out = await method(**additional_kwargs)
  File "/snap/dvc/1305/lib/python3.6/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the CopyObject operation: The specified key does not exist.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/command/base.py", line 50, in do_run
    return self.run()
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/command/add.py", line 32, in run
    jobs=self.args.jobs,
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/repo/scm_context.py", line 14, in run
    return method(repo, *args, **kw)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/repo/add.py", line 131, in add
    **kwargs,
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/repo/add.py", line 195, in _process_stages
    stage.commit()
  File "/snap/dvc/1305/lib/python3.6/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/snap/dvc/1305/lib/python3.6/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/stage/__init__.py", line 492, in commit
    out.commit(filter_info=filter_info)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/output.py", line 567, in commit
    objects.save(self.odb, obj)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/objects/__init__.py", line 29, in save
    future.result()
  File "/snap/dvc/1305/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/snap/dvc/1305/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/snap/dvc/1305/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/objects/db/base.py", line 59, in add
    self.fs.move(path_info, cache_info)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/fs/base.py", line 188, in move
    self.copy(from_info, to_info)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/fs/fsspec_wrapper.py", line 89, in copy
    self.fs.copy(self._with_bucket(from_info), self._with_bucket(to_info))
  File "/snap/dvc/1305/lib/python3.6/site-packages/fsspec/asyn.py", line 72, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/snap/dvc/1305/lib/python3.6/site-packages/fsspec/asyn.py", line 53, in sync
    raise result[0]
  File "/snap/dvc/1305/lib/python3.6/site-packages/fsspec/asyn.py", line 20, in _runner
    result[0] = await coro
  File "/snap/dvc/1305/lib/python3.6/site-packages/fsspec/asyn.py", line 228, in _copy
    raise ex
  File "/snap/dvc/1305/lib/python3.6/site-packages/s3fs/core.py", line 1528, in _cp_file
    await self._copy_basic(path1, path2, **kwargs)
  File "/snap/dvc/1305/lib/python3.6/site-packages/s3fs/core.py", line 1410, in _copy_basic
    "copy_object", kwargs, Bucket=buc2, Key=key2, CopySource=copy_src
  File "/snap/dvc/1305/lib/python3.6/site-packages/s3fs/core.py", line 252, in _call_s3
    raise translate_boto_error(err)
FileNotFoundError: The specified key does not exist.
------------------------------------------------------------
2021-06-06 15:38:58,169 DEBUG: Version info for developers:
DVC version: 2.3.0 (snap)
---------------------------------
Platform: Python 3.6.9 on Linux-5.4.0-71-generic-x86_64-with-Ubuntu-18.04-bionic
Supports: azure, gdrive, gs, http, https, s3, ssh
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local, s3
Remotes: s3
Workspace directory: ext4 on /dev/sda5
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-06-06 15:38:58,175 DEBUG: Analytics is enabled.
2021-06-06 15:38:58,279 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmp87z8bn24']'
2021-06-06 15:38:58,282 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmp87z8bn24']'

```

**Comment by efiop** [comment]
@seunboy1 Are both data that you are trying to add and cache.s3 location on the same bucket?

**Comment by seunboy1** [comment]
Yes they are.

**Comment by efiop** [comment]
@seunboy1 Thanks for clarifying. Need to take a closer look. In the mean time, could you elaborate on your scenario?

**Comment by seunboy1** [comment]
Alright, I am currently trying to version data and models residing in S3. I had done these already about a month ago and it worked perfectly however I tried it again about 3/4 days ago that's when i got those errors. Although, currently I am sorted because I  reverted to v2.0.17

**Comment by efiop** [comment]
Closing as stale.
