### ISSUE TITLE
`plot diff`: won't work with only numeric experiment names

### ISSUE THREAD

**Issue by PythonFZ** [iterative/dvc#6143]
# Bug Report

## Description

I ran multiple experiments with different sizes and layers and I named them by their neurons per layer like: 

![image](https://user-images.githubusercontent.com/46721498/121362102-26204c80-c936-11eb-927d-d2d241b78f23.png)

I can not run `dvc plots diff 8 16 32 64 128`
`ERROR: unexpected error - 8: ambiguous lookup - OID prefix is too short`

It works as soon as non numeric characters are introduced like `dvc plots diff 8_8` or when using the hash.

I tried using `dvc plots diff "128"` and `stage="8"; dvc plots diff $stage` but they did not work.
Because 128 does not work but 8_8 does, I assume it has something todo with the purely numerical name.

Maybe converting it to `str` could solve that problem?

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.3.0 (pip)
---------------------------------
Platform: Python 3.9.4 on Linux-5.4.0-74-generic-x86_64-with-glibc2.31
Supports: http, https
Cache types: symlink
Cache directory: nfs on 129.69.120.26:/beegfs/work
Caches: local
Remotes: None
Workspace directory: nfs on 129.69.120.26:/beegfs/work
Repo: dvc, git
```

**Additional Information:**

```console
>> dvc plots diff --verbose 8_8 128

2021-06-09 15:36:11,350 DEBUG: Check for update is enabled.
2021-06-09 15:36:11,467 ERROR: unexpected error - 128: ambiguous lookup - OID prefix is too short
------------------------------------------------------------
Traceback (most recent call last):
  File ".../python3.9/site-packages/pygit2/repository.py", line 309, in resolve_refish
    reference = self.lookup_reference_dwim(refish)
KeyError: '128'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File ".../python3.9/site-packages/dvc/command/base.py", line 50, in do_run
    return self.run()
  File ".../python3.9/site-packages/dvc/command/plots.py", line 37, in run
    plots = self._func(targets=self.args.targets, props=self._props())
  File ".../python3.9/site-packages/dvc/command/plots.py", line 79, in _func
    return self.repo.plots.diff(
  File ".../python3.9/site-packages/dvc/repo/plots/__init__.py", line 187, in diff
    return diff(self.repo, *args, **kwargs)
  File ".../python3.9/site-packages/dvc/repo/plots/diff.py", line 18, in diff
    return repo.plots.show(
  File ".../python3.9/site-packages/dvc/repo/plots/__init__.py", line 163, in show
    data = self.collect(targets, revs, recursive)
  File ".../python3.9/site-packages/dvc/repo/plots/__init__.py", line 60, in collect
    for rev in self.repo.brancher(revs=revs):
  File ".../python3.9/site-packages/dvc/repo/brancher.py", line 61, in brancher
    for sha, names in group_by(scm.resolve_rev, revs).items():
  File ".../python3.9/site-packages/funcy/seqs.py", line 317, in group_by
    result[f(item)].append(item)
  File ".../python3.9/site-packages/dvc/scm/git/__init__.py", line 400, in resolve_rev
    return self._resolve_rev(rev)
  File ".../python3.9/site-packages/dvc/scm/git/__init__.py", line 343, in _backend_func
    return func(*args, **kwargs)
  File ".../python3.9/site-packages/dvc/scm/git/backend/pygit2.py", line 203, in resolve_rev
    commit, _ref = self.repo.resolve_refish(rev)
  File ".../python3.9/site-packages/pygit2/repository.py", line 312, in resolve_refish
    commit = self.revparse_single(refish)
ValueError: 128: ambiguous lookup - OID prefix is too short
------------------------------------------------------------
2021-06-09 15:36:12,040 DEBUG: Version info for developers:
DVC version: 2.3.0 (pip)
---------------------------------
Platform: Python 3.9.4 on Linux-5.4.0-74-generic-x86_64-with-glibc2.31
Supports: http, https
Cache types: symlink
Cache directory: nfs on 129.69.120.26:/beegfs/work
Caches: local
Remotes: None
Workspace directory: nfs on 129.69.120.26:/beegfs/work
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-06-09 15:36:12,042 DEBUG: Analytics is enabled.
2021-06-09 15:36:12,077 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpvbpnxrbu']'
2021-06-09 15:36:12,078 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpvbpnxrbu']'
```

**Comment by pmrowla** [comment]
The problem isn't specific to numbers, if you used any short experiment name that only contained hex digits (`0-9a-f`) you'd see the same problem. The issue is that pygit thinks your experiment name looks like a shortened git commit SHA, and that the shortened SHA matches commits in your repo. In this case, `8` will match against any git commit in your repo that starts with `8...`.

What we need to do is double check that there aren't any experiment names that exactly match the given name, even if the name looks like it's supposed to be a git SHA.

In the meantime the workaround would be to just use any non-hex digit character in your experiment names (this is why your `8_8` names work) or to make your names a bit longer so that they don't match any actual commit SHAs from your repo.

**Comment by PythonFZ** [comment]
Thanks for the detailed explanation. I went with `_8` for now, which works seamlessly.
