### ISSUE TITLE
Cannot `import-url` from HTTP server missing the `Content-Length` header in responses

### ISSUE THREAD

**Issue by althonos** [iterative/dvc#6163]
# Bug Report

## Description

`dvc import-url` fails to import a file from an HTTP URL when the HTTP server does not set the `Content-Length` header. I have tried to manually download the file with `wget`, and it worked. 

I was able to reproduce this issue with a local HTTP server using a `http.server.SimpleHTTPRequestHandler` patched not to send a `Content-Length`, and I got the same error, so I can confirm that's where it's coming from.

### Reproduce

1. `dvc init`
2. `dvc import-url "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&id=KK037166.1&rettype=gbwithparts&retmode=text" test.gbk`

```console
021-06-14 13:31:06,412 DEBUG: Check for update is enabled.
2021-06-14 13:31:06,454 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-06-14 13:31:06,455 DEBUG: Spawned '['daemon', '-q', 'updater']'
2021-06-14 13:31:07,133 DEBUG: Removing output 'test.gbk' of stage: 'test.gbk.dvc'.
2021-06-14 13:31:07,134 DEBUG: Removing 'test.gbk'
Importing 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&id=KK037166.1&rettype=gbwithparts&retmode=text' -> 'test.gbk'
2021-06-14 13:31:25,047 ERROR: unexpected error - 'NoneType' object has no attribute 'endswith'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/command/base.py", line 50, in do_run
    return self.run()
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/command/imp_url.py", line 14, in run
    self.repo.imp_url(
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/repo/scm_context.py", line 14, in run
    return method(repo, *args, **kw)
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/repo/imp_url.py", line 80, in imp_url
    stage.run(jobs=jobs)
  File "/usr/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/usr/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/stage/__init__.py", line 515, in run
    sync_import(self, dry, force, jobs)
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/stage/imports.py", line 46, in sync_import
    stage.save_deps()
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/stage/__init__.py", line 450, in save_deps
    dep.save()
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/output.py", line 526, in save
    self.hash_info = self.get_hash()
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/output.py", line 399, in get_hash
    return ostage(
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/objects/stage.py", line 221, in stage
    _, obj = _get_file_obj(path_info, fs, name, odb, state, upload)
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/objects/stage.py", line 75, in _get_file_obj
    path_info, fs, get_file_hash(path_info, fs, name, state=state)
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/objects/stage.py", line 60, in get_file_hash
    hash_info = _get_file_hash(path_info, fs, name)
  File "/home/althonos/.local/lib/python3.9/site-packages/dvc/objects/stage.py", line 32, in _get_file_hash
    assert not info[name].endswith(".dir")
AttributeError: 'NoneType' object has no attribute 'endswith'
------------------------------------------------------------
2021-06-14 13:31:25,176 DEBUG: Version info for developers:
DVC version: 2.3.0 (pip)
---------------------------------
Platform: Python 3.9.5 on Linux-5.12.8-arch1-1-x86_64-with-glibc2.33
Supports: http, https, ssh
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: tmpfs on tmpfs
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-06-14 13:31:25,178 DEBUG: Analytics is enabled.
2021-06-14 13:31:25,180 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmp37mxnoeo']'
2021-06-14 13:31:25,183 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmp37mxnoeo']'
```

### Expected

`dvc` downloads the file and creates a `test.gbk.dvc` file.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.3.0 (pip)
---------------------------------
Platform: Python 3.9.5 on Linux-5.12.8-arch1-1-x86_64-with-glibc2.33
Supports: http, https, ssh
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: tmpfs on tmpfs
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by alexmojaki** [comment]
I investigated this, here's what I found. The error has since changed, here's an updated traceback:

```python
Traceback (most recent call last):
  File "/home/alex/work/dvc/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/home/alex/work/dvc/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/home/alex/work/dvc/dvc/commands/imp_url.py", line 15, in run
    self.repo.imp_url(
  File "/home/alex/work/dvc/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/alex/work/dvc/dvc/repo/scm_context.py", line 152, in run
    return method(repo, *args, **kw)
  File "/home/alex/work/dvc/dvc/repo/imp_url.py", line 83, in imp_url
    stage.run(jobs=jobs)
  File "/home/alex/work/dvc/venv/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/alex/work/dvc/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/home/alex/work/dvc/venv/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/alex/work/dvc/dvc/stage/__init__.py", line 535, in run
    self._sync_import(dry, force, jobs)
  File "/home/alex/work/dvc/venv/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/alex/work/dvc/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/home/alex/work/dvc/venv/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/alex/work/dvc/dvc/stage/__init__.py", line 559, in _sync_import
    sync_import(self, dry, force, jobs)
  File "/home/alex/work/dvc/dvc/stage/imports.py", line 46, in sync_import
    stage.save_deps()
  File "/home/alex/work/dvc/dvc/stage/__init__.py", line 470, in save_deps
    dep.save()
  File "/home/alex/work/dvc/dvc/output.py", line 552, in save
    _, self.meta, obj = ostage(
  File "/home/alex/work/dvc/venv/lib/python3.9/site-packages/dvc_data/stage.py", line 269, in stage
    _, meta, obj = _stage_file(
  File "/home/alex/work/dvc/venv/lib/python3.9/site-packages/dvc_data/stage.py", line 65, in _stage_file
    meta, hash_info = hash_file(path, fs, name, state=state)
  File "/home/alex/work/dvc/venv/lib/python3.9/site-packages/dvc_data/hashfile/hash.py", line 177, in hash_file
    assert ".dir" not in hash_info.value
TypeError: argument of type 'int' is not iterable
```

The problem doesn't seem related to missing `Content-Length`, but rather missing `ETag` and `Content-MD5`. For example if I run `python -m http.server` with no patching, the response headers have a content length, but the error is the same. Plently of URLs on the web are like this.

Here's what happens in the code:

1. In `dvc_data/hashfile/hash.py`, in the function `hash_file`:

```python
    hash_value, info = _hash_file(path, fs, name, callback=cb)
```

2. In `_hash_file`:

```python
        info = _adapt_info(fs.info(path), fs.protocol)
```

3. In `_adapt_info`:

```python
            elif scheme.startswith("http") and (
                "ETag" in info or "Content-MD5" in info
            ):
                info["checksum"] = info.get("ETag") or info.get("Content-MD5")
```

4. `"ETag" in info or "Content-MD5" in info` is False so the returned `info` doesn't have a `checksum`. Back in `_hash_file`, this is what's tried next:

```python
        if hasattr(fs, name):
            func = getattr(fs, name)
            return func(path), info
```

5. Here `fs` is an `HTTPSFileSystem` from `dvc_objects` and `name` is `checksum`. `func` exists, and it's the method `FileSystem.checksum` (`HTTPSFileSystem` doesn't have its own implementation) which simply delegates to `AbstractFileSystem.checksum` in `fsspec` (`HTTPFileSystem` in `fsspec` doesn't have its own checksum either) which looks like this:

```python
return int(tokenize(self.info(path)), 16)
```

6. That's a very simple hash of the info, which looks like `{'name': 'https://...', 'size': None, 'type': 'file'}`. Clearly it returns an `int`, whereas the type annotation of `_hash_file` says it should return a string. Ultimately that int becomes `hash_value` and `hash_info.value` in `hash_file`, which causes the error when it tries to use it as a string.

Thoughts:

1. The fact that `HTTPFileSystem.checksum` in `fsspec` doesn't have a more specialised implementation seems bad, but I suppose that's harder to change?
2. Otherwise, `HTTP[S]FileSystem.checksum` in `dvc_objects` should probably use the ETag/Content-MD5 headers so that `dvc_data` doesn't have to.
3. Anything that falls back to `AbstractFileSystem.checksum` in `fsspec` seems potentially buggy. Obviously the first problem is that it returns an int which needs to be converted to a string. But besides that, the file contents at the same URL could easily change while the checksum stays the same.
4. Maybe this issue should be moved to `dvc_data` or `dvc_objects`?
5. In general, when there's nothing like ETag to give a reliable checksum, would it be best to just hash the file contents directly?

**Comment by danstowell** [comment]
I think I'm hitting this bug (newcomer here, hi) in dvc 2.12.0 (on ubuntu with pipx). In case it's useful, here's my reproducer:

```
git init
dvc init
dvc import-url "http://archive.org/compress/freefield1010/formats=ZIP&file=/freefield1010.zip" raw
```

with this output:

```
Importing 'http://archive.org/compress/freefield1010/formats=ZIP&file=/freefield1010.zip' -> 'raw'
ERROR: unexpected error - argument of type 'int' is not iterable
```

**Comment by alexmojaki** [comment]
Yes, that's the same bug. I get the same traceback. In this case there is a content length header, but no etag/md5.

**Comment by danstowell** [comment]
I agree it's a duplicate. I recommend editing the title of #5560 so it's clear what the error message and/or core problem is. Thanks!
