### ISSUE TITLE
add: Path does not overlap with base path

### ISSUE THREAD

**Issue by cubrink** [iterative/dvc#6215]
## Description

Using `dvc add` on Windows can produce the error 

```
ERROR: Path: C:\Users\my_user\Desktop\DVC-2.4-TEST does not overlap with base path: C:\Users\my_user\Desktop\dvc-2.4-test
```

I believe this is because paths in Windows are case insensitive (note the difference in case between `DVC-2.4-TEST` and `dvc-2.4-test`)

### Reproduce

```
mkdir my_test
cd MY_TEST
git init
dvc init
```

Then, move data into the project folder.

```
dvc add mnist --verbose
```

Which outputs

```console
2021-06-23 08:22:44,410 DEBUG: Check for update is enabled.
2021-06-23 08:22:44,491 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-06-23 08:22:44,536 DEBUG: Spawned '['daemon', '-q', 'updater']'
Adding...
2021-06-23 08:22:44,558 ERROR: Path: C:\Users\my_user\Desktop\MY_TEST does not overlap with base path: C:\Users\my_user\Desktop\my_test
------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\my_user\anaconda3\envs\dvc-2.4\lib\site-packages\dvc\command\add.py", line 21, in run
    self.repo.add(
  File "c:\users\my_user\anaconda3\envs\dvc-2.4\lib\site-packages\dvc\repo\__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "c:\users\my_user\anaconda3\envs\dvc-2.4\lib\site-packages\dvc\repo\scm_context.py", line 14, in run
    return method(repo, *args, **kw)
  File "c:\users\my_user\anaconda3\envs\dvc-2.4\lib\site-packages\dvc\repo\add.py", line 92, in add
    stages = _create_stages(
  File "c:\users\my_user\anaconda3\envs\dvc-2.4\lib\site-packages\dvc\repo\add.py", line 250, in _create_stages
    path, wdir, out = resolve_paths(
  File "c:\users\my_user\anaconda3\envs\dvc-2.4\lib\site-packages\dvc\utils\__init__.py", line 386, in resolve_paths
    elif contains_symlink_up_to(dirname, repo.root_dir) or (
  File "c:\users\my_user\anaconda3\envs\dvc-2.4\lib\site-packages\dvc\utils\fs.py", line 81, in contains_symlink_up_to
    raise BasePathNotInCheckedPathException(path, base_path)
dvc.utils.fs.BasePathNotInCheckedPathException: Path: C:\Users\my_user\Desktop\MY_TEST does not overlap with base path: C:\Users\my_user\Desktop\my_test
------------------------------------------------------------
2021-06-23 08:22:44,563 DEBUG: Analytics is enabled.
2021-06-23 08:22:44,565 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\my_user\\AppData\\Local\\Temp\\tmpgejvwwr6']'
2021-06-23 08:22:44,610 
```

### Expected

```
dvc add mnist
```

Which would output

```
100% Add|█████████████████████████████████████████████████████████████████████████████████████|1/1 [00:00,  1.76file/s]

To track the changes with git, run:

        git add mnist.dvc .gitignore
```

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.4.0+b7c6df
---------------------------------
Platform: Python 3.8.10 on Windows-10-10.0.19041-SP0
Supports: http, https
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: local
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Additional Information (if any):**

This error does not happen if you do `cd my_test` instead of `cd MY_TEST`, or in general, if you specify the path with exactly the same case as the true file path.

**Comment by pmrowla** [comment]
in `dvc.utils.fs.contains_symlink_up_to()` we do a `if base_path in path` substring check without normalizing case for either path, which will fail on Windows in this case
