### ISSUE TITLE
`AuthorizationPermissionMismatch` error when using az cli logged in identity

### ISSUE THREAD

**Issue by meierale** [iterative/dvc#6318]
# Bug Report

## Description

dvc fails to authenticate when using the currently logged in identity from azure cli with the Error 
```console
ERROR: unexpected error - Operation returned an invalid status 'This request is not authorized to perform this operation using this permission.'
ErrorCode:AuthorizationPermissionMismatch
```

### Reproduce

Example:

0. have a working setup with azure blob storage and for example `connection_string` or `account_key`
1. clear local dvc cache (e.g. `rm -rf .dvc/cache`)
2. remove some of the large file (e.g. `rm data.xml`)
3. adjust .dvc/config so it (only) contains the following parameters in the remote config section
```console
['remote "dvcdemo"']
    url = azure://containername/foldername
    account_name = nameofyourstorageaccount
```
4. try a dvc pull

### Expected

Authorization with the currently logged in user (identity) of az cli should work without errors.

### Environment information

**Output of `dvc doctor`:**

```console
 ➜ dvc doctor
DVC version: 2.5.4 (pip)
---------------------------------
Platform: Python 3.9.5 on macOS-10.15.7-x86_64-i386-64bit
Supports:
	azure (adlfs = 0.7.1, knack = 0.8.2, azure-identity = 1.6.0),
	gdrive (pydrive2 = 1.8.3),
	http (requests = 2.25.1),
	https (requests = 2.25.1)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5
Caches: local
Remotes: azure
Workspace directory: apfs on /dev/disk1s5
Repo: dvc, git
```

**Additional Information (if any):**

This is the output of `dvc pull -v`:

```console
 ➜ dvc pull -v
2021-07-14 18:32:44,263 DEBUG: Check for update is enabled.
2021-07-14 18:32:45,068 DEBUG: Preparing to download data from 'azure://containername/foldername'
2021-07-14 18:32:45,068 DEBUG: Preparing to collect status from azure://containername/foldername
2021-07-14 18:32:45,068 DEBUG: Collecting information from local cache...
2021-07-14 18:32:45,070 DEBUG: Collecting information from remote cache...
2021-07-14 18:32:45,070 DEBUG: Matched '0' indexed hashes
2021-07-14 18:32:45,070 DEBUG: Querying 1 hashes via object_exists
2021-07-14 18:32:51,516 ERROR: unexpected error - Operation returned an invalid status 'This request is not authorized to perform this operation using this permission.'
ErrorCode:AuthorizationPermissionMismatch
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/output.py", line 804, in get_dir_cache
    objects.check(self.odb, obj)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/objects/__init__.py", line 45, in check
    odb.check(obj.hash_info)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/objects/db/base.py", line 152, in check
    obj.check(self, check_hash=check_hash)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/objects/file.py", line 71, in check
    actual = get_file_hash(
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/objects/stage.py", line 53, in get_file_hash
    hash_info = _get_file_hash(path_info, fs, name)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/objects/stage.py", line 28, in _get_file_hash
    info = fs.info(path_info)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/fs/local.py", line 157, in info
    st = os.stat(path_info)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/myusername/path/to/project/.dvc/cache/20/b786b6e6f80e2b3fcf17827ad18597.dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/command/base.py", line 50, in do_run
    return self.run()
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/command/data_sync.py", line 30, in run
    stats = self.repo.pull(
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/repo/pull.py", line 29, in pull
    processed_files_count = self.fetch(
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/repo/fetch.py", line 44, in fetch
    used = self.used_objs(
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/repo/__init__.py", line 404, in used_objs
    for odb, objs in stage.get_used_objs(
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/stage/__init__.py", line 646, in get_used_objs
    for odb, objs in out.get_used_objs(*args, **kwargs).items():
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/output.py", line 875, in get_used_objs
    return self.collect_used_dir_cache(**kwargs)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/output.py", line 821, in collect_used_dir_cache
    self.get_dir_cache(jobs=jobs, remote=remote)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/output.py", line 806, in get_dir_cache
    self.repo.cloud.pull([obj], show_checksums=False, **kwargs)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/data_cloud.py", line 105, in pull
    return remote_obj.pull(
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/remote/base.py", line 57, in wrapper
    return f(obj, *args, **kwargs)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/remote/base.py", line 517, in pull
    ret = self._process(
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/remote/base.py", line 351, in _process
    dir_status, file_status, dir_contents = self._status(
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/remote/base.py", line 195, in _status
    self.hashes_exist(
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/remote/base.py", line 145, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/objects/db/base.py", line 438, in hashes_exist
    remote_hashes = self.list_hashes_exists(hashes, jobs, name)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/objects/db/base.py", line 389, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/objects/db/base.py", line 380, in exists_with_progress
    ret = self.fs.exists(path_info)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/dvc/fs/fsspec_wrapper.py", line 92, in exists
    return self.fs.exists(self._with_bucket(path_info))
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/adlfs/spec.py", line 1259, in exists
    return sync(self.loop, self._exists, path)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/fsspec/asyn.py", line 69, in sync
    raise result[0]
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/adlfs/spec.py", line 1278, in _exists
    exists = await bc.exists()
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/azure/core/tracing/decorator_async.py", line 74, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 485, in exists
    process_storage_error(error)
  File "/Users/myusername/.virtualenvs/dvc/lib/python3.9/site-packages/azure/storage/blob/_shared/response_handlers.py", line 147, in process_storage_error
    raise error
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'This request is not authorized to perform this operation using this permission.'
ErrorCode:AuthorizationPermissionMismatch
------------------------------------------------------------
2021-07-14 18:32:51,592 DEBUG: Version info for developers:
DVC version: 2.5.4 (pip)
---------------------------------
Platform: Python 3.9.5 on macOS-10.15.7-x86_64-i386-64bit
Supports:
	azure (adlfs = 0.7.1, knack = 0.8.2, azure-identity = 1.6.0),
	gdrive (pydrive2 = 1.8.3),
	http (requests = 2.25.1),
	https (requests = 2.25.1)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5
Caches: local
Remotes: azure
Workspace directory: apfs on /dev/disk1s5
Repo: dvc, git
```

**Comment by meierale** [comment]
Update:
I locally debugged dvc and also enabled the DefaultCredential loggings just to check what azure is reporting. It seems to me as if dvc is indeed correctly trying to use the DefaultCredential from the az cli. 

Here's the output if I am **logged out of az cli**:
```console
EnvironmentCredential.get_token failed: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
ImdsCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
ManagedIdentityCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
SharedTokenCacheCredential.get_token failed: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
VisualStudioCodeCredential.get_token failed: Failed to get Azure user details from Visual Studio Code.
AzureCliCredential.get_token failed: Please run 'az login' to set up an account
AzurePowerShellCredential.get_token failed: Az.Account module >= 2.2.0 is not installed
ERROR: unexpected error - DefaultAzureCredential failed to retrieve a token from the included credentials.                                                                            
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
        SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
        VisualStudioCodeCredential: Failed to get Azure user details from Visual Studio Code.
        AzureCliCredential: Please run 'az login' to set up an account
        AzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed
```

Such an error makes sense, as I am not logged in. However.. this is the error when I am **logged in to az cli**:
```console
EnvironmentCredential.get_token failed: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
ImdsCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
ManagedIdentityCredential.get_token failed: ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
SharedTokenCacheCredential.get_token failed: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
VisualStudioCodeCredential.get_token failed: Failed to get Azure user details from Visual Studio Code.
ERROR: unexpected error - This request is not authorized to perform this operation using this permission.                                                                             
RequestId:00002c46-501e-00a4-4090-79f414000000
Time:2021-07-15T15:46:00.2697996Z
ErrorCode:AuthorizationPermissionMismatch
Error:None
```

So both time the DefaultAzureCredential tries to get credentials as specified by Microsoft. In the second case it obviously is also able to get my credentials from az cli... but somehow these lead to the `AuthorizationPermissionMismatch`.

Since I am Owner of the subscription in which I am trying to access the storage account, this seems to be a bug on the Azure side?? (I'll open a ticket there as well)

**Comment by meierale** [comment]
Never mind - this was an issue unrelated to dvc.

**Comment by skshetry** [comment]
@meierale, what was the issue then? It would be great if you could briefly explain what the issue was and how you resolved it, in case someone happens to reach here in the future.
