### ISSUE TITLE
Proposal: S3 Remote should respect AWS_PROFILE env var if no profile provided in DVC config

### ISSUE THREAD

**Issue by diesal11** [iterative/dvc#6336]
I believe that the DVC CLI should utilise the `AWS_PROFILE` env var when a profile is not provided for a remote 

For example, after setting the AWS_PROFILE: 
```
$ export AWS_PROFILE=someprofile
```

The following command works:
```
aws s3 ls s3://mybucket
```

But this command does not:
```
dvc pull
```

Similarly, it's common to set a profile for a one off command:
```
AWS_PROFILE=someprofile aws s3 ls s3://mybucket
```

DVC should be invokable in a similar way:
```
AWS_PROFILE=someprofile dvc fetch
```

It's worth noting that DVC already has some implicit behaviour when no profile is provided, it will default to the profile named `default` which matches the AWS CLI behaviour.

I propose that at this point, DVC should check whether `AWS_PROFILE` env var is set and use that as the Profile name. If AWS_PROFILE is unset or blank, then `default` would be used

This means that any aws profiles explicitly set in the DVC config will be respected before using the `AWS_PROFILE` env var. 

Happy to implement this one but wanted to get feedback on it before writing any code

**Comment by efiop** [comment]
@diesal11 Hi. Could you show the error you were getting with `dvc pull`?

**Comment by diesal11** [comment]
This error is presented if there is no "default" profile in ~/.aws/credentials. If i set the correct profile in `.dvc/config` then `dvc pull` works correctly.

I'm not suggesting the current functionality is broken, just some extra functionality so that `AWS_PROFILE` is respected in the same way as the AWS CLI.

<img width="1234" alt="Screen Shot 2021-07-21 at 11 33 17 am" src="https://user-images.githubusercontent.com/4567380/126419000-27a682aa-beb4-419f-add1-ceec7407092f.png">

**Comment by pmrowla** [comment]
@diesal11 it sounds like there is some other issue going on, `AWS_PROFILE` should already be respected in DVC

can you post the full error log from `dvc pull -v`

**Comment by diesal11** [comment]
```sh
$ AWS_PROFILE=cai-prod dvc pull -v

2021-07-21 14:44:24,568 DEBUG: Check for update is enabled.
2021-07-21 14:44:24,625 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-07-21 14:44:24,626 DEBUG: Spawned '['daemon', '-q', 'updater']'
2021-07-21 14:44:25,158 DEBUG: Preparing to download data from 's3://cai-dvc-store'
2021-07-21 14:44:25,158 DEBUG: Preparing to collect status from s3://cai-dvc-store
2021-07-21 14:44:25,158 DEBUG: Collecting information from local cache...
2021-07-21 14:44:25,160 DEBUG: Collecting information from remote cache...
2021-07-21 14:44:25,160 DEBUG: Matched '0' indexed hashes
2021-07-21 14:44:25,160 DEBUG: Querying 1 hashes via object_exists
2021-07-21 14:44:35,567 ERROR: unexpected error - Cannot connect to host s3-accelerate.amazonaws.com:443 ssl:default [nodename nor servname provided, or not known]: [Errno 8] nodename nor servname provided, or not known
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/command/base.py", line 50, in do_run
    return self.run()
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/command/data_sync.py", line 30, in run
    stats = self.repo.pull(
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/repo/pull.py", line 29, in pull
    processed_files_count = self.fetch(
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/repo/fetch.py", line 44, in fetch
    used = self.used_objs(
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/repo/__init__.py", line 404, in used_objs
    for odb, objs in stage.get_used_objs(
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/stage/__init__.py", line 633, in get_used_objs
    for odb, objs in out.get_used_objs(*args, **kwargs).items():
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/output.py", line 875, in get_used_objs
    return self.collect_used_dir_cache(**kwargs)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/output.py", line 821, in collect_used_dir_cache
    self.get_dir_cache(jobs=jobs, remote=remote)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/output.py", line 806, in get_dir_cache
    self.repo.cloud.pull([obj], show_checksums=False, **kwargs)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/data_cloud.py", line 105, in pull
    return remote_obj.pull(
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/remote/base.py", line 57, in wrapper
    return f(obj, *args, **kwargs)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/remote/base.py", line 517, in pull
    ret = self._process(
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/remote/base.py", line 351, in _process
    dir_status, file_status, dir_contents = self._status(
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/remote/base.py", line 195, in _status
    self.hashes_exist(
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/remote/base.py", line 145, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/objects/db/base.py", line 438, in hashes_exist
    remote_hashes = self.list_hashes_exists(hashes, jobs, name)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/objects/db/base.py", line 389, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/objects/db/base.py", line 380, in exists_with_progress
    ret = self.fs.exists(path_info)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/dvc/fs/fsspec_wrapper.py", line 92, in exists
    return self.fs.exists(self._with_bucket(path_info))
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/fsspec/asyn.py", line 87, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/fsspec/asyn.py", line 68, in sync
    raise result[0]
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/fsspec/asyn.py", line 24, in _runner
    result[0] = await coro
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/s3fs/core.py", line 802, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/s3fs/core.py", line 1057, in _info
    out = await self._simple_info(path)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/s3fs/core.py", line 970, in _simple_info
    out = await self._call_s3(
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/s3fs/core.py", line 265, in _call_s3
    raise translate_boto_error(err)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/s3fs/core.py", line 246, in _call_s3
    out = await method(**additional_kwargs)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/aiobotocore/client.py", line 140, in _make_api_call
    http, parsed_response = await self._make_request(
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/aiobotocore/client.py", line 160, in _make_request
    return await self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 89, in _send_request
    while await self._needs_retry(attempts, operation_model,
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 197, in _needs_retry
    responses = await self._event_emitter.emit(
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/aiobotocore/hooks.py", line 29, in _emit
    response = handler(**kwargs)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/botocore/retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 156, in _do_get_response
    http_response = await self._send(request)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 241, in _send
    resp = await self.http_session.request(
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/Cellar/dvc/2.5.0/libexec/lib/python3.9/site-packages/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host s3-accelerate.amazonaws.com:443 ssl:default [nodename nor servname provided, or not known]
------------------------------------------------------------
2021-07-21 14:44:36,476 DEBUG: Version info for developers:
DVC version: 2.5.0 (brew)
---------------------------------
Platform: Python 3.9.6 on macOS-11.3-x86_64-i386-64bit
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-07-21 14:44:36,478 DEBUG: Analytics is enabled.
2021-07-21 14:44:36,479 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/sn/5kmdgz1x30g0rl994jcmtrl40000gn/T/tmpb42_ah2c']'
2021-07-21 14:44:36,482 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/sn/5kmdgz1x30g0rl994jcmtrl40000gn/T/tmpb42_ah2c']'
```

However, if i set `profile = cai-prod` inside `.dvc/config` it works:

```sh
$ dvc pull -v

2021-07-21 14:47:07,025 DEBUG: Check for update is enabled.
2021-07-21 14:47:07,565 DEBUG: Preparing to download data from 's3://cai-dvc-store'
2021-07-21 14:47:07,566 DEBUG: Preparing to collect status from s3://cai-dvc-store
2021-07-21 14:47:07,566 DEBUG: Collecting information from local cache...
2021-07-21 14:47:07,566 DEBUG: Collecting information from remote cache...
2021-07-21 14:47:07,567 DEBUG: Matched '0' indexed hashes
2021-07-21 14:47:07,567 DEBUG: Querying 1 hashes via object_exists
2021-07-21 14:47:07,870 DEBUG: Downloading 's3://cai-dvc-store/80/17c60d6cf902bf5f49af35f48819df.dir' to '.dvc/cache/80/17c60d6cf902bf5f49af35f48819df.dir'
2021-07-21 14:47:08,288 DEBUG: state save (50320361, 1626844628283556096, 158) 8017c60d6cf902bf5f49af35f48819df.dir
2021-07-21 14:47:08,298 DEBUG: Preparing to download data from 's3://cai-dvc-store'
2021-07-21 14:47:08,298 DEBUG: Preparing to collect status from s3://cai-dvc-store
2021-07-21 14:47:08,298 DEBUG: Collecting information from local cache...
2021-07-21 14:47:08,299 DEBUG: Collecting information from remote cache...
2021-07-21 14:47:08,299 DEBUG: Querying 1 hashes via object_exists
2021-07-21 14:47:08,516 DEBUG: Indexing new .dir '8017c60d6cf902bf5f49af35f48819df.dir' with '2' nested files
2021-07-21 14:47:08,521 DEBUG: Downloading 's3://cai-dvc-store/5d/5cba937c06fa3f41ba38fe9e26f235' to '.dvc/cache/5d/5cba937c06fa3f41ba38fe9e26f235'
2021-07-21 14:47:08,522 DEBUG: Downloading 's3://cai-dvc-store/11/a1af865f639f1c33eb8d4e68b07f7f' to '.dvc/cache/11/a1af865f639f1c33eb8d4e68b07f7f'
2021-07-21 14:47:09,584 DEBUG: state save (50320361, 1626844628283556096, 158) 8017c60d6cf902bf5f49af35f48819df.dir
2021-07-21 14:47:09,584 DEBUG: state save (50320368, 1626844629580829952, 4767825) 5d5cba937c06fa3f41ba38fe9e26f235
2021-07-21 14:47:09,585 DEBUG: state save (50320369, 1626844629473097472, 1978071) 11a1af865f639f1c33eb8d4e68b07f7f
2021-07-21 14:47:09,609 DEBUG: state save (49653793, 1625750939486793216, 1978071) 11a1af865f639f1c33eb8d4e68b07f7f
2021-07-21 14:47:09,617 DEBUG: state save (49653792, 1625750939286681088, 4767825) 5d5cba937c06fa3f41ba38fe9e26f235
2021-07-21 14:47:09,629 DEBUG: state save (49653791, 1f5074cdc313e148c715b930edb00d9c, 6745896) 8017c60d6cf902bf5f49af35f48819df.dir
2 files fetched
2021-07-21 14:47:09,633 DEBUG: Analytics is enabled.
2021-07-21 14:47:09,756 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/sn/5kmdgz1x30g0rl994jcmtrl40000gn/T/tmpkxpl4xxq']'
2021-07-21 14:47:09,759 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/sn/5kmdgz1x30g0rl994jcmtrl40000gn/T/tmpkxpl4xxq']'
```

**Comment by pmrowla** [comment]
And just to double check, you do not have any of the other environment variables listed here set, correct? https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#id1

**Comment by diesal11** [comment]
Yep, the only AWS env var set is `AWS_PROFILE` :)

**Comment by efiop** [comment]
Closing as stale.

**Comment by diesal11** [comment]
Don't know if it's fair to close this as "stale" as i was waiting a response from you guys.

Regardless, this issue is still not resolved. i did some further digging and the issue here seems to be that the `AWS_PROFILE` env var is never read. I can see an [older commit that references this](https://github.com/iterative/dvc/commit/ddb91a152bc27ae9588a0dd7d08212fa33a3b1f8). But it looks like the S3 FS has been refactored since and this functionality must have been lost in that process?

**Comment by pmrowla** [comment]
`AWS_PROFILE` is already handled and supported in the underlying botocore library used to interact with AWS (and the env var does not need to be read at the DVC source level).

Do you have `use_accelerate_endpoint` set in your AWS config? It's possible that your problem is related to https://github.com/iterative/dvc/issues/6588

Setting `profile = ...` in your DVC remote config (instead of using `AWS_PROFILE`) does change how and where the profile is loaded (which may be why your workaround works, and is potentially what causes the problem in #6588)

**Comment by efiop** [comment]
> It's worth noting that DVC already has some implicit behaviour when no profile is provided, it will default to the profile named default which matches the AWS CLI behaviour.

> I propose that at this point, DVC should check whether AWS_PROFILE env var is set and use that as the Profile name. If AWS_PROFILE is unset or blank, then default would be used

@isidentical could you please double check if the current behaviour is intended?

**Comment by efiop** [comment]
Looks like it is explained by @pmrowla and we are not getting any new complains, so closing for now
