### ISSUE TITLE
Unable to dvc push to Google Cloud Storage bucket

### ISSUE THREAD

**Issue by Mason-McGough** [iterative/dvc#6345]
Was following the [Getting Started - Data and Model Versioning](https://dvc.org/doc/start/data-and-model-versioning) guide and got hung up on the [Storage and Sharing](https://dvc.org/doc/start/data-and-model-versioning#storing-and-sharing) section.
Using `dvc push` results in the following:

```
  0% Querying cache in gs://<my_gs_url>|                                                                                                                                   |0/1 [00:00<?,     ?file/s]_request non-retriable exception: Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object., 401
Traceback (most recent call last):
  File "/home/bricklayer/anaconda3/envs/dvc/lib/python3.9/site-packages/gcsfs/retry.py", line 110, in retry_request
    return await func(*args, **kwargs)
  File "/home/bricklayer/anaconda3/envs/dvc/lib/python3.9/site-packages/gcsfs/core.py", line 332, in _request
    validate_response(status, contents, path)
  File "/home/bricklayer/anaconda3/envs/dvc/lib/python3.9/site-packages/gcsfs/retry.py", line 97, in validate_response
    raise HttpError(error)
gcsfs.retry.HttpError: Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object., 401
ERROR: unexpected error - Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object., 401                                                                                       

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

I am trying to push to a Google Cloud Storage bucket. I used `gcloud auth login` to login previously and am able to use commands like `gsutil ls gs://<my_gs_url>` and `gsutil cp gs://<my_gs_url>` successfully.

`dvc remote -v list` gives the following:

```
storage	gs://<my_gs_url>
```

Did I miss some instructions or is this a bug?

**Comment by efiop** [comment]
@Mason-McGough Hi :) Why did you close the issue? Did you find a way to resolve it?

**Comment by Mason-McGough** [comment]
I was able to fix the issue with [this solution](https://stackoverflow.com/a/60429081/7195376).
