### ISSUE TITLE
error: Data doesn't add to the DVC

### ISSUE THREAD

**Issue by DmitriyKhodykin** [iterative/dvc#6397]
# Bug Report

Issue name

`Data doesn't add to the DVC`

## Description

ERROR: unexpected error - DLL load failed while importing win32file:

### Reproduce

Step list of how to reproduce the bug

1. dvc init
2. Copy data.parquet to the directory
3. dvc add data.parquet

### Expected

https://www.youtube.com/watch?v=kLKBcPonMYw?T=01m28s

### Environment information

dvc
pandas
pyarrow
pyyaml
requests

catboost
lightgbm
sklearn
scipy

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.5.4 (pip)
---------------------------------
Platform: Python 3.8.3 on Windows-10-10.0.18362-SP0
Supports:
        hdfs (pyarrow = 5.0.0),
        http (requests = 2.26.0),
        https (requests = 2.26.0)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Comment by pmrowla** [comment]
@DmitriyKhodykin Is your python installation from a conda environment?

If so could you please run
```
conda install -c conda-forge pywin32
```
and then retry `dvc add`?

**Comment by DmitriyKhodykin** [comment]
@pmrowla no, python venv. 
pip install pywin32 returns: 
Requirement already satisfied: pywin32 in c:\users\d.hodykin\pycharmprojects\agrous\venv\lib\site-packages (301)

**Comment by pmrowla** [comment]
Can you run `dvc add -v` and post the full error traceback

**Comment by DmitriyKhodykin** [comment]
@pmrowla 
dvc add -v data/data.parquet
2021-08-09 09:44:00,121 DEBUG: Check for update is enabled.
2021-08-09 09:44:00,266 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-08-09 09:44:00,421 DEBUG: Spawned '['daemon', '-q', 'updater']'
2021-08-09 09:44:00,495 ERROR: unexpected error - DLL load failed while importing win32file: Не найдена указанная процедура.
------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\d.hodykin\PycharmProjects\AgroUS\venv\lib\site-packages\dvc\main.py", line 55, in main
    ret = cmd.do_run()
  File "C:\Users\d.hodykin\PycharmProjects\AgroUS\venv\lib\site-packages\dvc\command\base.py", line 50, in do_run
    return self.run()
  File "C:\Users\d.hodykin\PycharmProjects\AgroUS\venv\lib\site-packages\dvc\command\add.py", line 21, in run
    self.repo.add(
  File "C:\Users\d.hodykin\PycharmProjects\AgroUS\venv\lib\site-packages\dvc\utils\collections.py", line 128, in inner
    result = func(*ba.args, **ba.kwargs)
  File "C:\Users\d.hodykin\PycharmProjects\AgroUS\venv\lib\site-packages\dvc\repo\__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "C:\Users\d.hodykin\PycharmProjects\AgroUS\venv\lib\site-packages\dvc\repo\scm_context.py", line 14, in run
    return method(repo, *args, **kw)
  File "C:\Users\d.hodykin\PycharmProjects\AgroUS\venv\lib\site-packages\dvc\repo\add.py", line 164, in add
    stages = list(ui.progress(stages_it, desc=desc, unit="file"))
  File "C:\Users\d.hodykin\PycharmProjects\AgroUS\venv\lib\site-packages\tqdm\std.py", line 1185, in __iter__
    for obj in iterable:
  File "C:\Users\d.hodykin\PycharmProjects\AgroUS\venv\lib\site-packages\dvc\repo\add.py", line 250, in create_stages
    path, wdir, out = resolve_paths(
  File "C:\Users\d.hodykin\PycharmProjects\AgroUS\venv\lib\site-packages\dvc\utils\__init__.py", line 386, in resolve_paths
    elif contains_symlink_up_to(dirname, repo.root_dir) or (
  File "C:\Users\d.hodykin\PycharmProjects\AgroUS\venv\lib\site-packages\dvc\utils\fs.py", line 89, in contains_symlink_up_to
    if System.is_symlink(path):
  File "C:\Users\d.hodykin\PycharmProjects\AgroUS\venv\lib\site-packages\dvc\system.py", line 203, in is_symlink
    info = System._getdirinfo(path)
  File "C:\Users\d.hodykin\PycharmProjects\AgroUS\venv\lib\site-packages\dvc\system.py", line 124, in _getdirinfo
    from win32file import (  # pylint: disable=import-error
ImportError: DLL load failed while importing win32file: Не найдена указанная процедура.
------------------------------------------------------------
2021-08-09 09:44:04,567 DEBUG: Version info for developers:
DVC version: 2.5.4 (pip)
---------------------------------
Platform: Python 3.8.3 on Windows-10-10.0.18362-SP0
Supports:
        hdfs (pyarrow = 5.0.0),
        http (requests = 2.26.0),
        https (requests = 2.26.0)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git

**Comment by pmrowla** [comment]
Was this venv configured through pycharm? What is your python interpreter set to?

**Comment by DmitriyKhodykin** [comment]
@pmrowla 
![image](https://user-images.githubusercontent.com/49707091/128676280-053efc5a-b14c-47fa-9575-13756b694330.png)

**Comment by pmrowla** [comment]
Where does your base (system) python come from? (The python installation used to create the virtualenv in the first place)

i.e. the python.org installer, windows store, conda, chocolatey, etc

**Comment by DmitriyKhodykin** [comment]
$ where python
C:\Users\name\PycharmProjects\AgroUS\venv\Scripts\python.exe
C:\ProgramData\Anaconda3\python.exe
C:\Users\name\AppData\Local\Microsoft\WindowsApps\python.exe

**Comment by pmrowla** [comment]
Can you please check in Pycharm which one is configured as your default system python intepreter? (Not the project specific venv python, the one which pycharm would use to make the venv in the first place). https://www.jetbrains.com/help/pycharm/configuring-local-python-interpreters.html

If it is the conda python (`C:\ProgramData\Anaconda3\python.exe`) you probably need to run

```
conda install -c conda-forge pywin32
```

**Comment by DmitriyKhodykin** [comment]
![image](https://user-images.githubusercontent.com/49707091/129571210-1d13f691-0743-4413-8d72-fce108544028.png)

**Comment by DmitriyKhodykin** [comment]
$conda list
![image](https://user-images.githubusercontent.com/49707091/129571569-762c8fb0-0618-40f5-8415-1c820682996e.png)

**Comment by DmitriyKhodykin** [comment]
I've completed 'conda install',
but it doesn't work

**Comment by DmitriyKhodykin** [comment]
Although I see that the version in conda (227) and in venv (310) have different numbers.
