### ISSUE TITLE
problems using a lower DVC version [0.9.4]

### ISSUE THREAD

**Issue by lilianabrandao** [iterative/dvc#6420]
I need to install an older version of DVC, namely 0.9.4, in a Python virtual environment.

I used the command:

`pip install dvc==0.9.4`

Everything seemed to work fine. However, when I try to run a ` dvc pull `command, I get the following error:

```
Traceback (most recent call last):
  File "c:\users\lbrandao\anaconda3\envs\my_env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lbrandao\anaconda3\envs\my_env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lbrandao\anaconda3\envs\my_env\Scripts\dvc.exe\__main__.py", line 4, in <module>
  File "c:\users\lbrandao\anaconda3\envs\my_env\lib\site-packages\dvc\main.py", line 2, in <module>
    from dvc.cli import parse_args
  File "c:\users\lbrandao\anaconda3\envs\my_env\lib\site-packages\dvc\cli.py", line 8, in <module>
    from dvc.command.init import CmdInit
  File "c:\users\lbrandao\anaconda3\envs\my_env\lib\site-packages\dvc\command\init.py", line 1, in <module>
    from dvc.project import Project
  File "c:\users\lbrandao\anaconda3\envs\my_env\lib\site-packages\dvc\project.py", line 15, in <module>
    from dvc.cloud.data_cloud import DataCloud
  File "c:\users\lbrandao\anaconda3\envs\my_env\lib\site-packages\dvc\cloud\data_cloud.py", line 11, in <module>
    from dvc.cloud.gcp import DataCloudGCP
  File "c:\users\lbrandao\anaconda3\envs\my_env\lib\site-packages\dvc\cloud\gcp.py", line 4, in <module>
    from google.cloud import storage as gc
ModuleNotFoundError: No module named 'google.cloud'
```

When I print the dvc version, I see:

`0.9.4+6bb66e.mod`

Can anyone please help? Thanks.

**Comment by lilianabrandao** [comment]
I was able to overcome the previous issue with:

`pip install --upgrade google-cloud-storage`

Nevertheless, when I run `dvc pull`, I now get the following error:

`Initialization error: 'charmap' codec can't decode byte 0x81 in position 3685: character maps to <undefined>`

**Comment by isidentical** [comment]
Can you share the output of `dvc doctor`? Also I'd advise trying a newer version of DVC, since `0.9.4` is a very old one.

**Comment by efiop** [comment]
closing as stale
