### ISSUE TITLE
Unexpected error - Forbidden: An error occurred (403) when calling the HeadObject operation: Forbidden

### ISSUE THREAD

**Issue by kareemjano** [iterative/dvc#6433]
# Bug Report

## Issue name

When querying hashes by traverse operation executes, (ex. 'dvc status -c' or 'dvc push'), having access to only a folder in the s3 bucket, and files that are more than ~500MB are added, I get the following error "Unexpected error - Forbidden: An error occurred (403) when calling the HeadObject operation: Forbidden".

## Description
It seems that the behavior of s3fs is changes on different operating systems (or file systems) and when files are added with size more than 500MB. 

I have the following configuration file:

[core]
    remote = test-s
[cache]
    type = symlink
['remote "test-s"']
    url = s3://root/dvc
    endpointurl = https://some.s3.endpoint
    region = us-east-1
    ssl_verify = false

I have access only to s3://root/dvc but not to root. When calling 'dvc statuc -c' or 'dvc push', the querying by travers operation is happening recursively. So it is also trying to access s3://root which i dont have access to. This happens only on Linux and not on Windows.

I was able to temporary avoid the error by changing body of the PermissionError exception in  `async def _info` in s3fs/core.py by setting `out = None`. Nevertheless, I am not sure if this is an excepted solution.

### Reproduce

1. dvc init
2. Copy file.ext to the directory (file.ext size should be larger than ~500MB)
3. dvc add file.ext
4. dvc status -c

### Expected
The expected behavior would be to not try to access s3://root similar to windows.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.5.4 (pip)                                                                                  
---------------------------------                                                                         
Platform: Python 3.8.5 on Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-glibc2.10                         
Supports:                                                                                                 
        http (requests = 2.25.1),                                                                         
        https (requests = 2.25.1),                                                                        
        s3 (s3fs = 2021.6.1, boto3 = 1.17.49)                                                             
Cache types: hardlink, symlink                                                                            
Cache directory: nfs on vihsdp502.infineon.com:/temp502/tmp_share                                         
Caches: local                                                                                             
Remotes: s3, s3                                                                                           
Workspace directory: nfs on vihsdp502.infineon.com:/temp502/tmp_share                                     
Repo: dvc, git 
```

**Additional Information (if any):**
```console
$ dvc status -c -v
2021-08-16 11:27:30,736 DEBUG: Check for update is enabled.
2021-08-16 11:27:30,804 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-08-16 11:27:30,805 DEBUG: Spawned '['daemon', '-q', 'updater']'
2021-08-16 11:27:32,181 DEBUG: Preparing to collect status from s3://rddl-sensys/dvc
2021-08-16 11:27:32,182 DEBUG: Collecting information from local cache...
2021-08-16 11:27:32,939 DEBUG: Collecting information from remote cache...                                
2021-08-16 11:27:32,940 DEBUG: Querying 2 hashes via object_exists
2021-08-16 11:27:33,593 DEBUG: Matched '0' indexed hashes                                                 
Estimating size of cache in 's3://rddl-sensys/dvc'                              |0.00 [00:00,     ?file/s]
2021-08-16 11:27:33,824 DEBUG: Estimated remote size: 4096 files                                          
2021-08-16 11:27:33,824 DEBUG: Querying '2316' hashes via traverse                                        
2021-08-16 11:27:33,911 ERROR: unexpected error - Forbidden: An error occurred (403) when calling the HeadObject operation: Forbidden
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/s3fs/core.py", line 246, in _call_s3
    out = await method(**additional_kwargs)
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Unknown

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/s3fs/core.py", line 1056, in _info
    out = await self._simple_info(path)
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/s3fs/core.py", line 970, in _simple_info
    out = await self._call_s3(
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/s3fs/core.py", line 265, in _call_s3
    raise translate_boto_error(err)
PermissionError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Unknown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/s3fs/core.py", line 246, in _call_s3
    out = await method(**additional_kwargs)
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/command/base.py", line 50, in do_run
    return self.run()
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/command/status.py", line 54, in run
    st = self.repo.status(
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/repo/status.py", line 135, in status
    return _cloud_status(
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/repo/status.py", line 98, in _cloud_status
    status_info = self.cloud.status(
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/data_cloud.py", line 134, in status
    return remote_obj.status(
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/remote/base.py", line 57, in wrapper
    return f(obj, *args, **kwargs)
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/remote/base.py", line 126, in status
    dir_status, file_status, _ = self._status(
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/remote/base.py", line 195, in _status
    self.hashes_exist(
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/remote/base.py", line 145, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/objects/db/base.py", line 467, in hashes_exist
    remote_hashes = set(
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/objects/db/base.py", line 312, in list_hashes_traverse
    yield from itertools.chain.from_iterable(in_remote)
  File "/home/presence/.conda/envs/base_p38/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/home/presence/.conda/envs/base_p38/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/presence/.conda/envs/base_p38/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/home/presence/.conda/envs/base_p38/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/objects/db/base.py", line 302, in list_with_update
    return list(
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/objects/db/base.py", line 193, in list_hashes
    for path in self._list_paths(prefix, progress_callback):
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/objects/db/base.py", line 173, in _list_paths
    for file_info in self.fs.walk_files(path_info, prefix=prefix):
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/fs/fsspec_wrapper.py", line 109, in walk_files
    for file in self.find(path_info, **kwargs):
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/dvc/fs/fsspec_wrapper.py", line 179, in find
    files = self.fs.find(
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/fsspec/asyn.py", line 87, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/fsspec/asyn.py", line 68, in sync
    raise result[0]
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/fsspec/asyn.py", line 24, in _runner
    result[0] = await coro
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/s3fs/core.py", line 642, in _find
    out = [await self._info(path)]
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/s3fs/core.py", line 1060, in _info
    out = await self._version_aware_info(path, version_id)
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/s3fs/core.py", line 1003, in _version_aware_info
    out = await self._call_s3(
  File "/opt/project/dvc/.venv/lib/python3.8/site-packages/s3fs/core.py", line 265, in _call_s3
    raise translate_boto_error(err)
PermissionError: Forbidden
```

**Comment by pared** [comment]
@kareemjano sorry for such a long response time, I will try to reproduce your problem.

**Comment by pared** [comment]
I was unable to reproduce the problem. It will have to wait till we have more capacity for bugs.

**Comment by efiop** [comment]
@kareemjano Please give the latest dvc version a try and let us know if it works. Thanks!
