### ISSUE TITLE
config list fails outside repository

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#6496]
```console
$ cd "$(mktemp -d)"
$ dvc config --list -v
dvc config --list -v
core.experiments=True
core.check_update=true
core.analytics=false
2021-08-27 15:06:56,870 ERROR: unexpected error - 'repo'
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/saugat/Projects/dvc/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/Users/saugat/Projects/dvc/dvc/command/base.py", line 59, in do_run
    return self.run()
  File "/Users/saugat/Projects/dvc/dvc/command/config.py", line 48, in run
    return self._list()
  File "/Users/saugat/Projects/dvc/dvc/command/config.py", line 71, in _list
    conf = self.config.read(level)
  File "/Users/saugat/Projects/dvc/dvc/config.py", line 270, in read
    return self.load_one(level)
  File "/Users/saugat/Projects/dvc/dvc/config.py", line 188, in load_one
    conf = self._load_config(level)
  File "/Users/saugat/Projects/dvc/dvc/config.py", line 162, in _load_config
    filename = self.files[level]
KeyError: 'repo'
------------------------------------------------------------
2021-08-27 15:06:57,394 DEBUG: Version info for developers:
DVC version: 2.6.4+73811f
---------------------------------
Platform: Python 3.10.0b4 on macOS-11.5.2-x86_64-i386-64bit
Supports:
	azure (adlfs = 2021.7.1, knack = 0.8.2, azure-identity = 1.6.0),
	gdrive (pydrive2 = 1.9.1),
	gs (gcsfs = 2021.7.0),
	webhdfs (hdfs = 2.5.8),
	http (requests = 2.26.0),
	https (requests = 2.26.0),
	s3 (s3fs = 2021.8.0, boto3 = 1.17.106),
	ssh (sshfs = 2021.7.1),
	oss (ossfs = 2021.7.5),
	webdav (webdav4 = 0.9.0),
	webdavs (webdav4 = 0.9.0)

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-08-27 15:06:57,396 DEBUG: Analytics is disabled.
```

**Comment by ameyk-2409** [comment]
I have opened a draft pull request. I am unsure what tests (if any?) can be added for this issue. Please guide me for this.

**Comment by ameyk-2409** [comment]
Added a test. Pull request is ready for review.
