### ISSUE TITLE
status: raises error when missing params

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#6676]
# Bug Report
I created the stage with following command:
```console
 dvc stage add -n train \
                  -p model.conv_units \
                  -p train.epochs \
                  -d data/images \
                  -m metrics.json \
                  python3 src/train.py
```
`status` command should not fail at all and should just say that the params are missing (even if the params.yaml file is present or not).

```pytb
dvc status -v
2021-09-23 11:56:14,254 DEBUG: Lockfile '../dvc.lock' needs to be updated.
2021-09-23 11:56:14,333 DEBUG: Computed stage: '../model2.txt.dvc' md5: 'None'
2021-09-23 11:56:14,335 ERROR: Parameters 'model.conv_units, train.epochs' are missing from '../params.yaml'.
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/saugat/Projects/dvc/dvc/command/status.py", line 54, in run
    st = self.repo.status(
  File "/Users/saugat/Projects/dvc/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/saugat/Projects/dvc/dvc/repo/status.py", line 145, in status
    return _local_status(
  File "/Users/saugat/Projects/dvc/dvc/repo/status.py", line 38, in _local_status
    return _joint_status(pairs)
  File "/Users/saugat/Projects/dvc/dvc/repo/status.py", line 23, in _joint_status
    stage.status(check_updates=True, filter_info=filter_info)
  File "/Users/saugat/Projects/webdav4/env/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/saugat/Projects/dvc/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/Users/saugat/Projects/webdav4/env/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/saugat/Projects/dvc/dvc/stage/__init__.py", line 598, in status
    self._status_deps(ret)
  File "/Users/saugat/Projects/dvc/dvc/stage/__init__.py", line 614, in _status_deps
    deps_status = self._status(self.deps)
  File "/Users/saugat/Projects/dvc/dvc/stage/__init__.py", line 609, in _status
    ret.update(entry.status())
  File "/Users/saugat/Projects/dvc/dvc/dependency/param.py", line 86, in status
    return self.workspace_status()
  File "/Users/saugat/Projects/dvc/dvc/dependency/param.py", line 62, in workspace_status
    status = super().workspace_status()
  File "/Users/saugat/Projects/dvc/dvc/output.py", line 466, in workspace_status
    if self.changed_checksum():
  File "/Users/saugat/Projects/dvc/dvc/output.py", line 446, in changed_checksum
    return self.hash_info != self.get_hash()
  File "/Users/saugat/Projects/dvc/dvc/dependency/param.py", line 129, in get_hash
    raise MissingParamsError(
dvc.dependency.param.MissingParamsError: Parameters 'model.conv_units, train.epochs' are missing from '../params.yaml'.
```

**Comment by skshetry** [comment]
This seems to have been fixed at some point. Closing.
