### ISSUE TITLE
push: doesn't respect HTTP remote "method" config

### ISSUE THREAD

**Issue by tonyfm15** [iterative/dvc#6694]
# Bug Report

## Description

I configured my DVC remote as a [GitLab generic package repository](https://docs.gitlab.com/ee/user/packages/generic_packages/). Part of the configuration was setting the HTTP method to `PUT`. However, `dvc push` did not work unless I went into `fsspec/implementations/http.py` and hard-coded the `method` variable in `_put_file` to `"put"`.

### Reproduce

1. Add an HTTP remote
1. `dvc remote modify <remote> method PUT`
1. `dvc add` a data file
1. Add a breakpoint or print statement to `_put_file` in `fsspec/implementations/http.py` in order to see what HTTP method it's using (via the `method` variable)
1. `dvc push`
1. Confirm that `_put_file` is using `POST`

### Expected

`dvc push` should respect the `method` config parameter and set the HTTP method to `PUT`

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.7.4 (brew)
---------------------------------
Platform: Python 3.9.7 on macOS-11.5.1-x86_64-i386-64bit
Supports:
        azure (adlfs = 2021.9.1, knack = 0.8.2, azure-identity = 1.6.1),
        gdrive (pydrive2 = 1.9.4),
        gs (gcsfs = 2021.8.1),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
        s3 (s3fs = 2021.8.1, boto3 = 1.17.106),
        ssh (sshfs = 2021.8.1),
        webdav (webdav4 = 0.9.2),
        webdavs (webdav4 = 0.9.2)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git
```

**Additional Information (if any):**

```console
$ dvc push --verbose
dvc push --verbose
2021-09-27 18:10:15,263 DEBUG: Preparing to transfer data from '.dvc/cache' to <redacted-url>
2021-09-27 18:10:15,263 DEBUG: Preparing to collect status from <redacted-url>
2021-09-27 18:10:15,263 DEBUG: Collecting status from <redacted-url>
2021-09-27 18:10:15,263 DEBUG: Querying 1 hashes via object_exists
2021-09-27 18:10:15,788 DEBUG: Preparing to collect status from '.dvc/cache'                                           
2021-09-27 18:10:15,788 DEBUG: Collecting status from '.dvc/cache'
2021-09-27 18:10:15,936 DEBUG: Uploading '.dvc/cache/bf/f4568d018ccda02658e3a5953a2629' to <redacted-url>                                        
2021-09-27 18:10:16,065 ERROR: failed to transfer 'md5: bff4568d018ccda02658e3a5953a2629' - 415, message='Unsupported Media Type', url=URL(<redacted-url>)
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/dvc/objects/transfer.py", line 25, in wrapper
    func(path_info, *args, **kwargs)
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/dvc/objects/transfer.py", line 159, in func
    return dest.add(
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/dvc/objects/db/base.py", line 113, in add
    self._add_file(fs, path_info, cache_info, hash_info, move=move)
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/dvc/objects/db/base.py", line 89, in _add_file
    return fs.utils.transfer(
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/dvc/fs/utils.py", line 30, in transfer
    return to_fs.upload(from_info, to_info)
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/dvc/fs/base.py", line 282, in upload
    return self.put_file(
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/dvc/fs/fsspec_wrapper.py", line 137, in put_file
    self.fs.put_file(
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/fsspec/asyn.py", line 88, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/fsspec/asyn.py", line 69, in sync
    raise result[0]
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/fsspec/implementations/http.py", line 287, in _put_file
    self._raise_not_found_for_status(resp, lpath)
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/fsspec/implementations/http.py", line 214, in _raise_not_found_for_status
    response.raise_for_status()
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 415, message='Unsupported Media Type', url=URL(<redacted-url>)
------------------------------------------------------------
2021-09-27 18:10:16,068 ERROR: failed to push data to the cloud - 1 files failed to upload                             
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/dvc/repo/push.py", line 48, in push
    pushed += self.cloud.push(obj_ids, jobs, remote=remote, odb=odb)
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/dvc/data_cloud.py", line 85, in push
    return transfer(
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/dvc/objects/transfer.py", line 169, in transfer
    _do_transfer(
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/dvc/objects/transfer.py", line 115, in _do_transfer
    raise FileTransferError(total_fails)
dvc.exceptions.FileTransferError: 1 files failed to transfer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/dvc/command/data_sync.py", line 57, in run
    processed_files_count = self.repo.push(
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/Cellar/dvc/2.7.4_1/libexec/lib/python3.9/site-packages/dvc/repo/push.py", line 50, in push
    raise UploadError(exc.amount)
dvc.exceptions.UploadError: 1 files failed to upload
------------------------------------------------------------
2021-09-27 18:10:16,071 DEBUG: Analytics is enabled.
2021-09-27 18:10:16,183 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/vs/7xcms_5d0_n0gm6gy_gt80_h021ngx/T/tmpajfw4vqx']'
2021-09-27 18:10:16,184 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/vs/7xcms_5d0_n0gm6gy_gt80_h021ngx/T/tmpajfw4vqx']'
```

**Comment by pmrowla** [comment]
Looks like it's probably a regression from https://github.com/iterative/dvc/pull/6525/files

We set `upload_method` at the DVC http fs level:
https://github.com/iterative/dvc/blob/fed9f088ca40edb73819944c9a91134a9f8a64fc/dvc/fs/http.py#L94

but it doesn't get passed into the lower level fsspec http fs
