### ISSUE TITLE
`list .`: fails on added directory path (tracked dataset)

### ISSUE THREAD

**Issue by mattseddon** [iterative/dvc#6695]
# Bug Report

## Description

After adding data to a tracked dataset (directory) `dvc list . path/to/new-dir` fails.

Possible duplicate of https://github.com/iterative/dvc/issues/3776.

### Reproduce

1. Have a tracked directory. I.e `data/MNIST/raw` (tracked with `data/MNIST/raw.dvc`)
2. Add a new sub-directory to the tracked directory, e.g `extra-data`.
3. Run `dvc list . data/MNIST/raw/extra-data`
4. Command fails with `ERROR: unexpected error - ('/', 'path', 'to', 'data', 'MNIST', 'raw', 'extra-data')`

### Expected

List returns the contents of the directory.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.7.3+f3010d 
---------------------------------
Platform: Python 3.9.5 on macOS-11.5.2-x86_64-i386-64bit
Supports:
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc (subdir), git
```

same behaviour on 

```console
$ dvc doctor
DVC version: 2.7.4+058377 
---------------------------------
Platform: Python 3.9.5 on macOS-11.5.2-x86_64-i386-64bit
Supports:
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc (subdir), git
```

**Additional Information (if any):**

### Demo

https://user-images.githubusercontent.com/37993418/134999066-5003d1ff-b66c-4208-bf02-d8f64af94334.mov

#### Verbose output:

```
 dvc list . data/MNIST/raw/extra-data -v                                                              3.0.0 09:16:00
2021-09-28 09:21:54,133 ERROR: unexpected error - ('/', 'Users', 'mattseddon', 'PP', 'vscode-dvc', 'demo', 'data', 'MNIST', 'raw', 'extra-data')
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/site-packages/dvc/command/base.py", line 59, in do_run
    return self.run()
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/site-packages/dvc/command/ls/__init__.py", line 30, in run
    entries = Repo.ls(
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/site-packages/dvc/repo/ls.py", line 36, in ls
    ret = _ls(repo.repo_fs, path_info, recursive, dvc_only)
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/site-packages/dvc/repo/ls.py", line 55, in _ls
    for root, dirs, files in fs.walk(
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/site-packages/dvc/fs/repo.py", line 445, in walk
    yield from self._walk(repo_walk, dvc_walk, dvcfiles=dvcfiles)
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/site-packages/dvc/fs/repo.py", line 346, in _walk
    next(dvc_walk) if dvc_walk else (None, [], [])
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/site-packages/dvc/fs/dvc.py", line 211, in walk
    yield from self._walk(root, trie, topdown=topdown, **kwargs)
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/site-packages/dvc/fs/dvc.py", line 169, in _walk
    for key, out in trie.iteritems(prefix=root.parts):  # noqa: B301
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pygtrie.py", line 633, in iteritems
    node, _ = self._get_node(prefix)
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pygtrie.py", line 545, in _get_node
    raise KeyError(key)
KeyError: ('/', 'Users', 'mattseddon', 'PP', 'vscode-dvc', 'demo', 'data', 'MNIST', 'raw', 'extra-data')
------------------------------------------------------------
2021-09-28 09:21:54,344 DEBUG: Version info for developers:
DVC version: 2.7.3+f3010d 
---------------------------------
Platform: Python 3.9.5 on macOS-11.5.2-x86_64-i386-64bit
Supports:
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc (subdir), git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-09-28 09:21:54,346 DEBUG: Analytics is enabled.
2021-09-28 09:21:54,465 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/q_/jpcf1bld2vz9fs5n62mgqshc0000gq/T/tmpgvqjnjeb']'
2021-09-28 09:21:54,467 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/q_/jpcf1bld2vz9fs5n62mgqshc0000gq/T/tmpgvqjnjeb']'
```

`dvc list . --dvc-only -R` **returns the correct information**

```
 dvc list . --dvc-only -R                                                                   0.92540s  3.0.0 09:34:34
data/MNIST/raw/extra-data/Screen Shot 2019-11-13 at 2.34.21 pm.png
data/MNIST/raw/extra-data/Screen Shot 2019-11-13 at 2.34.22 pm.png
data/MNIST/raw/extra-data/Screen Shot 2019-11-13 at 2.34.23 pm.png
data/MNIST/raw/extra-data/Screen Shot 2019-11-13 at 2.34.24 pm.png
data/MNIST/raw/t10k-images-idx3-ubyte
data/MNIST/raw/t10k-images-idx3-ubyte.gz
data/MNIST/raw/t10k-labels-idx1-ubyte
data/MNIST/raw/t10k-labels-idx1-ubyte.gz
data/MNIST/raw/train-images-idx3-ubyte
data/MNIST/raw/train-images-idx3-ubyte.gz
data/MNIST/raw/train-labels-idx1-ubyte
data/MNIST/raw/train-labels-idx1-ubyte.gz
logs/acc.tsv
logs/loss.tsv
model.pt
```

**Comment by mattseddon** [comment]
**Note**: There are a lot of interconnected issues listed in the description of https://github.com/iterative/vscode-dvc/issues/834. I'm pointing this out so that I don't have to duplicate the list here 👍🏻 .
