### ISSUE TITLE
DVC push looking for filenames wrapped within single quotes

### ISSUE THREAD

**Issue by aveek-brahmachari** [iterative/dvc#6741]
[core]
    remote = storage
['remote "storage"']
    url = ssh://xx.xxx.xx.xxx
    user = abcdefgh

0a becomes '\0a' folder and instead of looking for abcd.md5, it  might be looking for 'abcd.md5'

Any help would be appreciated.

**Comment by efiop** [comment]
Hi @aveek-brahmachari Please provide `dvc doctor` output. Also, do you have any error log or more info in general on the error you are getting?

**Comment by aveek-brahmachari** [comment]
> [core] remote = storage ['remote "storage"'] url = ssh://xx.xxx.xx.xxx user = abcdefgh
> 
> 0a becomes '\0a' folder and instead of looking for abcd.md5, it might be looking for 'abcd.md5'
> 
> Any help would be appreciated.

In tried to rename the folder on the repo so that the correct folder is found but even then the file did not get copied. That makes me believe that it might be looking for a quote wrapped filename which is non-existent

**Comment by aveek-brahmachari** [comment]
> Hi @aveek-brahmachari Please provide `dvc doctor` output. Also, do you have any error log or more info in general on the error you are getting?

Replied above.

**Comment by efiop** [comment]
@aveek-brahmachari Thanks! And could you add `-v` flag to the command you are running and show us full log, please?

**Comment by aveek-brahmachari** [comment]
> @aveek-brahmachari Thanks! And could you add `-v` flag to the command you are running and show us full log, please?

$ dvc -v push
ERROR: failed to transfer 'md5: 860e0ccab965d8d47921613f9bd17324' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 8ed5a2d4593cc728e4a2329632511d36' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: a0fe20248f00e23c659fc2169469047e' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: b9c86cd8ccc2c9c9d4da0bc5dea1343a' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 0e42d430b89d71664198538469eac80f' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: b0cba245928567ceb47d60113e61f09a' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 316278a2d0dcd8f39ba14b39ee067bcf' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: a9ec64e16a8197bb328fa6176c48e4de' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 746cfa0658da531c1580174a90cc70ab' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: f5af3a418a25989bc22d3349e098bcf1' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 35996c08d3ca38b70a96ee0f8e8e5f3e' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: f34f1dfa923e0f1b0bbc5ee5699b69cb' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: bdeac3464ba72281274c4c4b334e3dec' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: a345cf87e3a94342dfef7877e39fbcf7' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: f15d48909e1aa291feaf9daa2daba25a' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 0a6e6b2410e54fe5244a89430fddebc1' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: c77463ade067fb57fc49ddb4102f6ac6' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 3092389a7abd75006cbae79b12d22cf8' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 6159aa79516f0cda3eda963db9c8ef00' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 3fcb77cbafdac0c1e0dcbcc377e3a3e6' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 404491754b0b5906020b495a3cba6e58' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 38b89d95d9a68696a5aa57e58ffbc7b8' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 669c6512bed7d9641e1b962ecb57ff11' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 45f3bc1abc9cb7c64ed92a8dab691f18' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 1d70d61974605eb363ec769218662d87' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 5eef7f759d9c0fc65cd0c3d2bab507ff' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 8011a62090c8e2c43497910e76f95daa' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 65310d63cd8e7f6fc6da0c9ae3d9984c' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 2c80eb3aa450664fc2cd9c1f244b98a2' - [Errno 2] No such file or directory: No such file
ERROR: failed to transfer 'md5: 2088ffb422873b7d9595613cf63d7afb' - [Errno 2] No such file or directory: No such file
ERROR: failed to push data to the cloud - 30 files failed to upload

**Comment by efiop** [comment]
@aveek-brahmachari That doesn't look like full log, are you sure you've captured everything?

**Comment by aveek-brahmachari** [comment]
> @aveek-brahmachari That doesn't look like full log, are you sure you've captured everything?

Yes

**Comment by efiop** [comment]
@aveek-brahmachari Ah, I think I see what's the problem is. Try `dvc push -v`, please

**Comment by aveek-brahmachari** [comment]
$ dvc push -v
2021-10-04 21:38:31,229 DEBUG: Preparing to transfer data from '.dvc\cache' to 'ssh://xx.xxx.xx.xxx'
2021-10-04 21:38:31,231 DEBUG: Preparing to collect status from 'ssh://xx.xxx.xx.xxx'
2021-10-04 21:38:31,231 DEBUG: Collecting status from 'ssh://xx.xxx.xx.xxx'
2021-10-04 21:38:36,712 DEBUG: Estimated remote size: 256 files
2021-10-04 21:38:36,712 DEBUG: Querying '30' hashes via traverse
2021-10-04 21:40:25,095 DEBUG: '/./.Xauthority' doesn't look like a cache file, skipping
2021-10-04 21:40:25,095 DEBUG: '/./.bash_history' doesn't look like a cache file, skipping
2021-10-04 21:40:25,095 DEBUG: '/./.bash_logout' doesn't look like a cache file, skipping
2021-10-04 21:40:25,096 DEBUG: '/./.bashrc' doesn't look like a cache file, skipping
2021-10-04 21:40:25,096 DEBUG: '/./.cache/motd.legal-displayed' doesn't look like a cache file, skipping
2021-10-04 21:40:25,096 DEBUG: '/./.local/share/keyrings/login.keyring' doesn't look like a cache file, skipping
2021-10-04 21:40:25,097 DEBUG: '/./.local/share/keyrings/user.keystore' doesn't look like a cache file, skipping
2021-10-04 21:40:25,097 DEBUG: '/./.profile' doesn't look like a cache file, skipping
2021-10-04 21:40:25,097 DEBUG: '/./.ssh/authorized_keys' doesn't look like a cache file, skipping
2021-10-04 21:40:25,097 DEBUG: '/./.ssh/id_rsa.pub' doesn't look like a cache file, skipping
2021-10-04 21:40:25,098 DEBUG: '/./.vim/.netrwhist' doesn't look like a cache file, skipping
2021-10-04 21:40:25,098 DEBUG: '/./.viminfo' doesn't look like a cache file, skipping
2021-10-04 21:40:25,098 DEBUG: Preparing to collect status from '.dvc\cache'
2021-10-04 21:40:25,100 DEBUG: Collecting status from '.dvc\cache'
2021-10-04 21:40:26,652 DEBUG: Uploading '.dvc\cache\65\310d63cd8e7f6fc6da0c9ae3d9984c' to 'ssh://xx.xxx.xx.xxx/65/310d63cd8e7f6fc6da0c9ae3d9984c'
2021-10-04 21:40:26,652 DEBUG: Uploading '.dvc\cache\f3\4f1dfa923e0f1b0bbc5ee5699b69cb' to 'ssh://xx.xxx.xx.xxx/f3/4f1dfa923e0f1b0bbc5ee5699b69cb'
2021-10-04 21:40:26,652 DEBUG: Uploading '.dvc\cache\b0\cba245928567ceb47d60113e61f09a' to 'ssh://xx.xxx.xx.xxxx/b0/cba245928567ceb47d60113e61f09a'
2021-10-04 21:40:26,653 DEBUG: Uploading '.dvc\cache\3f\cb77cbafdac0c1e0dcbcc377e3a3e6' to 'ssh://xx.xxx.xx.xxxx/3f/cb77cbafdac0c1e0dcbcc377e3a3e6'
2021-10-04 21:40:27,421 DEBUG: Uploading '.dvc\cache\30\92389a7abd75006cbae79b12d22cf8' to 'ssh://xx.xxx.xx.xxxx/30/92389a7abd75006cbae79b12d22cf8'
2021-10-04 21:40:27,421 DEBUG: Uploading '.dvc\cache\45\f3bc1abc9cb7c64ed92a8dab691f18' to 'ssh://xx.xxx.xx.xxxx/45/f3bc1abc9cb7c64ed92a8dab691f18'
2021-10-04 21:40:27,421 DEBUG: Uploading '.dvc\cache\86\0e0ccab965d8d47921613f9bd17324' to 'ssh://xx.xxx.xx.xxxx/86/0e0ccab965d8d47921613f9bd17324'
2021-10-04 21:40:27,422 DEBUG: Uploading '.dvc\cache\2c\80eb3aa450664fc2cd9c1f244b98a2' to 'ssh://xx.xxx.xx.xxxx/2c/80eb3aa450664fc2cd9c1f244b98a2'
2021-10-04 21:40:27,422 DEBUG: Uploading '.dvc\cache\f1\5d48909e1aa291feaf9daa2daba25a' to 'ssh://xx.xxx.xx.xxxx/f1/5d48909e1aa291feaf9daa2daba25a'
2021-10-04 21:40:27,423 DEBUG: Uploading '.dvc\cache\35\996c08d3ca38b70a96ee0f8e8e5f3e' to 'ssh://xx.xxx.xx.xxxx/35/996c08d3ca38b70a96ee0f8e8e5f3e'
2021-10-04 21:40:27,424 DEBUG: Uploading '.dvc\cache\66\9c6512bed7d9641e1b962ecb57ff11' to 'ssh://xx.xxx.xx.xxxx/66/9c6512bed7d9641e1b962ecb57ff11'
2021-10-04 21:40:27,424 DEBUG: Uploading '.dvc\cache\a3\45cf87e3a94342dfef7877e39fbcf7' to 'ssh://xx.xxx.xx.xxxx/a3/45cf87e3a94342dfef7877e39fbcf7'
2021-10-04 21:40:27,424 DEBUG: Uploading '.dvc\cache\b9\c86cd8ccc2c9c9d4da0bc5dea1343a' to 'ssh://xx.xxx.xx.xxxx/b9/c86cd8ccc2c9c9d4da0bc5dea1343a'
2021-10-04 21:40:27,433 DEBUG: Uploading '.dvc\cache\5e\ef7f759d9c0fc65cd0c3d2bab507ff' to 'ssh://xx.xxx.xx.xxxx/5e/ef7f759d9c0fc65cd0c3d2bab507ff'
2021-10-04 21:40:27,434 DEBUG: Uploading '.dvc\cache\61\59aa79516f0cda3eda963db9c8ef00' to 'ssh://xx.xxx.xx.xxxx/61/59aa79516f0cda3eda963db9c8ef00'
2021-10-04 21:40:27,434 DEBUG: Uploading '.dvc\cache\38\b89d95d9a68696a5aa57e58ffbc7b8' to 'ssh://xx.xxx.xx.xxxx/38/b89d95d9a68696a5aa57e58ffbc7b8'
2021-10-04 21:40:27,434 DEBUG: Uploading '.dvc\cache\74\6cfa0658da531c1580174a90cc70ab' to 'ssh://xx.xxx.xx.xxxx/74/6cfa0658da531c1580174a90cc70ab'
2021-10-04 21:40:27,445 ERROR: failed to transfer 'md5: 65310d63cd8e7f6fc6da0c9ae3d9984c' - [Errno 2] No such file or directory: No such file
------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Programs\Python39\lib\site-packages\sshfs\utils.py", line 27, in wrapper
    return await func(*args, **kwargs)
  File "C:\Programs\Python39\lib\site-packages\sshfs\spec.py", line 232, in _makedirs
    await channel.makedirs(path, exist_ok=exist_ok, attrs=attrs)
  File "C:\Programs\Python39\lib\site-packages\asyncssh\sftp.py", line 2609, in makedirs
    await self.mkdir(curpath, attrs)
  File "C:\Programs\Python39\lib\site-packages\asyncssh\sftp.py", line 3293, in mkdir
    await self._handler.mkdir(path, attrs)
  File "C:\Programs\Python39\lib\site-packages\asyncssh\sftp.py", line 1507, in mkdir
    return await self._make_request(FXP_MKDIR, String(path), attrs.encode())
  File "C:\Programs\Python39\lib\site-packages\asyncssh\sftp.py", line 1189, in _make_request
    result = self._packet_handlers[resptype](self, resp)
  File "C:\Programs\Python39\lib\site-packages\asyncssh\sftp.py", line 1221, in _process_status
    raise _construct_sftp_error(code, reason, lang)
asyncssh.sftp.SFTPNoSuchFile: No such file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Programs\Python39\lib\site-packages\dvc\objects\transfer.py", line 25, in wrapper
    func(path_info, *args, **kwargs)
  File "C:\Programs\Python39\lib\site-packages\dvc\objects\transfer.py", line 159, in func
    return dest.add(
  File "C:\Programs\Python39\lib\site-packages\dvc\objects\db\base.py", line 113, in add
    self._add_file(fs, path_info, cache_info, hash_info, move=move)
  File "C:\Programs\Python39\lib\site-packages\dvc\objects\db\base.py", line 89, in _add_file
    return fs.utils.transfer(
  File "C:\Programs\Python39\lib\site-packages\dvc\fs\utils.py", line 30, in transfer
    return to_fs.upload(from_info, to_info)
  File "C:\Programs\Python39\lib\site-packages\dvc\fs\base.py", line 282, in upload
    return self.put_file(
  File "C:\Programs\Python39\lib\site-packages\dvc\fs\ssh.py", line 132, in put_file
    super().put_file(from_file, tmp_file, callback=callback, **kwargs)
  File "C:\Programs\Python39\lib\site-packages\dvc\fs\fsspec_wrapper.py", line 137, in put_file
    self.fs.put_file(
  File "C:\Programs\Python39\lib\site-packages\fsspec\asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "C:\Programs\Python39\lib\site-packages\fsspec\asyn.py", line 71, in sync
    raise return_result
  File "C:\Programs\Python39\lib\site-packages\fsspec\asyn.py", line 25, in _runner
    result[0] = await coro
  File "C:\Programs\Python39\lib\site-packages\sshfs\utils.py", line 27, in wrapper
    return await func(*args, **kwargs)
  File "C:\Programs\Python39\lib\site-packages\sshfs\spec.py", line 170, in _put_file
    await self._makedirs(self._parent(rpath), exist_ok=True)
  File "C:\Programs\Python39\lib\site-packages\sshfs\utils.py", line 31, in wrapper
    raise FileNotFoundError(errno.ENOENT, _NOT_FOUND) from exc
FileNotFoundError: [Errno 2] No such file or directory




This is only for the first file. Rest is repetitive mostly.

**Comment by efiop** [comment]
@aveek-brahmachari And could yoy try our upstream version, please?

```
pip install "git+https://github.com/iterative/dvc#egg=dvc[ssh]"
dvc push -v
```

Btw, how does the url for the remote look like? Are you sure the directory you are trying to push into exists on the server?

**Comment by aveek-brahmachari** [comment]
> @aveek-brahmachari And could yoy try our upstream version, please?
> pip install "git+https://github.com/iterative/dvc#egg=dvc[ssh]"

This worked. Many thanks.

**Comment by efiop** [comment]
@aveek-brahmachari Great! Looks like it was fixed in one of the recent changes. Stay tuned for a new release. Thanks for the feedback! 🙏
