### ISSUE TITLE
dvc push not working, "gir1.2-secret-1" already installed

### ISSUE THREAD

**Issue by alcinoluiz** [iterative/dvc#6796]
dvc version: 2.8.1
OS: ubuntu 20.04

01:00:56 alce@L380 horoscopo ±|main ✗|→ dvc push -v
2021-10-13 01:01:26,514 DEBUG: Preparing to transfer data from '.dvc/cache' to 'azure://alceblob/'
2021-10-13 01:01:26,515 DEBUG: Preparing to collect status from 'azure://alceblob/'
2021-10-13 01:01:26,515 DEBUG: Collecting status from 'azure://alceblob/'
2021-10-13 01:01:26,515 DEBUG: Querying 1 hashes via object_exists
  0% Querying cache in azure://alceblob/|                                                                                                     |0/1 [00:00<?,     ?file/s]Require a package "gir1.2-secret-1" which could be installed by:
        sudo apt install gir1.2-secret-1
        
Traceback (most recent call last):
  File "/home/alce/anaconda3/envs/py38/lib/python3.8/site-packages/msal_extensions/libsecret.py", line 34, in <module>
    gi.require_version("Secret", "1")  # Would require a package gir1.2-secret-1
  File "/home/alce/anaconda3/envs/py38/lib/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Secret not available

**Comment by efiop** [comment]
Hi @alcinoluiz, could you show `dvc doctor` output, please?

**Comment by alcinoluiz** [comment]
For sure! Here it is:

DVC version: 2.8.1 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.11.0-37-generic-x86_64-with-glibc2.10
Supports:
	azure (adlfs = 2021.9.1, knack = 0.8.2, azure-identity = 1.6.1),
	webhdfs (fsspec = 2021.10.0),
	http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda2
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/sda2
Repo: dvc, git
