### ISSUE TITLE
`exp show --show-json`: broken for non TTY

### ISSUE THREAD

**Issue by mattseddon** [iterative/dvc#6803]
# Bug Report

### Reproduce

1. open dvc repository

2. output from `exp show --show-json` in terminal: 
 
![image](https://user-images.githubusercontent.com/37993418/137243997-5db33fe2-112f-4e2d-9922-75b7a0f6a8ab.png)

3. output from `exp show --show-json` in non-TTY:
 `ERROR: unexpected error - Object of type datetime is not JSON serializable`

4. output from setting `DVC_IGNORE_ISATTY=true` && running `exp show --show-json` in non-TTY:

```

!
If DVC froze, see `hardlink_lock` in <https://man.dvc.org/config#core>
                                                                      

!
If DVC froze, see `hardlink_lock` in <https://man.dvc.org/config#core>
                                                                      

!
If DVC froze, see `hardlink_lock` in <https://man.dvc.org/config#core>

```

### Expected

Can run `exp show --show-json` in non-TTY without errors.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.8.1 (pip)
---------------------------------
Platform: Python 3.9.5 on macOS-11.5.2-x86_64-i386-64bit
Supports:
        webhdfs (fsspec = 2021.10.0),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
        s3 (s3fs = 2021.10.0, boto3 = 1.17.49)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc (subdir), git
```

**Additional Information (if any):**

**Comment by mattseddon** [comment]
Verbose output from 3:

```
2021-10-14 14:13:11,336 ERROR: unexpected error - Object of type datetime is not JSON serializable
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mattseddon/PP/vscode-dvc/demo/.env/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/Users/mattseddon/PP/vscode-dvc/demo/.env/lib/python3.9/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/Users/mattseddon/PP/vscode-dvc/demo/.env/lib/python3.9/site-packages/dvc/command/experiments.py", line 509, in run
    ui.write_json(all_experiments, default=_format_json)
  File "/Users/mattseddon/PP/vscode-dvc/demo/.env/lib/python3.9/site-packages/dvc/ui/__init__.py", line 101, in write_json
    return self.write(json.dumps(data))
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/mattseddon/.pyenv/versions/3.9.5/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

**Comment by efiop** [comment]
Caused by https://github.com/iterative/dvc/pull/6743

**Comment by efiop** [comment]
Looks like we've stopped passing `default` to https://github.com/iterative/dvc/blob/0ae91300523e25e060e1313d0adb8b2eb45c4cce/dvc/ui/__init__.py#L101 , which caused the error.
