### ISSUE TITLE
dvc push: [Errno 111] Connect call failed

### ISSUE THREAD

**Issue by SokolovMichail** [iterative/dvc#6813]
# Bug Report

## Description
Upon calling dvc push this error appears:
```console
$ dvc push
ERROR: unexpected error - [Errno 111] Connect call failed (COMPANY_SERVER_IP, PORT)
                                                       
Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```
(I am not able to provide COMPANY_SERVER_IP, PORT due to company policy. Port differs from 22).    

### Reproduce

1. dvc push

### Expected

An ability to push files to a company DVC server.

### Environment information

**Output of `dvc doctor`:**
```console
$ dvc doctor

DVC version: 2.8.1 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-88-generic-x86_64-with-glibc2.29
Supports:
        webhdfs (fsspec = 2021.10.0),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        ssh (sshfs = 2021.8.1)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda2
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/sda2
Repo: dvc, git
```

**Additional Information (if any):**

I was able to resolve this issue by downgrading to dvc version of 2.5.2. DVC push works fine there.

**Comment by SokolovMichail** [comment]
Providing dvc push -v output as requested.
Due to the company policy it had to be doctored to remove the confidential information. It is replaced with \<INFORMATION>. 
``` console
(venv) $ dvc push -v
2021-10-17 00:25:42,632 DEBUG: Preparing to transfer data from '.dvc/cache' to 'ssh://dvc@<COMPANY_SERVER_NAME>/<PATH_TO_FOLDER>
2021-10-17 00:25:42,636 DEBUG: Preparing to collect status from 'ssh://dvc@<COMPANY_SERVER_NAME>/<PATH_TO_FOLDER>'
2021-10-17 00:25:42,637 DEBUG: Collecting status from 'ssh://dvc@<COMPANY_SERVER_NAME>/<PATH_TO_FOLDER>'
2021-10-17 00:25:42,638 DEBUG: Querying 6 hashes via object_exists
2021-10-17 00:25:48,186 ERROR: unexpected error - [Errno 111] Connect call failed ('<COMPANY_SERVER_IP>', <PORT>)                                   
------------------------------------------------------------
Traceback (most recent call last):
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/dvc/command/data_sync.py", line 57, in run
    processed_files_count = self.repo.push(
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/dvc/repo/push.py", line 48, in push
    pushed += self.cloud.push(obj_ids, jobs, remote=remote, odb=odb)
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/dvc/data_cloud.py", line 85, in push
    return transfer(
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/dvc/objects/transfer.py", line 153, in transfer
    status = compare_status(src, dest, obj_ids, check_deleted=False, **kwargs)
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/dvc/objects/status.py", line 160, in compare_status
    dest_exists, dest_missing = status(
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/dvc/objects/status.py", line 122, in status
    exists = hashes.intersection(
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/dvc/objects/status.py", line 36, in _indexed_dir_hashes
    indexed_dir_exists.update(odb.list_hashes_exists(indexed_dirs))
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/dvc/objects/db/base.py", line 415, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/dvc/objects/db/base.py", line 406, in exists_with_progress
    ret = self.fs.exists(path_info)
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/dvc/fs/fsspec_wrapper.py", line 136, in exists
    return self.fs.exists(self._with_bucket(path_info))
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/funcy/objects.py", line 50, in __get__
    return prop.__get__(instance, type)
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "<PATH_TO_VENV>venv/lib/python3.8/site-packages/dvc/fs/ssh.py", line 117, in fs
    return _SSHFileSystem(**self.fs_args)
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/sshfs/spec.py", line 77, in __init__
    self._client, self._pool = self.connect(
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/sshfs/utils.py", line 27, in wrapper
    return await func(*args, **kwargs)
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/sshfs/spec.py", line 92, in _connect
    client = await self._stack.enter_async_context(_raw_client)
  File "/usr/lib/python3.8/contextlib.py", line 568, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/asyncssh/misc.py", line 220, in __aenter__
    self._result = await self._coro
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/asyncssh/connection.py", line 6803, in connect
    return await _connect(options, loop, flags, conn_factory,
  File "<PATH_TO_VENV>/venv/lib/python3.8/site-packages/asyncssh/connection.py", line 297, in _connect
    _, conn = await loop.create_connection(conn_factory, host, port,
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('<COMPANY_SERVER_IP>', <PORT>)
------------------------------------------------------------
2021-10-17 00:25:49,045 DEBUG: Version info for developers:
DVC version: 2.8.1 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-88-generic-x86_64-with-glibc2.29
Supports:
        webhdfs (fsspec = 2021.10.0),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        ssh (sshfs = 2021.8.1)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda2
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/sda2
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-10-17 00:25:49,046 DEBUG: Analytics is enabled.
2021-10-17 00:25:49,090 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpic0pzgti']'
2021-10-17 00:25:49,092 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpic0pzgti']'

```

**Comment by efiop** [comment]
@SokolovMichail Does aws cli work? Is this aws or some s3 compatible storage (e.g. minio)?

**Comment by efiop** [comment]
@SokolovMichail Anything special about your setup? Any special options in ssh config or our config?

**Comment by efiop** [comment]
@SokolovMichail Could you try:
```
pip install -U dvc
pip install 'sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]'
```
and then trying `dvc push` again? Please make sure `dvc doctor` indicates correct version and `pip` as a package type.

We've migrated from paramiko to asyncssh, so there is probably something special about your environment that was enabled by default in paramiko, but is not enabled by default in asyncssh. The command above will install additional extras, just to see if it is something among those that was missing.

**Comment by rnwind** [comment]
@SokolovMichail and I work in the same company.
I met the same issue. Downgrade to dvc 2.5.4 have helped.

**Comment by efiop** [comment]
@rnwind What about the recipe from my last comment above, could you give it a try, please?

**Comment by SokolovMichail** [comment]
I tried using the provided commands. 
Upon executing the latter command, I was greeted with this:
```console
$ pip install 'sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]'
Requirement already satisfied: sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl] in ./venv/lib/python3.8/site-packages (2021.8.1)
Requirement already satisfied: asyncssh==2.7.0 in ./venv/lib/python3.8/site-packages (from sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (2.7.0)
Collecting fsspec==2021.8.1
  Using cached fsspec-2021.8.1-py3-none-any.whl (119 kB)
Requirement already satisfied: cryptography>=2.8 in ./venv/lib/python3.8/site-packages (from asyncssh==2.7.0->sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (3.4.8)
Requirement already satisfied: cffi>=1.12 in ./venv/lib/python3.8/site-packages (from cryptography>=2.8->asyncssh==2.7.0->sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (1.14.6)
Requirement already satisfied: pycparser in ./venv/lib/python3.8/site-packages (from cffi>=1.12->cryptography>=2.8->asyncssh==2.7.0->sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (2.20)
Collecting fido2==0.9.1
  Using cached fido2-0.9.1.tar.gz (206 kB)
Requirement already satisfied: six in ./venv/lib/python3.8/site-packages (from fido2==0.9.1->asyncssh==2.7.0->sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (1.16.0)
Collecting gssapi>=1.2.0
  Using cached gssapi-1.7.2.tar.gz (1.2 MB)
Requirement already satisfied: decorator in ./venv/lib/python3.8/site-packages (from gssapi>=1.2.0->asyncssh==2.7.0->sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (5.0.9)
Collecting libnacl>=1.4.2
  Downloading libnacl-1.8.0-py2.py3-none-any.whl (20 kB)
Ignoring pyOpenSSL: markers 'extra == "pyOpenSSL"' don't match your environment
WARNING: asyncssh 2.7.0 does not provide the extra 'python-pkcs11'
Building wheels for collected packages: fido2, gssapi
  Building wheel for fido2 (setup.py) ... done
  Created wheel for fido2: filename=fido2-0.9.1-py2.py3-none-any.whl size=178610 sha256=8a844b6831641586667e67acd6998d6c73b795035b3327dcd4106aa7fcbfe710
  Stored in directory: /home/sokolov/.cache/pip/wheels/93/d7/62/c8706b47204630c260d9e86aead59953e448005a28b8831723
  Building wheel for gssapi (setup.py) ... done
  Created wheel for gssapi: filename=gssapi-1.7.2-cp38-cp38-linux_x86_64.whl size=3689705 sha256=6d409fcc4f937a563281a7243ae3a50557424f3724e209dfa88db5fa48bbc93b
  Stored in directory: /home/sokolov/.cache/pip/wheels/35/3c/f8/eaa0be532636f29e8505ece50a19dc0494cc99172bac8fec47
Successfully built fido2 gssapi
Installing collected packages: libnacl, gssapi, fsspec, fido2
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2021.11.0
    Uninstalling fsspec-2021.11.0:
      Successfully uninstalled fsspec-2021.11.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dvc 2.8.3 requires fsspec[http]>=2021.10.1, but you have fsspec 2021.8.1 which is incompatible.
Successfully installed fido2-0.9.1 fsspec-2021.8.1 gssapi-1.7.2 libnacl-1.8.0```

**Comment by pmrowla** [comment]
@SokolovMichail can you try doing
```
pip install -U 'sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]'
```
and then re-run `dvc push`? It looks like your sshfs wasn't actually updated, `dvc doctor` reports `ssh (sshfs = 2021.8.1)` but the latest should be `sshfs = 2021.11.0`

**Comment by SokolovMichail** [comment]
I tried doing this. Providing the output below.
```console
$ pip install -U dvc
Collecting dvc
  Using cached dvc-2.8.3-py3-none-any.whl (399 kB)
Requirement already satisfied: flufl.lock>=5 in ./venv/lib/python3.8/site-packages (from dvc) (6.0)
Requirement already satisfied: fsspec[http]>=2021.10.1 in ./venv/lib/python3.8/site-packages (from dvc) (2021.11.0)
Requirement already satisfied: pyasn1>=0.4.1 in ./venv/lib/python3.8/site-packages (from dvc) (0.4.8)
Requirement already satisfied: configobj>=5.0.6 in ./venv/lib/python3.8/site-packages (from dvc) (5.0.6)
Requirement already satisfied: pathspec<0.10.0,>=0.9.0 in ./venv/lib/python3.8/site-packages (from dvc) (0.9.0)
Requirement already satisfied: funcy>=1.14 in ./venv/lib/python3.8/site-packages (from dvc) (1.16)
Requirement already satisfied: typing-extensions>=3.7.4 in ./venv/lib/python3.8/site-packages (from dvc) (3.10.0.2)
Requirement already satisfied: distro>=1.3.0 in ./venv/lib/python3.8/site-packages (from dvc) (1.6.0)
Requirement already satisfied: python-benedict>=0.24.2 in ./venv/lib/python3.8/site-packages (from dvc) (0.24.2)
Requirement already satisfied: nanotime>=0.5.2 in ./venv/lib/python3.8/site-packages (from dvc) (0.5.2)
Requirement already satisfied: pydot>=1.2.4 in ./venv/lib/python3.8/site-packages (from dvc) (1.4.2)
Requirement already satisfied: flatten-dict<1,>=0.4.1 in ./venv/lib/python3.8/site-packages (from dvc) (0.4.2)
Requirement already satisfied: colorama>=0.3.9 in ./venv/lib/python3.8/site-packages (from dvc) (0.4.4)
Requirement already satisfied: dpath<3,>=2.0.2 in ./venv/lib/python3.8/site-packages (from dvc) (2.0.2)
Requirement already satisfied: dictdiffer>=0.8.1 in ./venv/lib/python3.8/site-packages (from dvc) (0.9.0)
Requirement already satisfied: pygtrie>=2.3.2 in ./venv/lib/python3.8/site-packages (from dvc) (2.4.2)
Requirement already satisfied: voluptuous>=0.11.7 in ./venv/lib/python3.8/site-packages (from dvc) (0.12.1)
Requirement already satisfied: aiohttp-retry>=2.4.5 in ./venv/lib/python3.8/site-packages (from dvc) (2.4.6)
Requirement already satisfied: toml>=0.10.1 in ./venv/lib/python3.8/site-packages (from dvc) (0.10.2)
Requirement already satisfied: pygit2>=1.5.0 in ./venv/lib/python3.8/site-packages (from dvc) (1.6.1)
Requirement already satisfied: requests>=2.22.0 in ./venv/lib/python3.8/site-packages (from dvc) (2.26.0)
Requirement already satisfied: zc.lockfile>=1.2.1 in ./venv/lib/python3.8/site-packages (from dvc) (2.0)
Requirement already satisfied: pyparsing>=2.4.7 in ./venv/lib/python3.8/site-packages (from dvc) (2.4.7)
Requirement already satisfied: grandalf==0.6 in ./venv/lib/python3.8/site-packages (from dvc) (0.6)
Requirement already satisfied: ruamel.yaml>=0.17.11 in ./venv/lib/python3.8/site-packages (from dvc) (0.17.16)
Requirement already satisfied: dulwich>=0.20.23 in ./venv/lib/python3.8/site-packages (from dvc) (0.20.25)
Requirement already satisfied: rich>=10.13.0 in ./venv/lib/python3.8/site-packages (from dvc) (10.13.0)
Requirement already satisfied: shtab<2,>=1.3.4 in ./venv/lib/python3.8/site-packages (from dvc) (1.4.1)
Requirement already satisfied: appdirs>=1.4.3 in ./venv/lib/python3.8/site-packages (from dvc) (1.4.4)
Requirement already satisfied: packaging>=19.0 in ./venv/lib/python3.8/site-packages (from dvc) (21.0)
Requirement already satisfied: gitpython>3 in ./venv/lib/python3.8/site-packages (from dvc) (3.1.18)
Requirement already satisfied: tabulate>=0.8.7 in ./venv/lib/python3.8/site-packages (from dvc) (0.8.9)
Requirement already satisfied: importlib-resources>=5.2.2 in ./venv/lib/python3.8/site-packages (from dvc) (5.4.0)
Requirement already satisfied: tqdm<5,>=4.45.0 in ./venv/lib/python3.8/site-packages (from dvc) (4.60.0)
Requirement already satisfied: networkx>=2.5 in ./venv/lib/python3.8/site-packages (from dvc) (2.6.2)
Requirement already satisfied: psutil>=5.8.0 in ./venv/lib/python3.8/site-packages (from dvc) (5.8.0)
Requirement already satisfied: diskcache>=5.2.1 in ./venv/lib/python3.8/site-packages (from dvc) (5.2.1)
Requirement already satisfied: shortuuid>=0.5.0 in ./venv/lib/python3.8/site-packages (from dvc) (1.0.1)
Requirement already satisfied: ply>=3.9 in ./venv/lib/python3.8/site-packages (from dvc) (3.11)
Requirement already satisfied: future in ./venv/lib/python3.8/site-packages (from grandalf==0.6->dvc) (0.18.2)
Requirement already satisfied: aiohttp in ./venv/lib/python3.8/site-packages (from aiohttp-retry>=2.4.5->dvc) (3.7.4.post0)
Requirement already satisfied: six in ./venv/lib/python3.8/site-packages (from configobj>=5.0.6->dvc) (1.16.0)
Requirement already satisfied: certifi in ./venv/lib/python3.8/site-packages (from dulwich>=0.20.23->dvc) (2021.5.30)
Requirement already satisfied: urllib3>=1.24.1 in ./venv/lib/python3.8/site-packages (from dulwich>=0.20.23->dvc) (1.26.6)
Requirement already satisfied: atpublic in ./venv/lib/python3.8/site-packages (from flufl.lock>=5->dvc) (2.3)
Requirement already satisfied: gitdb<5,>=4.0.1 in ./venv/lib/python3.8/site-packages (from gitpython>3->dvc) (4.0.7)
Requirement already satisfied: zipp>=3.1.0 in ./venv/lib/python3.8/site-packages (from importlib-resources>=5.2.2->dvc) (3.6.0)
Requirement already satisfied: cffi>=1.4.0 in ./venv/lib/python3.8/site-packages (from pygit2>=1.5.0->dvc) (1.14.6)
Requirement already satisfied: phonenumbers in ./venv/lib/python3.8/site-packages (from python-benedict>=0.24.2->dvc) (8.12.31)
Requirement already satisfied: mailchecker in ./venv/lib/python3.8/site-packages (from python-benedict>=0.24.2->dvc) (4.0.11)
Requirement already satisfied: xmltodict in ./venv/lib/python3.8/site-packages (from python-benedict>=0.24.2->dvc) (0.12.0)
Requirement already satisfied: python-fsutil in ./venv/lib/python3.8/site-packages (from python-benedict>=0.24.2->dvc) (0.5.0)
Requirement already satisfied: python-dateutil in ./venv/lib/python3.8/site-packages (from python-benedict>=0.24.2->dvc) (2.8.2)
Requirement already satisfied: ftfy in ./venv/lib/python3.8/site-packages (from python-benedict>=0.24.2->dvc) (6.0.3)
Requirement already satisfied: pyyaml in ./venv/lib/python3.8/site-packages (from python-benedict>=0.24.2->dvc) (5.4.1)
Requirement already satisfied: python-slugify in ./venv/lib/python3.8/site-packages (from python-benedict>=0.24.2->dvc) (5.0.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./venv/lib/python3.8/site-packages (from requests>=2.22.0->dvc) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.8/site-packages (from requests>=2.22.0->dvc) (3.2)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in ./venv/lib/python3.8/site-packages (from rich>=10.13.0->dvc) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in ./venv/lib/python3.8/site-packages (from rich>=10.13.0->dvc) (2.10.0)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2 in ./venv/lib/python3.8/site-packages (from ruamel.yaml>=0.17.11->dvc) (0.2.6)
Requirement already satisfied: setuptools in ./venv/lib/python3.8/site-packages (from zc.lockfile>=1.2.1->dvc) (57.0.0)
Requirement already satisfied: pycparser in ./venv/lib/python3.8/site-packages (from cffi>=1.4.0->pygit2>=1.5.0->dvc) (2.20)
Requirement already satisfied: smmap<5,>=3.0.1 in ./venv/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython>3->dvc) (4.0.0)
Requirement already satisfied: chardet<5.0,>=2.0 in ./venv/lib/python3.8/site-packages (from aiohttp->aiohttp-retry>=2.4.5->dvc) (4.0.0)
Requirement already satisfied: attrs>=17.3.0 in ./venv/lib/python3.8/site-packages (from aiohttp->aiohttp-retry>=2.4.5->dvc) (21.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./venv/lib/python3.8/site-packages (from aiohttp->aiohttp-retry>=2.4.5->dvc) (5.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in ./venv/lib/python3.8/site-packages (from aiohttp->aiohttp-retry>=2.4.5->dvc) (1.7.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in ./venv/lib/python3.8/site-packages (from aiohttp->aiohttp-retry>=2.4.5->dvc) (3.0.1)
Requirement already satisfied: wcwidth in ./venv/lib/python3.8/site-packages (from ftfy->python-benedict>=0.24.2->dvc) (0.2.5)
Requirement already satisfied: text-unidecode>=1.3 in ./venv/lib/python3.8/site-packages (from python-slugify->python-benedict>=0.24.2->dvc) (1.3)
Installing collected packages: dvc
Successfully installed dvc-2.8.3
$ pip install -U 'sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]'
Requirement already satisfied: sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl] in ./venv/lib/python3.8/site-packages (2021.11.2)
Requirement already satisfied: asyncssh<2.9,>=2.7.1 in ./venv/lib/python3.8/site-packages (from sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (2.8.1)
Requirement already satisfied: fsspec>=2021.8.1 in ./venv/lib/python3.8/site-packages (from sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (2021.11.0)
Requirement already satisfied: cryptography>=2.8 in ./venv/lib/python3.8/site-packages (from asyncssh<2.9,>=2.7.1->sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (3.4.8)
Requirement already satisfied: fido2==0.9.1 in ./venv/lib/python3.8/site-packages (from asyncssh<2.9,>=2.7.1->sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (0.9.1)
Requirement already satisfied: six in ./venv/lib/python3.8/site-packages (from fido2==0.9.1->asyncssh<2.9,>=2.7.1->sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (1.16.0)
Requirement already satisfied: gssapi>=1.2.0 in ./venv/lib/python3.8/site-packages (from asyncssh<2.9,>=2.7.1->sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (1.7.2)
Requirement already satisfied: libnacl>=1.4.2 in ./venv/lib/python3.8/site-packages (from asyncssh<2.9,>=2.7.1->sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (1.8.0)
Ignoring pyOpenSSL: markers 'extra == "pyOpenSSL"' don't match your environment
WARNING: asyncssh 2.8.1 does not provide the extra 'python-pkcs11'
Requirement already satisfied: cffi>=1.12 in ./venv/lib/python3.8/site-packages (from cryptography>=2.8->asyncssh<2.9,>=2.7.1->sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (1.14.6)
Requirement already satisfied: decorator in ./venv/lib/python3.8/site-packages (from gssapi>=1.2.0->asyncssh<2.9,>=2.7.1->sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (5.0.9)
Requirement already satisfied: pycparser in ./venv/lib/python3.8/site-packages (from cffi>=1.12->cryptography>=2.8->asyncssh<2.9,>=2.7.1->sshfs[fido2,gssapi,libnacl,pkcs11,pyopenssl]) (2.20)
$ dvc pull
ERROR: unexpected error - [Errno 111] Connect call failed ('195.201.232.232', 45672)                                                           

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!

```
dvc doctor output:
```console
$ dvc doctor
DVC version: 2.8.3 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-90-generic-x86_64-with-glibc2.29
Supports:
        webhdfs (fsspec = 2021.11.0),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        ssh (sshfs = 2021.11.2)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda2
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/sda2
Repo: dvc, git
```

**Comment by pmrowla** [comment]
@SokolovMichail one thing I noticed:

> As for dvc config - also nothing special there. I am able to provide a doctored config file for dvc - here it is. Doctored info is replaced with <INFORMATION>. config:
> 
> ```yaml
> [core]
>     remote = base
> [cache]
>     type = "hardlink,symlink"
> ['remote "base"']
>     url = ssh://dvc@<COMPANY_SERVER_NAME>:<PATH_TO_PROJECT>
>     port = <PORT>
> ```

Your remote URL should be in the form:
```
url = ssh://dvc@<COMPANY_SERVER_NAME>/<PATH_TO_PROJECT>
```

with a slash (`/`) and not colon (`:`) separating the hostname and path to your project.

If the URL contains a colon, DVC will try to use whatever is after the colon as a port (and it will take precedence over the `port = ...` option), which may be what is causing your error

**Comment by SokolovMichail** [comment]
Thanks, @pmrowla, might be my bad. Let me provide an alternatively doctored config, where I replace only letters and not special symbols like slashes, dots, and colons. Also, keep in mind, dvc==2.5.2(and 2.5.4) work just fine both for pull and push with just the same config file.
``` console
[core]
    remote = base
[cache]
    type = "hardlink,symlink"
['remote "base"']
    url = ssh://dvc@<COMPANY>.<SERVER>.<IP>:/<PATH>/<TO>/<PROJECT>/<FOLDER>
    port = 45672

```
None of blanks(like <SERVER>) contain any special characters, only English letters.

**Comment by pmrowla** [comment]
@SokolovMichail can you post the (sanitized) contents of your `.ssh/config` for that host?

**Comment by SokolovMichail** [comment]
@pmrowla, I am not quite sure what you meant to say. 
In the project folder, I have no folder named .ssh 
In Linux home  folder I do have a .ssh folder, but it contains no config file.

**Comment by efiop** [comment]
@SokolovMichail Could you try changing URL from

```
    url = ssh://dvc@<COMPANY>.<SERVER>.<NAME>:/<PATH>/<TO>/<PROJECT>/<FOLDER>
```

to

```
    url = ssh://dvc@<COMPANY>.<SERVER>.<NAME>/<PATH>/<TO>/<PROJECT>/<FOLDER>
```

as requested by @pmrowla and giving it a try, please?

**Comment by efiop** [comment]
@SokolovMichail Any luck so far?

**Comment by SokolovMichail** [comment]
@efiop, I tried both of the instructions. None worked so far. The issue persists.

**Comment by efiop** [comment]
@SokolovMichail 😞 Ok, I've contacted your colleague (rs on ods slack) with a link to schedule a meeting for this.

**Comment by pmrowla** [comment]
@SokolovMichail @efiop 

I'm unable to reproduce the issue - using the hostname and port we were provided after the discussion, I can connect to the host directly using `asyncssh`, `sshfs`, DVC's `fs.ssh.SSHFileSystem`, and using `status -c` from a test DVC repo with SSH remote configured to use `/home/dvc` on the provided remote host.

I tested using the current DVC pip release (`2.8.3`) on both macos and linux (ubuntu-focal), and had no connection issues on either platform.

It seems like whatever the issue is, it must be related to something that is standardized across your developers' machines/environments (since it was reproducible for multiple users on your network)? But I'm not really sure how to proceed from here.

linux results (with `host:port` removed):
![Screen Shot 2021-12-07 at 3 15 57 PM](https://user-images.githubusercontent.com/651988/144977503-46b1b526-94ab-4daa-961d-9a9ac8ff6a5a.png)

---

the two test python scripts are:
```py
import asyncio, asyncssh, sys

async def run_client():
    async with asyncssh.connect(HOST, port=PORT, username="dvc") as conn:
        result = await conn.run('echo "Hello!"', check=True)
        print(result.stdout, end='')
        print("connected")

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```

```py
from dvc.fs.ssh import SSHFileSystem

fs = SSHFileSystem(
    host=HOST,
    port=PORT,
    username="dvc",
)
print(fs.exists("/home/dvc"))
```

and the test DVC repo just contains a single `dvc add`ed file `foo`

**Comment by efiop** [comment]
Thanks for the research @pmrowla ! 🙏 

One more thing for the record: during our meeting @pmrowla established that asyncssh (first script above) works fine, while dvc has problems, so it is likely that the issue is in https://github.com/fsspec/sshfs , but unfortunately we are still not able to reproduce on our side yet 🙁

**Comment by efiop** [comment]
Closing as stale. Happy to get back to this once you have more time to walk through it with us.
