### ISSUE TITLE
Error: webdavs httpx.ProxyError with Jfrog Artifactory

### ISSUE THREAD

**Issue by UshakovDV** [iterative/dvc#6879]
# Bug Report

## webdavs httpx.ProxyError with Jfrog Artifactory

I have a problem connecting to Jfrog Artifactory via dvc, I can connect and work with Artifactory directly with the Python client, but when I try to work with Artifactory using dvc, I get httpx.proxyerror: [Error 0] Error.
My best guess is this is a problem in webdav.

## Config file

```
[core]
    remote = webdavs_remote
    analytics = false
['remote "webdavs_remote"']
    url = webdavs://artifactory.skblab.ru/artifactory/ml/test/
    user = ushakovdv
    ask_password = true
    ssl_verify = false
```

### LOGS
```

(venv) C:\Users\UshakovDV\PycharmProjects\test_dvc>dvc push -v
Enter a password for host 'https://artifactory.skblab.ru' user 'ushakovdv':

2021-10-27 17:06:28,277 DEBUG: Preparing to transfer data from '.dvc\cache' to 'https://artifactory.skblab.ru/artifactory/ml/test/'
2021-10-27 17:06:28,279 DEBUG: Preparing to collect status from 'https://artifactory.skblab.ru/artifactory/ml/test/'
2021-10-27 17:06:28,280 DEBUG: Collecting status from 'https://artifactory.skblab.ru/artifactory/ml/test/'
2021-10-27 17:06:28,281 DEBUG: Querying 1 hashes via object_exists
2021-10-27 17:06:28,550 ERROR: unexpected error - [Errno 0] Error: [Errno 0] Error
------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpcore\_sync\http_proxy.py", line 232, in _tunnel_request
    extensions=extensions,
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpcore\_sync\connection.py", line 136, in handle_request
    self.socket = self._open_socket(timeout)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpcore\_sync\connection.py", line 168, in _open_socket
    local_address=self._local_address,
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpcore\_backends\sync.py", line 144, in open_tcp_stream
    return SyncSocketStream(sock=sock)
  File "C:\Users\UshakovDV\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpx\_transports\default.py", line 62, in map_httpcore_exceptions
    yield
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpx\_transports\default.py", line 182, in handle_request
    extensions=request.extensions,
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpcore\_sync\http_proxy.py", line 128, in handle_request
    method, url, headers=headers, stream=stream, extensions=extensions
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpcore\_sync\http_proxy.py", line 256, in _tunnel_request
    raise ProxyError(exc)
httpcore.ProxyError: [Errno 0] Error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\main.py", line 55, in main
    ret = cmd.do_run()
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\command\base.py", line 45, in do_run
    return self.run()
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\command\data_sync.py", line 67, in run
    glob=self.args.glob,
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\repo\__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\repo\push.py", line 48, in push
    pushed += self.cloud.push(obj_ids, jobs, remote=remote, odb=odb)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\data_cloud.py", line 91, in push
    cache_odb=self.repo.odb.local,
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\objects\transfer.py", line 153, in transfer
    status = compare_status(src, dest, obj_ids, check_deleted=False, **kwargs)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\objects\status.py", line 161, in compare_status
    dest, obj_ids, index=dest_index, **kwargs
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\objects\status.py", line 132, in status
    odb.hashes_exist(hashes, name=str(odb.path_info), **kwargs)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\objects\db\base.py", line 468, in hashes_exist
    remote_size, remote_hashes = self._estimate_remote_size(hashes, name)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\objects\db\base.py", line 270, in _estimate_remote_size
    remote_hashes = set(hashes)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\objects\db\base.py", line 224, in _hashes_with_limit
    for hash_ in self.list_hashes(prefix, progress_callback):
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\objects\db\base.py", line 214, in list_hashes
    for path in self._list_paths(prefix, progress_callback):
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\objects\db\base.py", line 194, in _list_paths
    for file_info in self.fs.walk_files(path_info, prefix=prefix):
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\fs\fsspec_wrapper.py", line 181, in walk_files
    for file in self.find(path_info, **kwargs):
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\dvc\fs\fsspec_wrapper.py", line 174, in find
    files = self.fs.find(path, detail=detail)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\fsspec\spec.py", line 446, in find
    for _, dirs, files in self.walk(path, maxdepth, detail=True, **kwargs):
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\fsspec\spec.py", line 393, in walk
    listing = self.ls(path, detail=True, **kwargs)
  File "C:\Users\UshakovDV\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\webdav4\fsspec.py", line 118, in ls
    path, detail=detail, allow_listing_resource=False
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\webdav4\client.py", line 505, in ls
    result = self.propfind(path, headers={"Depth": "1"})
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\webdav4\client.py", line 313, in propfind
    http_resp = self.with_retry(call)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\webdav4\func_utils.py", line 44, in wrapped_function
    return func()
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\webdav4\func_utils.py", line 68, in wrapped
    return func(*args, **kwargs)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\webdav4\client.py", line 357, in _request
    http_resp = self.http.request(method, url, **kwargs)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpx\_client.py", line 792, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpx\_client.py", line 881, in send
    history=[],
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpx\_client.py", line 908, in _send_handling_auth
    history=history,
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpx\_client.py", line 942, in _send_handling_redirects
    response = self._send_single_request(request)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpx\_client.py", line 978, in _send_single_request
    response = transport.handle_request(request)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpx\_transports\default.py", line 182, in handle_request
    extensions=request.extensions,
  File "C:\Users\UshakovDV\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\ushakovdv\pycharmprojects\test_dvc\venv\lib\site-packages\httpx\_transports\default.py", line 79, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ProxyError: [Errno 0] Error
------------------------------------------------------------
2021-10-27 17:06:29,032 DEBUG: Version info for developers:
DVC version: 2.8.2 (pip)
---------------------------------
Platform: Python 3.7.7 on Windows-10-10.0.18362-SP0
Supports:
        webhdfs (fsspec = 2021.10.1),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        webdav (webdav4 = 0.9.3),
        webdavs (webdav4 = 0.9.3)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: webdavs
Workspace directory: NTFS on C:\
Repo: dvc, git

```

**Comment by UshakovDV** [comment]
Problem was on my side with proxy, I close the problem

**Comment by UshakovDV** [comment]
Problem was on my side with proxy, I close the problem
