### ISSUE TITLE
version: should be resilient to certain errors with particular mount points

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#6895]
# Bug Report

We test all mount points to collect as much info as possible:

```python
    for part in psutil.disk_partitions(all=True):
        if part.fstype != "":
            try:
                mountpoint = pathlib.Path(part.mountpoint).resolve()
                partition[mountpoint] = part.fstype + " on " + part.device
            except PermissionError:
                pass
```

On Windows with a tool like `https://disk-o.cloud/` that mounts on `Z:` it leads to errors like this and it breaks the whole `dvc version` command:

```python
ERROR: unexpected error - [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'Z:\\'
Traceback (most recent call last):
  File "D:\AnacondaEnvs\kdd-image\lib\site-packages\dvc\main.py", line 55, in main
    ret = cmd.do_run()
  File "D:\AnacondaEnvs\kdd-image\lib\site-packages\dvc\command\base.py", line 59, in do_run
    return self.run()
  File "D:\AnacondaEnvs\kdd-image\lib\site-packages\dvc\command\version.py", line 15, in run
    dvc_info = get_dvc_info()
  File "D:\AnacondaEnvs\kdd-image\lib\site-packages\dvc\info.py", line 44, in get_dvc_info
    fs_type = get_fs_type(repo.odb.local.cache_dir)
  File "D:\AnacondaEnvs\kdd-image\lib\site-packages\dvc\info.py", line 141, in get_fs_type
    mountpoint = pathlib.Path(part.mountpoint).resolve()
  File "D:\AnacondaEnvs\kdd-image\lib\pathlib.py", line 1215, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "D:\AnacondaEnvs\kdd-image\lib\pathlib.py", line 215, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'Z:\\'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AnacondaEnvs\kdd-image\Scripts\dvc-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\AnacondaEnvs\kdd-image\lib\site-packages\dvc\main.py", line 88, in main
    dvc_info = get_dvc_info()
  File "D:\AnacondaEnvs\kdd-image\lib\site-packages\dvc\info.py", line 44, in get_dvc_info
    fs_type = get_fs_type(repo.odb.local.cache_dir)
  File "D:\AnacondaEnvs\kdd-image\lib\site-packages\dvc\info.py", line 141, in get_fs_type
    mountpoint = pathlib.Path(part.mountpoint).resolve()
  File "D:\AnacondaEnvs\kdd-image\lib\pathlib.py", line 1215, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "D:\AnacondaEnvs\kdd-image\lib\pathlib.py", line 215, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 1005] The volume does not contain a recognized file system.
Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'Z:\\'
```
### Environment information

```
DVC version: 2.8.2 (conda)
---------------------------------
Platform: Python 3.9.7 on Windows-10-10.0.19043-SP0
Supports:
        gdrive (pydrive2 = 1.10.0),
        webhdfs (fsspec = 2021.10.1),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5)
```

**Comment by earonesty** [comment]
this is a bug in python 3.9
