### ISSUE TITLE
repro: stage usign abspath vs repo using realpath

### ISSUE THREAD

**Issue by zvealey** [iterative/dvc#6945]
When trying to reproduce a stage using the dvc.yaml file and the repro command on NFS mounted directory, DVC throws this error:

```shell
2021-10-25 19:27:39,733 ERROR: unexpected error - Stage: 'test_stage'
------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\vea02153\.conda\envs\ml-violations-env\lib\site-packages\dvc\main.py", line 55, in main
    ret = cmd.do_run()
  File "C:\Users\vea02153\.conda\envs\ml-violations-env\lib\site-packages\dvc\command\base.py", line 45, in do_run
    return self.run()
  File "C:\Users\vea02153\.conda\envs\ml-violations-env\lib\site-packages\dvc\command\repro.py", line 12, in run
    stages = self.repo.reproduce(**self._repro_kwargs)
  File "C:\Users\vea02153\.conda\envs\ml-violations-env\lib\site-packages\dvc\repo\__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "C:\Users\vea02153\.conda\envs\ml-violations-env\lib\site-packages\dvc\repo\scm_context.py", line 14, in run
    return method(repo, *args, **kw)
  File "C:\Users\vea02153\.conda\envs\ml-violations-env\lib\site-packages\dvc\repo\reproduce.py", line 135, in reproduce
    return _reproduce_stages(self.index.graph, list(stages), **kwargs)
  File "C:\Users\vea02153\.conda\envs\ml-violations-env\lib\site-packages\dvc\repo\reproduce.py", line 176, in _reproduce_stages
    steps = _get_steps(G, stages, downstream, single_item)
  File "C:\Users\vea02153\.conda\envs\ml-violations-env\lib\site-packages\dvc\repo\reproduce.py", line 245, in _get_steps
    all_pipelines += nx.dfs_postorder_nodes(active, stage)
  File "C:\Users\vea02153\.conda\envs\ml-violations-env\lib\site-packages\networkx\algorithms\traversal\depth_first_search.py", line 290, in <genexpr>
    return (v for u, v, d in edges if d == "reverse")
  File "C:\Users\vea02153\.conda\envs\ml-violations-env\lib\site-packages\networkx\algorithms\traversal\depth_first_search.py", line 423, in dfs_labeled_edges
    stack = [(start, depth_limit, iter(G[start]))]
  File "C:\Users\vea02153\.conda\envs\ml-violations-env\lib\site-packages\networkx\classes\graph.py", line 465, in __getitem__
    return self.adj[n]
  File "C:\Users\vea02153\.conda\envs\ml-violations-env\lib\site-packages\networkx\classes\coreviews.py", line 79, in __getitem__
    return AtlasView(self._atlas[name])
KeyError: Stage: 'test_stage'
------------------------------------------------------------
2021-10-25 19:27:45,223 DEBUG: Version info for developers:
DVC version: 2.8.2 (conda)
---------------------------------
Platform: Python 3.8.11 on Windows-10-10.0.19042-SP0
Supports:
        hdfs (fsspec = 2021.10.1, pyarrow = 3.0.0),
        webhdfs (fsspec = 2021.10.1),
        http (aiohttp = 3.6.3, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.6.3, aiohttp-retry = 2.4.6)
Cache types:
Cache directory: NTFS on S:\
Caches: local
Remotes: None
Workspace directory: NTFS on S:\
Repo: dvc, git
 
Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-10-25 19:27:45,332 DEBUG: Analytics is enabled.
2021-10-25 19:27:46,582 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\vea02153\\AppData\\Local\\Temp\\2\\tmpvntqx743']'
2021-10-25 19:27:46,598 DEBUG: Spawned '['daemon', '-q', 'analytics', 'C:\\Users\\vea02153\\AppData\\Local\\Temp\\2\\tmpvntqx743']'
 ```

**Comment by pared** [comment]
We tried to track the problem with @zvealey and here are the results:

It seems that the culprit is:
[`Stage.path_in_repo`](https://github.com/iterative/dvc/blob/4175f9ffa4948157436283bef11153a7233e90ca/dvc/repo/index.py#L245) call.
So, `Stage.path_in_repo` tries to evaluate:
`relpath(self.path, self.repo.root_dir)`. The problem here is that `self.path` is `S://...` (NFS repo path) while the `self.repo.root_dir` is actual mount point of the NFS drive, because when resolving `Repo.root_dir` we call [`realpath`](https://github.com/iterative/dvc/blob/4175f9ffa4948157436283bef11153a7233e90ca/dvc/repo/__init__.py#L319)

and due to that `path_in_repo` ends up being some very bizarre relative path with multiple `../..` and it seems that we cannot find it when building DAG.

**Comment by skshetry** [comment]
Closing, as this is likely fixed at some point. If not, please comment/reopen. :)
