### ISSUE TITLE
import-url: https: raises TypeError

### ISSUE THREAD

**Issue by pared** [iterative/dvc#6966]
Seems that after #6946 we broke `import-url`.

eg:
```
dvc import-url https://github.com/iterative/dvc/blob/master/LICENSE
```

results in:
```
2021-11-11 12:50:47,061 DEBUG: Removing output 'LICENSE' of stage: 'LICENSE.dvc'.
2021-11-11 12:50:47,061 DEBUG: Removing '/Users/pawelredzynski/development/playground/dvc/tmp/import-url-broken-after-path-info/LICENSE'
Importing 'https://github.com/iterative/dvc/blob/master/LICENSE' -> 'LICENSE'
2021-11-11 12:50:47,064 DEBUG: Computed stage: 'LICENSE.dvc' md5: '93a5547d0cd22f93ab4128dfac237cc1'
2021-11-11 12:50:47,064 DEBUG: 'md5' of stage: 'LICENSE.dvc' changed.
2021-11-11 12:50:50,279 ERROR: unexpected error - argument of type 'int' is not iterable
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pawelredzynski/development/projects/dvc/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/Users/pawelredzynski/development/projects/dvc/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/Users/pawelredzynski/development/projects/dvc/dvc/command/imp_url.py", line 14, in run
    self.repo.imp_url(
  File "/Users/pawelredzynski/development/projects/dvc/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/pawelredzynski/development/projects/dvc/dvc/repo/scm_context.py", line 14, in run
    return method(repo, *args, **kw)
  File "/Users/pawelredzynski/development/projects/dvc/dvc/repo/imp_url.py", line 83, in imp_url
    stage.run(jobs=jobs)
  File "/Users/pawelredzynski/.virtualenvs/dvc3.8/lib/python3.8/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/pawelredzynski/development/projects/dvc/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/Users/pawelredzynski/.virtualenvs/dvc3.8/lib/python3.8/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/pawelredzynski/development/projects/dvc/dvc/stage/__init__.py", line 532, in run
    self._sync_import(dry, force, jobs)
  File "/Users/pawelredzynski/.virtualenvs/dvc3.8/lib/python3.8/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/pawelredzynski/development/projects/dvc/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/Users/pawelredzynski/.virtualenvs/dvc3.8/lib/python3.8/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/pawelredzynski/development/projects/dvc/dvc/stage/__init__.py", line 556, in _sync_import
    sync_import(self, dry, force, jobs)
  File "/Users/pawelredzynski/development/projects/dvc/dvc/stage/imports.py", line 46, in sync_import
    stage.save_deps()
  File "/Users/pawelredzynski/development/projects/dvc/dvc/stage/__init__.py", line 467, in save_deps
    dep.save()
  File "/Users/pawelredzynski/development/projects/dvc/dvc/output.py", line 542, in save
    _, self.meta, obj = ostage(
  File "/Users/pawelredzynski/development/projects/dvc/dvc/objects/stage.py", line 334, in stage
    _, meta, obj = _stage_file(
  File "/Users/pawelredzynski/development/projects/dvc/dvc/objects/stage.py", line 98, in _stage_file
    meta, hash_info = get_file_hash(fs_path, fs, name, state=state)
  File "/Users/pawelredzynski/development/projects/dvc/dvc/objects/stage.py", line 90, in get_file_hash
    assert ".dir" not in hash_info.value
TypeError: argument of type 'int' is not iterable
------------------------------------------------------------
2021-11-11 12:50:51,005 DEBUG: Version info for developers:
DVC version: 2.8.4.dev3+g87fadd32 (osxpkg)
---------------------------------
Platform: Python 3.8.12 on macOS-11.6-x86_64-i386-64bit
Supports:
	azure (adlfs = 2021.9.1, knack = 0.8.2, azure-identity = 1.7.0),
	gdrive (pydrive2 = 1.10.0),
	gs (gcsfs = 2021.11.0),
	hdfs (fsspec = 2021.11.0, pyarrow = 5.0.0),
	webhdfs (fsspec = 2021.11.0),
	http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2021.11.0, boto3 = 1.17.106),
	ssh (sshfs = 2021.9.0),
	oss (ossfs = 2021.8.0),
	webdav (webdav4 = 0.9.3),
	webdavs (webdav4 = 0.9.3)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc (no_scm)

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

cc @efiop

**Comment by danstowell** [comment]
Hi - I suspect I'm hitting this same error. (I'm new to dvc.) I'm using dvc 2.12.0 (on ubuntu using pipx). It looks like the fix was merged back in Nov 2021, so it seems odd I'm still getting it. Here's my reproducer, does it also happen for you?

```
dvc --version
2.12.0

dvc import-url "https://archive.org/compress/freefield1010/formats=ZIP&file=/freefield1010.zip" data/raw
Importing 'https://archive.org/compress/freefield1010/formats=ZIP&file=/freefield1010.zip' -> 'data/raw/freefield1010.zip'
ERROR: unexpected error - argument of type 'int' is not iterable

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
zsh: exit 255   dvc import-url  data/raw

```
