### ISSUE TITLE
 [Errno 25] Inappropriate ioctl for device 

### ISSUE THREAD

**Issue by meiemari** [iterative/dvc#6980]
Dear Team,

we have been running dvc from a CircleCi job **successfully** for a while now. Recently, we have suddenly not been able to pull data anymore.                                                  

We are running a Linux machine (X large) on CircleCi. The error happens after our job runs `dvc pull -r s3-remote`. Any hints as to what is going on are highly appreciated.

How we install in the cloud:

pip3 install --upgrade pip
pip3 install "dvc[s3]"

**Output of dvc doctor:**

```DVC version: 2.8.3 (pip)
---------------------------------
Platform: Python 3.8.3 on Linux-4.4.0-1109-aws-x86_64-with-glibc2.17
Supports:
	webhdfs (fsspec = 2021.11.0),
	http (aiohttp = 3.8.0, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.0, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2021.11.0, boto3 = 1.17.106)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p1
Repo: dvc, git
If DVC froze, see `hardlink_lock` in <https://man.dvc.org/config#core     
```

**The error thrown:**

```2021-11-12 15:23:55,390 ERROR: unexpected error - [Errno 25] Inappropriate ioctl for device
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/command/data_sync.py", line 30, in run
    stats = self.repo.pull(
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/repo/pull.py", line 40, in pull
    stats = self.checkout(
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/repo/checkout.py", line 98, in checkout
    result = stage.checkout(
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/stage/__init__.py", line 572, in checkout
    key, outs = self._checkout(
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/stage/__init__.py", line 584, in _checkout
    result = out.checkout(**kwargs)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/output.py", line 751, in checkout
    modified = checkout(
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/checkout.py", line 301, in checkout
    _checkout(
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/checkout.py", line 247, in _checkout
    _checkout_file(
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/checkout.py", line 146, in _checkout_file
    _confirm_cache_type(cache, path_info)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/checkout.py", line 115, in _confirm_cache_type
    _link(cache, test_cache_file, workspace_file)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/checkout.py", line 95, in _link
    _try_links(cache, from_info, to_info, cache.cache_types)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/db/slow_link_detection.py", line 33, in wrapper
    return f(odb, *args, **kwargs)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/checkout.py", line 77, in _try_links
    _do_link(cache, from_info, to_info, link_method)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/checkout.py", line 65, in _do_link
    link_method(from_info, to_info)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/fs/local.py", line 161, in reflink
    System.reflink(from_info, to_info)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/system.py", line 113, in reflink
    System._reflink_linux(source, link_name)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/system.py", line 97, in _reflink_linux
    fcntl.ioctl(d.fileno(), FICLONE, s.fileno())
OSError: [Errno 25] Inappropriate ioctl for device
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/command/data_sync.py", line 30, in run
    stats = self.repo.pull(
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/repo/pull.py", line 40, in pull
    stats = self.checkout(
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/repo/checkout.py", line 98, in checkout
    result = stage.checkout(
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/stage/__init__.py", line 572, in checkout
    key, outs = self._checkout(
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/stage/__init__.py", line 584, in _checkout
    result = out.checkout(**kwargs)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/output.py", line 751, in checkout
    modified = checkout(
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/checkout.py", line 301, in checkout
    _checkout(
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/checkout.py", line 247, in _checkout
    _checkout_file(
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/checkout.py", line 146, in _checkout_file
    _confirm_cache_type(cache, path_info)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/checkout.py", line 115, in _confirm_cache_type
    _link(cache, test_cache_file, workspace_file)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/checkout.py", line 95, in _link
    _try_links(cache, from_info, to_info, cache.cache_types)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/db/slow_link_detection.py", line 33, in wrapper
    return f(odb, *args, **kwargs)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/checkout.py", line 77, in _try_links
    _do_link(cache, from_info, to_info, link_method)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/objects/checkout.py", line 65, in _do_link
    link_method(from_info, to_info)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/fs/local.py", line 161, in reflink
    System.reflink(from_info, to_info)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/system.py", line 113, in reflink
    System._reflink_linux(source, link_name)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/system.py", line 97, in _reflink_linux
    fcntl.ioctl(d.fileno(), FICLONE, s.fileno())
OSError: [Errno 25] Inappropriate ioctl for device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/3.8.3/bin/dvc", line 8, in <module>
    sys.exit(main())
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/main.py", line 88, in main
    dvc_info = get_dvc_info()
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/info.py", line 44, in get_dvc_info
    info.append(f"Cache types: {_get_linktype_support_info(repo)}")
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/info.py", line 102, in _get_linktype_support_info
    link(src, dst)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/system.py", line 113, in reflink
    System._reflink_linux(source, link_name)
  File "/opt/circleci/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dvc/system.py", line 97, in _reflink_linux
    fcntl.ioctl(d.fileno(), FICLONE, s.fileno())
OSError: [Errno 25] Inappropriate ioctl for device


Exited with code exit status 1
CircleCI received exit code 1 ```

**Comment by efiop** [comment]
@meiemari Hi! A workaround for now is to do `dvc config cache.type copy`(or rollback to 2.8.2). The error indicates that reflinks (which are default) are not supported, but we are not catching the error right now. Will send a fix ASAP. Thank you for the feedback! 🙏

**Comment by lucilemg** [comment]
Hello,

I encounter this problem when trying to repro a DVC stage.

Here's the output of **dvc doctor**
```
DVC version: 2.15.0 (pip)
---------------------------------
Platform: Python 3.9.13 on Linux-4.4.0-210-generic-x86_64-with-glibc2.23
Supports:
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
        s3 (s3fs = 2022.5.0, boto3 = 1.21.21)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p3
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p3
Repo: dvc, git
```

And the log I get when doing **dvc repro -s**
```
Running stage 'prepare_common_voice@fr_debug':
> python speech_to_text/data/common_voice/prepare.py speech_to_text/models/hparams/train.yaml --language fr_debug --corpus common_voice
torchvision is not available - cannot save figures
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 1343/1343 [00:00<00:00, 4761.61it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 4964.23it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 45/45 [00:00<00:00, 5318.37it/s]
2022-08-03 12:09:43,246 DEBUG: built tree 'object 3eb8f41e223c527a37fde6993fd0130c.dir'                                                              
2022-08-03 12:09:43,251 DEBUG: built tree 'object 4eb05a28fa89514d8d0bcf31ded07a5f.dir'                                                              
2022-08-03 12:09:43,292 DEBUG: Computed stage: 'prepare_common_voice@fr_debug' md5: '52f6d7c01410bcade5cbd52472174a3f'
2022-08-03 12:09:43,484 DEBUG: built tree 'object 3eb8f41e223c527a37fde6993fd0130c.dir'                                                              
2022-08-03 12:09:43,488 DEBUG: built tree 'object 4eb05a28fa89514d8d0bcf31ded07a5f.dir'                                                              
2022-08-03 12:09:43,710 DEBUG: built tree 'object 3eb8f41e223c527a37fde6993fd0130c.dir'                                                              
2022-08-03 12:09:43,715 DEBUG: built tree 'object 4eb05a28fa89514d8d0bcf31ded07a5f.dir'                                                              
2022-08-03 12:09:43,742 DEBUG: Preparing to transfer data from 'memory://dvc-staging/698678dbad98f16dad9aa3a004c7d9564bc67687058d46844c273ca68e21c8a7' to '/home/lucile/speech_repo/speech-models/.dvc/cache'
2022-08-03 12:09:43,742 DEBUG: Preparing to collect status from '/home/lucile/speech_repo/speech-models/.dvc/cache'
2022-08-03 12:09:43,743 DEBUG: Collecting status from '/home/lucile/speech_repo/speech-models/.dvc/cache'
2022-08-03 12:09:43,746 DEBUG: Preparing to collect status from 'memory://dvc-staging/698678dbad98f16dad9aa3a004c7d9564bc67687058d46844c273ca68e21c8a7'
2022-08-03 12:09:43,751 ERROR: failed to transfer 'md5: 2389c4c55532c3e365b0cfe6eaed0d2f' - [Errno 25] Inappropriate ioctl for device                
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc_data/transfer.py", line 31, in wrapper
    func(path, *args, **kwargs)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc_data/transfer.py", line 170, in func
    return dest.add(
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc_data/hashfile/db.py", line 77, in add
    super().add(path, fs, oid, hardlink=hardlink, callback=callback)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc_objects/db.py", line 112, in add
    generic.transfer(
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc_objects/fs/generic.py", line 97, in transfer
    _try_links(
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc_objects/fs/generic.py", line 68, in _try_links
    return _link(link, from_fs, from_path, to_fs, to_path)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc_objects/fs/generic.py", line 28, in _link
    func(from_path, to_path)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc_objects/fs/base.py", line 288, in reflink
    return self.fs.reflink(from_info, to_info)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc_objects/fs/implementations/local.py", line 157, in reflink
    return system.reflink(path1, path2)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc_objects/fs/system.py", line 105, in reflink
    _reflink_linux(source, link_name)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc_objects/fs/system.py", line 91, in _reflink_linux
    fcntl.ioctl(d.fileno(), FICLONE, s.fileno())
OSError: [Errno 25] Inappropriate ioctl for device
------------------------------------------------------------
2022-08-03 12:09:43,776 ERROR: failed to reproduce 'prepare_common_voice@fr_debug': 1 transfer failed                                                
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/repo/reproduce.py", line 204, in _reproduce_stages
    ret = _reproduce_stage(stage, **kwargs)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/repo/reproduce.py", line 41, in _reproduce_stage
    stage = stage.reproduce(**kwargs)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/stage/__init__.py", line 430, in reproduce
    self.run(**kwargs)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/stage/__init__.py", line 551, in run
    self.commit(allow_missing=allow_missing)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/stage/__init__.py", line 512, in commit
    out.commit(filter_info=filter_info)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/output.py", line 618, in commit
    otransfer(
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc_data/transfer.py", line 184, in transfer
    _do_transfer(
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc_data/transfer.py", line 119, in _do_transfer
    raise TransferError(total_fails)
dvc_data.transfer.TransferError: 1 transfer failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/commands/repro.py", line 13, in run
    stages = self.repo.reproduce(
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/repo/scm_context.py", line 156, in run
    return method(repo, *args, **kw)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/repo/reproduce.py", line 143, in reproduce
    return _reproduce_stages(self.index.graph, list(stages), **kwargs)
  File "/home/lucile/speech_repo/speech-models/.venv/lib/python3.9/site-packages/dvc/repo/reproduce.py", line 221, in _reproduce_stages
    raise ReproductionError(stage.addressing) from exc
dvc.exceptions.ReproductionError: failed to reproduce 'prepare_common_voice@fr_debug'
------------------------------------------------------------
2022-08-03 12:09:43,793 DEBUG: Analytics is enabled.
2022-08-03 12:09:43,957 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpxs0r9i6g']'
2022-08-03 12:09:43,959 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpxs0r9i6g']'
```

Any help would be greatly appreciated, thanks in advance!
Lucile

**Comment by marcosfelt** [comment]
I am getting the same error as @lucilemg on Linux with version 2.18.0

**Comment by pmrowla** [comment]
@marcosfelt what DVC command are you running

**Comment by marcosfelt** [comment]
@pmrowla  thanks for the reply, here are the outputs:
```
dvc doctor
DVC version: 2.18.0 (pip)
---------------------------------
Platform: Python 3.9.10 on Linux-4.4.0-184-generic-x86_64-with-glibc2.23
Supports:
	gdrive (pydrive2 = 1.14.0),
	hdfs (fsspec = 2022.7.1, pyarrow = 9.0.0),
	webhdfs (fsspec = 2022.7.1),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda2
Caches: local
Remotes: gdrive
Workspace directory: ext4 on /dev/sda2
Repo: dvc, git
```

```bash
dvc repro -s -f
Running stage 'reizman_etl':
> python multitask/etl_reizman_suzuki.py data/reizman_suzuki/ data/reizman_suzuki/ord/
Converting to ORD: 100%|████████████████████████████████████████| 96/96 [00:00<00:00, 203.34it/s]
First 5 Warnings. See data/reizman_suzuki/ord/warnings_reizman_suzuki_case_1.json for full output
['Dataset.reactions[0].workups[0]: Workup amount should only be specified if workup type is ALIQUOT or CUSTOM', 'Dataset.reactions[0].outcomes[0].products[0].measurements[0].percentage: Percentage values are 0-100, not fractions (0.6000000238418579 used)', 'Dataset.reactions[1].workups[0]: Workup amount should only be specified if workup type is ALIQUOT or CUSTOM', 'Dataset.reactions[1].outcomes[0].products[0].measurements[0].percentage: Percentage values are 0-100, not fractions (0.6000000238418579 used)', 'Dataset.reactions[2].workups[0]: Workup amount should only be specified if workup type is ALIQUOT or CUSTOM']
Converting to ORD: 100%|████████████████████████████████████████| 96/96 [00:00<00:00, 289.65it/s]
First 5 Warnings. See data/reizman_suzuki/ord/warnings_reizman_suzuki_case_2.json for full output
['Dataset.reactions[0].workups[0]: Workup amount should only be specified if workup type is ALIQUOT or CUSTOM', 'Dataset.reactions[0].outcomes[0].products[0].measurements[0].percentage: Percentage values are 0-100, not fractions (0.10000000149011612 used)', 'Dataset.reactions[1].workups[0]: Workup amount should only be specified if workup type is ALIQUOT or CUSTOM', 'Dataset.reactions[1].outcomes[0].products[0].measurements[0].percentage: Percentage values are 0-100, not fractions (0.10000000149011612 used)', 'Dataset.reactions[2].workups[0]: Workup amount should only be specified if workup type is ALIQUOT or CUSTOM']
Converting to ORD: 100%|████████████████████████████████████████| 96/96 [00:00<00:00, 254.79it/s]
First 5 Warnings. See data/reizman_suzuki/ord/warnings_reizman_suzuki_case_3.json for full output
['Dataset.reactions[0].workups[0]: Workup amount should only be specified if workup type is ALIQUOT or CUSTOM', 'Dataset.reactions[0].outcomes[0].products[0].measurements[0].percentage: Percentage values are 0-100, not fractions (0.20000000298023224 used)', 'Dataset.reactions[1].workups[0]: Workup amount should only be specified if workup type is ALIQUOT or CUSTOM', 'Dataset.reactions[1].outcomes[0].products[0].measurements[0].percentage: Percentage values are 0-100, not fractions (0.20000000298023224 used)', 'Dataset.reactions[2].workups[0]: Workup amount should only be specified if workup type is ALIQUOT or CUSTOM']
Converting to ORD: 100%|████████████████████████████████████████| 97/97 [00:00<00:00, 293.63it/s]
First 5 Warnings. See data/reizman_suzuki/ord/warnings_reizman_suzuki_case_4.json for full output
['Dataset.reactions[0].workups[0]: Workup amount should only be specified if workup type is ALIQUOT or CUSTOM', 'Dataset.reactions[1].workups[0]: Workup amount should only be specified if workup type is ALIQUOT or CUSTOM', 'Dataset.reactions[2].workups[0]: Workup amount should only be specified if workup type is ALIQUOT or CUSTOM', 'Dataset.reactions[3].workups[0]: Workup amount should only be specified if workup type is ALIQUOT or CUSTOM', 'Dataset.reactions[4].workups[0]: Workup amount should only be specified if workup type is ALIQUOT or CUSTOM']
ERROR: failed to transfer 'md5: 2c5bfc150fa9c0af7b97985fbfea6a71' - [Errno 25] Inappropriate ioctl for device
ERROR: failed to transfer 'md5: 16e1900b78b479c3129a295697aded79' - [Errno 25] Inappropriate ioctl for device
ERROR: failed to transfer 'md5: 58f73d5550db3f7437e07296ae6c715d' - [Errno 25] Inappropriate ioctl for device
ERROR: failed to transfer 'md5: 780c40231a5067d63f702f798b4ed7ff' - [Errno 25] Inappropriate ioctl for device
ERROR: failed to transfer 'md5: a16bfb874816e44f902c0e99ce722608' - [Errno 25] Inappropriate ioctl for device
ERROR: failed to transfer 'md5: bc1beba2988e86dc46512e2a2ad8e789' - [Errno 25] Inappropriate ioctl for device
ERROR: failed to transfer 'md5: a9a1e2187d5de79bf100ae63b962597c' - [Errno 25] Inappropriate ioctl for device
ERROR: failed to transfer 'md5: a0238d0dd9e90f828f928d333bb74536' - [Errno 25] Inappropriate ioctl for device
ERROR: failed to reproduce 'reizman_etl': 9 transfer failed
```

**Comment by pmrowla** [comment]
@marcosfelt @lucilemg can you please try the linked fix and see if it resolves the problem? You will need to update to the latest DVC pip release (should be 2.18.0) and then install the `dvc-objects` patch on top of that:

```
$ pip install -U dvc
$ pip install git+https://github.com/iterative/dvc-objects.git@refs/pull/120/head#egg=dvc_objects
```

**Comment by marcosfelt** [comment]
I just installed the patch and got this: 
```
dvc repro -s -f
Traceback (most recent call last):
  File "/home/kcmf2/.cache/pypoetry/virtualenvs/multitask-geS478Gs-py3.9/lib/python3.9/site-packages/dvc/cli/__init__.py", line 184, in main
    cmd = args.func(args)
  File "/home/kcmf2/.cache/pypoetry/virtualenvs/multitask-geS478Gs-py3.9/lib/python3.9/site-packages/dvc/cli/command.py", line 12, in __init__
    from dvc.repo import Repo
  File "/home/kcmf2/.cache/pypoetry/virtualenvs/multitask-geS478Gs-py3.9/lib/python3.9/site-packages/dvc/repo/__init__.py", line 13, in <module>
    from dvc.ignore import DvcIgnoreFilter
  File "/home/kcmf2/.cache/pypoetry/virtualenvs/multitask-geS478Gs-py3.9/lib/python3.9/site-packages/dvc/ignore.py", line 11, in <module>
    from dvc.fs import AnyFSPath, FileSystem, Schemes, localfs
  File "/home/kcmf2/.cache/pypoetry/virtualenvs/multitask-geS478Gs-py3.9/lib/python3.9/site-packages/dvc/fs/__init__.py", line 5, in <module>
    from dvc_objects.fs import (  # noqa: F401
ImportError: cannot import name 'FS_MAP' from 'dvc_objects.fs' (/home/kcmf2/.cache/pypoetry/virtualenvs/multitask-geS478Gs-py3.9/lib/python3.9/site-packages/dvc_objects/fs/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kcmf2/.cache/pypoetry/virtualenvs/multitask-geS478Gs-py3.9/bin/dvc", line 8, in <module>
    sys.exit(main())
  File "/home/kcmf2/.cache/pypoetry/virtualenvs/multitask-geS478Gs-py3.9/lib/python3.9/site-packages/dvc/cli/__init__.py", line 211, in main
    ret = _log_exceptions(exc) or 255
  File "/home/kcmf2/.cache/pypoetry/virtualenvs/multitask-geS478Gs-py3.9/lib/python3.9/site-packages/dvc/cli/__init__.py", line 69, in _log_exceptions
    from dvc.fs import AuthError, ConfigError, RemoteMissingDepsError
  File "/home/kcmf2/.cache/pypoetry/virtualenvs/multitask-geS478Gs-py3.9/lib/python3.9/site-packages/dvc/fs/__init__.py", line 5, in <module>
    from dvc_objects.fs import (  # noqa: F401
ImportError: cannot import name 'FS_MAP' from 'dvc_objects.fs' (/home/kcmf2/.cache/pypoetry/virtualenvs/multitask-geS478Gs-py3.9/lib/python3.9/site-packages/dvc_objects/fs/__init__.py
```

**Comment by pmrowla** [comment]
@marcosfelt I think you may need to rebuild your venv? Something seems out of date, nothing in current `dvc`/`dvc-data`/`dvc-objects` should be importing `FS_MAP`

**Comment by marcosfelt** [comment]
Took a little while to rebuild everything - it works! Thanks so much @pmrowla!

**Comment by marcosfelt** [comment]
One other note, I had to install the head of the dvc repository because 2.18.0 still had FS_MAP installed: https://github.com/iterative/dvc/blob/2e8b463795212b4252ab187d4bf8fc5017b78a2e/dvc/fs/__init__.py#L6

**Comment by courentin** [comment]
I think the issue is not resolve until `dvc-data` has been bump to at least `1.1.18`?
