### ISSUE TITLE
obj/s3: directory checksum for s3 fails with NotImplementedError

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#7023]
Reported from multiple users when adding/importing a directory on s3, the issue occurs in both `import-url` and `add --external`. Importing an individual file and `get-url` work normally as expected.

(reported against both `2.8.2 -  s3 (s3fs = 2021.10.1, boto3 = 1.19.7)` and `2.8.3 - s3 (s3fs = 2021.11.0, boto3 = 1.17.106)`

```pytb
dvc import-url --file data/raw.dvc s3://test/sample data/raw -v
2021-11-21 22:10:16,748 DEBUG: Lockfile 'dvc.lock' needs to be updated.
2021-11-21 22:10:16,834 DEBUG: Removing output 'data/raw/sample' of stage: 'data/raw.dvc'.
2021-11-21 22:10:16,834 DEBUG: Removing 'data/raw/sample'
Importing 's3://test/sample' -> 'data/raw/sample'
2021-11-21 22:10:16,839 DEBUG: Computed stage: 'data/raw.dvc' md5: '782d7c58160f763093fa1761aaea4bc5'
2021-11-21 22:10:16,839 DEBUG: 'md5' of stage: 'data/raw.dvc' changed.
2021-11-21 22:10:19,085 ERROR: unexpected error                                                                                                                                                
------------------------------------------------------------
Traceback (most recent call last):
...
    _, self.meta, obj = ostage(
  File "/root/.cache/pypoetry/virtualenvs/qt-expressions-classification-wj407T3L-py3.8/lib/python3.8/site-packages/dvc/objects/stage.py", line 296, in stage
    meta, obj = _stage_tree(
  File "/root/.cache/pypoetry/virtualenvs/qt-expressions-classification-wj407T3L-py3.8/lib/python3.8/site-packages/dvc/objects/stage.py", line 170, in _stage_tree
    meta, tree = _build_tree(path_info, fs, name, odb=odb, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/qt-expressions-classification-wj407T3L-py3.8/lib/python3.8/site-packages/dvc/objects/stage.py", line 138, in _build_tree
    for file_info, meta, obj in _iter_objects(path_info, fs, name, **kwargs):
  File "/root/.cache/pypoetry/virtualenvs/qt-expressions-classification-wj407T3L-py3.8/lib/python3.8/site-packages/dvc/objects/stage.py", line 130, in _iter_objects
    yield from _build_objects(path_info, fs, name, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/qt-expressions-classification-wj407T3L-py3.8/lib/python3.8/site-packages/dvc/objects/stage.py", line 126, in _build_objects
    yield from executor.map(worker, walk_iterator)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.cache/pypoetry/virtualenvs/qt-expressions-classification-wj407T3L-py3.8/lib/python3.8/site-packages/dvc/progress.py", line 133, in wrapped
    res = fn(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/qt-expressions-classification-wj407T3L-py3.8/lib/python3.8/site-packages/dvc/objects/stage.py", line 83, in _stage_file
    meta, hash_info = get_file_hash(path_info, fs, name, state=state)
  File "/root/.cache/pypoetry/virtualenvs/qt-expressions-classification-wj407T3L-py3.8/lib/python3.8/site-packages/dvc/objects/stage.py", line 72, in get_file_hash
    meta, hash_info = _get_file_hash(path_info, fs, name)
  File "/root/.cache/pypoetry/virtualenvs/qt-expressions-classification-wj407T3L-py3.8/lib/python3.8/site-packages/dvc/objects/stage.py", line 57, in _get_file_hash
    raise NotImplementedError
NotImplementedError
```

`add --external`:
```pytb
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/dvc/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/opt/conda/envs/dvc/lib/python3.9/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/opt/conda/envs/dvc/lib/python3.9/site-packages/dvc/command/add.py", line 21, in run
    self.repo.add(
  File "/opt/conda/envs/dvc/lib/python3.9/site-packages/dvc/utils/collections.py", line 163, in inner
    result = func(*ba.args, **ba.kwargs)
...
  File "/opt/conda/envs/dvc/lib/python3.9/site-packages/dvc/objects/stage.py", line 102, in _stage_file
    meta, hash_info = get_file_hash(path_info, fs, name, state=state)
  File "/opt/conda/envs/dvc/lib/python3.9/site-packages/dvc/objects/stage.py", line 90, in get_file_hash
    meta, hash_info = _get_file_hash(path_info, fs, name)
  File "/opt/conda/envs/dvc/lib/python3.9/site-packages/dvc/objects/stage.py", line 71, in _get_file_hash
    raise NotImplementedError
NotImplementedError
```

discord context (with full tracebacks):
- `add --external`: https://discord.com/channels/485586884165107732/485596304961962003/911253104694018058
- `import-url`: https://discord.com/channels/485586884165107732/485596304961962003/912074110790680646

**Comment by pmrowla** [comment]
I was unable to reproduce the issue with a simple test case and the `dvc-temp` bucket, will need to do more investigation into determining what causes the problem

**Comment by efiop** [comment]
for the record: From previous reports, it looked like this happens when operating on the whole bucket instead of a particular directory within it.

**Comment by arq-divjyotsingh** [comment]
I am facing same error as following , after running `dvc add --external s3://bucket_name/my_folder`

Note : I am trying add particular existing data in  `my_folder` in S3. The folder contains sub-dirs /train, /val, /test

```
 site-packages/dvc/objects/stage.py", line 57, in _get_file_hash
    raise NotImplementedError
```

**Comment by VOvchinnikov** [comment]
The same bug was observed, when using `gcsfs`

**Comment by dberenbaum** [comment]
@VOvchinnikov Support for external outputs in GCS was unfortunately dropped in DVC 2.0. See https://dvc.org/blog/dvc-2-0-release#breaking-changes. We would like to support it again in the future, but it is not being worked on at the moment, and would likely only happen after a refactor of external outputs.

cc @efiop

**Comment by dberenbaum** [comment]
@pmrowla @efiop Do you want to keep this as p1? Is there a plan to look into it further soon?

**Comment by pmrowla** [comment]
I think this can be p2 since the problem mostly occurs in the `--external` use case. But I think this is still a regression for `import-url` so it should be looked into some more at some point
