### ISSUE TITLE
dvc pull: unexpected error - [Errno 22] Bad Request

### ISSUE THREAD

**Issue by wdixon** [iterative/dvc#7034]
# Bug Report

## Description

I have several dvc resources imported into a project...  The tracking files (.dvc) are committed to the repository utilizing these resources.  When attempting to pull (dvc pull), the associated tracked resources - am getting an error:

An error occurred (400) when calling the HeadObject operation: Bad Request  (relevant log from dvc pull ---v below).

### Reproduce

Example:

1. dvc import resource into project
2. latter or from a fresh checkout of the above git repo and then attempt to dvc pull

### Expected

Expecting tracked resource to be retrieved from DVC.
I am able to perform a dvc update <resource> and that will pull the dvc resource into the folder structure, of course this causes the .dvc file to show as modified (even though it points to the same location/revision).

How to proceed here? something corrupted?

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.8.3 (pip)
---------------------------------
Platform: Python 3.8.0 on Linux-3.10.0-1160.45.1.el7.x86_64-x86_64-with-glibc2.27
Supports:
	webhdfs (fsspec = 2021.11.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2021.11.0, boto3 = 1.17.106)
Cache types: hardlink, symlink
Cache directory: nfs on LEB1MLNAS.company.com:/leb1mlnas_projects
Caches: local
Remotes: None
Workspace directory: nfs on LEB1MLNAS.company.com:/leb1mlnas_projects
Repo: dvc, git
```

```console
$ dvc pull -vvv

CUT......

2021-11-23 09:03:02,390 TRACE: Assuming '/projects/shared_dvc_cache/d6/9a712149e586998fb73c9566bd7e9f' is unchanged since it is read-only                                                                              
2021-11-23 09:03:02,394 DEBUG: Preparing to transfer data from 's3://dvc-inspection-ai/bit_tool_artifacts/RepoA' to '../../../../../../../shared_dvc_cache'                                                                                       
2021-11-23 09:03:02,394 DEBUG: Preparing to collect status from '../../../../../../../shared_dvc_cache'
2021-11-23 09:03:02,394 DEBUG: Collecting status from '../../../../../../../shared_dvc_cache'
2021-11-23 09:03:02,395 DEBUG: Preparing to collect status from 's3://dvc-inspection-ai/bit_tool_artifacts/RepoA'                                                                                                                                 
2021-11-23 09:03:02,396 DEBUG: Collecting status from 's3://dvc-inspection-ai/bit_tool_artifacts/RepoA'
2021-11-23 09:03:02,396 DEBUG: Querying 1 hashes via object_exists
2021-11-23 09:03:02,510 ERROR: unexpected error - [Errno 22] Bad Request: An error occurred (400) when calling the HeadObject operation: Bad Request                                                                                             
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/s3fs/core.py", line 250, in _call_s3
    out = await method(**additional_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/aiobotocore/client.py", line 155, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (400) when calling the HeadObject operation: Bad Request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/usr/local/lib/python3.8/dist-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/usr/local/lib/python3.8/dist-packages/dvc/command/data_sync.py", line 30, in run
    stats = self.repo.pull(
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/pull.py", line 29, in pull
    processed_files_count = self.fetch(
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/fetch.py", line 67, in fetch
    d, f = _fetch(
  File "/usr/local/lib/python3.8/dist-packages/dvc/repo/fetch.py", line 87, in _fetch
    downloaded += repo.cloud.pull(obj_ids, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dvc/data_cloud.py", line 114, in pull
    return transfer(
  File "/usr/local/lib/python3.8/dist-packages/dvc/objects/transfer.py", line 153, in transfer
    status = compare_status(src, dest, obj_ids, check_deleted=False, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dvc/objects/status.py", line 166, in compare_status
    src_exists, src_missing = status(
  File "/usr/local/lib/python3.8/dist-packages/dvc/objects/status.py", line 132, in status
    odb.hashes_exist(hashes, name=str(odb.path_info), **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dvc/objects/db/base.py", line 468, in hashes_exist
    remote_hashes = self.list_hashes_exists(hashes, jobs, name)
  File "/usr/local/lib/python3.8/dist-packages/dvc/objects/db/base.py", line 419, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dvc/objects/db/base.py", line 410, in exists_with_progress
    ret = self.fs.exists(path_info)
  File "/usr/local/lib/python3.8/dist-packages/dvc/fs/fsspec_wrapper.py", line 136, in exists
    return self.fs.exists(self._with_bucket(path_info))
  File "/usr/local/lib/python3.8/dist-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/usr/local/lib/python3.8/dist-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/usr/local/lib/python3.8/dist-packages/s3fs/core.py", line 822, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "/usr/local/lib/python3.8/dist-packages/s3fs/core.py", line 1016, in _info
    out = await self._call_s3(
  File "/usr/local/lib/python3.8/dist-packages/s3fs/core.py", line 270, in _call_s3
    raise err
OSError: [Errno 22] Bad Request
------------------------------------------------------------
2021-11-23 09:03:02,825 DEBUG: Version info for developers:
DVC version: 2.8.3 (pip)
---------------------------------
Platform: Python 3.8.0 on Linux-3.10.0-1160.45.1.el7.x86_64-x86_64-with-glibc2.27
Supports:
	webhdfs (fsspec = 2021.11.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2021.11.0, boto3 = 1.17.106)
Cache types: hardlink, symlink
Cache directory: nfs on LEB1MLNAS.company.com:/leb1mlnas_projects
Caches: local
Remotes: None
Workspace directory: nfs on LEB1MLNAS.company.com:/leb1mlnas_projects
Repo: dvc, git

```

**Comment by efiop** [comment]
@wdixon Hi. Are you using AWS s3 or some s3-compatible storage (like minio)? Does `awscli` work with it?

**Comment by wdixon** [comment]
This is an inhouse minio server.

The aws CLI works fine as far as I can tell - running listings/retrievals/etc...

aws s3api head-bucket --endpoint-url https://leb1minio.company.com --profile profile --bucket my-bucket
I don't know the actual command that you would be running that is causing the error?  If you have a suggestion of what should run as a test?

Running DVC import works.

**Comment by efiop** [comment]
@wdixon And could you try `aws s3api head-object` with some object?

**Comment by wdixon** [comment]
The head-object seems to work fine?

```code
$ aws s3api head-object --endpoint-url https://leb1minio.company.com --profile profile --bucket bucket --key datasets/regression/ff/14f36e28376fe0d1b22dd75409434f
{
    "AcceptRanges": "bytes",
    "LastModified": "Mon, 31 Aug 2020 12:05:53 GMT",
    "ContentLength": 5323,
    "ETag": "\"0135bdc1a8e6540e1b8619832d46eb26\"",
    "ContentType": "application/octet-stream",
    "Metadata": {}
}


```

**Comment by wdixon** [comment]
Is there a way to find out what the object is that is causing the error?

**Comment by efiop** [comment]
@wdixon Could you try lowering the number of jobs using `--jobs 1` or `--jobs 2`? E.g. let's try

```
dvc status -c -j1
```

to narrow it down.

**Comment by wdixon** [comment]
running dvc update --jobs 1 didn't change the error.


```console
wdixon@leb1mlgpu5:/projects$ dvc status
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
../S1FV_PS_A_20210725-161419-0500-0.0006.hdf5.dvc:                                                                                                                                                                                               
        changed outs:                                                                                                                                                                                                                            
                not in cache:       ../S1FV_PS_A_20210725-161419-0500-0.0006.hdf5                                                                                                                                                                
../S1SV_LETE_A_20210725-161432-0499-0.0003.hdf5.dvc:                                                                                                                                                                                             
        changed outs:                                                                                                                                                                                                                            
		not in cache:       ../S1SV_LETE_A_20210725-161432-0499-0.0003.hdf5
../S1SV_LETE_B_20210725-161432-0482-0.0002.hdf5.dvc:
	changed outs:
		not in cache:       ../S1SV_LETE_B_20210725-161432-0482-0.0002.hdf5
../S1SV_LETE_C_20210725-161419-0490-0.0004.hdf5.dvc:
	changed outs:
		not in cache:       ../S1SV_LETE_C_20210725-161419-0490-0.0004.hdf5
../S2SV_SS_A_20210725-161424-0489-0.0003.hdf5.dvc:
	changed outs:
		not in cache:       ../S2SV_SS_A_20210725-161424-0489-0.0003.hdf5
../../cal/UGP1HHF2P38B2_s1_fv.hdf5.dvc:
	changed outs:
		not in cache:       ../../cal/UGP1HHF2P38B2_s1_fv.hdf5
../../cal/UGP1HHF2P38B2_s1_sv.hdf5.dvc:
	changed outs:
		not in cache:       ../../cal/UGP1HHF2P38B2_s1_sv.hdf5
../../outline/07_26_2021/weights_S1FV_PS_A_UNetWithSoft_best_iou.hdf.dvc:
	changed outs:
		not in cache:       ../../outline/07_26_2021/weights_S1FV_PS_A_UNetWithSoft_best_iou.hdf
../../outline/07_26_2021/weights_S1SV_LETE_G_UNetWithSoft_best_iou.hdf.dvc:
	changed outs:
		not in cache:       ../../outline/07_26_2021/weights_S1SV_LETE_G_UNetWithSoft_best_iou.hdf
../../outline/07_26_2021/weights_S2SV_SS_A_UNetWithSoft_best_iou.hdf.dvc:
	changed outs:
		not in cache:       ../../outline/07_26_2021/weights_S2SV_SS_A_UNetWithSoft_best_iou.hdf
../../_rev/_revision_20200910-162354-0254-0.542.hdf5.dvc:
	changed outs:
		not in cache:       ../../_rev/_revision_20200910-162354-0254-0.542.hdf5
../../../../tests/data/ModelB/FSE/Project/Cyclops.dvc:
	changed deps:
		update available:   ModelB/FSE (https://github.build.company/datasets_regression.git)

wdixon@leb1mlgpu5:/projects$ dvc status -c -j1
Cache and remote 'None' are in sync.      
```

**Comment by efiop** [comment]
@wdixon What error? Doesn't look like there are any errors in the log (e.g. no more `Bad Request`). The `None` is really suspicious though, but that might be an unrelated bug.

Could you try `dvc pull -j1` ? It will take awhile, but if that works - maybe your server is getting overwhelmed with the requests or something. Btw, how many CPU cores do you have? We use 4*NCPU by default, might be a bit too much for your case.

**Comment by wdixon** [comment]
Sorry I had meant to say 

 dvc pull --jobs 1

produced the same error that I originally posted….

I am in a Linux vm - only 5 cpus - the minio endpoint is a reasonable size - and I am the only one currently interacting with it…. (Doubt it’s a capacity issue)

I get the same error on a Windows client 12core laptop… a colleague of mine also received the same error attempting access to the same repo

 The ‘none’ - I am guessing might be the git project doesn’t have its own dvc repo configured (remote), rather it only contains dvc imported resources…. Is that a clue?

**Comment by efiop** [comment]
@wdixon Oh, I see. Yeah, that's definitely a clue! So in the repo you are running `dvc pull` in, you only have `dvc import`ed artifacts? Are you able to clone those artifact's repo and run `dvc pull` there?

**Comment by wdixon** [comment]
> @efiop Oh, I see. Yeah, that's definitely a clue! So in the repo you are running `dvc pull` in, you only have `dvc import`ed artifacts? 

Yes - that is correct....  In this particular cases - all of the individually imported dvc artifacts originate in the same git artifacts repository. 

> @efiop Are you able to clone those artifact's repo and run `dvc pull` there?  

Yes - that work just fine...  I just performed 
1. git clone <artifacts_repo> 
2. dvc pull from within the artifacts repo.

**Comment by wdixon** [comment]
Just checking back to understand if you had any further thoughts on how to proceed?

**Comment by efiop** [comment]
@wdixon Hard to say what specifically is wrong in your case. You could try narrowing it down by trying to use https://github.com/fsspec/s3fs/ directly and going from there. We use s3fs internally, so if it works - it means that there is a problem on our side.

**Comment by wdixon** [comment]
Not entirely sure what you are asking me to do?  I don't have any visibility into what requested resource is failing?  It seems to be attempting to perform a head operation on some file that it is expecting to be there - but what file is that?  Is there additional logging that can be turned on to show this?

The command used already already had the -vvv flag
```code
dvc pull -vvv
```

If I knew what resource was attempting to head -  I could certainly attempt that with the s3fs or awscli directly?

**Comment by wdixon** [comment]
Also - what is different between a pull from the repo and a pull from an imported repo?  That seems to be some difference where its the imported resources that produce the error?

**Comment by efiop** [comment]
@wdixon If you could try, say, `dvc pull _rev/_revision_20200910-162354-0254-0.542.hdf5.dvc` or `dvc pull tests/data/ModelB/FSE/Project/Cyclops.dvc` to narrow down what specifically is failing, then open that .dvc file to get md5 for the artifact and inspect closer resulting resource url.

**Comment by efiop** [comment]
Closing as stale.
