### ISSUE TITLE
CI: `mypy` error while commit

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#7145]
# Bug Report

## Description

While committing changes on `dvc`, during the mypy check it errored out 
```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

Traceback (most recent call last):
  File "/Users/gao/anaconda3/envs/dvc/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 87, in main
  File "mypy/main.py", line 165, in run_build
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 254, in _build
  File "mypy/build.py", line 2644, in dispatch
  File "mypy/build.py", line 2868, in load_graph
  File "mypy/build.py", line 1848, in __init__
  File "mypy/build.py", line 1307, in validate_meta
  File "mypy/build.py", line 698, in getmtime
  File "mypy/metastore.py", line 90, in getmtime
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '.mypy_cache/3.8/dvc/daemon.data.json'
Traceback (most recent call last):
  File "/Users/gao/anaconda3/envs/dvc/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 87, in main
  File "mypy/main.py", line 165, in run_build
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 254, in _build
  File "mypy/build.py", line 2644, in dispatch
  File "mypy/build.py", line 2868, in load_graph
  File "mypy/build.py", line 1848, in __init__
  File "mypy/build.py", line 1307, in validate_meta
  File "mypy/build.py", line 698, in getmtime
  File "mypy/metastore.py", line 90, in getmtime
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '.mypy_cache/3.8/dvc/daemon.data.json'
Traceback (most recent call last):
  File "/Users/gao/anaconda3/envs/dvc/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 87, in main
  File "mypy/main.py", line 165, in run_build
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 254, in _build
  File "mypy/build.py", line 2644, in dispatch
  File "mypy/build.py", line 2868, in load_graph
  File "mypy/build.py", line 1848, in __init__
  File "mypy/build.py", line 1307, in validate_meta
  File "mypy/build.py", line 698, in getmtime
  File "mypy/metastore.py", line 90, in getmtime
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '.mypy_cache/3.8/dvc/daemon.data.json'
```

Deleting the `.mypy_cache` will temporarily solve it, but it appeared again sometime later.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

**Additional Information (if any):**

**Comment by pmrowla** [comment]
This is not happening in CI though, right? It looks like it's a local dev environment issue?

**Comment by skshetry** [comment]
This has happened to me a lot, this is one of the reason why I moved to nox on other projects.

If I remember correctly, I was using mypy command line tool and pre-commit mypy, which was causing issues with cache, but I never investigated and deleted the cache as you have done.

**Comment by karajan1001** [comment]
Not happened in CI yet, maybe because every time CI start from an empty env.

**Comment by maximvl** [comment]
This happens to me and fellow devs in our environment also. As someone who promotes type checking I would like to help finding the solution. We have a big project with on-commit mypy check and it doesn't fail like this often. Can I somehow help investigating this?

**Comment by skshetry** [comment]
Closing as stale
