### ISSUE TITLE
dvc pull -r origin: Cannot connect to host

### ISSUE THREAD

**Issue by Carllizca** [iterative/dvc#7148]
## Description

In the latest released (2.9.2) when I run "dvc pull -r origin" to download a file from google storage I get the following error:
"Cannot connect to host storage.googleapis.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]"

The error disappears by downgrading to version 2.8.3

### Reproduce

FROM google/cloud-sdk:latest

RUN apt-get --yes install wget
RUN wget \
       https://dvc.org/deb/dvc.list \
       -O /etc/apt/sources.list.d/dvc.list
RUN wget -qO - https://dvc.org/deb/iterative.asc | apt-key add -
RUN apt update
RUN apt install dvc

ENV GOOGLE_APPLICATION_CREDENTIALS "Google cloud credentials"
RUN gcloud auth activate-service-account --key-file "Google cloud credentials"

RUN dvc config core.no_scm true
RUN dvc pull -r origin

**Comment by karajan1001** [comment]
https://discord.com/channels/485586884165107732/485596304961962003/920652069734608928

Another example might be related to this.

**Comment by karajan1001** [comment]
@Carllizca Could you please:
1. show a more detailed log of `dvc pull -r origin -vv`.
2. try with `dvc` version 2.9.2 together with a `gcsfs` version `2021.11.0`
This will help us to know more about the details 
Thank you.

**Comment by Carllizca** [comment]
Hi @karajan1001,
1. Testing with `dvc` version 2.9.2 and `CLOUD_SDK_VERSION` 367.0.0:

Step 12/15 : RUN dvc pull -r origin -vv
 ---> Running in 85b7ec33fa79
2021-12-16 08:51:42,187 TRACE: Namespace(all_branches=False, all_commits=False, all_tags=False, cd='.', cmd='pull', cprofile=False, cprofile_dump=None, force=False, func=<class 'dvc.command.data_sync.CmdDataPull'>, glob=False, instrument=False, instrument_open=False, jobs=None, pdb=False, quiet=0, recursive=False, remote='origin', run_cache=False, targets=[], verbose=2, version=None, with_deps=False, yappi=False)
2021-12-16 08:51:42,400 DEBUG: Adding '/app/.dvc/config.local' to gitignore file.
2021-12-16 08:51:42,401 DEBUG: Adding '/app/.dvc/tmp' to gitignore file.
2021-12-16 08:51:42,402 DEBUG: Adding '/app/.dvc/cache' to gitignore file.
2021-12-16 08:51:42,711 DEBUG: Preparing to transfer data from 'gs://_cloud storage path_' to '/app/.dvc/cache'
2021-12-16 08:51:42,712 DEBUG: Preparing to collect status from '/app/.dvc/cache'
2021-12-16 08:51:42,712 DEBUG: Collecting status from '/app/.dvc/cache'
2021-12-16 08:51:42,713 DEBUG: Preparing to collect status from 'gs://_cloud storage path_''
2021-12-16 08:51:42,714 DEBUG: Collecting status from 'gs://_cloud storage path_''
2021-12-16 08:51:42,714 DEBUG: Querying 1 hashes via object_exists
_request out of retries on exception: Cannot connect to host storage.googleapis.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
Traceback (most recent call last):
  File "aiohttp/connector.py", line 986, in _wrap_create_connection
  File "asyncio/base_events.py", line 1050, in create_connection
  File "asyncio/base_events.py", line 1080, in _create_connection_transport
  File "asyncio/sslproto.py", line 529, in data_received
  File "asyncio/sslproto.py", line 189, in feed_ssldata
  File "ssl.py", line 944, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gcsfs/retry.py", line 115, in retry_request
  File "gcsfs/core.py", line 363, in _request
  File "aiohttp/client.py", line 1138, in __aenter__
  File "aiohttp/client.py", line 535, in _request
  File "aiohttp/connector.py", line 542, in connect
  File "aiohttp/connector.py", line 907, in _create_connection
  File "aiohttp/connector.py", line 1206, in _create_direct_connection
  File "aiohttp/connector.py", line 1175, in _create_direct_connection
  File "aiohttp/connector.py", line 988, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host storage.googleapis.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
2021-12-16 08:52:16,339 ERROR: unexpected error - Cannot connect to host storage.googleapis.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

Traceback (most recent call last):
  File "aiohttp/connector.py", line 986, in _wrap_create_connection
  File "asyncio/base_events.py", line 1050, in create_connection
  File "asyncio/base_events.py", line 1080, in _create_connection_transport
  File "asyncio/sslproto.py", line 529, in data_received
  File "asyncio/sslproto.py", line 189, in feed_ssldata
  File "ssl.py", line 944, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dvc/main.py", line 55, in main
  File "dvc/command/base.py", line 45, in do_run
  File "dvc/command/data_sync.py", line 30, in run
  File "dvc/repo/__init__.py", line 49, in wrapper
  File "dvc/repo/pull.py", line 29, in pull
  File "dvc/repo/__init__.py", line 49, in wrapper
  File "dvc/repo/fetch.py", line 40, in fetch
  File "dvc/repo/__init__.py", line 431, in used_objs
  File "dvc/repo/index.py", line 186, in used_objs
  File "dvc/stage/__init__.py", line 660, in get_used_objs
  File "dvc/output.py", line 940, in get_used_objs
  File "dvc/output.py", line 882, in _collect_used_dir_cache
  File "dvc/output.py", line 864, in get_dir_cache
  File "dvc/data_cloud.py", line 114, in pull
  File "dvc/objects/transfer.py", line 153, in transfer
  File "dvc/objects/status.py", line 164, in compare_status
  File "dvc/objects/status.py", line 122, in status
  File "dvc/objects/status.py", line 48, in _indexed_dir_hashes
  File "dvc/objects/db/base.py", line 421, in list_hashes_exists
  File "concurrent/futures/_base.py", line 611, in result_iterator
  File "concurrent/futures/_base.py", line 439, in result
  File "concurrent/futures/_base.py", line 388, in __get_result
  File "concurrent/futures/thread.py", line 57, in run
  File "dvc/objects/db/base.py", line 412, in exists_with_progress
  File "dvc/fs/fsspec_wrapper.py", line 91, in exists
  File "fsspec/asyn.py", line 91, in wrapper
  File "fsspec/asyn.py", line 71, in sync
  File "fsspec/asyn.py", line 25, in _runner
  File "fsspec/asyn.py", line 549, in _exists
  File "gcsfs/core.py", line 674, in _info
  File "gcsfs/core.py", line 452, in _get_object
  File "gcsfs/core.py", line 386, in _call
  File "decorator.py", line 221, in fun
  File "gcsfs/retry.py", line 147, in retry_request
  File "gcsfs/retry.py", line 115, in retry_request
  File "gcsfs/core.py", line 363, in _request
  File "aiohttp/client.py", line 1138, in __aenter__
  File "aiohttp/client.py", line 535, in _request
  File "aiohttp/connector.py", line 542, in connect
  File "aiohttp/connector.py", line 907, in _create_connection
  File "aiohttp/connector.py", line 1206, in _create_direct_connection
  File "aiohttp/connector.py", line 1175, in _create_direct_connection
  File "aiohttp/connector.py", line 988, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host storage.googleapis.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]

**Comment by tareqalmuntasir7** [comment]
I'm also facing the same issue. With dvc v2.9.2.

**Comment by pmrowla** [comment]
> I tried to manually install gcsfs version 2021.11.0 but it still uses version 2021.11.1 I don't know why.

You will have to install dvc via pip in order to be able to manually install a different gcsfs version. If you are installing from the binary package (the `.deb` ), that dvc binary will always use the dependencies bundled with the `.deb` package.

@Carllizca

**Comment by carlthome** [comment]
I'm also a deb package user hitting 

>ERROR: unexpected error - Cannot connect to host storage.googleapis.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

just now with dvc 2.9.3 and gcloud 368.0.0 - is there a quick & obvious fix for this or is the way forward to `pip install dvc` in a venv instead?

```
dvc doctor

DVC version: 2.9.3 (deb)
---------------------------------
Platform: Python 3.8.3 on Linux-5.13.0-22-generic-x86_64-with-glibc2.14
Supports:
        azure (adlfs = 2021.10.0, knack = 0.9.0, azure-identity = 1.7.1),
        gdrive (pydrive2 = 1.10.0),
        gs (gcsfs = 2021.11.1),
        hdfs (fsspec = 2021.11.1, pyarrow = 6.0.1),
        webhdfs (fsspec = 2021.11.1),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2021.11.1, boto3 = 1.19.8),
        ssh (sshfs = 2021.11.2),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.3),
        webdavs (webdav4 = 0.9.3)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/vgubuntu-root
Caches: local
Remotes: gs
Workspace directory: ext4 on /dev/mapper/vgubuntu-root
Repo: dvc, git
```

**Comment by efiop** [comment]
Looks related to https://github.com/iterative/dvc/issues/7207

**Comment by dtrifiro** [comment]
Hi @Carllizca does the workaround reported in #7207 work for you?

**Comment by bmccord2** [comment]
I was getting this issue with gcfs and dvc 2.9.3 installed via apt package.  The issue seemed to only occur when doing a "dvc push" rather than a pull (although I had nothing to pull, I got an "up to date" message with no errors).  I uninstalled the package and installed via pip (2.9.3) and it seems to have fixed the issue.  The only other thing I should add is it seems someone had already installed an earlier version of dvc via pip (2.8.1), and when I originally ran pip install it didn't actually do anything but it fixed the issue.. I then updated to 2.9.3 via pip and tried again and it seemed to work.   I mention this simply because I don't know what is causing this issue or much how certs are managed, so idk if *could* have been an issue with 2.9.x preventing the certificates from being resolved correctly, and then was resolved by using 2.8.1 and remained fixed when going back to 2.9.3.. but seems unlikely.

Oh actually, one more thing, for whatever reason this machine started resolving a lot of hostnames to ipv6 when it does not have a public ipv6 address, which was causing an issue before all of this.  Looking at the code I believe this was always a possibility since I think gcfs sets the resolver "family" for querying a host to AF_UNSPEC rather than AF_INET or something else.. whatever the case, I disabled ipv6 on the machine and that is when I began encountering the issue.  I do not *think* this was related, since my understanding is certificates are bound to names rather than ip addresses, but I thought I should mention it.

**Comment by WilliamHarvey97** [comment]
I had the same issue. It was solved by regenerating the certificate using certifi. To do so, run `Install Certificates.command` from your terminal. In my case, this script was under `/Applications/Python 3.9/Install Certificates.command`.

**Comment by dberenbaum** [comment]
Lowering the priority as it's not clear at this point whether it's even still an issue.

**Comment by efiop** [comment]
Closing as stale. Please let us know if this still happens for you.
