### ISSUE TITLE
sshfs: SFTP mkdir permission error on push

### ISSUE THREAD

**Issue by ansonuser** [iterative/dvc#7174]
# Bug Report

## Issue name
using command "dvc push -v"
asyncssh.sftp.SFTPPermissionDenied: Permission denied

## Description

I had some problems when using the command “dvc push”.  I wanted to add some data to the dataset. I pulled from the server and used “dvc push -v”. 

Then, the following error popped up.

```pytb
 2021-12-20 18:47:37,032 ERROR: failed to transfer 'md5: 1f18348f32c9a4694f16426798937ae2' - Permission denied
------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/dvc/1320/lib/python3.6/site-packages/dvc/objects/transfer.py", line 25, in wrapper
    func(path_info, *args, **kwargs)
  File "/snap/dvc/1320/lib/python3.6/site-packages/dvc/objects/transfer.py", line 160, in func
    obj.path_info, obj.fs, obj.hash_info, verify=verify, move=move
  File "/snap/dvc/1320/lib/python3.6/site-packages/dvc/objects/db/base.py", line 113, in add
    self._add_file(fs, path_info, cache_info, hash_info, move=move)
  File "/snap/dvc/1320/lib/python3.6/site-packages/dvc/objects/db/base.py", line 88, in _add_file
    self.makedirs(to_info.parent)
  File "/snap/dvc/1320/lib/python3.6/site-packages/dvc/objects/db/base.py", line 67, in makedirs
    self.fs.makedirs(path_info)
  File "/snap/dvc/1320/lib/python3.6/site-packages/dvc/fs/fsspec_wrapper.py", line 198, in makedirs
    self._with_bucket(path_info), exist_ok=kwargs.pop("exist_ok", True)
  File "/snap/dvc/1320/lib/python3.6/site-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/snap/dvc/1320/lib/python3.6/site-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/snap/dvc/1320/lib/python3.6/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/snap/dvc/1320/lib/python3.6/site-packages/sshfs/utils.py", line 27, in wrapper
    return await func(*args, **kwargs)
  File "/snap/dvc/1320/lib/python3.6/site-packages/sshfs/spec.py", line 232, in _makedirs
    await channel.makedirs(path, exist_ok=exist_ok, attrs=attrs)
  File "/snap/dvc/1320/lib/python3.6/site-packages/asyncssh/sftp.py", line 2609, in makedirs
    await self.mkdir(curpath, attrs)
  File "/snap/dvc/1320/lib/python3.6/site-packages/asyncssh/sftp.py", line 3293, in mkdir
    await self._handler.mkdir(path, attrs)
  File "/snap/dvc/1320/lib/python3.6/site-packages/asyncssh/sftp.py", line 1507, in mkdir
    return await self._make_request(FXP_MKDIR, String(path), attrs.encode())
  File "/snap/dvc/1320/lib/python3.6/site-packages/asyncssh/sftp.py", line 1189, in _make_request
    result = self._packet_handlers[resptype](self, resp)
  File "/snap/dvc/1320/lib/python3.6/site-packages/asyncssh/sftp.py", line 1221, in _process_status
    raise _construct_sftp_error(code, reason, lang)
asyncssh.sftp.SFTPPermissionDenied: Permission denied
```

### Reproduce
```bash
git clone $url
dvc pull 
mkdir test_data
vim test_data/test_file.txt
dvc add test_data
dvc push -v
```

### Expected

I tried ssh and sftp connection which worked well. Besides, I found that if I sampled data from the original dataset and made a copy to a new folder and pushed that folder to the server worked. I checked file permission, group and owner were all the same. Can’t figure it out .

### Environment information

My dvc version:

```console
DVC version: 2.7.2 (pip)
---------------------------------
Platform: Python 3.6.9 on Linux-5.4.0-90-generic-x86_64-with-Ubuntu-18.04-bionic
Supports:
	http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	ssh (sshfs = 2021.8.1)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda2
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/sda2
Repo: dvc, git
```
Is there a way to fix it ?
thank you !

**Comment by karajan1001** [comment]
Hello, @ansonuser 
Your `DVC` and `sshfs` version are quite old ones, could you please first upgrade to the latest version and then try it again?

**Comment by ansonuser** [comment]
Hello, @karajan1001 
After upgrade:
DVC version: 2.9.2 (pip)
---------------------------------
Platform: Python 3.7.12 on Linux-5.4.0-91-generic-x86_64-with-Ubuntu-18.04-bionic
Supports:
	webhdfs (fsspec = 2021.11.1),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	ssh (sshfs = 2021.11.2)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb2
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/sdb2
Repo: dvc, git
-----------------------------------
So sad, the result was same as before.

**Comment by karajan1001** [comment]
@ansonuser, Could you please give me the log from `dvc push -vv`. From the current info quite hard to know the reason for the permission denied.

**Comment by ansonuser** [comment]
Hi, @karajan1001
`dvc push --v ` got extra message:
2021-12-20 23:24:44,777 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/7a/9491a5762205ceb4e217a55d182212.dir' is unchanged since it is read-only
2021-12-20 23:24:44,778 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/7a/9491a5762205ceb4e217a55d182212.dir' is unchanged since it is read-only
2021-12-20 23:24:44,778 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/81/74178d16d3a2c6dbe791d86b7aa4fa.dir' is unchanged since it is read-only
2021-12-20 23:24:44,778 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/81/74178d16d3a2c6dbe791d86b7aa4fa.dir' is unchanged since it is read-only
2021-12-20 23:24:44,778 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/a0/86bff5e38c726517cdc2302ab105cf.dir' is unchanged since it is read-only
2021-12-20 23:24:44,778 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/a0/86bff5e38c726517cdc2302ab105cf.dir' is unchanged since it is read-only
2021-12-20 23:24:44,778 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/42/29b298b75468724b133fdccc654250.dir' is unchanged since it is read-only
2021-12-20 23:24:44,778 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/42/29b298b75468724b133fdccc654250.dir' is unchanged since it is read-only
2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/d7/51713988987e9331980363e24189ce.dir' is unchanged since it is read-only
2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/d7/51713988987e9331980363e24189ce.dir' is unchanged since it is read-only
2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/d7/51713988987e9331980363e24189ce.dir' is unchanged since it is read-only
2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/d7/51713988987e9331980363e24189ce.dir' is unchanged since it is read-only
2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/42/29b298b75468724b133fdccc654250.dir' is unchanged since it is read-only
2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/42/29b298b75468724b133fdccc654250.dir' is unchanged since it is read-only
2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/d7/51713988987e9331980363e24189ce.dir' is unchanged since it is read-only
2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/d7/51713988987e9331980363e24189ce.dir' is unchanged since it is read-only
2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/42/29b298b75468724b133fdccc654250.dir' is unchanged since it is read-only
2021-12-20 23:24:44,780 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/42/29b298b75468724b133fdccc654250.dir' is unchanged since it is read-only
2021-12-20 23:24:44,780 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/a0/86bff5e38c726517cdc2302ab105cf.dir' is unchanged since it is read-only
2021-12-20 23:24:44,780 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/a0/86bff5e38c726517cdc2302ab105cf.dir' is unchanged since it is read-only

some of files got different permission
![image](https://user-images.githubusercontent.com/33833371/146792046-2322fa4f-61dc-45f9-8d00-4e3fbd001000.png)

**Comment by karajan1001** [comment]
> Hi, @karajan1001 `dvc push -vv ` got extra message: 2021-12-20 23:24:44,777 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/7a/9491a5762205ceb4e217a55d182212.dir' is unchanged since it is read-only 2021-12-20 23:24:44,778 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/7a/9491a5762205ceb4e217a55d182212.dir' is unchanged since it is read-only 2021-12-20 23:24:44,778 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/81/74178d16d3a2c6dbe791d86b7aa4fa.dir' is unchanged since it is read-only 2021-12-20 23:24:44,778 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/81/74178d16d3a2c6dbe791d86b7aa4fa.dir' is unchanged since it is read-only 2021-12-20 23:24:44,778 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/a0/86bff5e38c726517cdc2302ab105cf.dir' is unchanged since it is read-only 2021-12-20 23:24:44,778 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/a0/86bff5e38c726517cdc2302ab105cf.dir' is unchanged since it is read-only 2021-12-20 23:24:44,778 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/42/29b298b75468724b133fdccc654250.dir' is unchanged since it is read-only 2021-12-20 23:24:44,778 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/42/29b298b75468724b133fdccc654250.dir' is unchanged since it is read-only 2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/d7/51713988987e9331980363e24189ce.dir' is unchanged since it is read-only 2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/d7/51713988987e9331980363e24189ce.dir' is unchanged since it is read-only 2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/d7/51713988987e9331980363e24189ce.dir' is unchanged since it is read-only 2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/d7/51713988987e9331980363e24189ce.dir' is unchanged since it is read-only 2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/42/29b298b75468724b133fdccc654250.dir' is unchanged since it is read-only 2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/42/29b298b75468724b133fdccc654250.dir' is unchanged since it is read-only 2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/d7/51713988987e9331980363e24189ce.dir' is unchanged since it is read-only 2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/d7/51713988987e9331980363e24189ce.dir' is unchanged since it is read-only 2021-12-20 23:24:44,779 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/42/29b298b75468724b133fdccc654250.dir' is unchanged since it is read-only 2021-12-20 23:24:44,780 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/42/29b298b75468724b133fdccc654250.dir' is unchanged since it is read-only 2021-12-20 23:24:44,780 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/a0/86bff5e38c726517cdc2302ab105cf.dir' is unchanged since it is read-only 2021-12-20 23:24:44,780 TRACE: Assuming '/media/plctekadmin/fba0e0cc-b376-484f-ba50-4cf22b96f260/home/plctekadmin/data/test_dvc/test_dvc_regional2/regional2_dataset_dvc/.dvc/cache/a0/86bff5e38c726517cdc2302ab105cf.dir' is unchanged since it is read-only
> 
> some of files got different permission ![image](https://user-images.githubusercontent.com/33833371/146792046-2322fa4f-61dc-45f9-8d00-4e3fbd001000.png)

Files stored in `dvc` cache are in a protected state, so the permission is `-r--r--r---` in default.

**Comment by lefos99** [comment]
Is there any update on that?
I have version `dvc==2.10.2` and the problem still exists for me. :disappointed:

**Comment by pmrowla** [comment]
@lefos99 in 2.10.2 you are probably encountering https://github.com/iterative/dvc/issues/7702 which we are still investigating. Can you try running your command with `-v` and double check which exception you get?

(This issue is regarding SSH/SFTP write permissions for files within an SSH remote, and #7702 is regarding not being able to connect to the remote at all)

**Comment by lefos99** [comment]
> @lefos99 in 2.10.2 you are probably encountering #7702 which we are still investigating. Can you try running your command with `-v` and double check which exception you get?
> 
> (This issue is regarding SSH/SFTP write permissions for files within an SSH remote, and #7702 is regarding not being able to connect to the remote at all)

Thanks for the reply @pmrowla .
I created a dummy `.txt` file and the ran `dvc push deleteme.txt.dvc  -vv`
This is what I get back:
```
(ihc_cell_detection_env) eleftherios@eleftherios-hyrican-pc:~/git/ihc_cell_detection/ihc_cell_detection/pd_l1$ dvc push deleteme.txt.dvc 
Enter a private key passphrase or a password for host '192.168.96.80' port '22' user 'mindpeak': 

ERROR: failed to transfer 'md5: 382047661eb063eb123e9be9dce25e54' - Permission denied                                                                                                                                                                                              
ERROR: failed to push data to the cloud - 1 files failed to upload                                                                                                                                                                                                                 
(ihc_cell_detection_env) eleftherios@eleftherios-hyrican-pc:~/git/ihc_cell_detection/ihc_cell_detection/pd_l1$ dvc push deleteme.txt.dvc  -vv
2022-05-12 09:35:40,793 TRACE: Namespace(all_branches=False, all_commits=False, all_tags=False, cd='.', cmd='push', cprofile=False, cprofile_dump=None, func=<class 'dvc.commands.data_sync.CmdDataPush'>, glob=False, instrument=False, instrument_open=False, jobs=None, parser=DvcParser(prog='dvc', usage=None, description='Data Version Control', formatter_class=<class 'argparse.RawTextHelpFormatter'>, conflict_handler='error', add_help=False), pdb=False, quiet=0, recursive=False, remote=None, run_cache=False, targets=['deleteme.txt.dvc'], verbose=2, version=None, viztracer=False, viztracer_depth=None, with_deps=False, yappi=False)
Enter a private key passphrase or a password for host '192.168.95.79' port '22' user 'mindpeak': 

2022-05-12 09:35:48,570 DEBUG: Preparing to transfer data from '/media/newhdd/data/ki67_er_pr/data/dvc_cache' to '/slidespeicher/projects/ki67_er_pr/data/annotations/dvc_setup'
2022-05-12 09:35:48,570 DEBUG: Preparing to collect status from '/slidespeicher/projects/ki67_er_pr/data/annotations/dvc_setup'
2022-05-12 09:35:48,570 DEBUG: Collecting status from '/slidespeicher/projects/ki67_er_pr/data/annotations/dvc_setup'
2022-05-12 09:35:48,571 DEBUG: Querying 1 hashes via object_exists                                                                                                                                                                                                                 
2022-05-12 09:35:49,025 DEBUG: Preparing to collect status from '/media/newhdd/data/ki67_er_pr/data/dvc_cache'                                                                                                                                                                     
2022-05-12 09:35:49,025 DEBUG: Collecting status from '/media/newhdd/data/ki67_er_pr/data/dvc_cache'
2022-05-12 09:35:49,026 TRACE: Assuming '/media/newhdd/data/ki67_er_pr/data/dvc_cache/38/2047661eb063eb123e9be9dce25e54' is unchanged since it is read-only                                                                                                                        
2022-05-12 09:35:49,031 ERROR: failed to transfer 'md5: 382047661eb063eb123e9be9dce25e54' - Permission denied                                                                                                                                                                      
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/dvc/data/transfer.py", line 25, in wrapper
    func(fs_path, *args, **kwargs)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/dvc/data/transfer.py", line 162, in func
    return dest.add(
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/dvc/objects/db.py", line 126, in add
    self._add_file(
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/dvc/objects/db.py", line 97, in _add_file
    self.makedirs(self.fs.path.parent(to_info))
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/dvc/objects/db.py", line 77, in makedirs
    self.fs.makedirs(fs_path)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/dvc/fs/base.py", line 312, in makedirs
    self.fs.makedirs(path, exist_ok=kwargs.pop("exist_ok", True))
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/fsspec/asyn.py", line 85, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/fsspec/asyn.py", line 65, in sync
    raise return_result
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/sshfs/utils.py", line 27, in wrapper
    return await func(*args, **kwargs)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/sshfs/spec.py", line 231, in _makedirs
    await channel.makedirs(path, exist_ok=exist_ok, attrs=attrs)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/asyncssh/sftp.py", line 4045, in makedirs
    await self.mkdir(curpath, attrs)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/asyncssh/sftp.py", line 4989, in mkdir
    await self._handler.mkdir(path, attrs)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/asyncssh/sftp.py", line 2769, in mkdir
    await self._make_request(FXP_MKDIR, String(path),
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/asyncssh/sftp.py", line 2370, in _make_request
    result = self._packet_handlers[resptype](self, resp)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/asyncssh/sftp.py", line 2386, in _process_status
    raise exc
asyncssh.sftp.SFTPPermissionDenied: Permission denied
------------------------------------------------------------
2022-05-12 09:35:49,035 ERROR: failed to push data to the cloud - 1 files failed to upload                                                                                                                                                                                         
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/dvc/repo/push.py", line 68, in push
    pushed += self.cloud.push(
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/dvc/data_cloud.py", line 85, in push
    return transfer(
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/dvc/data/transfer.py", line 176, in transfer
    _do_transfer(
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/dvc/data/transfer.py", line 116, in _do_transfer
    raise FileTransferError(total_fails)
dvc.exceptions.FileTransferError: 1 files failed to transfer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/dvc/commands/data_sync.py", line 58, in run
    processed_files_count = self.repo.push(
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/eleftherios/anaconda3/envs/ihc_cell_detection_env/lib/python3.8/site-packages/dvc/repo/push.py", line 72, in push
    raise UploadError(exc.amount)
dvc.exceptions.UploadError: 1 files failed to upload
------------------------------------------------------------
```

My `dvc doctor` looks like this:
```
DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.8.12 on Linux-5.4.0-109-generic-x86_64-with-glibc2.17
Supports:
	webhdfs (fsspec = 2022.3.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2021.5.0, boto3 = 1.17.49),
	ssh (sshfs = 2022.3.1)
Cache types: symlink
Cache directory: ext4 on /dev/sda
Caches: local
Remotes: ssh, s3
Workspace directory: ext4 on /dev/nvme1n1p6
Repo: dvc, git
```
With `dvc 2.3.0`, everything works fine though! :thinking:

**Comment by pmrowla** [comment]
It looks like the user you are connecting as doesn't have permissions for the SFTP mkdir call. Can you double check that if you `ssh` into that machine with the same user accoutn, you can manually create subdirectories in the DVC remote directory (using `mkdir`?

**Comment by lefos99** [comment]
> It looks like the user you are connecting as doesn't have permissions for the SFTP mkdir call. Can you double check that if you `ssh` into that machine with the same user account, you can manually create subdirectories in the DVC remote directory (using `mkdir`?

I tried to create a new dir (`mkdir dummy_folder`) in the remote DVC cache by using:

1. ssh -> `ssh user@local_ip` by using the same private key and it worked.
2. sftp -> ` sftp -i /home/eleftherios/.ssh/deep_priv_key_hetzner.openssh user@ip` and it also worked.

Apart from that, isn't it weird that it worked fine with exactly the same setup with older version of DVC?
(`dvc 2.10.2` vs `dvc 2.3.0`)

**Comment by pmrowla** [comment]
There are two different SSH backends used in those versions (we moved from using paramiko to sshfs/asyncssh)

**Comment by lefos99** [comment]
> There are two different SSH backends used in those versions (we moved from using paramiko to sshfs/asyncssh)

I see, but then I still don't get why I get the `asyncssh.sftp.SFTPPermissionDenied: Permission denied` error.

Btw my `.dvc/config` looks like this, if that helps
```
[core]
    remote = nas_remote
[cache]
    type = symlink
    dir = path_to_my_local_cahce
['remote "nas_remote"']
    url = ssh://192.168.96.80:/path_to_dvc_cahce
    verify = true
    keyfile = path_to_my_private_key
    user = mindpeak
    port = 22
    ask_password = true
```

**Comment by pmrowla** [comment]
@lefos99 can you share the options you are using in your SSH config (`~/.ssh/config`)? You can sanitize any private values, but the issue here may be that some particular option is causing the problem with asyncssh

**Comment by lefos99** [comment]
> @lefos99 can you share the options you are using in your SSH config (`~/.ssh/config`)? You can sanitize any private values, but the issue here may be that some particular option is causing the problem with asyncssh

Sure, here it is:
```
AddKeysToAgent yes
Host nas
        HostName 192.168.96.80
        User mindpeak
        Port 22
        IdentityFile path_to_my_private_key.openssh

```

After what you pointed out actually,
> There are two different SSH backends used in those versions (we moved from using paramiko to sshfs/asyncssh)

 I started playing around with [sshfs](https://pypi.org/project/sshfs/). I created the following script:
```Python
from sshfs import SSHFileSystem

fs = SSHFileSystem(
    '192.168.96.80',
    client_keys='path_to_my_private_key.openssh',
    passphrase='my_secret_passphrase',
    username='mindpeak',
    port=22
)
with fs.open('/slidespeicher/projects/ki67_er_pr/data/annotations/cell_classification/preanno/annotation.json') as stream:
    print(stream.read()) # works fine
with fs.open('/slidespeicher/projects/ki67_er_pr/data/annotations/deleteme.txt', 'wb') as stream:
    stream.write(b'Deleteme!') # works fine
fs.mkdir('/slidespeicher/projects/ki67_er_pr/data/annotations/deleteme') # I get the SFTPPermissionDenied
```
So for reading/writing files, `sshfs` works fine but it fails with the same error with creating a folder... :thinking:

**Comment by lefos99** [comment]
Okay, I found the issue!

In my local script with the [sshfs](https://pypi.org/project/sshfs/), instead of running:
```PYTHON
fs.mkdir('/slidespeicher/projects/ki67_er_pr/data/annotations/deleteme') # I get the SFTPPermissionDenied
```
I deactivate the flag `create_parents`
```PYTHON
fs.mkdir('/slidespeicher/projects/ki67_er_pr/data/annotations/deleteme/', create_parents=False)
```

If you have this flag activated, then [sshfs](https://pypi.org/project/sshfs/) tries to create the whole path, and my user (because is no admin) doesn't have a write access to all parent folders.

In my opinion, this flag should be de-activated by default in DVC.

**Comment by lefos99** [comment]
Glad that we found it @pmrowla . 
Thanks for the help! :slightly_smiling_face:

**Comment by pmrowla** [comment]
@lefos can you try installing this patch and see if it resolves your issue:
```
pip install git+https://github.com/pmrowla/asyncssh.git@sftp-makedir-parents#egg=asyncssh
```

**Comment by lefos99** [comment]
> @lefos can you try installing this patch and see if it resolves your issue:
> 
> ```
> pip install git+https://github.com/pmrowla/asyncssh.git@sftp-makedir-parents#egg=asyncssh
> ```

Yes, it does! :partying_face:
