### ISSUE TITLE
`exp run`: doesn't work with submodule as dependency

### ISSUE THREAD

**Issue by woodshop** [iterative/dvc#7186]
# Bug Report

## Description
`dvc exp run` fails and `dvc repro` runs successfully when a cmd is executed from inside of a submodule and the submodule is included as a dependency.

#### Set Up:
```bash
mkdir test
cd test

mkdir submodule
cd submodule
git init
echo "cp ../data/a.txt ../models/b.txt" > run.sh
git add run.sh
git commit -m "initial commit"

cd ..
mkdir main
cd main
git init
dvc init
dvc config cache.type=hardlink,symlink,copy
git submodule add ../submodule src
mkdir data
echo "test" > data/a.txt
mkdir models
dvc stage add -n cp -w src -d ../src -d ../data/a.txt -o ../models/b.txt bash run.sh
dvc repro
git add .
git commit -m "initial commit"
```

**This works**
`dvc repro -f`

**This fails:**
`dvc exp run -f`

**This also fails:**
`dvc exp run -f --temp`

### Expected

`dvc repro` and `dvc exp run` run and succeed similarly.

### Environment information
**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 2.9.2 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.11.0-1021-aws-x86_64-with-glibc2.29
Supports:
	hdfs (fsspec = 2021.10.1, pyarrow = 5.0.0),
	webhdfs (fsspec = 2021.10.1),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2021.10.1, boto3 = 1.17.106)
Cache types: hardlink, symlink
Cache directory: lustre on 172.16.38.30@tcp:/skl3jbmv
Caches: local
Remotes: s3
Workspace directory: lustre on 172.16.38.30@tcp:/skl3jbmv
Repo: dvc, git
```

**Additional Information (if any):**
There's an error in the verbose output that indicates
```console
ERROR: unexpected error - invalid data in index - invalid entry
```

**Comment by woodshop** [comment]
Wondering if this is related to an earlier resolved issue that I posted about. https://github.com/iterative/dvc/issues/5740

**Comment by pmrowla** [comment]
This is definitely a bug for the `--temp/--queue` use case, we don't handle submodules at all there. We probably need to be doing submodule pull/update in the temp workspaces that we create.

I'm not sure why `exp run` does not work for workspace runs though, as we should not have to do anything special there, since the submodule is already set up properly.

@woodshop it would help if you could provide the entire error traceback from the `-v` command output, the error message alone doesn't provide us with enough information to debug the issue.

**Comment by woodshop** [comment]
Apologies for the slow reply!

```shell
(tensorflow-stable) asarroff@neu:/fsx/test/main$ dvc exp run -f -v
2022-01-24 16:46:45,382 DEBUG: Detaching HEAD at 'HEAD'
2022-01-24 16:46:45,528 DEBUG: Stashing workspace
2022-01-24 16:46:45,565 DEBUG: No changes to stash
2022-01-24 16:46:45,782 DEBUG: Stashing changes in 'refs/exps/stash'
2022-01-24 16:46:45,891 DEBUG: Stashed experiment '13dd17b' with baseline '0f01676' for future execution.
2022-01-24 16:46:45,930 DEBUG: Restore HEAD to 'master'
2022-01-24 16:46:45,942 DEBUG: Detaching HEAD at '0f016762c88d617197e9ecdc07f29afdbcd468d5'
2022-01-24 16:46:45,973 DEBUG: Popping from stash 'refs/exps/stash'
2022-01-24 16:46:45,977 DEBUG: Applying stash commit '13dd17b166bf604c6c5dce2b591f6ab91d194bb7'
2022-01-24 16:46:46,023 DEBUG: Dropping 'refs/exps/stash@{0}'
2022-01-24 16:46:46,175 DEBUG: Running repro in '/fsx/test/main'
2022-01-24 16:46:46,175 DEBUG: Removing '/fsx/test/main/.dvc/tmp/repro.dat'
2022-01-24 16:46:47,786 DEBUG: Removing output 'models/b.txt' of stage: 'cp'.
2022-01-24 16:46:47,786 DEBUG: Removing 'models/b.txt'
Running stage 'cp':
> bash run.sh
2022-01-24 16:46:47,879 DEBUG: staged tree 'object md5: 7836100ad7371e5f9125fbeb2b24a8e5.dir'
2022-01-24 16:46:47,880 DEBUG: state save (144115339624538843, 18b8cc44b3ff9d08f37b0f235c09d9cd, 33) 7836100ad7371e5f9125fbeb2b24a8e5.dir
2022-01-24 16:46:47,895 DEBUG: state save (144115339624539057, 1643060807000000000, 5) d8e8fca2dc0f896fd7cb4cb0031ba249
2022-01-24 16:46:47,909 DEBUG: state save (144115339624539057, 1643060807000000000, 5) d8e8fca2dc0f896fd7cb4cb0031ba249
2022-01-24 16:46:47,911 DEBUG: Computed stage: 'cp' md5: '44286a707e35ea3bf08062b5fe4b7152'
2022-01-24 16:46:47,922 DEBUG: staged tree 'object md5: 7836100ad7371e5f9125fbeb2b24a8e5.dir'
2022-01-24 16:46:47,923 DEBUG: state save (144115339624538843, 18b8cc44b3ff9d08f37b0f235c09d9cd, 33) 7836100ad7371e5f9125fbeb2b24a8e5.dir
2022-01-24 16:46:47,935 DEBUG: staged tree 'object md5: 7836100ad7371e5f9125fbeb2b24a8e5.dir'
2022-01-24 16:46:47,936 DEBUG: state save (144115339624538843, 18b8cc44b3ff9d08f37b0f235c09d9cd, 33) 7836100ad7371e5f9125fbeb2b24a8e5.dir
2022-01-24 16:46:47,949 DEBUG: Preparing to transfer data from '.dvc/cache' to '.dvc/cache'
2022-01-24 16:46:47,956 DEBUG: Cache type 'reflink' is not supported: [Errno 95] Operation not supported
2022-01-24 16:46:47,962 DEBUG: Created 'copy': .dvc/cache/.cache_type_test_file -> models/.FbMDcG75ZPEQSMqkQadB8W
2022-01-24 16:46:47,962 DEBUG: Removing 'models/.FbMDcG75ZPEQSMqkQadB8W'
2022-01-24 16:46:47,963 DEBUG: Removing '.dvc/cache/.cache_type_test_file'
2022-01-24 16:46:47,964 DEBUG: Skipping copying for 'models/b.txt', since it is not a symlink or a hardlink.
2022-01-24 16:46:47,966 DEBUG: state save (144115339624539057, 1643060807000000000, 5) d8e8fca2dc0f896fd7cb4cb0031ba249
2022-01-24 16:46:47,986 DEBUG: state save (144115339624539057, 1643060807000000000, 5) d8e8fca2dc0f896fd7cb4cb0031ba249
2022-01-24 16:46:47,991 DEBUG: stage: 'cp' was reproduced

To track the changes with git, run:

	git add dvc.yaml data/a.txt src
2022-01-24 16:46:48,090 DEBUG: Commit to new experiment branch 'refs/exps/0f/016762c88d617197e9ecdc07f29afdbcd468d5/exp-1c9fb'
2022-01-24 16:46:48,148 DEBUG: Removing '/fsx/test/main/.dvc/tmp/exps/run/workspace.run'
2022-01-24 16:46:48,169 DEBUG: Restore HEAD to 'master'
2022-01-24 16:46:48,178 ERROR: unexpected error - invalid data in index - invalid entry
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/site-packages/dvc/command/experiments.py", line 614, in run
    results = self.repo.experiments.run(
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/site-packages/dvc/repo/experiments/__init__.py", line 993, in run
    return run(self.repo, *args, **kwargs)
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/site-packages/dvc/repo/experiments/run.py", line 32, in run
    return repo.experiments.reproduce_one(
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/site-packages/dvc/repo/experiments/__init__.py", line 436, in reproduce_one
    results = self._workspace_repro()
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/site-packages/dvc/repo/experiments/__init__.py", line 58, in wrapper
    ret = f(exp, *args, **kwargs)
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/site-packages/dvc/repo/experiments/__init__.py", line 844, in _workspace_repro
    return {exp_rev: exec_result.exp_hash}
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/site-packages/dvc/scm/git/__init__.py", line 416, in detach_head
    self.reset()
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/site-packages/dvc/scm/git/__init__.py", line 296, in _backend_func
    return func(*args, **kwargs)
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/site-packages/dvc/scm/git/backend/pygit2.py", line 469, in reset
    self.repo.index.read(False)
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/site-packages/pygit2/index.py", line 115, in read
    check_error(err, io=True)
  File "/home/asarroff/miniconda3/envs/tensorflow-stable/lib/python3.8/site-packages/pygit2/errors.py", line 65, in check_error
    raise GitError(message)
_pygit2.GitError: invalid data in index - invalid entry
------------------------------------------------------------
2022-01-24 16:46:50,428 DEBUG: Version info for developers:
DVC version: 2.8.3 (pip)
---------------------------------
Platform: Python 3.8.8 on Linux-4.15.0-1065-aws-x86_64-with-glibc2.10
Supports:
	webhdfs (fsspec = 2021.10.1),
	http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	s3 (s3fs = 2021.8.1, boto3 = 1.17.106)
Cache types: hardlink, symlink
Cache directory: lustre on 172.16.38.30@tcp:/skl3jbmv
Caches: local
Remotes: None
Workspace directory: lustre on 172.16.38.30@tcp:/skl3jbmv
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-01-24 16:46:50,434 DEBUG: Analytics is disabled.
```

**Comment by woodshop** [comment]
@pmrowla this issue is no longer "awaiting response" but I cannot change the label.

**Comment by woodshop** [comment]
Just wondering @daavoo if this issue is on any roadmap for resolution.

**Comment by pmrowla** [comment]
@woodshop unfortunately we have not been able to get to this issue yet, and it's not currently planned. There's a few submodule related `dvc exp` issues that are open, but given that it's not a very common setup (at least based on user reports we've received so far) we have had to prioritize other work over addressing the submodule problems.

**Comment by rick-van-veen** [comment]
I would actually like to see this working as well for the --temp, --queue case.

**Comment by dflatow** [comment]
Hey team -- I'm running into this same error message:

> ERROR: unexpected error - invalid data in index - invalid entry 

Also similarly, ` dvc repro -R` seems to work but `dvc exp run -R src/pipelines/` does not.

```
$ dvc doctor
DVC version: 3.33.4 (pip)
-------------------------
Platform: Python 3.10.13 on macOS-12.6-arm64-arm-64bit
Subprojects:
        dvc_data = 2.24.0
        dvc_objects = 2.0.1
        dvc_render = 1.0.0
        dvc_task = 0.3.0
        scmrepo = 1.6.0
Supports:
        http (aiohttp = 3.9.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.9.1, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.12.2, boto3 = 1.33.13)
Config:
        Global: /Users/dflatow/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/ceb4be7a51a3752fe6157394a646b490
```

**Comment by dflatow** [comment]
Not sure if different or related issue.

**Comment by dflatow** [comment]
Also unsure if this is related but some strange git things seem to be going on - DVC has added a few files (metric files) outside of my repo:

```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   ../../../../var/folders/2h/2_3k3c317ts84_86kzzcpqjh0000gn/T/tmprlj4wq1v/noise/evaluate/metrics/metrics.json
        new file:   ../../../../var/folders/2h/2_3k3c317ts84_86kzzcpqjh0000gn/T/tmptg4lvlwb/noise/evaluate/metrics/metrics.json
        new file:   ../../../../var/folders/2h/2_3k3c317ts84_86kzzcpqjh0000gn/T/tmpvjg0amiu/noise/evaluate/metrics/metrics.json
        new file:   ../../../../var/folders/2h/2_3k3c317ts84_86kzzcpqjh0000gn/T/tmpvjyepa6l/noise/evaluate/metrics/metrics.json

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    ../../../../var/folders/2h/2_3k3c317ts84_86kzzcpqjh0000gn/T/tmprlj4wq1v/noise/evaluate/metrics/metrics.json
        deleted:    ../../../../var/folders/2h/2_3k3c317ts84_86kzzcpqjh0000gn/T/tmptg4lvlwb/noise/evaluate/metrics/metrics.json
        deleted:    ../../../../var/folders/2h/2_3k3c317ts84_86kzzcpqjh0000gn/T/tmpvjg0amiu/noise/evaluate/metrics/metrics.json
        deleted:    ../../../../var/folders/2h/2_3k3c317ts84_86kzzcpqjh0000gn/T/tmpvjyepa6l/noise/evaluate/metrics/metrics.json
```

**Comment by dflatow** [comment]
hmmm seems the errant metrics files were created but not properly cleaned up in a tmp directory I was using for some testing.

**Comment by dflatow** [comment]
Ok so I think the issue here was due to some sort of git issue caused by running DVC Live in a temporary folder via python library with save_exp=True.
