### ISSUE TITLE
DVC push error using minIO SSL_verify

### ISSUE THREAD

**Issue by marleneelojmz** [iterative/dvc#7225]
# Bug Report

## Description

Hi! I'm working with DVC and for now I'm trying to connect my proyect with minIO (on permisse). 
everything works fine for dvc coommands but when I try to do thepush action the result is "Everything is up to date".
I have no more ideas to what is happen.

### Reproduce

1. dvc init
2. Copy dataset.zip to the directory
3. dvc add dataset.zip
4. dvc remote add -d  myremote https://localhost:9000/bucket_name
5. dvc remote modify --local myremote user miniouser
6. dvc remote modify --local myremote password miniopassword
7. dvc remote modify myremote ssl_verify true
8. dvc remote modify myremote ssl_verify C:/Users/username/.minio/certs/public.crt
9. dvc push

### Expected

when I try to do dvc push the output is: Everything is up to date.
Nothing happen

### Environment information

DVC version: 2.8.1 (pip)
---------------------------------
Platform: Python 3.6.8 on Windows-10-10.0.19041-SP0
Supports:
        gdrive (pydrive2 = 1.10.0),
        webhdfs (fsspec = 2021.11.0),
        http (aiohttp = 3.8.0, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.0, aiohttp-retry = 2.4.6)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: https
Workspace directory: NTFS on C:\
Repo: dvc, git

### Output of `dvc push -v`

```console
2022-01-04 16:58:04,421 DEBUG: Preparing to transfer data from '.dvc\cache' to 'https://localhost:9000/bucket_name'
2022-01-04 16:58:04,791 DEBUG: Preparing to collect status from 'https://localhost:9000/bucket_name'
2022-01-04 16:58:05,240 DEBUG: Collecting status from 'https://localhost:9000/bucket_name'
2022-01-04 16:58:05,627 DEBUG: Querying 1 hashes via object_exists
2022-01-04 16:58:07,181 DEBUG: Preparing to collect status from '.dvc\cache'
2022-01-04 16:58:07,184 DEBUG: Collecting status from '.dvc\cache'
2022-01-04 16:58:07,360 DEBUG: Uploading '.dvc\cache\4d\9bbf2d320477b9b8c1991e212b6727' to 'https://localhost:9000/4d/9bbf2d320477b9b8c1991e212b6727'   
2022-01-04 16:58:07,400 ERROR: failed to transfer 'md5: 4d9bbf2d320477b9b8c1991e212b6727' - 400, message='Bad Request', url=URL('https://localhost:9000/4d/9bbf2d320477b9b8c1991e212b6727')
------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\dvc\objects\transfer.py", line 25, in wrapper
    func(path_info, *args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\dvc\objects\transfer.py", line 160, in func
    obj.path_info, obj.fs, obj.hash_info, verify=verify, move=move
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\dvc\objects\db\base.py", line 113, in add
    self._add_file(fs, path_info, cache_info, hash_info, move=move)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\dvc\objects\db\base.py", line 90, in _add_file
    from_fs, from_info, self.fs, to_info, move=move
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\dvc\fs\utils.py", line 30, in transfer
    return to_fs.upload(from_info, to_info)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\dvc\fs\base.py", line 270, in upload
    os.fspath(from_info), to_info, callback=callback
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\dvc\fs\fsspec_wrapper.py", line 209, in put_file
    from_file, self._with_bucket(to_info), callback=callback, **kwargs
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\fsspec\asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\fsspec\asyn.py", line 71, in sync
    raise return_result
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\fsspec\asyn.py", line 25, in _runner
    result[0] = await coro
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\fsspec\implementations\http.py", line 303, in _put_file    
    self._raise_not_found_for_status(resp, rpath)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\fsspec\implementations\http.py", line 216, in _raise_not_found_for_status
    response.raise_for_status()
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\aiohttp\client_reqrep.py", line 1009, in raise_for_status  
    headers=self.headers,
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://localhost:9000/4d/9bbf2d320477b9b8c1991e212b6727')
------------------------------------------------------------
2022-01-04 16:58:07,471 ERROR: failed to push data to the cloud - 1 files failed to upload
------------------------------------------------------------
```

**Additional Information (if any):**

All is running on my local machine, I have been working dvc on a virtual environment for the project

Thanks for ideas!

**Comment by efiop** [comment]
@marleneelojmz Hi. I see that you are configuring it as an http remote, but you need to configure it as s3 remote and use custom endpoint. E.g. see s3-compatible storage in https://dvc.org/doc/command-reference/remote/add or https://stackoverflow.com/questions/67635688/installation-dvc-on-minio-storage

**Comment by marleneelojmz** [comment]
I found lot of information about s3 storage but my storage is on my local machine, minio is working on my disk E:/. 
Then I need to do a different configuration?

**Comment by efiop** [comment]
@marleneelojmz The links I've posted talk about minio in general, it doesnt' matter where it is actually running, you just need to configure s3 enpoint correctly.

**Comment by marleneelojmz** [comment]
Thank u very much. It's working now <3!!!
