### ISSUE TITLE
`conda install/update dvc-ssh` does not install the proper version of `sshfs` to allow us to work well with `dvc push`

### ISSUE THREAD

**Issue by ciaochiaociao** [iterative/dvc#7244]
# Bug Report

## Description

`conda install/update dvc-ssh` does not install the proper version of `sshfs`, which is `sshfs=3.0.0` now but should be `sshfs=1.1.1`.
This will trigger an error when `dvc push`.

### Reproduce

```
$ conda install -n dvc dvc-ssh  # or conda update
$ dvc push

ERROR: failed to push data to the cloud - URL 'ssh://' is supported but requires these missing dependencies: ['sshfs']. To install dvc with those dependencies, run:

        conda install -c conda-forge dvc-ssh

See <https://dvc.org/doc/install> for more info.

$ python -c "import sshfs"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cwhsu/anaconda3/envs/dvc/lib/python3.9/site-packages/sshfs/__init__.py", line 1, in <module>
    from sshfs.spec import SSHFileSystem
  File "/home/cwhsu/anaconda3/envs/dvc/lib/python3.9/site-packages/sshfs/spec.py", line 10, in <module>
    import asyncssh
  File "/home/cwhsu/anaconda3/envs/dvc/lib/python3.9/site-packages/asyncssh/__init__.py", line 31, in <module>
    from .agent import SSHAgentClient, SSHAgentKeyPair, connect_agent
  File "/home/cwhsu/anaconda3/envs/dvc/lib/python3.9/site-packages/asyncssh/agent.py", line 30, in <module>
    from .public_key import SSHKeyPair, load_default_keypairs, load_keypairs
  File "/home/cwhsu/anaconda3/envs/dvc/lib/python3.9/site-packages/asyncssh/public_key.py", line 32, in <module>
    from .crypto import ed25519_available, ed448_available
  File "/home/cwhsu/anaconda3/envs/dvc/lib/python3.9/site-packages/asyncssh/crypto/__init__.py", line 27, in <module>
    from .ec import ECDSAPrivateKey, ECDSAPublicKey, ECDH
  File "/home/cwhsu/anaconda3/envs/dvc/lib/python3.9/site-packages/asyncssh/crypto/ec.py", line 24, in <module>
    from cryptography.hazmat.backends.openssl import backend
  File "/home/cwhsu/anaconda3/envs/dvc/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/cwhsu/anaconda3/envs/dvc/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 64, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/home/cwhsu/anaconda3/envs/dvc/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
```

### Environment information

```
DVC version: 2.9.3 (conda)
---------------------------------
Platform: Python 3.9.9 on Linux-4.4.0-140-generic-x86_64-with-glibc2.23
Supports:
        gs (gcsfs = 2021.11.1),
        webhdfs (fsspec = 2021.11.1),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb1
Caches: local
Remotes: ssh, ssh, local, ssh, gs, local
Workspace directory: ext4 on /dev/sdb1
Repo: dvc, git
```

**Additional Information (if any):**

Current hack: `conda update -n dvc cryptography` will install the correct version of the `sshfs` needed.

**Comment by pmrowla** [comment]
The current version of `sshfs` is `2021.11.2`, and the conda `dvc-ssh` package installs `2021.8.1` or later: https://github.com/conda-forge/dvc-feedstock/blob/881269f01978023329f1dffd9086b15d539eeba2/recipe/meta.yaml#L208

I'm assuming you were referring to the `openssl` version and not `sshfs`?

I don't think this is an issue with the DVC or `sshfs` conda packages. openssl is a system package that `cryptography` depends on. And `cryptography` is a nesteddependency of `sshfs/asyncssh`.

The issue here is that OpenSSL 3.0 is only supported in cryptography 35.0.0 and later, while other versions work properly with OpenSSL 1.1.1. `sshfs`/`asyncssh` work with cryptography 2.8 and later (they changed versioning scheme after 3.4.x, so 35.0.x is essentially 3.5.x). Pinning OpenSSL versions is something that should be handled in the `cryptography` conda package (which we don't have any control over).

The workaround for this is just to manually update the cryptography package, which you've already found (`conda update -n cryptography`)
