### ISSUE TITLE
dvc push: Cannot combine AUTHORIZATION header with AUTH argument or credentials encoded in URL

### ISSUE THREAD

**Issue by ygbingo** [iterative/dvc#7301]
# Bug Report
## Description
When I use dvc push, I got this unexcepted error - "Cannot combine AUTHORIZATION header with AUTH argument or credentials encoded in URL".

### Reproduce

1. dvc init
2. Copy dataset.zip to the directory
3. dvc add dataset.zip
4. dvc remote add -d *** azure://***/***
5. dvc remote modify *** account_name *****
6. az cloud set -n AzureChinaCloud
7. az login
6. dvc push

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.10.0 on Linux-5.10.23-5.al8.x86_64-x86_64-with-glibc2.27
Supports:
        azure (adlfs = 2021.10.0, knack = 0.9.0, azure-identity = 1.7.1),
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: nfs4 on 122524a915-jtm8.cn-beijing.nas.aliyuncs.com:/user/gupengcheng
Caches: local
Remotes: azure, azure
Workspace directory: nfs4 on 122524a915-jtm8.cn-beijing.nas.aliyuncs.com:/user/gupengcheng
Repo: dvc, git

```

**Comment by pared** [comment]
@ygbingo could you post the stack trace for failing `dvc push -v`?

**Comment by ygbingo** [comment]
Sure, and thanks for your reply. When I run ```dvc push -v```, I got error like 
```
...
------------------------------------------------------------
2022-01-23 07:46:47,530 DEBUG: [Errno 95] no more link types left to try out: [Errno 95] 'reflink' is not supported by <class 'dvc.fs.local.LocalFileSystem'>: [Errno 95] Operation not supported
------------------------------------------------------------
...
```

And this is my ```dvc push -v``` output:
```
...
2022-01-23 07:46:47,618 DEBUG: Version info for developers:
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.10.0 on Linux-5.10.23-5.al8.x86_64-x86_64-with-glibc2.27
Supports:
        azure (adlfs = 2021.10.0, knack = 0.9.0, azure-identity = 1.7.1),
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: nfs4 on 122524a915-jtm8.cn-beijing.nas.aliyuncs.com:/user/gupengcheng
Caches: local
Remotes: azure, azure
Workspace directory: nfs4 on 122524a915-jtm8.cn-beijing.nas.aliyuncs.com:/user/gupengcheng
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-01-23 07:46:47,621 DEBUG: Analytics is enabled.
...
```

**Comment by pared** [comment]
@ygbingo Would it be possible to post the whole trace for `dvc push -v` command?

**Comment by ygbingo** [comment]
The whole ```dvc push -v``` output:
```
2022-01-25 08:37:07,521 DEBUG: Adding '/mnt/user/******/dvc/hello-dvc/.dvc/config.local' to gitignore file.
2022-01-25 08:37:07,531 DEBUG: Adding '/mnt/user/******/dvc/hello-dvc/.dvc/tmp' to gitignore file.
2022-01-25 08:37:07,532 DEBUG: Adding '/mnt/user/******/dvc/hello-dvc/.dvc/cache' to gitignore file.
2022-01-25 08:37:09,387 DEBUG: Preparing to transfer data from '/mnt/user/******/dvc/hello-dvc/.dvc/cache' to 'dvc/hello-dvc'
2022-01-25 08:37:09,387 DEBUG: Preparing to collect status from 'dvc/hello-dvc'
2022-01-25 08:37:09,387 DEBUG: Collecting status from 'dvc/hello-dvc'
2022-01-25 08:37:09,395 DEBUG: Querying 1 hashes via object_exists
2022-01-25 08:37:19,729 ERROR: unexpected error - DefaultAzureCredential failed to retrieve a token from the included credentials.                                   
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
        SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
        VisualStudioCodeCredential: Failed to get Azure user details from Visual Studio Code.
        AzureCliCredential: Timed out waiting for Azure CLI
        AzurePowerShellCredential: PowerShell is not installed
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/command/data_sync.py", line 57, in run
    processed_files_count = self.repo.push(
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/repo/push.py", line 56, in push
    pushed += self.cloud.push(
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/data_cloud.py", line 85, in push
    return transfer(
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/objects/transfer.py", line 153, in transfer
    status = compare_status(src, dest, obj_ids, check_deleted=False, **kwargs)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/objects/status.py", line 158, in compare_status
    dest_exists, dest_missing = status(
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/objects/status.py", line 131, in status
    exists.update(odb.hashes_exist(hashes, name=odb.fs_path, **kwargs))
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/objects/db/base.py", line 470, in hashes_exist
    remote_hashes = self.list_hashes_exists(hashes, jobs, name)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/objects/db/base.py", line 421, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/home/******/.conda/envs/py310/lib/python3.10/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/home/******/.conda/envs/py310/lib/python3.10/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/home/******/.conda/envs/py310/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/******/.conda/envs/py310/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/objects/db/base.py", line 412, in exists_with_progress
    ret = self.fs.exists(fs_path)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/fs/fsspec_wrapper.py", line 91, in exists
    return self.fs.exists(path)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/adlfs/spec.py", line 1375, in exists
    return sync(self.loop, self._exists, path)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/adlfs/spec.py", line 1397, in _exists
    if await bc.exists():
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 74, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 606, in exists
    process_storage_error(error)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 89, in process_storage_error
    raise storage_error
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 597, in exists
    await self._client.blob.get_properties(
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/storage/blob/_generated/aio/operations/_blob_operations.py", line 394, in get_properties
    pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 215, in run
    return await first_node.send(pipeline_request)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  [Previous line repeated 3 more times]
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication_async.py", line 73, in send
    await await_result(self.on_request, request)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/pipeline/_tools_async.py", line 36, in await_result
    return await result  # type: ignore
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication_async.py", line 51, in on_request
    self._token = await self._credential.get_token(*self._scopes)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/identity/aio/_credentials/default.py", line 143, in get_token
    return await super().get_token(*scopes, **kwargs)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/identity/aio/_credentials/chained.py", line 84, in get_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
        SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
        VisualStudioCodeCredential: Failed to get Azure user details from Visual Studio Code.
        AzureCliCredential: Timed out waiting for Azure CLI
        AzurePowerShellCredential: PowerShell is not installed
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
------------------------------------------------------------
2022-01-25 08:37:22,575 DEBUG: Adding '/mnt/user/******/dvc/hello-dvc/.dvc/config.local' to gitignore file.
2022-01-25 08:37:22,583 DEBUG: Adding '/mnt/user/******/dvc/hello-dvc/.dvc/tmp' to gitignore file.
2022-01-25 08:37:22,583 DEBUG: Adding '/mnt/user/******/dvc/hello-dvc/.dvc/cache' to gitignore file.
2022-01-25 08:37:22,602 DEBUG: [Errno 95] no more link types left to try out: [Errno 95] 'reflink' is not supported by <class 'dvc.fs.local.LocalFileSystem'>: [Errno 95] Operation not supported
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/command/data_sync.py", line 57, in run
    processed_files_count = self.repo.push(
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/repo/push.py", line 56, in push
    pushed += self.cloud.push(
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/data_cloud.py", line 85, in push
    return transfer(
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/objects/transfer.py", line 153, in transfer
    status = compare_status(src, dest, obj_ids, check_deleted=False, **kwargs)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/objects/status.py", line 158, in compare_status
    dest_exists, dest_missing = status(
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/objects/status.py", line 131, in status
    exists.update(odb.hashes_exist(hashes, name=odb.fs_path, **kwargs))
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/objects/db/base.py", line 470, in hashes_exist
    remote_hashes = self.list_hashes_exists(hashes, jobs, name)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/objects/db/base.py", line 421, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/home/******/.conda/envs/py310/lib/python3.10/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/home/******/.conda/envs/py310/lib/python3.10/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/home/******/.conda/envs/py310/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/******/.conda/envs/py310/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/objects/db/base.py", line 412, in exists_with_progress
    ret = self.fs.exists(fs_path)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/fs/fsspec_wrapper.py", line 91, in exists
    return self.fs.exists(path)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/adlfs/spec.py", line 1375, in exists
    return sync(self.loop, self._exists, path)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/adlfs/spec.py", line 1397, in _exists
    if await bc.exists():
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 74, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 606, in exists
    process_storage_error(error)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 89, in process_storage_error
    raise storage_error
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 597, in exists
    await self._client.blob.get_properties(
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/storage/blob/_generated/aio/operations/_blob_operations.py", line 394, in get_properties
    pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 215, in run
    return await first_node.send(pipeline_request)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  [Previous line repeated 3 more times]
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication_async.py", line 73, in send
    await await_result(self.on_request, request)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/pipeline/_tools_async.py", line 36, in await_result
    return await result  # type: ignore
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/core/pipeline/policies/_authentication_async.py", line 51, in on_request
    self._token = await self._credential.get_token(*self._scopes)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/identity/aio/_credentials/default.py", line 143, in get_token
    return await super().get_token(*scopes, **kwargs)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/azure/identity/aio/_credentials/chained.py", line 84, in get_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
        EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
        ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.
        SharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
        VisualStudioCodeCredential: Failed to get Azure user details from Visual Studio Code.
        AzureCliCredential: Timed out waiting for Azure CLI
        AzurePowerShellCredential: PowerShell is not installed
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/fs/utils.py", line 28, in _link
    func(from_path, to_path)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/fs/local.py", line 148, in reflink
    System.reflink(from_info, to_info)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/system.py", line 112, in reflink
    System._reflink_linux(source, link_name)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/system.py", line 96, in _reflink_linux
    fcntl.ioctl(d.fileno(), FICLONE, s.fileno())
OSError: [Errno 95] Operation not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/fs/utils.py", line 69, in _try_links
    return _link(link, from_fs, from_path, to_fs, to_path)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/fs/utils.py", line 32, in _link
    raise OSError(
OSError: [Errno 95] 'reflink' is not supported by <class 'dvc.fs.local.LocalFileSystem'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/fs/utils.py", line 124, in _test_link
    _try_links([link], from_fs, from_file, to_fs, to_file)
  File "/home/******/.conda/envs/py310/lib/python3.10/site-packages/dvc/fs/utils.py", line 77, in _try_links
    raise OSError(
OSError: [Errno 95] no more link types left to try out
------------------------------------------------------------
2022-01-25 08:37:22,604 DEBUG: Removing '/mnt/user/******/dvc/.9PahkiYVQ93jjc6nxYZshS.tmp'
2022-01-25 08:37:22,608 DEBUG: Removing '/mnt/user/******/dvc/.9PahkiYVQ93jjc6nxYZshS.tmp'
2022-01-25 08:37:22,612 DEBUG: Removing '/mnt/user/******/dvc/.9PahkiYVQ93jjc6nxYZshS.tmp'
2022-01-25 08:37:22,616 DEBUG: Removing '/mnt/user/******/dvc/hello-dvc/.dvc/cache/.irztLQBhq5esVT6WppBZ5m.tmp'
2022-01-25 08:37:22,693 DEBUG: Version info for developers:
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.10.0 on Linux-5.10.23-5.al8.x86_64-x86_64-with-glibc2.27
Supports:
        azure (adlfs = 2021.10.0, knack = 0.9.0, azure-identity = 1.7.1),
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: nfs4 on ******.cn-beijing.nas.aliyuncs.com:/user/******
Caches: local
Remotes: azure, azure
Workspace directory: nfs4 on ******.cn-beijing.nas.aliyuncs.com:/user/******
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-01-25 08:37:22,696 DEBUG: Analytics is enabled.
2022-01-25 08:37:22,772 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmp9qrmines']'
2022-01-25 08:37:22,774 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmp9qrmines']'
```

**Comment by ygbingo** [comment]
I have resolved it. I change my ```azure_storage_connection_string``` and ```pip install dvc[azure]``` resolved it. Thank you ~
