### ISSUE TITLE
BackBlaze B2 permission error

### ISSUE THREAD

**Issue by vladv14** [iterative/dvc#7372]
## Summary

I am getting an error when running ```dvc push```  command in python to push to a BackBlaze B2 (S3 compatible) remote.
https://www.backblaze.com/b2/docs/s3_compatible_api.html

Prior to that I have created a bucket on BackBlaze B2 (e.g. bucket-name) and added a virtual folder in it (e.g. folder-name).
Then in an existing git repo (monorepo), I have create a sub directory with ```cookiecutter https://github.com/drivendata/cookiecutter-data-science``` structure and subsequently added this sub directory to dvc tracking.

## Commands I ran
```
dvc init --subdir
dvc add data
```

```
dvc remote add -d b2 s3://bucket-name/folder-name
dvc remote modify b2 endpointurl https://s3.eu-central-003.backblazeb2.com
```

This successfully creates ```.dvc/config``` with the remote named ```b2``` added:
```
[core]
    analytics = false
    remote = b2

['remote "b2"']
    url = s3://bucket-name/folder-name
    endpointurl = https://s3.eu-central-003.backblazeb2.com
```

After that I added my access keys details:
```
dvc remote modify --local b2 access_key_id 'my-key'
dvc remote modify --local b2 secret_access_key 'my-secret'
```

Which appear in ```.dvc/config.local```:
```
['remote "b2"']
    access_key_id = my-key
    secret_access_key = my-secret
```

## Error I get

When running ```dvc push -v``` I get the following:
```
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/s3fs/core.py", line 261, in _call_s3
    out = await method(**additional_kwargs)
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/aiobotocore/client.py", line 225, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/dvc/command/data_sync.py", line 57, in run
    processed_files_count = self.repo.push(
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/dvc/repo/push.py", line 56, in push
    pushed += self.cloud.push(
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/dvc/data_cloud.py", line 85, in push
    return transfer(
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/dvc/objects/transfer.py", line 153, in transfer
    status = compare_status(src, dest, obj_ids, check_deleted=False, **kwargs)
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/dvc/objects/status.py", line 158, in compare_status
    dest_exists, dest_missing = status(
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/dvc/objects/status.py", line 122, in status
    exists = hashes.intersection(
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/dvc/objects/status.py", line 48, in _indexed_dir_hashes
    dir_exists.update(odb.list_hashes_exists(dir_hashes - dir_exists))
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/dvc/objects/db/base.py", line 421, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/dvc/objects/db/base.py", line 412, in exists_with_progress
    ret = self.fs.exists(fs_path)
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/dvc/fs/fsspec_wrapper.py", line 91, in exists
    return self.fs.exists(path)
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/s3fs/core.py", line 835, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/s3fs/core.py", line 1029, in _info
    out = await self._call_s3(
  File "/home/ubuntu/.virtualenvs/analytics/lib/python3.9/site-packages/s3fs/core.py", line 281, in _call_s3
    raise err
PermissionError: Forbidden
```

And I also get the same error when trying:
```
export AWS_ACCESS_KEY_ID='my-key'
export AWS_SECRET_ACCESS_KEY='my-secret'
dvc push
```

### BackBlaze S3 compatible API:
https://www.backblaze.com/b2/docs/s3_compatible_api.html

### I can successfully run the following and upload a test file using the key:
```python
import boto3
from boto3.s3.transfer import S3Transfer, TransferConfig


S3 = boto3.client('s3',
                  endpoint_url='https://s3.eu-central-003.backblazeb2.com/',
                  aws_access_key_id='my-key',
                  aws_secret_access_key='my-secret'
                  )
transfer = S3Transfer(S3, config=TransferConfig(use_threads=False))
transfer.upload_file(filename='requirements.txt', bucket="bucket-name", key='folder-name/test')
```

### BackBlaze key permissions
```
bypassGovernance, deleteBuckets, deleteFiles, deleteKeys, listBuckets, listFiles, listKeys, readBucketEncryption, readBucketRetentions, readBuckets, readFileLegalHolds, readFileRetentions, readFiles, shareFiles, writeBucketEncryption, writeBucketRetentions, writeBuckets, writeFileLegalHolds, writeFileRetentions, writeFiles, writeKeys
```

### DVC doctor output
```
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.9.5 on Linux-5.11.0-1021-aws-x86_64-with-glibc2.31
Supports:
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.1.0, boto3 = 1.20.24)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/xvda1
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/xvda1
Repo: dvc (subdir), git
```

### My subdir folder structure to which DVC tracking is applied
```
├── .dvc
├── .dvcignore
├── .env
├── .gitignore
├── LICENSE
├── Makefile
├── README.md
├── data
│   ├── external
│   ├── interim
│   ├── processed
│   └── raw
│       └── test.txt
├── data.dvc
├── docs
│   └── dvc_setup.md
├── models
├── notebooks
├── references
├── reports
│   └── figures
├── requirements.txt
├── setup.py
├── src
│   ├── __init__.py
│   ├── data
│   │   ├── __init__.py
│   │   └── make_dataset.py
│   ├── features
│   │   ├── __init__.py
│   │   └── build_features.py
│   ├── models
│   │   ├── __init__.py
│   │   ├── predict_model.py
│   │   └── train_model.py
│   └── visualization
│       ├── __init__.py
│       └── visualize.py
├── test_environment.py
└── tox.ini

```

**Comment by daavoo** [comment]
Traceback looks similar to https://github.com/iterative/dvc/issues/7238

**Comment by dacbd** [comment]
I wasn't able to reproduce this:

I ran:
```bash
#!/bin/bash
git init b2-dvc-test
pushd b2-dvc-test
virtualenv venv
source venv/bin/activate
pip install dvc[s3] > /dev/null
dvc init
mkdir data
echo "test data" > data/test.txt
dvc add data
dvc remote add -d b2 s3://dvc-test/objs
dvc remote modify b2 endpointurl https://s3.us-west-000.backblazeb2.com
dvc remote modify --local b2 access_key_id ***
dvc remote modify --local b2 secret_access_key ***
dvc push -v
sleep 2
dvc doctor
popd 
rm -rf b2-dvc-test

```

output:
```
dabarnes@ubuntu:~/projects$ ./cmds.sh 
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /home/dabarnes/projects/b2-dvc-test/.git/
~/projects/b2-dvc-test ~/projects
created virtual environment CPython3.9.5.final.0-64 in 75ms
  creator CPython3Posix(dest=/home/dabarnes/projects/b2-dvc-test/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/dabarnes/.local/share/virtualenv)
    added seed packages: pip==20.3.4, pkg_resources==0.0.0, setuptools==44.1.1, wheel==0.34.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Initialized DVC repository.

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|             <https://dvc.org/doc/user-guide/analytics>              |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: <https://dvc.org/doc>
- Get help and share ideas: <https://dvc.org/chat>
- Star us on GitHub: <https://github.com/iterative/dvc>
100% Adding...|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|1/1 [00:00, 25.29file/s]
                                                                                                                                                                                                                                                                                  
To track the changes with git, run:                                                                                                                                                                                                                                               

    git add data.dvc .gitignore

To enable auto staging, run:

	dvc config core.autostage true
Setting 'b2' as a default remote.
2022-02-11 13:46:46,595 DEBUG: Adding '/home/dabarnes/projects/b2-dvc-test/.dvc/config.local' to gitignore file.
2022-02-11 13:46:46,597 DEBUG: Adding '/home/dabarnes/projects/b2-dvc-test/.dvc/tmp' to gitignore file.
2022-02-11 13:46:46,597 DEBUG: Adding '/home/dabarnes/projects/b2-dvc-test/.dvc/cache' to gitignore file.
2022-02-11 13:46:46,722 DEBUG: Preparing to transfer data from '/home/dabarnes/projects/b2-dvc-test/.dvc/cache' to 'dvc-test/objs'
2022-02-11 13:46:46,722 DEBUG: Preparing to collect status from 'dvc-test/objs'
2022-02-11 13:46:46,722 DEBUG: Collecting status from 'dvc-test/objs'
2022-02-11 13:46:46,722 DEBUG: Querying 1 hashes via object_exists
2022-02-11 13:46:47,339 DEBUG: Estimated remote size: 4096 files                                                                                                                                                                                                                  
2022-02-11 13:46:47,339 DEBUG: Large remote ('4' hashes < '4.096' traverse weight), using object_exists for remaining hashes                                                                                                                                                      
2022-02-11 13:46:47,339 DEBUG: Querying 4 hashes via object_exists
2022-02-11 13:46:47,673 DEBUG: Preparing to collect status from '/home/dabarnes/projects/b2-dvc-test/.dvc/cache'                                                                                                                                                                  
2022-02-11 13:46:47,674 DEBUG: Collecting status from '/home/dabarnes/projects/b2-dvc-test/.dvc/cache'
2022-02-11 13:46:47,763 DEBUG: Uploading '/home/dabarnes/projects/b2-dvc-test/.dvc/cache/b8/1b1549ac3ea1f71ed48aea4f24bf4c' to 'dvc-test/objs/b8/1b1549ac3ea1f71ed48aea4f24bf4c'                                                                                                  
2022-02-11 13:46:47,774 DEBUG: Uploading '/home/dabarnes/projects/b2-dvc-test/.dvc/cache/07/359f9afff3f38b046de016839e78c6' to 'dvc-test/objs/07/359f9afff3f38b046de016839e78c6'                                                                                                  
2022-02-11 13:46:47,776 DEBUG: Uploading '/home/dabarnes/projects/b2-dvc-test/.dvc/cache/8c/5c78b4d2e8978164ba9a96d956386e' to 'dvc-test/objs/8c/5c78b4d2e8978164ba9a96d956386e'                                                                                                  
2022-02-11 13:46:49,159 DEBUG: Uploading '/home/dabarnes/projects/b2-dvc-test/.dvc/cache/5d/ad12b63632774c77c4f856922b5b92.dir' to 'dvc-test/objs/5d/ad12b63632774c77c4f856922b5b92.dir'                                                                                          
2022-02-11 13:46:50,349 DEBUG: Indexing pushed dir 'md5: 5dad12b63632774c77c4f856922b5b92.dir' with '3' nested files                                                                                                                                                              
4 files pushed                                                                                                                                                                                                                                                                    
2022-02-11 13:46:50,354 DEBUG: Analytics is enabled.                                                                                                                                                                                                                              
2022-02-11 13:46:50,381 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmppdd3pchf']'
2022-02-11 13:46:50,383 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmppdd3pchf']'
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.9.5 on Linux-5.11.0-49-generic-x86_64-with-glibc2.33
Supports:
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.1.0, boto3 = 1.20.24)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda3
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/sda3
Repo: dvc, git
~/projects
```

**Comment by vladv14** [comment]
After playing around and trying different keys and permissions, it turned our that **all newly created keys work** fine and don't have this issue. The key that I was using originally, which caused this issue, was an old key I created over 1 year ago, however it did not have have an expiry or any bucket restrictions. So a strange issue, which seems to be only happening when using an old BackBlaze key and leading this permission error.

Big thank you to Daniel @dacbd for helping to investigate this issue! Much appreciated.
