### ISSUE TITLE
diff: Fails on duplicate commits

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7398]
While looking into #6729, I found that using the same commit for both revision arguments in `dvc diff` results in an error:

```
$ dvc diff -v 16ba2cd 16ba2cd
2022-02-17 13:52:53,456 ERROR: unexpected error - '16ba2cd'
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dave/Code/dvc/dvc/cli/__init__.py", line 78, in main
    ret = cmd.do_run()
  File "/Users/dave/Code/dvc/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/Users/dave/Code/dvc/dvc/commands/diff.py", line 125, in run
    diff = self.repo.diff(
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/diff.py", line 54, in diff
    old = results[a_rev]
KeyError: '16ba2cd'
...
```

Even with different revisions pointing to the same commit, it fails:

```
$ dvc diff -v $(git rev-parse --short HEAD) HEAD
2022-02-17 14:22:44,063 ERROR: unexpected error - '258fbff'
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dave/Code/dvc/dvc/cli/__init__.py", line 78, in main
    ret = cmd.do_run()
  File "/Users/dave/Code/dvc/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/Users/dave/Code/dvc/dvc/commands/diff.py", line 125, in run
    diff = self.repo.diff(
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/diff.py", line 54, in diff
    old = results[a_rev]
KeyError: '258fbff'
...
```

It looks like the brancher is returning comma-separated keys like `16ba2cd,16ba2cd`, but a simple key like `16ba2cd` is expected here:

https://github.com/iterative/dvc/blob/0b18efb7b7cea1d2b76d1ab450266b1551eeee84/dvc/repo/diff.py#L54

May also be related to #7265.

**Comment by skshetry** [comment]
Looks like this is fixed, and returns empty results as expected.
