### ISSUE TITLE
api.open: Write mode doesn't work with rev argument

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#7405]
# Bug Report

## Description

Error when using `dvc.api.open("foo", rev="HEAD", mode="w")`. See below for full error.

It's easy enough to work around this, but we should either fix it or not support write mode.

### Reproduce

In a fresh git+dvc repo, I added a `foo` file and committed:

```bash
$ echo foo > foo
$ git add foo
$ git commit -m "adds foo"
```

Then I tried to write a copy with `dvc.api.open()`:

```python
>>> with dvc.api.open("foo", mode="w") as f:
...     f.write("foo_copy")
...
8
>>> with dvc.api.open("foo", rev="HEAD", mode="w") as f:
...     f.write("foo_copy")
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dave/miniforge3/envs/example-get-started/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/dave/Code/dvc/dvc/api.py", line 76, in _open
    with _repo.open_by_relpath(
  File "/Users/dave/miniforge3/envs/example-get-started/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 499, in open_by_relpath
    with fs.open(
  File "/Users/dave/Code/dvc/dvc/fs/repo.py", line 228, in open
    return fs.open(path, mode=mode, encoding=encoding)
  File "/Users/dave/Code/dvc/dvc/fs/fsspec_wrapper.py", line 80, in open
    return self.fs.open(path, mode=mode)
  File "/Users/dave/miniforge3/envs/example-get-started/lib/python3.8/site-packages/fsspec/spec.py", line 997, in open
    self.open(
  File "/Users/dave/miniforge3/envs/example-get-started/lib/python3.8/site-packages/fsspec/spec.py", line 1009, in open
    f = self._open(
  File "/Users/dave/miniforge3/envs/example-get-started/lib/python3.8/site-packages/scmrepo/fs.py", line 84, in _open
    raise NotImplementedError
NotImplementedError
```

### Expected

Being able to write a file from a specified revision.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.9.4.dev58+g47481219
---------------------------------
Platform: Python 3.8.5 on macOS-10.16-x86_64-i386-64bit
Supports:
        gdrive (pydrive2 = 1.7.3),
        hdfs (fsspec = 2022.1.0, pyarrow = 3.0.0),
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.7.3, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.3, aiohttp-retry = 2.4.6),
        ssh (sshfs = 2021.11.2)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: local
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
```

**Comment by pmrowla** [comment]
It seems like write mode should just not be supported at all here. If you are writing to a file associated with a specific git revision, wouldn't this require rewriting git history?

Actually, is write mode even something that should be supported in `api.open` at all (with or without rev)?

**Comment by pmrowla** [comment]
If anything this sounds more like a `dvcx` scenario where a write actually requires
- modify the file
- `dvc commit` the changes if it's a DVC tracked file
- `git add + git commit` the changes to relevant files

**Comment by dberenbaum** [comment]
Yeah, it shouldn't be supported at all. Sorry, going through too many issues 😄 . So we probably need:

1. A better error.
2. Fix the docs to specify supported modes ("r"/"rb"). cc @jorgeorpinel

**Comment by dberenbaum** [comment]
Yeah, it shouldn't be supported. Going through too many issues 😄 . It would be nice to have a better error message and maybe document when write mode isn't supported.
