### ISSUE TITLE
dvc: openSSL failed to load certificates

### ISSUE THREAD

**Issue by fnareoh** [iterative/dvc#7429]
Hi, thank you for this dataset and repository, it is very inspiring! :D

I managed to re-generate the dataset using the scripts but I can't figure out the dvc get commands...

I always get `ERROR: unexpected error - OpenSSL error: failed to load certificates` which I googled but don't see any obvious way to fix it :/ 
Here is the verbose log:

```
$ dvc -v get https://github.com/iterative/aita_dataset aita_clean.csv -v
2022-03-01 21:33:20,621 DEBUG: Creating external repo https://github.com/iterative/aita_dataset@None
2022-03-01 21:33:20,621 DEBUG: erepo: git clone 'https://github.com/iterative/aita_dataset' to a temporary dir
2022-03-01 21:33:40,302 DEBUG: Removing '/home/fnareoh/Documents/aita_dataset/.RscaXVboDTamk3mraEb6Eq'                         
2022-03-01 21:33:40,303 ERROR: unexpected error - OpenSSL error: failed to load certificates: error:00000000:lib(0):func(0):reason(0)
------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/dvc/cli/__init__.py", line 78, in main
    ret = cmd.do_run()
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/dvc/cli/command.py", line 36, in do_run
    return self.run()
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/dvc/commands/get.py", line 33, in run
    return self._get_file_from_repo()
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/dvc/commands/get.py", line 39, in _get_file_from_repo
    Repo.get(
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/dvc/repo/get.py", line 49, in get
    with external_repo(
  File "/var/lib/snapd/snap/dvc/1321/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/dvc/external_repo.py", line 72, in external_repo
    repo = Repo(**repo_kwargs)
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/dvc/repo/__init__.py", line 176, in __init__
    self.root_dir, self.dvc_dir, self.tmp_dir = self._get_repo_dirs(
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/dvc/repo/__init__.py", line 95, in _get_repo_dirs
    root_dir = self.find_root(root_dir, fs)
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/dvc/repo/__init__.py", line 321, in find_root
    if not fs.isdir(root_dir):
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/dvc/fs/fsspec_wrapper.py", line 53, in isdir
    return self.fs.isdir(path)
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/funcy/objects.py", line 50, in __get__
    return prop.__get__(instance, type)
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/dvc/fs/git.py", line 48, in fs
    return FsspecGitFileSystem(**self.fs_args)
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/fsspec/spec.py", line 68, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/scmrepo/fs.py", line 53, in __init__
    resolved = resolver(scm, rev or "HEAD")
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/dvc/scm.py", line 117, in resolve_rev
    return scm.resolve_rev(fix_exp_head(scm, rev))
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/scmrepo/git/__init__.py", line 250, in _backend_func
    for backend in self.backends.values():
  File "/var/lib/snapd/snap/dvc/1321/bin/../usr/lib/python3.8/_collections_abc.py", line 762, in __iter__
    yield self._mapping[key]
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/scmrepo/git/__init__.py", line 45, in __getitem__
    initialized = backend(*self.args, **self.kwargs)
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/scmrepo/git/backend/pygit2.py", line 77, in __init__
    import pygit2
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/pygit2/__init__.py", line 230, in <module>
    settings = Settings()
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/pygit2/settings.py", line 55, in __init__
    self._initialize_tls_certificate_locations()
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/pygit2/settings.py", line 61, in _initialize_tls_certificate_locations
    self.set_ssl_cert_locations(
  File "/var/lib/snapd/snap/dvc/1321/lib/python3.8/site-packages/pygit2/settings.py", line 191, in set_ssl_cert_locations
    option(_pygit2.GIT_OPT_SET_SSL_CERT_LOCATIONS, cert_file, cert_dir)
_pygit2.GitError: OpenSSL error: failed to load certificates: error:00000000:lib(0):func(0):reason(0)
------------------------------------------------------------
2022-03-01 21:33:41,060 DEBUG: Version info for developers:
DVC version: 2.9.5 (snap)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.176-1-MANJARO-x86_64-with-glibc2.29
Supports:
	azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.7.1),
	gdrive (pydrive2 = 1.10.0),
	gs (gcsfs = 2022.2.0),
	webhdfs (fsspec = 2022.2.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.2.0, boto3 = 1.20.24),
	ssh (sshfs = 2021.11.2)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: https
Workspace directory: ext4 on /dev/sdb2
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-03-01 21:33:41,061 DEBUG: Analytics is enabled.
2022-03-01 21:33:41,179 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmp_wwi02hd']'
2022-03-01 21:33:41,181 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmp_wwi02hd']'
```

**Comment by dtrifiro** [comment]
Cannot reproduce on a fresh snap install (rev 1321) on ubuntu 20.04:

```
dvc doctor
DVC version: 2.9.5 (snap)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-91-generic-x86_64-with-glibc2.29
Supports:
	azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.7.1),
	gdrive (pydrive2 = 1.10.0),
	gs (gcsfs = 2022.2.0),
	webhdfs (fsspec = 2022.2.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.2.0, boto3 = 1.20.24),
	ssh (sshfs = 2021.11.2)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: https
Workspace directory: ext4 on /dev/vda3
Repo: dvc, git
```

**Comment by dtrifiro** [comment]
Hi @fnareoh, were you able to solve the issue? I see that you use snap on Manjaro. In case this helps, an (unofficial) AUR package is available here: https://aur.archlinux.org/packages/dvc

**Comment by fnareoh** [comment]
Hi ! very  for not answering earlier and thank you very much for responding.

Yes it is fixed with a fresh install of the AUR repository! Very sorry for bothering you!
