### ISSUE TITLE
exp show: throws an error with `-n -1`

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#7434]
`dvc exp show -v -n -1` throws an error for me:

```
2022-01-25 12:25:40,695 DEBUG: Adding '/private/tmp/example-get-started/.dvc/config.local' to gitignore file.
2022-01-25 12:25:40,697 DEBUG: Adding '/private/tmp/example-get-started/.dvc/tmp' to gitignore file.
2022-01-25 12:25:40,697 DEBUG: Adding '/private/tmp/example-get-started/.dvc/cache' to gitignore file.
2022-01-25 12:25:40,711 ERROR: unexpected error - refs/remotes/origin/HEAD~12: the given reference name 'refs/remotes/origin/HEAD~12' is not valid
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dave/Code/dvc/dvc/cli/__init__.py", line 78, in main
    ret = cmd.do_run()
  File "/Users/dave/Code/dvc/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/Users/dave/Code/dvc/dvc/commands/experiments/show.py", line 445, in run
    all_experiments = self.repo.experiments.show(
  File "/Users/dave/Code/dvc/dvc/repo/experiments/__init__.py", line 820, in show
    return show(self.repo, *args, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/experiments/show.py", line 126, in show
    iter_revs(repo.scm, revs, num, all_branches, all_tags, all_commits)
  File "/Users/dave/Code/dvc/dvc/scm.py", line 165, in iter_revs
    revs.append(resolve_rev(scm, head))
  File "/Users/dave/Code/dvc/dvc/scm.py", line 115, in resolve_rev
    return scm.resolve_rev(rev)
  File "/Users/dave/miniforge3/envs/example-get-started/lib/python3.8/site-packages/scmrepo/git/__init__.py", line 253, in _backend_func
    return func(*args, **kwargs)
  File "/Users/dave/miniforge3/envs/example-get-started/lib/python3.8/site-packages/scmrepo/git/backend/pygit2.py", line 263, in resolve_rev
    shas = {
  File "/Users/dave/miniforge3/envs/example-get-started/lib/python3.8/site-packages/scmrepo/git/backend/pygit2.py", line 264, in <setcomp>
    self.get_ref(f"refs/remotes/{remote.name}/{rev}")
  File "/Users/dave/miniforge3/envs/example-get-started/lib/python3.8/site-packages/scmrepo/git/backend/pygit2.py", line 322, in get_ref
    ref = self.repo.references.get(name)
  File "/Users/dave/miniforge3/envs/example-get-started/lib/python3.8/site-packages/pygit2/repository.py", line 1440, in get
    return self[key]
  File "/Users/dave/miniforge3/envs/example-get-started/lib/python3.8/site-packages/pygit2/repository.py", line 1436, in __getitem__
    return self._repository.lookup_reference(name)
_pygit2.InvalidSpecError: refs/remotes/origin/HEAD~12: the given reference name 'refs/remotes/origin/HEAD~12' is not valid
------------------------------------------------------------
2022-01-25 12:25:41,566 DEBUG: Adding '/private/tmp/example-get-started/.dvc/config.local' to gitignore file.
2022-01-25 12:25:41,567 DEBUG: Adding '/private/tmp/example-get-started/.dvc/tmp' to gitignore file.
2022-01-25 12:25:41,567 DEBUG: Adding '/private/tmp/example-get-started/.dvc/cache' to gitignore file.
2022-01-25 12:25:41,568 DEBUG: Version info for developers:
DVC version: 2.9.4.dev58+g47481219
---------------------------------
Platform: Python 3.8.5 on macOS-10.16-x86_64-i386-64bit
Supports:
        gdrive (pydrive2 = 1.7.3),
        hdfs (fsspec = 2022.1.0, pyarrow = 3.0.0),
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.7.3, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.3, aiohttp-retry = 2.4.6),
        ssh (sshfs = 2021.11.2)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-01-25 12:25:41,569 DEBUG: Analytics is disabled.
```

_Originally posted by @dberenbaum in https://github.com/iterative/dvc/issues/7204#issuecomment-1021431886_

**Comment by pmrowla** [comment]
Fixed in https://github.com/iterative/scmrepo/pull/32

see: https://github.com/iterative/dvc/pull/7435#issuecomment-1060640894
