### ISSUE TITLE
dvc cache: files missing in shared cache

### ISSUE THREAD

**Issue by weidenka** [iterative/dvc#7447]
# Bug Report

## Description
I try to run `dvc repro` and get an error which is caused by some missing file in the cache. The stage were calculated on a different machine before and I expect it to be cached. The cache directory is stored on an NFS share. I had this error before and created a new cache, now with the exact same issue.

File permissions in the cache are `drwxrwxr-x` for directories and `-r--r--r--` for files and the owner is some admin user. Therefore I do not think that those files were deleted accidentally.

```console
Stage 'mystage@9' is cached - skipping run, checking out outputs
2022-03-09 11:19:45,649 TRACE: Assuming '/dvc_remote_cache/myproject2/31/5d6dd00b52417843717efded769650' is unchanged since it is read-only
2022-03-09 11:19:45,649 TRACE: Assuming '/dvc_remote_cache/myproject2/e1/8b93ba83899172b1d328eb7541ec50.dir' is unchanged since it is read-only
2022-03-09 11:19:45,649 TRACE: Assuming '/dvc_remote_cache/myproject2/04/f755b19576d0a255fd92a901f7d797' is unchanged since it is read-only
2022-03-09 11:19:45,649 TRACE: Assuming '/dvc_remote_cache/myproject2/05/177aed143f1d5e6183ea4c16aee772' is unchanged since it is read-only
2022-03-09 11:19:45,649 TRACE: Assuming '/dvc_remote_cache/myproject2/ea/9c80cb8c80010aee610430f856fe03' is unchanged since it is read-only
2022-03-09 11:19:45,649 TRACE: Assuming '/dvc_remote_cache/myproject2/96/3966cef6e3ec74654b76feecaf9673' is unchanged since it is read-only
2022-03-09 11:19:45,650 TRACE: Assuming '/dvc_remote_cache/myproject2/8f/cbdb6343c311a40b0acce07fd5b90d' is unchanged since it is read-only
2022-03-09 11:19:45,650 TRACE: Assuming '/dvc_remote_cache/myproject2/1d/fc58fcf516a471d7f38d9c27e9d9f9' is unchanged since it is read-only
2022-03-09 11:19:45,650 TRACE: Assuming '/dvc_remote_cache/myproject2/29/fe132c68ac9fdcb34d0f793a88e446' is unchanged since it is read-only
2022-03-09 11:19:45,650 TRACE: Assuming '/dvc_remote_cache/myproject2/ed/c7f9ecbdde439652d309af793c0bfc' is unchanged since it is read-only
2022-03-09 11:19:45,652 DEBUG: [Errno 95] no more link types left to try out: [Errno 95] 'symlink' is not supported by <class 'dvc.fs.local.LocalFileSystem'>: [Errno 2] No such file or directory: '/dvc_remote_cache/myproject2/.CN9arhxnYqZ9KqWSgj4uxF.tmp' -> '/code/myproject/dvc/data/processed/embedding/fitness/XRHealthActions/elbow_to_knee/.5U3Q7wiYYaUKvrBtRMn7af.tmp'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/someuser/env/lib/python3.7/site-packages/dvc/fs/utils.py", line 28, in _link
    func(from_path, to_path)
  File "/home/someuser/env/lib/python3.7/site-packages/dvc/fs/local.py", line 115, in symlink
    System.symlink(from_info, to_info)
  File "/home/someuser/env/lib/python3.7/site-packages/dvc/system.py", line 43, in symlink
    os.symlink(source, link_name)
FileNotFoundError: [Errno 2] No such file or directory: '/dvc_remote_cache/myproject2/.CN9arhxnYqZ9KqWSgj4uxF.tmp' -> '/code/myproject/dvc/data/processed/embedding/fitness/XRHealthActions/elbow_to_knee/.5U3Q7wiYYaUKvrBtRMn7af.tmp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/someuser/env/lib/python3.7/site-packages/dvc/fs/utils.py", line 69, in _try_links
    return _link(link, from_fs, from_path, to_fs, to_path)
  File "/home/someuser/env/lib/python3.7/site-packages/dvc/fs/utils.py", line 34, in _link
    ) from exc
OSError: [Errno 95] 'symlink' is not supported by <class 'dvc.fs.local.LocalFileSystem'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/someuser/env/lib/python3.7/site-packages/dvc/fs/utils.py", line 124, in _test_link
    _try_links([link], from_fs, from_file, to_fs, to_file)
  File "/home/someuser/env/lib/python3.7/site-packages/dvc/fs/utils.py", line 79, in _try_links
    ) from error
OSError: [Errno 95] no more link types left to try out
```

### Reproduce

Can not reproduce the bug in a simple toy example.

### Expected

Cached features should be retrieved.

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.7.5 on Linux-5.8.18-100.fc31.x86_64-x86_64-with-Ubuntu-18.04-bionic
Supports:
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: symlink
Cache directory: nfs on 192.168.1.99:/test_dvc/dvc_remote_cache
Caches: local
Remotes: local
Workspace directory: ext4 on /dev/mapper/fedora_localhost--live-home
Repo: dvc (subdir), git
```

**Additional Information (if any):**

**Comment by karajan1001** [comment]
Hi, @weidenka Could you please provide some more info `dvc status --cloud` on the original computer side.
