### ISSUE TITLE
add: --external unexpected error: FileNotFoundError in MemoryFS

### ISSUE THREAD

**Issue by Lubricy** [iterative/dvc#7461]
# Bug Report

add: --external unexpected error: FileNotFoundError in MemoryFS

## Description

`dvc add --external` with s3 cache and s3 external throws error.

```console
$ dvc add -v --external s3://<my-bucket>/<my-prefix>/data/processed/                                                                 ±(main)[1]
2022-03-14 23:01:49,452 DEBUG: staged tree 'object md5: 0dbe4183ce147106170d373b5da5da34.dir'
2022-03-14 23:01:53,843 DEBUG: Computed stage: 'processed.dvc' md5: 'None'
2022-03-14 23:01:59,086 DEBUG: staged tree 'object md5: 0dbe4183ce147106170d373b5da5da34.dir'
2022-03-14 23:01:59,746 DEBUG: Preparing to transfer data from 'memory://dvc-staging/b1ceaf2f5df5eccc3f5a3fbd012b42f829c5d42682b7323577afb03d864e9cfd' to '<my-bucket>/<my-prefix>/dvc/cache/'
2022-03-14 23:01:59,747 DEBUG: Preparing to collect status from '<my-bucket>/<my-prefix>/dvc/cache/'
Adding...
2022-03-14 23:01:59,749 ERROR: unexpected error - /dvc-staging/b1ceaf2f5df5eccc3f5a3fbd012b42f829c5d42682b7323577afb03d864e9cfd/7d/0236d632ddc2d50c75946ac597fad6.dir
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/cli/__init__.py", line 78, in main
    ret = cmd.do_run()
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/commands/add.py", line 22, in run
    self.repo.add(
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/utils/collections.py", line 163, in inner
    result = func(*ba.args, **ba.kwargs)
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/repo/scm_context.py", line 152, in run
    return method(repo, *args, **kw)
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/repo/add.py", line 192, in add
    stage.commit()
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/stage/__init__.py", line 509, in commit
    out.commit(filter_info=filter_info)
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/output.py", line 589, in commit
    otransfer(
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/data/transfer.py", line 154, in transfer
    status = compare_status(
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/data/status.py", line 163, in compare_status
    dest_exists, dest_missing = status(
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/data/status.py", line 106, in status
    tree = Tree.load(cache_odb, hash_info)
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/data/tree.py", line 145, in load
    with obj.fs.open(obj.fs_path, "r") as fobj:
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/fs/memory.py", line 31, in open
    with super().open(*args, **kwargs) as fobj:
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/fs/fsspec_wrapper.py", line 71, in open
    return self.fs.open(path, mode=mode)
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/fsspec/spec.py", line 997, in open
    self.open(
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/fsspec/spec.py", line 1009, in open
    f = self._open(
  File "/Users/me/.local/pipx/venvs/dvc/lib/python3.9/site-packages/fsspec/implementations/memory.py", line 182, in _open
    raise FileNotFoundError(path)
FileNotFoundError: /dvc-staging/b1ceaf2f5df5eccc3f5a3fbd012b42f829c5d42682b7323577afb03d864e9cfd/7d/0236d632ddc2d50c75946ac597fad6.dir
------------------------------------------------------------
2022-03-14 23:01:59,833 DEBUG: Version info for developers:
DVC version: 2.9.5 (pip)
---------------------------------
Platform: Python 3.9.6 on macOS-11.6.2-x86_64-i386-64bit
Supports:
        webhdfs (fsspec = 2022.2.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.2.0, boto3 = 1.20.24)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local, s3
Remotes: s3, s3
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-03-14 23:01:59,836 DEBUG: Analytics is disabled.
```

### Reproduce

```console
1. dvc init
2. dvc remote add s3-cache s3://<my-bucket>/<my-perfix>/dvc/cache
3. dvc config cache.s3 s3-cache
4. aws s3 cp test.txt s3://<my-bucket>/<my-perfix>/data/processed/
5. dvc add -v --external s3://<my-bucket>/<my-perfix>/data/processed/
```
### Expected

command run successfully with external file added.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.9.5 (pip)
---------------------------------
Platform: Python 3.9.6 on macOS-11.6.2-x86_64-i386-64bit
Supports:
        webhdfs (fsspec = 2022.2.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.2.0, boto3 = 1.20.24)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local, s3
Remotes: s3, s3
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git
```

**Additional Information (if any):**

a little debugging around suggests the command tries to find a file named with the eTag of the s3 object inside local memory fs, which unfortunately does not exist.

**Comment by D34D10CK** [comment]
I have the same issue on DVC 2.28.0 but using gs instead of s3.

**Comment by pmrowla** [comment]
@D34D10CK can you post your `-v` traceback as well

**Comment by D34D10CK** [comment]
Here's the stacktrace:
```
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc/commands/add.py", line 53, in run
    self.repo.add(
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc/utils/collections.py", line 164, in inner
    result = func(*ba.args, **ba.kwargs)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc/repo/scm_context.py", line 156, in run
    return method(repo, *args, **kw)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc/repo/add.py", line 192, in add
    stage.commit()
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc/stage/__init__.py", line 531, in commit
    out.commit(filter_info=filter_info)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc/output.py", line 682, in commit
    otransfer(
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc_data/hashfile/transfer.py", line 158, in transfer
    status = compare_status(
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc_data/hashfile/status.py", line 179, in compare_status
    dest_exists, dest_missing = status(
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc_data/hashfile/status.py", line 118, in status
    tree = Tree.load(cache_odb, hash_info)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc_data/hashfile/tree.py", line 166, in load
    with obj.fs.open(obj.path, "r") as fobj:
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 197, in open
    return self.fs.open(path, mode=mode, **kwargs)
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/fsspec/spec.py", line 1022, in open
    self.open(
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/fsspec/spec.py", line 1034, in open
    f = self._open(
  File "/home/user/.local/share/virtualenvs/project/lib/python3.10/site-packages/fsspec/implementations/memory.py", line 190, in _open
    raise FileNotFoundError(path)
FileNotFoundError: /dvc-staging/46f69644008dc51f11cb711fd76605a60bf0097824692c9f09a327f3e0bc8f05/08/e49ea7c397c6fa021001.dir
```

and here's the output of dvc doctor:

```
DVC version: 2.28.0 (pip)
---------------------------------
Platform: Python 3.10.6 on Linux-4.19.0-21-cloud-amd64-x86_64-with-glibc2.28
Subprojects:
        dvc_data = 0.13.0
        dvc_objects = 0.5.0
        dvc_render = 0.0.11
        dvc_task = 0.1.2
        dvclive = 0.11.0
        scmrepo = 0.1.1
Supports:
        azure (adlfs = 2022.9.1, knack = 0.10.0, azure-identity = 1.11.0),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = 2022.8.2),
        hdfs (fsspec = 2022.8.2, pyarrow = 9.0.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2022.8.2, boto3 = 1.24.59),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7),
        webhdfs (fsspec = 2022.8.2)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda1
Caches: local, gs
Remotes: gs, gs
Workspace directory: ext4 on /dev/sda1
Repo: dvc, git
```

**Comment by BobTheScientist** [comment]
I am experiencing this same issue:

```dvc add -v --external -R gs://tl-sci-launchpad-local-data/image_dataset_1/flowers/daisy
2023-03-29 16:56:51,413 DEBUG: v2.51.0 (pip), CPython 3.9.16 on Linux-4.19.0-22-cloud-amd64-x86_64-with-glibc2.28
2023-03-29 16:56:51,414 DEBUG: command: /opt/conda/envs/ttf/bin/dvc add -v --external -R gs://tl-sci-launchpad-local-data/image_dataset_1/flowers/daisy
2023-03-29 16:56:52,561 DEBUG: built tree 'object 4384369fefb991855fe8de49be3b8187.dir'                                                                                                                                                                                
2023-03-29 16:56:52,647 DEBUG: Computed stage: 'daisy.dvc' md5: 'None'                                                                                                                                                                                                 
2023-03-29 16:56:52,976 DEBUG: built tree 'object 4384369fefb991855fe8de49be3b8187.dir'
2023-03-29 16:56:53,047 DEBUG: Preparing to transfer data from 'memory://dvc-staging/b2c1a59640fa828372842be65ea1fa4094e064e8bd5d7638dc77ccbb84ae3009' to 'tl-sci-launchpad-local-data/dvc'                                                                            
2023-03-29 16:56:53,047 DEBUG: Preparing to collect status from 'tl-sci-launchpad-local-data/dvc'
Adding...
2023-03-29 16:56:53,049 ERROR: unexpected error - /dvc-staging/b2c1a59640fa828372842be65ea1fa4094e064e8bd5d7638dc77ccbb84ae3009/08/93c1e3d4cd81fe021001.dir
Traceback (most recent call last):
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc/commands/add.py", line 50, in run
    self.repo.add(
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc/utils/collections.py", line 160, in inner
    result = func(*ba.args, **ba.kwargs)
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc/repo/__init__.py", line 67, in wrapper
    return f(repo, *args, **kwargs)
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc/repo/scm_context.py", line 151, in run
    return method(repo, *args, **kw)
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc/repo/add.py", line 192, in add
    stage.commit()
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc/stage/__init__.py", line 554, in commit
    out.commit(filter_info=filter_info, **kwargs)
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc/output.py", line 736, in commit
    otransfer(
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc_data/hashfile/transfer.py", line 203, in transfer
    status = compare_status(
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc_data/hashfile/status.py", line 178, in compare_status
    dest_exists, dest_missing = status(
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc_data/hashfile/status.py", line 116, in status
    tree = Tree.load(cache_odb, hash_info)
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc_data/hashfile/tree.py", line 169, in load
    with obj.fs.open(obj.path, "r") as fobj:
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/dvc_objects/fs/base.py", line 194, in open
    return self.fs.open(path, mode=mode, **kwargs)
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/fsspec/spec.py", line 1139, in open
    self.open(
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/fsspec/spec.py", line 1151, in open
    f = self._open(
  File "/opt/conda/envs/ttf/lib/python3.9/site-packages/fsspec/implementations/memory.py", line 192, in _open
    raise FileNotFoundError(path)
FileNotFoundError: /dvc-staging/b2c1a59640fa828372842be65ea1fa4094e064e8bd5d7638dc77ccbb84ae3009/08/93c1e3d4cd81fe021001.dir

2023-03-29 16:56:53,113 DEBUG: Version info for developers:
DVC version: 2.51.0 (pip)
-------------------------
Platform: Python 3.9.16 on Linux-4.19.0-22-cloud-amd64-x86_64-with-glibc2.28
Subprojects:
        dvc_data = 0.44.1
        dvc_objects = 0.21.1
        dvc_render = 0.3.1
        dvc_task = 0.2.0
        scmrepo = 0.1.17
Supports:
        gs (gcsfs = 2023.3.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local, gs
Remotes: gs, gs
Workspace directory: ext4 on /dev/sda1
Repo: dvc (subdir), git
Repo.site_cache_dir: /var/tmp/dvc/repo/503d774f570f689ee993490951bbd2b2```

**Comment by Moriiitez** [comment]
I have the same error when trying to add --external hdfs directory.

**Comment by guigautier** [comment]
Same issue: with minio s3 cache

**Comment by efiop** [comment]
Hey folks, please note that we will be dropping support for external outputs in 3.0 soon https://github.com/iterative/dvc/issues/9531

**Comment by dberenbaum** [comment]
No longer relevant
