### ISSUE TITLE
GBK charactor encoding error

### ISSUE THREAD

**Issue by SiriusBHU** [iterative/dvc#7466]
# Bug Report

## GBK charactor encoding error, when 'dvc pull'
UnicodeEncodeError: 'latin-1' codec can't encode character '\u6b23' in position 248: ordinal not in range(256)

## Description

when i use 'dvc pull' on linux, the pushed files with chinese charactors can not be encoded
Example:  欣_EDA_20210812165116 -> \u6b23_EDA_20210812165116, the '\u6b23' encoding error
By the way, those files are successfully pushed on windows, but failed to pull on linux

## Logs
```
Traceback (most recent call last):
  File "dvc/logger.py", line 162, in emit
  File "tqdm/std.py", line 619, in write
UnicodeEncodeError: 'latin-1' codec can't encode character '\u6b23' in position 248: ordinal not in range(256)
Call stack:
  File "dvc/__main__.py", line 7, in <module>
  File "dvc/main.py", line 55, in main
  File "dvc/command/base.py", line 45, in do_run
  File "dvc/command/data_sync.py", line 30, in run
  File "dvc/repo/__init__.py", line 49, in wrapper
  File "dvc/repo/pull.py", line 40, in pull
  File "dvc/repo/__init__.py", line 49, in wrapper
  File "dvc/repo/checkout.py", line 98, in checkout
  File "funcy/decorators.py", line 45, in wrapper
  File "dvc/stage/decorators.py", line 36, in rwlocked
  File "funcy/decorators.py", line 66, in __call__
  File "dvc/stage/__init__.py", line 572, in checkout
  File "dvc/stage/__init__.py", line 584, in _checkout
  File "dvc/output.py", line 756, in checkout
  File "dvc/objects/checkout.py", line 241, in checkout
  File "dvc/objects/checkout.py", line 187, in _checkout
  File "dvc/objects/checkout.py", line 90, in _checkout_file
  File "dvc/objects/db/slow_link_detection.py", line 33, in wrapper
  File "dvc/objects/checkout.py", line 142, in __call__
  File "dvc/fs/utils.py", line 96, in transfer
  File "dvc/fs/utils.py", line 66, in _try_links
  File "dvc/fs/utils.py", line 44, in _copy
  File "dvc/fs/base.py", line 263, in upload
  File "logging/__init__.py", line 1422, in debug
  File "logging/__init__.py", line 1577, in _log
  File "logging/__init__.py", line 1587, in handle
  File "logging/__init__.py", line 1649, in callHandlers
  File "logging/__init__.py", line 950, in handle
  File "dvc/logger.py", line 169, in emit
Message: "Uploading '%s' to '%s'"
Arguments: ('/srv/dataset/ppg/raw/.dvc/cache/f6/e4562e813c42eda87ad06d95d02e31', '/srv/dataset/ppg/raw/jupiter/2021.08.12.X.A.normal/0812_J-132.0806.01_left_EDA/20210812165116/\u6b23_EDA_20210812165116.txt')
2022-03-15 12:29:15,667 ERROR: unexpected error - failed to log <LogRecord: dvc.fs.base, 10, dvc/fs/base.py, 263, "Uploading '%s' to '%s'">
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/logger.py", line 162, in emit
  File "tqdm/std.py", line 619, in write
UnicodeEncodeError: 'latin-1' codec can't encode character '\u6b23' in position 248: ordinal not in range(256)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc/main.py", line 55, in main
  File "dvc/command/base.py", line 45, in do_run
  File "dvc/command/data_sync.py", line 30, in run
  File "dvc/repo/__init__.py", line 49, in wrapper
  File "dvc/repo/pull.py", line 40, in pull
  File "dvc/repo/__init__.py", line 49, in wrapper
  File "dvc/repo/checkout.py", line 98, in checkout
  File "funcy/decorators.py", line 45, in wrapper
  File "dvc/stage/decorators.py", line 36, in rwlocked
  File "funcy/decorators.py", line 66, in __call__
  File "dvc/stage/__init__.py", line 572, in checkout
  File "dvc/stage/__init__.py", line 584, in _checkout
  File "dvc/output.py", line 756, in checkout
  File "dvc/objects/checkout.py", line 241, in checkout
  File "dvc/objects/checkout.py", line 187, in _checkout
  File "dvc/objects/checkout.py", line 90, in _checkout_file
  File "dvc/objects/db/slow_link_detection.py", line 33, in wrapper
  File "dvc/objects/checkout.py", line 142, in __call__
  File "dvc/fs/utils.py", line 96, in transfer
  File "dvc/fs/utils.py", line 66, in _try_links
  File "dvc/fs/utils.py", line 44, in _copy
  File "dvc/fs/base.py", line 263, in upload
  File "logging/__init__.py", line 1422, in debug
  File "logging/__init__.py", line 1577, in _log
  File "logging/__init__.py", line 1587, in handle
  File "logging/__init__.py", line 1649, in callHandlers
  File "logging/__init__.py", line 950, in handle
  File "dvc/logger.py", line 169, in emit
  File "dvc/logger.py", line 143, in handleError
dvc.logger.LoggingException: failed to log <LogRecord: dvc.fs.base, 10, dvc/fs/base.py, 263, "Uploading '%s' to '%s'">
------------------------------------------------------------
2022-03-15 12:29:16,487 DEBUG: Adding '/srv/dataset/ppg/raw/.dvc/config.local' to gitignore file.
2022-03-15 12:29:16,489 DEBUG: Adding '/srv/dataset/ppg/raw/.dvc/tmp' to gitignore file.
2022-03-15 12:29:16,489 DEBUG: Adding '/srv/dataset/ppg/raw/.dvc/cache' to gitignore file.
2022-03-15 12:29:16,490 DEBUG: [Errno 95] no more link types left to try out: [Errno 95] 'reflink' is not supported by <class 'dvc.fs.local.LocalFileSystem'>: [Errno 95] Operation not supported
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/logger.py", line 162, in emit
  File "tqdm/std.py", line 619, in write
UnicodeEncodeError: 'latin-1' codec can't encode character '\u6b23' in position 248: ordinal not in range(256)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc/main.py", line 55, in main
  File "dvc/command/base.py", line 45, in do_run
  File "dvc/command/data_sync.py", line 30, in run
  File "dvc/repo/__init__.py", line 49, in wrapper
  File "dvc/repo/pull.py", line 40, in pull
  File "dvc/repo/__init__.py", line 49, in wrapper
  File "dvc/repo/checkout.py", line 98, in checkout
  File "funcy/decorators.py", line 45, in wrapper
  File "dvc/stage/decorators.py", line 36, in rwlocked
  File "funcy/decorators.py", line 66, in __call__
  File "dvc/stage/__init__.py", line 572, in checkout
  File "dvc/stage/__init__.py", line 584, in _checkout
  File "dvc/output.py", line 756, in checkout
  File "dvc/objects/checkout.py", line 241, in checkout
  File "dvc/objects/checkout.py", line 187, in _checkout
  File "dvc/objects/checkout.py", line 90, in _checkout_file
  File "dvc/objects/db/slow_link_detection.py", line 33, in wrapper
  File "dvc/objects/checkout.py", line 142, in __call__
  File "dvc/fs/utils.py", line 96, in transfer
  File "dvc/fs/utils.py", line 66, in _try_links
  File "dvc/fs/utils.py", line 44, in _copy
  File "dvc/fs/base.py", line 263, in upload
  File "logging/__init__.py", line 1422, in debug
  File "logging/__init__.py", line 1577, in _log
  File "logging/__init__.py", line 1587, in handle
  File "logging/__init__.py", line 1649, in callHandlers
  File "logging/__init__.py", line 950, in handle
  File "dvc/logger.py", line 169, in emit
  File "dvc/logger.py", line 143, in handleError
dvc.logger.LoggingException: failed to log <LogRecord: dvc.fs.base, 10, dvc/fs/base.py, 263, "Uploading '%s' to '%s'">
```

**Comment by pmrowla** [comment]
Your system locale is most likely set to `latin-1`, which is an encoding that cannot display CJK characters. You need to set your locale (`LANG` env var) to use an encoding that supports those characters (like one of the `utf-8` based locales)

see also: https://github.com/iterative/dvc/issues/5591#issuecomment-816866732

**Comment by SiriusBHU** [comment]
i try the advice mentioned in [#5591](https://github.com/iterative/dvc/issues/5591#issuecomment-816866732), and I don't get this error.
thanks a lot
