### ISSUE TITLE
dvc push: Kills MinIO

### ISSUE THREAD

**Issue by jmaaks** [iterative/dvc#7480]
# Bug Report

## dvc push: Kills MinIO

Attempting dvc push from within a Jupyter notebook in a Kubernetes custer to MinIO S3 causes the MinIO server process to be killed.

## Description

dvc push behaves similar to below, but causes MinIO server process to use increasing memory until it eventually exceeds the container/pod limit and is killed.  Adding the "-j 8" option at least prevents the server instance from being killed.

```
dvc push -j 8 -v
2022-03-21 16:45:46,536 DEBUG: Preparing to transfer data from '/dvc_test/.dvc/cache' to 'data-cleansed/jeff-test'
2022-03-21 16:45:46,536 DEBUG: Preparing to collect status from 'data-cleansed/jeff-test'
2022-03-21 16:45:46,536 DEBUG: Collecting status from 'data-cleansed/jeff-test'

After hanging at this point for several minutes, the command fails with the following:

2022-03-21 16:47:09,197 ERROR: unexpected error - Connect timeout on endpoint URL: "https://[Retracted URL]/data-cleansed?list-type=2&prefix=jeff-test%2F00%2F0&delimiter=&encoding-type=url"
------------------------------------------------------------
Traceback (most recent call last):
  File "aiobotocore/httpsession.py", line 172, in send
  File "aiohttp/client.py", line 559, in _request
  File "aiohttp/client_reqrep.py", line 898, in start
  File "aiohttp/streams.py", line 616, in read
aiohttp.client_exceptions.ServerTimeoutError: Timeout on reading data from socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc/cli/__init__.py", line 78, in main
  File "dvc/cli/command.py", line 22, in do_run
  File "dvc/commands/data_sync.py", line 58, in run
  File "dvc/repo/__init__.py", line 48, in wrapper
  File "dvc/repo/push.py", line 68, in push
  File "dvc/data_cloud.py", line 85, in push
  File "dvc/data/transfer.py", line 154, in transfer
  File "dvc/data/status.py", line 163, in compare_status
  File "dvc/data/status.py", line 135, in status
  File "dvc/objects/db.py", line 434, in hashes_exist
  File "dvc/objects/db.py", line 271, in _estimate_remote_size
  File "dvc/objects/db.py", line 225, in _hashes_with_limit
  File "dvc/objects/db.py", line 215, in _list_hashes
  File "dvc/objects/db.py", line 195, in _list_paths
  File "dvc/fs/fsspec_wrapper.py", line 189, in find
  File "fsspec/asyn.py", line 91, in wrapper
  File "fsspec/asyn.py", line 71, in sync
  File "fsspec/asyn.py", line 25, in _runner
  File "s3fs/core.py", line 665, in _find
  File "s3fs/core.py", line 593, in _lsdir
  File "aiobotocore/paginate.py", line 32, in __anext__
  File "aiobotocore/client.py", line 211, in _make_api_call
  File "aiobotocore/client.py", line 231, in _make_request
  File "aiobotocore/endpoint.py", line 81, in _send_request
  File "aiobotocore/endpoint.py", line 213, in _needs_retry
  File "aiobotocore/hooks.py", line 29, in _emit
  File "botocore/retryhandler.py", line 183, in __call__
  File "botocore/retryhandler.py", line 250, in __call__
  File "botocore/retryhandler.py", line 277, in _should_retry
  File "botocore/retryhandler.py", line 316, in __call__
  File "botocore/retryhandler.py", line 222, in __call__
  File "botocore/retryhandler.py", line 359, in _check_caught_exception
  File "aiobotocore/endpoint.py", line 147, in _do_get_response
  File "aiobotocore/endpoint.py", line 229, in _send
  File "aiobotocore/httpsession.py", line 203, in send
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "https://{Retracted URL]/data-cleansed?list-type=2&prefix=jeff-test%2F00%2F0&delimiter=&encoding-type=url"
------------------------------------------------------------
2022-03-21 16:47:09,780 DEBUG: [Errno 95] no more link types left to try out: [Errno 95] 'reflink' is not supported by <class 'dvc.fs.local.LocalFileSystem'>: [Errno 95] Operation not supported
------------------------------------------------------------
Traceback (most recent call last):
  File "aiobotocore/httpsession.py", line 172, in send
  File "aiohttp/client.py", line 559, in _request
  File "aiohttp/client_reqrep.py", line 898, in start
  File "aiohttp/streams.py", line 616, in read
aiohttp.client_exceptions.ServerTimeoutError: Timeout on reading data from socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc/cli/__init__.py", line 78, in main
  File "dvc/cli/command.py", line 22, in do_run
  File "dvc/commands/data_sync.py", line 58, in run
  File "dvc/repo/__init__.py", line 48, in wrapper
  File "dvc/repo/push.py", line 68, in push
  File "dvc/data_cloud.py", line 85, in push
  File "dvc/data/transfer.py", line 154, in transfer
  File "dvc/data/status.py", line 163, in compare_status
  File "dvc/data/status.py", line 135, in status
  File "dvc/objects/db.py", line 434, in hashes_exist
  File "dvc/objects/db.py", line 271, in _estimate_remote_size
  File "dvc/objects/db.py", line 225, in _hashes_with_limit
  File "dvc/objects/db.py", line 215, in _list_hashes
  File "dvc/objects/db.py", line 195, in _list_paths
  File "dvc/fs/fsspec_wrapper.py", line 189, in find
  File "fsspec/asyn.py", line 91, in wrapper
  File "fsspec/asyn.py", line 71, in sync
  File "fsspec/asyn.py", line 25, in _runner
  File "s3fs/core.py", line 665, in _find
  File "s3fs/core.py", line 593, in _lsdir
  File "aiobotocore/paginate.py", line 32, in __anext__
  File "aiobotocore/client.py", line 211, in _make_api_call
  File "aiobotocore/client.py", line 231, in _make_request
  File "aiobotocore/endpoint.py", line 81, in _send_request
  File "aiobotocore/endpoint.py", line 213, in _needs_retry
  File "aiobotocore/hooks.py", line 29, in _emit
  File "botocore/retryhandler.py", line 183, in __call__
  File "botocore/retryhandler.py", line 250, in __call__
  File "botocore/retryhandler.py", line 277, in _should_retry
  File "botocore/retryhandler.py", line 316, in __call__
  File "botocore/retryhandler.py", line 222, in __call__
  File "botocore/retryhandler.py", line 359, in _check_caught_exception
  File "aiobotocore/endpoint.py", line 147, in _do_get_response
  File "aiobotocore/endpoint.py", line 229, in _send
  File "aiobotocore/httpsession.py", line 203, in send
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "https://[retracted URL]/data-cleansed?list-type=2&prefix=jeff-test%2F00%2F0&delimiter=&encoding-type=url"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc/fs/utils.py", line 28, in _link
  File "dvc/fs/local.py", line 145, in reflink
  File "dvc/system.py", line 112, in reflink
  File "dvc/system.py", line 96, in _reflink_linux
OSError: [Errno 95] Operation not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dvc/fs/utils.py", line 69, in _try_links
  File "dvc/fs/utils.py", line 32, in _link
OSError: [Errno 95] 'reflink' is not supported by <class 'dvc.fs.local.LocalFileSystem'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dvc/fs/utils.py", line 124, in _test_link
  File "dvc/fs/utils.py", line 77, in _try_links
OSError: [Errno 95] no more link types left to try out
------------------------------------------------------------
2022-03-21 16:47:09,782 DEBUG: Removing '[retracted dir]/.gTuv6jzewLHDiXFZHDSGuS.tmp'
2022-03-21 16:47:09,783 DEBUG: Removing '[retracted dir]/.gTuv6jzewLHDiXFZHDSGuS.tmp'
2022-03-21 16:47:09,784 DEBUG: Removing '[retracted dir]/.gTuv6jzewLHDiXFZHDSGuS.tmp'
2022-03-21 16:47:09,784 DEBUG: Removing '[retracted dir]/dvc_test/.dvc/cache/.XY53coEfh6WUUtstAUVZvR.tmp'
2022-03-21 16:47:09,796 DEBUG: Version info for developers:
DVC version: 2.9.5 (rpm)
---------------------------------
Platform: Python 3.8.3 on Linux-5.3.18-24.67-default-x86_64-with-glibc2.14
Supports:
        azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.7.1),
        gdrive (pydrive2 = 1.10.0),
        gs (gcsfs = 2022.1.0),
        hdfs (fsspec = 2022.1.0, pyarrow = 7.0.0),
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.1.0, boto3 = 1.20.24),
        ssh (sshfs = 2021.11.2),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.4),
        webdavs (webdav4 = 0.9.4)
Cache types: hardlink, symlink
Cache directory: overlay on overlay
Caches: local
Remotes: s3
Workspace directory: overlay on overlay
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-03-21 16:47:09,798 DEBUG: Analytics is enabled.
2022-03-21 16:47:09,871 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpdyx0ukyt']'
2022-03-21 16:47:09,875 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpdyx0ukyt']'
[dvc_test]$ [34674] Failed to execute script '__main__' due to unhandled exception!
```

However, doing "dvc remote modify minio jobs 32" DOES allow "dvc push" to work.  Thus, it seems that some internal process doesn't entirely honor the command-line process throttling.

What I've found is that the host we're running on has 64 cores, so as I understand it DVC multiplies that by 4 and kicks off 256 processes, which must overwhelm MinIO.

### Reproduce

1. dvc init
2. dvc remote add –d minio s3://bucket_name/folder_name
3. dvc remote modify minio endpointurl <URL_OF_MINIO>
4. Copy *.dat files to data/
5. dvc add data/*.dat
6. dvc push

### Expected

Expect files to be pushed into MinIO bucket/dir.

### Environment information

DVC running on a host with many (~64) cores, and targeting a MinIO server instance running in k8s with 2GB memory limit.

**Output of `dvc doctor`:**

```
DVC version: 2.9.5 (rpm)
---------------------------------
Platform: Python 3.8.3 on Linux-5.3.18-24.67-default-x86_64-with-glibc2.14
Supports:
        azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.7.1),
        gdrive (pydrive2 = 1.10.0),
        gs (gcsfs = 2022.1.0),
        hdfs (fsspec = 2022.1.0, pyarrow = 7.0.0),
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.1.0, boto3 = 1.20.24),
        ssh (sshfs = 2021.11.2),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.4),
        webdavs (webdav4 = 0.9.4)
Cache types: hardlink, symlink
Cache directory: overlay on overlay
Caches: local
Remotes: s3
Workspace directory: overlay on overlay
Repo: dvc, git
```
**Additional Information (if any):**

**Comment by jmaaks** [comment]
Just to be clear, "dvc remote modify minio jobs 32" provides a fix to this issue for our implementation.  I just wanted to report this behavior about DVC killing MinIO without that option, or at least the "-j n" command-line option being set.

**Comment by skshetry** [comment]
Hi, the correct approach is to limit jobs by using config. Closing, thanks.

**Comment by jmaaks** [comment]
Hi @skshetry  -- Thanks, but a question about my comment clarification: Yes, the correct approach is to limit jobs by using config, but why doesn't limiting jobs on the command-line also work (and only just changes the behavior slightly)?  That strikes me as a subtle bug.
