### ISSUE TITLE
Unable to update data to dvc

### ISSUE THREAD

**Issue by Guixudong** [iterative/dvc#7505]
My dvc version is 2.8.3 ,when I pushed my data to remote,I got an error:No module named 'win32timezone'

Trace back:

```
Traceback (most recent call last):
  File "dvc\output.py", line 855, in get_dir_cache
  File "dvc\objects\__init__.py", line 20, in check
  File "dvc\objects\db\base.py", line 175, in check
  File "dvc\objects\file.py", line 68, in check
  File "dvc\objects\file.py", line 73, in _check_hash
  File "dvc\objects\stage.py", line 72, in get_file_hash
  File "dvc\objects\stage.py", line 47, in _get_file_hash
  File "dvc\fs\local.py", line 164, in info
  File "fsspec\implementations\local.py", line 80, in info
FileNotFoundError: [WinError 3] ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒·▒▒▒▒: 'E:/dvcrepo/.dvc/cache/7a/950a4ae9f11dc87b046d83b2b128f8.dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc\main.py", line 55, in main
  File "dvc\command\base.py", line 45, in do_run
  File "dvc\command\data_sync.py", line 57, in run
  File "dvc\repo\__init__.py", line 50, in wrapper
  File "dvc\repo\push.py", line 37, in push
  File "dvc\repo\__init__.py", line 420, in used_objs
  File "dvc\repo\index.py", line 186, in used_objs
  File "dvc\stage\__init__.py", line 660, in get_used_objs
  File "dvc\output.py", line 933, in get_used_objs
  File "dvc\output.py", line 877, in _collect_used_dir_cache
  File "dvc\output.py", line 859, in get_dir_cache
  File "dvc\data_cloud.py", line 114, in pull
  File "dvc\objects\transfer.py", line 153, in transfer
  File "dvc\objects\status.py", line 166, in compare_status
  File "dvc\objects\status.py", line 122, in status
  File "dvc\objects\status.py", line 48, in _indexed_dir_hashes
  File "dvc\objects\db\base.py", line 419, in list_hashes_exists
  File "concurrent\futures\_base.py", line 619, in result_iterator
  File "concurrent\futures\_base.py", line 444, in result
  File "concurrent\futures\_base.py", line 389, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "dvc\objects\db\base.py", line 410, in exists_with_progress
  File "dvc\fs\fsspec_wrapper.py", line 136, in exists
  File "funcy\objects.py", line 50, in __get__
  File "funcy\objects.py", line 28, in __get__
  File "dvc\fs\ssh.py", line 117, in fs
  File "fsspec\spec.py", line 76, in __call__
  File "sshfs\spec.py", line 77, in __init__
  File "fsspec\asyn.py", line 91, in wrapper
  File "fsspec\asyn.py", line 71, in sync
  File "fsspec\asyn.py", line 25, in _runner
  File "asyncio\tasks.py", line 494, in wait_for
  File "sshfs\utils.py", line 27, in wrapper
  File "sshfs\spec.py", line 92, in _connect
  File "contextlib.py", line 568, in enter_async_context
  File "asyncssh\misc.py", line 220, in __aenter__
  File "asyncssh\connection.py", line 6855, in connect
  File "asyncssh\connection.py", line 297, in _connect
  File "asyncio\base_events.py", line 1050, in create_connection
  File "asyncio\base_events.py", line 1068, in _create_connection_transport
  File "asyncssh\connection.py", line 6846, in conn_factory
  File "asyncssh\connection.py", line 2750, in __init__
  File "asyncssh\gss_win32.py", line 148, in __init__
  File "sspi.py", line 200, in __init__
ModuleNotFoundError: No module named 'win32timezone'
```

I am waiting for your reply!

**Comment by skshetry** [comment]
@Guixudong, can you please share output from `dvc doctor`?

**Comment by efiop** [comment]
closing as stale
