### ISSUE TITLE
`dvc get` with ssh fails on 2.10

### ISSUE THREAD

**Issue by achimgaedke** [iterative/dvc#7537]
Straight into things: using ubuntu 20.04 with mamba for environment management, having dvc installed.

```bash
dvc get --verbose git@github.com:iterative/dvc.git setup.py
```

succeeds with `dvc<2.10`, namely 2.9.5:

```bash
$ dvc get --verbose git@github.com:iterative/dvc.git setup.py
2022-04-04 21:49:55,140 DEBUG: Creating external repo git@github.com:iterative/dvc.git@None
2022-04-04 21:49:55,141 DEBUG: erepo: git clone 'git@github.com:iterative/dvc.git' to a temporary dir
2022-04-04 21:49:56,356 DEBUG: Downloading '/tmp/tmpoyxezvmrdvc-clone/setup.py' to '/home/achim.gaedke/setup.py'                                                                        
2022-04-04 21:49:56,357 DEBUG: Removing '/home/achim.gaedke/.2EvdPfR6EX9aUyirFD8gQA'                                                                                                    
2022-04-04 21:49:56,358 DEBUG: Analytics is enabled.
2022-04-04 21:49:56,384 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmp2e7pkkmz']'
2022-04-04 21:49:56,385 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmp2e7pkkmz']'
```

 but fails with `dvc=2.10` (of course have removed the `setup.py` first).

```bash
$ dvc get --verbose git@github.com:iterative/dvc.git setup.py
2022-04-04 21:51:18,064 DEBUG: Creating external repo git@github.com:iterative/dvc.git@None
2022-04-04 21:51:18,064 DEBUG: erepo: git clone 'git@github.com:iterative/dvc.git' to a temporary dir
2022-04-04 21:51:20,669 DEBUG: Removing '/home/achim.gaedke/.5cyoeUaxji4S6QyDvfiBwF'                                                                                                    
2022-04-04 21:51:20,670 ERROR: failed to get 'setup.py' from 'git@github.com:iterative/dvc.git' - Failed to clone repo 'git@github.com:iterative/dvc.git' to '/tmp/tmpgr9b2v2ndvc-clone'
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 193, in clone
    repo = clone_from()
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dulwich/porcelain.py", line 443, in clone
    return client.clone(
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dulwich/client.py", line 535, in clone
    result = self.fetch(path, target, progress=progress, depth=depth)
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dulwich/client.py", line 601, in fetch
    result = self.fetch_pack(
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dulwich/client.py", line 1125, in fetch_pack
    self._handle_upload_pack_tail(
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dulwich/client.py", line 911, in _handle_upload_pack_tail
    self._read_side_band64k_data(
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dulwich/client.py", line 665, in _read_side_band64k_data
    for pkt in proto.read_pkt_seq():
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dulwich/protocol.py", line 290, in read_pkt_seq
    pkt = self.read_pkt_line()
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dulwich/protocol.py", line 245, in read_pkt_line
    raise GitProtocolError(
dulwich.errors.GitProtocolError: Length of pkt read 0005 does not match length prefix 0026

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dvc/scm.py", line 106, in clone
    return Git.clone(url, to_path, progress=pbar.update_git, **kwargs)
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 143, in clone
    backend.clone(url, to_path, **kwargs)
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 196, in clone
    raise CloneError(url, to_path) from exc
scmrepo.exceptions.CloneError: Failed to clone repo 'git@github.com:iterative/dvc.git' to '/tmp/tmpgr9b2v2ndvc-clone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dvc/commands/get.py", line 39, in _get_file_from_repo
    Repo.get(
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dvc/repo/get.py", line 49, in get
    with external_repo(
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dvc/external_repo.py", line 36, in external_repo
    path = _cached_clone(url, rev, for_write=for_write)
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dvc/external_repo.py", line 162, in _cached_clone
    clone_path, shallow = _clone_default_branch(url, rev, for_write=for_write)
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/funcy/flow.py", line 274, in wrap_with
    return call()
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dvc/external_repo.py", line 232, in _clone_default_branch
    git = clone(url, clone_path)
  File "/opt/conda-envs/envs/dvc-test/lib/python3.10/site-packages/dvc/scm.py", line 108, in clone
    raise CloneError(str(exc))
dvc.scm.CloneError: Failed to clone repo 'git@github.com:iterative/dvc.git' to '/tmp/tmpgr9b2v2ndvc-clone'
------------------------------------------------------------
2022-04-04 21:51:20,679 DEBUG: Analytics is enabled.
2022-04-04 21:51:20,713 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmplzn7qgpu']'
2022-04-04 21:51:20,714 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmplzn7qgpu']'
```

Here some more environment information:

```bash
$ dvc doctor
DVC version: 2.10.0 (conda)
---------------------------------
Platform: Python 3.10.4 on Linux-5.4.0-1069-aws-x86_64-with-glibc2.31
Supports:
        webhdfs (fsspec = 2022.3.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
```

**Comment by achimgaedke** [comment]
Surprisingly, the dulwich version did not change, ugrading from 2.9.5 to 2.10 with `mamba install "dvc=2.10"`

```bash
  Package    Version  Build            Channel                    Size
────────────────────────────────────────────────────────────────────────
  Upgrade:
────────────────────────────────────────────────────────────────────────

  - dvc        2.9.5  py310hff52083_1  installed                      
  + dvc       2.10.0  py310hff52083_0  conda-forge/linux-64     Cached
  - scmrepo    0.0.7  pyhd8ed1ab_0     installed                      
  + scmrepo   0.0.16  pyhd8ed1ab_1     conda-forge/noarch       Cached

```

**Comment by skshetry** [comment]
@achimgaedke, does it always happen or only intermittently? Also, would it be possible to check installing `dvc` via `pip`?

**Comment by skshetry** [comment]
Related: https://github.com/iterative/dvc/issues/7361, looks like the issue is with dulwich client.

**Comment by achimgaedke** [comment]
> @achimgaedke, does it always happen or only intermittently? 

The message  `Length of pkt read 0005 does not match length prefix 0026`  changes from time to time, but there's no intermittent success.

> Also, would it be possible to check installing `dvc` via `pip`?

Yes, it fails consistently, here are the installation commands I used.
The error message is as above, `dulwich.errors.GitProtocolError: Length of pkt read 0005 does not match length prefix 0029` ... just the length prefix is different.

```bash
mamba create -n dvc-test "python=3.10" pip wheel
conda activate dvc-test
pip install dvc
```

**Comment by daavoo** [comment]
I am able to consistently reproduce this. I think it would be addressed as part of #7361

**Comment by Guillaume-oso** [comment]
I have the same problem with versions of scmrepo>0.0.10
scmrepo>0.0.10


DVC version: 2.10.1 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.8.0-38-generic-x86_64-with-glibc2.29
Supports:
        webhdfs (fsspec = 2022.3.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.2.0, boto3 = 1.21.29)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git

**Comment by pmrowla** [comment]
Installing `scmrepo==0.0.18` should resolve this issue (you will get a pip warning about scmrepo not matching the version required by DVC, this will be updated in the next DVC release)
