### ISSUE TITLE
DVC push to google storage bucket failed

### ISSUE THREAD

**Issue by bmabir17-asj** [iterative/dvc#7538]
# Bug Report

## Description
while trying to push data after adding them to dvc with following command
```console
$ dvc push -v
```
I get the following errror message
```
------------------------------------------------------------
2022-04-04 09:59:40,770 DEBUG: Uploading '/home/bmabir/repo/anomaly_detection_engine/.dvc/cache/93/40cff707f78db6700e586c259194b6' to 'gs://dvc_dataset_remote/remote_data/93/40cff707f78db6700e586c259194b6'
2022-04-04 09:59:40,947 ERROR: failed to transfer 'md5: 9340cff707f78db6700e586c259194b6' - Forbidden: https://storage.googleapis.com/upload/storage/v1/b/dvc_dataset_remote/o    
Access denied.
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/data/transfer.py", line 25, in wrapper
  File "dvc/data/transfer.py", line 162, in func
  File "dvc/objects/db.py", line 117, in add
  File "dvc/objects/db.py", line 89, in _add_file
  File "dvc/fs/utils.py", line 96, in transfer
  File "dvc/fs/utils.py", line 66, in _try_links
  File "dvc/fs/utils.py", line 44, in _copy
  File "dvc/fs/base.py", line 251, in upload
  File "dvc/fs/fsspec_wrapper.py", line 240, in put_file
  File "dvc/fs/fsspec_wrapper.py", line 133, in upload_fobj
  File "fsspec/spec.py", line 1663, in __exit__
  File "fsspec/spec.py", line 1630, in close
  File "fsspec/spec.py", line 1496, in flush
  File "gcsfs/core.py", line 1391, in _initiate_upload
  File "fsspec/asyn.py", line 65, in sync
  File "fsspec/asyn.py", line 25, in _runner
  File "gcsfs/core.py", line 1507, in initiate_upload
  File "gcsfs/core.py", line 386, in _call
  File "decorator.py", line 221, in fun
  File "gcsfs/retry.py", line 115, in retry_request
  File "gcsfs/core.py", line 378, in _request
  File "gcsfs/retry.py", line 96, in validate_response
OSError: Forbidden: https://storage.googleapis.com/upload/storage/v1/b/dvc_dataset_remote/o
Access denied.
```
I have setup Google auth using the following commands
`gcloud auth login`
`gcloud auth application-default login`

I have even tried use the service account credential and set `GOOGLE_APPLICATION_CREDENTIALS` environment variable with the json key file.
But the error seems to be the same.

### Reproduce

1. dvc init
2. Copy dataset files to the directory of dataset
3. dvc add dataset/*
6. dvc push

### Expected
The dataset file would get uploaded to gs bucket

### Environment information
**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.10.0 (deb)
---------------------------------
Platform: Python 3.8.3 on Linux-4.19.0-20-cloud-amd64-x86_64-with-glibc2.14
Supports:
        azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.8.0),
        gdrive (pydrive2 = 1.10.0),
        gs (gcsfs = 2022.2.0),
        hdfs (fsspec = 2022.2.0, pyarrow = 7.0.0),
        webhdfs (fsspec = 2022.2.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.2.0, boto3 = 1.20.24),
        ssh (sshfs = 2022.3.1),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.5),
        webdavs (webdav4 = 0.9.5)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda1
Caches: local
Remotes: gs
Workspace directory: ext4 on /dev/sda1
Repo: dvc, git
```

**Comment by pmrowla** [comment]
Are you able to use `gsutil cp` to manually copy a test file into that bucket with the credentials you are trying to use in DVC?

**Comment by efiop** [comment]
closing as stale

**Comment by kooroshsajadi** [comment]
I personally have this issue. When I run `gsutil cp`, I can upload the data from my computer to my bucket. However, when I run `dvc push`, I get the error _ERROR: unexpected error - Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist)., 401_.

**Comment by kooroshsajadi** [comment]
Problem is solved for me! I had to authenticate with the command `gcloud auth application-default login` after doing authentication using the command `gcloud auth login`.
