### ISSUE TITLE
repro / push: failed to reproduce: Permission denied / NFS file system issue?

### ISSUE THREAD

**Issue by PythonFZ** [iterative/dvc#7553]
# Bug Report
## Description

I trained a model and now using `dvc repro` leads to the following:

```console
Stage '273_15K' didn't change, skipping                               
ERROR: failed to reproduce '283_15K': [Errno 13] Permission denied: '/work/fzills/projects/BMIM_BF4/.dvc/cache/dc/ba2b481c31e874fd9d4c50d34be971'
```

I get the same error with `dvc push -r origin` or `dvc exp run --name "basic_model"`.
I have multiple "start" stages and the issue can occur for all of them.
All files have `-r--r--r--` permission and can accesses e.g. via 
`tail /work/fzills/projects/BMIM_BF4/.dvc/cache/dc/ba2b481c31e874fd9d4c50d34be971`

If I use `tail <affected_file>` and call `dvc repro` it will load that stage.
So I can manually look into the files to solve this but it would be helpful if `dvc repro` could do that?

### Reproduce
I struggle to easily reproduce this and give an example.
Probably related to NFS file system.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 2.10.1 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-107-generic-x86_64-with-glibc2.29
Supports:
        webhdfs (fsspec = 2021.11.0),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        ssh (sshfs = 2021.11.2)
Cache types: hardlink, symlink
Cache directory: nfs on 129.69.120.13:/share/.../fzills
Caches: local
Remotes: https
Workspace directory: nfs on 129.69.120.13:/share/.../fzills
Repo: dvc, git
```

**Comment by daavoo** [comment]
Hi @PythonFZ , could you share the verbose output `dvc repro -v`?

**Comment by PythonFZ** [comment]
This is from a different stage in the workflow but the same issue which could be resolved by running `touch <filename>`

```
2022-04-08 14:49:15,843 ERROR: failed to reproduce 'NequipModel': [Errno 13] Permission denied: '/work/fzills/projects/BMIM_BF4/.dvc/cache/d0/9510cdf5499aca83ae0a5bc78e18c8'
------------------------------------------------------------
Traceback (most recent call last):
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/repo/reproduce.py", line 203, in _reproduce_stages
    ret = _reproduce_stage(stage, **kwargs)
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/repo/reproduce.py", line 40, in _reproduce_stage
    stage = stage.reproduce(**kwargs)
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/stage/__init__.py", line 411, in reproduce
    if not (kwargs.get("force", False) or self.changed()):
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/stage/__init__.py", line 360, in changed
    or self.changed_outs()
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/stage/__init__.py", line 335, in changed_outs
    status = out.status()
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/output.py", line 472, in status
    if self.hash_info and self.use_cache and self.changed_cache():
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/output.py", line 454, in changed_cache
    ocheck(self.odb, obj)
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/data/__init__.py", line 17, in check
    odb.check(oid, **kwargs)
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/objects/db.py", line 164, in check
    if self.is_protected(obj.fs_path):
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/data/db/local.py", line 153, in is_protected
    mode = os.stat(fs_path).st_mode
PermissionError: [Errno 13] Permission denied: '/work/fzills/projects/BMIM_BF4/.dvc/cache/d0/9510cdf5499aca83ae0a5bc78e18c8'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/cli/__init__.py", line 89, in main
    ret = cmd.do_run()
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/commands/repro.py", line 13, in run
    stages = self.repo.reproduce(
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/repo/scm_context.py", line 152, in run
    return method(repo, *args, **kw)
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/repo/reproduce.py", line 142, in reproduce
    return _reproduce_stages(self.index.graph, list(stages), **kwargs)
  File "/tikhome/fzills/miniconda3/envs/work/lib/python3.9/site-packages/dvc/repo/reproduce.py", line 220, in _reproduce_stages
    raise ReproductionError(stage.addressing) from exc
dvc.exceptions.ReproductionError: failed to reproduce 'NequipModel'
------------------------------------------------------------
2022-04-08 14:49:15,961 DEBUG: Analytics is enabled.
2022-04-08 14:49:16,029 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpkyk4feaq']'
2022-04-08 14:49:16,030 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpkyk4feaq']
```

**Comment by PythonFZ** [comment]
I could solve the issue in https://github.com/iterative/dvc/pull/7562.

I tried the following:

```py
try:
    print(os.stat(filename))
except PermissionError:
    with open(filename): # works
        pass
# subprocess.check_call(["touch", filename]) # works, but uses subprocess module 
# pathlib.Path(filename).touch() # does not work    
    print(os.stat(filename))
```

**Comment by pmrowla** [comment]
@PythonFZ what NFS options are you using for this mount (from `/etc/fstab`)? It's probably a caching issue

**Comment by PythonFZ** [comment]
> @PythonFZ what NFS options are you using for this mount (from `/etc/fstab`)? It's probably an NFS caching issue, you may need to try mounting it with either `noac` or with a small `actimeo=...` timeout value

The mount options are:
```
174.32.120.37:/share/work_abc/fzills on /work/fzills type nfs (rw,relatime,vers=3,rsize=262144,wsize=262144,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=174.32.120.37,mountvers=3,mountport=39848,mountproto=tcp,local_lock=none,addr=174.32.120.37)
```
I'm not responsible for the NFS mount so changing them is not an option.

**Comment by pmrowla** [comment]
> I'm not responsible for the NFS mount so changing them is not an option.

Right, but the issue here is that this may not actually be a DVC bug.

If it's an issue with your NFS configuration, calling `open` may force NFS to invalidate the attribute cache in your particular NFS client/server setup, but it doesn't make sense to have a random unused `open` call in DVC.

**Comment by PythonFZ** [comment]
> > I'm not responsible for the NFS mount so changing them is not an option.
> 
> Right, but the issue here is that this may not actually be a DVC bug.
> 
> If it's an issue with your NFS configuration, calling `open` may force NFS to invalidate the attribute cache in your particular NFS client/server setup, but it doesn't make sense to have a random unused `open` call in DVC.

I absolutely agree. Are you familiar with NFS? There is no issue going into the directory and looking at the stat of the file.
So `os.stat` seems to do something different here.

**Comment by pmrowla** [comment]
By default, NFS caches file attributes which can make `stat` calls return (incorrect) cached values. The mount options I suggested trying would disable the caching altogether (`noac`) or at least reduce the time that NFS will consider the cached value to be valid (`actimeo`).

Testing those options and seeing if it makes the issue go away would help identify what the underlying cause of your problem is.

---

> I'm not responsible for the NFS mount so changing them is not an option.

Do you have the necessary permissions to add another NFS mount? i.e. just doing:

```
mkdir test-mount
mount -t nfs -o noac 174.32.120.37:/share/work_abc/fzills  test-mount
```

and trying DVC with that alternate mount point for testing purposes

**Comment by PythonFZ** [comment]
I'm still trying to test that. The same issue occurs for `dvc init` on a similar NFS mount (`129.69.120.26:/beegfs/work on /auto.bee/work type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=129.69.120.26,mountvers=3,mountport=20048,mountproto=tcp,local_lock=none,addr=129.69.120.26)`)

Unfortunately, `dvc init -v` doesn't show any output. It just stops working. I can't even stop the process and have to close the terminal.
