### ISSUE TITLE
Errors on `dvc get --show-url` after update from 2.7.4 to 2.10.1

### ISSUE THREAD

**Issue by choux130** [iterative/dvc#7640]
# Bug Report

## Description

Hello, I tried printing the storage location by running `dvc get --show-url`  and got errors on version 2.10.1 but it works well on version 2.7.4. Any thoughts about what might cause it or how to avoid the error on 2.10.1? 

### Reproduce

The following code works on version 2.7.4 but not in 2.10.1
```
dvc get --rev 70465609297817c8a71a0037e614deaa5d60a9e8 --show-url git@ssh.dev.azure.com:v3/xxx/xxx/TemplateProject code/data -v
```

### Expected

I expect the result will be the same on both version. However, this is what I got for version 2.7.4
```
2022-04-26 16:18:37,888 DEBUG: Creating external repo git@ssh.dev.azure.com:v3/xxx/xxx/TemplateProject@70465609297817c8a71a0037e614deaa5d60a9e8
2022-04-26 16:18:37,889 DEBUG: erepo: git clone 'git@ssh.dev.azure.com:v3/xxx/xxx/TemplateProject' to a temporary dir
s3://xxx/xxx/dvc/local_test2/b0/f2e29290908f72cd2926983b0000e9.dir                                                                                                                                         
2022-04-26 16:18:40,691 DEBUG: Analytics is enabled.
2022-04-26 16:18:41,031 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\TING~1.CHO\\AppData\\Local\\Temp\\tmpmfpvcm10']'
2022-04-26 16:18:41,036 DEBUG: Spawned '['daemon', '-q', 'analytics', 'C:\\Users\\TING~1.CHO\\AppData\\Local\\Temp\\tmpmfpvcm10']'
```
and errors for 2.10.1
```
2022-04-26 16:18:47,108 DEBUG: Creating external repo git@ssh.dev.azure.com:v3/xxx/xxx/TemplateProject@70465609297817c8a71a0037e614deaa5d60a9e8
2022-04-26 16:18:47,109 DEBUG: erepo: git clone 'git@ssh.dev.azure.com:v3/xxx/xxx/TemplateProject' to a temporary dir
2022-04-26 16:18:49,113 ERROR: failed to show URL - Failed to clone repo 'git@ssh.dev.azure.com:v3/xxx/xxx/TemplateProject' to 'C:\Users\TING~1.CHO\AppData\Local\Temp\tmp43hc_j7bdvc-clone'
------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\scmrepo\git\backend\dulwich\__init__.py", line 193, in clone
    repo = clone_from()
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dulwich\porcelain.py", line 443, in clone
    return client.clone(
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dulwich\client.py", line 535, in clone
    result = self.fetch(path, target, progress=progress, depth=depth)
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dulwich\client.py", line 601, in fetch
    result = self.fetch_pack(
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dulwich\client.py", line 1125, in fetch_pack
    self._handle_upload_pack_tail(
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dulwich\client.py", line 911, in _handle_upload_pack_tail
    self._read_side_band64k_data(
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dulwich\client.py", line 665, in _read_side_band64k_data
    for pkt in proto.read_pkt_seq():
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dulwich\protocol.py", line 290, in read_pkt_seq
    pkt = self.read_pkt_line()
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dulwich\protocol.py", line 245, in read_pkt_line
    raise GitProtocolError(
dulwich.errors.GitProtocolError: Length of pkt read 8000 does not match length prefix afd7

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dvc\scm.py", line 106, in clone
    return Git.clone(url, to_path, progress=pbar.update_git, **kwargs)
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\scmrepo\git\__init__.py", line 143, in clone
    backend.clone(url, to_path, **kwargs)
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\scmrepo\git\backend\dulwich\__init__.py", line 196, in clone
    raise CloneError(url, to_path) from exc
scmrepo.exceptions.CloneError: Failed to clone repo 'git@ssh.dev.azure.com:v3/xxx/xxx/TemplateProject' to 'C:\Users\TING~1.CHO\AppData\Local\Temp\tmp43hc_j7bdvc-clone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dvc\commands\get.py", line 19, in _show_url
    url = get_url(
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dvc\api.py", line 21, in get_url
    with Repo.open(repo, rev=rev, subrepos=True, uninitialized=True) as _repo:
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dvc\external_repo.py", line 36, in external_repo
    path = _cached_clone(url, rev, for_write=for_write)
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dvc\external_repo.py", line 162, in _cached_clone
    clone_path, shallow = _clone_default_branch(url, rev, for_write=for_write)
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\funcy\decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\funcy\flow.py", line 274, in wrap_with
    return call()
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\funcy\decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dvc\external_repo.py", line 232, in _clone_default_branch
    git = clone(url, clone_path)
  File "C:\Users\ting.chou\Anaconda3\envs\dvc\lib\site-packages\dvc\scm.py", line 108, in clone
    raise CloneError(str(exc))
dvc.scm.CloneError: Failed to clone repo 'git@ssh.dev.azure.com:v3/xxx/xxx/TemplateProject' to 'C:\Users\TING~1.CHO\AppData\Local\Temp\tmp43hc_j7bdvc-clone'
------------------------------------------------------------
2022-04-26 16:18:49,160 DEBUG: Analytics is enabled.
2022-04-26 16:18:49,277 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\TING~1.CHO\\AppData\\Local\\Temp\\tmpo8i3b3ao']'
2022-04-26 16:18:49,281 DEBUG: Spawned '['daemon', '-q', 'analytics', 'C:\\Users\\TING~1.CHO\\AppData\\Local\\Temp\\tmpo8i3b3ao']'
```

### Environment information

```console
$ dvc doctor
```
```
DVC version: 2.7.4 (pip)
---------------------------------
Platform: Python 3.8.13 on Windows-10-10.0.19041-SP0   
Supports:
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.5), 
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.5),
        s3 (s3fs = 2022.3.0, boto3 = 1.21.21)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3, s3, s3, s3
Workspace directory: NTFS on C:\
Repo: dvc, git
```
```
DVC version: 2.10.1 (pip)
---------------------------------
Platform: Python 3.8.13 on Windows-10-10.0.19041-SP0
Supports:
        webhdfs (fsspec = 2022.3.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.3.0, boto3 = 1.21.21)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3, s3, s3, s3
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Comment by daavoo** [comment]
Could you try with`pip install scmrepo==0.0.18` ? 

Fix should be shipped in next release

**Comment by choux130** [comment]
Yup! Version 2.10.1 works after doing `pip install scmrepo==0.0.18`. Thank you very much for the prompt response. 👍
