### ISSUE TITLE
exp-init: broken in a fresh repo

### ISSUE THREAD

**Issue by drorata** [iterative/dvc#7660]
# Bug Report

## Description

The command `dvc exp init` is broken and returns:

```
ERROR: command is not specified
```

### Reproduce

1. Start a fresh git repo
2. Run `dvc init`
3. Run `dvc expo init`

### Expected

I expected the behavior as described in the [docs](https://dvc.org/doc/command-reference/exp/init).

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.10.1 (pip)
---------------------------------
Platform: Python 3.9.12 on macOS-10.16-x86_64-i386-64bit
Supports:
	webhdfs (fsspec = 2022.3.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
```

**Additional Information (if any):**

The output of `dvc exp init --verbose` is:

```
➜ dvc exp init --verbose
2022-04-29 09:41:50,256 ERROR: command is not specified
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/drorata/anaconda3/envs/dvc-exp-tutorial/lib/python3.9/site-packages/dvc/cli/__init__.py", line 89, in main
    ret = cmd.do_run()
  File "/Users/drorata/anaconda3/envs/dvc-exp-tutorial/lib/python3.9/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/Users/drorata/anaconda3/envs/dvc-exp-tutorial/lib/python3.9/site-packages/dvc/commands/experiments/init.py", line 44, in run
    raise InvalidArgumentError("command is not specified")
dvc.exceptions.InvalidArgumentError: command is not specified
------------------------------------------------------------
2022-04-29 09:41:50,259 DEBUG: Analytics is enabled.
2022-04-29 09:41:50,313 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/hc/m_f707sd7t3ghfvxn5013sfm0000gp/T/tmprdafwvva']'
2022-04-29 09:41:50,315 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/hc/m_f707sd7t3ghfvxn5013sfm0000gp/T/tmprdafwvva']'
```

**Comment by skshetry** [comment]
@drorata, `exp init` requires an explicit command (it will prompt you if you use `--interactive`).

This is what the docs say:

> You must always provide a command that runs your experiment(s). It can be given either directly [as an argument](https://dvc.org/doc/command-reference/exp/init#the-command-argument), or by using the --interactive (-i) mode which will prompt you for it. This command will be wrapped as a stage that [dvc exp run](https://dvc.org/doc/command-reference/exp/run) can execute.

**Comment by drorata** [comment]
Thanks @skshetry. I don't have deep enough understanding around this, but I would argue that a more verbose error message would be helpful for the users.

**Comment by dtrifiro** [comment]
Hi @drorata, thanks for the report.
 `dvc exp init --help` mentions that `command` is a positional argument and, as skshetry mentioned, it's also mentioned in the docs. Closing for now
