### ISSUE TITLE
`exp pull`: _get_file() got an unexpected keyword argument

### ISSUE THREAD

**Issue by mattlbeck** [iterative/dvc#7669]
# Bug Report

## Description

Ominous error when trying to run `dvc exp pull` to pull all experiments for certain revision

```
ERROR: failed to transfer 'md5: 6ddbf4e482c3d9acaa9a6f77a9c54176.dir' - 
  _get_file() got an unexpected keyword argument 'callback' 
```

I recieve a number of these errors for various md5 strings. A separate concern is that I think DVC is looking at more than the revsion I specify, but that still happens with older versions without the error I have encountered here.

### Reproduce

Using `dvc==2.10.2`

```
dvc exp pull origin --rev HEAD
```

The error is not present on `2.10.1`

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.8.12 on Linux-5.10.76-linuxkit-x86_64-with-glibc2.27
Supports:
        webhdfs (fsspec = 2021.11.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2021.11.0, boto3 = 1.17.106)
Cache types: symlink
Cache directory: fuse.grpcfuse on grpcfuse
Caches: local
Remotes: s3
Workspace directory: fuse.grpcfuse on grpcfuse
Repo: dvc, git
```

**Comment by efiop** [comment]
@mattlbeck Could you please post full verbose log for `dvc exp pull origin --rev HEAD -v`?

**Comment by mattlbeck** [comment]
@efiop here's a complete traceback:
```
2022-05-01 13:44:49,787 ERROR: failed to transfer 'md5: a23843ba1499a3f7e17f58d32d9fc687.dir' - _get_file() got an unexpected keyword argument 'callback'   
------------------------------------------------------------                                                                                                
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/dvc/data/transfer.py", line 25, in wrapper
    func(fs_path, *args, **kwargs)
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/dvc/data/transfer.py", line 162, in func
    return dest.add(
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/dvc/objects/db.py", line 126, in add
    self._add_file(
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/dvc/objects/db.py", line 98, in _add_file
    return fs.utils.transfer(
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/dvc/fs/utils.py", line 96, in transfer
    _try_links(links, from_fs, from_path, to_fs, to_path)
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/dvc/fs/utils.py", line 66, in _try_links
    return _copy(from_fs, from_path, to_fs, to_path)
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/dvc/fs/utils.py", line 47, in _copy
    return from_fs.download_file(from_path, to_path)
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/dvc/fs/base.py", line 448, in download_file
    self.get_file(from_info, tmp_file, callback=cb)
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/dvc/fs/base.py", line 341, in get_file
    self.fs.get_file(from_info, to_info, callback=callback, **kwargs)
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/fsspec/asyn.py", line 53, in sync
    coro = func(*args, **kwargs)
TypeError: _get_file() got an unexpected keyword argument 'callback'
------------------------------------------------------------
```

**Comment by efiop** [comment]
@mattlbeck It seems like you have an older s3fs version than the one we support. Could you please `pip install -U s3fs` and check `pip freeze | grep s3fs`?
