### ISSUE TITLE
dvc exp run: failing with [merge] ff.only in git config

### ISSUE THREAD

**Issue by dtrifiro** [iterative/dvc#7675]
# Bug Report
## Description
`dvc exp run` fails when git is configured to only use fast forward merges (`git config --global merge.ff only`)

### Reproduce
```bash
#!/bin/bash
set -euo pipefail

working_dir=$(mktemp -d --suffix _ff_only)
echo "working_dir=${working_dir}"

pushd ${working_dir}
python -m venv .venv
source .venv/bin/activate
pip install dvc
git init
dvc init
git commit -am "init"

echo "stages:
  prepare:
    cmd: echo something > out
    outs:
    - out" >>dvc.yaml

dvc exp run -n succeedingrun

git config --local merge.ff only

dvc exp run -n failingrun # fails with "Cannot fast-forward HEAD to rev"
```

### Expected
Succesful exp run

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.8.12 on Linux-5.15.32-1-MANJARO-x86_64-with-glibc2.33
Supports:
	webhdfs (fsspec = 2022.3.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: tmpfs on tmpfs
Caches: local
Remotes: None
Workspace directory: tmpfs on tmpfs
Repo: dvc, git

```

**Additional Information (if any):**
Full traceback:
```console
2022-05-02 13:01:19,008 DEBUG: Stashed experiment 'c372161' with baseline '33774db' for future execution.
2022-05-02 13:01:19,010 DEBUG: Reproducing experiment revs 'c372161'
2022-05-02 13:01:19,017 ERROR: Cannot fast-forward HEAD to '{rev}'
------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/scm.py", line 55, in map_scm_exception
    yield
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/repo/experiments/__init__.py", line 53, in wrapper
    return f(exp, *args, **kwargs)
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/repo/experiments/__init__.py", line 635, in _reproduce_revs
    manager = manager_cls.from_stash_entries(
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/repo/experiments/executor/manager/local.py", line 47, in from_stash_entries
    executor = cls.EXECUTOR_CLS.from_stash_entry(
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/repo/experiments/executor/local.py", line 145, in from_stash_entry
    executor = cls._from_stash_entry(repo, stash_rev, entry, root_dir)
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/repo/experiments/executor/base.py", line 238, in _from_stash_entry
    executor.init_git(repo.scm, branch=entry.branch)
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/repo/experiments/executor/local.py", line 158, in init_git
    self.scm.merge(merge_rev, squash=True, commit=False)
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/scmrepo/git/__init__.py", line 289, in _backend_func
    result = func(*args, **kwargs)
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/scmrepo/git/backend/pygit2.py", line 649, in merge
    raise SCMError("Cannot fast-forward HEAD to '{rev}'")
scmrepo.exceptions.SCMError: Cannot fast-forward HEAD to '{rev}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/cli/__init__.py", line 90, in main
    ret = cmd.do_run()
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/commands/experiments/run.py", line 32, in run
    results = self.repo.experiments.run(
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/repo/experiments/__init__.py", line 825, in run
    return run(self.repo, *args, **kwargs)
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/repo/experiments/run.py", line 32, in run
    return repo.experiments.reproduce_one(
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/repo/experiments/__init__.py", line 438, in reproduce_one
    results = self._reproduce_revs(
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/repo/experiments/__init__.py", line 53, in wrapper
    return f(exp, *args, **kwargs)
  File "/home/dtrifiro/.pyenv/versions/3.8.12/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/tmp.sXCrGLLELW_ff_only/.venv/lib/python3.8/site-packages/dvc/scm.py", line 60, in map_scm_exception
    raise into
dvc.scm.SCMError: Cannot fast-forward HEAD to '{rev}'
```

**Comment by pmrowla** [comment]
`exp run` requires generating merge commits, which is supposed to fail when a git repo is configured to only allow fast-forwards (and to reject generation of merge commits).

I'm not sure what the expected behavior here would be. We can force generation of a merge commit in experiments (and ignore the git configuration), but if a user is explicitly setting `--ff-only` for a git repo, it seems like they may be expecting this to fail?

@dtrifiro does this report come from a user or is it something that you found on your own?

**Comment by dtrifiro** [comment]
This is something I found out myself: the problem is that have set `--ff-only` in my global config (`git config --global merge.ff only`).

I guess that if merge commits are required, we could just try adding a friendlier error message mentioning that.

What I'm not sure about though, is why I've run into this issue just now. I had used `exp run` before with no issues and `--ff-only` has been in my git config for a long time, that's why I'm confused about this.

**Comment by pmrowla** [comment]
I think it's probably because the scmrepo merge implementation wasn't actually handling the ff-only config setting until relatively recently. It was fixed when we moved to using dulwich/pygit clone.

**Comment by pmrowla** [comment]
Thinking about this some more, we should probably just override `ff-only` for DVC-generated experiment commits, given that we aren't merging anything into user-managed branches (only in DVC exp refs)

**Comment by dberenbaum** [comment]
Setting this as p3 since I haven't noticed user reports on it. If it actually becomes an issue we see in the wild, I think we need to prioritize it quickly.
