### ISSUE TITLE
add: Error message on none-dvc repository 

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#7679]
# Bug Report

DVC shows `ERROR: "${repo_path}" is not a git repository` on a Git but no DVC repo.

## Description

```bash
$ git init
$ dvc add data
ERROR: /Users/gao/test is not a git repository
```

### Reproduce

```bash
mkdir add
cd add
echo data > data 
git init
dvc add data
```

### Expected
Show a correct error message

### Environment information

```bash
DVC version: 2.10.2.dev63+g8963f1f6
---------------------------------
Platform: Python 3.8.8 on macOS-10.16-x86_64-i386-64bit
Supports:
	azure (adlfs = 2021.10.0, knack = 0.8.0, azure-identity = 1.5.0),
	gdrive (pydrive2 = 1.9.4),
	gs (gcsfs = 2022.1.0),
	hdfs (fsspec = 2022.1.0, pyarrow = 3.0.0),
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	s3 (s3fs = 2022.1.0, boto3 = 1.20.24),
	ssh (sshfs = 2021.11.2),
	oss (ossfs = 2021.8.0),
	webdav (webdav4 = 0.9.3),
	webdavs (webdav4 = 0.9.3)
Repo: dvc, git (broken)
```

**Additional Information (if any):**

Looks like DVC tried to seek if the DVC root in the parent directory and throw an exception there as it was not a Git Repo
```
Traceback (most recent call last):
  File "/Users/gao/Code/scmrepo/scmrepo/git/backend/dulwich/__init__.py", line 118, in __init__
    self.repo = Repo.discover(start=root_dir)
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/dulwich/repo.py", line 1170, in discover
    raise NotGitRepository(
dulwich.errors.NotGitRepository: No git repository was found at /Users/gao/test
```

**Comment by tirkarthi** [comment]
```
Repo: dvc, git (broken)
```

I am unable to reproduce this error with the steps. It seems there is an `SCMError` raised such that the line above gets appended. Is `git rev-parse --is-inside-work-tree` working inside the directory?

https://stackoverflow.com/questions/2180270/check-if-current-directory-is-a-git-repository

**Comment by karajan1001** [comment]
I see, it was because there is some `.dvc` cache that remains in the parent directory.
