### ISSUE TITLE
pull: from SSH remote, does not follow ProxyJump in ~.ssh/config

### ISSUE THREAD

**Issue by pwrightkcl** [iterative/dvc#7800]
# Bug Report

## Description

When an SSH remote needs to be reached via a ProxyJump connection, `dvc pull` cannot connect to it.

### Reproduce

Set up ~/.ssh/config to allow connection to the server behind the proxy, example:

```console
Host main
    ServerAliveInterval 60
    ServerAliveCountMax 10
    User memain
    HostName 1.2.3.4
    IdentityFile ~/.ssh/id_rsa
    ProxyJump meproxy@proxy.tld
```

Test ssh from the terminal to check the ProxyJump and SSH keys for both proxy and main are working:

```console
melocal@local:~$ ssh main
memain@main:~$ exit
```

Pull the git repo to the local machine. Set up a local remote with the full SSH URL

```console
melocal@local:~/dvc_repo$ dvc remote add --local fromlocal ssh://memain@main:/path/to/dvc/remote
melocal@local:~/dvc_repo$ cat .dvc/config.local
[cache]
    dir = cache
['remote "fromlocal"']
    url = ssh://memain@main:/path/to/dvc/remote
```

Trying to pull from the remote gives an SSH connection error:

```console
melocal@local:~$ dvc pull -r from local
ERROR: unexpected error - [Errno 61] Connect call failed ('1.2.3.4', 22)

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

### Expected

DVC pulls the data from the remote.

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.8.5 on macOS-10.16-x86_64-i386-64bit
Supports:
	webhdfs (fsspec = 2022.5.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	ssh (sshfs = 2022.3.1)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: local, ssh
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git
```

**Additional Information (if any):**

The verbose output was really long, and I didn't want to go through and anonymise it all, but I can do it later if needed.

**Comment by pwrightkcl** [comment]
This may relate to #3815, which fixed ProxyCommand not working. That fix may not have fixed ProxyJump.

**Comment by pmrowla** [comment]
#3815 is not related since we no longer use paramiko.

sshfs/asyncssh should support ProxyJump w/SSH keys (https://github.com/fsspec/sshfs/issues/14), we will likely need the verbose output to determine what the problem is here

**Comment by pwrightkcl** [comment]
Here is the verbose output, user and paths changed:
```console
(venv) me@local test_dvc_data_registry % dvc pull -r fromlocal -v
2022-05-24 09:41:06,741 DEBUG: Preparing to transfer data from '/remote/path/test_dvc_cache' to '/Users/me/Data/test_dvc_data_registry/.dvc/cache'
2022-05-24 09:41:06,741 DEBUG: Preparing to collect status from '/Users/me/Data/test_dvc_data_registry/.dvc/cache'
2022-05-24 09:41:06,741 DEBUG: Collecting status from '/Users/me/Data/test_dvc_data_registry/.dvc/cache'
2022-05-24 09:41:06,742 DEBUG: Preparing to collect status from '/remote/path/test_dvc_cache'
2022-05-24 09:41:06,742 DEBUG: Collecting status from '/remote/path/test_dvc_cache'
2022-05-24 09:41:06,743 DEBUG: Querying 1 hashes via object_exists
2022-05-24 09:41:25,874 ERROR: unexpected error - [Errno 61] Connect call failed ('1.2.3.4', 22)
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/output.py", line 852, in get_dir_cache
    ocheck(self.odb, obj)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/data/__init__.py", line 19, in check
    odb.check(obj.hash_info, **kwargs)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/objects/db.py", line 181, in check
    obj.check(self, check_hash=check_hash)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/objects/file.py", line 65, in check
    self._check_hash(odb)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/objects/file.py", line 71, in _check_hash
    _, actual = get_file_hash(
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/data/stage.py", line 92, in get_file_hash
    meta, hash_info = _get_file_hash(fs_path, fs, name)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/data/stage.py", line 66, in _get_file_hash
    info = _adapt_info(fs.info(fs_path), fs.scheme)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/fs/base.py", line 309, in info
    return self.fs.info(path)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/fs/local.py", line 54, in info
    return self.fs.info(path)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/fsspec/implementations/local.py", line 80, in info
    out = os.stat(path, follow_symlinks=False)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/me/Data/test_dvc_data_registry/.dvc/cache/1f/f1cec4dd61736bdaaa47a4744175a7.dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/cli/__init__.py", line 90, in main
    ret = cmd.do_run()
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/commands/data_sync.py", line 31, in run
    stats = self.repo.pull(
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/repo/pull.py", line 34, in pull
    processed_files_count = self.fetch(
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/repo/fetch.py", line 45, in fetch
    used = self.used_objs(
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 418, in used_objs
    for odb, objs in self.index.used_objs(
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/repo/index.py", line 226, in used_objs
    for odb, objs in stage.get_used_objs(
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/stage/__init__.py", line 661, in get_used_objs
    for odb, objs in out.get_used_objs(*args, **kwargs).items():
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/output.py", line 934, in get_used_objs
    obj = self._collect_used_dir_cache(**kwargs)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/output.py", line 874, in _collect_used_dir_cache
    self.get_dir_cache(jobs=jobs, remote=remote)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/output.py", line 856, in get_dir_cache
    self.repo.cloud.pull([obj.hash_info], **kwargs)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/data_cloud.py", line 114, in pull
    return transfer(
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/data/transfer.py", line 154, in transfer
    status = compare_status(
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/data/status.py", line 186, in compare_status
    src_exists, src_missing = status(
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/data/status.py", line 136, in status
    exists = hashes.intersection(
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/data/status.py", line 56, in _indexed_dir_hashes
    dir_exists.update(
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/objects/db.py", line 345, in list_hashes_exists
    yield from itertools.compress(hashes, in_remote)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/fs/base.py", line 244, in exists
    return self.fs.exists(path)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/funcy/objects.py", line 50, in __get__
    return prop.__get__(instance, type)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/dvc/fs/ssh.py", line 120, in fs
    return _SSHFileSystem(**self.fs_args)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/sshfs/spec.py", line 76, in __init__
    self._client, self._pool = self.connect(
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 86, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 66, in sync
    raise return_result
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 26, in _runner
    result[0] = await coro
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/sshfs/utils.py", line 27, in wrapper
    return await func(*args, **kwargs)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/sshfs/spec.py", line 91, in _connect
    client = await self._stack.enter_async_context(_raw_client)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 568, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/asyncssh/misc.py", line 274, in __aenter__
    self._coro_result = await self._coro
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/asyncssh/connection.py", line 7707, in connect
    return await asyncio.wait_for(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/Users/me/Data/test_dvc_data_registry/venv/lib/python3.8/site-packages/asyncssh/connection.py", line 430, in _connect
    _, session = await loop.create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/selector_events.py", line 526, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 61] Connect call failed ('10.202.67.206', 22)
------------------------------------------------------------
2022-05-24 09:41:26,094 DEBUG: Version info for developers:
DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.8.5 on macOS-10.16-x86_64-i386-64bit
Supports:
	webhdfs (fsspec = 2022.5.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	ssh (sshfs = 2022.3.1)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: local, ssh
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-05-24 09:41:26,096 DEBUG: Analytics is enabled.
2022-05-24 09:41:26,160 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/v6/8mt3x7617z71jg30d2pc17nc0000gn/T/tmptamf7vws']'
2022-05-24 09:41:26,162 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/v6/8mt3x7617z71jg30d2pc17nc0000gn/T/tmptamf7vws']'
(venv) me@local test_dvc_data_registry %
```

**Comment by miguelvalente** [comment]
@pwrightkcl Can you share the steps on Linux. I'm simply doing what they say https://dvc.org/doc/start/data-management.

I can push to a brand new dir on a server iff i don't have to go through a proxyjump.

**Comment by miguelvalente** [comment]
Update!

I replaced proxyJump with ProxyCommand and now it works.

```
Host odm
    HostName 123.123.123.13
    User me
    IdentityFile ~/.ssh/id_rsa
    ProxyCommand ssh -W %h:%p bastion
    # ProxyJump bastion

```
