### ISSUE TITLE
dvc push: it's run successfully but the remote path has no file

### ISSUE THREAD

**Issue by harvey-che** [iterative/dvc#7807]
# Bug Report

## Description
I setup a hdfs path as remote storage, and dvc add and then push a file successfully according to the terminal message. But I can't see files in the hdfs path.

### Reproduce
0, dvc init
1, dvc add data.csv
2, dvc remote add -d myhdfs hdfs://xxx/yyy
3, dvc push
4, hadoop fs -ls hdfs://xxx/yyy

### Expected
Expect to see some files in the hdfs path after pushing successfully, but got nothing there.

### Environment information

**Output of `hadoop fs -ls hdfs://xxx/yyy`:**

```console
$ 
```

**Additional Information (if any):**
After runing dvc push, the output is 
```console
$ 0% Querying cache in yyy|                                                                                                                                        
22/05/24 20:50:26 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
22/05/24 20:50:26 WARN shortcircuit.DomainSocketFactory: The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
Everything is up to date.
```

**Comment by daavoo** [comment]
hi @harvey-che , could you share the output of `dvc doctor` and `dvc push -v` ?

**Comment by harvey-che** [comment]
The output of dvc doctor

```console
DVC version: 2.10.1 (pip)
---------------------------------
Platform: Python 3.7.11 on Linux-4.15.0-42-shopee-generic-x86_64-with-debian-stretch-sid
Supports:
	hdfs (fsspec = 2022.3.0, pyarrow = 6.0.1),
	webhdfs (fsspec = 2022.3.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb4
Caches: local
Remotes: hdfs
Workspace directory: ext4 on /dev/sdb4
Repo: dvc, git
```

The output of dvc push -v
```
2022-05-24 23:09:04,967 DEBUG: Preparing to transfer data from '/data/zhihua/codebase/global_attr_pred/.dvc/cache' to 'user/zhihua.che/dvc_storage'
2022-05-24 23:09:04,967 DEBUG: Preparing to collect status from 'user/zhihua.che/dvc_storage'
2022-05-24 23:09:04,967 DEBUG: Collecting status from 'user/zhihua.che/dvc_storage'
2022-05-24 23:09:04,968 DEBUG: Querying 1 hashes via object_exists
Environment variable CLASSPATH not set!
getJNIEnv: getGlobalJNIEnv failed
Environment variable CLASSPATH not set!
getJNIEnv: getGlobalJNIEnv failed
/arrow/cpp/src/arrow/filesystem/hdfs.cc:52: Failed to disconnect hdfs client: IOError: HDFS hdfsFS::Disconnect failed, errno: 255 (Unknown error 255) Please check that you are connecting to the correct HDFS RPC port
2022-05-24 23:09:04,976 ERROR: unexpected error - HDFS connection failed
------------------------------------------------------------
Traceback (most recent call last):
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/cli/__init__.py", line 89, in main
    ret = cmd.do_run()
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/commands/data_sync.py", line 68, in run
    glob=self.args.glob,
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/repo/push.py", line 69, in push
    obj_ids, jobs, remote=remote, odb=odb or dest_odb
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/data_cloud.py", line 91, in push
    cache_odb=self.repo.odb.local,
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/data/transfer.py", line 155, in transfer
    src, dest, obj_ids, check_deleted=False, jobs=jobs, **kwargs
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/data/status.py", line 164, in compare_status
    dest, obj_ids, index=dest_index, jobs=jobs, **kwargs
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/data/status.py", line 135, in status
    exists.update(odb.hashes_exist(hashes, name=odb.fs_path, jobs=jobs))
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/objects/db.py", line 419, in hashes_exist
    remote_hashes = self.list_hashes_exists(hashes, jobs, name)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/objects/db.py", line 370, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/objects/db.py", line 361, in exists_with_progress
    ret = self.fs.exists(fs_path)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/fs/fsspec_wrapper.py", line 81, in exists
    return self.fs.exists(path)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/funcy/objects.py", line 50, in __get__
    return prop.__get__(instance, type)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/fs/hdfs.py", line 49, in fs
    return HadoopFileSystem(**self.fs_args)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/fsspec/spec.py", line 68, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/fsspec/implementations/arrow.py", line 240, in __init__
    extra_conf=extra_conf,
  File "pyarrow/_hdfs.pyx", line 89, in pyarrow._hdfs.HadoopFileSystem.__init__
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
OSError: HDFS connection failed
------------------------------------------------------------
2022-05-24 23:09:05,102 DEBUG: [Errno 95] no more link types left to try out: [Errno 95] 'reflink' is not supported by <class 'dvc.fs.local.LocalFileSystem'>: [Errno 95] Operation not supported
------------------------------------------------------------
Traceback (most recent call last):
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/cli/__init__.py", line 89, in main
    ret = cmd.do_run()
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/commands/data_sync.py", line 68, in run
    glob=self.args.glob,
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/repo/push.py", line 69, in push
    obj_ids, jobs, remote=remote, odb=odb or dest_odb
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/data_cloud.py", line 91, in push
    cache_odb=self.repo.odb.local,
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/data/transfer.py", line 155, in transfer
    src, dest, obj_ids, check_deleted=False, jobs=jobs, **kwargs
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/data/status.py", line 164, in compare_status
    dest, obj_ids, index=dest_index, jobs=jobs, **kwargs
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/data/status.py", line 135, in status
    exists.update(odb.hashes_exist(hashes, name=odb.fs_path, jobs=jobs))
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/objects/db.py", line 419, in hashes_exist
    remote_hashes = self.list_hashes_exists(hashes, jobs, name)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/objects/db.py", line 370, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/objects/db.py", line 361, in exists_with_progress
    ret = self.fs.exists(fs_path)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/fs/fsspec_wrapper.py", line 81, in exists
    return self.fs.exists(path)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/funcy/objects.py", line 50, in __get__
    return prop.__get__(instance, type)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/fs/hdfs.py", line 49, in fs
    return HadoopFileSystem(**self.fs_args)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/fsspec/spec.py", line 68, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/fsspec/implementations/arrow.py", line 240, in __init__
    extra_conf=extra_conf,
  File "pyarrow/_hdfs.pyx", line 89, in pyarrow._hdfs.HadoopFileSystem.__init__
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
OSError: HDFS connection failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/fs/utils.py", line 28, in _link
    func(from_path, to_path)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/fs/local.py", line 145, in reflink
    System.reflink(from_info, to_info)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/system.py", line 112, in reflink
    System._reflink_linux(source, link_name)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/system.py", line 96, in _reflink_linux
    fcntl.ioctl(d.fileno(), FICLONE, s.fileno())
OSError: [Errno 95] Operation not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/fs/utils.py", line 69, in _try_links
    return _link(link, from_fs, from_path, to_fs, to_path)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/fs/utils.py", line 34, in _link
    ) from exc
OSError: [Errno 95] 'reflink' is not supported by <class 'dvc.fs.local.LocalFileSystem'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/fs/utils.py", line 124, in _test_link
    _try_links([link], from_fs, from_file, to_fs, to_file)
  File "/data/zhihua/anaconda3/envs/tf2/lib/python3.7/site-packages/dvc/fs/utils.py", line 79, in _try_links
    ) from error
OSError: [Errno 95] no more link types left to try out
------------------------------------------------------------
2022-05-24 23:09:05,103 DEBUG: Removing '/data/zhihua/codebase/.issVeBCrHpPffFtcyEUBrN.tmp'
2022-05-24 23:09:05,103 DEBUG: Removing '/data/zhihua/codebase/.issVeBCrHpPffFtcyEUBrN.tmp'
2022-05-24 23:09:05,103 DEBUG: Removing '/data/zhihua/codebase/.issVeBCrHpPffFtcyEUBrN.tmp'
2022-05-24 23:09:05,103 DEBUG: Removing '/data/zhihua/codebase/global_attr_pred/.dvc/cache/.ZYXks8sDdZ2WbhcPHvgPZb.tmp'
2022-05-24 23:09:05,108 DEBUG: Version info for developers:
DVC version: 2.10.1 (pip)
---------------------------------
Platform: Python 3.7.11 on Linux-4.15.0-42-shopee-generic-x86_64-with-debian-stretch-sid
Supports:
        hdfs (fsspec = 2022.3.0, pyarrow = 6.0.1),
        webhdfs (fsspec = 2022.3.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb4
Caches: local
Remotes: hdfs
Workspace directory: ext4 on /dev/sdb4
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-05-24 23:09:05,110 DEBUG: Analytics is enabled.
2022-05-24 23:09:05,150 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpguqrx5j8']'
2022-05-24 23:09:05,152 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpguqrx5j8']'
```

**Comment by daavoo** [comment]
@harvey-che Which is your dvc version? (`dvc doctor`)

**Comment by harvey-che** [comment]
@daavoo dvc version is 2.10.1

**Comment by daavoo** [comment]
> @daavoo dvc version is 2.10.1

Could you try with `2.10.2`? I think this was solved in https://github.com/iterative/dvc/pull/7563

**Comment by harvey-che** [comment]
@daavoo I tried 2.10.2, and it worked. I can push to and find the files in my remote path.
