### ISSUE TITLE
ERROR: failed to get 'my_data' from 'my_repo'

### ISSUE THREAD

**Issue by TranThanh96** [iterative/dvc#7871]
I created my dvc repository and push data successfully. But when I use "dvc get link_my_repo", an error occurs. Here is log:
[log.txt](https://github.com/iterative/dvc/files/8875673/log.txt)
 
 ```console
$ dvc get https://github.com/TranThanh96/dvc_tut facemask -v
2022-06-10 10:48:29,940 DEBUG: Creating external repo https://github.com/TranThanh96/dvc_tut@None
2022-06-10 10:48:29,940 DEBUG: erepo: git clone 'https://github.com/TranThanh96/dvc_tut' to a temporary dir
2022-06-10 10:48:32,638 DEBUG: Removing '/u01/thanhtm/workspace/DVC_tutorial/.9tJR9JSqVEE4ysKFzk3EAB'
2022-06-10 10:48:32,642 ERROR: unexpected error
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/cli/__init__.py", line 185, in main
  File "dvc/cli/command.py", line 36, in do_run
  File "dvc/commands/get.py", line 33, in run
  File "dvc/commands/get.py", line 39, in _get_file_from_repo
  File "dvc/repo/get.py", line 67, in get
  File "dvc_objects/fs/base.py", line 471, in get
  File "dvc_objects/fs/base.py", line 319, in find
  File "fsspec/spec.py", line 444, in find
  File "fsspec/spec.py", line 392, in walk
  File "dvc/fs/dvc.py", line 335, in ls
  File "dvc_objects/fs/base.py", line 312, in ls
  File "dvc/fs/data.py", line 100, in ls
  File "dvc_data/tree.py", line 211, in ls
dvc_data.tree.TreeError
------------------------------------------------------------
2022-06-10 10:48:33,158 DEBUG: Version info for developers:
DVC version: 2.11.0 (deb)
---------------------------------
Platform: Python 3.8.3 on Linux-5.4.0-91-generic-x86_64-with-glibc2.14
Supports:
	azure (adlfs = 2022.4.0, knack = 0.9.0, azure-identity = 1.10.0),
	gdrive (pydrive2 = 1.10.1),
	gs (gcsfs = 2022.5.0),
	hdfs (fsspec = 2022.5.0, pyarrow = 8.0.0),
	webhdfs (fsspec = 2022.5.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.5.0, boto3 = 1.21.21),
	ssh (sshfs = 2022.6.0),
	oss (ossfs = 2021.8.0),
	webdav (webdav4 = 0.9.7),
	webdavs (webdav4 = 0.9.7)

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-06-10 10:48:33,159 DEBUG: Analytics is enabled.
2022-06-10 10:48:33,159 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpweljuw3t']'
2022-06-10 10:48:33,161 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpweljuw3t']'
```

**Comment by dtrifiro** [comment]
Hi! I cannot seem to reproduce on a fresh install on `ubuntu 20.04`. Could you try re-installing dvc and check if that helps? Thanks!

**Comment by TranThanh96** [comment]
> Hi! I cannot seem to reproduce on a fresh install on `ubuntu 20.04`. Could you try re-installing dvc and check if that helps? Thanks!

yes, I tried to reinstall (by pip, conda, apt-get) but getting some other errors.

**Comment by dtrifiro** [comment]
Could you post full tracebacks?

**Comment by TranThanh96** [comment]
> Could you post full tracebacks?

yes ? How could I do to provide you more infomation?

**Comment by dtrifiro** [comment]
> but getting some other errors.
Do you mean you're getting different errors than the one you first reported while running `dvc get`? If so, could you re-run the command that's failing with the `-v` flag and post the full output of the command?

**Comment by TranThanh96** [comment]
> > but getting some other errors.
> 
> Do you mean you're getting different errors than the one you first reported while running `dvc get`? If so, could you re-run the command that's failing with the `-v` flag and post the full output of the command?

no, I tried to reinstall DVC but still get that error which is mentioned above. And I attached a log file.

**Comment by daavoo** [comment]
> Hello, after I had successfully pushed my dataset to s3 and pushed my code to git, I executed `dvc list MyProjectAddress` and i get error: failed to list MyProjectAddress - Failed to clone repo MyProjectAddress to '/var/folders/4t/v1175pvs19b_skbgygbqchd00000gn/T/tmp0ob8qi1xdvc-clone'. All my files tracked by dvc is in the root of project. Is there anyway to get more error messages?

Hi @Ichiruchan . You can run the command with debug flags `dvc list -vv MyProjectAddress`

**Comment by efiop** [comment]
Closing as stale.
