### ISSUE TITLE
ERROR: unexpected error - Passphrase must be specified to import encrypted private keys

### ISSUE THREAD

**Issue by SharadSirsat** [iterative/dvc#7901]
# Bug Report

### Reproduce

```
Traceback (most recent call last):
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/command/data_sync.py", line 30, in run
    stats = self.repo.pull(
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/repo/pull.py", line 29, in pull
    processed_files_count = self.fetch(
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/repo/fetch.py", line 40, in fetch
    used = self.used_objs(
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/repo/__init__.py", line 431, in used_objs
    for odb, objs in self.index.used_objs(
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/repo/index.py", line 186, in used_objs
    for odb, objs in stage.get_used_objs(
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/stage/__init__.py", line 660, in get_used_objs
    for odb, objs in out.get_used_objs(*args, **kwargs).items():
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/output.py", line 940, in get_used_objs
    obj = self._collect_used_dir_cache(**kwargs)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/output.py", line 882, in _collect_used_dir_cache
    self.get_dir_cache(jobs=jobs, remote=remote)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/output.py", line 864, in get_dir_cache
    self.repo.cloud.pull([obj.hash_info], **kwargs)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/data_cloud.py", line 114, in pull
    return transfer(
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/objects/transfer.py", line 153, in transfer
    status = compare_status(src, dest, obj_ids, check_deleted=False, **kwargs)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/objects/status.py", line 164, in compare_status
    src_exists, src_missing = status(
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/objects/status.py", line 122, in status
    exists = hashes.intersection(
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/objects/status.py", line 48, in _indexed_dir_hashes
    dir_exists.update(odb.list_hashes_exists(dir_hashes - dir_exists))
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/objects/db/base.py", line 421, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/home/sharad/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 600, in result_iterator
    yield fs.pop().result()
  File "/home/sharad/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/home/sharad/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/sharad/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/objects/db/base.py", line 412, in exists_with_progress
    ret = self.fs.exists(fs_path)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/fs/fsspec_wrapper.py", line 91, in exists
    return self.fs.exists(path)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/funcy/objects.py", line 50, in __get__
    return prop.__get__(instance, type)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/dvc/fs/ssh.py", line 124, in fs
    return _SSHFileSystem(**self.fs_args)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/fsspec/spec.py", line 68, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/sshfs/spec.py", line 77, in __init__
    self._client, self._pool = self.connect(
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/home/sharad/miniconda3/lib/python3.9/asyncio/tasks.py", line 478, in wait_for
    return fut.result()
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/sshfs/utils.py", line 27, in wrapper
    return await func(*args, **kwargs)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/sshfs/spec.py", line 92, in _connect
    client = await self._stack.enter_async_context(_raw_client)
  File "/home/sharad/miniconda3/lib/python3.9/contextlib.py", line 556, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/asyncssh/misc.py", line 223, in __aenter__
    self._result = await self._coro
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/asyncssh/connection.py", line 6887, in connect
    options = SSHClientConnectionOptions(options, config=config, host=host,
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/asyncssh/connection.py", line 5596, in __init__
    super().__init__(options=options, last_config=last_config, **kwargs)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/asyncssh/misc.py", line 271, in __init__
    self.prepare(**self.kwargs)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/asyncssh/connection.py", line 6329, in prepare
    self.client_keys = load_keypairs(client_keys, passphrase,
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/asyncssh/public_key.py", line 3152, in load_keypairs
    key, certs = read_private_key_and_certs(key, passphrase)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/asyncssh/public_key.py", line 2969, in read_private_key_and_certs
    key, cert = import_private_key_and_certs(read_file(filename), passphrase)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/asyncssh/public_key.py", line 2859, in import_private_key_and_certs
    key, end = _decode_private(data, passphrase)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/asyncssh/public_key.py", line 2519, in _decode_private
    key = _decode_pem_private(pem_name, headers, data, passphrase)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/asyncssh/public_key.py", line 2433, in _decode_pem_private
    return _decode_openssh_private(data, passphrase)
  File "/home/sharad/.local/pipx/venvs/dvc/lib/python3.9/site-packages/asyncssh/public_key.py", line 2276, in _decode_openssh_private
    raise KeyImportError('Passphrase must be specified to import '
asyncssh.public_key.KeyImportError: Passphrase must be specified to import encrypted private keys
```

output of `dvc doctor `is :
```
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.9.1 on Linux-5.15.0-37-generic-x86_64-with-glibc2.35
Supports:
	azure (adlfs = 2021.10.0, knack = 0.9.0, azure-identity = 1.7.1),
	gdrive (pydrive2 = 1.10.0),
	gs (gcsfs = 2022.1.0),
	hdfs (fsspec = 2022.1.0, pyarrow = 6.0.1),
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.1.0, boto3 = 1.20.24),
	ssh (sshfs = 2021.11.2),
	oss (ossfs = 2021.8.0),
	webdav (webdav4 = 0.9.4),
	webdavs (webdav4 = 0.9.4)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: ssh
Workspace directory: zfs on rpool/USERDATA/sharad_e6y7rt
Repo: dvc, git
```

I ma using ubuntu 22.04. 
```

**Comment by skshetry** [comment]
@SharadSirsat, did you intend to use encrypted keys?

**Comment by SharadSirsat** [comment]
I have tried to set the password by setting up the config.local by using the same command as you have provided but it did not work out. I am still facing the same issue.

**Comment by SharadSirsat** [comment]
Earlier I never need to use the password as I have passphrase for my SSH key. I try to establish ssh connection with my server with passphrase and it connects successfully.
I am facing this issue for only one repo other repos seems to work fine without entering/setting up any password in config

**Comment by skshetry** [comment]
> I am facing this issue for only one repo other repos seems to work fine without entering/setting up any password in config

Do you use imports in this repository? In that case, dvc does not read local configs. You can try setting the passphrase as a global config:
```console
dvc remote modify --global <remote_name> password <passphrase>
```

**Comment by skshetry** [comment]
@SharadSirsat, would you be able to debug why passphrase is not being passed? If yes, then you can try adding `--pdb` flag to the command, which will open up a `pdb`/`ipdb` on that error.
```console
dvc pull --pdb
```

We do set it here: 
https://github.com/iterative/dvc/blob/32fcc730785c9ae789eefaec626df024f06df4dc/dvc/fs/ssh.py#L81

**Comment by skshetry** [comment]
You can try jumping up in the stack and see if the config is being set properly. You can also try setting up a breakpoint in `SSHFileSystem`. I tried locally, and it seems it's being passed correctly, so I am not sure what's going on here.

**Comment by SharadSirsat** [comment]
Downgrading dvc version to 2.5.4 seems to work. I wonder why? It wasn't even working with 2.11 latest version.

**Comment by SharadSirsat** [comment]
Okay. Finally. I got rid of this error by removing passphrase that I have set for the SSH Key. But, I wonder, how should I use SSH key which is encrypted with dvc config without setting up password in dvc/config (but having a passphrase for ssh key). Any solutions for that?
This is weird because my other collugues have passphrase for their ssh key and they didnt set up the passphrase for dvc/config and still they dont face any issue like me.

**Comment by SharadSirsat** [comment]
I have encrypted the ssh key and did not set up password in dvc/config and it still works. Vola!! but weird behavior, intially it asked me for a passphrase while doing anything (for any command of dvc) and then i remove encryption and then it works. again I encrypted the ssh key and it works again.
Thank you for your suggestion and help!

**Comment by efiop** [comment]
@SharadSirsat There is a `ask_password` option that should help.
