### ISSUE TITLE
add: Doesn't add the data

### ISSUE THREAD

**Issue by geblanco** [iterative/dvc#7904]
# Bug Report

## Description

Dvc is unable to add a dataset composed of 150K files in images. The dataset is stored in another device.

### Reproduce

It's complicated to reproduce.... there are 30GB of downloaded images.

### Expected

Data should be added to cache and dvc file created correctly

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.11.0 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-109-generic-x86_64-with-glibc2.29
Supports:
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb1
Caches: local
Remotes: http
Workspace directory: ext4 on /dev/sdb1
Repo: dvc, git
```

**Additional Information (if any):**

Here is the complete traceback:
```
dvc add -v --external --file anchoring-experiments/tqa_sentence_images.dvc /media/usb8tb/rortega/anchoring-experiments/data/sentence_images
2022-06-16 12:29:53,257 DEBUG: Computed stage: 'anchoring-experiments/tqa_sentence_images.dvc' md5: 'None'
2022-06-16 12:29:56,115 DEBUG: Preparing to transfer data from '/home/gblanco/data-registry/.dvc/cache' to '/home/gblanco/data-registry/.dvc/cache'
2022-06-16 12:30:02,709 DEBUG: [Errno 95] no more link types left to try out: [Errno 18] Invalid cross-device link
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/generic.py", line 68, in _try_links
    return _link(link, from_fs, from_path, to_fs, to_path)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/generic.py", line 28, in _link
    func(from_path, to_path)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/base.py", line 282, in reflink
    return self.fs.reflink(from_info, to_info)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/implementations/local.py", line 157, in reflink
    return system.reflink(path1, path2)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/system.py", line 115, in reflink
    _reflink_linux(source, link_name)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/system.py", line 101, in _reflink_linux
    fcntl.ioctl(d.fileno(), FICLONE, s.fileno())
OSError: [Errno 18] Invalid cross-device link

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/generic.py", line 127, in _test_link
    _try_links([link], from_fs, from_file, to_fs, to_file)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/generic.py", line 76, in _try_links
    raise OSError(
OSError: [Errno 95] no more link types left to try out
------------------------------------------------------------
2022-06-16 12:30:02,712 DEBUG: Removing '/media/usb8tb/rortega/anchoring-experiments/data/.XLxbAAWSkm7bZSTprfCP9H.tmp'
2022-06-16 12:30:02,712 DEBUG: Removing '/media/usb8tb/rortega/anchoring-experiments/data/.XLxbAAWSkm7bZSTprfCP9H.tmp'
2022-06-16 12:30:02,712 DEBUG: Removing '/home/gblanco/data-registry/.dvc/cache/.hQP273M9yENX3QNzGVMzkx.tmp'
2022-06-16 12:30:02,713 DEBUG: Removing '/media/usb8tb/rortega/anchoring-experiments/data/sentence_images/329.the_radioactive_decay_of_a_parent_isotope_the_original_element_leads_to_the_formation_of_stable_daughter_productalso_known_as_daughter_isotope/8.new-chm-152unit10nuclearchemistrypowerpointssu13-23-320.jpg'
Adding...
2022-06-16 12:30:02,716 ERROR: unexpected error - [Errno 13] Permission denied: '/media/usb8tb/rortega/anchoring-experiments/data/sentence_images/329.the_radioactive_decay_of_a_parent_isotope_the_original_element_leads_to_the_formation_of_stable_daughter_productalso_known_as_daughter_isotope/8.new-chm-152unit10nuclearchemistrypowerpointssu13-23-320.jpg'
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/utils.py", line 85, in _unlink
    os.unlink(path)
PermissionError: [Errno 13] Permission denied: '/media/usb8tb/rortega/anchoring-experiments/data/sentence_images/329.the_radioactive_decay_of_a_parent_isotope_the_original_element_leads_to_the_formation_of_stable_daughter_productalso_known_as_daughter_isotope/8.new-chm-152unit10nuclearchemistrypowerpointssu13-23-320.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/commands/add.py", line 22, in run
    self.repo.add(
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/utils/collections.py", line 152, in inner
    result = func(*ba.args, **ba.kwargs)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/repo/scm_context.py", line 152, in run
    return method(repo, *args, **kw)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/repo/add.py", line 192, in add
    stage.commit()
  File "/home/gblanco/.local/lib/python3.8/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/home/gblanco/.local/lib/python3.8/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/stage/__init__.py", line 512, in commit
    out.commit(filter_info=filter_info)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/output.py", line 624, in commit
    self._checkout(
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/output.py", line 587, in _checkout
    return checkout(*args, **kwargs)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_data/checkout.py", line 271, in checkout
    _checkout(
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_data/checkout.py", line 216, in _checkout
    _checkout_file(
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_data/checkout.py", line 86, in _checkout_file
    _relink(
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_data/checkout.py", line 57, in _relink
    _remove(path, fs, in_cache, force=force, prompt=prompt)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_data/checkout.py", line 53, in _remove
    fs.remove(fs_path)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/base.py", line 335, in rm
    self.fs.rm(path, recursive=True)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/implementations/local.py", line 106, in rm
    remove(path)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/utils.py", line 97, in remove
    _unlink(path, _chmod)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/utils.py", line 87, in _unlink
    onerror(os.unlink, path, sys.exc_info())
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/utils.py", line 80, in _chmod
    func(p)
PermissionError: [Errno 13] Permission denied: '/media/usb8tb/rortega/anchoring-experiments/data/sentence_images/329.the_radioactive_decay_of_a_parent_isotope_the_original_element_leads_to_the_formation_of_stable_daughter_productalso_known_as_daughter_isotope/8.new-chm-152unit10nuclearchemistrypowerpointssu13-23-320.jpg'
------------------------------------------------------------
2022-06-16 12:30:03,007 DEBUG: [Errno 95] no more link types left to try out: [Errno 95] Operation not supported
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/utils.py", line 85, in _unlink
    os.unlink(path)
PermissionError: [Errno 13] Permission denied: '/media/usb8tb/rortega/anchoring-experiments/data/sentence_images/329.the_radioactive_decay_of_a_parent_isotope_the_original_element_leads_to_the_formation_of_stable_daughter_productalso_known_as_daughter_isotope/8.new-chm-152unit10nuclearchemistrypowerpointssu13-23-320.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/commands/add.py", line 22, in run
    self.repo.add(
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/utils/collections.py", line 152, in inner
    result = func(*ba.args, **ba.kwargs)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/repo/scm_context.py", line 152, in run
    return method(repo, *args, **kw)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/repo/add.py", line 192, in add
    stage.commit()
  File "/home/gblanco/.local/lib/python3.8/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/home/gblanco/.local/lib/python3.8/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/stage/__init__.py", line 512, in commit
    out.commit(filter_info=filter_info)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/output.py", line 624, in commit
    self._checkout(
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc/output.py", line 587, in _checkout
    return checkout(*args, **kwargs)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_data/checkout.py", line 271, in checkout
    _checkout(
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_data/checkout.py", line 216, in _checkout
    _checkout_file(
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_data/checkout.py", line 86, in _checkout_file
    _relink(
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_data/checkout.py", line 57, in _relink
    _remove(path, fs, in_cache, force=force, prompt=prompt)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_data/checkout.py", line 53, in _remove
    fs.remove(fs_path)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/base.py", line 335, in rm
    self.fs.rm(path, recursive=True)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/implementations/local.py", line 106, in rm
    remove(path)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/utils.py", line 97, in remove
    _unlink(path, _chmod)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/utils.py", line 87, in _unlink
    onerror(os.unlink, path, sys.exc_info())
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/utils.py", line 80, in _chmod
    func(p)
PermissionError: [Errno 13] Permission denied: '/media/usb8tb/rortega/anchoring-experiments/data/sentence_images/329.the_radioactive_decay_of_a_parent_isotope_the_original_element_leads_to_the_formation_of_stable_daughter_productalso_known_as_daughter_isotope/8.new-chm-152unit10nuclearchemistrypowerpointssu13-23-320.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/generic.py", line 68, in _try_links
    return _link(link, from_fs, from_path, to_fs, to_path)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/generic.py", line 28, in _link
    func(from_path, to_path)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/base.py", line 282, in reflink
    return self.fs.reflink(from_info, to_info)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/implementations/local.py", line 157, in reflink
    return system.reflink(path1, path2)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/system.py", line 115, in reflink
    _reflink_linux(source, link_name)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/system.py", line 101, in _reflink_linux
    fcntl.ioctl(d.fileno(), FICLONE, s.fileno())
OSError: [Errno 95] Operation not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/generic.py", line 127, in _test_link
    _try_links([link], from_fs, from_file, to_fs, to_file)
  File "/home/gblanco/.local/lib/python3.8/site-packages/dvc_objects/fs/generic.py", line 76, in _try_links
    raise OSError(
OSError: [Errno 95] no more link types left to try out
------------------------------------------------------------
2022-06-16 12:30:03,007 DEBUG: Removing '/home/gblanco/.TRYwfH8Pt6vYcgMQiTFZge.tmp'
2022-06-16 12:30:03,007 DEBUG: Removing '/home/gblanco/.TRYwfH8Pt6vYcgMQiTFZge.tmp'
2022-06-16 12:30:03,007 DEBUG: Removing '/home/gblanco/.TRYwfH8Pt6vYcgMQiTFZge.tmp'
2022-06-16 12:30:03,007 DEBUG: Removing '/home/gblanco/data-registry/.dvc/cache/.TUfGULRDLDZPTwkXtu7z3k.tmp'
2022-06-16 12:30:03,365 DEBUG: Version info for developers:
DVC version: 2.11.0 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-109-generic-x86_64-with-glibc2.29
Supports:
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb1
Caches: local
Remotes: http
Workspace directory: ext4 on /dev/sdb1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-06-16 12:30:03,500 DEBUG: Analytics is enabled.
2022-06-16 12:30:03,519 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmp47a8hh_h']'
2022-06-16 12:30:03,524 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmp47a8hh_h']'
```

**Comment by geblanco** [comment]
Hi @dberenbaum,

Yes, I do have read/write permissions over the entire disk.

**Comment by efiop** [comment]
closing as stale for now
