### ISSUE TITLE
init: unrelated dir throws unknown character

### ISSUE THREAD

**Issue by smallTrogdor** [iterative/dvc#8080]
# Bug Report

## Description

The input comands including creating new git repository:

```console
(base) PS C:\Users\u236343\repos> mkdir dvc_test


    Directory: C:\Users\u236343\repos


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       02.08.2022     15:53                dvc_test


(base) PS C:\Users\u236343\repos> cd .\dvc_test\
(base) PS C:\Users\u236343\repos\dvc_test> git init
Initialized empty Git repository in C:/Users/u236343/repos/dvc_test/.git/
(base) PS C:\Users\u236343\repos\dvc_test> dvc init
ERROR: unexpected error - escape character followed by unknown character 100 at 48 in bytearray(b'K:\\\\repos\\\\rcm-pp-wf-obm-es-converter-algorithm\\directory = K:/repos/rcm-pp-wf-obm-es-converter-algorithm')

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

The dvc init command throws an unexpected error due to a path in a complete different directory. I tried complete new install of dvc.

### Reproduce

1. create **non dvc** repo K:/repos/rcm-pp-wf-obm-es-converter-algorithm
2. create git & dvc repo in different location

### Expected

new dvc repo

### Environment information

**Output of `dvc doctor`:**
```console
$ dvc doctor
DVC version: 2.15.0 (exe)
---------------------------------
Platform: Python 3.8.10 on Windows-10-10.0.17763-SP0
Supports:
        azure (adlfs = 2022.7.0, knack = 0.9.0, azure-identity = 1.10.0),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = 2022.7.1),
        hdfs (fsspec = 2022.7.1, pyarrow = 8.0.0),
        webhdfs (fsspec = 2022.7.1),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
        s3 (s3fs = 2022.7.1, boto3 = 1.21.21),
        ssh (sshfs = 2022.6.0),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7)
```

### command with verbose
```console
(base) PS C:\Users\u236343\repos\dvc_test> dvc init --verbose
2022-08-02 16:03:00,775 ERROR: unexpected error - escape character followed by unknown character 100 at 48 in bytearray(b'K:\\\\repos\\\\rcm-pp-wf-obm-es-converter-algorithm\\directory = K:/repos/rcm-pp-wf-obm-es-converter-algorithm')
------------------------------------------------------------
Traceback (most recent call last):
  File "dulwich\config.py", line 437, in _parse_string
KeyError: 100

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc\cli\__init__.py", line 185, in main
  File "dvc\cli\command.py", line 36, in do_run
  File "dvc\commands\init.py", line 45, in run
  File "dvc\repo\__init__.py", line 362, in init
  File "dvc\repo\init.py", line 53, in init
  File "scmrepo\git\__init__.py", line 289, in _backend_func
  File "scmrepo\git\backend\dulwich\__init__.py", line 406, in is_ignored
  File "funcy\objects.py", line 28, in __get__
  File "scmrepo\git\backend\dulwich\__init__.py", line 397, in ignore_manager
  File "dulwich\ignore.py", line 388, in from_repo
  File "dulwich\repo.py", line 684, in get_config_stack
  File "dulwich\config.py", line 716, in default_backends
  File "dulwich\config.py", line 595, in from_path
  File "dulwich\config.py", line 585, in from_file
  File "dulwich\config.py", line 443, in _parse_string
ValueError: escape character followed by unknown character 100 at 48 in bytearray(b'K:\\\\repos\\\\rcm-pp-wf-obm-es-converter-algorithm\\directory = K:/repos/rcm-pp-wf-obm-es-converter-algorithm')
------------------------------------------------------------
2022-08-02 16:03:01,908 DEBUG: Version info for developers:
DVC version: 2.15.0 (exe)
---------------------------------
Platform: Python 3.8.10 on Windows-10-10.0.17763-SP0
Supports:
        azure (adlfs = 2022.7.0, knack = 0.9.0, azure-identity = 1.10.0),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = 2022.7.1),
        hdfs (fsspec = 2022.7.1, pyarrow = 8.0.0),
        webhdfs (fsspec = 2022.7.1),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
        s3 (s3fs = 2022.7.1, boto3 = 1.21.21),
        ssh (sshfs = 2022.6.0),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7)

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-08-02 16:03:01,939 DEBUG: Analytics is enabled.
2022-08-02 16:03:01,939 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\u236343\\AppData\\Local\\Temp\\2\\tmpnd_9tl6t']'
2022-08-02 16:03:01,955 DEBUG: Spawned '['daemon', '-q', 'analytics', 'C:\\Users\\u236343\\AppData\\Local\\Temp\\2\\tmpnd_9tl6t']'
(base) PS C:\Users\u236343\repos\dvc_test>
```

**Comment by smallTrogdor** [comment]
safe directory in gitconfig was the problem. The path was UNIX, on a Windows machine

**Comment by michelpf** [comment]
> safe directory in gitconfig was the problem. The path was UNIX, on a Windows machine

I had the same problem.

Just fix doing this:
```
git config --global --replace-all safe.directory *
```

More info, (here)[https://stackoverflow.com/questions/71849415/i-cannot-add-the-parent-directory-to-safe-directory-in-git] in this thread on Stackoverflow.
