### ISSUE TITLE
dvc pull error

### ISSUE THREAD

**Issue by jodv-ordina** [iterative/dvc#8122]
I am working on a project where dvc is used to version data stored on a s3 bucket. 
Everything worked fine until a week ago. Now dvc pull results in an error even though the data did not change over the course of that week.  Could updates on my windows laptop result in such behavior? 

```
PS C:\Users\JoDV\projects\give-face> dvc pull -v
2022-08-10 15:54:00,603 DEBUG: Preparing to transfer data from 'dvc-storage/give-face' to 'C:\Users\JoDV\projects\give-face\.dvc\cache'
2022-08-10 15:54:00,604 DEBUG: Preparing to collect status from 'C:\Users\JoDV\projects\give-face\.dvc\cache'
2022-08-10 15:54:00,605 DEBUG: Collecting status from 'C:\Users\JoDV\projects\give-face\.dvc\cache'
2022-08-10 15:54:00,610 DEBUG: Preparing to collect status from 'dvc-storage/give-face'
2022-08-10 15:54:00,612 DEBUG: Collecting status from 'dvc-storage/give-face'
2022-08-10 15:54:00,615 DEBUG: Querying 1 oids via object_exists
2022-08-10 15:54:01,188 DEBUG: Querying 1 oids via object_exists
2022-08-10 15:54:01,454 ERROR: unexpected error                                                             
------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\output.py", line 886, in get_dir_cache
    ocheck(self.odb, obj)
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc_data\__init__.py", line 21, in check
    odb.check(obj.oid, **kwargs)
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc_data\hashfile\db.py", line 136, in check
    _, actual = hash_file(obj.path, obj.fs, self.hash_name, self.state)
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc_data\hashfile\hash.py", line 186, in hash_file
    hash_value, info = _hash_file(path, fs, name, callback=cb)
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc_data\hashfile\hash.py", line 131, in _hash_file
    info = _adapt_info(fs.info(path), fs.protocol)
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc_objects\fs\base.py", line 346, in info
    return self.fs.info(path)
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc_objects\fs\implementations\local.py", line 52, in info
    return self.fs.info(path)
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\fsspec\implementations\local.py", line 83, in info
    out = os.stat(path, follow_symlinks=False)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/JoDV/projects/give-face/.dvc/cache/56/595f65ab4a1bd8d9b34342bb790728.dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\cli\__init__.py", line 185, in main
    ret = cmd.do_run()
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\cli\command.py", line 22, in do_run
    return self.run()
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\commands\data_sync.py", line 31, in run
    stats = self.repo.pull(
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\repo\__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\repo\pull.py", line 34, in pull
    processed_files_count = self.fetch(
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\repo\__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\repo\fetch.py", line 45, in fetch
    used = self.used_objs(
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\repo\__init__.py", line 429, in used_objs
    for odb, objs in self.index.used_objs(
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\repo\index.py", line 240, in used_objs
    for odb, objs in stage.get_used_objs(
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\stage\__init__.py", line 663, in get_used_objs
    for odb, objs in out.get_used_objs(*args, **kwargs).items():
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\output.py", line 968, in get_used_objs
    obj = self._collect_used_dir_cache(**kwargs)
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\output.py", line 908, in _collect_used_dir_cache
    self.get_dir_cache(jobs=jobs, remote=remote)
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\output.py", line 890, in get_dir_cache
    self.repo.cloud.pull([obj.hash_info], **kwargs)
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\data_cloud.py", line 136, in pull
    return self.transfer(
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc\data_cloud.py", line 88, in transfer
    return transfer(src_odb, dest_odb, objs, **kwargs)
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc_data\transfer.py", line 184, in transfer
    _do_transfer(
  File "c:\users\jodv\projects\give-face\.venv2\lib\site-packages\dvc_data\transfer.py", line 79, in _do_transfer
    assert dir_obj
AssertionError
------------------------------------------------------------
2022-08-10 15:54:01,777 DEBUG: link type reflink is not available ([Errno 129] no more link types left to try out)
2022-08-10 15:54:01,779 DEBUG: Removing 'C:\Users\JoDV\projects\.fwHdFPV5kVoE3v334juaC5.tmp'
2022-08-10 15:54:01,785 DEBUG: Removing 'C:\Users\JoDV\projects\.fwHdFPV5kVoE3v334juaC5.tmp'
2022-08-10 15:54:01,790 DEBUG: link type symlink is not available ([WinError 1314] A required privilege is not held by the client: 'C:\\Users\\JoDV\\projects\\give-face\\.dvc\\cache\\.RJn
KC23StpDzxuPrXTHnLF.tmp' -> 'C:\\Users\\JoDV\\projects\\.fwHdFPV5kVoE3v334juaC5.tmp')
2022-08-10 15:54:01,792 DEBUG: Removing 'C:\Users\JoDV\projects\.fwHdFPV5kVoE3v334juaC5.tmp'
2022-08-10 15:54:01,795 DEBUG: Removing 'C:\Users\JoDV\projects\give-face\.dvc\cache\.RJnKC23StpDzxuPrXTHnLF.tmp'
2022-08-10 15:54:01,806 DEBUG: Version info for developers:
DVC version: 2.17.0 (pip)
---------------------------------
Platform: Python 3.9.13 on Windows-10-10.0.19044-SP0
Supports:
        webhdfs (fsspec = 2022.7.1),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.7.0),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.7.0),
        s3 (s3fs = 2022.7.1, boto3 = 1.21.21)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: s3
Workspace directory: NTFS on C:\
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-08-10 15:54:01,819 DEBUG: Analytics is enabled.
2022-08-10 15:54:02,300 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\JoDV\\AppData\\Local\\Temp\\tmp211yj9ba']'
2022-08-10 15:54:02,310 DEBUG: Spawned '['daemon', '-q', 'analytics', 'C:\\Users\\JoDV\\AppData\\Local\\Temp\\tmp211yj9ba']'

```

**Comment by pmrowla** [comment]
@jodv-ordina did you upgrade from an older DVC version the last week?

**Comment by jodv-ordina** [comment]
> @jodv-ordina did you upgrade from an older DVC version the last week?

No i did not.

**Comment by pmrowla** [comment]
@jodv-ordina does anyone else share this DVC project with you? Is it possible that someone else forgot to do a `dvc push` to the remote?

**Comment by efiop** [comment]
closing as stale
