### ISSUE TITLE
sshfs not missing

### ISSUE THREAD

**Issue by Tel44** [iterative/dvc#8127]
dvc push reports 
```
ERROR: failed to push data to the cloud - URL 'ssh://' is supported but requires these missing dependencies: ['sshfs']. To install dvc with those dependencies, run

pip install 'dvc[ssh]'
```

pip freeze reports
```
sshfs==2022.6.0
```

This happens whenever I try to push to a ssh remote.

```
Traceback (most recent call last):
  File "/data/someenv/lib/python3.6/site-packages/dvc/command/data_sync.py", line 67, in run
    glob=self.args.glob,
  File "/data/someenv/lib/python3.6/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/data/someenv/lib/python3.6/site-packages/dvc/repo/push.py", line 48, in push
    pushed += self.cloud.push(obj_ids, jobs, remote=remote, odb=odb)
  File "/data/someenv/lib/python3.6/site-packages/dvc/data_cloud.py", line 84, in push
    odb = self.get_remote_odb(remote, "push")
  File "/data/someenv/lib/python3.6/site-packages/dvc/data_cloud.py", line 40, in get_remote_odb
    return self._init_odb(name)
  File "/data/someenv/lib/python3.6/site-packages/dvc/data_cloud.py", line 63, in _init_odb
    return get_odb(cls(**config), path_info, **config)
  File "/data/someenv/lib/python3.6/site-packages/dvc/fs/fsspec_wrapper.py", line 42, in __init__
    super().__init__(**kwargs)
  File "/data/someenv/lib/python3.6/site-packages/dvc/fs/base.py", line 62, in __init__
    self._check_requires(**kwargs)
  File "/data/someenv/lib/python3.6/site-packages/dvc/fs/base.py", line 128, in _check_requires
    f"URL '{url}' is supported but requires these missing "
dvc.fs.base.RemoteMissingDepsError: URL 'ssh://' is supported but requires these missing dependencies: ['sshfs']. To install dvc with those dependencies, run:
```

What makes this even more bizarre is:
```
which sshfs
/usr/bin/sshfs
```

**Comment by pmrowla** [comment]
You likely have a version of sshfs installed that is not compatible with the version of DVC that you have installed. DVC no longer supports Python 3.6 or 3.7, if you are in 3.6 your DVC installation is likely very outdated.

Please try Python 3.8 or later and then re-install DVC using `pip install dvc[ssh]` in a Python 3.8+ environment.

**Comment by Tel44** [comment]
I tried python 3.8 and that works. I'd suggest to add the python version requirement somewhere. Maybe the readme or at https://dvc.org/doc/start ?

**Comment by skshetry** [comment]
@Tel44, we do mention that we require a particular version of Python in the installation section.
https://dvc.org/doc/install/linux#install-with-pip

But it looks like we did not update that to reflect that we now require Python 3.8. I have opened the PR in https://github.com/iterative/dvc.org/pull/3874 for that.

**Comment by Tel44** [comment]
If you do not support older python versions at all, it would be worth mentioning that.

The missing piece is: Which versions are still supported?

**Comment by skshetry** [comment]
It is mentioned, it says `Python 3.7+`, which will be updated to `Python 3.8+` shortly.
