### ISSUE TITLE
add, init, doctor: database is locked

### ISSUE THREAD

**Issue by schwobr** [iterative/dvc#8176]
# Bug Report

## Description

I'm trying to create a data registry but it seems that I'm on some kind of edge case as I keep getting a `database is locked` error. My situation is as follows. I have a cifs mountpoint where new files are added on a regular basis directly in the root dir. These files are quite large (~1.5 GB each) and I'll have around 18000 of them when they'll all be added. The thing is that I can basically separate these files into 18 subcategories, that I wish to be able to pull separately. That is why a data registry seemed to be a good solution for me. As I don't want to modify anything from the original files in the source directory, I made a subdirectory called data_registry and created a directory structure that basically separated files in 18 subdirectories, each file actually being a hardlink to the original file in the root directory. It basically looks like this:
```
cifs_root_dir
│   file_1
│   file_2 
│   file_3 
│   ...
│
└───data_registry
│   │
│   └───subfolder1
│       │   hardlink_to_file_1
│       │   hardlink_to_file_3
│       │   ...
│   │
│   └───subfolder2
│       │   hardlink_to_file_2
│       │   ...
│   ...
```

Id like to create the data registry by still using hardlinks, so I configured cache type to use hardlink. Then when I use `dvc add anything` it raises a sqlite `database is locked` error. I did not try with other cache options, as reflinks are not available in my system and I don't want to copy data.

Note: the error already occurs when using `dvc init` after the `.dvcignore` file and the `.dvc` directory are created.

### Reproduce

```bash
dvc init #first occurrence of error
dvc cache.type hardlink
dvc add subfolder1 #second occurrence of error
```

### Expected

I basically expect my subfolders to be correctly added to the database.

### Environment information

**Output of `dvc doctor`:**
It actually raises the same error, here is the verbose output.
```console
$ dvc doctor
2022-08-24 15:42:24,497 ERROR: unexpected error - database is locked
------------------------------------------------------------
Traceback (most recent call last):
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/cli/command.py", line 36, in do_run
    return self.run()
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/commands/version.py", line 16, in run
    dvc_info = get_dvc_info()
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/info.py", line 30, in get_dvc_info
    with Repo() as repo:
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/repo/__init__.py", line 214, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc_data/hashfile/state.py", line 83, in __init__
    self.links = Cache(links_dir)
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/diskcache/core.py", line 2440, in reset
    sql('PRAGMA %s = %s' % (pragma, value)).fetchall()
sqlite3.OperationalError: database is locked
------------------------------------------------------------
Traceback (most recent call last):
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/cli/command.py", line 36, in do_run
    return self.run()
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/commands/version.py", line 16, in run
    dvc_info = get_dvc_info()
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/info.py", line 30, in get_dvc_info
    with Repo() as repo:
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/repo/__init__.py", line 214, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc_data/hashfile/state.py", line 83, in __init__
    self.links = Cache(links_dir)
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/diskcache/core.py", line 2440, in reset
    sql('PRAGMA %s = %s' % (pragma, value)).fetchall()
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/apps/conda/Robin/envs/apriorics/bin/dvc", line 8, in <module>
    sys.exit(main())
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/cli/__init__.py", line 211, in main
    ret = _log_exceptions(exc) or 255
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/cli/__init__.py", line 130, in _log_exceptions
    _log_unknown_exceptions()
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/cli/__init__.py", line 46, in _log_unknown_exceptions
    logger.debug("Version info for developers:\n%s", get_dvc_info())
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/info.py", line 30, in get_dvc_info
    with Repo() as repo:
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc/repo/__init__.py", line 214, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc_data/hashfile/state.py", line 83, in __init__
    self.links = Cache(links_dir)
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/data/apps/conda/Robin/envs/apriorics/lib/python3.9/site-packages/diskcache/core.py", line 2440, in reset
    sql('PRAGMA %s = %s' % (pragma, value)).fetchall()
sqlite3.OperationalError: database is locked
```

Main environment infos are:
* OS: CentOS Stream 8 on Linux-4.18.0-365.el8.x86_64-x86_64-with-glibc2.28
* python: 3.9.7
* dvc version 2.20.0 installed via pip in a conda environment
* cache and workspace in a mounted cifs filesystem

**Comment by schwobr** [comment]
After some more research it seems that the main problem comes from the interaction between sqlite3 lock management and the cifs filesystem, as explained in [this post](https://sqlite-users.sqlite.narkive.com/PkF3Wqkw/how-to-make-sqlite-run-safely-on-cifs-mounted-file-system). I therefore changed state.dir in the dvc config to a location in the main server and it now works fine. 

Closing this issue as it is basically resolved.
