### ISSUE TITLE
Return StageCmdFailedError when I import pycuda.autoinit

### ISSUE THREAD

**Issue by taikiinoue45** [iterative/dvc#8222]
# Bug Report

`run: Return StageCmdFailedError when I import pycuda.autoinit`

## Description
 When running `dvc run`, I got the following error. It seems to occur only under certain conditions (See details in the reproduce section). I have tried to solve this problem, but it's not easy for me. Could you please help me?

```
2022-09-01 06:17:44,924 ERROR: failed to run: python sandbox.py, exited with -11
```

### environment
gpu: GeForce RTX 3090
nvidia driver: 465.19.01
docker image: nvcr.io/nvidia/pytorch:22.06-py3
python libraries:
- dvc==2.23.0
- pycuda==2022.1
- torch==1.13.0a0+340c412

### python script
```python
import pycuda.autoinit
import torch

tsr = torch.randn(500, 500).to(device="cuda:0", dtype=torch.float32)
torch.linalg.inv(tsr)
```

### dvc command and error message
```shell
$ dvc run -f -v -n sandbox python sandbox.py
Running stage 'sandbox':                                              
> python sandbox.py
2022-09-01 06:17:44,924 ERROR: failed to run: python sandbox.py, exited with -11
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/dvc/commands/run.py", line 47, in run
    self.repo.run(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dvc/repo/scm_context.py", line 156, in run
    return method(repo, *args, **kw)
  File "/opt/conda/lib/python3.8/site-packages/dvc/repo/run.py", line 33, in run
    stage.run(no_commit=no_commit, run_cache=run_cache)
  File "/opt/conda/lib/python3.8/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/opt/conda/lib/python3.8/site-packages/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
  File "/opt/conda/lib/python3.8/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dvc/stage/__init__.py", line 561, in run
    self._run_stage(dry, force, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/opt/conda/lib/python3.8/site-packages/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
  File "/opt/conda/lib/python3.8/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dvc/stage/__init__.py", line 579, in _run_stage
    return run_stage(self, dry, force, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dvc/stage/run.py", line 152, in run_stage
    run(stage, dry=dry, checkpoint_func=checkpoint_func, run_env=run_env)
  File "/opt/conda/lib/python3.8/site-packages/dvc/stage/decorators.py", line 52, in wrapper
    ret = f(stage, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dvc/stage/run.py", line 136, in cmd_run
    _run(stage, executable, cmd, checkpoint_func=checkpoint_func, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dvc/stage/run.py", line 103, in _run
    raise StageCmdFailedError(cmd, p.returncode)
dvc.stage.exceptions.StageCmdFailedError: failed to run: python sandbox.py, exited with -11
------------------------------------------------------------
2022-09-01 06:17:44,926 DEBUG: Analytics is enabled.
2022-09-01 06:17:44,954 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpv5v_ivys']'
2022-09-01 06:17:44,955 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpv5v_ivys']'
```

## Additional Information

The error seems to occur when the three things are executed. The following 3 python script shouldn't return the error.
- `import pycuda.autoinit`
- `to(device="cuda:0")`
- `torch.linalg.inv`

without `import pycuda.autoinit`
```python
import torch

tsr = torch.randn(500, 500).to(device="cuda:0", dtype=torch.float32)
torch.linalg.inv(tsr)
```

without `to(device="cuda:0")`
```python
import pycuda.autoinit
import torch

tsr = torch.randn(500, 500)
torch.linalg.inv(tsr)
```

without `torch.linalg.inv`
```python
import pycuda.autoinit
import torch

tsr = torch.randn(500, 500).to(device="cuda:0", dtype=torch.float32)
```

**Comment by skshetry** [comment]
From the exception, it seems that it's your script that failed:
```console
failed to run: python sandbox.py, exited with -11
```

I'll suggest running your script manually, and see why it's failing. It does not seem like it's DVC-specific error. I'm closing this for now, please feel free to reopen it if it has something to do with dvc.

**Comment by taikiinoue45** [comment]
Sorry it's my bad. When I run just python, I got error..
```bash
$ python sandbox.py 
Segmentation fault (core dumped)
```
