### ISSUE TITLE
Cannot pull with "dvc pull" from gdrive.

### ISSUE THREAD

**Issue by Kamuzinzi** [iterative/dvc#8231]
# Bug Report

## Description

WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:                                                                                          
name: data/AdSmartABdata.csv, md5: 1ae19300fae64a8d41f40122d8f68a53
name: data/control_group_data.csv, md5: cfa31c5fe1ba45af5ed190bd5299dad2

**Output of `dvc doctor`:**
DVC version: 2.24.0 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.15.0-46-generic-x86_64-with-glibc2.29
Subprojects:
        dvc_data = 0.4.0
        dvc_objects = 0.2.0
        dvc_render = 0.0.9
        dvc_task = 0.1.2
        dvclive = 0.10.0
        scmrepo = 0.0.25
Supports:
        gdrive (pydrive2 = 1.14.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda5
Caches: local
Remotes: gdrive
Workspace directory: ext4 on /dev/sda5
Repo: dvc, git

**Additional Information (if any):**

**Comment by rlamy** [comment]
What output do you get with `dvc pull -vv` please?

**Comment by Kamuzinzi** [comment]
> What output do you get with `dvc pull -vv` please?

(env) egide@egide-VirtualBox:~/Documents/tenAcademy/week 2/abtest-mlops$ dvc pull -vv 
2022-09-02 08:46:33,659 TRACE: Namespace(all_branches=False, all_commits=False, all_tags=False, cd='.', cmd='pull', cprofile=False, cprofile_dump=None, force=False, func=<class 'dvc.commands.data_sync.CmdDataPull'>, glob=False, instrument=False, instrument_open=False, jobs=None, parser=DvcParser(prog='dvc', usage=None, description='Data Version Control', formatter_class=<class 'argparse.RawTextHelpFormatter'>, conflict_handler='error', add_help=False), pdb=False, quiet=0, recursive=False, remote=None, run_cache=False, targets=[], verbose=2, version=None, viztracer=False, viztracer_depth=None, with_deps=False, yappi=False)
2022-09-02 08:46:34,003 TRACE:     1.67 ms in collecting stages from /home/egide/Documents/tenAcademy/week 2/abtest-mlops
2022-09-02 08:46:34,006 TRACE:     7.33 mks in collecting stages from /home/egide/Documents/tenAcademy/week 2/abtest-mlops/tests
2022-09-02 08:46:34,007 TRACE:   181.09 mks in collecting stages from /home/egide/Documents/tenAcademy/week 2/abtest-mlops/scripts
2022-09-02 08:46:34,064 TRACE:    56.29 ms in collecting stages from /home/egide/Documents/tenAcademy/week 2/abtest-mlops/data
2022-09-02 08:46:34,067 TRACE:   100.60 mks in collecting stages from /home/egide/Documents/tenAcademy/week 2/abtest-mlops/notebooks
2022-09-02 08:46:34,078 DEBUG: Preparing to transfer data from '1zV2M1g6rzVVuSXMgf3tPaJPEBQUymyKq' to '/home/egide/Documents/tenAcademy/week 2/abtest-mlops/.dvc/cache'
2022-09-02 08:46:34,078 DEBUG: Preparing to collect status from '/home/egide/Documents/tenAcademy/week 2/abtest-mlops/.dvc/cache'
2022-09-02 08:46:34,078 DEBUG: Collecting status from '/home/egide/Documents/tenAcademy/week 2/abtest-mlops/.dvc/cache'
2022-09-02 08:46:34,079 DEBUG: Preparing to collect status from '1zV2M1g6rzVVuSXMgf3tPaJPEBQUymyKq'                                                                                        
2022-09-02 08:46:34,079 DEBUG: Collecting status from '1zV2M1g6rzVVuSXMgf3tPaJPEBQUymyKq'
2022-09-02 08:46:35,306 DEBUG: Estimated remote size: 256 files                                                                                                                            
2022-09-02 08:46:35,310 DEBUG: Querying '2' oids via traverse                                                                                                                              
2022-09-02 08:46:35,771 WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:                                                                  
name: data/control_group_data.csv, md5: cfa31c5fe1ba45af5ed190bd5299dad2
name: data/AdSmartABdata.csv, md5: 1ae19300fae64a8d41f40122d8f68a53
2022-09-02 08:46:35,782 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)                                                                          
2022-09-02 08:46:35,785 DEBUG: Removing '/home/egide/Documents/tenAcademy/week 2/abtest-mlops/data/.YUSVAheUCYibofvceYZHeA.tmp'                                                            
2022-09-02 08:46:35,785 DEBUG: Removing '/home/egide/Documents/tenAcademy/week 2/abtest-mlops/data/.YUSVAheUCYibofvceYZHeA.tmp'                                                            
2022-09-02 08:46:35,787 DEBUG: Removing '/home/egide/Documents/tenAcademy/week 2/abtest-mlops/.dvc/cache/.6mdxqt3XjyuXyUysEeRvcV.tmp'                                                      
2022-09-02 08:46:35,793 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)                                                                          
2022-09-02 08:46:35,793 DEBUG: Removing '/home/egide/Documents/tenAcademy/week 2/abtest-mlops/data/.6FCG4KRBjHnZLSjbLVpWY4.tmp'                                                            
2022-09-02 08:46:35,797 DEBUG: Removing '/home/egide/Documents/tenAcademy/week 2/abtest-mlops/data/.6FCG4KRBjHnZLSjbLVpWY4.tmp'                                                            
2022-09-02 08:46:35,797 DEBUG: Removing '/home/egide/Documents/tenAcademy/week 2/abtest-mlops/.dvc/cache/.4UuobkKFf9rAFspQ77f2r8.tmp'                                                      
2022-09-02 08:46:35,801 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)                                                                          
2022-09-02 08:46:35,804 DEBUG: Removing '/home/egide/Documents/tenAcademy/week 2/abtest-mlops/data/.Uq5x3jxBX4UxZa5gyHkhwf.tmp'                                                            
2022-09-02 08:46:35,805 DEBUG: Removing '/home/egide/Documents/tenAcademy/week 2/abtest-mlops/data/.Uq5x3jxBX4UxZa5gyHkhwf.tmp'                                                            
2022-09-02 08:46:35,806 DEBUG: Removing '/home/egide/Documents/tenAcademy/week 2/abtest-mlops/.dvc/cache/.jQzh9pqBgVGYzi348niMHJ.tmp'                                                      
3 files failed                                                                                                                                                                             
2022-09-02 08:46:35,807 ERROR: failed to pull data from the cloud - Checkout failed for following targets:
/home/egide/Documents/tenAcademy/week 2/abtest-mlops/data/control_group_data.csv
/home/egide/Documents/tenAcademy/week 2/abtest-mlops/data/exposed_clean_data.csv
/home/egide/Documents/tenAcademy/week 2/abtest-mlops/data/AdSmartABdata.csv
Is your cache up to date?
<https://error.dvc.org/missing-files>
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/egide/.local/lib/python3.8/site-packages/dvc/commands/data_sync.py", line 31, in run
    stats = self.repo.pull(
  File "/home/egide/.local/lib/python3.8/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/egide/.local/lib/python3.8/site-packages/dvc/repo/pull.py", line 46, in pull
    stats = self.checkout(
  File "/home/egide/.local/lib/python3.8/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/egide/.local/lib/python3.8/site-packages/dvc/repo/checkout.py", line 110, in checkout
    raise CheckoutError(stats["failed"], stats)
dvc.exceptions.CheckoutError: Checkout failed for following targets:
/home/egide/Documents/tenAcademy/week 2/abtest-mlops/data/control_group_data.csv
/home/egide/Documents/tenAcademy/week 2/abtest-mlops/data/exposed_clean_data.csv
/home/egide/Documents/tenAcademy/week 2/abtest-mlops/data/AdSmartABdata.csv
Is your cache up to date?
<https://error.dvc.org/missing-files>
------------------------------------------------------------
2022-09-02 08:46:35,816 DEBUG: Analytics is enabled.
2022-09-02 08:46:35,876 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmp74xtj5h3']'
2022-09-02 08:46:35,881 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmp74xtj5h3']'

**Comment by rlamy** [comment]
And `dvc config -l --show-origin`?

**Comment by Kamuzinzi** [comment]
> dvc config -l --show-origin

```
egide@egide-VirtualBox:~/Documents/tenAcademy/week 2/version2/abtest-mlops$ dvc config -l --show-origin
.dvc/config     remote.storage.url=gdrive://1zV2M1g6rzVVuSXMgf3tPaJPEBQUymyKq
.dvc/config     core.remote=storage
```

**Comment by rlamy** [comment]
And `dvc data status`? (sorry, I should have asked for all of that in one go)

**Comment by Kamuzinzi** [comment]
> dvc data status

```
Not in cache:
  (use "dvc fetch <file>..." to download files)
        data/control_group_data.csv
        data/AdSmartABdata.csv
        data/exposed_clean_data.csv

DVC uncommitted changes:
  (use "dvc commit <file>..." to track changes)
  (use "dvc checkout <file>..." to discard changes)
        deleted: data/control_group_data.csv
        deleted: data/AdSmartABdata.csv
        deleted: data/exposed_clean_data.csv
```

**Comment by rlamy** [comment]
Ah, I see. You have some orphan `*.dvc` files that aren't in cache. Removing these files (`data/control_group_data.csv.dvc`, `data/AdSmartABdata.csv.dvc` and `data/exposed_clean_data.csv.dvc`) should allow you to use your remote again.

This situation isn't meant to happen though. Do you remember what you did with those files? Did you maybe use `dvc add --no-commit`?

**Comment by Kamuzinzi** [comment]
I did `dvc add data/*.csv` to be able to create .dvc files.
After this I removed the *.csv files. pulling from my local machine is working but failing on other machines.

**Comment by rlamy** [comment]
Ah, OK, I thought this was all happening on the same machine.

The .dvc files tell dvc what to push and pull. If I understand correctly, you never `dvc push`ed the actual files, so the remote doesn't have them. In that case, you can fix it with `dvc checkout` then `dvc pull` on your local machine, but check what's going on with `dvc data status` before and after each command.

**Comment by Alberto1404** [comment]
@rlamy I am experimenting the same issue. However, the way to handle it porposed by @Kamuzinzi is not valid for me. I use dvc for data versioning of a deep learning model. The remote storage is a bucket from S3. I upload them from my computer (source device), and download them in another device (target device). DVC has been successfully working so far for me, and honestly I have no idea why this is happening. 

`dvc doctor` (**source device**): 
```sh
DVC version: 2.8.1 (pip)
---------------------------------
Platform: Python 3.9.16 on Linux-5.15.0-83-generic-x86_64-with-glibc2.31
Supports:
        webhdfs (fsspec = 2021.10.0),
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2021.10.0, boto3 = 1.17.106)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p8
Repo: dvc, git
```
`dvc doctor` (**target device**):
```sh
DVC version: 2.8.1 (pip)
---------------------------------
Platform: Python 3.6.9 on Linux-4.9.253-tegra-aarch64-with-Ubuntu-18.04-bionic
Supports:
        webhdfs (fsspec = 2021.10.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.5.1),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.5.1),
        s3 (s3fs = 2021.10.0, boto3 = 1.17.106)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p1
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p1
Repo: dvc, git
``` 

`dvc pull -vv` (**target device**): 
```sh
watchbot@wbnx15:~/Repo/models$ dvc pull -vv
2023-09-15 11:33:56,187 TRACE: Namespace(all_branches=False, all_commits=False, all_tags=False, cd='.', cmd='pull', cprofile=False, cprofile_dump=None, force=False, func=<class 'dvc.command.data_sync.CmdDataPull'>, glob=False, instrument=False, instrument_open=False, jobs=None, pdb=False, quiet=0, recursive=False, remote=None, run_cache=False, targets=[], verbose=2, version=None, with_deps=False, yappi=False)
2023-09-15 11:33:58,647 DEBUG: Preparing to transfer data from 's3://sr-dvc-data/dvcstore' to '.dvc/cache'
2023-09-15 11:33:58,649 DEBUG: Preparing to collect status from '.dvc/cache'
2023-09-15 11:33:58,652 DEBUG: Collecting status from '.dvc/cache'
2023-09-15 11:33:58,671 TRACE: Assuming '/home/watchbot/Repo/models/.dvc/cache/19/f19a50b1345d162a4408002b076c3f' is unchanged since it is read-only                                                                                                                              
2023-09-15 11:33:58,676 TRACE: Assuming '/home/watchbot/Repo/models/.dvc/cache/3f/70f2ebb82e34096df5d8f41e55cef1' is unchanged since it is read-only                                                                                                                              
2023-09-15 11:33:58,678 DEBUG: Preparing to collect status from 's3://sr-dvc-data/dvcstore'                                                                                                                                                                                       
2023-09-15 11:33:58,681 DEBUG: Collecting status from 's3://sr-dvc-data/dvcstore'
2023-09-15 11:33:59,820 DEBUG: Estimated remote size: 4096 files                                                                                                                                                                                                                  
2023-09-15 11:33:59,823 DEBUG: Querying '5' hashes via traverse                                                                                                                                                                                                                   
2023-09-15 11:33:59,952 WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:                                                                                                                                                         
name: yolov5.wts, md5: f4449630004c484a182c8dd28e28f262
name: yolov5.cfg, md5: 5d980890b65d09608728a1f647d784dc
name: model_b4_dla0_fp16.engine, md5: a078e0051a5c7bcc953373d566ba353b
2023-09-15 11:33:59,985 TRACE: Path 'libnvdsinfer_custom_impl_Yolo.so' inode '14943126'                                                                                                                                                                                           
2023-09-15 11:34:00,005 TRACE: Assuming '/home/watchbot/Repo/models/.dvc/cache/3f/70f2ebb82e34096df5d8f41e55cef1' is unchanged since it is read-only                                                                                                                              
2023-09-15 11:34:00,009 TRACE: Assuming '/home/watchbot/Repo/models/.dvc/cache/3f/70f2ebb82e34096df5d8f41e55cef1' is unchanged since it is read-only                                                                                                                              
2023-09-15 11:34:00,012 TRACE: Assuming '/home/watchbot/Repo/models/.dvc/cache/3f/70f2ebb82e34096df5d8f41e55cef1' is unchanged since it is read-only                                                                                                                              
2023-09-15 11:34:00,015 TRACE: Data 'libnvdsinfer_custom_impl_Yolo.so' didn't change.                                                                                                                                                                                             
2023-09-15 11:34:00,023 DEBUG: Cache type 'reflink' is not supported: reflink is not supported                                                                                                                                                                                    
2023-09-15 11:34:00,026 DEBUG: Removing '.MwSajowLr2tyQakGbYEFTg.tmp'                                                                                                                                                                                                             
2023-09-15 11:34:00,036 DEBUG: Removing '.ew6hVVbMsuArzeWuARRPeR.tmp'                                                                                                                                                                                                             
2023-09-15 11:34:00,043 TRACE: Path 'libnvdsinfer_custom_impl_Yolo_original.so' inode '14943116'                                                                                                                                                                                  
2023-09-15 11:34:00,047 TRACE: Assuming '/home/watchbot/Repo/models/.dvc/cache/19/f19a50b1345d162a4408002b076c3f' is unchanged since it is read-only                                                                                                                              
2023-09-15 11:34:00,064 DEBUG: Removing '.FcCTzQQ8TT25p73uSMJf4p.tmp'                                                                                                                                                                                                             
3 files failed                                                                                                                                                                                                                                                                    
2023-09-15 11:34:00,077 ERROR: failed to pull data from the cloud - Checkout failed for following targets:
model_b4_dla0_fp16.engine
yolov5.cfg
yolov5.wts
Is your cache up to date?
<https://error.dvc.org/missing-files>
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/watchbot/.local/lib/python3.6/site-packages/dvc/command/data_sync.py", line 41, in run
    glob=self.args.glob,
  File "/home/watchbot/.local/lib/python3.6/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/watchbot/.local/lib/python3.6/site-packages/dvc/repo/pull.py", line 44, in pull
    recursive=recursive,
  File "/home/watchbot/.local/lib/python3.6/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/watchbot/.local/lib/python3.6/site-packages/dvc/repo/checkout.py", line 110, in checkout
    raise CheckoutError(stats["failed"], stats)
dvc.exceptions.CheckoutError: Checkout failed for following targets:
model_b4_dla0_fp16.engine
yolov5.cfg
yolov5.wts
Is your cache up to date?
<https://error.dvc.org/missing-files>
------------------------------------------------------------
2023-09-15 11:34:00,105 DEBUG: Analytics is enabled.
2023-09-15 11:34:00,390 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmph6d810gc']'
2023-09-15 11:34:00,395 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmph6d810gc']'
```
