### ISSUE TITLE
pull: unable to pull from cloud-versioned remote

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8316]
Copy of my terminal from a fresh repo:

```bash
$ dvc remote add -d cloud s3://dave-sandbox-versioning/remote
Setting 'cloud' as a default remote.
$ dvc remote modify cloud version_aware true
$ dvc remote modify cloud worktree true
$ echo foo > foo.txt
$ dvc add foo.txt
100% Adding...|█████████████████████████████████████████████████|1/1 [00:00, 44.17file/s]

To track the changes with git, run:

        git add foo.txt.dvc .gitignore

To enable auto staging, run:

        dvc config core.autostage true
$ dvc push
1 file pushed
$ cat foo.txt.dvc
outs:
- md5: d3b07384d113edec49eaa6238ad5ff00
  size: 4
  path: foo.txt
  version_id: SSME9jvAVWPYoDUT3q8gf6XZrydT8w_I
  etag: d3b07384d113edec49eaa6238ad5ff00
$ aws s3api list-object-versions --bucket dave-sandbox-versioning --prefix remote/foo.txt

{
    "Versions": [
        {
            "ETag": "\"d3b07384d113edec49eaa6238ad5ff00\"",
            "Size": 4,
            "StorageClass": "STANDARD",
            "Key": "remote/foo.txt",
            "VersionId": "SSME9jvAVWPYoDUT3q8gf6XZrydT8w_I",
            "IsLatest": true,
            "LastModified": "2022-09-16T19:04:18.000Z",
            "Owner": {
                "DisplayName": "owner+aws-iterative-sandbox",
                "ID": "ae73bd383e70f5233868f83638fdca9cd1a96bd36d92fdc8e939352899e4e79c"
            }
        }
    ]
}
$ rm foo.txt
$ rm -rf .dvc/cache
$ dvc pull -v
2022-09-16 15:10:34,154 DEBUG: Removing '/Users/dave/repo/.dvc/cache/d3/.FmHz48jPHsnmizW8Mu7FZK.tmp'
2022-09-16 15:10:34,157 ERROR: unexpected error - The specified key does not exist.: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/s3fs/core.py", line 110, in _error_wrapper
    return await func(*args, **kwargs)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/aiobotocore/client.py", line 358, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dave/Code/dvc/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/Users/dave/Code/dvc/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/Users/dave/Code/dvc/dvc/commands/data_sync.py", line 31, in run
    stats = self.repo.pull(
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/pull.py", line 34, in pull
    processed_files_count = self.fetch(
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/fetch.py", line 80, in fetch
    return _fetch_worktree(self, _remote)
  File "/Users/dave/Code/dvc/dvc/repo/fetch.py", line 27, in _fetch_worktree
    save(index)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_data/index.py", line 264, in save
    entry.cache.add(
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_data/hashfile/db/__init__.py", line 105, in add
    super().add(path, fs, oid, hardlink=hardlink, callback=callback)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_objects/db.py", line 122, in add
    generic.transfer(
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_objects/fs/generic.py", line 101, in transfer
    _try_links(
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_objects/fs/generic.py", line 64, in _try_links
    return copy(from_fs, from_path, to_fs, to_path, callback=callback)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_objects/fs/generic.py", line 44, in copy
    return from_fs.get_file(from_path, tmp_file, callback=callback)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 387, in get_file
    self.fs.get_file(from_info, to_info, callback=callback, **kwargs)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/fsspec/asyn.py", line 111, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/fsspec/asyn.py", line 96, in sync
    raise return_result
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/s3fs/core.py", line 1076, in _get_file
    body, content_length = await _open_file(range=0)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/s3fs/core.py", line 1067, in _open_file
    resp = await self._call_s3(
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/s3fs/core.py", line 332, in _call_s3
    return await _error_wrapper(
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/s3fs/core.py", line 137, in _error_wrapper
    raise err
FileNotFoundError: The specified key does not exist.
------------------------------------------------------------
2022-09-16 15:10:34,700 DEBUG: Removing '/Users/dave/.HcVfJ6gEhSsYnp57Kk2CnM.tmp'
2022-09-16 15:10:34,700 DEBUG: Removing '/Users/dave/.HcVfJ6gEhSsYnp57Kk2CnM.tmp'
2022-09-16 15:10:34,701 DEBUG: Removing '/Users/dave/.HcVfJ6gEhSsYnp57Kk2CnM.tmp'
2022-09-16 15:10:34,703 DEBUG: Removing '/Users/dave/repo/.dvc/cache/.grAKGKyCuePXLfUunGaEt6.tmp'
2022-09-16 15:10:34,709 DEBUG: Version info for developers:
DVC version: 2.26.3.dev4+g391bb29be
---------------------------------
Platform: Python 3.10.2 on macOS-12.5.1-arm64-arm-64bit
Subprojects:
        dvc_data = 0.8.0
        dvc_objects = 0.2.2
        dvc_render = 0.0.10
        dvc_task = 0.1.2
        dvclive = 0.10.0
        scmrepo = 0.1.1
Supports:
        azure (adlfs = 2022.7.0, knack = 0.9.0, azure-identity = 1.7.1),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = 2022.8.2),
        hdfs (fsspec = 2022.8.2, pyarrow = 7.0.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2022.8.2, boto3 = 1.24.59),
        ssh (sshfs = 2022.3.1),
        webdav (webdav4 = 0.9.4),
        webdavs (webdav4 = 0.9.4),
        webhdfs (fsspec = 2022.8.2)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: local, s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-09-16 15:10:34,718 DEBUG: Analytics is disabled.
```

**Comment by efiop** [comment]
Looks like in s3fs specifically version_id is not getting correctly extracted from the key. Taking a closer look...

**Comment by efiop** [comment]
@pmrowla Works great! Thank you! 🙏
