### ISSUE TITLE
pull: fails if pulling to a symlink from outside of the symlink

### ISSUE THREAD

**Issue by Icemole** [iterative/dvc#8345]
# Bug Report

## Description

When running `dvc pull path/to/symlink/*.dvc` from inside of a `dvc` repository, I get this error:
```
ERROR: unexpected error                                                                                                                

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

I can do `cd path/to/symlink; dvc pull *.dvc` and it will work without any issues. Moreover, I can also do `dvc pull` from outside of the directory that the symlink points to, for instance `dvc pull physical/path/where/symlink/points/*.dvc`. It's just the specific pulling from outside of a symlink that creates an error.

### Reproduce

1. `dvc init`
2. `mkdir data`
3. `echo data >> data/file`
4. `dvc add data/file`
5. `dvc push`
6. `ln -s data data_symlink`
7. `dvc pull data_symlink/file.dvc`

(taken from the [corresponding discord message](https://discord.com/channels/485586884165107732/485596304961962003/1022533436927381504))

### Expected

Data should be pulled from remote to the `data_symlink/` directory (and therefore to the `data/` directory).

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.27.2 (pip)
---------------------------------
Platform: Python 3.8.10 on [...]
Subprojects:
        dvc_data = 0.10.0
        dvc_objects = 0.4.0
        dvc_render = 0.0.11
        dvc_task = 0.1.2
        dvclive = 0.10.0
        scmrepo = 0.1.1
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2022.8.2, boto3 = 1.24.59)
Cache types: hardlink, symlink
Cache directory: nfs4 on [...]
Caches: local
Remotes: s3
Workspace directory: nfs4 on [...]
Repo: dvc, git
```

**Additional Information (if any):**

This issue doesn't happen with version 2.8.1.

This could be related to #2530 and #6149, and maybe other issues that I didn't find.

Output of `dvc pull -v ...`:
```
2022-09-22 13:51:58,363 DEBUG: Preparing to transfer data from '[...]' to '/home/default/evaluations/versions/.dvc/cache'
2022-09-22 13:51:58,363 DEBUG: Preparing to collect status from '/home/default/evaluations/versions/.dvc/cache'
2022-09-22 13:51:58,363 DEBUG: Collecting status from '/home/default/evaluations/versions/.dvc/cache'
2022-09-22 13:51:58,363 DEBUG: Collecting status from '/home/default/evaluations/versions/.dvc/cache'
2022-09-22 13:52:06,119 ERROR: unexpected error                                                                                                                              
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/default/venv_dvc/lib/python3.8/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
...
  File "/home/default/venv_dvc/lib/python3.8/site-packages/dvc/repo/graph.py", line 32, in get_pipeline
    assert len(found) == 1
AssertionError
------------------------------------------------------------
2022-09-22 13:52:09,514 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2022-09-22 13:52:09,515 DEBUG: Removing '/home/default/evaluations/.LTh7BNYaseVtmmwQBdYSKu.tmp'
2022-09-22 13:52:09,521 DEBUG: Removing '/home/default/evaluations/.LTh7BNYaseVtmmwQBdYSKu.tmp'
2022-09-22 13:52:09,529 DEBUG: Removing '/home/default/evaluations/.LTh7BNYaseVtmmwQBdYSKu.tmp'
2022-09-22 13:52:09,534 DEBUG: Removing '/home/default/evaluations/versions/.dvc/cache/.bdYA2e6GJ3A5gvTvDvQdie.tmp'
2022-09-22 13:52:09,641 DEBUG: Version info for developers:
DVC version: 2.27.2 (pip)
---------------------------------
[Output of dvc doctor as specified above]

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-09-22 13:52:09,644 DEBUG: Analytics is disabled.
```

**Comment by pared** [comment]
Repro script:
```bash
#!/bin/bash

set -exu
pushd $TMPDIR

wsp=test_wspace
rep=test_repo

rm -rf $wsp && mkdir $wsp && pushd $wsp
main=$(pwd)

mkdir $rep && pushd $rep

mkdir data
git init
dvc init

echo data >> data/file
dvc add data/file
dvc remote add -d str $main/storage

dvc push

git add -A
git commit -am "init"

rm -rf data/file .dvc/cache

ln -s data data_link
dvc pull -v data_link/file.dvc
```

This use case used to work. Seems like 
https://github.com/iterative/dvc/commit/26008f155901aa590b1a809452f951b2c5d7c6c3
Introduced the regression
