### ISSUE TITLE
cli: cannot import name 'isfilelike' from 'fsspec.utils'  (2.30.0)

### ISSUE THREAD

**Issue by clintlombard** [iterative/dvc#8439]
# Bug Report

Note that this is not reproducible in a minimal environment, but might server useful if anyone else find the same problem

## Description

When running any CLI command I get the following error:

```shell
$ dvc version
...
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.9.9/bin/dvc", line 8, in <module>
    sys.exit(main())
  File "/opt/pyenv/versions/3.9.9/lib/python3.9/site-packages/dvc/cli/__init__.py", line 216, in main
    if analytics.is_enabled():
  File "/opt/pyenv/versions/3.9.9/lib/python3.9/site-packages/dvc/analytics.py", line 50, in is_enabled
    Config(validate=False).get("core", {}).get("analytics", "true")
  File "/opt/pyenv/versions/3.9.9/lib/python3.9/site-packages/dvc/config.py", line 99, in __init__
    self.dvc_dir = Repo.find_dvc_dir()
  File "/opt/pyenv/versions/3.9.9/lib/python3.9/site-packages/dvc/repo/__init__.py", line 361, in find_dvc_dir
    root_dir = cls.find_root(root)
  File "/opt/pyenv/versions/3.9.9/lib/python3.9/site-packages/dvc/repo/__init__.py", line 338, in find_root
    if not fs.isdir(root_dir):
  File "/opt/pyenv/versions/3.9.9/lib/python3.9/site-packages/dvc_objects/fs/base.py", line 160, in isdir
    return self.fs.isdir(path)
  File "/opt/pyenv/versions/3.9.9/lib/python3.9/site-packages/funcy/objects.py", line 50, in __get__
    return prop.__get__(instance, type)
  File "/opt/pyenv/versions/3.9.9/lib/python3.9/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/opt/pyenv/versions/3.9.9/lib/python3.9/site-packages/dvc_objects/fs/local.py", line 194, in fs
    return FsspecLocalFileSystem(**self.config)
  File "/opt/pyenv/versions/3.9.9/lib/python3.9/site-packages/fsspec/spec.py", line 68, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/opt/pyenv/versions/3.9.9/lib/python3.9/site-packages/dvc_objects/fs/local.py", line 21, in __init__
    from ._local import LocalFileSystem as _LocalFileSystem
  File "/opt/pyenv/versions/3.9.9/lib/python3.9/site-packages/dvc_objects/fs/_local.py", line 18, in <module>
    from fsspec.utils import isfilelike, stringify_path
ImportError: cannot import name 'isfilelike' from 'fsspec.utils' (/opt/pyenv/versions/3.9.9/lib/python3.9/site-packages/fsspec/utils.py)
```

However, this works when installing `dvc==2.29.0`.

### Reproduce

Not reproducible when using the `python:3.9.9` docker image and installing `dvc==2.30.0`. However, in the docker image I'm using, this happens (I know not very useful).

### Expected

CLI should work as normal.

### Environment information

* Arch: aarch64
* OS: Ubuntu 18.04
* `dvc==2.30.0`
* Running DVC inside a docker container
* Python 3.9.9

**Output of `dvc doctor`:** (also broken)

**Comment by clintlombard** [comment]
[Disabling analytics](https://dvc.org/doc/user-guide/analytics) seems to fix this.

**Comment by efiop** [comment]
@clintlombard Could you run `pip check`? Seems like you didn't upgrade all dvc dependencies or something else installed old fsspec version.

**Comment by skshetry** [comment]
@efiop, we support [`fsspec>2021.10.1` in `dvc-objects`](https://github.com/iterative/dvc-objects/blob/695b7db726c48fcdfa2d448ac6db671ff1ec44fb/setup.cfg#L30), but `isfilelike` is only available since `2022.5.0`.

**Comment by efiop** [comment]
@skshetry Good point. I thought we have a higher requirement in dvc-http, but we don't. So need to update it in dvc-objects then.

**Comment by clintlombard** [comment]
@efiop the pip check came back clean. However, on @skshetry' point I have `fsspec==2022.2.0`.

**Comment by clintlombard** [comment]
Updating `fsspec` fixes this issue.
