### ISSUE TITLE
dvc.api.open / dvc.api.get_url fail in long-running tmux session

### ISSUE THREAD

**Issue by junwang-wish** [iterative/dvc#8465]
## Description

In short-running tmux session, `dvc.api.open` and `dvc.api.get_url` work properly, but in long-running tmux session where I repeated use `dvc.api.open` and `dvc.api.get_url` to query multiple files, it begins to fail like below:

```shell
root@dad9a7c7086a:/workspaces/query_understanding_model/notebooks/dvc# python
Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dvc.api
>>> resource_url = dvc.api.get_url( 'data/amazon/All_Amazon_Meta_Train.json', repo='git@github.com:junwang-wish/query_understanding_data.git' )
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 200, in clone
    repo = clone_from()
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/dulwich/porcelain.py", line 538, in clone
    return client.clone(
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/dulwich/client.py", line 760, in clone
    result = self.fetch(path, target, progress=progress, depth=depth)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/dulwich/client.py", line 837, in fetch
    result = self.fetch_pack(
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/dulwich/client.py", line 1146, in fetch_pack
    proto, can_read, stderr = self._connect(b"upload-pack", path)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/dulwich/client.py", line 1792, in _connect
    con = self.ssh_vendor.run_command(
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/fsspec/asyn.py", line 111, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/fsspec/asyn.py", line 96, in sync
    raise return_result
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scmrepo/git/backend/dulwich/asyncssh_vendor.py", line 163, in _run_command
    conn = await asyncssh.connect(
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/connection.py", line 7834, in connect
    return await asyncio.wait_for(
  File "/opt/conda/envs/py38/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/connection.py", line 457, in _connect
    await conn.wait_closed()
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/connection.py", line 2588, in wait_closed
    await self._agent.wait_closed()
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/agent.py", line 601, in wait_closed
    await maybe_wait_closed(self._writer)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/misc.py", line 329, in maybe_wait_closed
    await writer.wait_closed()
  File "/opt/conda/envs/py38/lib/python3.8/asyncio/streams.py", line 359, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/connection.py", line 447, in _connect
    await options.waiter
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/connection.py", line 1046, in _reap_task
    task.result()
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/auth.py", line 322, in _start
    self._keypair = await self._conn.public_key_auth_requested()
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/connection.py", line 3349, in public_key_auth_requested
    agent_keys = await self._agent.get_keys(self._agent_identities)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/agent.py", line 275, in get_keys
    await self._make_request(SSH_AGENTC_REQUEST_IDENTITIES)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/agent.py", line 256, in _make_request
    await self._cleanup()
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/agent.py", line 206, in _cleanup
    await self.wait_closed()
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/agent.py", line 601, in wait_closed
   await maybe_wait_closed(self._writer)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/misc.py", line 329, in maybe_wait_closed
    await writer.wait_closed()
  File "/opt/conda/envs/py38/lib/python3.8/asyncio/streams.py", line 359, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/asyncssh/agent.py", line 249, in _make_request
    resplen = int.from_bytes((await reader.readexactly(4)), 'big')
  File "/opt/conda/envs/py38/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/opt/conda/envs/py38/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/opt/conda/envs/py38/lib/python3.8/asyncio/selector_events.py", line 848, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/dvc/scm.py", line 145, in clone
    git = Git.clone(url, to_path, progress=pbar.update_git, **kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scmrepo/git/__init__.py", line 143, in clone
    backend.clone(url, to_path, **kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 203, in clone
    raise CloneError(url, to_path) from exc
scmrepo.exceptions.CloneError: Failed to clone repo 'git@github.com:junwang-wish/query_understanding_data.git' to '/tmp/tmpeaxfqgwedvc-clone'

During handling of the above exception, another exception occurred:
ceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/dvc/api/data.py", line 21, in get_url
    with Repo.open(repo, rev=rev, subrepos=True, uninitialized=True) as _repo:
  File "/opt/conda/envs/py38/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/dvc/external_repo.py", line 39, in external_repo
    path = _cached_clone(url, rev, for_write=for_write)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/dvc/external_repo.py", line 169, in _cached_clone
    clone_path, shallow = _clone_default_branch(url, rev, for_write=for_write)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/funcy/flow.py", line 274, in wrap_with
    return call()
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/dvc/external_repo.py", line 239, in _clone_default_branch
    git = clone(url, clone_path)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/dvc/scm.py", line 150, in clone
    raise CloneError(str(exc))
dvc.scm.CloneError: Failed to clone repo 'git@github.com:junwang-wish/query_understanding_data.git' to '/tmp/tmpeaxfqgwedvc-clone'

```
Note that I can git clone `git@github.com:junwang-wish/query_understanding_data.git` in the same tmux session without problem, and the same problem happens even if I `rm -rf /tmp/tmpeaxfqgwedvc-clone`

**Comment by rlamy** [comment]
Thanks for the report! It would be helpful if you could create a minimal reproducer that reliably triggers the issue (even if takes a while).

**Comment by efiop** [comment]
closing as stale
