### ISSUE TITLE
exp: Too many openfiles error in `exp` related commands. 

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#8476]
# Bug Report

Sometimes on MacOS, we will meet the "too many open files error". This can happen in `exp run`, `exp show` or inside celery work.  
And the time it happening is also varied, setup, running, or result collection, I met this error in all stages. `ulimit` to a larger number ( for example 1024 instead of default 256 ) can prevent this.

```
Traceback (most recent call last):
  File "/Users/gao/Code/dvc/dvc/repo/experiments/queue/tasks.py", line 66, in collect_exp
    BaseStashQueue.collect_executor(
  File "/Users/gao/Code/dvc/dvc/repo/experiments/queue/base.py", line 643, in collect_executor
    results = cls.collect_git(exp, executor, exec_result)
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/funcy/flow.py", line 127, in retry
    return call()
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/gao/Code/dvc/dvc/repo/experiments/utils.py", line 40, in wrapper
    return f(exp, *args, **kwargs)
  File "/Users/gao/Code/dvc/dvc/repo/experiments/queue/base.py", line 623, in collect_git
    for ref in executor.fetch_exps(
  File "/Users/gao/Code/dvc/dvc/repo/experiments/executor/base.py", line 367, in fetch_exps
    dest_scm.fetch_refspecs(
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 289, in _backend_func
    result = func(*args, **kwargs)
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 634, in fetch_refspecs
    fetch_result = client.fetch(
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/client.py", line 1502, in fetch
    refs = r.fetch(
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/repo.py", line 427, in fetch
    count, pack_data = self.fetch_pack_data(
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/repo.py", line 460, in fetch_pack_data
    objects = self.fetch_objects(
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/repo.py", line 494, in fetch_objects
    obj = self.object_store[sha]
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/object_store.py", line 144, in __getitem__
    type_num, uncomp = self.get_raw(sha)
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/object_store.py", line 581, in get_raw
    ret = self._get_loose_object(hexsha)
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/object_store.py", line 745, in _get_loose_object
    return ShaFile.from_path(path)
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/objects.py", line 420, in from_path
    with GitFile(path, "rb") as f:
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/file.py", line 94, in GitFile
    return io.open(filename, mode, bufsize)
OSError: [Errno 24] Too many open files: '/Users/gao/test/vscode-dvc/demo/.dvc/tmp/exps/tmp9x5praul/.git/objects/55/4aa474348369ca4eec2945226686b9e4f11666'
[2022-10-25 16:25:09,522: ERROR/MainProcess] Task dvc.repo.experiments.queue.tasks.run_exp[cf2fd3f4-a0c2-4c42-80b9-9554e03d9a55] raised unexpected: OSError(24, 'Too many open files')
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 628, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
OSError: [Errno 24] Too many open files: '/Users/gao/test/vscode-dvc/demo/.dvc/tmp/exps/tmp9x5praul/demo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/gao/Code/dvc/dvc/repo/experiments/queue/tasks.py", line 111, in run_exp
    cleanup_exp.s(executor, infofile)()
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/celery/canvas.py", line 168, in __call__
    return self.type(*args, **kwargs)
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 735, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/celery/app/task.py", line 392, in __call__
    return self.run(*args, **kwargs)
  File "/Users/gao/Code/dvc/dvc/repo/experiments/queue/tasks.py", line 87, in cleanup_exp
    executor.cleanup(infofile)
  File "/Users/gao/Code/dvc/dvc/repo/experiments/executor/local.py", line 128, in cleanup
    remove(self.root_dir)
  File "/Users/gao/Code/dvc/dvc/utils/fs.py", line 69, in remove
    shutil.rmtree(path, onerror=_chmod)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 724, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 657, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 632, in _rmtree_safe_fd
    onerror(os.scandir, path, sys.exc_info())
  File "/Users/gao/Code/dvc/dvc/utils/fs.py", line 54, in _chmod
    func(p)
OSError: [Errno 24] Too many open files: '/Users/gao/test/vscode-dvc/demo/.dvc/tmp/exps/tmp9x5praul/demo'
```

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

**Additional Information (if any):**

**Comment by karajan1001** [comment]
Another case 
```
[2022-10-26 18:25:39,068: ERROR/MainProcess] Failed to collect experiment
Traceback (most recent call last):
  File "/Users/gao/Code/dvc/dvc/repo/experiments/queue/tasks.py", line 66, in collect_exp
    BaseStashQueue.collect_executor(
  File "/Users/gao/Code/dvc/dvc/repo/experiments/queue/base.py", line 641, in collect_executor
    results = cls.collect_git(exp, executor, exec_result)
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/funcy/flow.py", line 127, in retry
    return call()
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/gao/Code/dvc/dvc/repo/experiments/utils.py", line 40, in wrapper
    return f(exp, *args, **kwargs)
  File "/Users/gao/Code/dvc/dvc/repo/experiments/queue/base.py", line 621, in collect_git
    for ref in executor.fetch_exps(
  File "/Users/gao/Code/dvc/dvc/repo/experiments/executor/base.py", line 367, in fetch_exps
    dest_scm.fetch_refspecs(
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 289, in _backend_func
    result = func(*args, **kwargs)
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 634, in fetch_refspecs
    fetch_result = client.fetch(
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/client.py", line 1502, in fetch
    refs = r.fetch(
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/repo.py", line 427, in fetch
    count, pack_data = self.fetch_pack_data(
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/repo.py", line 460, in fetch_pack_data
    objects = self.fetch_objects(
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/repo.py", line 527, in fetch_objects
    haves = self.object_store.find_common_revisions(graph_walker)
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/object_store.py", line 292, in find_common_revisions
    if sha in self:
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/object_store.py", line 440, in __contains__
    if self.contains_packed(sha) or self.contains_loose(sha):
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/object_store.py", line 427, in contains_packed
    for pack in self.packs:
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/object_store.py", line 474, in packs
    return list(self._iter_cached_packs()) + list(self._update_pack_cache())
  File "/Users/gao/test/vscode-dvc/demo/.venv/lib/python3.10/site-packages/dulwich/object_store.py", line 702, in _update_pack_cache
    pack_dir_contents = os.listdir(self.pack_dir)
OSError: [Errno 24] Too many open files: '/Users/gao/test/vscode-dvc/demo/.dvc/tmp/exps/tmpysrdhlo6/.git/objects/pack'
```

And I found this file `'/Users/gao/test/vscode-dvc/demo/.dvc/tmp/exps/tmpysrdhlo6/.git/objects/pack'` is 148M large

**Comment by pmrowla** [comment]
Given a large enough git repo this is expected. This is probably something that needs to go into a troubleshooting docs entry, increasing `ulimit` is the correct solution.

**Comment by pmrowla** [comment]
We could consider manually packing the temporary repo when we generate it, which would resolve the issue of potentially needing to open >256 loose object files at a time, but is an expensive operation performance wise and would make our executor init slower.

**Comment by shcheklein** [comment]
Q: why do we need keep that many files simultaneously open?

**Comment by karajan1001** [comment]
> Q: why do we need keep that many files simultaneously open?

We didn't keep many of them, the problem comes from two part. 
The first is that on macOS this limitation is only 256, and if we run many other programs in the background, there is a high probability of going into this situation.
The second is that it looks like the `dulwich` would open dozens of files when it does some of the operations, which is the direct reason of this problem.

**Comment by shcheklein** [comment]
So, probably, the proper fix is to see what dulwich does, close files as soon as we are done with them?

> and if we run many other programs in the background, there is a high probability of going into this situation.

I guess `ulimit -n` is per process, right? If we hit the global one (64K?) it's a bug ...

To my mind OSes usually have reasonable limits and it almost always a sing of something weird happening. E.g. highly parallel operations with network (OS doesn't have to close descriptors, etc). I would investigate this first.

**Comment by karajan1001** [comment]
> I guess `ulimit -n` is per process, right? If we hit the global one (64K?) it's a bug ...

Yes, every time after opening a new terminal, we need to change the change the limit of file opening number.

**Comment by pmrowla** [comment]
It's because dulwich and libgit2 do not automatically garbage collect in git repositories, git objects are kept as loose objects (individual files) and not packed. CLI git does this in the background when it determines the repo should be packed, but this is also dependent on user configuration. So in the experiment temp workspaces the git repositories contain lots of loose git objects that are kept open and in memory whenever possible.

**Comment by pmrowla** [comment]
As I posted earlier, we could consider automatically packing the temp git workspaces ourselves, but this will come with a performance impact. Packing the objects up can take a significant amount of time, and then any git operations which need to read those objects out of a pack will also be slower than working with loose objects (individual files).

**Comment by shcheklein** [comment]
thanks ,Peter, one more question:

>  So in the experiment temp workspaces the git repositories contain lots of loose git objects that are kept open and in memory whenever possible.

why does it keep them open?

**Comment by pmrowla** [comment]
I haven't looked into it in detail, but based on the tracebacks it looks like this happens when dulwich is trying to pack objects for a fetch or push. It has to open all of the loose object files that are being pushed, also open any existing packs that contain objects which are also being pushed/fetched,  read object headers and determine what order the objects should go into the pack (sort them), and then read the rest of the object data + write it into the pack in the correct order.

I'm assuming dulwich just keeps everything open and in memory during this process for performance reasons. There may be some upstream changes we could send which would close and then reopen object or pack files only when needed, but I don't think keeping the files open is actually any different than what CLI git does.

The main difference between using CLI git all the time and dulwich is that CLI git does the automatic background `git gc` whenever it decides the repo has either too many loose objects or too many pack files, which then get garbage collected and repacked into fewer, larger pack files. Once the repo has been gc'd, it no longer matters that git (whether dulwich or CLI) keeps the files open, since there are fewer total files to be opened. The one thing to note here is that what CLI git considers to be "too many" objects or packs is somewhat arbitrary, and can vary a lot depending on system/user configuration

**Comment by pmrowla** [comment]
If we want to try and avoid the too many open files issue (without suggesting the `ulimit -n` increase), we can do the manual repack (i.e. manual `git gc`) ourselves when we generate the temp exp workspaces. But as noted, this may be a very slow operation depending on the size of the user's git repo (CLI git hides this slow operation by doing it in the background after you run regular commands like `git fetch/pull/clone`)

**Comment by pmrowla** [comment]
@karajan1001 I'm curious if anyone else on the vscode team has run into this same problem? Also, could you run `git count-objects -vH` in your clone of the vscode repo? (In your main clone of the repo, not in a temp exp workspace)

What I am wondering is that if you aren't making regular changes in the vscode repo, you also aren't using CLI git in that clone regularly, so it may not be gc'd at all, which could also lead to dulwich hitting the file limit when we try to collect exps. So there may be too many objects on the receiving end of the fetch (in the main repo) and not necessarily too many objects in the source end (in an exp temp workspace). A typical user would not hit this scenario, because they would presumably be using regular CLI git themselves in conjunction with DVC on a regular enough basis that git would perform a gc at some point.

**Comment by dberenbaum** [comment]
As one data point, I haven't hit this issue on my mac.

**Comment by pmrowla** [comment]
Yeah, so your repo hasn't been garbage collected. If you just manually run `git gc` in that repo it may resolve the too many files issue.

**Comment by pmrowla** [comment]
I think we can close this for now given that it is unlikely this will occur in normal DVC use (where users are at least semi-regularly also using CLI git commands)
