### ISSUE TITLE
failed to transfer  [WinError 1] 函数不正确。:

### ISSUE THREAD

**Issue by yannli** [iterative/dvc#8515]
# failed to dvc add on window platform

## Description

  when i use dvc on windows.  `dvc add` produce the error :`  ERROR: failed to transfer 'md5: XXX - [WinError 1] 函数不正确。`
  
### Environment information
  Win 10

**Output of `dvc doctor`:**
```
Supports:
        azure (adlfs = 2022.10.0, knack = 0.10.0, azure-identity = 1.11.0),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = 2022.10.0),
        hdfs (fsspec = 2022.10.0, pyarrow = 10.0.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2022.10.0, boto3 = 1.24.59),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2022.10.0)
Cache types:
Cache directory: FAT32 on E:\
Caches: local
Remotes: None
Workspace directory: FAT32 on E:\
Repo: dvc, git
```
This is required to ensure that we can reproduce the bug.

```console
$ dvc doctor
```

**Additional Information (if any):**

I dont kown whether is a bug or something else.

**Comment by pmrowla** [comment]
@yannli can you rerun your `dvc add` command with `-v` and post the output here?

```
dvc add -v ...
```

Also, please re-run `dvc doctor`, it looks like you cut the first few lines from the output out in your post (it should start with details of the DVC and python versions you are using, as well as some information about your platform

**Comment by sospiess** [comment]
Same issue. Happening both with the pip dvc package (2.35.1) in an virtual env as well as with the Windows installer (2.34.0). Here's the output from the Anaconda Prompt but pretty much the same when using the VS Code shell integration (Powershell).

```
(base) D:\git\parking-slots>dvc add .\data\carPark.mp4 -v
2022-11-24 21:22:18,627 DEBUG: Lockfile for 'dvc.yaml' not found
Adding...                                                                                                                    2022-11-24 21:22:18,789 DEBUG: Computed stage: 'data\carPark.mp4.dvc' md5: 'None'
2022-11-24 21:22:18,836 DEBUG: Preparing to transfer data from 'memory://dvc-staging/c47a7be99f70e3fc71c1c088fa5f105ede6f60d435a289e64ae6f3ebf450f4e0' to 'D:\git\parking-slots\.dvc\cache'
2022-11-24 21:22:18,836 DEBUG: Preparing to collect status from 'D:\git\parking-slots\.dvc\cache'
2022-11-24 21:22:18,836 DEBUG: Collecting status from 'D:\git\parking-slots\.dvc\cache'
                                                                                                                             2022-11-24 21:22:18,867 DEBUG: Preparing to collect status from 'memory://dvc-staging/c47a7be99f70e3fc71c1c088fa5f105ede6f60d435a289e64ae6f3ebf450f4e0'
                                                                                                                             2022-11-24 21:22:18,898 ERROR: failed to transfer 'md5: e64b26059e47aae7bac1c0f8e6047d7f' - [WinError 1] Unzulässige Funktion: 'D:\\git\\parking-slots\\data\\carPark.mp4' -> 'D:\\git\\parking-slots\\.dvc\\cache\\e6\\4b26059e47aae7bac1c0f8e6047d7f'
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc_data\hashfile\transfer.py", line 40, in wrapper
  File "dvc_data\hashfile\transfer.py", line 202, in func
  File "dvc_data\hashfile\db\__init__.py", line 105, in add
  File "dvc_objects\db.py", line 145, in add
  File "dvc_objects\fs\generic.py", line 132, in transfer
  File "dvc_objects\fs\generic.py", line 96, in _try_links
  File "dvc_objects\fs\generic.py", line 55, in _link
  File "dvc_objects\fs\base.py", line 321, in link
  File "dvc_objects\fs\local.py", line 163, in link
  File "dvc_objects\fs\system.py", line 32, in hardlink
OSError: [WinError 1] Unzulässige Funktion: 'D:\\git\\parking-slots\\data\\carPark.mp4' -> 'D:\\git\\parking-slots\\.dvc\\cache\\e6\\4b26059e47aae7bac1c0f8e6047d7f'
------------------------------------------------------------
                                                                                                                             2022-11-24 21:22:18,925 DEBUG: link type reflink is not available ([Errno 129] no more link types left to try out)
2022-11-24 21:22:18,925 DEBUG: Removing 'D:\git\parking-slots\data\.gbABMGLbS3XkiNm69jJJG6.tmp'
2022-11-24 21:22:18,972 DEBUG: Removing 'D:\git\parking-slots\data\.gbABMGLbS3XkiNm69jJJG6.tmp'
2022-11-24 21:22:18,988 DEBUG: Removing 'D:\git\parking-slots\.dvc\cache\.kEJDj5E8kaXER7N8pKdF8P.tmp'
file/directory 'D:\git\parking-slots\data\carPark.mp4' is going to be removed. Are you sure you want to proceed? [y/n] n
Adding...
2022-11-24 21:22:51,037 ERROR: unable to remove 'D:\git\parking-slots\data\carPark.mp4' without a confirmation. Use `-f` to force.
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc\output.py", line 668, in _checkout
  File "dvc_data\hashfile\checkout.py", line 274, in checkout
  File "dvc_data\hashfile\checkout.py", line 221, in _checkout
  File "dvc_data\hashfile\checkout.py", line 88, in _checkout_file
  File "dvc_data\hashfile\checkout.py", line 59, in _relink
  File "dvc_data\hashfile\checkout.py", line 53, in _remove
dvc_data.hashfile.checkout.PromptError: unable to remove 'D:\git\parking-slots\data\carPark.mp4' without a confirmation.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc\commands\add.py", line 53, in run
  File "dvc\utils\collections.py", line 164, in inner
  File "dvc\repo\__init__.py", line 48, in wrapper
  File "dvc\repo\scm_context.py", line 156, in run
  File "dvc\repo\add.py", line 192, in add
  File "funcy\decorators.py", line 45, in wrapper
  File "dvc\stage\decorators.py", line 43, in rwlocked
  File "funcy\decorators.py", line 66, in __call__
  File "dvc\stage\__init__.py", line 520, in commit
  File "dvc\output.py", line 705, in commit
  File "dvc\output.py", line 670, in _checkout
dvc.exceptions.ConfirmRemoveError: unable to remove 'D:\git\parking-slots\data\carPark.mp4' without a confirmation. Use `-f` to force.
------------------------------------------------------------
2022-11-24 21:22:51,074 DEBUG: Analytics is enabled.
2022-11-24 21:22:51,079 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\Sven\\AppData\\Local\\Temp\\tmpxpd0sk7e']'
2022-11-24 21:22:51,742 DEBUG: Spawned '['daemon', '-q', 'analytics', 'C:\\Users\\Sven\\AppData\\Local\\Temp\\tmpxpd0sk7e']'
```

---

Below the corresponding output of **dvc doctor**. My venv is using Python 3.11.0, however according to the output the platform appears to be Python 3.10.8.

```
(base) D:\git\parking-slots>dvc doctor
DVC version: 2.34.0 (exe)
---------------------------------
Platform: Python 3.10.8 on Windows-10-10.0.19045-SP0
Subprojects:

Supports:
        azure (adlfs = 2022.10.0, knack = 0.10.0, azure-identity = 1.12.0),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = 2022.11.0),
        hdfs (fsspec = 2022.11.0, pyarrow = 10.0.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2022.11.0, boto3 = 1.24.59),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2022.11.0)
Cache types:
Cache directory: exFAT on D:\
Caches: local
Remotes: None
Workspace directory: exFAT on D:\
Repo: dvc, git
```

Thanks for any suggestions! :)

**Comment by pmrowla** [comment]
exfat doesn't support hardlinks: https://learn.microsoft.com/en-us/windows/win32/fileio/filesystem-functionality-comparison#functionality

We need to handle that particular oserror on windows in `_try_links`
https://github.com/iterative/dvc-objects/blob/76db927c585f89e0d7ebdc7c481c6ebba77a91a2/src/dvc_objects/fs/generic.py#L99-L105
