### ISSUE TITLE
exp:  the `dvc exp show --num` command is broken on branches without history when you create a branch with `dvc branch`. 

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#8526]
From my testing so far, the `dvc exp show --num` command is broken on branches without history when you create a branch with `dvc branch`. 

https://user-images.githubusercontent.com/43496356/199589691-26fed2b0-11ac-4c10-833b-032ca0495415.mov

Steps to reproduce
```bash
dvc exp branch EXP_NAME BRANCH_NAME
git checkout BRANCH_NAME
dvc exp show -n 3
```
_Originally posted by @julieg18 in https://github.com/iterative/vscode-dvc/issues/2703#issuecomment-1301161381_

**Comment by karajan1001** [comment]
@julieg18 Excuse me, I'm sorry I cannot reproduce on my side. could you please give more details? the output of the `dvc exp show -n 3 -vv` and the output of `dvc doctor`.

**Comment by julieg18** [comment]
> @julieg18 Excuse me, I'm sorry I cannot reproduce on my side. could you please give more details? the output of the dvc exp show -n 3 -vv and the output of dvc doctor.

Sure! (I used the [`ensemble-dvc-template`](https://github.com/shcheklein/ensemble-dvc-template/tree/experiment) repo that Ivan mentioned in https://github.com/iterative/vscode-dvc/issues/2703)

<details>

<summary>verbose exp show output</summary>

```
❯ dvc exp show -n 3 -vv
2022-11-08 08:31:30,472 TRACE: Namespace(cprofile=False, yappi=False, yappi_separate_threads=False, viztracer=False, viztracer_depth=None, cprofile_dump=None, pdb=False, instrument=False, instrument_open=False, show_stack=False, quiet=0, verbose=2, version=None, cd='.', cmd='show', all_commits=False, rev=None, num=3, all_branches=False, all_tags=False, no_pager=False, only_changed=False, drop=None, keep=None, param_deps=False, sort_by=None, sort_order='asc', sha=False, hide_failed=False, hide_queued=False, json=False, csv=False, markdown=False, precision=None, pcp=False, out=None, open=False, fetch_running=True, func=<class 'dvc.commands.experiments.show.CmdExperimentsShow'>, parser=DvcParser(prog='dvc', usage=None, description='Data Version Control', formatter_class=<class 'argparse.RawTextHelpFormatter'>, conflict_handler='error', add_help=False))
2022-11-08 08:31:30,907 TRACE: params.yaml does not exist, it won't be used in parametrization
2022-11-08 08:31:30,939 TRACE: Context during resolution of stage train@model-1:
{'item': 'model-1'}
2022-11-08 08:31:30,946 TRACE: Context during resolution of stage train@model-2:
{'item': 'model-2'}
2022-11-08 08:31:30,950 TRACE: Context during resolution of stage evaluate:
{}
2022-11-08 08:31:30,953 TRACE:    65.37 ms in collecting stages from /Users/juliegalvan/Desktop/workspace/ensemble-dvc-template
2022-11-08 08:31:30,956 TRACE:     2.32 ms in collecting stages from /Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/model-2
2022-11-08 08:31:30,956 TRACE:     8.27 mks in collecting stages from /Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/.devcontainer
2022-11-08 08:31:30,959 TRACE:     2.69 ms in collecting stages from /Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/model-1
2022-11-08 08:31:30,960 TRACE:    16.44 mks in collecting stages from /Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/evaluation
2022-11-08 08:31:30,962 TRACE:   297.50 mks in collecting stages from /Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/dvclive
2022-11-08 08:31:30,963 TRACE:   158.01 mks in collecting stages from /Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/dvclive/model-2
2022-11-08 08:31:30,963 TRACE:   143.98 mks in collecting stages from /Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/dvclive/model-2/plots
2022-11-08 08:31:30,964 TRACE:     9.23 mks in collecting stages from /Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/dvclive/model-2/plots/metrics
2022-11-08 08:31:30,965 TRACE:   168.88 mks in collecting stages from /Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/dvclive/model-1
2022-11-08 08:31:30,965 TRACE:   148.02 mks in collecting stages from /Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/dvclive/model-1/plots
2022-11-08 08:31:30,967 TRACE:    66.03 mks in collecting stages from /Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/dvclive/model-1/plots/metrics
2022-11-08 08:31:30,968 TRACE:     8.01 mks in collecting stages from /Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/.vscode
2022-11-08 08:31:31,115 TRACE: params.yaml does not exist, it won't be used in parametrization
2022-11-08 08:31:31,117 TRACE: Context during resolution of stage train@model-1:
{'item': 'model-1'}
2022-11-08 08:31:31,121 TRACE: Context during resolution of stage train@model-2:
{'item': 'model-2'}
2022-11-08 08:31:31,124 TRACE: Context during resolution of stage evaluate:
{}
2022-11-08 08:31:31,125 TRACE:    17.50 ms in collecting stages from /
2022-11-08 08:31:31,126 TRACE:     8.71 mks in collecting stages from /.devcontainer
2022-11-08 08:31:31,126 TRACE:     6.40 mks in collecting stages from /.dvc
2022-11-08 08:31:31,128 TRACE:    28.52 mks in collecting stages from /dvclive
2022-11-08 08:31:31,129 TRACE:    23.31 mks in collecting stages from /dvclive/model-1
2022-11-08 08:31:31,130 TRACE:     7.96 mks in collecting stages from /dvclive/model-1/plots
2022-11-08 08:31:31,131 TRACE:    58.27 mks in collecting stages from /dvclive/model-1/plots/metrics
2022-11-08 08:31:31,132 TRACE:    24.07 mks in collecting stages from /dvclive/model-2
2022-11-08 08:31:31,132 TRACE:     8.88 mks in collecting stages from /dvclive/model-2/plots
2022-11-08 08:31:31,133 TRACE:    50.88 mks in collecting stages from /dvclive/model-2/plots/metrics
2022-11-08 08:31:31,134 TRACE:    18.14 mks in collecting stages from /evaluation
2022-11-08 08:31:31,137 TRACE:     1.83 ms in collecting stages from /model-1
2022-11-08 08:31:31,138 TRACE:    37.11 mks in collecting stages from /model-1/data
2022-11-08 08:31:31,143 TRACE:     3.46 ms in collecting stages from /model-2
2022-11-08 08:31:31,145 TRACE:    25.66 mks in collecting stages from /model-2/data
2022-11-08 08:31:31,168 TRACE: params.yaml does not exist, it won't be used in parametrization
2022-11-08 08:31:31,170 TRACE: Context during resolution of stage train@model-1:
{'item': 'model-1'}
2022-11-08 08:31:31,173 TRACE: Context during resolution of stage train@model-2:
{'item': 'model-2'}
2022-11-08 08:31:31,176 TRACE: Context during resolution of stage evaluate:
{}
2022-11-08 08:31:31,178 TRACE:    17.35 ms in collecting stages from /
2022-11-08 08:31:31,179 TRACE:    25.06 mks in collecting stages from /.devcontainer
2022-11-08 08:31:31,180 TRACE:     6.48 mks in collecting stages from /.dvc
2022-11-08 08:31:31,181 TRACE:    33.58 mks in collecting stages from /dvclive
2022-11-08 08:31:31,182 TRACE:    14.69 mks in collecting stages from /dvclive/model-1
2022-11-08 08:31:31,183 TRACE:     8.43 mks in collecting stages from /dvclive/model-1/plots
2022-11-08 08:31:31,184 TRACE:    22.83 mks in collecting stages from /dvclive/model-1/plots/metrics
2022-11-08 08:31:31,185 TRACE:    12.96 mks in collecting stages from /dvclive/model-2
2022-11-08 08:31:31,186 TRACE:     6.39 mks in collecting stages from /dvclive/model-2/plots
2022-11-08 08:31:31,186 TRACE:     7.25 mks in collecting stages from /dvclive/model-2/plots/metrics
2022-11-08 08:31:31,186 TRACE:     7.18 mks in collecting stages from /evaluation
2022-11-08 08:31:31,190 TRACE:     3.54 ms in collecting stages from /model-1
2022-11-08 08:31:31,192 TRACE:    11.99 mks in collecting stages from /model-1/data
2022-11-08 08:31:31,197 TRACE:     3.86 ms in collecting stages from /model-2
2022-11-08 08:31:31,198 TRACE:    19.96 mks in collecting stages from /model-2/data
2022-11-08 08:31:31,221 TRACE: params.yaml does not exist, it won't be used in parametrization
2022-11-08 08:31:31,223 TRACE: Context during resolution of stage train@model-1:
{'item': 'model-1'}
2022-11-08 08:31:31,226 TRACE: Context during resolution of stage train@model-2:
{'item': 'model-2'}
2022-11-08 08:31:31,229 TRACE: Context during resolution of stage evaluate:
{}
2022-11-08 08:31:31,231 TRACE:    21.42 ms in collecting stages from /
2022-11-08 08:31:31,231 TRACE:    12.49 mks in collecting stages from /.devcontainer
2022-11-08 08:31:31,232 TRACE:     9.73 mks in collecting stages from /.dvc
2022-11-08 08:31:31,234 TRACE:    12.85 mks in collecting stages from /dvclive
2022-11-08 08:31:31,235 TRACE:    17.73 mks in collecting stages from /dvclive/model-1
2022-11-08 08:31:31,235 TRACE:     7.73 mks in collecting stages from /dvclive/model-1/plots
2022-11-08 08:31:31,236 TRACE:     9.25 mks in collecting stages from /dvclive/model-1/plots/metrics
2022-11-08 08:31:31,236 TRACE:    48.16 mks in collecting stages from /dvclive/model-2
2022-11-08 08:31:31,238 TRACE:    24.50 mks in collecting stages from /dvclive/model-2/plots
2022-11-08 08:31:31,240 TRACE:    39.39 mks in collecting stages from /dvclive/model-2/plots/metrics
2022-11-08 08:31:31,241 TRACE:    11.19 mks in collecting stages from /evaluation
2022-11-08 08:31:31,245 TRACE:     3.37 ms in collecting stages from /model-1
2022-11-08 08:31:31,245 TRACE:    16.06 mks in collecting stages from /model-1/data
2022-11-08 08:31:31,250 TRACE:     3.49 ms in collecting stages from /model-2
2022-11-08 08:31:31,250 TRACE:    11.47 mks in collecting stages from /model-2/data
2022-11-08 08:31:31,275 TRACE: params.yaml does not exist, it won't be used in parametrization
2022-11-08 08:31:31,277 TRACE: Context during resolution of stage train@model-1:
{'item': 'model-1'}
2022-11-08 08:31:31,281 TRACE: Context during resolution of stage train@model-2:
{'item': 'model-2'}
2022-11-08 08:31:31,288 TRACE: Context during resolution of stage evaluate:
{}
2022-11-08 08:31:31,292 TRACE:    26.03 ms in collecting stages from /
2022-11-08 08:31:31,293 TRACE:    31.58 mks in collecting stages from /.devcontainer
2022-11-08 08:31:31,294 TRACE:    23.27 mks in collecting stages from /.dvc
2022-11-08 08:31:31,296 TRACE:    11.40 mks in collecting stages from /dvclive
2022-11-08 08:31:31,297 TRACE:    25.14 mks in collecting stages from /dvclive/model-1
2022-11-08 08:31:31,299 TRACE:    13.86 mks in collecting stages from /dvclive/model-1/plots
2022-11-08 08:31:31,299 TRACE:    12.81 mks in collecting stages from /dvclive/model-1/plots/metrics
2022-11-08 08:31:31,300 TRACE:    14.18 mks in collecting stages from /dvclive/model-2
2022-11-08 08:31:31,301 TRACE:    46.30 mks in collecting stages from /dvclive/model-2/plots
2022-11-08 08:31:31,302 TRACE:    28.47 mks in collecting stages from /dvclive/model-2/plots/metrics
2022-11-08 08:31:31,303 TRACE:     8.12 mks in collecting stages from /evaluation
2022-11-08 08:31:31,305 TRACE:     1.84 ms in collecting stages from /model-1
2022-11-08 08:31:31,306 TRACE:    11.68 mks in collecting stages from /model-1/data
2022-11-08 08:31:31,309 TRACE:     2.31 ms in collecting stages from /model-2
2022-11-08 08:31:31,309 TRACE:     9.36 mks in collecting stages from /model-2/data
2022-11-08 08:31:31,333 TRACE: params.yaml does not exist, it won't be used in parametrization
2022-11-08 08:31:31,337 TRACE: Context during resolution of stage train@model-1:
{'item': 'model-1'}
2022-11-08 08:31:31,347 TRACE: Context during resolution of stage train@model-2:
{'item': 'model-2'}
2022-11-08 08:31:31,353 TRACE: Context during resolution of stage evaluate:
{}
2022-11-08 08:31:31,355 TRACE:    31.96 ms in collecting stages from /
2022-11-08 08:31:31,356 TRACE:     8.82 mks in collecting stages from /.devcontainer
2022-11-08 08:31:31,356 TRACE:     3.32 mks in collecting stages from /.dvc
2022-11-08 08:31:31,356 TRACE:     7.09 mks in collecting stages from /dvclive
2022-11-08 08:31:31,357 TRACE:    25.34 mks in collecting stages from /dvclive/model-1
2022-11-08 08:31:31,358 TRACE:     7.97 mks in collecting stages from /dvclive/model-1/plots
2022-11-08 08:31:31,358 TRACE:     9.10 mks in collecting stages from /dvclive/model-1/plots/metrics
2022-11-08 08:31:31,359 TRACE:    12.23 mks in collecting stages from /dvclive/model-2
2022-11-08 08:31:31,359 TRACE:     7.00 mks in collecting stages from /dvclive/model-2/plots
2022-11-08 08:31:31,360 TRACE:    12.25 mks in collecting stages from /dvclive/model-2/plots/metrics
2022-11-08 08:31:31,360 TRACE:    16.68 mks in collecting stages from /evaluation
2022-11-08 08:31:31,364 TRACE:     3.40 ms in collecting stages from /model-1
2022-11-08 08:31:31,365 TRACE:    12.62 mks in collecting stages from /model-1/data
2022-11-08 08:31:31,369 TRACE:     2.88 ms in collecting stages from /model-2
2022-11-08 08:31:31,369 TRACE:    10.52 mks in collecting stages from /model-2/data
2022-11-08 08:31:31,400 TRACE: params.yaml does not exist, it won't be used in parametrization
2022-11-08 08:31:31,403 TRACE: Context during resolution of stage train@model-1:
{'item': 'model-1'}
2022-11-08 08:31:31,411 TRACE: Context during resolution of stage train@model-2:
{'item': 'model-2'}
2022-11-08 08:31:31,420 TRACE: Context during resolution of stage evaluate:
{}
2022-11-08 08:31:31,422 TRACE:    32.11 ms in collecting stages from /
2022-11-08 08:31:31,423 TRACE:    11.74 mks in collecting stages from /.devcontainer
2022-11-08 08:31:31,424 TRACE:     6.78 mks in collecting stages from /.dvc
2022-11-08 08:31:31,425 TRACE:    10.89 mks in collecting stages from /dvclive
2022-11-08 08:31:31,425 TRACE:    15.18 mks in collecting stages from /dvclive/model-1
2022-11-08 08:31:31,426 TRACE:     8.16 mks in collecting stages from /dvclive/model-1/plots
2022-11-08 08:31:31,427 TRACE:     8.69 mks in collecting stages from /dvclive/model-1/plots/metrics
2022-11-08 08:31:31,427 TRACE:    12.61 mks in collecting stages from /dvclive/model-2
2022-11-08 08:31:31,428 TRACE:     6.52 mks in collecting stages from /dvclive/model-2/plots
2022-11-08 08:31:31,428 TRACE:    46.62 mks in collecting stages from /dvclive/model-2/plots/metrics
2022-11-08 08:31:31,431 TRACE:    31.65 mks in collecting stages from /evaluation
2022-11-08 08:31:31,436 TRACE:     4.06 ms in collecting stages from /model-1
2022-11-08 08:31:31,437 TRACE:    16.04 mks in collecting stages from /model-1/data
2022-11-08 08:31:31,440 TRACE:     2.37 ms in collecting stages from /model-2
2022-11-08 08:31:31,442 TRACE:    12.23 mks in collecting stages from /model-2/data
2022-11-08 08:31:31,499 ERROR: unexpected error - 'a4bc827538fab216fe5f01ebd92dd91eb2c85b3e'
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/.venv/lib/python3.9/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/.venv/lib/python3.9/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/.venv/lib/python3.9/site-packages/dvc/commands/experiments/show.py", line 472, in run
    all_experiments = self.repo.experiments.show(
  File "/Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/.venv/lib/python3.9/site-packages/dvc/repo/experiments/__init__.py", line 469, in show
    return show(self.repo, *args, **kwargs)
  File "/Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/.venv/lib/python3.9/site-packages/dvc/repo/experiments/show.py", line 370, in show
    get_names(repo, res)
  File "/Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/.venv/lib/python3.9/site-packages/dvc/repo/experiments/show.py", line 176, in get_names
    name = name or exact_name[rev]
KeyError: 'a4bc827538fab216fe5f01ebd92dd91eb2c85b3e'
------------------------------------------------------------
2022-11-08 08:31:32,260 DEBUG: Removing '/Users/juliegalvan/Desktop/workspace/.Mpg4e3dRhTfebxdsEQyW4P.tmp'
2022-11-08 08:31:32,261 DEBUG: Removing '/Users/juliegalvan/Desktop/workspace/.Mpg4e3dRhTfebxdsEQyW4P.tmp'
2022-11-08 08:31:32,261 DEBUG: Removing '/Users/juliegalvan/Desktop/workspace/.Mpg4e3dRhTfebxdsEQyW4P.tmp'
2022-11-08 08:31:32,261 DEBUG: Removing '/Users/juliegalvan/Desktop/workspace/ensemble-dvc-template/.dvc/cache/.TF2SPyLMdLhbn8RzhZeg2W.tmp'
2022-11-08 08:31:32,264 DEBUG: Version info for developers:
DVC version: 2.33.1 (pip)
---------------------------------
Platform: Python 3.9.4 on macOS-10.16-x86_64-i386-64bit
Subprojects:
        dvc_data = 0.25.2
        dvc_objects = 0.12.2
        dvc_render = 0.0.12
        dvc_task = 0.1.4
        dvclive = 0.12.2.dev10+gace839f
        scmrepo = 0.1.2
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s7s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s7s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-11-08 08:31:32,266 DEBUG: Analytics is enabled.
2022-11-08 08:31:32,459 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/xm/3tbdgph9391bx406zhwf7bx00000gn/T/tmpjghbtxf6']'
2022-11-08 08:31:32,460 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/xm/3tbdgph9391bx406zhwf7bx00000gn/T/tmpjghbtxf6']'
```
</details>

```
❯ dvc doctor
DVC version: 2.33.1 (pip)
---------------------------------
Platform: Python 3.9.4 on macOS-10.16-x86_64-i386-64bit
Subprojects:
        dvc_data = 0.25.2
        dvc_objects = 0.12.2
        dvc_render = 0.0.12
        dvc_task = 0.1.4
        dvclive = 0.12.2.dev10+gace839f
        scmrepo = 0.1.2
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s7s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s7s1
Repo: dvc, git
```
