### ISSUE TITLE
dvc import/get not working with a git repository with two remotes

### ISSUE THREAD

**Issue by moisesrc13** [iterative/dvc#8540]
# Bug Report

## Description

I have a git repository with two remotes, my `.dvc/config` is as follows, basically one  `remote` for model, and one for `data`
```
[core]
    autostage = true
    remote = modelstore
['remote "modelstore"']
    url = s3://models/classifier/dvcstore
    endpointurl = <endpoint URL>
['remote "datastore"']
    url = s3://data/classifier/dvcstore
    endpointurl = <endpoint URL>
```
Here, `model.dvc` & `data.dvc` exist under `/classifier` dir

Then I have other repository to consume only the model from my artifact registry repo above. When I try to import the model I get the following error 
```
dvc import <git repo> classifier/model --rev <tag>
ERROR: failed to import '<model path>' from '<git repo>'. - The path 'classifier/model' does not exist in the target repository '<git repo>' neither as a DVC output nor as a Git-tracked file.:
```
However the `mode.dvc` file exists in the repo under `classifier/model`. I have tried with and without a `default` remote, same error. Using `dvc get`, I only get `ERROR: unexpected error`

### Expected

model artifacts are downloaded on local `model`

### Environment information

**Output of `dvc doctor` on consumer repo:**

```console
$ dvc doctor
DVC version: 2.27.2 (pip)
---------------------------------
Platform: Python 3.9.7 on Linux-4.18.0-372.26.1.el8_6.x86_64-x86_64-with-glibc2.28
Subprojects:
        dvc_data = 0.10.0
        dvc_objects = 0.4.0
        dvc_render = 0.0.11
        dvc_task = 0.1.2
        dvclive = 0.11.0
        scmrepo = 0.1.1
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2022.10.0, boto3 = 1.24.59)
Cache types: reflink, hardlink, symlink
Cache directory: xfs on /dev/mapper/vg_li1744707733-lv_root
Caches: local
Remotes: None
Workspace directory: xfs on /dev/mapper/vg_li1744707733-lv_root
Repo: dvc, git
```

**Output of `dvc doctor` on artifact registry repo:**

```console
$ dvc doctor
DVC version: 2.27.2 (pip)
---------------------------------
Platform: Python 3.9.7 on Linux-4.18.0-372.26.1.el8_6.x86_64-x86_64-with-glibc2.28
Subprojects:
	dvc_data = 0.10.0
	dvc_objects = 0.4.0
	dvc_render = 0.0.11
	dvc_task = 0.1.2
	dvclive = 0.11.0
	scmrepo = 0.1.1
Supports:
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2022.10.0, boto3 = 1.24.59)
Cache types: reflink, hardlink, symlink
Cache directory: xfs on /dev/mapper/vg_li1744707733-lv_root
Caches: local
Remotes: s3, s3
Workspace directory: xfs on /dev/mapper/vg_li1744707733-lv_root
Repo: dvc, git

```

**Comment by pmrowla** [comment]
Is your `classifier` directory gitignored?

**Comment by moisesrc13** [comment]
> Is your `classifier` directory gitignored? DVC will traverse into gitignored directories when trying to find `.dvc` files, so if `classifier/` is gitignored DVC may not be able to find your `classifier/model.dvc` file when you are running `dvc import` in the consumer repo.

Hey, no. My  `classifier` directory is not gitignored.

**Comment by pmrowla** [comment]
> Using dvc get, I only get ERROR: unexpected error

Could you please re-run this with `dvc get -v` and post the full error traceback

**Comment by moisesrc13** [comment]
> > Using dvc get, I only get ERROR: unexpected error
> 
> Could you please re-run this with `dvc get -v` and post the full error traceback

Sure,
```
2022-11-09 07:18:14,065 DEBUG: Creating external repo <git repo>/classifier.git@classifier-model@v0.1.0-20221104-110143
2022-11-09 07:18:14,065 DEBUG: erepo: git clone '<git repo>/classifier.git' to a temporary dir
2022-11-09 07:18:23,625 DEBUG: Removing '/home/moisesrc/vs-workspace/classifier/.M8GcmwjHxRhMYbRTRyn6Hr'    
2022-11-09 07:18:23,631 ERROR: unexpected error
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/moisesrc/python-env-3.9.7/lib/python3.9/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/home/moisesrc/python-env-3.9.7/lib/python3.9/site-packages/dvc/cli/command.py", line 36, in do_run
    return self.run()
  File "/home/moisesrc/python-env-3.9.7/lib/python3.9/site-packages/dvc/commands/get.py", line 33, in run
    return self._get_file_from_repo()
  File "/home/moisesrc/python-env-3.9.7/lib/python3.9/site-packages/dvc/commands/get.py", line 39, in _get_file_from_repo
    Repo.get(
  File "/home/moisesrc/python-env-3.9.7/lib/python3.9/site-packages/dvc/repo/get.py", line 67, in get
    fs.get(
  File "/home/moisesrc/python-env-3.9.7/lib/python3.9/site-packages/dvc_objects/fs/base.py", line 476, in get
    from_infos = list(self.find(from_info))
  File "/home/moisesrc/python-env-3.9.7/lib/python3.9/site-packages/dvc_objects/fs/base.py", line 329, in find
    yield from self.fs.find(path)
  File "/home/moisesrc/python-env-3.9.7/lib/python3.9/site-packages/fsspec/spec.py", line 442, in find
    for _, dirs, files in self.walk(path, maxdepth, detail=True, **kwargs):
  File "/home/moisesrc/python-env-3.9.7/lib/python3.9/site-packages/fsspec/spec.py", line 390, in walk
    listing = self.ls(path, detail=True, **kwargs)
  File "/home/moisesrc/python-env-3.9.7/lib/python3.9/site-packages/dvc/fs/dvc.py", line 257, in ls
    for entry in dvc_fs.ls(dvc_path, detail=False):
  File "/home/moisesrc/python-env-3.9.7/lib/python3.9/site-packages/dvc_objects/fs/base.py", line 322, in ls
    return self.fs.ls(path, detail=detail)
  File "/home/moisesrc/python-env-3.9.7/lib/python3.9/site-packages/dvc_data/fs.py", line 86, in ls
    for key in self.index.ls(root_key, detail=False)
  File "/home/moisesrc/python-env-3.9.7/lib/python3.9/site-packages/dvc_data/index.py", line 182, in ls
    self._ensure_loaded(root_key)
  File "/home/moisesrc/python-env-3.9.7/lib/python3.9/site-packages/dvc_data/index.py", line 179, in _ensure_loaded
    raise TreeError
dvc_data.hashfile.tree.TreeError
------------------------------------------------------------
2022-11-09 07:18:24,085 DEBUG: Removing '/home/moisesrc/vs-workspace/.CE2xfC882eKqVfLi9Fr3Cz.tmp'
2022-11-09 07:18:24,085 DEBUG: Removing '/home/moisesrc/vs-workspace/.CE2xfC882eKqVfLi9Fr3Cz.tmp'
2022-11-09 07:18:24,086 DEBUG: Removing '/home/moisesrc/vs-workspace/.CE2xfC882eKqVfLi9Fr3Cz.tmp'
2022-11-09 07:18:24,086 DEBUG: Removing '/home/moisesrc/vs-workspace/classifier/.dvc/cache/.gKvRZHz2KzVkBRimGgAaRs.tmp'
2022-11-09 07:18:24,095 DEBUG: Version info for developers:
DVC version: 2.27.2 (pip)
---------------------------------
Platform: Python 3.9.7 on Linux-4.18.0-372.26.1.el8_6.x86_64-x86_64-with-glibc2.28
Subprojects:
        dvc_data = 0.10.0
        dvc_objects = 0.4.0
        dvc_render = 0.0.11
        dvc_task = 0.1.2
        dvclive = 0.11.0
        scmrepo = 0.1.1
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2022.10.0, boto3 = 1.24.59)
Cache types: reflink, hardlink, symlink
Cache directory: xfs on /dev/mapper/vg_li1744707733-lv_root
Caches: local
Remotes: None
Workspace directory: xfs on /dev/mapper/vg_li1744707733-lv_root
Repo: dvc, git
```

**Comment by moisesrc13** [comment]
In addition, using `dvc get` I'm able to see `model` & `data` under `classifier/` path, but regardless this, import is failing
```
dvc list <git repo> classifier --rev classifier-model@v0.1.0-20221104-110143 -v
2022-11-09 10:08:39,040 DEBUG: Creating external repo <git repo>@classifier-model@v0.1.0-20221104-110143
2022-11-09 10:08:39,040 DEBUG: erepo: git clone '<git repo>' to a temporary dir
>>> clone path /tmp/tmpx4v_o5rjdvc-clone
>>>>>> ('classifier',)                                                                             
.gitignore
__init__.py
**data**
data.dvc
index.py
logger.py
**model**
model.dvc
notebooks
tasks
transformers
utils
```

**Comment by pmrowla** [comment]
Looks like this is probably a `dvc-data` bug, but just to be sure, could you please update to the latest DVC release (should be `2.34.0`) and retry those commands? There have been some recent changes in `dvc_data.index` that may have resolved the issue, so it would help if you can double check.

**Comment by moisesrc13** [comment]
> Looks like this is probably a `dvc-data` bug, but just to be sure, could you please update to the latest DVC release (should be `2.34.0`) and retry those commands? There have been some recent changes in `dvc_data.index` that may have resolved the issue, so it would help if you can double check.

thanks for the heads up!. Sure, will try with latest version.

**Comment by moisesrc13** [comment]
@pmrowla  I tried with `2.34.0` and still `get` & `import` are failing. Notice that now `dvc ls` works, but still not able to get my data

**Comment by pmrowla** [comment]
Also, one last question, can you confirm which remote you have set as the default now, and which directory DVC cannot find on `import`?

**Comment by moisesrc13** [comment]
> Also, one last question, can you confirm which remote you have set as the default now, and which directory DVC cannot find on `import`?

I set the modelstore remote as default,  from my root project dir I added the directory as

dvc add classifier/model -r modelstore --to-remote

This directory, classifier/model is the one I can  not get

**Comment by moisesrc13** [comment]
adding more info here
when I use `dvc get --show-url`, the given path in my s3 bucket is empty

`dvc get --show-url <git repo> classifier/model`
>>
s3://models/model-registry/dvcstore/fd/fbd9ca7086474bb5ab4712e218ebe2.dir

and getting empty objects here
```
aws --endpoint-url=<s3 endpoint> s3 ls s3://models/model-registry/dvcstore/fd/fbd9ca7086474bb5ab4712e218ebe2.dir
```

this was working ok on `dvc==2.20.4` though

**Comment by pmrowla** [comment]
@moisesrc13 is it possible someone forgot to `dvc push` the latest data from your data registry?

**Comment by moisesrc13** [comment]
@pmrowla thanks so much!, adding the default remote in `mode.dvc` & `data.dvc` made it to work :tada:
