### ISSUE TITLE
`dvc pull` fails for folder containing dvc files created with `dvc import` and `dvc import-url` 

### ISSUE THREAD

**Issue by jruehle** [iterative/dvc#8607]
# Bug Report

## Description

`dvc pull -R` does not work for folders that contain both 
- dvc files created with `dvc import`
- dvc files created with `dvc import-url`

`dvc pull -R` fails in that case with a rather obscure error pointing to a cache issue.

### Reproduce

1. `mkdir testdir/`
2. `cd testdir/`
3. `git init .`
4. `dvc init`
5. `dvc import-url http://images.cocodataset.org/val2017/000000252219.jpg coco_000000252219.jpg`
6. `dvc import https://github.com/iterative/dataset-registry fashion-mnist/images.tar.gz`
7. `rm coco_000000252219.jpg`
8. `rm images.tar.gz`
9. `rm -rf .dvc/cache`
10. `dvc pull -R ./ -vvv`

Step `10` will fail with the error (full message, see additional information below):
```console
2022-11-22 12:33:59,574 ERROR: failed to pull data from the cloud - Checkout failed for following targets:
[removed path]/testdir/images.tar.gz
Is your cache up to date?
<https://error.dvc.org/missing-files>
------------------------------------------------------------
Traceback (most recent call last):
  File "[removed path]/dvc-venv/lib/python3.8/site-packages/dvc/commands/data_sync.py", line 31, in run
    stats = self.repo.pull(
  File "[removed path]/dvc-venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "[removed path]/dvc-venv/lib/python3.8/site-packages/dvc/repo/pull.py", line 46, in pull
    stats = self.checkout(
  File "[removed path]/dvc-venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "[removed path]/dvc-venv/lib/python3.8/site-packages/dvc/repo/checkout.py", line 113, in checkout
    raise CheckoutError(stats["failed"], stats)
dvc.exceptions.CheckoutError: Checkout failed for following targets:
[removed path]/testdir/images.tar.gz
Is your cache up to date?
<https://error.dvc.org/missing-files>
```

### Expected

`dvc pull` should finish without an error and both files `coco_000000252219.jpg` and `images.tar.gz` should have been created.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.34.2 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.15.0-53-generic-x86_64-with-glibc2.29
Subprojects:
        dvc_data = 0.25.3
        dvc_objects = 0.12.2
        dvc_render = 0.0.12
        dvc_task = 0.1.5
        dvclive = 1.0.1
        scmrepo = 0.1.3
Supports:
        http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb1
Caches: local
Remotes: http, http, https, https
Workspace directory: ext4 on /dev/sdb1
Repo: dvc, git
----------------------
```

**Additional Information:**

Verbose output of the failing `dvc pull -R ./ -vvv` command:
```console
$ dvc pull -R ./ -vvv                                                                                                                
2022-11-22 12:33:51,721 TRACE: Namespace(all_branches=False, all_commits=False, all_tags=False, cd='.', cmd='pull', cprofile=False, cprofile_dump=None, force=False, func=<class 'dvc.commands.data_sync.CmdDataPull'>, glob=False, instrument=False, instrument_open=False, jobs=None, parser=DvcParser(prog='dvc', usage=None, description='Data Version Control', formatter_class=<class 'argparse.RawTextHelpFormatter'>, conflict_handler='error', add_help=False), pdb=False, quiet=0, recursive=True, remote=None, run_cache=False, show_stack=False, targets=['./'], verbose=3, version=None, viztracer=False, viztracer_depth=None, with_deps=False, yappi=False, yappi_separate_threads=False)
2022-11-22 12:33:51,869 DEBUG: Checking if stage './' is in 'dvc.yaml'
2022-11-22 12:33:51,950 TRACE:    79.56 ms in collecting stages from [removed path]/testdir
2022-11-22 12:33:51,987 DEBUG: Creating external repo https://github.com/iterative/dataset-registry@c172a9b59c7f30a5f83a87adb9296406676dfffa
2022-11-22 12:33:51,988 DEBUG: erepo: git clone 'https://github.com/iterative/dataset-registry' to a temporary dir
2022-11-22 12:33:59,537 DEBUG: Checking if stage '/fashion-mnist/images.tar.gz' is in 'dvc.yaml'
2022-11-22 12:33:59,538 TRACE:    17.62 mks in collecting stages from /
2022-11-22 12:33:59,539 TRACE:     2.89 mks in collecting stages from /.dvc
2022-11-22 12:33:59,541 TRACE:     1.93 ms in collecting stages from /blog
2022-11-22 12:33:59,542 TRACE:     1.02 ms in collecting stages from /dvc-course
2022-11-22 12:33:59,545 TRACE:     2.66 ms in collecting stages from /fashion-mnist
2022-11-22 12:33:59,547 TRACE:     1.09 ms in collecting stages from /get-started
2022-11-22 12:33:59,548 TRACE:   894.83 mks in collecting stages from /github-issues                                                                                                                                        
2022-11-22 12:33:59,551 TRACE:     2.65 ms in collecting stages from /images                                                                                                                                                
2022-11-22 12:33:59,554 TRACE:     2.66 ms in collecting stages from /mnist
2022-11-22 12:33:59,554 TRACE:     4.45 mks in collecting stages from /tutorials
2022-11-22 12:33:59,556 TRACE:     1.79 ms in collecting stages from /tutorials/nlp
2022-11-22 12:33:59,558 TRACE:     1.93 ms in collecting stages from /tutorials/versioning
2022-11-22 12:33:59,559 TRACE:   871.48 mks in collecting stages from /use-cases
2022-11-22 12:33:59,566 DEBUG: Checking if stage './' is in 'dvc.yaml'
2022-11-22 12:33:59,571 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)                                                                                                           
2022-11-22 12:33:59,572 DEBUG: Removing '[removed path]/testdir/.6QuDS2FAVLzSRFF93cRa3r.tmp'                                                                                        
2022-11-22 12:33:59,572 DEBUG: Removing '[removed path]/testdir/.6QuDS2FAVLzSRFF93cRa3r.tmp'                                                                                        
2022-11-22 12:33:59,573 DEBUG: Removing '[removed path]/testdir/.dvc/cache/.YfPETN2y8UdPFEdwj7NLfi.tmp'                                                                             
1 file failed
2022-11-22 12:33:59,574 ERROR: failed to pull data from the cloud - Checkout failed for following targets:
[removed path]/testdir/images.tar.gz
Is your cache up to date?
<https://error.dvc.org/missing-files>
------------------------------------------------------------
Traceback (most recent call last):
  File "[removed path]/dvc-venv/lib/python3.8/site-packages/dvc/commands/data_sync.py", line 31, in run
    stats = self.repo.pull(
  File "[removed path]/dvc-venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "[removed path]/dvc-venv/lib/python3.8/site-packages/dvc/repo/pull.py", line 46, in pull
    stats = self.checkout(
  File "[removed path]/dvc-venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "[removed path]/dvc-venv/lib/python3.8/site-packages/dvc/repo/checkout.py", line 113, in checkout
    raise CheckoutError(stats["failed"], stats)
dvc.exceptions.CheckoutError: Checkout failed for following targets:
[removed path]/testdir/images.tar.gz
Is your cache up to date?
<https://error.dvc.org/missing-files>
------------------------------------------------------------
2022-11-22 12:33:59,577 DEBUG: Analytics is enabled.
2022-11-22 12:33:59,622 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpx60hxrjx']'
2022-11-22 12:33:59,623 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpx60hxrjx']'
```

**Comment by jruehle** [comment]
Sorry for the noise.

`Step 9` in is wrong and causing the cache issue when trying to reproducible the error. 
Should be `rm -rf .dvc/cache/*` to only remove the cache folder content but not the cache folder itself. When doing the right `rm` command, my bug is no longer reproducible (all is correctly working). 

I am closing this issue until I find another way to create reproducible problems with `import`ed and `import-url` imported dvc files.
