### ISSUE TITLE
dvc.api.open: does not work, whereas DVCFileSystem.open does

### ISSUE THREAD

**Issue by francesco086** [iterative/dvc#8635]
# Bug Report

## Description

I am working in a dvc initialized git repository, with remote set.

This code works:
```python
from dvc.api import DVCFileSystem
import pandas as pd

fs = DVCFileSystem()

with fs.open("/customers/dvc/data_0_0_0.snappy.parquet") as f:
    print(pd.read_parquet(f))
```

This one does not (bug?):
```python
import dvc.api
import pandas as pd


with dvc.api.open(
    path="/customers/dvc/data_0_0_0.snappy.parquet",
    mode="rb",
) as f:
    print(pd.read_parquet(f))
```

Error:
```
Traceback (most recent call last):
  File "/Users/cesco/Code/exp/data-extraction/venv/lib/python3.10/site-packages/dvc_data/index/index.py", line 134, in info
    entry = self[key]
  File "/Users/cesco/Code/exp/data-extraction/venv/lib/python3.10/site-packages/dvc_data/index/index.py", line 179, in __getitem__
    return self._trie[key]
  File "/Users/cesco/Code/exp/data-extraction/venv/lib/python3.10/site-packages/pygtrie.py", line 937, in __getitem__
    node, _ = self._get_node(key_or_slice)
  File "/Users/cesco/Code/exp/data-extraction/venv/lib/python3.10/site-packages/pygtrie.py", line 630, in _get_node
    raise KeyError(key)
KeyError: ('customers', 'dvc', 'data_0_0_0.snappy.parquet')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cesco/Code/exp/data-extraction/venv/lib/python3.10/site-packages/dvc/repo/__init__.py", line 524, in open_by_relpath
    with fs.open(
  File "/Users/cesco/Code/exp/data-extraction/venv/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 197, in open
    return self.fs.open(path, mode=mode, **kwargs)
  File "/Users/cesco/Code/exp/data-extraction/venv/lib/python3.10/site-packages/dvc_data/fs.py", line 70, in open
    fs, fspath = self._get_fs_path(path, **kwargs)
  File "/Users/cesco/Code/exp/data-extraction/venv/lib/python3.10/site-packages/dvc_data/fs.py", line 46, in _get_fs_path
    info = self.info(path)
  File "/Users/cesco/Code/exp/data-extraction/venv/lib/python3.10/site-packages/dvc_data/fs.py", line 109, in info
    info = self.index.info(key)
  File "/Users/cesco/Code/exp/data-extraction/venv/lib/python3.10/site-packages/dvc_data/index/index.py", line 162, in info
    raise FileNotFoundError from exc
FileNotFoundError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cesco/Code/exp/data-extraction/exp.py", line 5, in <module>
    with dvc.api.open(
  File "/Users/cesco/.pyenv/versions/3.10.6/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/cesco/Code/exp/data-extraction/venv/lib/python3.10/site-packages/dvc/api/data.py", line 198, in _open
    with _repo.open_by_relpath(
  File "/Users/cesco/.pyenv/versions/3.10.6/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/cesco/Code/exp/data-extraction/venv/lib/python3.10/site-packages/dvc/repo/__init__.py", line 531, in open_by_relpath
    raise FileMissingError(path) from exc
dvc.exceptions.FileMissingError: Can't find '/customers/dvc/data_0_0_0.snappy.parquet' neither locally nor on remote
```

### Expected

I expect `dvc.api.open` to work the same as `DVCFileSystem.open`, as it is mentioned so in the documentation.

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.33.0 (brew)
---------------------------------
Platform: Python 3.10.8 on macOS-12.6.1-arm64-arm-64bit
Subprojects:
        dvc_data = 0.25.1
        dvc_objects = 0.12.1
        dvc_render = 0.0.12
        dvc_task = 0.1.4
        dvclive = 0.12.1
        scmrepo = 0.1.2
Supports:
        azure (adlfs = 2022.10.0, knack = 0.10.0, azure-identity = 1.11.0),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = 2022.10.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2022.10.0, boto3 = 1.24.59),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2022.10.0)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: azure
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc (no_scm)
```

**Comment by dtrifiro** [comment]
Ciao Francesco, the issue here is that `DVCFileSystem` can take absolute paths (dvc repo file system), whereas `dvc.api.open` is meant to be used with relative paths only: https://dvc.org/doc/api-reference/open#parameters

**Comment by francesco086** [comment]
Argh I didn't notice it, ok thanks! I will close this issue
