### ISSUE TITLE
dvc push: fails on p9 filesystem mounted in crostini

### ISSUE THREAD

**Issue by liljenstolpe** [iterative/dvc#8709]
# Bug Report

## Description

First of all, I know this is a crap bug report, sorry about that - don't have time to dig into to it more at the moment. 

I have a DVC repo I want to work on in a crostini container (linux environment in a chromebook).  If I place the repo in a directory in the 'main' chromeos filesystem 'shared' with linux (p9 mount) everything works (git, etc) but DVC pulls fail with 'unexpected i/o error').  

If I place the repo in the local container filesystem it all works.  When I have time, I'll do more digging.  

In the meantime, if you find yourself doing DVC on chromebooks, keep your repos in the local crostini container (btrfs), not chromeOS (p9) file system.

**Comment by rlamy** [comment]
Thanks for the report, please add more details when you can, such as a full reproducer, and the complete traceback for the failing operation (with `dvc push -v` or similar).

**Comment by liljenstolpe** [comment]
Here is the traceback....

```
cdl@penguin:/mnt/chromeos/MyFiles/Downloads/b22ca$ dvc pull -v
2022-12-19 14:32:05,471 ERROR: unexpected error - disk I/O error
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/cli/__init__.py", line 184, in main
    cmd = args.func(args)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/cli/command.py", line 16, in __init__
    self.repo: "Repo" = Repo(uninitialized=self.UNINITIALIZED)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/repo/__init__.py", line 215, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc_data/hashfile/state.py", line 83, in __init__
    self.links = Cache(links_dir)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/home/cdl/.local/lib/python3.9/site-packages/diskcache/core.py", line 480, in __init__
    sql(
  File "/home/cdl/.local/lib/python3.9/site-packages/diskcache/core.py", line 666, in _execute_with_retry
    return sql(statement, *args, **kwargs)
sqlite3.OperationalError: disk I/O error
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/cli/__init__.py", line 184, in main
    cmd = args.func(args)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/cli/command.py", line 16, in __init__
    self.repo: "Repo" = Repo(uninitialized=self.UNINITIALIZED)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/repo/__init__.py", line 215, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc_data/hashfile/state.py", line 83, in __init__
    self.links = Cache(links_dir)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/home/cdl/.local/lib/python3.9/site-packages/diskcache/core.py", line 480, in __init__
    sql(
  File "/home/cdl/.local/lib/python3.9/site-packages/diskcache/core.py", line 666, in _execute_with_retry
    return sql(statement, *args, **kwargs)
sqlite3.OperationalError: disk I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdl/.local/bin/dvc", line 8, in <module>
    sys.exit(main())
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/cli/__init__.py", line 211, in main
    ret = _log_exceptions(exc) or 255
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/cli/__init__.py", line 130, in _log_exceptions
    _log_unknown_exceptions()
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/cli/__init__.py", line 46, in _log_unknown_exceptions
    logger.debug("Version info for developers:\n%s", get_dvc_info())
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/info.py", line 39, in get_dvc_info
    with Repo() as repo:
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/repo/__init__.py", line 215, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc_data/hashfile/state.py", line 83, in __init__
    self.links = Cache(links_dir)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/home/cdl/.local/lib/python3.9/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/home/cdl/.local/lib/python3.9/site-packages/diskcache/core.py", line 2433, in reset
    ((old_value,),) = sql(
sqlite3.OperationalError: disk I/O error
```

## Looks like dvc doctor fails too....

```
$ dvc doctor 
ERROR: unexpected error - disk I/O error

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
````

same traceback, basically

```
2022-12-19 14:34:25,009 ERROR: unexpected error - disk I/O error
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/cli/command.py", line 36, in do_run
    return self.run()
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/commands/version.py", line 16, in run
    dvc_info = get_dvc_info()
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/info.py", line 39, in get_dvc_info
    with Repo() as repo:
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/repo/__init__.py", line 215, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc_data/hashfile/state.py", line 83, in __init__
    self.links = Cache(links_dir)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/home/cdl/.local/lib/python3.9/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/home/cdl/.local/lib/python3.9/site-packages/diskcache/core.py", line 2433, in reset
    ((old_value,),) = sql(
sqlite3.OperationalError: disk I/O error
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/cli/command.py", line 36, in do_run
    return self.run()
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/commands/version.py", line 16, in run
    dvc_info = get_dvc_info()
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/info.py", line 39, in get_dvc_info
    with Repo() as repo:
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/repo/__init__.py", line 215, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc_data/hashfile/state.py", line 83, in __init__
    self.links = Cache(links_dir)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/home/cdl/.local/lib/python3.9/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/home/cdl/.local/lib/python3.9/site-packages/diskcache/core.py", line 2433, in reset
    ((old_value,),) = sql(
sqlite3.OperationalError: disk I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cdl/.local/bin/dvc", line 8, in <module>
    sys.exit(main())
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/cli/__init__.py", line 211, in main
    ret = _log_exceptions(exc) or 255
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/cli/__init__.py", line 130, in _log_exceptions
    _log_unknown_exceptions()
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/cli/__init__.py", line 46, in _log_unknown_exceptions
    logger.debug("Version info for developers:\n%s", get_dvc_info())
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/info.py", line 39, in get_dvc_info
    with Repo() as repo:
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc/repo/__init__.py", line 215, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc_data/hashfile/state.py", line 83, in __init__
    self.links = Cache(links_dir)
  File "/home/cdl/.local/lib/python3.9/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/home/cdl/.local/lib/python3.9/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/home/cdl/.local/lib/python3.9/site-packages/diskcache/core.py", line 2433, in reset
    ((old_value,),) = sql(
sqlite3.OperationalError: disk I/O error
```

**Comment by liljenstolpe** [comment]
Looks like it's in the bowls of sqlite, but I haven't seen this behavior before....

**Comment by liljenstolpe** [comment]
Will be offline starting 00:00 22-DEC-2022Z until 00:00 09-JAN-2023Z

**Comment by rlamy** [comment]
It's never a good sign when `dvc doctor` fails...
I suspect that traceback means that something in `.dvc/tmp/links/` isn't writable. Can you check permissions and whether you're able to read and write files from Python?

**Comment by liljenstolpe** [comment]
.dvc/tmp/links is 755 and I can touch and write files from the shell

the following python code works as expected
```python
file = open( "testFile", "w" )
file.write( "test text" )
file.close()
```
So that all rings out correctly.

**Comment by liljenstolpe** [comment]
Any thoughts here?

**Comment by efiop** [comment]
@liljenstolpe Could you try the latest version? We've changed some internal layouts for temporary files, which might help in your specific case as well.
