### ISSUE TITLE
Problems with dvc 2.34.0 on ReFS formatted drive under Windows ( does not happen with 2.10.1 )

### ISSUE THREAD

**Issue by SpaceGhost123** [iterative/dvc#8711]
Let me first say, I am appreciative of dvc and very much enjoy using it. However, I am now experiencing problems with the newer version of dvc when the add command fails with a "WinError 50". Any help or suggestions would be appreciated.

**With 2.34.0 I get the following:**
```
PS E:\Test2>  &"C:\Program Files (x86)\DVC (Data Version Control) 2.34.0\dvc.exe" version
DVC version: 2.34.0 (exe)
---------------------------------
Platform: Python 3.10.8 on Windows-10-10.0.19044-SP0
Subprojects:

Supports:
        azure (adlfs = 2022.10.0, knack = 0.10.0, azure-identity = 1.12.0),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = 2022.11.0),
        hdfs (fsspec = 2022.11.0, pyarrow = 10.0.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2022.11.0, boto3 = 1.24.59),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2022.11.0)

PS E:\Test2>  &"C:\Program Files (x86)\DVC (Data Version Control) 2.34.0\dvc.exe" init
Initialized DVC repository.

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|             <https://dvc.org/doc/user-guide/analytics>              |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: <https://dvc.org/doc>
- Get help and share ideas: <https://dvc.org/chat>
- Star us on GitHub: <https://github.com/iterative/dvc>
PS E:\Test2>  &"C:\Program Files (x86)\DVC (Data Version Control) 2.34.0\dvc.exe" add a.png
Adding...
ERROR: failed to transfer 'md5: 8c490777d38df41d34c371c1ad8638a5' - [WinError 50] The request is not supported: 'E:\\Test2\\a.png' -> 'E:\\Test2\\.dvc\\cache\\8c\\490777d38df41d34c371c1ad8638a5'
file/directory 'E:\Test2\a.png' is going to be removed. Are you sure you want to proceed? [y/n]

**whereas with 2.10.1 I get the following (normal expected behavior) **

PS E:\Test1> &"C:\Program Files (x86)\DVC (Data Version Control) 2.10.1\dvc.exe" version
DVC version: 2.10.1 (exe)
---------------------------------
Platform: Python 3.8.10 on Windows-10-10.0.19044-SP0
Supports:
        azure (adlfs = 2022.4.0, knack = 0.9.0, azure-identity = 1.9.0),
        gdrive (pydrive2 = 1.10.1),
        gs (gcsfs = 2022.3.0),
        hdfs (fsspec = 2022.3.0, pyarrow = 7.0.0),
        webhdfs (fsspec = 2022.3.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.3.0, boto3 = 1.21.21),
        ssh (sshfs = 2022.3.1),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.5),
        webdavs (webdav4 = 0.9.5)
Cache types:
Cache directory: ReFS on E:\
Caches: local
Remotes: None
Workspace directory: ReFS on E:\
Repo: dvc, git

You are using dvc version 2.10.1; however, version 2.38.1 is available.
To upgrade, uninstall dvc and reinstall from https://dvc.org.

PS E:\Test1> &"C:\Program Files (x86)\DVC (Data Version Control) 2.10.1\dvc.exe" init
Initialized DVC repository.

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|             <https://dvc.org/doc/user-guide/analytics>              |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: <https://dvc.org/doc>
- Get help and share ideas: <https://dvc.org/chat>
- Star us on GitHub: <https://github.com/iterative/dvc>

PS E:\Test1> &"C:\Program Files (x86)\DVC (Data Version Control) 2.10.1\dvc.exe" add a.png
100% Adding...|███████████████████████████████████████████████████████████████████████████████|1/1 [00:00,  6.41file/s]

To track the changes with git, run:

    git add a.png.dvc

To enable auto staging, run:

        dvc config core.autostage true
```

**Comment by efiop** [comment]
@SpaceGhost123 Please add `-v` flag to the command that is failing and show us full log.

**Comment by SpaceGhost123** [comment]
I had to run it twice,  the first time it said it was locked so I deleted .dvc/tmp/rwlock per the instructions. 

PS E:\Test2> &"C:\Program Files (x86)\DVC (Data Version Control) 2.34.0\dvc.exe" add -v a.png
Adding...                                                                                                              2022-12-19 16:14:44,127 DEBUG: Computed stage: 'a.png.dvc' md5: 'None'
Adding...
2022-12-19 16:14:44,134 ERROR: 'E:\Test2\a.png' is busy, it is being blocked by:
  (PID 58792): C:\Program Files (x86)\DVC (Data Version Control) 2.34.0\dvc.exe add a.png

If there are no processes with such PIDs, you can manually remove '.dvc/tmp/rwlock' and try again.
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc\commands\add.py", line 53, in run
  File "dvc\utils\collections.py", line 164, in inner
  File "dvc\repo\__init__.py", line 48, in wrapper
  File "dvc\repo\scm_context.py", line 156, in run
  File "dvc\repo\add.py", line 192, in add
  File "funcy\decorators.py", line 45, in wrapper
  File "dvc\stage\decorators.py", line 35, in rwlocked
  File "contextlib.py", line 135, in __enter__
  File "dvc\rwlock.py", line 174, in rwlock
  File "dvc\rwlock.py", line 90, in _check_blockers
dvc.lock.LockError: 'E:\Test2\a.png' is busy, it is being blocked by:
  (PID 58792): C:\Program Files (x86)\DVC (Data Version Control) 2.34.0\dvc.exe add a.png

If there are no processes with such PIDs, you can manually remove '.dvc/tmp/rwlock' and try again.
------------------------------------------------------------
2022-12-19 16:14:44,142 DEBUG: Analytics is enabled.
2022-12-19 16:14:44,144 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\rystrol\\AppData\\Local\\Temp\\tmpynrxxp72']'
2022-12-19 16:14:44,156 DEBUG: Spawned '['daemon', '-q', 'analytics', 'C:\\Users\\rystrol\\AppData\\Local\\Temp\\tmpynrxxp72']'
PS E:\Test2> &"C:\Program Files (x86)\DVC (Data Version Control) 2.34.0\dvc.exe" add -v a.png
Adding...                                                                                                              2022-12-19 16:15:22,588 DEBUG: Computed stage: 'a.png.dvc' md5: 'None'
2022-12-19 16:15:22,594 DEBUG: Preparing to transfer data from 'memory://dvc-staging/df3e4ff16b0d3904cba73e238261a9223b2d3088fd3d2e8dc3ba87d51e3aad3b' to 'E:\Test2\.dvc\cache'
2022-12-19 16:15:22,595 DEBUG: Preparing to collect status from 'E:\Test2\.dvc\cache'
2022-12-19 16:15:22,596 DEBUG: Collecting status from 'E:\Test2\.dvc\cache'
                                                                                                                       2022-12-19 16:15:22,607 DEBUG: Preparing to collect status from 'memory://dvc-staging/df3e4ff16b0d3904cba73e238261a9223b2d3088fd3d2e8dc3ba87d51e3aad3b'
                                                                                                                       2022-12-19 16:15:22,618 ERROR: failed to transfer 'md5: 8c490777d38df41d34c371c1ad8638a5' - [WinError 50] The request is not supported: 'E:\\Test2\\a.png' -> 'E:\\Test2\\.dvc\\cache\\8c\\490777d38df41d34c371c1ad8638a5'
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc_data\hashfile\transfer.py", line 40, in wrapper
  File "dvc_data\hashfile\transfer.py", line 202, in func
  File "dvc_data\hashfile\db\__init__.py", line 105, in add
  File "dvc_objects\db.py", line 145, in add
  File "dvc_objects\fs\generic.py", line 132, in transfer
  File "dvc_objects\fs\generic.py", line 96, in _try_links
  File "dvc_objects\fs\generic.py", line 55, in _link
  File "dvc_objects\fs\base.py", line 321, in link
  File "dvc_objects\fs\local.py", line 163, in link
  File "dvc_objects\fs\system.py", line 32, in hardlink
OSError: [WinError 50] The request is not supported: 'E:\\Test2\\a.png' -> 'E:\\Test2\\.dvc\\cache\\8c\\490777d38df41d34c371c1ad8638a5'
------------------------------------------------------------
                                                                                                                       2022-12-19 16:15:22,631 DEBUG: link type reflink is not available ([Errno 129] no more link types left to try out)
2022-12-19 16:15:22,636 DEBUG: Removing 'E:\Test2\.RoZjF46fzfLbh9RCSFDQrT.tmp'
2022-12-19 16:15:22,642 DEBUG: Removing 'E:\Test2\.RoZjF46fzfLbh9RCSFDQrT.tmp'
2022-12-19 16:15:22,643 DEBUG: Removing 'E:\Test2\.dvc\cache\.EF6y6rJedvTH7Npdm6U78N.tmp'
file/directory 'E:\Test2\a.png' is going to be removed. Are you sure you want to proceed? [y/n]

**Comment by efiop** [comment]
@SpaceGhost123 Hey, sorry for the delay. Is this still happening for you?
