### ISSUE TITLE
Issue with some DVC commands on unitialized project when there is a `.dvc` folder in a higher directory

### ISSUE THREAD

**Issue by julieg18** [iterative/dvc#8731]
## Description

I ran into a strange issue while working on DVC VSCode onboarding. I created an empty folder (`Users/juliegalvan/workspace/testing-onboarding/test-1`), initialized git, and installed dvc. When I tried to run a couple dvc commands, I would get this error:

```
ERROR: /Users/juliegalvan is not a git repository
```

I tried `dvc exp show` and `dvc doctor`. The `show` command showed just the above error while `dvc doctor` showed the correct output and the error. Also, the error only appears if I haven't run `dvc init` yet. Once I ran `dvc init`, everything appears to be working correctly. 

Research brought up #3461 which shows a similar error. After some debugging, we figured out there was a `.dvc` folder in `/Users/juliegalvan`. I don't know how it got there, but once I deleted the `.dvc` folder, everything worked correctly. 

### Reproduce

I'm not sure how to reproduce since I'm not sure how I got a `.dvc` folder in `/Users/juliegalvan` in the first place 

### Expected

For `dvc exp show` to return the error: `ERROR: you are not inside of a DVC repository (checked up to mount point '/')` and for `dvc doctor` to just show the output with no error at all. 

### Environment information
**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 2.38.1 (pip)
---------------------------------
Platform: Python 3.9.4 on macOS-10.16-x86_64-i386-64bit
Subprojects:
        dvc_data = 0.28.4
        dvc_objects = 0.14.0
        dvc_render = 0.0.15
        dvc_task = 0.1.8
        dvclive = 1.2.2
        scmrepo = 0.1.4
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
```

**Additional Information (if any):**

Since the problem is solved and don't how to recreate it, I can't run anything with a verbose flag or see the error again. But I'm happy to help in any way I can.

**Comment by skshetry** [comment]
Can you recreate `.dvc` folder in `/Users/juliegalvan` again and provide the verbose output please?
```console
mkdir /Users/juliegalvan 
```

Reading through it, my initial guess is that the `Users/juliegalvan/workspace/testing-onboarding/test-1` did not have dvc initialized (i.e. `.dvc` folder missing), so dvc (correctly) backtracked and found `/Users/juliegalvan` and considered it as a root (also a correct behaviour).

**Comment by shcheklein** [comment]
ping @julieg18

**Comment by julieg18** [comment]
> 

Thanks, I was able to recreate once I ran `mkdir /Users/juliegalvan/.dvc`! Here's the verbose output of `dvc exp show`:

```
❯ dvc exp show -v
2022-12-29 12:01:34,817 ERROR: /Users/juliegalvan is not a git repository
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 132, in __init__
    self.repo = Repo.discover(start=root_dir)
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/dulwich/repo.py", line 1239, in discover
    raise NotGitRepository(
dulwich.errors.NotGitRepository: No git repository was found at /Users/juliegalvan

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/dvc/scm.py", line 76, in map_scm_exception
    yield
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/dvc/scm.py", line 102, in SCM
    return Git(
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/scmrepo/git/__init__.py", line 98, in __init__
    first_ = first(self.backends.values())
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/funcy/seqs.py", line 55, in first
    return next(iter(seq), None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/_collections_abc.py", line 869, in __iter__
    yield self._mapping[key]
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/scmrepo/git/__init__.py", line 49, in __getitem__
    initialized = backend(*self.args, **self.kwargs)
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 136, in __init__
    raise SCMError(f"{root_dir} is not a git repository") from exc
scmrepo.exceptions.SCMError: /Users/juliegalvan is not a git repository

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/dvc/cli/__init__.py", line 184, in main
    cmd = args.func(args)
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/dvc/cli/command.py", line 16, in __init__
    self.repo: "Repo" = Repo(uninitialized=self.UNINITIALIZED)
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/dvc/repo/__init__.py", line 225, in __init__
    self._ignore()
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/dvc/repo/__init__.py", line 382, in _ignore
    self.scm_context.ignore(file)
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/dvc/repo/__init__.py", line 281, in scm_context
    return SCMContext(self.scm, self.config)
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/dvc/repo/__init__.py", line 269, in scm
    return SCM(self.root_dir, no_scm=no_scm)
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/dvc/scm.py", line 102, in SCM
    return Git(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/juliegalvan/Desktop/workspace/vscode-onboarding-testing/test/.env/lib/python3.9/site-packages/dvc/scm.py", line 81, in map_scm_exception
    raise into
dvc.scm.SCMError: /Users/juliegalvan is not a git repository
------------------------------------------------------------
2022-12-29 12:01:34,827 DEBUG: Analytics is enabled.
2022-12-29 12:01:34,942 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/xm/3tbdgph9391bx406zhwf7bx00000gn/T/tmpgijewi1f']'
2022-12-29 12:01:34,943 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/xm/3tbdgph9391bx406zhwf7bx00000gn/T/tmpgijewi1f']'
```

> Reading through it, my initial guess is that the Users/juliegalvan/workspace/testing-onboarding/test-1 did not have dvc initialized (i.e. .dvc folder missing), so dvc (correctly) backtracked and found /Users/juliegalvan and considered it as a root (also a correct behaviour).

Good to know that it's correct behavior! Feel free to close this if nothing else needs to be done!
