### ISSUE TITLE
dvc push: unexpected error - local variable 'paths' referenced before assignment

### ISSUE THREAD

**Issue by ttajmajer-mellow** [iterative/dvc#8863]
# Bug Report

## Description

Error after performing "dvc push":
ERROR: unexpected error - local variable 'paths' referenced before assignment 

Using S3 bucket to store the data

### Reproduce

Problem started after running "dvc repro -f stage_name" and terminating it with ctrl-c, then running "dvc pull"
```
command: **dvc push -vv**
Trace:

(...)
2023-01-22 18:06:27,372 ERROR: unexpected error - local variable 'paths' referenced before assignment                                                                                         
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc/cli/__init__.py", line 184, in main
    ret = cmd.do_run()
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc/commands/data_sync.py", line 59, in run
    processed_files_count = self.repo.push(
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc/repo/__init__.py", line 66, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc/repo/push.py", line 92, in push
    result = self.cloud.push(
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc/data_cloud.py", line 142, in push
    return self.transfer(
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc/data_cloud.py", line 123, in transfer
    return transfer(src_odb, dest_odb, objs, **kwargs)
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc_data/hashfile/transfer.py", line 203, in transfer
    status = compare_status(
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc_data/hashfile/status.py", line 178, in compare_status
    dest_exists, dest_missing = status(
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc_data/hashfile/status.py", line 149, in status
    odb.oids_exist(hashes, jobs=jobs, progress=pbar.callback)
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc_objects/db.py", line 451, in oids_exist
    return list(oids & set(wrap_iter(remote_oids, callback)))
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc_objects/db.py", line 36, in wrap_iter
    for index, item in enumerate(iterable, start=1):
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc_objects/db.py", line 335, in _list_oids_traverse
    yield from self._list_oids(prefixes=traverse_prefixes, jobs=jobs)
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc_objects/db.py", line 233, in _list_oids
    for path in self._list_prefixes(prefixes=prefixes, jobs=jobs):
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc_objects/db.py", line 213, in _list_prefixes
    yield from self.fs.find(paths, batch_size=jobs)
  File "/home/ubuntu/experiments/env/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 658, in find
    for path in paths:
UnboundLocalError: local variable 'paths' referenced before assignment
------------------------------------------------------------
(...)
```
### Expected

Command executed succesfully

### Environment information

**Output of `dvc doctor`:**

DVC version: 2.42.0 (pip)
---------------------------------
Platform: Python 3.10.6 on Linux-5.15.0-1028-aws-x86_64-with-glibc2.35
Subprojects:
	dvc_data = 0.34.0
	dvc_objects = 0.18.1
	dvc_render = 0.0.17
	dvc_task = 0.1.11
	dvclive = 1.3.2
	scmrepo = 0.1.6
Supports:
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2023.1.0, boto3 = 1.24.59)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p1
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p1
Repo: dvc, gitpports:
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2023.1.0, boto3 = 1.24.59)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p1
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p1
Repo: dvc, git

**Additional Information (if any):**

**Comment by efiop** [comment]
Hi @ttajmajer-mellow

Please upgrade to 2.43.0 or downgrade to 2.41.1. There was a problem with one of our dependencies that is resolved now.
