### ISSUE TITLE
dvc exp show : unexpected error if config file has lists in it 

### ISSUE THREAD

**Issue by anasali90** [iterative/dvc#8877]
dvc exp show  would crash if there are parameters consisting of lists in yaml config file.
This happens only for newer versions of dvc : 2.42.0 and later versions. 
This bug doesn't show up on older versions like 2.41.1 and 2.40.0

### output of dvc exp show -v 
```
dvc exp show -v
2023-01-25 07:15:17,775 DEBUG: found refs for revs: {'ae52acfb4471b1efc5b7ed3aa3884c6add2d585e': 'exp1', '51f00e86d849926c12781cbd1326f0f6c57936e3': 'base_exps', '4529d76893006f85a2f86ca99ee42c1de54f2233': 'main'}
2023-01-25 07:15:17,930 ERROR: unexpected error - unsupported format string passed to list.__format__
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/cli/__init__.py", line 184, in main
  File "dvc/cli/command.py", line 26, in do_run
  File "dvc/commands/experiments/show.py", line 501, in run
  File "dvc/commands/experiments/show.py", line 347, in show_experiments
  File "dvc/commands/experiments/show.py", line 289, in experiments_table
  File "dvc/compare.py", line 80, in extend
  File "dvc/commands/experiments/show.py", line 153, in _collect_rows
  File "dvc/commands/experiments/show.py", line 246, in _extend_row
  File "dvc/compare.py", line 340, in _format_field
  File "dvc/compare.py", line 337, in _format
  File "dvc/compare.py", line 337, in <listcomp>
  File "dvc/compare.py", line 333, in _format
  File "dvc/compare.py", line 323, in _normalize_float
TypeError: unsupported format string passed to list.__format__
------------------------------------------------------------
2023-01-25 07:15:18,436 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-01-25 07:15:18,436 DEBUG: Removing '/home/runner/.KHmSvQgfVUPC7za7Rj2q3E.tmp'
2023-01-25 07:15:18,436 DEBUG: Removing '/home/runner/.KHmSvQgfVUPC7za7Rj2q3E.tmp'
2023-01-25 07:15:18,436 DEBUG: Removing '/home/runner/.KHmSvQgfVUPC7za7Rj2q3E.tmp'
2023-01-25 07:15:18,436 DEBUG: Removing '/home/runner/test-MLOps/.dvc/cache/.RciNVcyewYThkHzsNnKsga.tmp'
2023-01-25 07:15:18,438 DEBUG: Version info for developers:
DVC version: 2.43.1 (deb)
---------------------------------
Platform: Python 3.10.8 on Linux-5.15.0-58-generic-x86_64-with-glibc2.31
Subprojects:
	
Supports:
	azure (adlfs = 2023.1.0, knack = 0.10.1, azure-identity = 1.12.0),
	gdrive (pydrive2 = 1.15.0),
	gs (gcsfs = 2022.11.0),
	hdfs (fsspec = 2022.11.0, pyarrow = 10.0.1),
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	oss (ossfs = 2023.1.0),
	s3 (s3fs = 2022.11.0, boto3 = 1.24.59),
	ssh (sshfs = 2023.1.0),
	webdav (webdav4 = 0.9.8),
	webdavs (webdav4 = 0.9.8),
	webhdfs (fsspec = 2022.11.0)
Cache types: hardlink, symlink
Cache directory: overlay on overlay
Caches: local
Remotes: gdrive
Workspace directory: overlay on overlay
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-01-25 07:15:18,439 DEBUG: Analytics is enabled.
2023-01-25 07:15:18,440 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpbzq_qe25']'
2023-01-25 07:15:18,442 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpbzq_qe25']'

**Comment by dtrifiro** [comment]
Hi, by config file do you mean `dvc.yaml`? Can you provide an example?

**Comment by daavoo** [comment]
Pretty sure this is the same as https://github.com/iterative/dvc/issues/8891
