### ISSUE TITLE
pip install error: reflink

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#888]
Linux: `Amazon AMI`

```
$ sudo pip install --upgrade pip
...
$ pip install dvc
...
...
Collecting reflink==0.2.0 (from dvc)
  Using cached https://files.pythonhosted.org/packages/9a/50/3b5af06903ba93cf9064708350f3a7e4c350652f68e0e68e6d0dc9f6e608/reflink-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...

    Installed /mnt/tmp/pip-install-RB3MNn/reflink/.eggs/pytest_runner-4.2-py2.7.egg
    Searching for cffi
    Reading https://pypi.python.org/simple/cffi/
    Downloading https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz#sha256=e90f17980e6ab0f3c2f3730e56d1fe9bcba1891eeea58966e89d352492cc74f4
    Best match: cffi 1.11.5
    Processing cffi-1.11.5.tar.gz
    Writing /tmp/easy_install-LNyQWo/cffi-1.11.5/setup.cfg
    Running cffi-1.11.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-LNyQWo/cffi-1.11.5/egg-dist-tmp-Xco1Ml
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/tmp/pip-install-RB3MNn/reflink/setup.py", line 64, in <module>
        cffi_modules = ["reflink/native.py:ffibuilder"]
      File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 325, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 446, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 855, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1127, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1139, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 518, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 691, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 717, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 898, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1137, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1125, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /mnt/tmp/pip-install-RB3MNn/reflink/
```

**Comment by efiop** [comment]
Looks like there are no ffi headers on your machine. Could you please try installing ffi packages? I.e. with `apt-get install libffi libffi-dev`.

**Comment by dmpetrov** [comment]
It is pretty much the same issue as a video driver for graphviz.
Is there a way to get rid of this?

**Comment by efiop** [comment]
Graphviz doesn't need video drivers :) With pygraphviz installing graphviz itself was a problem on windows.

Ok, there are a few ways around it. I'll take a look today.
