### ISSUE TITLE
Why dvc cannot track and lose my experiment files?

### ISSUE THREAD

**Issue by erdiphd** [iterative/dvc#8905]
# Bug Report

**ERROR: unexpected error - unable to open database file**    

DVC is very cool for organizing the data and results from trainings. Unfortunately, whenever I want to experiment with DVC, I waste a lot of time attempting to understand DVC behavior and end up losing my data.Instead of DVC, I end up organizing my training results with git branches.However, if I could understand dvc exp clearly, it would be perfect to use. But as far as I see, It doesn't have stable behavior and leads to losing data, which makes it very risky to use.

I would like to give an example by sharing a video using a dummy script.

https://user-images.githubusercontent.com/81103451/215286543-8afec0fb-63cd-45c7-9d38-4be108d3457a.mp4

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```
```
dvc doctor
DVC version: 2.39.0 (deb)
---------------------------------
Platform: Python 3.10.9 on Linux-5.15.0-58-generic-x86_64-with-glibc2.31
Subprojects:
	
Supports:
	azure (adlfs = 2022.11.2, knack = 0.10.1, azure-identity = 1.12.0),
	gdrive (pydrive2 = 1.15.0),
	gs (gcsfs = 2022.11.0),
	hdfs (fsspec = 2022.11.0, pyarrow = 10.0.1),
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	oss (ossfs = 2023.1.0),
	s3 (s3fs = 2022.11.0, boto3 = 1.24.59),
	ssh (sshfs = 2022.6.0),
	webdav (webdav4 = 0.9.8),
	webdavs (webdav4 = 0.9.8),
	webhdfs (fsspec = 2022.11.0)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/sda2
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by dtrifiro** [comment]
I cannot reproduce using `dvc==2.39.0` (installed via pip/deb). Could you provide a full traceback by running `dvc exp apply test2 -v`?

**Comment by erdiphd** [comment]
```
hgg_force) erdi@erdi:~/Desktop/Storage/dvc_exp_test/code$ dvc exp apply test2 -v
2023-01-29 17:01:12,650 DEBUG: Found done task fa08a9fde2ead52a42870f1f53f13654d45f020f
2023-01-29 17:01:12,651 DEBUG: Found done task 051abb441c4a5a7fd40c63bff2b39f005c65aa15
2023-01-29 17:01:12,663 DEBUG: Stashing workspace
2023-01-29 17:01:12,681 DEBUG: Removing '/home/erdi/Desktop/Storage/dvc_exp_test/code/.dvc/tmp/repro.dat'
2023-01-29 17:01:12,702 ERROR: unexpected error - unable to open database file
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/cli/__init__.py", line 185, in main
  File "dvc/cli/command.py", line 22, in do_run
  File "dvc/commands/experiments/apply.py", line 14, in run
  File "dvc/repo/experiments/__init__.py", line 449, in apply
  File "dvc/repo/__init__.py", line 48, in wrapper
  File "dvc/repo/scm_context.py", line 156, in run
  File "dvc/repo/experiments/apply.py", line 77, in apply
  File "dvc/repo/__init__.py", line 48, in wrapper
  File "dvc/repo/checkout.py", line 87, in checkout
  File "dvc/repo/checkout.py", line 31, in _remove_unused_links
  File "dvc_data/hashfile/state.py", line 176, in get_unused_links
  File "diskcache/core.py", line 2356, in __enter__
  File "diskcache/core.py", line 623, in _con
sqlite3.OperationalError: unable to open database file
------------------------------------------------------------
2023-01-29 17:01:13,565 DEBUG: Version info for developers:
DVC version: 2.39.0 (deb)
---------------------------------
Platform: Python 3.10.9 on Linux-5.15.0-58-generic-x86_64-with-glibc2.31
Subprojects:

Supports:
        azure (adlfs = 2022.11.2, knack = 0.10.1, azure-identity = 1.12.0),
        gdrive (pydrive2 = 1.15.0),
        gs (gcsfs = 2022.11.0),
        hdfs (fsspec = 2022.11.0, pyarrow = 10.0.1),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        oss (ossfs = 2023.1.0),
        s3 (s3fs = 2022.11.0, boto3 = 1.24.59),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2022.11.0)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/sda2
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-01-29 17:01:13,566 DEBUG: Analytics is enabled.
2023-01-29 17:01:13,566 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpyxgf7kfc']'
2023-01-29 17:01:13,568 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpyxgf7kfc']'
```

**Comment by erdiphd** [comment]
[code.zip](https://github.com/iterative/dvc/files/10530223/code.zip)

Here are the codes. I am using **docker-compose**

**Comment by dtrifiro** [comment]
Can you install from `pip` and retry with the latest version?
