### ISSUE TITLE
cloud versioning: pulling a version-aware import-url dir fails

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8932]
# Bug Report

## Description

After doing `dvc import-url --version-aware`, a subsequent `dvc pull` fails.

### Reproduce

```bash
$ dvc import-url --version-aware s3://dave-sandbox-versioning/example-get-started-worktree/data
Importing 's3://dave-sandbox-versioning/example-get-started-worktree/data' -> 'data'

$ dvc push
Everything is up to date.

$ rm -rf data/ .dvc/cache

$ dvc pull -v
2023-02-01 14:53:44,185 DEBUG: v2.43.2.dev43+gae92154ce.d20230201, CPython 3.10.2 on macOS-13.1-arm64-arm-64bit
2023-02-01 14:53:44,185 DEBUG: command: /Users/dave/miniforge3/envs/dvc/bin/dvc pull -v
2023-02-01 14:53:44,486 DEBUG: Preparing to transfer data from '/Users/dave/repo/.dvc/../../dvcremote' to '/Users/dave/repo/.dvc/cache'
2023-02-01 14:53:44,486 DEBUG: Preparing to collect status from '/Users/dave/repo/.dvc/cache'
2023-02-01 14:53:44,486 DEBUG: Collecting status from '/Users/dave/repo/.dvc/cache'
2023-02-01 14:53:44,487 DEBUG: Preparing to collect status from '/Users/dave/repo/.dvc/../../dvcremote'
2023-02-01 14:53:44,487 DEBUG: Collecting status from '/Users/dave/repo/.dvc/../../dvcremote'
2023-02-01 14:53:44,487 DEBUG: Querying 1 oids via object_exists
2023-02-01 14:53:44,488 WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:
name: None, md5: 3ce9c43d5bead55bee0d3752fc1d68c5.dir
2023-02-01 14:53:45,292 DEBUG: built tree 'object 1e86e486d807f5fe511c7173f8d9b101.dir'
2023-02-01 14:53:47,272 ERROR: unexpected error
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dave/Code/dvc/dvc/cli/__init__.py", line 207, in main
    ret = cmd.do_run()
  File "/Users/dave/Code/dvc/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/Users/dave/Code/dvc/dvc/commands/data_sync.py", line 31, in run
    stats = self.repo.pull(
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 66, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/pull.py", line 34, in pull
    processed_files_count = self.fetch(
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 66, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/fetch.py", line 111, in fetch
    imported = save_imports(
  File "/Users/dave/Code/dvc/dvc/repo/imports.py", line 120, in save_imports
    md5(data_view)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_data/index/save.py", line 24, in md5
    assert entry.fs
AssertionError
------------------------------------------------------------
2023-02-01 14:53:47,914 DEBUG: Removing '/Users/dave/.7BRrM2BffnKpDr4sGFkDb4.tmp'
2023-02-01 14:53:47,915 DEBUG: Removing '/Users/dave/.7BRrM2BffnKpDr4sGFkDb4.tmp'
2023-02-01 14:53:47,915 DEBUG: Removing '/Users/dave/.7BRrM2BffnKpDr4sGFkDb4.tmp'
2023-02-01 14:53:47,915 DEBUG: Removing '/Users/dave/repo/.dvc/cache/.bG3MXm3o73Kt55ooRXgZR2.tmp'
2023-02-01 14:53:47,916 DEBUG: Version info for developers:
DVC version: 2.43.2.dev43+gae92154ce.d20230201
----------------------------------------------
Platform: Python 3.10.2 on macOS-13.1-arm64-arm-64bit
Subprojects:
        dvc_data = 0.36.2
        dvc_objects = 0.19.0
        dvc_render = 0.0.17
        dvc_task = 0.1.11
        dvclive = 1.3.5.dev1+g4ff495a.d20230131
        scmrepo = 0.1.7
Supports:
        azure (adlfs = 2022.9.1, knack = 0.9.0, azure-identity = 1.7.1),
        gdrive (pydrive2 = 1.15.0),
        gs (gcsfs = 2022.11.0),
        hdfs (fsspec = 2022.11.0+0.gacad158.dirty, pyarrow = 7.0.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2022.11.0+6.g804057f.dirty, boto3 = 1.24.59),
        ssh (sshfs = 2023.1.0),
        webdav (webdav4 = 0.9.4),
        webdavs (webdav4 = 0.9.4),
        webhdfs (fsspec = 2022.11.0+0.gacad158.dirty)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: local
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-02-01 14:53:47,917 DEBUG: Analytics is disabled.
```

### Expected

The `.dir` file shouldn't be required to complete the operation. Can we drop it or make `pull` succeed (recreate it) even if it's missing?

**Comment by dberenbaum** [comment]
This breaks a pretty essential workflow of using cloud versioning to track imported files.

**Comment by pmrowla** [comment]
This is failling because one of the index entries doesn't have a source filesystem set
```
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_data/index/save.py", line 24, in md5
    assert entry.fs
AssertionError
```

The warning about the .dir file is the generic warning we generate any time there is a missing cache file, but suppressing that for cloud versioned remotes is a separate UI issue

**Comment by dberenbaum** [comment]
@pmrowla `dvc pull` still fails for me -- now it fails even if the data exists in the cache and workspace:

```bash
$ dvc import-url --version-aware s3://dave-sandbox-versioning/example-get-started-worktree/data
Importing 's3://dave-sandbox-versioning/example-get-started-worktree/data' -> 'data'

To track the changes with git, run:

        git add data.dvc .gitignore

To enable auto staging, run:

        dvc config core.autostage true

$ dvc pull -v
2023-02-03 15:42:43,139 DEBUG: v2.43.2.dev53+g5d2701341, CPython 3.10.2 on macOS-13.1-arm64-arm-64bit
2023-02-03 15:42:43,140 DEBUG: command: /Users/dave/miniforge3/envs/dvc/bin/dvc pull -v
2023-02-03 15:42:43,436 DEBUG: Preparing to transfer data from '/Users/dave/repo/.dvc/../../dvcremote' to '/Users/dave/repo/.dvc/cache'
2023-02-03 15:42:43,436 DEBUG: Preparing to collect status from '/Users/dave/repo/.dvc/cache'
2023-02-03 15:42:43,436 DEBUG: Collecting status from '/Users/dave/repo/.dvc/cache'
2023-02-03 15:42:43,437 ERROR: unexpected error - 'DataIndex' object has no attribute 'odb_map'
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dave/Code/dvc/dvc/cli/__init__.py", line 207, in main
    ret = cmd.do_run()
  File "/Users/dave/Code/dvc/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/Users/dave/Code/dvc/dvc/commands/data_sync.py", line 31, in run
    stats = self.repo.pull(
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 66, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/pull.py", line 34, in pull
    processed_files_count = self.fetch(
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 66, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/fetch.py", line 111, in fetch
    imported = save_imports(
  File "/Users/dave/Code/dvc/dvc/repo/imports.py", line 109, in save_imports
    data_view = unfetched.data["repo"]
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/Users/dave/Code/dvc/dvc/repo/index.py", line 504, in data
    for workspace, data_index in self._index.data.items():
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/Users/dave/Code/dvc/dvc/repo/index.py", line 307, in data
    data_index.odb_map[key] = out.odb
AttributeError: 'DataIndex' object has no attribute 'odb_map'
------------------------------------------------------------
2023-02-03 15:42:44,159 DEBUG: Removing '/Users/dave/.mZGsBnSFrmAXopxcrzgsH3.tmp'
2023-02-03 15:42:44,160 DEBUG: Removing '/Users/dave/.mZGsBnSFrmAXopxcrzgsH3.tmp'
2023-02-03 15:42:44,160 DEBUG: Removing '/Users/dave/.mZGsBnSFrmAXopxcrzgsH3.tmp'
2023-02-03 15:42:44,160 DEBUG: Removing '/Users/dave/repo/.dvc/cache/.oCftZHof4EALTsA3GYmDSk.tmp'
2023-02-03 15:42:44,161 DEBUG: Version info for developers:
DVC version: 2.43.2.dev53+g5d2701341
------------------------------------
Platform: Python 3.10.2 on macOS-13.1-arm64-arm-64bit
Subprojects:
        dvc_data = 0.36.2
        dvc_objects = 0.19.0
        dvc_render = 0.0.18.dev8+g2606ca9
        dvc_task = 0.1.11
        dvclive = 1.4.1.dev9+g9ca202e.d20230203
        scmrepo = 0.1.7
Supports:
        azure (adlfs = 2022.9.1, knack = 0.9.0, azure-identity = 1.7.1),
        gdrive (pydrive2 = 1.15.0),
        gs (gcsfs = 2022.11.0),
        hdfs (fsspec = 2022.11.0+0.gacad158.dirty, pyarrow = 7.0.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2022.11.0+6.g804057f.dirty, boto3 = 1.24.59),
        ssh (sshfs = 2023.1.0),
        webdav (webdav4 = 0.9.4),
        webdavs (webdav4 = 0.9.4),
        webhdfs (fsspec = 2022.11.0+0.gacad158.dirty)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: local
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-02-03 15:42:44,162 DEBUG: Analytics is disabled.
```

**Comment by dberenbaum** [comment]
Sorry for the noise here. LGTM.
