### ISSUE TITLE
File names containing [ ] in s3 causes import-url/update to fail

### ISSUE THREAD

**Issue by hemker** [iterative/dvc#8964]
Hey,
as discussed with @rlamy in discord, there seems to be a bug when there are file names containing `[...]` in the s3 storage.

The output I got is:
```
2023-02-01 19:46:21,703 DEBUG: Removing output 'data/inbox' of stage: 'data/inbox.dvc'.
2023-02-01 19:46:21,704 DEBUG: Removing '/home/user/project/data/inbox'
Importing 'remote://inbox' -> 'data/inbox'
2023-02-01 19:46:21,704 DEBUG: Computed stage: 'data/inbox.dvc' md5: 'c2fd66c6ef8f74858a8b197f75b67f92'
2023-02-01 19:46:21,704 DEBUG: 'md5' of stage: 'data/inbox.dvc' changed.
2023-02-01 19:46:26,084 DEBUG: built tree 'object 23b84f911a47f0a97a4ba0e0ffa95740.dir'                                                                                                                              
2023-02-01 19:46:26,818 ERROR: unexpected error
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/project/env/lib/python3.10/site-packages/dvc/cli/__init__.py", line 184, in main
    ret = cmd.do_run()
  File "/home/user/project/env/lib/python3.10/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/home/user/project/env/lib/python3.10/site-packages/dvc/commands/imp_url.py", line 15, in run
    self.repo.imp_url(
  File "/home/user/project/env/lib/python3.10/site-packages/dvc/repo/__init__.py", line 66, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/user/project/env/lib/python3.10/site-packages/dvc/repo/scm_context.py", line 159, in run
    return method(repo, *args, **kw)
  File "/home/user/project/env/lib/python3.10/site-packages/dvc/repo/imp_url.py", line 99, in imp_url
    stage.run(jobs=jobs, no_download=no_download)
  File "/home/user/project/env/lib/python3.10/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/user/project/env/lib/python3.10/site-packages/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
  File "/home/user/project/env/lib/python3.10/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/user/project/env/lib/python3.10/site-packages/dvc/stage/__init__.py", line 600, in run
    self._sync_import(
  File "/home/user/project/env/lib/python3.10/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/user/project/env/lib/python3.10/site-packages/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
  File "/home/user/project/env/lib/python3.10/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/user/project/env/lib/python3.10/site-packages/dvc/stage/__init__.py", line 638, in _sync_import
    sync_import(self, dry, force, jobs, no_download)
  File "/home/user/project/env/lib/python3.10/site-packages/dvc/stage/imports.py", line 61, in sync_import
    stage.deps[0].download(
  File "/home/user/project/env/lib/python3.10/site-packages/dvc/dependency/base.py", line 55, in download
    fs_download(self.fs, self.fs_path, to, jobs=jobs)
  File "/home/user/project/env/lib/python3.10/site-packages/dvc/fs/__init__.py", line 56, in download
    fs.get(fs_path, to.fs_path, batch_size=jobs, callback=cb)
  File "/home/user/project/env/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 648, in get
    return self.fs.get(
  File "/home/user/project/env/lib/python3.10/site-packages/fsspec/asyn.py", line 114, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/user/project/env/lib/python3.10/site-packages/fsspec/asyn.py", line 99, in sync
    raise return_result
  File "/home/user/project/env/lib/python3.10/site-packages/fsspec/asyn.py", line 54, in _runner
    result[0] = await coro
  File "/home/user/project/env/lib/python3.10/site-packages/fsspec/asyn.py", line 532, in _get
    lpaths = other_paths(rpaths, lpath)
  File "/home/user/project/env/lib/python3.10/site-packages/fsspec/utils.py", line 379, in other_paths
    assert len(paths) == len(path2)
AssertionError
------------------------------------------------------------
2023-02-01 19:46:26,833 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-02-01 19:46:26,833 DEBUG: Removing '/home/user/project/.92SaAGpcztPmMtkbzv5s7s.tmp'
2023-02-01 19:46:26,833 DEBUG: Removing '/home/user/project/.92SaAGpcztPmMtkbzv5s7s.tmp'
2023-02-01 19:46:26,833 DEBUG: Removing '/home/user/project/.92SaAGpcztPmMtkbzv5s7s.tmp'
2023-02-01 19:46:26,833 DEBUG: Removing '/home/user/project/.dvc/cache/.UbwbziMSkV6Uh7xhVnN4ZL.tmp'
2023-02-01 19:46:26,837 DEBUG: Version info for developers:
DVC version: 2.43.1 (pip)
---------------------------------
Platform: Python 3.10.6 on Linux-5.15.0-58-generic-x86_64-with-glibc2.35
Subprojects:
	dvc_data = 0.35.1
	dvc_objects = 0.19.0
	dvc_render = 0.0.17
	dvc_task = 0.1.11
	dvclive = 1.3.4
	scmrepo = 0.1.6
Supports:
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2023.1.0, boto3 = 1.24.59)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p3
Caches: local
Remotes: s3, s3, s3
Workspace directory: ext4 on /dev/nvme0n1p3
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-02-01 19:46:26,838 DEBUG: Analytics is enabled.
2023-02-01 19:46:26,867 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmp0lwdewvk']'
2023-02-01 19:46:26,868 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmp0lwdewvk']'
```

The discussion with a log attached containing some sample file names that crash at the line above can be found here:
https://discord.com/channels/485586884165107732/1070416529688100915/1071049750796832888

**Comment by hemker** [comment]
@rlamy Any news on this? It still kinda breaks our workflow :( If you can point me a bit to the right parts of dvc I can also take a look into that bug.

**Comment by pmrowla** [comment]
related: https://github.com/fsspec/filesystem_spec/issues/838
