### ISSUE TITLE
pull: 'NoneType' object has no attribute 'get_extra_info'

### ISSUE THREAD

**Issue by pckhoi** [iterative/dvc#9002]
# Bug Report

## Description

All of a sudden, whenever I run `dvc pull`, I get `ERROR: unexpected error - 'NoneType' object has no attribute 'get_extra_info'`. Here's the full output when I run `dvc pull --verbose`:

```bash
$ dvc pull --verbose
2023-02-10 06:50:47,167 DEBUG: v2.43.4 (pip), CPython 3.9.13 on macOS-12.5-x86_64-i386-64bit
2023-02-10 06:50:47,168 DEBUG: command: /Users/khoipham/.pyenv/versions/3.9.13/bin/dvc pull --verbose
2023-02-10 06:50:47,782 DEBUG: Preparing to transfer data from 'llead-dvc' to '/Users/khoipham/projects/PPACT/.dvc/cache'
2023-02-10 06:50:47,782 DEBUG: Preparing to collect status from '/Users/khoipham/projects/PPACT/.dvc/cache'
2023-02-10 06:50:47,783 DEBUG: Collecting status from '/Users/khoipham/projects/PPACT/.dvc/cache'
2023-02-10 06:50:47,784 DEBUG: Preparing to collect status from 'llead-dvc'                                                                                                                              
2023-02-10 06:50:47,784 DEBUG: Collecting status from 'llead-dvc'
2023-02-10 06:50:47,784 DEBUG: Querying 1 oids via object_exists                                                                                                                                         
2023-02-10 06:50:48,156 ERROR: unexpected error - 'NoneType' object has no attribute 'get_extra_info'                                                                                                    
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/output.py", line 1009, in get_dir_cache
    ocheck(self.odb, obj)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc_data/hashfile/__init__.py", line 20, in check
    odb.check(obj.oid, **kwargs)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc_data/hashfile/db/__init__.py", line 183, in check
    _, actual = hash_file(obj.path, obj.fs, self.hash_name, self.state)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc_data/hashfile/hash.py", line 178, in hash_file
    hash_value, meta = _hash_file(path, fs, name, callback=cb, info=info)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc_data/hashfile/hash.py", line 121, in _hash_file
    info = info or fs.info(path)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc_objects/fs/base.py", line 481, in info
    return self.fs.info(path, **kwargs)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc_objects/fs/local.py", line 42, in info
    return self.fs.info(path)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/fsspec/implementations/local.py", line 83, in info
    out = os.stat(path, follow_symlinks=False)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/khoipham/projects/PPACT/.dvc/cache/f4/021f23b490aed8fb0beaa2412140df.dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/cli/__init__.py", line 206, in main
    ret = cmd.do_run()
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/commands/data_sync.py", line 31, in run
    stats = self.repo.pull(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/repo/__init__.py", line 57, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/repo/pull.py", line 34, in pull
    processed_files_count = self.fetch(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/repo/__init__.py", line 57, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/repo/fetch.py", line 86, in fetch
    d, f = _fetch(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/repo/fetch.py", line 142, in _fetch
    used = repo.used_objs(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/repo/__init__.py", line 449, in used_objs
    for odb, objs in self.index.used_objs(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/repo/index.py", line 370, in used_objs
    for odb, objs in stage.get_used_objs(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/stage/__init__.py", line 722, in get_used_objs
    for odb, objs in out.get_used_objs(*args, **kwargs).items():
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/output.py", line 1098, in get_used_objs
    obj = self._collect_used_dir_cache(**kwargs)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/output.py", line 1031, in _collect_used_dir_cache
    self.get_dir_cache(jobs=jobs, remote=remote)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/output.py", line 1013, in get_dir_cache
    self.repo.cloud.pull([obj.hash_info], **kwargs)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/data_cloud.py", line 176, in pull
    return self.transfer(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc/data_cloud.py", line 130, in transfer
    return transfer(src_odb, dest_odb, objs, **kwargs)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc_data/hashfile/transfer.py", line 203, in transfer
    status = compare_status(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc_data/hashfile/status.py", line 189, in compare_status
    src_exists, src_missing = status(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc_data/hashfile/status.py", line 134, in status
    exists = hashes.intersection(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc_data/hashfile/status.py", line 55, in _indexed_dir_hashes
    dir_exists.update(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc_objects/db.py", line 357, in list_oids_exists
    in_remote = self.fs.exists(paths, batch_size=jobs)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc_objects/fs/base.py", line 345, in exists
    return fut.result()
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/dvc_objects/executors.py", line 134, in batch_coros
    result = fut.result()
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/fsspec/asyn.py", line 588, in _exists
    await self._info(path)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/gcsfs/core.py", line 782, in _info
    exact = await self._get_object(path)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/gcsfs/core.py", line 495, in _get_object
    res = await self._call(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/gcsfs/core.py", line 422, in _call
    status, headers, info, contents = await self._request(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/decorator.py", line 221, in fun
    return await caller(func, *(extras + args), **kw)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/gcsfs/retry.py", line 115, in retry_request
    return await func(*args, **kwargs)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/gcsfs/core.py", line 400, in _request
    async with self.session.request(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/aiohttp/connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/aiohttp/connector.py", line 1325, in _create_proxy_connection
    return await self._start_tls_connection(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/aiohttp/connector.py", line 1124, in _start_tls_connection
    tls_proto.connection_made(
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/aiohttp/base_protocol.py", line 58, in connection_made
    tcp_nodelay(tr, True)
  File "/Users/khoipham/.pyenv/versions/3.9.13/lib/python3.9/site-packages/aiohttp/tcp_helpers.py", line 25, in tcp_nodelay
    sock = transport.get_extra_info("socket")
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
------------------------------------------------------------
2023-02-10 06:50:48,242 DEBUG: Version info for developers:
DVC version: 2.43.4 (pip)
-------------------------
Platform: Python 3.9.13 on macOS-12.5-x86_64-i386-64bit
Subprojects:
        dvc_data = 0.37.8
        dvc_objects = 0.19.3
        dvc_render = 0.1.0
        dvc_task = 0.1.11
        dvclive = 2.0.2
        scmrepo = 0.1.7
Supports:
        gs (gcsfs = 2022.11.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: gs
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-02-10 06:50:48,244 DEBUG: Analytics is enabled.
2023-02-10 06:50:48,325 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/xl/26mh73ls1zz_pqcxk3v21kgm0000gn/T/tmpn3xb5eyj']'
2023-02-10 06:50:48,326 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/xl/26mh73ls1zz_pqcxk3v21kgm0000gn/T/tmpn3xb5eyj']'
```

### Reproduce

Not sure if this can even be reliably reproduced on other machines. My colleague cannot reproduce this error on their computer so there's probably something different about my computer.

### Expected

It should work without error.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.43.4 (pip)
-------------------------
Platform: Python 3.9.13 on macOS-12.5-x86_64-i386-64bit
Subprojects:
        dvc_data = 0.37.8
        dvc_objects = 0.19.3
        dvc_render = 0.1.0
        dvc_task = 0.1.11
        dvclive = 2.0.2
        scmrepo = 0.1.7
Supports:
        gs (gcsfs = 2022.11.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1s1
Caches: local
Remotes: gs
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git
```

**Comment by skshetry** [comment]
@pckhoi, are you using proxy by any chance?

**Comment by pckhoi** [comment]
I think that is it. It is pulling fine without proxy. Thanks for the help!
