### ISSUE TITLE
`dvc.repo.Repo.dvcfs.get`: AWS Codecommit credential helper and cloning

### ISSUE THREAD

**Issue by dogeplusplus** [iterative/dvc#9007]
# Bug Report

## Description

I am trying to use DVC in an AWS setting where services like virtual machines require access to my DVC dataset registry hosted on AWS Codecommit as the SCM tool. The reason it's on codecommit is around trying to get git access to the DVC repo without having to bake HTTPS/SSH credentials into docker containers/instances, by using IAM roles.

There is a method of git cloning a Codecommit repository without keys by using the AWS credential-helper. This involves baking this information into `.gitconfig`:

```
[credential]
        helper = !aws codecommit credential-helper $@
        UseHttpPath = true
```

https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-https-unixes.html

Provided my instance has the AWS Code Commit IAM permissions, and I have set the credential helper in `.gitconfig`, it should clone as if I used the regular git clone command. This seems to work with `git clone` but not the cloning function in the API.

Either dvc repo is not picking up this git config information, or there is some AWS magic that happens when git cloning with the https url. 

### Reproduce

```python
import os
from dvc.repo import Repo


# neither URL seems to work
# https url
repository = "https://git-codecommit.eu-west-2.amazonaws.com/v1/repos/my-repository"
# grc url
repository = "codecommit::eu-west-2://my-repository"

version = "master"
dataset = "dataset_name"
dataset_folder = "dest"
with Repo.open(repository, rev=version) as repo:
    repo.dvcfs.get(dataset, str(dataset_folder), recursive=True, batch_size=os.cpu_count() * 4)
```

### Expected

I expect I should be able to clone the repo using the API with the https URL, `.gitconfig` set up with the codecommit credential helper, and the IAM role for codecommit.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

```console
DVC version: 2.44.0 (pip)
-------------------------
Platform: Python 3.10.6 on Linux-5.15.0-1028-aws-x86_64-with-glibc2.35
Subprojects:
        dvc_data = 0.39.3
        dvc_objects = 0.19.3
        dvc_render = 0.1.1
        dvc_task = 0.1.11
        dvclive = 2.0.2
        scmrepo = 0.1.9
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
```

**Additional Information (if any):**

Stack trace for `dvcfs.get` with HTTPS url:
```


Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 200, in clone
    repo = clone_from()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dulwich/porcelain.py", line 563, in clone
    return client.clone(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dulwich/client.py", line 756, in clone
    result = self.fetch(path, target, progress=progress, depth=depth)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dulwich/client.py", line 833, in fetch
    result = self.fetch_pack(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dulwich/client.py", line 2136, in fetch_pack
    refs, server_capabilities, url = self._discover_references(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dulwich/client.py", line 1992, in _discover_references
    resp, read = self._http_request(url, headers)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dulwich/client.py", line 2276, in _http_request
    raise HTTPUnauthorized(resp.headers.get("WWW-Authenticate"), url)
dulwich.client.HTTPUnauthorized: No valid credentials provided

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dvc/scm.py", line 180, in clone
    git = Git.clone(url, to_path, progress=pbar.update_git, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 135, in clone
    backend.clone(url, to_path, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 203, in clone
    raise CloneError(url, to_path) from exc
scmrepo.exceptions.CloneError: Failed to clone repo 'https://git-codecommit.eu-west-2.amazonaws.com/v1/repos/my-repository' to '/tmp/tmp603966rudvc-clone'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/get_repo.py", line 21, in get_dataset_dvc
    with Repo.open(repository, rev=version) as repo:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dvc/external_repo.py", line 45, in external_repo
    path = _cached_clone(url, rev, for_write=for_write)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dvc/external_repo.py", line 173, in _cached_clone
    clone_path, shallow = _clone_default_branch(url, rev, for_write=for_write)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/funcy/flow.py", line 274, in wrap_with
    return call()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dvc/external_repo.py", line 241, in _clone_default_branch
    git = clone(url, clone_path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dvc/scm.py", line 185, in clone
    raise CloneError("SCM error") from exc
dvc.scm.CloneError: SCM error
```

Stack trace for codecommit URL:
```

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 200, in clone
    repo = clone_from()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dulwich/porcelain.py", line 563, in clone
    return client.clone(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dulwich/client.py", line 756, in clone
    result = self.fetch(path, target, progress=progress, depth=depth)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dulwich/client.py", line 833, in fetch
    result = self.fetch_pack(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dulwich/client.py", line 1149, in fetch_pack
    proto, can_read, stderr = self._connect(b"upload-pack", path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dulwich/client.py", line 1798, in _connect
    con = self.ssh_vendor.run_command(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fsspec/asyn.py", line 114, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fsspec/asyn.py", line 99, in sync
    raise return_result
  File "/home/ubuntu/.local/lib/python3.10/site-packages/fsspec/asyn.py", line 54, in _runner
    result[0] = await coro
  File "/home/ubuntu/.local/lib/python3.10/site-packages/scmrepo/git/backend/dulwich/asyncssh_vendor.py", line 159, in _run_command
    conn = await asyncssh.connect(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/asyncssh/connection.py", line 8047, in connect
    return await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/home/ubuntu/.local/lib/python3.10/site-packages/asyncssh/connection.py", line 437, in _connect
    _, session = await loop.create_connection(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1025, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1404, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/dvc/scm.py", line 180, in clone
    git = Git.clone(url, to_path, progress=pbar.update_git, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 135, in clone
    backend.clone(url, to_path, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 203, in clone
    raise CloneError(url, to_path) from exc
scmrepo.exceptions.CloneError: Failed to clone repo 'codecommit::eu-west-2://my-repository' to '/tmp/tmpnn6vctlvdvc-clone'
```

**Comment by skshetry** [comment]
Hi, what kind of output do you get when you run:
```console
aws codecommit credential-helper get << EOF
protocol=https
host=git-codecommit.eu-west-2.amazonaws.com
EOF
```

Please remove secrets/confidential data, I am mostly interested in the output format. 
We currently expect output like follows (i.e. username and password together):
```console
username=<username>
password=<token>
```

If you can, it'd be great to add a breakpoint here and see what we are getting:
https://github.com/iterative/scmrepo/blob/4eac7a9adddcb64d60fc109237ee27f055ecdf72/src/scmrepo/git/backend/dulwich/credentials.py#L179

Thanks.

**Comment by dogeplusplus** [comment]
With the first output I only get this. I don't get any `username=` or `password=` sections
```

'path'
```

Regarding the breakpoint, I added it to the scm installation in my site-packages, but `dvcfs.get` doesn't seem to touch this try block.

**Comment by skshetry** [comment]
Try adding a breakpoint around here: https://github.com/iterative/scmrepo/blob/4eac7a9adddcb64d60fc109237ee27f055ecdf72/src/scmrepo/git/backend/dulwich/__init__.py#L182

**Comment by dogeplusplus** [comment]
```python
183  ->	            clone_from = partial(
184  	                git_clone,
185  	                url,
186  	                target=to_path,
187  	                errstream=(
188  	                    DulwichProgressReporter(progress) if progress else NoneStream()
```
```
url = 'https://git-codecommit.eu-west-2.amazonaws.com/v1/repos/my-repository'
to_path = '/tmp/tmpb49qoj19dvc-clone'
progress = <bound method TqdmGit.update_git of <dvc.scm.TqdmGit object at 0x7f72b91f28c0>>
git_clone = <function clone at 0x7f72b8be7490>
```

second part:

```python
 27  	        if not username:
 28  	            try:
 29  	                import pdb; pdb.set_trace()
 30  ->	                helper_username, helper_password = get_credentials_from_helper(
 31  	                    base_url, config or StackedConfig.default()
 32  	                )
 33  	            except CredentialNotFoundError:
 34  	                pass
```

```
url = 'https://git-codecommit.eu-west-2.amazonaws.com/v1/repos/my-repository'
config = <StackedConfig for [ConfigFile(<dulwich.config.CaseInsensitiveOrderedMultiDict object at 0x7f24418894e0>)]>
```

Raises the `CredentialNotFoundError`. Looking at the `url_match_credential_sections` it seems to always return an empty list for each conf backend.

**Comment by skshetry** [comment]
Hi, can you try setting those in `~/.gitconfig` globally instead?

**Comment by dogeplusplus** [comment]
So I've tried to set this locally with something along the following lines but no luck so far. Unless I'm supposed to store it in `.git-credentials` then I'm not sure what I should be doing. Apologies I'm not too savvy with `git-credentials` in general:
```
[credential]
    username=output-from-aws-codecommit-credential-helper-get
    password=output-from-aws-codecommit-credential-helper-get
```

Happy to experiment with more things with a bit more guidance to get a proper fix. But for those attempting a similar thing, I think a workaround is to clone the DVC repo hosted on Codecommit just using IAM and just your bog standard `git clone`, and then use `dvc get-url` to point to the `.dvc` files now on the local filesystem of the instance:

```
git clone https://git-codecommit.eu-west-2.amazonaws.com/v1/repos/my-repository
# or
git clone codecommit::eu-west-2://my-repository
```

```
dvc get-url /path/to/dvc-repo/file-or-directory dest
```

**Comment by skshetry** [comment]
Hi, do you have it set in `~/.gitconfig`? I don't think you need to specify `password` inside `[credential]`.

Also, if your `git clone` works, then `dvc` should work too. There was a bug recently, could you please try updating to 2.45.0 and see if it works?

**Comment by dogeplusplus** [comment]
I did upgrade to 2.45.0 yesterday but it seems unrelated to those issues. I tried setting he username in both `~/.gitconfig` and `~/.git-credentials`, after entering the password manually as outputted by:
```
echo -e "protocol=https\npath=/v1/repos/myrepo\nhost=git-codecommit.eu-west-2.amazonaws.com" | aws codecommit credential-helper get
```
I get 403'ed when I `git clone`. I can clone fine if I just use the credential helper as listed in the AWS docs, and `dvc get` does work after the credential helper has stored the username/password in my osxkeychain (only after I do a git clone). But I would like it to work without having to git clone it myself manually.

**Comment by skshetry** [comment]
> ```
> git clone https://git-codecommit.eu-west-2.amazonaws.com/v1/repos/my-repository #works, > credentials stored in osxkeychain
> ```

So, does `git clone` here ask for your username/password?

**Comment by dogeplusplus** [comment]
If I set the username manually in gitconfig manually, yes. But then I enter the password and get 403'ed. If use the credential helper it doesn't ask for it and clones normally.

**Comment by mattlbeck** [comment]
Looks like I have hit the same issue. I am working within an EC2 with a remote url to a codecommit origin in the form https://git-codecommit.eu-west-2.amazonaws.com/v1/repos/my-repository. Credential helper is set in `.gitconfig` exactly as @dogeplusplus has it. Git can communicate with the remote just fine, but `dvc exp push origin ...` will ask me to supply a password, so seemingly ignoring the credential helper.

**Comment by pmrowla** [comment]
@mattlbeck can you please try installing that patch in your DVC environment (on the EC2 instance) and then retry `dvc exp push`

```
pip install git+https://github.com/iterative/scmrepo.git@refs/pull/231/merge#egg=scmrepo
```

**Comment by mattlbeck** [comment]
Thanks @pmrowla there's a different error now (progress!)

```
ERROR: unexpected error - unexpected http resp 403 for https://git-codecommit.eu-west-2.amazonaws.com/v1/repos/myrepo/info/refs?service=git-receive-pack`
```

**Comment by pmrowla** [comment]
@mattlbeck can you please use `dvc exp push -v` and include the longer traceback so we can see where the operation is actually failing

**Comment by pmrowla** [comment]
@mattlbeck please retry with the latest version of the PR (you may need to do `pip uninstall scmrepo` and then re-install it)

**Comment by pmrowla** [comment]
Remaining issue was that amazon's credential helper expects URL's formatted in a very specific format with regard to leading & trailing slashes in certain paths, and does not sanitize them itself. When passing URL's with a trailing slash it will end up causing the server-side signature verification to fail

**Comment by mattlbeck** [comment]
All fixed now! 💯
