### ISSUE TITLE
pull: pulling from private github dataregistry repo with git credential helper not working anymore

### ISSUE THREAD

**Issue by bakaleks** [iterative/dvc#9016]
# Bug Report

## Description
With latest 2.44.0 version 'dvc pull' no longer works when pulling assets from private GitHub repo. Using git credential helper for authentication.

### Reproduce
```console
$ dvc pull -v
2023-02-13 15:02:05,305 DEBUG: v2.44.0 (deb), CPython 3.10.8 on Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-glibc2.31
2023-02-13 15:02:05,305 DEBUG: command: pull -v
2023-02-13 15:02:06,332 DEBUG: Creating external repo https://github.com/company/repo.git@4673682286885bda923460f92cc829602
2023-02-13 15:02:06,332 DEBUG: erepo: git clone 'https://github.com/company/repo.git' to a temporary dir
2023-02-13 15:02:11,410 ERROR: unexpected error - Git failed to fetch ref from 'https://github.com/company/repo.git': remote authentication required but no callback set
Traceback (most recent call last):
  File "funcy/flow.py", line 112, in reraise
  File "scmrepo/git/backend/pygit2.py", line 508, in fetch_refspecs
  File "pygit2/remote.py", line 146, in fetch
  File "pygit2/callbacks.py", line 98, in check_error
  File "pygit2/errors.py", line 65, in check_error
_pygit2.GitError: remote authentication required but no callback set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dvc/cli/__init__.py", line 205, in main
  File "dvc/cli/command.py", line 26, in do_run
  File "dvc/commands/data_sync.py", line 31, in run
  File "dvc/repo/__init__.py", line 57, in wrapper
  File "dvc/repo/pull.py", line 34, in pull
  File "dvc/repo/__init__.py", line 57, in wrapper
  File "dvc/repo/fetch.py", line 86, in fetch
  File "dvc/repo/fetch.py", line 142, in _fetch
  File "dvc/repo/__init__.py", line 449, in used_objs
  File "dvc/repo/index.py", line 385, in used_objs
  File "dvc/stage/__init__.py", line 722, in get_used_objs
  File "dvc/output.py", line 1074, in get_used_objs
  File "dvc/output.py", line 1133, in get_used_external
  File "dvc/dependency/repo.py", line 102, in get_used_objs
  File "dvc/dependency/repo.py", line 116, in _get_used_and_obj
  File "contextlib.py", line 135, in __enter__
  File "dvc/external_repo.py", line 45, in external_repo
  File "dvc/external_repo.py", line 173, in _cached_clone
  File "funcy/decorators.py", line 45, in wrapper
  File "funcy/flow.py", line 274, in wrap_with
  File "funcy/decorators.py", line 66, in __call__
  File "dvc/external_repo.py", line 241, in _clone_default_branch
  File "dvc/scm.py", line 182, in clone
  File "dvc/repo/experiments/utils.py", line 288, in fetch_all_exps
  File "scmrepo/git/__init__.py", line 279, in _backend_func
  File "scmrepo/git/backend/pygit2.py", line 504, in fetch_refspecs
  File "contextlib.py", line 153, in __exit__
  File "funcy/flow.py", line 116, in reraise
  File "<string>", line 3, in raise_from
scmrepo.exceptions.SCMError: Git failed to fetch ref from 'https://github.com/company/repo.git'
```

### Expected
It worked fine with 2.43.4, suspecting https://github.com/iterative/dvc/pull/8907

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.44.0 (deb)
-------------------------
Platform: Python 3.10.8 on Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-glibc2.31
Subprojects:

Supports:
        azure (adlfs = 2023.1.0, knack = 0.10.1, azure-identity = 1.12.0),
        gdrive (pydrive2 = 1.15.0),
        gs (gcsfs = 2023.1.0),
        hdfs (fsspec = 2023.1.0, pyarrow = 11.0.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2023.1.0, boto3 = 1.24.59),
        ssh (sshfs = 2023.1.0),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2023.1.0)
Cache types: hardlink, symlink
Cache directory: xfs on /dev/mapper/rootvg-home_lv
Caches: local
Remotes: azure
Workspace directory: xfs on /dev/mapper/rootvg-home_lv
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by skshetry** [comment]
Thanks, looks like #8907 is to blame as you said. `libgit2` does not support git-credential helper. cc @karajan1001

**Comment by marctorsoc** [comment]
Thanks a lot for reporting this. I was having a hard time figuring out how to solve it!

**Comment by skshetry** [comment]
Hi @bakaleks @marctorsoc. Do you mind testing out patch from #9023, and see whether that works or not for you? Thanks.

```console
pip install "dvc @ git+https://github.com/skshetry/dvc.git@fix-clone-pygit2"
```

**Comment by bakaleks** [comment]
@skshetry works like a charm! DVC version: 0.68.2.dev4402+g683643d7

**Comment by skshetry** [comment]
Thanks @bakaleks for the confirmation.
(DVC version looks a bit suspicious (looks like I haven't pushed tags to my fork)).

**Comment by skshetry** [comment]
The fix is now released in 2.45.0, and available in pip. It'll take some time for debian package though.

**Comment by Verschtunken** [comment]
Hi @skshetry , I am noticing that the commit which fixed this issue [was reverted](https://github.com/iterative/dvc/commit/d7ea7c358da530df33c6d7a4371fec7497254f07), and it appears that the fix was not carried over to 2.45.1 where I experience the issue again. Should this issue be reopened?

**Comment by pmrowla** [comment]
@Verschtunken it was reverted in DVC because the fix was moved into the underlying git dependency instead (https://github.com/iterative/scmrepo/releases/tag/0.1.11)

 What dvc command are you using where you see the error?

**Comment by Verschtunken** [comment]
Hi @pmrowla ,

I can confirm as of this morning that running a `dvc pull` gives me the following error on `dvc==2.44.0, 2.44.1, 2.45.1` but NOT `dvc==2.45.0`:

```
ERROR: unexpected error - Git failed to fetch ref from 'git@gitlab.com:[REDACTED URL]': authentication required but no callback set                                                 
```

I can also confirm that my virtual environment uses `scmrepo==0.1.11`. Let me know what outputs you would require to investigate further.

**Comment by skshetry** [comment]
@Verschtunken, can you please share output of `dvc pull --verbose`? 

If you can, it'd be great if you can add a breakpoint around here, and see why it's not using credential helper.

https://github.com/iterative/scmrepo/blob/eaba5d70bdeb718bd1fedf89578cc15f0b790243/src/scmrepo/git/__init__.py#L332-L335

**Comment by Verschtunken** [comment]
On that second point: `self.backends.backends` does contain the `dulwich` key but the `any(get_matching_helper_commands(url, self.dulwich.repo.get_config_stack()))` check fails. 

Digging deeper it appears that the return from `get_matching_helper_commands` gives an empty generator. The only backend the function finds points to the `PROJECT_ROOT/.git/config` file, which **does not contain the required `credential` section** which would give a non-empty generator in `urlmatch_credential_sections(conf, url)`.

**Comment by Verschtunken** [comment]
As for the `dvc pull --verbose`:

```
```
(p6-data-science-pipeline-py3.9) zflansberry@Zackarys-MacBook-Pro p6-data-science-pipeline % dvc pull --verbose
2023-02-20 12:42:43,723 DEBUG: v2.45.1 (pip), CPython 3.9.13 on macOS-10.16-x86_64-i386-64bit
2023-02-20 12:42:43,723 DEBUG: command: /Users/zflansberry/code/p6-data-science-pipeline/.venv/bin/dvc pull --verbose
2023-02-20 12:42:44,676 DEBUG: Preparing to transfer data from 'chrysalabs-data-science-dvc-remote/p6-data-science-pipeline' to '/Users/zflansberry/code/p6-data-science-pipeline/.dvc/cache'
2023-02-20 12:42:44,677 DEBUG: Preparing to collect status from '/Users/zflansberry/code/p6-data-science-pipeline/.dvc/cache'
2023-02-20 12:42:44,677 DEBUG: Collecting status from '/Users/zflansberry/code/p6-data-science-pipeline/.dvc/cache'
2023-02-20 12:42:44,678 DEBUG: Preparing to collect status from 'chrysalabs-data-science-dvc-remote/p6-data-science-pipeline'                                                                                                                     
2023-02-20 12:42:44,678 DEBUG: Collecting status from 'chrysalabs-data-science-dvc-remote/p6-data-science-pipeline'
2023-02-20 12:42:44,748 DEBUG: Querying 1489 oids via object_exists                                                                                                                                                                               
  0% Querying remote cache|                                                                                                                                                                                         |0/1489 [00:00<?,    ?files/s]/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/gcsfs/core.py:285: UserWarning: GCS project not set - cannot list or create buckets
  warnings.warn("GCS project not set - cannot list or create buckets")
2023-02-20 12:42:49,360 DEBUG: Querying 1 oids via object_exists                                                                                                                                                                                  
2023-02-20 12:42:49,615 DEBUG: Querying 1 oids via object_exists                                                                                                                                                                                  
2023-02-20 12:42:49,847 WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:                                                                                                                         
name: None, md5: 0c6d25617f7428108acf0f3b6468557d.dir
2023-02-20 12:42:49,872 DEBUG: Preparing to transfer data from 'chrysalabs-data-science-dvc-remote/p6-data-science-pipeline' to '/Users/zflansberry/code/p6-data-science-pipeline/.dvc/cache'
2023-02-20 12:42:49,872 DEBUG: Preparing to collect status from '/Users/zflansberry/code/p6-data-science-pipeline/.dvc/cache'
2023-02-20 12:42:49,872 DEBUG: Collecting status from '/Users/zflansberry/code/p6-data-science-pipeline/.dvc/cache'
2023-02-20 12:42:49,873 DEBUG: Preparing to collect status from 'chrysalabs-data-science-dvc-remote/p6-data-science-pipeline'                                                                                                                     
2023-02-20 12:42:49,874 DEBUG: Collecting status from 'chrysalabs-data-science-dvc-remote/p6-data-science-pipeline'
2023-02-20 12:42:49,947 DEBUG: Querying 1489 oids via object_exists                                                                                                                                                                               
  0% Querying remote cache|                                                                                                                                                                                         |0/1489 [00:00<?,    ?files/s]/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/gcsfs/core.py:285: UserWarning: GCS project not set - cannot list or create buckets
  warnings.warn("GCS project not set - cannot list or create buckets")
2023-02-20 12:42:54,684 DEBUG: Querying 1 oids via object_exists                                                                                                                                                                                  
2023-02-20 12:42:54,947 DEBUG: Querying 1 oids via object_exists                                                                                                                                                                                  
2023-02-20 12:42:55,187 WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:                                                                                                                         
name: None, md5: 85eb235ddc913d13cf272b2cf2cdcaaa.dir
2023-02-20 12:42:55,254 DEBUG: Preparing to transfer data from 'chrysalabs-data-science-dvc-remote/p6-data-science-pipeline' to '/Users/zflansberry/code/p6-data-science-pipeline/.dvc/cache'
2023-02-20 12:42:55,254 DEBUG: Preparing to collect status from '/Users/zflansberry/code/p6-data-science-pipeline/.dvc/cache'
2023-02-20 12:42:55,254 DEBUG: Collecting status from '/Users/zflansberry/code/p6-data-science-pipeline/.dvc/cache'
2023-02-20 12:42:55,255 DEBUG: Preparing to collect status from 'chrysalabs-data-science-dvc-remote/p6-data-science-pipeline'                                                                                                                     
2023-02-20 12:42:55,255 DEBUG: Collecting status from 'chrysalabs-data-science-dvc-remote/p6-data-science-pipeline'
2023-02-20 12:42:55,327 DEBUG: Querying 1489 oids via object_exists                                                                                                                                                                               
  0% Querying remote cache|                                                                                                                                                                                         |0/1489 [00:00<?,    ?files/s]/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/gcsfs/core.py:285: UserWarning: GCS project not set - cannot list or create buckets
  warnings.warn("GCS project not set - cannot list or create buckets")
2023-02-20 12:42:59,726 DEBUG: Querying 1 oids via object_exists                                                                                                                                                                                  
2023-02-20 12:42:59,987 DEBUG: Querying 1 oids via object_exists                                                                                                                                                                                  
2023-02-20 12:43:00,225 WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:                                                                                                                         
name: None, md5: 9c70f9d16304759de9400f62e672702d.dir
2023-02-20 12:43:00,286 DEBUG: Creating external repo git@gitlab.com:REDACTED.git@38d2744db76c63abf72e1b0b56ee8451efe86a90
2023-02-20 12:43:00,286 DEBUG: erepo: git clone 'git@gitlab.com:REDACTED.git' to a temporary dir
Cloning REDACTED.git|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| Compressing |2.78k/2.78k [00:13,  9.46kobj/s]git@gitlab.com:REDACTED.git
[]
False
None
<bound method TqdmGit.update_git of <dvc.scm.TqdmGit object at 0x7fb7f8613a60>>
{}
OrderedDict([('dulwich', <class 'scmrepo.git.backend.dulwich.DulwichBackend'>), ('pygit2', <class 'scmrepo.git.backend.pygit2.Pygit2Backend'>), ('gitpython', <class 'scmrepo.git.backend.gitpython.GitPythonBackend'>)])
True
[]
2023-02-20 12:43:53,209 ERROR: unexpected error - Git failed to fetch ref from 'git@gitlab.com:REDACTED.git': authentication required but no callback set                                                            
Traceback (most recent call last):
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/funcy/flow.py", line 112, in reraise
    yield
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/scmrepo/git/backend/pygit2.py", line 508, in fetch_refspecs
    remote.fetch(refspecs=fetch_refspecs)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/pygit2/remote.py", line 146, in fetch
    payload.check_error(err)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/pygit2/callbacks.py", line 98, in check_error
    check_error(error_code)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/pygit2/errors.py", line 65, in check_error
    raise GitError(message)
_pygit2.GitError: authentication required but no callback set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/commands/data_sync.py", line 31, in run
    stats = self.repo.pull(
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/repo/__init__.py", line 58, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/repo/pull.py", line 34, in pull
    processed_files_count = self.fetch(
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/repo/__init__.py", line 58, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/repo/fetch.py", line 86, in fetch
    d, f = _fetch(
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/repo/fetch.py", line 142, in _fetch
    used = repo.used_objs(
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/repo/__init__.py", line 476, in used_objs
    for odb, objs in self.index.used_objs(
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/repo/index.py", line 449, in used_objs
    for odb, objs in stage.get_used_objs(
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/stage/__init__.py", line 722, in get_used_objs
    for odb, objs in out.get_used_objs(*args, **kwargs).items():
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/output.py", line 1074, in get_used_objs
    return self.get_used_external(**kwargs)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/output.py", line 1133, in get_used_external
    return dep.get_used_objs(**kwargs)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/dependency/repo.py", line 102, in get_used_objs
    used, _, _ = self._get_used_and_obj(**kwargs)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/dependency/repo.py", line 116, in _get_used_and_obj
    with self._make_repo(locked=locked, cache_dir=local_odb.path) as repo:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/external_repo.py", line 45, in external_repo
    path = _cached_clone(url, rev, for_write=for_write)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/external_repo.py", line 173, in _cached_clone
    clone_path, shallow = _clone_default_branch(url, rev, for_write=for_write)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/funcy/flow.py", line 274, in wrap_with
    return call()
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/external_repo.py", line 241, in _clone_default_branch
    git = clone(url, clone_path)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/scm.py", line 182, in clone
    fetch_all_exps(git, url, progress=pbar.update_git)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/dvc/repo/experiments/utils.py", line 288, in fetch_all_exps
    scm.fetch_refspecs(
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/scmrepo/git/__init__.py", line 347, in fetch_refspecs
    return self._fetch_refspecs(
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/scmrepo/git/__init__.py", line 283, in _backend_func
    result = func(*args, **kwargs)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/scmrepo/git/backend/pygit2.py", line 508, in fetch_refspecs
    remote.fetch(refspecs=fetch_refspecs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/zflansberry/code/p6-data-science-pipeline/.venv/lib/python3.9/site-packages/funcy/flow.py", line 116, in reraise
    raise_from(into, e)
  File "<string>", line 3, in raise_from
scmrepo.exceptions.SCMError: Git failed to fetch ref from 'git@gitlab.com:REDACTED.git'

2023-02-20 12:43:53,278 DEBUG: Removing '/Users/zflansberry/code/.HJimovYV7gm4WdVXxd8chb.tmp'
2023-02-20 12:43:53,278 DEBUG: Removing '/Users/zflansberry/code/.HJimovYV7gm4WdVXxd8chb.tmp'
2023-02-20 12:43:53,278 DEBUG: Removing '/Users/zflansberry/code/.HJimovYV7gm4WdVXxd8chb.tmp'
2023-02-20 12:43:53,278 DEBUG: Removing '/Users/zflansberry/code/p6-data-science-pipeline/.dvc/cache/.hpfkVqG5bp5Qid6ZrS9jVv.tmp'
2023-02-20 12:43:53,280 DEBUG: Version info for developers:
DVC version: 2.45.1 (pip)
-------------------------
Platform: Python 3.9.13 on macOS-10.16-x86_64-i386-64bit
Subprojects:
        dvc_data = 0.40.3
        dvc_objects = 0.19.3
        dvc_render = 0.2.0
        dvc_task = 0.1.11
        dvclive = 2.0.2
        scmrepo = 0.1.11
Supports:
        gs (gcsfs = 2023.1.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: gs
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-02-20 12:43:53,281 DEBUG: Analytics is enabled.
2023-02-20 12:43:53,348 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/wl/lh2zs6nj3m594ssvtk6h84h00000gn/T/tmprfzoe9u1']'
2023-02-20 12:43:53,357 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/wl/lh2zs6nj3m594ssvtk6h84h00000gn/T/tmprfzoe9u1']'
```

```

**Comment by petrchmelar** [comment]
Hi, we have encountered the same problem with dvc `2.45.1` in our CI jobs.
As @Verschtunken pointed out the problem is probably caused by missing `credentials` section in our `.gitconfig` .
We have successfully worked-around the problem by adding `git config --global credential.helper cache` to our CI job.

```
dvc ls git@github.com:iterative/example-get-started.git --verbose
```

results to 

```
2023-02-24 14:54:53,633 DEBUG: v2.45.1 (pip), CPython 3.8.10 on Linux-4.18.0-408.el8.x86_64-x86_64-with-glibc2.29
2023-02-24 14:54:53,633 DEBUG: command: /opt/venv/bin/dvc ls git@github.com:iterative/example-get-started.git --verbose
2023-02-24 14:54:53,822 DEBUG: Creating external repo git@github.com:iterative/example-get-started.git@None
2023-02-24 14:54:53,822 DEBUG: erepo: git clone 'git@github.com:iterative/example-get-started.git' to a temporary dir
2023-02-24 14:54:58,580 ERROR: unexpected error - Git failed to fetch ref from 'git@github.com:iterative/example-get-started.git': authentication required but no callback set                
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/funcy/flow.py", line 112, in reraise
    yield
  File "/opt/venv/lib/python3.8/site-packages/scmrepo/git/backend/pygit2.py", line 508, in fetch_refspecs
    remote.fetch(refspecs=fetch_refspecs)
  File "/opt/venv/lib/python3.8/site-packages/pygit2/remote.py", line 146, in fetch
    payload.check_error(err)
  File "/opt/venv/lib/python3.8/site-packages/pygit2/callbacks.py", line 98, in check_error
    check_error(error_code)
  File "/opt/venv/lib/python3.8/site-packages/pygit2/errors.py", line 65, in check_error
    raise GitError(message)
_pygit2.GitError: authentication required but no callback set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/opt/venv/lib/python3.8/site-packages/dvc/cli/command.py", line 40, in do_run
    return self.run()
  File "/opt/venv/lib/python3.8/site-packages/dvc/commands/ls/__init__.py", line 31, in run
    entries = Repo.ls(
  File "/opt/venv/lib/python3.8/site-packages/dvc/repo/ls.py", line 42, in ls
    with Repo.open(url, rev=rev, subrepos=True, uninitialized=True) as repo:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/venv/lib/python3.8/site-packages/dvc/external_repo.py", line 45, in external_repo
    path = _cached_clone(url, rev, for_write=for_write)
  File "/opt/venv/lib/python3.8/site-packages/dvc/external_repo.py", line 173, in _cached_clone
    clone_path, shallow = _clone_default_branch(url, rev, for_write=for_write)
  File "/opt/venv/lib/python3.8/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/opt/venv/lib/python3.8/site-packages/funcy/flow.py", line 274, in wrap_with
    return call()
  File "/opt/venv/lib/python3.8/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/opt/venv/lib/python3.8/site-packages/dvc/external_repo.py", line 241, in _clone_default_branch
    git = clone(url, clone_path)
  File "/opt/venv/lib/python3.8/site-packages/dvc/scm.py", line 182, in clone
    fetch_all_exps(git, url, progress=pbar.update_git)
  File "/opt/venv/lib/python3.8/site-packages/dvc/repo/experiments/utils.py", line 288, in fetch_all_exps
    scm.fetch_refspecs(
  File "/opt/venv/lib/python3.8/site-packages/scmrepo/git/__init__.py", line 337, in fetch_refspecs
    return self._fetch_refspecs(
  File "/opt/venv/lib/python3.8/site-packages/scmrepo/git/__init__.py", line 283, in _backend_func
    result = func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/scmrepo/git/backend/pygit2.py", line 508, in fetch_refspecs
    remote.fetch(refspecs=fetch_refspecs)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/venv/lib/python3.8/site-packages/funcy/flow.py", line 116, in reraise
    raise_from(into, e)
  File "<string>", line 3, in raise_from
scmrepo.exceptions.SCMError: Git failed to fetch ref from 'git@github.com:iterative/example-get-started.git'

2023-02-24 14:54:58,623 DEBUG: Version info for developers:
DVC version: 2.45.1 (pip)
-------------------------
Platform: Python 3.8.10 on Linux-4.18.0-408.el8.x86_64-x86_64-with-glibc2.29
Subprojects:
	dvc_data = 0.40.3
	dvc_objects = 0.19.3
	dvc_render = 0.1.2
	dvc_task = 0.1.11
	dvclive = 2.0.2
	scmrepo = 0.1.11
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2023.1.0, boto3 = 1.24.59)

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-02-24 14:54:58,636 DEBUG: Analytics is enabled.
2023-02-24 14:54:58,708 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmp61t5i9zn']'
2023-02-24 14:54:58,712 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmp61t5i9zn']'

```

**Comment by daavoo** [comment]
>  is probably caused by missing credentials section in our .gitconfig .

That's correct. I can reproduce this when dropping the `crendentials` section from config.

Looking into a fix
