### ISSUE TITLE
Pushing Directory to cloud

### ISSUE THREAD

**Issue by Abusheik008** [iterative/dvc#9024]
# Bug Report

## Description

I am trying to push directory to drive but when I use dvc push it throws some error which is mentioned below.
`ERROR: unexpected error - [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\{directory}\\Code\\{project}\\.dvc\\..\\gdrive:{link}`

### Reproduce

1. dvc add
2. dvc push

**Comment by skshetry** [comment]
@Abusheik008, can you please share `dvc doctor` output? Also, please share full verbose output of `dvc push --verbose`. Thanks

**Comment by Abusheik008** [comment]
# dvc doctor

DVC version: 2.38.1 (exe)
---------------------------------
webhdfs (fsspec = 2022.11.0)
Cache types: hardlink, symlink
Cache directory: NTFS on D:\
Caches: local
Remotes: local, local
Workspace directory: NTFS on D:\
Repo: dvc, git

# dvc push --verbose
2023-02-14 17:58:27,166 DEBUG: Preparing to transfer data from 'D:\Project\Code\Project\Project\.dvc\cache' to 'D:\Project\Code\Project\Project\.dvc\..\gdrive:1wCNyQ4KpE6nRGWCqQ_hwZjROuuBlhmvB'
2023-02-14 17:58:27,167 DEBUG: Preparing to collect status from 'D:\Project\Code\Project\Project\.dvc\..\gdrive:1wCNyQ4KpE6nRGWCqQ_hwZjROuuBlhmvB'
2023-02-14 17:58:27,169 DEBUG: Collecting status from 'D:\Project\Code\Project\Project\.dvc\..\gdrive:1wCNyQ4KpE6nRGWCqQ_hwZjROuuBlhmvB'
  0% Querying remote cache|                                                                                                                           |0/1 [00:00<?,    ?files/s]2023-02-14 17:58:27,171 DEBUG: Querying 1 oids via object_exists
2023-02-14 17:58:27,179 ERROR: unexpected error - [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\Project\\Code\\Project\\Project\\.dvc\\..\\gdrive:1wCNyQ4KpE6nRGWCqQ_hwZjROuuBlhmvB\\c5\\9d9197495d43790842313796bd43f6'
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc\cli\__init__.py", line 185, in main
  File "dvc\cli\command.py", line 22, in do_run
  File "dvc\commands\data_sync.py", line 59, in run
  File "dvc\repo\__init__.py", line 48, in wrapper
  File "dvc\repo\push.py", line 91, in push
  File "dvc\data_cloud.py", line 143, in push
  File "dvc\data_cloud.py", line 124, in transfer
  File "dvc_data\hashfile\transfer.py", line 190, in transfer
  File "dvc_data\hashfile\status.py", line 179, in compare_status
  File "dvc_data\hashfile\status.py", line 151, in status
  File "dvc_data\hashfile\db\local.py", line 56, in oids_exist
  File "dvc_data\hashfile\db\__init__.py", line 156, in check
  File "dvc_data\hashfile\db\local.py", line 128, in is_protected
        gdrive (pydrive2 = 1.15.0),        gs (gcsfs = 2022.11.0),
        hdfs (fsspec = 2022.11.0, pyarrow = 10.0.1),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        oss (ossfs = 2023.1.0),
        s3 (s3fs = 2022.11.0, boto3 = 1.24.59),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2022.11.0)
Cache types: hardlink, symlink
Cache directory: NTFS on D:\
Caches: local
Remotes: local, local
Workspace directory: NTFS on D:\
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-02-14 17:58:28,381 DEBUG: Analytics is enabled.
2023-02-14 17:58:28,387 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\ABUSHEIK\\AppData\\Local\\Temp\\tmp4hiivbse']'
2023-02-14 17:58:28,393 DEBUG: Spawned '['daemon', '-q', 'analytics', 'C:\\Users\\ABUSHEIK\\AppData\\Local\\Temp\\tmp4hiivbse']'

**Comment by Abusheik008** [comment]
Any update on this @skshetry ?

**Comment by pmrowla** [comment]
It looks like DVC thinks your configured remote is local (and not a gdrive remote).
```
Remotes: local, local
```

Can you double check that your configured remote URL starts with `gdrive://` in `.dvc/config`?

**Comment by Abusheik008** [comment]
No it looks like this 

`[core]
    remote = storage_1
['remote "storage"']
    url = ../gdrive: link 1
['remote "storage_1"']
    url = ../gdrive: link 2`

**Comment by pmrowla** [comment]
Are you using `dvc remote add` to generate it? The problem is that your remote URLs are formatted like `url = ../gdrive: link 1`

A gdrive URL should look like `gdrive://folder_id/...`

**Comment by pmrowla** [comment]
Please refer to the docs on adding a gdrive remote: https://dvc.org/doc/user-guide/how-to/setup-google-drive-remote#url-format

It sounds like you may have just made a typo when adding the remote, and did not format the URL correctly (with `gdrive://`)

**Comment by Abusheik008** [comment]
Ok will look into it

**Comment by Abusheik008** [comment]
I have removed all the existing storage and created a new one and it works fine with this command `dvc push -r storage_name`

Closing this issue thanks for the support @pmrowla
