### ISSUE TITLE
Unable to push file 

### ISSUE THREAD

**Issue by Alberto1404** [iterative/dvc#9067]
Hi, I am trying to use dvc for managing big files. 
I have been following the documentation along with this tutorial: 
[https://www.youtube.com/watch?v=W2DvpCYw22o](https://www.youtube.com/watch?v=W2DvpCYw22o)
For my personal case, I want the remote adress via ssh, via this command: 
```dvc remote add -d dvc ssh://username@ip_adress:/home/username/dvc```
Such that I get this output when executing ```dvc doctor```:
```
DVC version: 2.44.0 (pip)
-------------------------
Platform: Python 3.8.0 on Linux-5.15.0-60-generic-x86_64-with-glibc2.10
Subprojects:
        dvc_data = 0.39.3
        dvc_objects = 0.19.3
        dvc_render = 0.1.1
        dvc_task = 0.1.11
        dvclive = 2.0.2
        scmrepo = 0.1.9
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        ssh (sshfs = 2023.1.0)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p8
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/nvme0n1p8
Repo: dvc, git
```
My problem comes when doing ```dvc push```, I get the following output: 
```
ERROR: unexpected error - Permission denied: Permission denied
```
What am I doing wrong?
Thank you for your help

**Comment by Alberto1404** [comment]
# Update
Output of ```dvc push -vv```
```
2023-02-21 15:49:11,330 DEBUG: v2.44.0 (pip), CPython 3.8.0 on Linux-5.15.0-60-generic-x86_64-with-glibc2.10
2023-02-21 15:49:11,330 DEBUG: command: /home/alberto/anaconda3/envs/yolo/bin/dvc push -vv
2023-02-21 15:49:11,330 TRACE: Namespace(all_branches=False, all_commits=False, all_tags=False, cd='.', cmd='push', cprofile=False, cprofile_dump=None, func=<class 'dvc.commands.data_sync.CmdDataPush'>, glob=False, instrument=False, instrument_open=False, jobs=None, parser=DvcParser(prog='dvc', usage=None, description='Data Version Control', formatter_class=<class 'argparse.RawTextHelpFormatter'>, conflict_handler='error', add_help=False), pdb=False, quiet=0, recursive=False, remote=None, run_cache=False, show_stack=False, targets=[], verbose=2, viztracer=False, viztracer_async=False, viztracer_depth=None, with_deps=False, yappi=False, yappi_separate_threads=False)
2023-02-21 15:49:11,523 TRACE:     7.57 ms in collecting stages from /home/alberto/Repo/models
2023-02-21 15:49:11,523 TRACE:    82.58 mks in collecting stages from /home/alberto/Repo/models/yolo5
2023-02-21 15:49:11,523 TRACE:     3.13 mks in collecting stages from /home/alberto/Repo/models/yolo5/pretrained
2023-02-21 15:49:11,523 TRACE:     2.98 mks in collecting stages from /home/alberto/Repo/models/yolo5/trained2023
2023-02-21 15:49:11,523 TRACE:     3.61 mks in collecting stages from /home/alberto/Repo/models/yolo5/trained
2023-02-21 15:49:11,523 TRACE:     2.34 mks in collecting stages from /home/alberto/Repo/models/engine
2023-02-21 15:49:11,527 DEBUG: Preparing to transfer data from '/home/alberto/Repo/models/.dvc/cache' to '/home/sr/dvc'
2023-02-21 15:49:11,527 DEBUG: Preparing to collect status from '/home/sr/dvc'
2023-02-21 15:49:11,527 DEBUG: Collecting status from '/home/sr/dvc'
2023-02-21 15:49:11,528 DEBUG: Querying 1 oids via object_exists                            
2023-02-21 15:49:11,551 ERROR: unexpected error - Permission denied: Permission denied      
Traceback (most recent call last):
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/sshfs/utils.py", line 27, in wrapper
    return await func(*args, **kwargs)
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/sshfs/spec.py", line 82, in _connect
    client = await self._stack.enter_async_context(_raw_client)
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/contextlib.py", line 568, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/asyncssh/misc.py", line 274, in __aenter__
    self._coro_result = await self._coro
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/asyncssh/connection.py", line 8047, in connect
    return await asyncio.wait_for(
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/asyncssh/connection.py", line 447, in _connect
    await options.waiter
asyncssh.misc.PermissionDenied: Permission denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc/cli/__init__.py", line 205, in main
    ret = cmd.do_run()
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc/commands/data_sync.py", line 59, in run
    processed_files_count = self.repo.push(
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc/repo/__init__.py", line 57, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc/repo/push.py", line 89, in push
    result = self.cloud.push(
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc/data_cloud.py", line 149, in push
    return self.transfer(
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc/data_cloud.py", line 130, in transfer
    return transfer(src_odb, dest_odb, objs, **kwargs)
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc_data/hashfile/transfer.py", line 203, in transfer
    status = compare_status(
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc_data/hashfile/status.py", line 178, in compare_status
    dest_exists, dest_missing = status(
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc_data/hashfile/status.py", line 149, in status
    odb.oids_exist(hashes, jobs=jobs, progress=pbar.callback)
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc_objects/db.py", line 411, in oids_exist
    return list(wrap_iter(remote_oids, callback))
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc_objects/db.py", line 36, in wrap_iter
    for index, item in enumerate(iterable, start=1):
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc_objects/db.py", line 357, in list_oids_exists
    in_remote = self.fs.exists(paths, batch_size=jobs)
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc_objects/fs/base.py", line 332, in exists
    if self.fs.async_impl:
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/funcy/objects.py", line 50, in __get__
    return prop.__get__(instance, type)
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/dvc_ssh/__init__.py", line 116, in fs
    return _SSHFileSystem(**self.fs_args)
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/sshfs/spec.py", line 65, in __init__
    self._client, self._pool = self.connect(
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/fsspec/asyn.py", line 113, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/fsspec/asyn.py", line 98, in sync
    raise return_result
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/home/alberto/anaconda3/envs/yolo/lib/python3.8/site-packages/sshfs/utils.py", line 29, in wrapper
    raise PermissionError(exc.reason) from exc
PermissionError: Permission denied

2023-02-21 15:49:11,610 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-02-21 15:49:11,610 DEBUG: Removing '/home/alberto/Repo/.Nczc8wwRdcWHjBaDNjsLct.tmp'
2023-02-21 15:49:11,610 DEBUG: Removing '/home/alberto/Repo/.Nczc8wwRdcWHjBaDNjsLct.tmp'
2023-02-21 15:49:11,610 DEBUG: Removing '/home/alberto/Repo/.Nczc8wwRdcWHjBaDNjsLct.tmp'
2023-02-21 15:49:11,610 DEBUG: Removing '/home/alberto/Repo/models/.dvc/cache/.PLBX9YVsPugUSAER5rdVGk.tmp'
2023-02-21 15:49:11,613 DEBUG: Version info for developers:
DVC version: 2.44.0 (pip)
-------------------------
Platform: Python 3.8.0 on Linux-5.15.0-60-generic-x86_64-with-glibc2.10
Subprojects:
        dvc_data = 0.39.3
        dvc_objects = 0.19.3
        dvc_render = 0.1.1
        dvc_task = 0.1.11
        dvclive = 2.0.2
        scmrepo = 0.1.9
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        ssh (sshfs = 2023.1.0)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p8
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/nvme0n1p8
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-02-21 15:49:11,613 DEBUG: Analytics is enabled.
2023-02-21 15:49:11,630 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmp6vjbhugz']'
2023-02-21 15:49:11,631 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmp6vjbhugz']'
```
