### ISSUE TITLE
pipenv run dvc repro not finding packages

### ISSUE THREAD

**Issue by thoefkens** [iterative/dvc#9120]
Hi all!

When running dvc through a pipenv shell, the command

`dvc repro `

works perfectly fine.

However, when running it on an Azure build agent with 
`"pipenv run dvc repro"`, the first stage of dvc.yaml fails (it is either `python somescript.py`or we also tried `pipenv run python somescript.py`) The run fails with ModuleNotFoundErrors (for example sklearn). When running a pipenv graph, we can see the modules are all installed, so it seems like dvc is ignoring the pipenv. How can we work around this?

Thank you
Thomas

**Comment by efiop** [comment]
@thoefkens The issue is probably because you've installed your deps in pipenv, but `python` in `python somescript.py` is from your system. You need to enter the venv yourself first to make it run.

**Comment by thoefkens** [comment]
@efiop As described, I already tested running "pipenv run python somescript.py" in the dvc stages, with no effect.

**Comment by efiop** [comment]
@thoefkens Reopening is also not a problem :) Just thought it was a simple confusion. It seems like an environment issue. Dvc itself doesn't fiddle with the environment. Do you use fish shell by any chance?

**Comment by efiop** [comment]
@thoefkens So `pipenv run python somescript.py` ran by hand without dvc works correctly, but it doesn't work when in dvc stage?

**Comment by thoefkens** [comment]
@efiop No.. when running dvc repro in a "pipenv shell" everything works as expected. However, I am trying to run dvc repro on an Azure Pipelines standard Ubuntu agent, where "pipenv shell" does not work (as it is non-interactive). Running "pipenv run" instaed as suggested launches dvc correctly, but it then does not install the packages added by running pipenv install. So it seems as though dvc is not running in the env..

**Comment by efiop** [comment]
@thoefkens Sounds like there is some misunderstanding of how pipenv works. if you `pipenv run dvc repro`, it will launch dvc from pipenv env, but dvc will launch just `python somescript.py` with your regular environement that I suspect is not affected by `pipenv`. You clearly need to find a way to activate the environment.

What error are you getting when you try to `pipenv shell`?

**Comment by thoefkens** [comment]
@efiop As I mentioned, after running only "python somescript.py" in the dvc stage, I altered that stage to say "pipenv run python somescript.py" - that should make sure that dvc runs in the same pipenv env, right?

**Comment by thoefkens** [comment]
@efiop  This would be the error when running a pipenv shell

```
Launching subshell in virtual environment...
Traceback (most recent call last):
  File "/home/vsts/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/vsts/.local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/vsts/.local/lib/python3.9/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/vsts/.local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/vsts/.local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vsts/.local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vsts/.local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/vsts/.local/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/vsts/.local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/vsts/.local/lib/python3.9/site-packages/pipenv/cli/command.py", line 397, in shell
    do_shell(
  File "/home/vsts/.local/lib/python3.9/site-packages/pipenv/core.py", line 2604, in do_shell
    shell.fork_compat(*fork_args)
  File "/home/vsts/.local/lib/python3.9/site-packages/pipenv/shells.py", line 124, in fork_compat
    c.interact(escape_character=None)
  File "/home/vsts/.local/lib/python3.9/site-packages/pipenv/vendor/pexpect/pty_spawn.py", line 788, in interact
    mode = tty.tcgetattr(self.STDIN_FILENO)
termios.error: (25, 'Inappropriate ioctl for device')
```

**Comment by efiop** [comment]
@thoefkens Sorry, but I am honestly not that familiar with how pipenv works and whether pipenv run inside pipenv run will work correctly or not. Maybe try playing with it to narrow down the issue. E.g. `pipenv run pipenv run pip freeze` to check if the inner pipenv run actually has the same packages installed as the outer one.

With venv and alike, this problem is usually just solved by activating the environment and running inside of it. Maybe `pipenv install --system` could do that by using system python for you?
