### ISSUE TITLE
`dvc.api.read` fails when `version_aware = true`

### ISSUE THREAD

**Issue by dacbd** [iterative/dvc#9139]
dvc remotes are in our sandbox account,

you can see a minimal example here: https://github.com/dacbd/20230308.dvc-test
Running:
```
pip install "dvc[s3]"
python works.py
python fails.py
```

Stack trace:
```
Traceback (most recent call last):
  File "/Users/dabarnes/projects/20230308.dvc-test/fails.py", line 3, in <module>
    data = dvc.api.read(
  File "/Users/dabarnes/projects/20230308.dvc-test/venv/lib/python3.10/site-packages/dvc/api/data.py", line 210, in read
    with open(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/dabarnes/projects/20230308.dvc-test/venv/lib/python3.10/site-packages/dvc/api/data.py", line 198, in _open
    with _repo.open_by_relpath(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/dabarnes/projects/20230308.dvc-test/venv/lib/python3.10/site-packages/dvc/repo/__init__.py", line 598, in open_by_relpath
    remote_odb = self.cloud.get_remote_odb(name=remote)
  File "/Users/dabarnes/projects/20230308.dvc-test/venv/lib/python3.10/site-packages/dvc/data_cloud.py", line 107, in get_remote_odb
    raise NoRemoteError(
dvc.config.NoRemoteError: config file error: '<command>' is unsupported for cloud versioned remotes

```

```
DVC version: 2.46.0 (pip)
-------------------------
Platform: Python 3.10.4 on macOS-13.2.1-arm64-arm-64bit
Subprojects:
	dvc_data = 0.42.1
	dvc_objects = 0.21.1
	dvc_render = 0.2.0
	dvc_task = 0.2.0
	scmrepo = 0.1.15
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2023.3.0, boto3 = 1.24.59)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3, s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git

```

**Comment by dberenbaum** [comment]
@efiop Should `dvc.api.read` be relying on dvcfs here? Do we still need `dvc.api.read`?

**Comment by efiop** [comment]
@dberenbaum `read` was using `dvcfs` and is still using it. Tested and `read` works now too. Thanks for the heads up!

Fixed by https://github.com/iterative/dvc/pull/9246

**Comment by dberenbaum** [comment]
@efiop Maybe I'm missing something. With the example repo above, I get:

```
$ python fails.py
Traceback (most recent call last):
  File "/Users/dave/Code/dvc/dvc/api/data.py", line 17, in _wrap_exceptions
    yield
  File "/Users/dave/Code/dvc/dvc/api/data.py", line 239, in _open
    remote_odb = _repo.cloud.get_remote_odb(name=remote)
  File "/Users/dave/Code/dvc/dvc/data_cloud.py", line 107, in get_remote_odb
    raise NoRemoteError(
dvc.config.NoRemoteError: config file error: '<command>' is unsupported for cloud versioned remotes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/tmp/20230308.dvc-test/fails.py", line 3, in <module>
    data = dvc.api.read(
  File "/Users/dave/Code/dvc/dvc/api/data.py", line 262, in read
    with open(
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/Users/dave/Code/dvc/dvc/api/data.py", line 218, in _open
    with _wrap_exceptions(_repo, path):
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/dave/Code/dvc/dvc/api/data.py", line 19, in _wrap_exceptions
    raise NoRemoteInExternalRepoError(url) from exc
dvc.exceptions.NoRemoteInExternalRepoError: No DVC remote is specified in target repository 'my_data.txt'.
```

**Comment by efiop** [comment]
Oh, sorry, I was only testing with default remote.

This is more related to https://github.com/iterative/studio/issues/4782#issuecomment-1495100166 actually. Reopening and taking a look...

**Comment by efiop** [comment]
Okay, yeah, I forgot about this branch of execution completely 🤦 

https://github.com/iterative/dvc/blob/cf52efb8c30f615935932094d121103284499b94/dvc/api/data.py#L242

**Comment by efiop** [comment]
@dacbd Btw, thank you so much for a comprehensive reproducer! 🙏
