### ISSUE TITLE
dvc get --show-url fails with missing `md5` key.

### ISSUE THREAD

**Issue by Limess** [iterative/dvc#9176]
# Bug Report

## Issue name 

`--show-url` results in an error

## Description

My intended use case is trying to get the S3 URI where DVC is storing models, so I can use this within other commands which have S3 credentials but are not aware of dvc. This might be the wrong command/approach.

Running `dvc get` with `--show-url` results in an error.

```
$ pipx run 'dvc[s3]' get . data/models/TABS --show-url --verbose
2023-03-14 15:17:12,036 DEBUG: v2.48.0 (pip), CPython 3.10.10 on Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2023-03-14 15:17:12,036 DEBUG: command: /home/charlie_briggs/.local/pipx/.cache/7c88dcae1426782/bin/dvc get . data/models/TABS --show-url --verbose
2023-03-14 15:17:12,390 ERROR: unexpected error - 'md5'
Traceback (most recent call last):
  File "/home/charlie_briggs/.local/pipx/.cache/7c88dcae1426782/lib/python3.10/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/home/charlie_briggs/.local/pipx/.cache/7c88dcae1426782/lib/python3.10/site-packages/dvc/cli/command.py", line 40, in do_run
    return self.run()
  File "/home/charlie_briggs/.local/pipx/.cache/7c88dcae1426782/lib/python3.10/site-packages/dvc/commands/get.py", line 28, in run
    return self._show_url()
  File "/home/charlie_briggs/.local/pipx/.cache/7c88dcae1426782/lib/python3.10/site-packages/dvc/commands/get.py", line 18, in _show_url
    url = get_url(self.args.path, repo=self.args.url, rev=self.args.rev)
  File "/home/charlie_briggs/.local/pipx/.cache/7c88dcae1426782/lib/python3.10/site-packages/dvc/api/data.py", line 31, in get_url
    md5 = dvc_info["md5"]
KeyError: 'md5'
````

`dvc status` reports no md5s so may be related? `data/models`, `data/train` and `data/test` are directories.

```
$ dvc status --verbose
2023-03-14 15:22:01,757 DEBUG: v2.46.0 (pip), CPython 3.10.10 on Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
2023-03-14 15:22:01,757 DEBUG: command: /home/charlie_briggs/.local/bin//dvc status --verbose
2023-03-14 15:22:01,956 DEBUG: built tree 'object 98d41a9a715a6913bbb3142129aba44e.dir'
2023-03-14 15:22:01,956 DEBUG: Computed stage: 'data/models.dvc' md5: 'None'
2023-03-14 15:22:01,958 DEBUG: built tree 'object d751713988987e9331980363e24189ce.dir'
2023-03-14 15:22:01,958 DEBUG: Computed stage: 'data/train.dvc' md5: 'None'
2023-03-14 15:22:01,960 DEBUG: built tree 'object 27bc3950d029bbd1555ab10f49b3e76b.dir'
2023-03-14 15:22:01,960 DEBUG: Computed stage: 'data/test.dvc' md5: 'None'
Data and pipelines are up to date.
2023-03-14 15:22:01,961 DEBUG: Analytics is enabled.
2023-03-14 15:22:01,983 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpbm7raq51']'
2023-03-14 15:22:01,984 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpbm7raq51']'
```

### Reproduce

Not currently sure how to reproduce
### Expected

Command returns without error.

### Environment information

DVC 2.48.0 Ubuntu WSL

Installed via pipx with S3 backend.

DVC config:

```
['remote "train"']
    url = s3://<bucket>/dvc/train
['remote "test"']
    url = s3://<bucket>/dvc/test
['remote "models"']
    url = s3://<bucket>/dvc/models
```

where `<bucket>` is redacted

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.48.0 (pip)
-------------------------
Platform: Python 3.10.10 on Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Subprojects:
        dvc_data = 0.43.0
        dvc_objects = 0.21.1
        dvc_render = 0.2.0
        dvc_task = 0.2.0
        scmrepo = 0.1.15
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.3.0, boto3 = 1.24.59)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdc
Caches: local
Remotes: s3, s3, s3
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/569e9d75f1d4413ec3af212ec6333961
```

**Additional Information (if any):**

**Comment by pmrowla** [comment]
Are you setting the `remote:` field in each `.dvc` file to indicate that each directory is only stored in a specific remote?

i.e. `data/models.dvc` would contain something like:
```
outs:
  path: models
  ...
  remote: models
```

`dvc get` will try to look up URLs using the default configured remote, but in this case you don't have a default remote configured which may be related to the problem here.

**Comment by Limess** [comment]
Yes, each file has a specific remote and I have no default remote.

**Comment by capfish** [comment]
Hi we're having the exact same issue on Ubuntu 22.04.2 we do have a default remote set and it is the only remote that we are using.  I removed the exact path of the file and replaced it with "path/to"


**Output of dvc get --show-url --verbose**
```
2023-06-29 16:49:51,651 DEBUG: v3.2.3 (pip), CPython 3.10.6 on Linux-5.19.0-45-generic-x86_64-with-glibc2.35
2023-06-29 16:49:51,651 DEBUG: command: dvc get --show-url . ./path/to/hygdata_v3.h5 --verbose
2023-06-29 16:49:52,304 ERROR: unexpected error - 'md5'
Traceback (most recent call last):
  File "/home/sulekha/.local/lib/python3.10/site-packages/dvc/cli/__init__.py", line 209, in main
    ret = cmd.do_run()
  File "/home/sulekha/.local/lib/python3.10/site-packages/dvc/cli/command.py", line 40, in do_run
    return self.run()
  File "/home/sulekha/.local/lib/python3.10/site-packages/dvc/commands/get.py", line 24, in run
    return self._show_url()
  File "/home/sulekha/.local/lib/python3.10/site-packages/dvc/commands/get.py", line 17, in _show_url
    url = get_url(self.args.path, repo=self.args.url, rev=self.args.rev)
  File "/home/sulekha/.local/lib/python3.10/site-packages/dvc/api/data.py", line 53, in get_url
    md5 = dvc_info["md5"]
KeyError: 'md5'

2023-06-29 16:49:52,323 DEBUG: Version info for developers:
DVC version: 3.2.3 (pip)
------------------------
Platform: Python 3.10.6 on Linux-5.19.0-45-generic-x86_64-with-glibc2.35
Subprojects:
    dvc_data = 2.3.1
    dvc_objects = 0.23.0
    dvc_render = 0.5.3
    dvc_task = 0.3.0
    scmrepo = 1.0.4
Supports:
    gs (gcsfs = 2023.6.0),
    http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
    https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Config:
    Global: /home/sulekha/.config/dvc
    System: /etc/xdg/xdg-ubuntu/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: gs
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/4012dc2fa4d2060883e3641bf024ae04

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-06-29 16:49:52,324 DEBUG: Analytics is enabled.
2023-06-29 16:49:52,346 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpf6tbnuti']'
2023-06-29 16:49:52,347 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpf6tbnuti']'
```


We did some debugging and printed out `dvc_info` and indeed "md5" is not a key however we see "md5-dos2unix" as a key here is `dvc_info`
```
{
'type': 'file', 'size': 5745584, 'isexec': False, 'entry': DataIndexEntry(key=('path', 'to', 'hygdata_v3.h5'), meta=Meta(isdir=False, size=5745584, nfiles=None, isexec=False, version_id=None, etag=None, checksum=None, md5='726554c2bca215edacbd2b94f82404d2', inode=None, mtime=None, remote=None), hash_info=HashInfo(name='md5-dos2unix', value='726554c2bca215edacbd2b94f82404d2', obj_name=None), loaded=None), 'md5-dos2unix': '726554c2bca215edacbd2b94f82404d2', 'name': 'path/to/hygdata_v3.h5', 'isout': True, 'isdvc': True
}
```
This is the .dvc file
```
outs:
- md5: 726554c2bca215edacbd2b94f82404d2
  size: 5745584
  path: hygdata_v3.h5
```
Any ideas what this could be?

**Comment by pmrowla** [comment]
@capfish this looks like a DVC 3.0 related bug, will take a look into it later today
