### ISSUE TITLE
dvc assert path.startswith(base) AssertionError

### ISSUE THREAD

**Issue by samhodge-aiml** [iterative/dvc#9191]
# Bug Report

stats: assertion error with relative path

## Description

Unable to complete `dvc status`

### Reproduce

1. dvc status --verbose
2. stack trace below

```
2023-03-16 09:01:15,012 ERROR: unexpected error                                                                                                                                              
------------------------------------------------------------
Traceback (most recent call last):
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/command/base.py", line 45, in do_run
    return self.run()
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/command/status.py", line 63, in run
    recursive=self.args.recursive,
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/repo/status.py", line 146, in status
    self, targets, with_deps=with_deps, recursive=recursive
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/repo/status.py", line 38, in _local_status
    return _joint_status(pairs)
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/repo/status.py", line 23, in _joint_status
    stage.status(check_updates=True, filter_info=filter_info)
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/stage/__init__.py", line 598, in status
    self._status_deps(ret)
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/stage/__init__.py", line 614, in _status_deps
    deps_status = self._status(self.deps)
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/stage/__init__.py", line 609, in _status
    ret.update(entry.status())
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/output.py", line 480, in status
    return self.workspace_status()
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/output.py", line 468, in workspace_status
    if self.changed_checksum():
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/output.py", line 448, in changed_checksum
    return self.hash_info != self.get_hash()
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/output.py", line 426, in get_hash
    dry_run=not self.use_cache,
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/objects/stage.py", line 330, in stage
    **kwargs,
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/objects/stage.py", line 190, in _stage_tree
    meta, tree = _build_tree(fs_path, fs, name, odb=odb, **kwargs)
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/objects/stage.py", line 168, in _build_tree
    key = fs.path.relparts(file_fs_path, fs_path)
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/fs/path.py", line 91, in relparts
    return self.parts(self.relpath(path, base))
  File "/media/sam/projects/gitlab/aiml/synthetic-data/env/lib/python3.7/site-packages/dvc/fs/path.py", line 85, in relpath
    assert path.startswith(base)
AssertionError
```

### Expected

Expect to see status of dvc stages

### Environment information

**Output of `dvc doctor`:**

```console
/media/sam/projects/gitlab/aiml/synthetic-data$ dvc doctor
DVC version: 2.9.1 (conda)
---------------------------------
Platform: Python 3.7.12 on Linux-5.15.0-60-generic-x86_64-with-debian-bookworm-sid
Supports:
        gs (gcsfs = 2021.11.1),
        webhdfs (fsspec = 2021.11.1),
        http (aiohttp = 3.6.2, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.6.2, aiohttp-retry = 2.8.3)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: gs
Workspace directory: ext4 on /dev/sda
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by skshetry** [comment]
Hi @samhodge-aiml, that is a very old release. Recent release is 2.50. Also we have stopped supporting Python 3.7.

Please try upgrading to a newer python version and newer dvc version and see if it works.

We also have debian binary package if you don’t want to upgrade Python.

**Comment by samhodge-aiml** [comment]
We cannot update the Python version, but thanks for that suggestion

`dvc-gs==2.9.4`
`fsspec==2022.7.1`

solved the issue.
