### ISSUE TITLE
push: Azure non-versioned remote not providing error message about not supporting versioning

### ISSUE THREAD

**Issue by glenn-t** [iterative/dvc#9194]
# Bug Report

## Description

I have been trying out DVC for the first time, using an Azure remote. I mistakenly set `version_aware true`, but my Azure remote is not version enabled. When trying `dvc push`, got `unexpected error`, rather than `failed to push data to the cloud - remote 'myremote' does not support versioning`. This caused me a lot of debugging time, so an informative error would have been better.

I can see an informative error should have been produced from `test_versioning` function, but this didn't happen as the function produced an error on line `info = dest_fs.info(dest_path)`, rather than producing the desired informative error message.

The full error is below.

```
dvc push -v
2023-03-16 14:37:19,723 DEBUG: v2.50.0 (pip), CPython 3.10.4 on Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
2023-03-16 14:37:19,723 DEBUG: command: /home/glenn/Projects/dvc/.venv/bin/dvc push -v
2023-03-16 14:37:19,955 DEBUG: Pushing version-aware files to 'dvs-test/dvc'
2023-03-16 14:37:20,227 DEBUG: '['dvs-test/dvc/data/data2.csv']' file already exists, skipping                                                                    
2023-03-16 14:37:20,548 ERROR: unexpected error                                                                                                                   
Traceback (most recent call last):
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 705, in _ls_blobs
    async for next_blob in blobs:
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/async_paging.py", line 149, in __anext__
    return await self.__anext__()
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/async_paging.py", line 152, in __anext__
    self._page = await self._page_iterator.__anext__()
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/async_paging.py", line 96, in __anext__
    self._response = await self._get_next(self.continuation_token)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/storage/blob/aio/_list_blobs_helper.py", line 90, in _get_next_cb
    process_storage_error(error)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 189, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/storage/blob/aio/_list_blobs_helper.py", line 83, in _get_next_cb
    return await self._command(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 79, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/storage/blob/_generated/aio/operations/_container_operations.py", line 1785, in list_blob_hierarchy_segment
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/exceptions.py", line 109, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: The specified container does not exist.
RequestId:887a78c3-c01e-0077-7fa7-570344000000
Time:2023-03-16T01:37:20.5036327Z
ErrorCode:ContainerNotFound
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.
RequestId:887a78c3-c01e-0077-7fa7-570344000000
Time:2023-03-16T01:37:20.5036327Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/commands/data_sync.py", line 60, in run
    processed_files_count = self.repo.push(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/repo/__init__.py", line 67, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/repo/push.py", line 50, in push
    pushed += _push_worktree(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/repo/push.py", line 119, in _push_worktree
    return push_worktree(repo, remote, targets=targets, jobs=jobs, **kwargs)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/repo/worktree.py", line 176, in push_worktree
    pushed += checkout(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc_data/index/checkout.py", line 102, in checkout
    entry.meta = test_versioning(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc_data/index/checkout.py", line 38, in test_versioning
    info = dest_fs.info(dest_path)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 467, in info
    return self.fs.info(path, **kwargs)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 506, in info
    return sync(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/fsspec/asyn.py", line 100, in sync
    raise return_result
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/fsspec/asyn.py", line 55, in _runner
    result[0] = await coro
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 561, in _info
    out = await self._ls(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 812, in _ls
    output = await self._ls_blobs(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 738, in _ls_blobs
    raise FileNotFoundError
FileNotFoundError

2023-03-16 14:37:20,623 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-03-16 14:37:20,623 DEBUG: Removing '/home/glenn/Projects/.GKTi22QwBRBYvnZLnJQW8Y.tmp'
2023-03-16 14:37:20,623 DEBUG: Removing '/home/glenn/Projects/.GKTi22QwBRBYvnZLnJQW8Y.tmp'
2023-03-16 14:37:20,624 DEBUG: Removing '/home/glenn/Projects/.GKTi22QwBRBYvnZLnJQW8Y.tmp'
2023-03-16 14:37:20,624 DEBUG: Removing '/home/glenn/Projects/dvc/.dvc/cache/.oR9jKxwCthEwWrBWfHWEfp.tmp'
2023-03-16 14:37:20,631 DEBUG: Version info for developers:
DVC version: 2.50.0 (pip)
-------------------------
Platform: Python 3.10.4 on Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 0.44.1
        dvc_objects = 0.21.1
        dvc_render = 0.2.0
        dvc_task = 0.2.0
        scmrepo = 0.1.15
Supports:
        azure (adlfs = 2023.1.0, knack = 0.10.1, azure-identity = 1.12.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdc
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/2b5af32cb49e0e43fcdab0056793557a
```

### Reproduce

1. dvc init
2. Set up a non-versioned Azure storage account with hierarchical namespacing
3. dvc remote add -d myremote azure://mycontainer/path
4. dvc remote modify myremote version_aware true
5. dvc remote modify myremote --local account_name <storage_account_name>
6. dvc remote modify --local myremote connection_string <connection_string>
7. create dummy file: data/data2.csv
8. dvc add data/data2.csv
9. dvc push

### Expected

```
dvc push                          
  0% Pushing to remote 'myremote'  | dvs-test/dvc/data/data2.csv                                                                                                                                        
ERROR: while uploading 'dvs-test/dvc/data/data2.csv', support for versioning could not be detected                                                                
ERROR: failed to push data to the cloud - remote 'myremote' does not support versioning  
```

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.50.0 (pip)
-------------------------
Platform: Python 3.10.4 on Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 0.44.1
        dvc_objects = 0.21.1
        dvc_render = 0.2.0
        dvc_task = 0.2.0
        scmrepo = 0.1.15
Supports:
        azure (adlfs = 2023.1.0, knack = 0.10.1, azure-identity = 1.12.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdc
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/2b5af32cb49e0e43fcdab0056793557a
```

**Additional Information (if any):**

The data file I was trying to push was actually uploaded to Azure during this process. Once uploaded, I was able to delete the data file and cache locally, and use `dvc pull` to successfully pull the data.

As seen in the stack trace, I was also getting an error `The specified container does not exist`. I can confirm the container does exist. When setting `version_aware false`, `dvc push` worked as expected.

**Comment by pmrowla** [comment]
The issue here is that the error returned by the azure API is a generic "container does not exist" error. It does not return anything that would indicate the problem is due to versioning not being enabled on a container. The `test_versioning` function is a naive check that only works for certain cloud providers, where they will allow the API request but return null version IDs when versioning is disabled.

In azure's case, it denies the entire request with `ResourceNotFoundError: The specified container does not exist.`. There's not really any way for DVC to determine whether or not the container does in fact exist but is misconfigured. Closing this as expected behavior since we can't really do anything beyond returning the error the azure API gives us.

**Comment by skshetry** [comment]
@pmrowla, what do you think of catching FileNotFoundError?

**Comment by dberenbaum** [comment]
Can we use [BlobServiceProperties.is_versioning_enabled](https://learn.microsoft.com/en-us/python/api/azure-mgmt-storage/azure.mgmt.storage.v2022_09_01.models.blobserviceproperties?view=azure-python) (see https://stackoverflow.com/a/75635303) to check the storage account?

**Comment by glenn-t** [comment]
Thanks for looking into it. I set up a versioned Azure Storage Account, and was surprised to find I am actually getting the same problem.

```
dvc push -v
2023-03-17 07:40:22,113 DEBUG: v2.50.0 (pip), CPython 3.10.4 on Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
2023-03-17 07:40:22,113 DEBUG: command: /home/glenn/Projects/dvc/.venv/bin/dvc push -v
memory://.3S5uoEDZfTt2fyQeAubQ4B.tmp                                  
2023-03-17 07:40:22,325 DEBUG: Pushing version-aware files to 'smallcrafttrial/dvc'
100% Pushing to remote 'myremote'|█████████████████████████████████████████████████████████████████████████████████████████████████|1/1 [00:00<00:00,  2.66file/ssmallcrafttrial/dvc/data/data2.csv                                                                                                                                 
2023-03-17 07:40:22,819 ERROR: unexpected error                                                                                                                   
Traceback (most recent call last):
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 705, in _ls_blobs
    async for next_blob in blobs:
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/async_paging.py", line 149, in __anext__
    return await self.__anext__()
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/async_paging.py", line 152, in __anext__
    self._page = await self._page_iterator.__anext__()
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/async_paging.py", line 96, in __anext__
    self._response = await self._get_next(self.continuation_token)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/storage/blob/aio/_list_blobs_helper.py", line 90, in _get_next_cb
    process_storage_error(error)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 189, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/storage/blob/aio/_list_blobs_helper.py", line 83, in _get_next_cb
    return await self._command(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 79, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/storage/blob/_generated/aio/operations/_container_operations.py", line 1785, in list_blob_hierarchy_segment
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/exceptions.py", line 109, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: The specified container does not exist.
RequestId:2751f9ae-501e-0002-7536-58f1e7000000
Time:2023-03-16T18:40:22.4721674Z
ErrorCode:ContainerNotFound
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.
RequestId:2751f9ae-501e-0002-7536-58f1e7000000
Time:2023-03-16T18:40:22.4721674Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/commands/data_sync.py", line 60, in run
    processed_files_count = self.repo.push(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/repo/__init__.py", line 67, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/repo/push.py", line 50, in push
    pushed += _push_worktree(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/repo/push.py", line 119, in _push_worktree
    return push_worktree(repo, remote, targets=targets, jobs=jobs, **kwargs)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/repo/worktree.py", line 176, in push_worktree
    pushed += checkout(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc_data/index/checkout.py", line 102, in checkout
    entry.meta = test_versioning(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc_data/index/checkout.py", line 38, in test_versioning
    info = dest_fs.info(dest_path)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 473, in info
    return self.fs.info(path, **kwargs)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 506, in info
    return sync(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/fsspec/asyn.py", line 100, in sync
    raise return_result
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/fsspec/asyn.py", line 55, in _runner
    result[0] = await coro
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 561, in _info
    out = await self._ls(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 812, in _ls
    output = await self._ls_blobs(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 738, in _ls_blobs
    raise FileNotFoundError
FileNotFoundError

2023-03-17 07:40:22,835 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-03-17 07:40:22,835 DEBUG: Removing '/home/glenn/Projects/.bp9XQy9DGDgWSxdX5Gw7Gk.tmp'
2023-03-17 07:40:22,836 DEBUG: Removing '/home/glenn/Projects/.bp9XQy9DGDgWSxdX5Gw7Gk.tmp'
2023-03-17 07:40:22,836 DEBUG: Removing '/home/glenn/Projects/.bp9XQy9DGDgWSxdX5Gw7Gk.tmp'
2023-03-17 07:40:22,836 DEBUG: Removing '/home/glenn/Projects/dvc/.dvc/cache/.TLUGZuPrXbhJTDK2XzfnKi.tmp'
2023-03-17 07:40:22,846 DEBUG: Version info for developers:
DVC version: 2.50.0 (pip)
-------------------------
Platform: Python 3.10.4 on Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 0.44.1
        dvc_objects = 0.21.1
        dvc_render = 0.2.0
        dvc_task = 0.2.0
        scmrepo = 0.1.15
Supports:
        azure (adlfs = 2023.1.0, knack = 0.10.1, azure-identity = 1.12.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdc
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/2b5af32cb49e0e43fcdab0056793557a

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-03-17 07:40:22,849 DEBUG: Analytics is enabled.
2023-03-17 07:40:22,891 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpu8ewcjvi']'
2023-03-17 07:40:22,893 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpu8ewcjvi']'
```

So it pushes to the remote fine, but then fails.

Doing a little debugging:

```
> /home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc_objects/fs/base.py(475)info()
-> return self.fs.info(path, **kwargs)
(Pdb) path
'smallcrafttrial/dvc/data/data2.csv'
(Pdb) self.fs.info(path)
*** FileNotFoundError
(Pdb) self.fs.ls(path, details=True)
[]
(Pdb) self.fs.ls('smallcrafttrial/dvc/data', detail=True)
[{'metadata': {'is_directory': 'false'}, 'creation_time': datetime.datetime(2023, 3, 16, 18, 40, 22, tzinfo=datetime.timezone.utc), 'deleted': None, 'deleted_time': None, 'last_modified': datetime.datetime(2023, 3, 16, 18, 40, 22, tzinfo=datetime.timezone.utc), 'content_settings': {'content_type': 'application/octet-stream', 'content_encoding': None, 'content_language': None, 'content_md5': bytearray(b"\xfb*\xe5\xdb\x06\xef\xd8)q\x95\'\x0b\xdcO\xb6\x0b"), 'content_disposition': None, 'cache_control': None}, 'remaining_retention_days': None, 'archive_status': None, 'last_accessed_on': None, 'etag': '0x8DB264DE6722AEC', 'tags': None, 'tag_count': None, 'version_id': '2023-03-16T18:40:22.3636204Z', 'is_current_version': True, 'name': 'smallcrafttrial/dvc/data/data2.csv', 'size': 9, 'type': 'file'}]
(Pdb) self.fs.ls('smallcrafttrial/dvc/data/data2.csv', details=True)
[]
```

So the file exists in the repo, and it has a version_id, as seen when calling `self.fs.ls` on the prefix, but returns an empty list when called on the file itself.

This could be a wider issue than just an incorrectly specified remote.
