### ISSUE TITLE
dvc init: AttributeError: module 'platformdirs' has no attribute 'site_cache_dir'. Did you mean: 'site_data_dir'?

### ISSUE THREAD

**Issue by thisiswhereitype** [iterative/dvc#9199]
# Bug Report

## Description

The command errors when running against my empty git reporsitory.

### Reproduce

`dvc init`

### Environment information

**Output of `dvc doctor`:**

```console
(jupyplay) PS repo_path> dvc doctor -v
2023-03-16 13:19:02,139 DEBUG: v2.49.0 (conda), CPython 3.11.0 on Windows-10-10.0.19044-SP0
2023-03-16 13:19:02,140 DEBUG: command: conda_path\envs\jupyplay\Scripts\dvc doctor -v
2023-03-16 13:19:02,694 ERROR: unexpected error - module 'platformdirs' has no attribute 'site_cache_dir'
Traceback (most recent call last):
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\cli\__init__.py", line 210, in main
    ret = cmd.do_run()
          ^^^^^^^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\cli\command.py", line 40, in do_run
    return self.run()
           ^^^^^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\commands\version.py", line 16, in run
    dvc_info = get_dvc_info()
               ^^^^^^^^^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\info.py", line 38, in get_dvc_info
    with Repo() as repo:
         ^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\repo\__init__.py", line 212, in __init__
    os.makedirs(self.site_cache_dir, exist_ok=True)
                ^^^^^^^^^^^^^^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\funcy\objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
                                                  ^^^^^^^^^^^^^^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\repo\__init__.py", line 564, in site_cache_dir
    cache_dir = platformdirs.site_cache_dir("dvc", "iterative", opinion=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'platformdirs' has no attribute 'site_cache_dir'

Traceback (most recent call last):
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\cli\__init__.py", line 210, in main
    ret = cmd.do_run()
          ^^^^^^^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\cli\command.py", line 40, in do_run
    return self.run()
           ^^^^^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\commands\version.py", line 16, in run
    dvc_info = get_dvc_info()
               ^^^^^^^^^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\info.py", line 38, in get_dvc_info
    with Repo() as repo:
         ^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\repo\__init__.py", line 212, in __init__
    os.makedirs(self.site_cache_dir, exist_ok=True)
                ^^^^^^^^^^^^^^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\funcy\objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
                                                  ^^^^^^^^^^^^^^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\repo\__init__.py", line 564, in site_cache_dir
    cache_dir = platformdirs.site_cache_dir("dvc", "iterative", opinion=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'platformdirs' has no attribute 'site_cache_dir'. Did you mean: 'site_data_dir'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "conda_path\envs\jupyplay\Scripts\dvc-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\cli\__init__.py", line 236, in main
    ret = _log_exceptions(exc) or 255
          ^^^^^^^^^^^^^^^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\cli\__init__.py", line 145, in _log_exceptions
    _log_unknown_exceptions()
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\cli\__init__.py", line 47, in _log_unknown_exceptions
    logger.debug("Version info for developers:\n%s", get_dvc_info())
                                                     ^^^^^^^^^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\info.py", line 38, in get_dvc_info
    with Repo() as repo:
         ^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\repo\__init__.py", line 212, in __init__
    os.makedirs(self.site_cache_dir, exist_ok=True)
                ^^^^^^^^^^^^^^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\funcy\objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
                                                  ^^^^^^^^^^^^^^^^^^^
  File "conda_path\envs\jupyplay\Lib\site-packages\dvc\repo\__init__.py", line 564, in site_cache_dir
    cache_dir = platformdirs.site_cache_dir("dvc", "iterative", opinion=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'platformdirs' has no attribute 'site_cache_dir'. Did you mean: 'site_data_dir'?
```

**Additional Information (if any):**

```console
(jupyplay) PS repo_path> dvc init -v -f
2023-03-16 12:55:39,383 DEBUG: v2.49.0 (conda), CPython 3.11.0 on Windows-10-10.0.19044-SP0
2023-03-16 12:55:39,383 DEBUG: command: <conda_path>\envs\jupyplay\Scripts\dvc init -v -f
2023-03-16 12:55:39,919 ERROR: unexpected error - module 'platformdirs' has no attribute 'site_cache_dir'
Traceback (most recent call last):
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\cli\__init__.py", line 210, in main
    ret = cmd.do_run()
          ^^^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\cli\command.py", line 40, in do_run
    return self.run()
           ^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\commands\init.py", line 45, in run
    with Repo.init(
         ^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\repo\__init__.py", line 419, in init
    return init(root_dir=root_dir, no_scm=no_scm, force=force, subdir=subdir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\repo\init.py", line 76, in init
    proj = Repo(root_dir)
           ^^^^^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\repo\__init__.py", line 212, in __init__      
    os.makedirs(self.site_cache_dir, exist_ok=True)
                ^^^^^^^^^^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\funcy\objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
                                                  ^^^^^^^^^^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\repo\__init__.py", line 564, in site_cache_dir
    cache_dir = platformdirs.site_cache_dir("dvc", "iterative", opinion=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'platformdirs' has no attribute 'site_cache_dir'

Traceback (most recent call last):
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\cli\__init__.py", line 210, in main
    ret = cmd.do_run()
          ^^^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\cli\command.py", line 40, in do_run
    return self.run()
           ^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\commands\init.py", line 45, in run
    with Repo.init(
         ^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\repo\__init__.py", line 419, in init
    return init(root_dir=root_dir, no_scm=no_scm, force=force, subdir=subdir)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\repo\init.py", line 76, in init
    proj = Repo(root_dir)
           ^^^^^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\repo\__init__.py", line 212, in __init__
    os.makedirs(self.site_cache_dir, exist_ok=True)
                ^^^^^^^^^^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\funcy\objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
                                                  ^^^^^^^^^^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\repo\__init__.py", line 564, in site_cache_dir
    cache_dir = platformdirs.site_cache_dir("dvc", "iterative", opinion=True)
AttributeError: module 'platformdirs' has no attribute 'site_cache_dir'. Did you mean: 'site_data_dir'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<conda_path>\envs\jupyplay\Scripts\dvc-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\cli\__init__.py", line 236, in main
    ret = _log_exceptions(exc) or 255
          ^^^^^^^^^^^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\cli\__init__.py", line 145, in _log_exceptions
    _log_unknown_exceptions()
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\cli\__init__.py", line 47, in _log_unknown_exceptions
    logger.debug("Version info for developers:\n%s", get_dvc_info())
                                                     ^^^^^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\info.py", line 38, in get_dvc_info
    with Repo() as repo:
         ^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\repo\__init__.py", line 212, in __init__
    os.makedirs(self.site_cache_dir, exist_ok=True)
                ^^^^^^^^^^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\funcy\objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
                                                  ^^^^^^^^^^^^^^^^^^^
  File "<conda_path>\envs\jupyplay\Lib\site-packages\dvc\repo\__init__.py", line 564, in site_cache_dir
    cache_dir = platformdirs.site_cache_dir("dvc", "iterative", opinion=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'platformdirs' has no attribute 'site_cache_dir'. Did you mean: 'site_data_dir'? /
```

**Comment by thisiswhereitype** [comment]
My conda environement lists platformdirs older than needed, and it appears to be missing entirely from the conda forge build:

https://github.com/conda-forge/dvc-feedstock/blob/main/recipe/meta.yaml

**Comment by shcheklein** [comment]
@thisiswhereitype could you please try to install it again, the 2.50 is published and I think this issue should be fixed in it.

Sorry for inconvenience.

**Comment by efiop** [comment]
Not fixed yet in 2.50.0, sorry. I'll send a patch.

**Comment by efiop** [comment]
New conda package build should be out in an hour or so. Thanks for the feedback! 🙏

**Comment by dberenbaum** [comment]
@efiop @mattseddon This broke the VS Code extension for me. How do we prevent users from hitting this?

**Comment by mattseddon** [comment]
> Yes. The problem was that there was no warning from VS Code to upgrade, so it's hard for the user to know that they need to upgrade/reinstall.

We have purposefully tried to make the extension backwards compatible with as many versions as possible. We can change that policy and periodically bump our min required version.

There are breaking changes coming shortly which will force users to upgrade as well.

**Comment by efiop** [comment]
it really depends on installation, as by default conda will try to install latest platformdirs version which will work.

Here are specific conda package versions that could be affected:

2.48.0
2.49.0
2.50.0-0 (the last digit is a conda build number and 1 is fixed and should always be picked during installations. But I don't think it is visible in the `dvc doctor` or `dvc version` output)

**Comment by narbhar** [comment]
I'm having this issue when I try to do `dvc get`
The error I get is `ERROR: unexpected error - module 'platformdirs' has no attribute 'site_cache_dir'`
My DVC version is 2.53.0 and my platformdirs version is 3.2.0
