### ISSUE TITLE
ERROR: failed to reproduce 'train': failed to run: python train.py, exited with 1

### ISSUE THREAD

**Issue by bwassim** [iterative/dvc#9218]
# Bug Report

If there are no processes with such PIDs, you can manually remove 'C:\Users\ob\r\dvc_r\.dvc\tmp/rwlock' and try again.
ERROR: failed to reproduce 'train': failed to run: python train.py, exited with 1

The full output after dvc repro 
WARNING: The following untracked files were present in the workspace before saving but will not be included in the experiment commit:
        dvc.lock
WARNING:dvc.repo.experiments.save:The following untracked files were present in the workspace before saving but will not be included in the experiment commit:
        dvc.lock
Traceback (most recent call last):
  File "C:\Users\ob\r\dvc_r\train.py", line 93, in <module>
    go(args)
  File "C:\Users\ob\r\dvc_r\train.py", line 46, in go
    mlp, _ = train_and_plot(
  File "C:\Users\ob\r\dvc_r\ml\model.py", line 70, in train_and_plot
    history = mlp.fit(
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\dvclive\keras.py", line 59, in on_train_end
    self.live.end()
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\dvclive\live.py", line 373, in end
    self._experiment_rev = self._dvc_repo.experiments.save(
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\dvc\repo\experiments\__init__.py", line 470, in save
    return save(self.repo, *args, **kwargs)
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\dvc\repo\experiments\save.py", line 80, in save
    exp_rev = _save_experiment(
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\dvc\repo\experiments\save.py", line 25, in _save_experiment
    repo.commit([], force=True)
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\dvc\repo\__init__.py", line 57, in wrapper
    return f(repo, *args, **kwargs)
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\dvc\repo\commit.py", line 63, in commit
    stage.commit(filter_info=stage_info.filter_info, allow_missing=allow_missing)
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\funcy\decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\dvc\stage\decorators.py", line 35, in rwlocked
    with rwlock(
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\dvc\rwlock.py", line 212, in rwlock
    _check_blockers(tmp_dir, lock, info, mode="read", waiters=write)
  File "C:\ProgramData\MiniforgeEnvs\tf\lib\site-packages\dvc\rwlock.py", line 126, in _check_blockers
    raise LockError(
dvc.lock.LockError: 'C:\Users\ob\r\dvc_r\data\train\train_dataset.csv' is busy, it is being blocked by:
  (PID 18492): C:\ProgramData\MiniforgeEnvs\tf\Scripts\dvc repro

If there are no processes with such PIDs, you can manually remove 'C:\Users\ob\r\dvc_r\.dvc\tmp/rwlock' and try again.
ERROR: failed to reproduce 'train': failed to run: python train.py, exited with 1

### Expected

I am expected to run train stage and after predict stage, but having this error after the end of the training

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```
DVC version: 2.43.4 (pip)
-------------------------
Platform: Python 3.9.15 on Windows-10-10.0.19044-SP0
Subprojects:
        dvc_data = 0.37.8
        dvc_objects = 0.19.3
        dvc_render = 0.1.0
        dvc_task = 0.1.11
        dvclive = 2.0.2
        scmrepo = 0.1.7
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git

**Additional Information (if any):**

**Comment by pmrowla** [comment]
> dvc.lock.LockError: 'C:\Users\ob\r\dvc_r\data\train\train_dataset.csv' is busy, it is being blocked by:
> (PID 18492): C:\ProgramData\MiniforgeEnvs\tf\Scripts\dvc repro

It looks like you may have force quit a `dvc repro` process? You should be able to just remove the problematic lock file (`C:\Users\ob\r\dvc_r\.dvc\tmp\rwlock`) and then retry the DVC command that failed

**Comment by bwassim** [comment]
Also I have often this error: dvc repro
ERROR: 'C:\Users\ob\r\dvc_r\dvc.lock' is git-ignored.  Sometime it is asking me to gitignore this file and other time to include it in the gitignore. I don't understand

**Comment by pmrowla** [comment]
You need to remove it from your `.gitignore` and then git commit the change to .gitignore

**Comment by bwassim** [comment]
I see, maybe that's the reason I have all these errors. Thanks I will try that

**Comment by bwassim** [comment]
I am having in fact less errors by using dvc  exp run. Thanks for your remark. However somehow when I change a parameter in dvc.yaml and run dvc exp run again, my train stage is not triggered, any idea on why it is the case?

**Comment by bwassim** [comment]
everything works fine. Thanks again for your help
