### ISSUE TITLE
push: Authentication on gdrive not working and redirecting to localhost:8080

### ISSUE THREAD

**Issue by kevinmeetooa** [iterative/dvc#9223]
Hello, I've been using dvc for months now and I've never had any issues when using local file system storages.
However, I'm encountering a bug when using a Google Drive storage.

## Description
`dvc push` returns the following error: ERROR: unexpected error - Failed to authenticate GDrive: No code found in redirect.

A Google authentication window is then opened (DVC wants to access your account, Select what DVC can access, etc.) but when I log in, it redirects me to an empty localhost page.

### Reproduce
I've only ran basic commands:

- dvc remote add -d myremote gdrive://(my folder id)
- dvc add mydata
- dvc push

### Environment information

**Output of dvc push -v:**
```console
$ dvc push -v
2023-03-21 22:52:55,904 DEBUG: v2.51.0 (pip), CPython 3.9.12 on Linux-5.15.0-67-generic-x86_64-with-glibc2.31
2023-03-21 22:52:55,904 DEBUG: command: /home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/bin/dvc push -v
2023-03-21 22:52:56,526 DEBUG: Preparing to transfer data from '/home/kmeetooa/Documents/CODE/CML2/cml-experiments/.dvc/cache' to '1h0f3VLg4NAn_vItaBeAACn4HWFiZE51w'
2023-03-21 22:52:56,526 DEBUG: Preparing to collect status from '1h0f3VLg4NAn_vItaBeAACn4HWFiZE51w'
2023-03-21 22:52:56,526 DEBUG: Collecting status from '1h0f3VLg4NAn_vItaBeAACn4HWFiZE51w'
  0% Checking cache in '1h0f3VLg4NAn_vItaBeAACn4HWFiZE51w'| |0/? [00:00<?,    ?f/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /home/kmeetooa/.cache/pydrive2fs/710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com/default.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.appdata&access_type=offline&response_type=code&approval_prompt=force

Failed to find "code" in the query parameters of the redirect.
Try command-line authentication
2023-03-21 22:52:57,861 ERROR: unexpected error - Failed to authenticate GDrive: No code found in redirect
Traceback (most recent call last):
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/pydrive2/fs/spec.py", line 70, in _wrap_errors
    yield
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/pydrive2/fs/spec.py", line 127, in _client_auth
    auth.LocalWebserverAuth()
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/pydrive2/auth.py", line 126, in _decorated
    code = decoratee(self, *args, **kwargs)
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/pydrive2/auth.py", line 283, in LocalWebserverAuth
    raise AuthenticationError("No code found in redirect")
pydrive2.auth.AuthenticationError: No code found in redirect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc/commands/data_sync.py", line 60, in run
    processed_files_count = self.repo.push(
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc/repo/__init__.py", line 67, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc/repo/push.py", line 92, in push
    result = self.cloud.push(
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc/data_cloud.py", line 154, in push
    return self.transfer(
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc/data_cloud.py", line 135, in transfer
    return transfer(src_odb, dest_odb, objs, **kwargs)
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc_data/hashfile/transfer.py", line 203, in transfer
    status = compare_status(
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc_data/hashfile/status.py", line 178, in compare_status
    dest_exists, dest_missing = status(
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc_data/hashfile/status.py", line 149, in status
    odb.oids_exist(hashes, jobs=jobs, progress=pbar.callback)
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 408, in oids_exist
    remote_size, remote_oids = self._estimate_remote_size(
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 290, in _estimate_remote_size
    remote_oids = set(iter_with_pbar(oids))
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 280, in iter_with_pbar
    for oid in oids:
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 246, in _oids_with_limit
    for oid in self._list_oids(prefixes=prefixes, jobs=jobs):
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 233, in _list_oids
    for path in self._list_prefixes(prefixes=prefixes, jobs=jobs):
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc_objects/db.py", line 213, in _list_prefixes
    yield from self.fs.find(paths, batch_size=jobs, prefix=prefix)
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc_objects/fs/base.py", line 401, in find
    yield from self.fs.find(path)
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/funcy/objects.py", line 50, in __get__
    return prop.__get__(instance, type)
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/dvc_gdrive/__init__.py", line 105, in fs
    return _GDriveFileSystem(self._path, **self._settings)
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/pydrive2/fs/spec.py", line 226, in __init__
    google_auth = _client_auth(
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/pydrive2/fs/spec.py", line 127, in _client_auth
    auth.LocalWebserverAuth()
  File "/home/kmeetooa/anaconda3/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/kmeetooa/Documents/CODE/CML2/cml-experiments/venv/lib/python3.9/site-packages/pydrive2/fs/spec.py", line 76, in _wrap_errors
    raise GDriveAuthError("Failed to authenticate GDrive") from exc
pydrive2.fs.spec.GDriveAuthError: Failed to authenticate GDrive

2023-03-21 22:52:57,908 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-03-21 22:52:57,908 DEBUG: Removing '/home/kmeetooa/Documents/CODE/CML2/.AFMWS7k7Qoa3TTS2Q83prx.tmp'
2023-03-21 22:52:57,908 DEBUG: Removing '/home/kmeetooa/Documents/CODE/CML2/.AFMWS7k7Qoa3TTS2Q83prx.tmp'
2023-03-21 22:52:57,908 DEBUG: Removing '/home/kmeetooa/Documents/CODE/CML2/.AFMWS7k7Qoa3TTS2Q83prx.tmp'
2023-03-21 22:52:57,908 DEBUG: Removing '/home/kmeetooa/Documents/CODE/CML2/cml-experiments/.dvc/cache/.nakxnhAo2TWUpZivx9suA8.tmp'
2023-03-21 22:52:57,913 DEBUG: Version info for developers:
DVC version: 2.51.0 (pip)
-------------------------
Platform: Python 3.9.12 on Linux-5.15.0-67-generic-x86_64-with-glibc2.31
Subprojects:
	dvc_data = 0.44.1
	dvc_objects = 0.21.1
	dvc_render = 0.3.1
	dvc_task = 0.2.0
	scmrepo = 0.1.15
Supports:
	azure (adlfs = 2023.1.0, knack = 0.10.1, azure-identity = 1.12.0),
	gdrive (pydrive2 = 1.15.1),
	gs (gcsfs = 2023.3.0),
	hdfs (fsspec = 2023.3.0, pyarrow = 11.0.0),
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	oss (ossfs = 2021.8.0),
	s3 (s3fs = 2023.3.0, boto3 = 1.24.59),
	ssh (sshfs = 2023.1.0),
	webdav (webdav4 = 0.9.8),
	webdavs (webdav4 = 0.9.8),
	webhdfs (fsspec = 2023.3.0)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/vgubuntu-root
Caches: local
Remotes: gdrive
Workspace directory: ext4 on /dev/mapper/vgubuntu-root
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/7ffa4036f3d221c6d6caa04119dc082b

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-03-21 22:52:57,915 DEBUG: Analytics is enabled.
2023-03-21 22:52:57,953 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpy5exdrv8']'
2023-03-21 22:52:57,955 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpy5exdrv8']'

```

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.51.0 (pip)
-------------------------
Platform: Python 3.9.12 on Linux-5.15.0-67-generic-x86_64-with-glibc2.31
Subprojects:
	dvc_data = 0.44.1
	dvc_objects = 0.21.1
	dvc_render = 0.3.1
	dvc_task = 0.2.0
	scmrepo = 0.1.15
Supports:
	azure (adlfs = 2023.1.0, knack = 0.10.1, azure-identity = 1.12.0),
	gdrive (pydrive2 = 1.15.1),
	gs (gcsfs = 2023.3.0),
	hdfs (fsspec = 2023.3.0, pyarrow = 11.0.0),
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	oss (ossfs = 2021.8.0),
	s3 (s3fs = 2023.3.0, boto3 = 1.24.59),
	ssh (sshfs = 2023.1.0),
	webdav (webdav4 = 0.9.8),
	webdavs (webdav4 = 0.9.8),
	webhdfs (fsspec = 2023.3.0)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/vgubuntu-root
Caches: local
Remotes: gdrive
Workspace directory: ext4 on /dev/mapper/vgubuntu-root
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/7ffa4036f3d221c6d6caa04119dc082b
```

**Additional Information (if any):**
I've tried running `pip install -U "dvc[all]"` to no avail. Any ideas that might help? Thanks in advance.

**Comment by kevinmeetooa** [comment]
Proxy issue fixed by unsetting HTTP_PROXY, HTTPS_PROXY, http_proxy and https_proxy environment variables
