### ISSUE TITLE
dvc.api.open: PermissionError: [Errno 13] Permission denied: '/var/tmp/dvc/repo/475b80c28a5e0a63dd53f2b187988dce'

### ISSUE THREAD

**Issue by Guillaume-oso** [iterative/dvc#9247]
# Bug Report

Hi, got an error with ```dvc.api.open```

 

## Description

```
Traceback (most recent call last):                                                                                                                                                                                                   
  File "dvcapi.py", line 3, in <module>
    with dvc.api.open(
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/guillaume/.venv/lib/python3.8/site-packages/dvc/api/data.py", line 198, in _open
    with _repo.open_by_relpath(
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/guillaume/.venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 605, in open_by_relpath
    remote_odb = self.cloud.get_remote_odb(name=remote)
  File "/home/guillaume/.venv/lib/python3.8/site-packages/dvc/data_cloud.py", line 105, in get_remote_odb
    remote = self.get_remote(name=name, command=command)
  File "/home/guillaume/.venv/lib/python3.8/site-packages/dvc/data_cloud.py", line 79, in get_remote
    if self.repo.data_index is not None:
  File "/home/guillaume/.venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 375, in data_index
    os.makedirs(index_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/tmp/dvc/repo/475b80c28a5e0a63dd53f2b187988dce'
```

### Reproduce

```
import dvc.api

with dvc.api.open(
    path="data/my_data",
    repo=f"git@github.com:oso-ai/my_repo.git",
    remote="storage",
    mode="r",
    encoding=None,
) as f:
    print(f.read())
```

### Expected

to print my data (works woth dvc[s3]==2.41)

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.51.0 (pip)
-------------------------
Platform: Python 3.8.10 on Linux-5.8.0-38-generic-x86_64-with-glibc2.29
Subprojects:
        dvc_data = 0.44.1
        dvc_objects = 0.21.1
        dvc_render = 0.3.1
        dvc_task = 0.2.0
        scmrepo = 0.1.17
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.3.0, boto3 = 1.24.59)
```

**Additional Information (if any):**

**Comment by daavoo** [comment]
Hi @Guillaume-oso , can you try removing `/var/tmp/dvc` as per https://github.com/iterative/dvc/issues/9184#issuecomment-1470002516 ?

**Comment by efiop** [comment]
@Guillaume-oso Are you working on a shared server? Or is this your personal machine? Could you show permissions on `/var/tmp/dvc` and `/var/tmp/dvc/repo` to see if it belongs to you?

**Comment by Guillaume-oso** [comment]
Hi, it works on after removing `/var/tmp/dvc`
I work on a shared server, that's probably why it does not work if somebody executed that command before me.
Thanks!
I close the issue, looks duplicated with the one you mentioned

**Comment by Guillaume-oso** [comment]
ok, thanks for the precisions!
