### ISSUE TITLE
exp push: breaking in GHA

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9290]
# Bug Report

## Description

`dvc exp push --rev HEAD` is breaking in GitHub Actions. The log is in https://github.com/iterative/lstm_seq2seq/actions/runs/4559164229/jobs/8042811435#step:7:4777.

### Reproduce

Try to run the action in https://github.com/iterative/lstm_seq2seq/actions/workflows/cml.yaml from the `debug` branch (to get verbose output).

Note that I could not reproduce it locally, even from a shallow clone or detached head.

**Comment by daavoo** [comment]
This is what I get inside the codespace (git push from CLI works):

<details>
<summary>`dulwich.errors.HangupException: The remote server unexpectedly closed the connection.`</summary>
```
2023-04-04 12:26:08,432 DEBUG: v2.52.1.dev12+gcf52efb8, CPython 3.10.10 on Linux-5.4.0-1105-azure-x86_64-with-glibc2.31
2023-04-04 12:26:08,432 DEBUG: command: /workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/bin/dvc exp remove -A -g origin -vv
2023-04-04 12:26:08,433 TRACE: Namespace(cprofile=False, yappi=False, yappi_separate_threads=False, viztracer=False, viztracer_depth=None, viztracer_async=False, cprofile_dump=None, pdb=False, instrument=False, instrument_open=False, show_stack=False, quiet=0, verbose=2, cd='.', cmd='remove', all_commits=True, rev=None, num=1, queue=False, git_remote='origin', experiment=[], func=<class 'dvc.commands.experiments.remove.CmdExperimentsRemove'>, parser=DvcParser(prog='dvc', usage=None, description='Data Version Control', formatter_class=<class 'argparse.RawTextHelpFormatter'>, conflict_handler='error', add_help=False))
2023-04-04 12:26:10,148 ERROR: unexpected error - The remote server unexpectedly closed the connection.                                                                                                 
Traceback (most recent call last):
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/dvc/commands/experiments/remove.py", line 31, in run
    removed = self.repo.experiments.remove(
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/dvc/repo/experiments/__init__.py", line 506, in remove
    return remove(self.repo, *args, **kwargs)
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/dvc/repo/__init__.py", line 65, in wrapper
    return f(repo, *args, **kwargs)
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/dvc/repo/scm_context.py", line 151, in run
    return method(repo, *args, **kw)
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/dvc/repo/experiments/remove.py", line 71, in remove
    _remove_commited_exps(repo.scm, exp_ref_list, git_remote)
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/dvc/repo/experiments/remove.py", line 112, in _remove_commited_exps
    push_refspec(
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/dvc/repo/experiments/utils.py", line 167, in push_refspec
    results = scm.push_refspecs(
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 286, in _backend_func
    result = func(*args, **kwargs)
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 571, in push_refspecs
    client.send_pack(
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/dulwich/client.py", line 2054, in send_pack
    ref_status = self._handle_receive_pack_tail(
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/dulwich/client.py", line 881, in _handle_receive_pack_tail
    for chan, data in _read_side_band64k_data(proto.read_pkt_seq()):
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/dulwich/client.py", line 458, in _read_side_band64k_data
    for pkt in pkt_seq:
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/dulwich/protocol.py", line 271, in read_pkt_seq
    pkt = self.read_pkt_line()
  File "/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.venv/lib/python3.10/site-packages/dulwich/protocol.py", line 214, in read_pkt_line
    raise HangupException()
dulwich.errors.HangupException: The remote server unexpectedly closed the connection.

2023-04-04 12:26:10,249 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-04-04 12:26:10,249 DEBUG: Removing '/workspaces/example-repos-dev/example-get-started-experiments/build/.D69g23EAEMabcCHqmaow5u.tmp'
2023-04-04 12:26:10,249 DEBUG: Removing '/workspaces/example-repos-dev/example-get-started-experiments/build/.D69g23EAEMabcCHqmaow5u.tmp'
2023-04-04 12:26:10,249 DEBUG: Removing '/workspaces/example-repos-dev/example-get-started-experiments/build/.D69g23EAEMabcCHqmaow5u.tmp'
2023-04-04 12:26:10,250 DEBUG: Removing '/workspaces/example-repos-dev/example-get-started-experiments/build/example-get-started-experiments/.dvc/cache/.dRHZfWAaMPuhj4t4EBZiYD.tmp'
2023-04-04 12:26:10,257 DEBUG: Version info for developers:
DVC version: 2.52.1.dev12+gcf52efb8
-----------------------------------
Platform: Python 3.10.10 on Linux-5.4.0-1105-azure-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 0.47.1
        dvc_objects = 0.21.1
        dvc_render = 0.3.1
        dvc_task = 0.2.0
        scmrepo = 0.2.0
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.3.0, boto3 = 1.24.59)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/loop0
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/loop0
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/8320f4256dcd8a001d3e3ee03150ad17

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-04-04 12:26:10,258 DEBUG: Analytics is enabled.
2023-04-04 12:26:10,318 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpaei65x3b']'
2023-04-04 12:26:10,320 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpaei65x3b']'
```
</details>

**Comment by pmrowla** [comment]
Just an FYI that `dvc exp remove -g ...` is unsupported in codespaces, the github access token generated for a codespace does not have delete permissions. (This can be verified by trying `git push --delete refs/exps/...` in the codespace)

**Comment by daavoo** [comment]
> I'm assuming it's possible to configure codespaces to use a specific token, in which case `exp remove -g origin` would work as long as the token had the appropriate delete permissions.

Yes, the `example-repos-dev` is correctly configured so `exp remove -g` and `exp push` both work:

https://github.com/iterative/example-repos-dev/blob/dcfd76301af427f9cc33f7e3e6248fa68669d16b/.devcontainer.json#L20-L22

**Comment by kyrylogy** [comment]
Hi! Is this fixed? I'm still running into the same issue, seems like hashes are somehow getting mixed up when running `dvc exp push` with pre-configured remote origin. Problem persists for me even after updating scmrepo>=0.2.1 and DVC version: 2.53.0

Here's my log: 

https://github.com/kyrylogy/dvc-test/actions/runs/4627560834/jobs/8185613736

**Comment by pmrowla** [comment]
@kyrylogy can you try setting `fetch-depth: 0` in your `actions/checkout` step (see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches)

**Comment by kyrylogy** [comment]
> @kyrylogy can you try setting `fetch-depth: 0` in your `actions/checkout` step (see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches)

Huge thanks for a quick reply, works like a charm!

**Comment by dberenbaum** [comment]
@pmrowla When do you expect users need to set the fetch depth? I thought it was no longer needed?

**Comment by pmrowla** [comment]
> @pmrowla When do you expect users need to set the fetch depth? I thought it was no longer needed?

It's not needed for `exp run` and `exp apply`.

`git push` (and `exp push`) depends on git history that may or may not be available in shallow repos. I haven't tested to see if it's actually possible to manually `git push` exp refs from an `actions/checkout` GHA workflow (with the default shallow `fetch-depth: 1`), but in general any time you need to `git push` anything in GHA I'm pretty sure the recommendation is to use `fetch-depth: 0`.

**Comment by dberenbaum** [comment]
`git push` works in the [same GHA](https://github.com/iterative/lstm_seq2seq/actions/runs/4671620766/jobs/8272831487), and as noted above, `exp push` works locally from both a shallow clone and detached head. This is important because `dvc exp push` can be a better workflow than `git push` in CI, but only if it can be a drop-in replacement.

**Comment by pmrowla** [comment]
It looks like git push does work, so this is probably due to dulwich's shallow ref support being incomplete. I'll start looking into it but it may be non-trivial to fix (shallow repo support is complicated, there's a reason libgit2 still hasn't implemented any shallow support at all)

In the meantime the suggested workflow for using `exp push` in CI should be to just use `fetch-depth: 0`

**Comment by pmrowla** [comment]
@dberenbaum I'm not sure that this workflow will actually do what you are intending though. If you run an experiment in a github actions PR with the default `actions/checkout` workflow, HEAD in the pull request is the merge commit generated by github (`refs/pull/###/merge`), and not the actual tip of the PR branch (`refs/pull/###/head`).

So the resulting experiment will be derived from the pull request merge commit (and not from some commit on your original `main` branch).

To illustrate this, the linked run from my example-get-started fork creates an experiment derived from `716deb4` (the PR merge commit). The tip of my PR `ci-push-test` branch is actually `66610db`

```
$ dvc exp list origin -A
716deb4:
        pmrowla-test
```

Even if I pull the experiment and then do `exp show -A` I will not be able to see the experiment since it does not actually belong to any of the branches in my repo (the PR merge commit generated by github is essentially a dangling merge commit that does not belong to any branch)

If you want the experiment to actually derive from the tip of the PR branch, users need to explicitly tell github to not use the merge ref in their GHA workflow
```
- uses: actions/checkout@v3
  with:
    ref: ${{ github.event.pull_request.head.sha }}
```
(see https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit)

**Comment by dberenbaum** [comment]
Thanks, @pmrowla. That's only for actions that trigger on PR, right? Is it an issue for other triggers like `workflow_dispatch` or `push`? I think in most cases we will be suggesting those triggers and then opening a PR after seeing the pushed experiment results.

Even for a PR, I think it is not ideal but still works, especially if interacting through Studio. We already have to account for "phantom" experiments like this in Studio where the user hasn't pushed the local branch or most recent commits, so I don't think there's anything uniquely challenging about showing these in Studio unless I'm missing something. Studio will also have an action to create a branch and PR from that experiment row, so it should be possible to use this experiment even if it doesn't belong to any branch.

**Comment by pmrowla** [comment]
Yes, that's specifically for actions triggered by a PR. On `push` it should be using the tip of the pushed branch.
