### ISSUE TITLE
An error occurred(404) when calling the ListObjectsV2 operation

### ISSUE THREAD

**Issue by duany049** [iterative/dvc#9318]
# Bug Report

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```
# Below is the info while call dvc status -c -vv

```
2023-04-10 17:21:33,135 ERROR: unexpected error - Not Found: An error occurred (404) when calling the ListObjectsV2 operation: Not Found                                                                                                                                          
------------------------------------------------------------
Traceback (most recent call last):
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/s3fs/core.py", line 698, in _lsdir
    async for i in it:
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/aiobotocore/paginate.py", line 30, in __anext__
    response = await self._make_request(current_kwargs)
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/aiobotocore/client.py", line 358, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the ListObjectsV2 operation: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/cli/__init__.py", line 90, in main
    ret = cmd.do_run()
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/commands/status.py", line 63, in run
    recursive=self.args.recursive,
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/repo/status.py", line 132, in status
    recursive=True,
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/repo/status.py", line 97, in _cloud_status
    obj_ids, jobs, remote=remote, log_missing=False
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/data_cloud.py", line 155, in status
    cache_odb=self.repo.odb.local,
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/data/status.py", line 181, in compare_status
    dest, obj_ids, index=dest_index, jobs=jobs, **kwargs
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/data/status.py", line 151, in status
    odb.hashes_exist(hashes, jobs=jobs, progress=pbar.callback)
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/objects/db.py", line 404, in hashes_exist
    hashes, progress=estimator_cb
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/objects/db.py", line 272, in _estimate_remote_size
    remote_hashes = set(iter_with_pbar(hashes))
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/objects/db.py", line 260, in iter_with_pbar
    for hash_ in hashes:
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/objects/db.py", line 226, in _hashes_with_limit
    for hash_ in self._list_hashes(prefix):
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/objects/db.py", line 216, in _list_hashes
    for path in self._list_paths(prefix):
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/objects/db.py", line 200, in _list_paths
    yield from self.fs.find(self.fs.path.join(*parts), prefix=bool(prefix))
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/dvc/fs/base.py", line 491, in find
    files = self.fs.find(with_prefix, prefix=self.path.parts(path)[-1])
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/fsspec/asyn.py", line 113, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/fsspec/asyn.py", line 98, in sync
    raise return_result
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/s3fs/core.py", line 774, in _find
    out = await self._lsdir(path, delimiter="", prefix=prefix)
  File "/root/anaconda3/envs/py3torch18/lib/python3.7/site-packages/s3fs/core.py", line 725, in _lsdir
    raise translate_boto_error(e)
FileNotFoundError: Not Found
------------------------------------------------------------

2023-04-10 17:21:33,351 DEBUG: Version info for developers:
DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.7.7 on Linux-5.15.0-69-generic-x86_64-with-debian-bullseye-sid
Supports:
	webhdfs (fsspec = 2022.11.0),
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2022.11.0, boto3 = 1.24.59)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/sda2
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-04-10 17:21:33,352 DEBUG: Analytics is enabled.
2023-04-10 17:21:33,378 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpwe1wxgp0']'

2023-04-10 17:21:33,379 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpwe1wxgp0']'
```

**Comment by efiop** [comment]
@duany049 Could you check that the bucket exists?
