### ISSUE TITLE
any command: unexpected error - attempt to write a readonly database

### ISSUE THREAD

**Issue by mstrupp** [iterative/dvc#9379]
# Bug Report

## Description

All DVC CLI commands return `ERROR: unexpected error - attempt to write a readonly database`.

@shcheklein linked [this](https://discuss.dvc.org/t/multiple-users-in-one-repo/746/5) discussion on discord but it didn't help to change the file permissions.
Even when I delete the `.dvc` folder and run `dvc init` again, the error still exists.

I was only able to get DVC to work again by downgrading to version `2.52.0`.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
ERROR: unexpected error - attempt to write a readonly database

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

**Output of `dvc doctor` after downgrade:**

```console
$ dvc doctor
DVC version: 2.52.0 (pip)
-------------------------
Platform: Python 3.9.16 on Windows-10-10.0.19045-SP0
Subprojects:
        dvc_data = 0.46.0
        dvc_objects = 0.21.2
        dvc_render = 0.3.1
        dvc_task = 0.2.1
        scmrepo = 0.2.1
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: local
Workspace directory: NTFS on C:\
Repo: dvc, git
Repo.site_cache_dir: C:\ProgramData\iterative\dvc\Cache\repo\41762bfd7f32a1edf2ac2edefc84196e

You are using dvc version 2.52.0; however, version 2.55.0 is available.
To upgrade, run 'pip install --upgrade dvc'.
```

**Output of `dvc doctor -v`:**

```console
$ dvc doctor -v
2023-04-28 09:55:18,468 DEBUG: v2.55.0 (pip), CPython 3.9.16 on Windows-10-10.0.19045-SP0
2023-04-28 09:55:18,468 DEBUG: command: C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\Scripts\dvc version -v
2023-04-28 09:55:19,766 ERROR: unexpected error - attempt to write a readonly database
Traceback (most recent call last):
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\cli\__init__.py", line 210, in main     
    ret = cmd.do_run()
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\cli\command.py", line 40, in do_run     
    return self.run()
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\commands\version.py", line 16, in run   
    dvc_info = get_dvc_info()
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\info.py", line 38, in get_dvc_info      
    with Repo() as repo:
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\repo\__init__.py", line 214, in __init__
    self.state = State(self.root_dir, self.site_cache_dir, self.dvcignore)
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc_data\hashfile\state.py", line 89, in __init__
    self.links = Cache(links_dir)
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc_data\hashfile\cache.py", line 59, in __init__
    super().__init__(
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\diskcache\core.py", line 499, in __init__
    sql(query, (key, value))
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\diskcache\core.py", line 666, in _execute_with_retry
    return sql(statement, *args, **kwargs)
sqlite3.OperationalError: attempt to write a readonly database

Traceback (most recent call last):
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\cli\__init__.py", line 210, in main
    ret = cmd.do_run()
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\cli\command.py", line 40, in do_run
    return self.run()
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\commands\version.py", line 16, in run
    dvc_info = get_dvc_info()
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\info.py", line 38, in get_dvc_info
    with Repo() as repo:
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\repo\__init__.py", line 214, in __init__
    self.state = State(self.root_dir, self.site_cache_dir, self.dvcignore)
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc_data\hashfile\state.py", line 89, in __init__
    self.links = Cache(links_dir)
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc_data\hashfile\cache.py", line 59, in __init__
    super().__init__(
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\diskcache\core.py", line 499, in __init__
    sql(query, (key, value))
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\diskcache\core.py", line 666, in _execute_with_retry
    return sql(statement, *args, **kwargs)
sqlite3.OperationalError: attempt to write a readonly database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\Scripts\dvc.exe\__main__.py", line 7, in <module>
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\cli\__init__.py", line 236, in main
    ret = _log_exceptions(exc) or 255
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\cli\__init__.py", line 145, in _log_exceptions
    _log_unknown_exceptions()
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\cli\__init__.py", line 47, in _log_unknown_exceptions
    logger.debug("Version info for developers:\n%s", get_dvc_info())
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\info.py", line 38, in get_dvc_info
    with Repo() as repo:
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc\repo\__init__.py", line 214, in __init__
    self.state = State(self.root_dir, self.site_cache_dir, self.dvcignore)
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc_data\hashfile\state.py", line 89, in __init__
    self.links = Cache(links_dir)
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\dvc_data\hashfile\cache.py", line 59, in __init__
    super().__init__(
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\diskcache\core.py", line 499, in __init__
    sql(query, (key, value))
  File "C:\Users\michael.strupp\AppData\Local\miniconda3\envs\tf\lib\site-packages\diskcache\core.py", line 666, in _execute_with_retry
    return sql(statement, *args, **kwargs)
sqlite3.OperationalError: attempt to write a readonly database
```

**Comment by efiop** [comment]
@mstrupp Could you try deleting `C:\ProgramData\iterative\dvc\Cache\repo\41762bfd7f32a1edf2ac2edefc84196e` and trying again with the newest version?

**Comment by mstrupp** [comment]
@efiop I deleted the folder but the error persists.

**Comment by efiop** [comment]
@mstrupp That is expected as the key is determined by the path (and more stuff). Try deleting whole `C:\ProgramData\iterative\dvc` and switch to the newest dvc right away. That should work.

Are there multiple users on this machine or something?

**Comment by mstrupp** [comment]
@efiop That fixed it. Thank you!

It's just one user on the machine. I remeber that recently, the antivirus software temporarily blocked python.exe and might have crashed DVC while running some commands. That possibly messed something up.

Is it possible to show a more descriptive error message when the corrupted cache occurs?

**Comment by mstrupp** [comment]
Everything works again after restarting my PC. The problem might have been on my end.
