### ISSUE TITLE
dvc.api.open: disregards cache folder from config 

### ISSUE THREAD

**Issue by aftersought** [iterative/dvc#9382]
# Bug Report

## Description

Opening a file using `dvc.api.open()` from local repo fails with `FileMissingError: Can't find ... neither locally nor on remote`. By printing out the searched paths in DVC library, I see that DVC tries to locate the file in `dvccache/02/cb7babaadc7e5f1cca32d784587902` subfolder of the project folder. The `02/cb7babaadc7e5f1cca32d784587902` is correct relative path of the file, but there is no cache in this repo with the default name (it is in another folder, with a different name). Here is the relevant part of the .dvc/config:
```
[cache]
    type = "reflink,symlink"
    dir = ../../dvc-cache
    shared = group
```

### Reproduce
```
with dvc.api.open("file.csv", rev=branch_name) as f:
    print(f)
```
where file.csv is tracked by DVC.

### Environment information

```console
$ dvc doctor
DVC version: 2.38.1 (pip)
---------------------------------
Platform: Python 3.10.9 on Linux-6.0.16-200.fc36.x86_64-x86_64-with-glibc2.35
Subprojects:
        dvc_data = 0.28.4
        dvc_objects = 0.14.0
        dvc_render = 0.0.15
        dvc_task = 0.1.8
        dvclive = 1.3.2
        scmrepo = 0.1.4
Supports:
        gs (gcsfs = 2022.11.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: reflink, hardlink, symlink
Cache directory: btrfs on /dev/sdb
Caches: local
Remotes: gs
Workspace directory: btrfs on /dev/sdb
Repo: dvc, git
```

**Comment by dberenbaum** [comment]
Confirmed that DVC will only look in the default cache location, not the shared cache location specified in the config.

Thanks for the report @aftersought.

**Comment by dberenbaum** [comment]
Also confirmed the same error with `DVCFileSystem`:

```python
>>> from dvc.api import DVCFileSystem
>>> fs = DVCFileSystem(".", rev="main")
>>> with fs.open("file.csv") as f:
...     print(f)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/fsspec/spec.py", line 1106, in open
    f = self._open(
  File "/Users/dave/Code/dvc/dvc/fs/dvc.py", line 262, in _open
    return dvc_fs.open(dvc_path, mode=mode, **kw)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 194, in open
    return self.fs.open(path, mode=mode, **kwargs)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_data/fs.py", line 71, in open
    fs, typ, fspath = self._get_fs_path(path, **kwargs)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_data/fs.py", line 65, in _get_fs_path
    raise FileNotFoundError
FileNotFoundError
```

**Comment by pmrowla** [comment]
This appears to have been fixed. I can reproduce the issue in 2.38.1, but cannot reproduce it in current 3.x main, or in 2.58.2
