### ISSUE TITLE
missing cloud-versioned data error not helpful

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9447]
When I do a `dvc pull` for https://github.com/iterative/iterative.ai/, I get:

```bash
$ dvc pull
ERROR: unexpected error - The specified version does not exist.: An error occurred (NoSuchVersion) when calling the GetObject operation: The specified version does not exist.
```

With `-v`, I get:

```bash
$ dvc pull -v
2023-05-12 14:00:17,363 DEBUG: v2.55.1.dev12+g77f82090c, CPython 3.10.6 on macOS-13.3.1-arm64-arm-64bit
2023-05-12 14:00:17,363 DEBUG: command: /Users/dave/miniforge3/bin/dvc pull -v
2023-05-12 14:00:18,580 DEBUG: Removing '/Users/dave/Code/iterative.ai/.dvc/cache/e1/.7yEDHBqMtrgvbFL8kUxvTk.tmp'
2023-05-12 14:00:18,584 ERROR: unexpected error - The specified version does not exist.: An error occurred (NoSuchVersion) when calling the GetObject operation: The specified version does not exist.
Traceback (most recent call last):
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/s3fs/core.py", line 112, in _error_wrapper
    return await func(*args, **kwargs)
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/aiobotocore/client.py", line 358, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (NoSuchVersion) when calling the GetObject operation: The specified version does not exist.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dave/Code/dvc/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/Users/dave/Code/dvc/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/Users/dave/Code/dvc/dvc/commands/data_sync.py", line 31, in run
    stats = self.repo.pull(
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 65, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/pull.py", line 35, in pull
    processed_files_count = self.fetch(
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 65, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/fetch.py", line 73, in fetch
    transferred_count += _fetch_worktree(
  File "/Users/dave/Code/dvc/dvc/repo/fetch.py", line 197, in _fetch_worktree
    downloaded += fetch_worktree(repo, remote, targets=targets, jobs=jobs, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/worktree.py", line 129, in fetch_worktree
    transferred += save(index, callback=cb, jobs=jobs, storage="remote")
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/dvc_data/index/save.py", line 137, in save
    transferred += cache.add(
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/dvc_data/hashfile/db/__init__.py", line 113, in add
    transferred = super().add(
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/dvc_objects/db.py", line 175, in add
    generic.transfer(
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/dvc_objects/fs/generic.py", line 307, in transfer
    _try_links(
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/dvc_objects/fs/generic.py", line 247, in _try_links
    return copy(from_fs, from_path, to_fs, to_path, callback=callback)
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/dvc_objects/fs/generic.py", line 93, in copy
    return _get(
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/dvc_objects/fs/generic.py", line 197, in _get
    return _get_one(from_paths[0], to_paths[0])
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/dvc_objects/fs/generic.py", line 189, in _get_one
    return get_file(from_path, tmp_file, callback=callback)
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/dvc_objects/fs/callbacks.py", line 69, in func
    return wrapped(path1, path2, **kw)
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/dvc_objects/fs/callbacks.py", line 41, in wrapped
    res = fn(*args, **kwargs)
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 522, in get_file
    self.fs.get_file(from_info, to_info, callback=callback, **kwargs)
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/fsspec/asyn.py", line 113, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/fsspec/asyn.py", line 98, in sync
    raise return_result
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/s3fs/core.py", line 1134, in _get_file
    body, content_length = await _open_file(range=0)
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/s3fs/core.py", line 1125, in _open_file
    resp = await self._call_s3(
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/s3fs/core.py", line 339, in _call_s3
    return await _error_wrapper(
  File "/Users/dave/miniforge3/lib/python3.10/site-packages/s3fs/core.py", line 139, in _error_wrapper
    raise err
FileNotFoundError: The specified version does not exist.

2023-05-12 14:00:18,633 DEBUG: Removing '/Users/dave/Code/.TyYZmy24Ar2UMtV3fz8e5b.tmp'
2023-05-12 14:00:18,633 DEBUG: Removing '/Users/dave/Code/.TyYZmy24Ar2UMtV3fz8e5b.tmp'
2023-05-12 14:00:18,634 DEBUG: Removing '/Users/dave/Code/.TyYZmy24Ar2UMtV3fz8e5b.tmp'
2023-05-12 14:00:18,634 DEBUG: Removing '/Users/dave/Code/iterative.ai/.dvc/cache/.mNehLjmbL4vCLLchyjGXDh.tmp'
2023-05-12 14:00:18,816 DEBUG: Version info for developers:
DVC version: 2.55.1.dev12+g77f82090c
------------------------------------
Platform: Python 3.10.6 on macOS-13.3.1-arm64-arm-64bit
Subprojects:
        dvc_data = 0.47.2
        dvc_objects = 0.21.1
        dvc_render = 0.3.1
        dvc_task = 0.2.0
        scmrepo = 1.0.2
Supports:
        azure (adlfs = 2022.10.0, knack = 0.10.0, azure-identity = 1.11.0),
        gdrive (pydrive2 = 1.15.3),
        gs (gcsfs = 2022.11.0),
        hdfs (fsspec = 2022.11.0, pyarrow = 9.0.0),
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2022.11.0, boto3 = 1.24.59),
        ssh (sshfs = 2023.4.1),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2022.11.0)
Config:
        Global: /Users/dave/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/e4247a13e500df28823f6bc74fd46080
```

Neither tell me what file was being fetched or what version of that file was missing. Can we include that info with the error?

**Comment by dberenbaum** [comment]
The context here is that one file was missing from many, so it would be helpful to identify which file was missing. Lowering the priority, but it's still important.
