### ISSUE TITLE
exp run: unable to start a new experiment

### ISSUE THREAD

**Issue by mattseddon** [iterative/dvc#9454]
# Bug Report

## Description

Cannot run experiments with a fresh install of DVC 2.56.0

### Reproduce

1. clone vscode-dvc-demo
2. create a virtual environment and install dependencies
3. dvc pull
4. dvc exp run -S 'params.yaml:lr=0.005'
5. experiment will fail with unexpected error

### Expected

Experiment will run as expected

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.56.0 (pip)
-------------------------
Platform: Python 3.10.6 on macOS-13.3.1-arm64-arm-64bit
Subprojects:
        dvc_data = 0.47.5
        dvc_objects = 0.22.0
        dvc_render = 0.5.0
        dvc_task = 0.2.1
        scmrepo = 1.0.3
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.5.0, boto3 = 1.26.76)
Config:
        Global: /Users/mattseddon/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/9b2d1355ef26cb2a38a704c54d1f3710
```

**Additional Information (if any):**

```
❯ dvc exp run -S 'params.yaml:lr=0.005' --verbose                                                                            ✘ 255  .env  base 07:54:43
2023-05-16 07:54:48,868 DEBUG: v2.56.0 (pip), CPython 3.10.6 on macOS-13.3.1-arm64-arm-64bit
2023-05-16 07:54:48,869 DEBUG: command: /Users/mattseddon/projects/vscode-dvc/demo/.env/bin/dvc exp run -S params.yaml:lr=0.005 --verbose
2023-05-16 07:54:49,217 DEBUG: Using experiment params '{'params.yaml': ['lr=0.005']}'
2023-05-16 07:54:49,286 DEBUG: built tree 'object c6587323f82a17504d6e1adf2d2e77f4.dir'                                                                                                      
2023-05-16 07:54:49,286 DEBUG: Computed stage: 'data.dvc' md5: 'None'
2023-05-16 07:54:49,289 DEBUG: built tree 'object c6587323f82a17504d6e1adf2d2e77f4.dir'                                                                                                      
2023-05-16 07:54:49,289 DEBUG: Preparing to transfer data from 'memory://dvc-staging/b271f7e1db9c5291c1d7e33cba29dde64dbff080f23206f42f016cb283570d33' to '/Users/mattseddon/projects/vscode-dvc/demo/.dvc/cache'
2023-05-16 07:54:49,290 DEBUG: Preparing to collect status from '/Users/mattseddon/projects/vscode-dvc/demo/.dvc/cache'
2023-05-16 07:54:49,290 DEBUG: Collecting status from '/Users/mattseddon/projects/vscode-dvc/demo/.dvc/cache'
2023-05-16 07:54:49,291 DEBUG: Saving information to 'data.dvc'.                                                                                                                             
2023-05-16 07:54:49,307 ERROR: unexpected error - 'token'
Traceback (most recent call last):
  File "/Users/mattseddon/projects/vscode-dvc/demo/.env/lib/python3.10/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/Users/mattseddon/projects/vscode-dvc/demo/.env/lib/python3.10/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/Users/mattseddon/projects/vscode-dvc/demo/.env/lib/python3.10/site-packages/dvc/commands/experiments/run.py", line 29, in run
    results = self.repo.experiments.run(
  File "/Users/mattseddon/projects/vscode-dvc/demo/.env/lib/python3.10/site-packages/dvc/repo/experiments/__init__.py", line 479, in run
    return run(self.repo, *args, **kwargs)
  File "/Users/mattseddon/projects/vscode-dvc/demo/.env/lib/python3.10/site-packages/dvc/repo/__init__.py", line 65, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/mattseddon/projects/vscode-dvc/demo/.env/lib/python3.10/site-packages/dvc/repo/experiments/run.py", line 72, in run
    return repo.experiments.reproduce_one(
  File "/Users/mattseddon/projects/vscode-dvc/demo/.env/lib/python3.10/site-packages/dvc/repo/experiments/__init__.py", line 128, in reproduce_one
    self.queue_one(exp_queue, **kwargs)
  File "/Users/mattseddon/projects/vscode-dvc/demo/.env/lib/python3.10/site-packages/dvc/repo/experiments/__init__.py", line 165, in queue_one
    return self.new(
  File "/Users/mattseddon/projects/vscode-dvc/demo/.env/lib/python3.10/site-packages/dvc/repo/experiments/__init__.py", line 279, in new
    return queue.put(*args, **kwargs)
  File "/Users/mattseddon/projects/vscode-dvc/demo/.env/lib/python3.10/site-packages/dvc/repo/experiments/queue/workspace.py", line 37, in put
    return self._stash_exp(*args, **kwargs)
  File "/Users/mattseddon/projects/vscode-dvc/demo/.env/lib/python3.10/site-packages/dvc/repo/experiments/queue/base.py", line 424, in _stash_exp
    studio_token, studio_repo_url = get_studio_token_and_repo_url()
  File "/Users/mattseddon/projects/vscode-dvc/demo/.env/lib/python3.10/site-packages/dvc_studio_client/post_live_metrics.py", line 65, in get_studio_token_and_repo_url
    return config["token"], config["repo_url"]
KeyError: 'token'

2023-05-16 07:54:49,359 DEBUG: Removing '/Users/mattseddon/projects/vscode-dvc/.5zeVHk62cBNLfVajkpYYAQ.tmp'
2023-05-16 07:54:49,359 DEBUG: Removing '/Users/mattseddon/projects/vscode-dvc/.5zeVHk62cBNLfVajkpYYAQ.tmp'
2023-05-16 07:54:49,359 DEBUG: Removing '/Users/mattseddon/projects/vscode-dvc/.5zeVHk62cBNLfVajkpYYAQ.tmp'
2023-05-16 07:54:49,360 DEBUG: Removing '/Users/mattseddon/projects/vscode-dvc/demo/.dvc/cache/.f6SkEYnh7sXvm7Rtqzyybz.tmp'
2023-05-16 07:54:49,361 DEBUG: Version info for developers:
DVC version: 2.56.0 (pip)
-------------------------
Platform: Python 3.10.6 on macOS-13.3.1-arm64-arm-64bit
Subprojects:
        dvc_data = 0.47.5
        dvc_objects = 0.22.0
        dvc_render = 0.5.0
        dvc_task = 0.2.1
        scmrepo = 1.0.3
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.5.0, boto3 = 1.26.76)
Config:
        Global: /Users/mattseddon/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/9b2d1355ef26cb2a38a704c54d1f3710

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-05-16 07:54:49,362 DEBUG: Analytics is enabled.
2023-05-16 07:54:49,436 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/sb/fqcw44jd19nfrhl_9lz_81d80000gn/T/tmpnz063q2v']'
2023-05-16 07:54:49,438 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/sb/fqcw44jd19nfrhl_9lz_81d80000gn/T/tmpnz063q2v']'
```
Error first identified by E2E tests: https://github.com/iterative/vscode-dvc/actions/runs/4985384678 (see screenshots)

**Comment by shcheklein** [comment]
@dberenbaum might be related to the very recent release of the https://github.com/iterative/dvc-studio-client. Is it breaking compatibility by chance?

**Comment by mattseddon** [comment]
I can confirm pinning `dvc-studio-client==0.9.0` fixes the issue.

**Comment by dberenbaum** [comment]
Taking a look.

**Comment by dberenbaum** [comment]
Sorry about that. Should be fixed in https://github.com/iterative/dvc-studio-client/pull/37. If someone with permission can review and merge, I'd appreciate it.
