### ISSUE TITLE
DVC list FileNotFoundError

### ISSUE THREAD

**Issue by george-kuanli-peng** [iterative/dvc#9564]
# Bug Report

`dvc ls -v --dvc-only . ./.git : gives "ERROR: unexpected error"`

## Description

Although it is fixed in #7120, I still have the same proglem. I'm using dvc 2.58.2 and runnig the command in a bind-mount within Docker container.

### Reproduce

1. dvc ls --dvc-only . ./.git

### Expected

The command should print nothing and exit with code 0.

### Environment information

**Output of `dvc doctor`:**

```console
# dvc doctor
DVC version: 2.58.2 (pip)
-------------------------
Platform: Python 3.8.10 on Linux-5.4.0-84-generic-x86_64-with-glibc2.10
Subprojects:
        dvc_data = 0.51.0
        dvc_objects = 0.22.0
        dvc_render = 0.5.3
        dvc_task = 0.2.1
        scmrepo = 1.0.3
Supports:
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.5.0, boto3 = 1.26.76)
Config:
        Global: /mlsteam/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: xfs on /dev/sdb1
Caches: local
Remotes: s3
Workspace directory: xfs on /dev/sdb1
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/481f8aaf689cfdbdb632a79cd882e7b2
```

**Additional Information (if any):**

**Output of `dvc ls -v --dvc-only . ./.git`**

```console
# dvc ls -v --dvc-only . ./.git
2023-06-08 05:21:12,500 DEBUG: v2.58.2 (pip), CPython 3.8.10 on Linux-5.4.0-84-generic-x86_64-with-glibc2.10
2023-06-08 05:21:12,500 DEBUG: command: /opt/conda/bin/dvc ls -v --dvc-only . ./.git
2023-06-08 05:21:13,766 ERROR: unexpected error
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/opt/conda/lib/python3.8/site-packages/dvc/cli/command.py", line 40, in do_run
    return self.run()
  File "/opt/conda/lib/python3.8/site-packages/dvc/commands/ls/__init__.py", line 31, in run
    entries = Repo.ls(
  File "/opt/conda/lib/python3.8/site-packages/dvc/repo/ls.py", line 43, in ls
    ret = _ls(repo, path, recursive, dvc_only)
  File "/opt/conda/lib/python3.8/site-packages/dvc/repo/ls.py", line 62, in _ls
    fs_path = fs.info(fs_path)["name"]
  File "/opt/conda/lib/python3.8/site-packages/dvc_objects/fs/base.py", line 495, in info
    return self.fs.info(path, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dvc/fs/dvc.py", line 330, in info
    return self._info(key, path, ignore_subrepos=ignore_subrepos)
  File "/opt/conda/lib/python3.8/site-packages/dvc/fs/dvc.py", line 371, in _info
    raise FileNotFoundError
FileNotFoundError

2023-06-08 05:21:14,088 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-06-08 05:21:14,089 DEBUG: Removing '/mlsteam/data/fake-dvc-folder/.h6zNuTjqCP27BUAf7kUcjL.tmp'
2023-06-08 05:21:14,089 DEBUG: Removing '/mlsteam/data/fake-dvc-folder/.h6zNuTjqCP27BUAf7kUcjL.tmp'
2023-06-08 05:21:14,089 DEBUG: Removing '/mlsteam/data/fake-dvc-folder/.h6zNuTjqCP27BUAf7kUcjL.tmp'
2023-06-08 05:21:14,089 DEBUG: Removing '/mlsteam/data/fake-dvc-folder/VC-Blank-project/.dvc/cache/.RSrF8hqGZ9PAi9bjAWPUtj.tmp'
2023-06-08 05:21:14,099 DEBUG: Version info for developers:
DVC version: 2.58.2 (pip)
-------------------------
Platform: Python 3.8.10 on Linux-5.4.0-84-generic-x86_64-with-glibc2.10
Subprojects:
        dvc_data = 0.51.0
        dvc_objects = 0.22.0
        dvc_render = 0.5.3
        dvc_task = 0.2.1
        scmrepo = 1.0.3
Supports:
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.5.0, boto3 = 1.26.76)
Config:
        Global: /mlsteam/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: xfs on /dev/sdb1
Caches: local
Remotes: s3
Workspace directory: xfs on /dev/sdb1
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/481f8aaf689cfdbdb632a79cd882e7b2

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-06-08 05:21:14,103 DEBUG: Analytics is enabled.
2023-06-08 05:21:14,169 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpvc13_99d']'
2023-06-08 05:21:14,171 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpvc13_99d']'
```

**Comment by efiop** [comment]
@george-kuanli-peng The error is a bit cryptic, but it is expected behaviour - you are trying to list dvc-tracked files in `.git`, which is not seen by `--dvc-only` at all. Could you elaborate on what you are trying to accomplish?

**Comment by george-kuanli-peng** [comment]
> @george-kuanli-peng The error is a bit cryptic, but it is expected behaviour - you are trying to list dvc-tracked files in `.git`, which is not seen by `--dvc-only` at all. Could you elaborate on what you are trying to accomplish?

Hi @efiop , I'm implementing a function that reports which files / directories are tracked by DVC under a user-specified directory. And I happen to know `dvc ls --dvc-only` has such a problem, which seems to have the same symptons as in #7120.

Additional to `.git`, `dvc ls --dvc-only` also produces the same error for `.dvc`. But the same command works well (that is, it outputs nothing and exits with 0) for other *normal* directories not tracked by DVC.

**Comment by george-kuanli-peng** [comment]
Currently, I make a workaround by skipping such an error. But it looks like a bug for a DVC user if it outputs `"ERROR: unexpected error"`. If `dvc ls --dvc-only` is not expected to support this use case, a more concrete error message would be better.

**Comment by efiop** [comment]
@george-kuanli-peng Both `.dvc` and `.git` are expected to not be seen by `dvc list` as those are git and dvc internal files that it has no business viewing. Not sure I understand why you need to list them, seems like you just need to catch `dvc list` error here and that is an indicator that those files are not tracked by dvc.

**Comment by george-kuanli-peng** [comment]
Users may want to see the `dvc list` results under any direcory within a project, and `.dvc/` and `.git/` are just two of them. The workaround I use is actually cating this `dvc list` error as your suggestion.

My point is this command has different behaviors for files/directories not tracked by DVC:
1. `dvc ls --dvc-only . ./.git` reports `unexpected error`
1. `dvc ls --dvc-only . ./.abc` (where `.abc/` is not tracked by DVC) reports empty result

Users may not understand the error is caused by attempting to listing files not tracked by DVC if they only see `unexpected error`, but the behavior of **case 2** makes more sense for this error cause. If **case 1** (reporting an error) is considered appropriate for this command, then giving a more specific error description or at least mentioning it in documentation would avoid user's confusion.
