### ISSUE TITLE
Hitting `assert self.is_in_repo` in dvc push after 3.0 upgrade

### ISSUE THREAD

**Issue by Erotemic** [iterative/dvc#9621]
# Bug Report

When trying to push a new file after upgradeing to 3.0 I'm hitting an unxexpected error, and the logs give no indication of what's going on. It's possible I've done something wrong, but at the very least the error message should be improved. I'm creating a PR to make a start on this.

The issue might be due to the dvc cache living in an external directory. I'm not exactly sure.  The traceback I'm getting with a new improved error message is:

```
2023-06-16 16:08:22,858 ERROR: unexpected error - Unexpected error
self.def_path='Drop7-MedianNoWinter10GSD_landcover_invar_scratch_split6_V65_epoch5_stepNone.pt'
self.repo=Repo: '/data/projects/smart/smart_expt_dvc'
self.repo.root_dir='/data/projects/smart/smart_expt_dvc'
self.fs_path='/data/projects/smart/smart_expt_dvc/models/fusion/Drop7-MedianNoWinter10GSD/packages/Drop7-MedianNoWinter10GSD_landcover_invar_scratch_split6_V65/Drop7-MedianNoWinter10GSD_landcover_invar_scratch_split6_V65_epoch5_stepNone.pt'
self.fs.path.realpath(self.fs_path)='/data/dvc-caches/smart_expt_dvc_cache/files/md5/c5/e09b8697020d86f077b0a24425f4cc'
Traceback (most recent call last):
  File "/home/local/KHQ/jon.crall/code/dvc/dvc/cli/__init__.py", line 209, in main
    ret = cmd.do_run()
  File "/home/local/KHQ/jon.crall/code/dvc/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/home/local/KHQ/jon.crall/code/dvc/dvc/commands/data_sync.py", line 60, in run
    processed_files_count = self.repo.push(
  File "/home/local/KHQ/jon.crall/code/dvc/dvc/repo/__init__.py", line 64, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/local/KHQ/jon.crall/code/dvc/dvc/repo/push.py", line 63, in push
    used = self.used_objs(
  File "/home/local/KHQ/jon.crall/code/dvc/dvc/repo/__init__.py", line 491, in used_objs
    for odb, objs in self.index.used_objs(
  File "/home/local/KHQ/jon.crall/code/dvc/dvc/repo/index.py", line 480, in used_objs
    for odb, objs in stage.get_used_objs(
  File "/home/local/KHQ/jon.crall/code/dvc/dvc/stage/__init__.py", line 743, in get_used_objs
    for odb, objs in out.get_used_objs(*args, **kwargs).items():
  File "/home/local/KHQ/jon.crall/code/dvc/dvc/output.py", line 1154, in get_used_objs
    obj = self.get_obj(filter_info=kwargs.get("filter_info"))
  File "/home/local/KHQ/jon.crall/code/dvc/dvc/output.py", line 912, in get_obj
    obj = oload(self.cache, self.hash_info)
  File "/home/local/KHQ/jon.crall/code/dvc/dvc/output.py", line 529, in cache
    raise AssertionError('\n'.join([
AssertionError: Unexpected error
self.def_path='Drop7-MedianNoWinter10GSD_landcover_invar_scratch_split6_V65_epoch5_stepNone.pt'
self.repo=Repo: '/data/projects/smart/smart_expt_dvc'
self.repo.root_dir='/data/projects/smart/smart_expt_dvc'
self.fs_path='/data/projects/smart/smart_expt_dvc/models/fusion/Drop7-MedianNoWinter10GSD/packages/Drop7-MedianNoWinter10GSD_landcover_invar_scratch_split6_V65/Drop7-MedianNoWinter10GSD_landcover_invar_scratch_split6_V65_epoch5_stepNone.pt'
self.fs.path.realpath(self.fs_path)='/data/dvc-caches/smart_expt_dvc_cache/files/md5/c5/e09b8697020d86f077b0a24425f4cc'
```

This is indicating that `Drop7-MedianNoWinter10GSD_landcover_invar_scratch_split6_V65_epoch5_stepNone.pt'` is not in the repo path because the cache lives outside of the repo?

I'm not sure if this is a bug or if I messed something up somehow. I'll note that have found a workaround. If I unprotect the file that my error message reports, it seems to be able to get to the next one. I had to do this for several files (although not every file in the repo, thankfully), but as eventually able to get a push to work. 

### Reproduce
I'm not sure how to reproduce the bug at this time. 

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 3.0.1.dev8+gfd73b389
---------------------------------
Platform: Python 3.10.5 on Linux-5.15.0-69-generic-x86_64-with-glibc2.31
Subprojects:
	dvc_data = 1.11.0
	dvc_objects = 0.23.0
	dvc_render = 0.5.3
	dvc_task = 0.3.0
	scmrepo = 1.0.3
Supports:
	azure (adlfs = 2023.4.0, knack = 0.9.0, azure-identity = 1.10.0),
	gdrive (pydrive2 = 1.15.4),
	gs (gcsfs = 2023.6.0),
	hdfs (fsspec = 2023.6.0, pyarrow = 8.0.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
	oss (ossfs = 2021.8.0),
	s3 (s3fs = 2023.6.0, boto3 = 1.26.76),
	ssh (sshfs = 2023.4.1),
	webdav (webdav4 = 0.9.7),
	webdavs (webdav4 = 0.9.7),
	webhdfs (fsspec = 2023.6.0)
Config:
	Global: /home/local/KHQ/jon.crall/.config/dvc
	System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/md0
Caches: local
Remotes: s3, ssh
Workspace directory: ext4 on /dev/md0
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/a0457bedea4e28e1518387be0506369e
```

**Comment by Erotemic** [comment]
I think this is likely a bug with out-of-repo cache directories (i.e. shared caches between multiple different DVC repos on the same machine). I moved my external cache into `<repo>/.dvc/cache`, and then symlinked the old location to the new location, and the errors went away.

**Comment by efiop** [comment]
Yeah, looks like it is a symlink that confuses `is_in_repo` implementation. Looks like if we don't `realpath` it - it works fine. Preparing a patch to see if nothing else will get triggered.

**Comment by efiop** [comment]
@Erotemic Could you please give an upstream dvc a try?

**Comment by Erotemic** [comment]
Unfortunately, I manually worked around the bug by moving my cache, so I don't have an easy way to check it anymore. But the fix sounds like it will work as long you wearn't relying on other realpath behavior.

**Comment by Erotemic** [comment]
@efiop I had a repo on a different machine that experienced the same issue. An ugprade to 3.1.0 seemed to fix it. :tada:

**Comment by efiop** [comment]
@Erotemic Thank you for the feedback! 🙏

**Comment by diogo-sr** [comment]
Hi. I have just installed `v3.2.2` and I get the issue mentioned in this thread. The structure of my project is:

```
├── src
│   ├── dvc.yaml
│   ├── .dvc
│   │   ├── cache
│   ├── datasets (only contains my *.dvc files)
│   │   ├── *.dvc
```

If I try to run either `dvc  pull` or `dvc repro` I get the error mentioned above:

```
2023-06-27 11:53:43,744 ERROR: failed to reproduce 'split_data@0':    
Traceback (most recent call last):
  File "/home/dmartins/workspaces/dl_train/env/lib/python3.9/site-packages/dvc/repo/reproduce.py", line 177, in _reproduce_stages
    ret = _reproduce_stage(stage, **kwargs)
  File "/home/dmartins/workspaces/dl_train/env/lib/python3.9/site-packages/dvc/repo/reproduce.py", line 25, in _reproduce_stage
    stage = stage.reproduce(**kwargs)
  File "/home/dmartins/workspaces/dl_train/env/lib/python3.9/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/dmartins/workspaces/dl_train/env/lib/python3.9/site-packages/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
  File "/home/dmartins/workspaces/dl_train/env/lib/python3.9/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/dmartins/workspaces/dl_train/env/lib/python3.9/site-packages/dvc/stage/__init__.py", line 436, in reproduce
    self.run(**kwargs)
  File "/home/dmartins/workspaces/dl_train/env/lib/python3.9/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/dmartins/workspaces/dl_train/env/lib/python3.9/site-packages/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
  File "/home/dmartins/workspaces/dl_train/env/lib/python3.9/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/dmartins/workspaces/dl_train/env/lib/python3.9/site-packages/dvc/stage/__init__.py", line 621, in run
    self.save(
  File "/home/dmartins/workspaces/dl_train/env/lib/python3.9/site-packages/dvc/stage/__init__.py", line 479, in save
    self.save_outs(allow_missing=allow_missing)
  File "/home/dmartins/workspaces/dl_train/env/lib/python3.9/site-packages/dvc/stage/__init__.py", line 517, in save_outs
    out.save()
  File "/home/dmartins/workspaces/dl_train/env/lib/python3.9/site-packages/dvc/output.py", line 698, in save
    self.cache,
  File "/home/dmartins/workspaces/dl_train/env/lib/python3.9/site-packages/dvc/output.py", line 528, in cache
    assert self.is_in_repo
AssertionError

```


Output of `dvc doctor`:

```
DVC version: 3.2.2 (conda)
--------------------------
Platform: Python 3.9.15 on Linux-5.15.0-1036-gcp-x86_64-with-glibc2.31
Subprojects:
	dvc_data = 2.3.0
	dvc_objects = 0.23.0
	dvc_render = 0.5.3
	dvc_task = 0.3.0
	scmrepo = 1.0.4
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	ssh (sshfs = 2023.4.1)
Config:
	Global: /home/dmartins/.config/dvc
	System: /etc/xdg/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/sda1
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/76a8e028e4ca12bea0b1db4e68b94632

```

**Comment by efiop** [comment]
@diogo-sr Do you use external outputs?

**Comment by diogo-sr** [comment]
Thanks for the prompt reply. Yes and I had actually recently changed the logging to be outside of the repo. I have re-adjusted it to be inside the repo (because of your reply) and it works :smile:

**Comment by efiop** [comment]
Looks like we should handle this better, I'll try to improve the error soon.

**Comment by alealv** [comment]
Got the same problem. Removing external dependencies seems to have fixed it.
