### ISSUE TITLE
pull: error when pulling both pipeline and .dvc files

### ISSUE THREAD

**Issue by bakaleks** [iterative/dvc#9658]
# Bug Report

## Description
After upgrade to v3 usual 'dvc pull' produces error
`ERROR: failed to pull data from the cloud - Checkout failed for following targets:``
Remote is in Azure Blob Storage.

The project is a data pipeline with dvc.yaml together with some .dvc files located in the *data* folder.

When doing `pull` separately on data files and pipeline files everything works:
```bash
dvc pull data/*.dvc
dvc pull dvc.yaml
dvc pull                                                           
Everything is up to date.                                    
```

When issuing single `dvc pull` on a freshly cloned repo:
`ERROR: failed to pull data from the cloud - Checkout failed for following targets:``
with some additional DEBUG around cache folder:
```log
2023-06-23 15:39:57,489 DEBUG: failed to create {/workspaces/file} from {/workspaces/dir/.dvc/cache/cf/351f6f3ba7d97cd62200747a655567} - [Errno 2] No such file or directory: '/workspaces/dir/.dvc/cache/cf/351f6f3ba7d97cd62200747a655567'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
```

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.2.1 ({args.pkg})
-------------------------------
Platform: Python 3.10.8 on Linux-3.10.0-1160.90.1.el7.x86_64-x86_64-with-glibc2.31
Subprojects:

Supports:
        azure (adlfs = 2023.4.0, knack = 0.10.1, azure-identity = 1.13.0),
        gdrive (pydrive2 = 1.16.0),
        gs (gcsfs = 2023.6.0),
        hdfs (fsspec = 2023.6.0, pyarrow = 12.0.1),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2023.6.0, boto3 = 1.26.76),
        ssh (sshfs = 2023.4.1),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2023.6.0)
Config:
        Global: /home/cd4tll/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: xfs on /dev/mapper/rootvg-home_lv
Caches: local
Remotes: azure
Workspace directory: xfs on /dev/mapper/rootvg-home_lv
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/8b6039cdff44fbe624cf728424568da8
```

**Additional Information (if any):**

**Comment by efiop** [comment]
Hi @bakaleks ,

could you post full verbose log, please? That debug message that you've included is just saying that there is no file with such hash, but the error should be higher in the log.

Also, which package did you install dvc from? I see `{args.pkg}` which means we have a bug in one of out package building scripts 🤦

**Comment by bakaleks** [comment]
I installed it via 'apt install' in Debian. One more stacktrace that I found when running 'dvc pull -vvv':
```py
2023-06-26 09:53:11,856 ERROR: failed to pull data from the cloud - Checkout failed for following targets:
.....
Is your cache up to date?
<https://error.dvc.org/missing-files>
Traceback (most recent call last):
  File "dvc/commands/data_sync.py", line 31, in run
  File "dvc/repo/__init__.py", line 64, in wrapper
  File "dvc/repo/pull.py", line 41, in pull
  File "dvc/repo/__init__.py", line 64, in wrapper
  File "dvc/repo/checkout.py", line 204, in checkout
dvc.exceptions.CheckoutError: Checkout failed for following targets:
```

**Comment by efiop** [comment]
> I installed it via 'apt install' in Debian

Wait, there is some kind of mistake. The `doctor` above clearly tells us that you are using an `el7` kernel, which is red hat and not debian.

> There is no error higher in the log btw

There should be an error or a warning or something. Please post full verbose log.

**Comment by bakaleks** [comment]
We use Redhat as host OS and run 'dvc pull' in a Debian Docker container, that's why el7 kernel. Here is a complete debug log(I removed some file content that was dump to the console):
```bash
$ dvc pull -vvvv
2023-06-26 09:53:02,880 DEBUG: v3.2.1 ({args.pkg}), CPython 3.10.8 on Linux-3.10.0-1160.90.1.el7.x86_64-x86_64-with-glibc2.31
2023-06-26 09:53:02,880 DEBUG: command: pull -vvvv
2023-06-26 09:53:02,880 TRACE: Namespace(cprofile=False, yappi=False, yappi_separate_threads=False, viztracer=False, viztracer_depth=None, viztracer_async=False, cprofile_dump=None, pdb=False, instrument=False, instrument_open=False, show_stack=False, quiet=0, verbose=4, cd='.', cmd='pull', jobs=None, targets=[], remote=None, all_branches=False, all_tags=False, all_commits=False, force=False, with_deps=False, recursive=False, run_cache=False, glob=False, allow_missing=False, func=<class 'dvc.commands.data_sync.CmdDataPull'>, parser=DvcParser(prog='dvc', usage=None, description='Data Version Control', formatter_class=<class 'argparse.RawTextHelpFormatter'>, conflict_handler='error', add_help=False))
2023-06-26 09:53:03,227 TRACE: Context during resolution of .....
2023-06-26 09:53:03,252 TRACE:    76.16 ms in collecting stages from /workspaces/pipeline_repo
.....(removed file content here)
2023-06-26 09:53:03,511 DEBUG: Preparing to transfer data from 'dvc/pipeline_repo' to '/workspaces/pipeline_repo/.dvc/cache'
2023-06-26 09:53:03,511 DEBUG: Preparing to collect status from '/workspaces/pipeline_repo/.dvc/cache'
2023-06-26 09:53:03,511 DEBUG: Collecting status from '/workspaces/pipeline_repo/.dvc/cache'
2023-06-26 09:53:03,518 DEBUG: Preparing to transfer data from 'dvc/pipeline_repo/files/md5' to '/workspaces/pipeline_repo/.dvc/cache/files/md5'
2023-06-26 09:53:03,519 DEBUG: Preparing to collect status from '/workspaces/pipeline_repo/.dvc/cache/files/md5'
2023-06-26 09:53:03,519 DEBUG: Collecting status from '/workspaces/pipeline_repo/.dvc/cache/files/md5'
2023-06-26 09:53:03,521 DEBUG: Creating external repo https://github.com/company/data-registry.git@4b952bcfead75c51aa162d46a95461a49577cba4
2023-06-26 09:53:03,521 DEBUG: erepo: git clone 'https://github.com/company/data-registry.git' to a temporary dir
2023-06-26 09:53:11,615 TRACE:     9.64 ms in collecting stages from /                                                 
2023-06-26 09:53:11,615 TRACE:     5.83 mks in collecting stages from /.vscode
2023-06-26 09:53:11,797 DEBUG: failed to create {/workspaces/pipeline_repo/report/report_f.html} from {/workspaces/pipeline_repo/.dvc/cache/bb/3b0be4e3045002db1209fa2830bf5d} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/bb/3b0be4e3045002db1209fa2830bf5d'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/bb/3b0be4e3045002db1209fa2830bf5d'

2023-06-26 09:53:11,798 DEBUG: failed to create {/workspaces/pipeline_repo/data/datafile1.csv} from {/workspaces/pipeline_repo/.dvc/cache/files/md5/ab/b539bd3eb33ef95b3cc63382370fe0} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/files/md5/ab/b539bd3eb33ef95b3cc63382370fe0'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/files/md5/ab/b539bd3eb33ef95b3cc63382370fe0'

2023-06-26 09:53:11,799 DEBUG: failed to create {/workspaces/pipeline_repo/data/datafile2.csv} from {/workspaces/pipeline_repo/.dvc/cache/files/md5/a1/614543951f7c61188ac60b5fb3f2c1} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/files/md5/a1/614543951f7c61188ac60b5fb3f2c1'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/files/md5/a1/614543951f7c61188ac60b5fb3f2c1'

2023-06-26 09:53:11,799 DEBUG: failed to create {/workspaces/pipeline_repo/data/datafile3.csv} from {/workspaces/pipeline_repo/.dvc/cache/files/md5/c0/a5120fd3bbffef6220e307eb39d092} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/files/md5/c0/a5120fd3bbffef6220e307eb39d092'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/files/md5/c0/a5120fd3bbffef6220e307eb39d092'

2023-06-26 09:53:11,800 DEBUG: failed to create {/workspaces/pipeline_repo/data/datafile4.csv} from {/workspaces/pipeline_repo/.dvc/cache/12/50d790404cbe2fa694f2007b3416ea} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/12/50d790404cbe2fa694f2007b3416ea'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/12/50d790404cbe2fa694f2007b3416ea'

2023-06-26 09:53:11,800 DEBUG: failed to create {/workspaces/pipeline_repo/data/datafile6.csv} from {/workspaces/pipeline_repo/.dvc/cache/22/775e5e1e473c0fec362c65cdb18919} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/22/775e5e1e473c0fec362c65cdb18919'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/22/775e5e1e473c0fec362c65cdb18919'

2023-06-26 09:53:11,801 DEBUG: failed to create {/workspaces/pipeline_repo/data/datafile5.csv} from {/workspaces/pipeline_repo/.dvc/cache/files/md5/d4/9c090321c786f0618795c8c3c645d5} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/files/md5/d4/9c090321c786f0618795c8c3c645d5'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/files/md5/d4/9c090321c786f0618795c8c3c645d5'

2023-06-26 09:53:11,801 DEBUG: failed to create {/workspaces/pipeline_repo/data/datafile7.csv} from {/workspaces/pipeline_repo/.dvc/cache/files/md5/c1/987a7c61440a94e147977b3e0bf429} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/files/md5/c1/987a7c61440a94e147977b3e0bf429'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/files/md5/c1/987a7c61440a94e147977b3e0bf429'

2023-06-26 09:53:11,802 DEBUG: failed to create {/workspaces/pipeline_repo/report/f/vega_streamlit/analysis/spline__var1.json} from {/workspaces/pipeline_repo/.dvc/cache/cf/351f6f3ba7d97cd62200747a655567} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/cf/351f6f3ba7d97cd62200747a655567'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/cf/351f6f3ba7d97cd62200747a655567'

2023-06-26 09:53:11,802 DEBUG: failed to create {/workspaces/pipeline_repo/report/f/vega_streamlit/marginal/intercept.json} from {/workspaces/pipeline_repo/.dvc/cache/11/74a612c1ad23a0e29ef06f7f81c566} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/11/74a612c1ad23a0e29ef06f7f81c566'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/11/74a612c1ad23a0e29ef06f7f81c566'

2023-06-26 09:53:11,803 DEBUG: failed to create {/workspaces/pipeline_repo/report/f/vega_streamlit/marginal/spline__var1.json} from {/workspaces/pipeline_repo/.dvc/cache/bc/674a65ff5119ff1d5e415022ee65e8} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/bc/674a65ff5119ff1d5e415022ee65e8'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/bc/674a65ff5119ff1d5e415022ee65e8'

2023-06-26 09:53:11,803 DEBUG: failed to create {/workspaces/pipeline_repo/report/f/vega_streamlit/overview/predictions_distribution.json} from {/workspaces/pipeline_repo/.dvc/cache/4c/da9893bd166fb272169cd6c6fc654c} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/4c/da9893bd166fb272169cd6c6fc654c'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/4c/da9893bd166fb272169cd6c6fc654c'

2023-06-26 09:53:11,804 DEBUG: failed to create {/workspaces/pipeline_repo/report/f/vega_streamlit/overview/quantile_plot.json} from {/workspaces/pipeline_repo/.dvc/cache/bc/5ee80fbb8bba8d2abc008913d4044f} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/bc/5ee80fbb8bba8d2abc008913d4044f'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/bc/5ee80fbb8bba8d2abc008913d4044f'

2023-06-26 09:53:11,804 DEBUG: failed to create {/workspaces/pipeline_repo/report/f/vega_streamlit/overview/total_level.json} from {/workspaces/pipeline_repo/.dvc/cache/2e/2a51c6ed94c6e3e7c5be4432daf07d} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/2e/2a51c6ed94c6e3e7c5be4432daf07d'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/2e/2a51c6ed94c6e3e7c5be4432daf07d'

2023-06-26 09:53:11,805 DEBUG: failed to create {/workspaces/pipeline_repo/report/f/vega_html/marginal/spline__var1.json} from {/workspaces/pipeline_repo/.dvc/cache/39/393b5c19fb1f88a6ab7bf72bdb67e0} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/39/393b5c19fb1f88a6ab7bf72bdb67e0'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/39/393b5c19fb1f88a6ab7bf72bdb67e0'

2023-06-26 09:53:11,805 DEBUG: failed to create {/workspaces/pipeline_repo/report/f/vega_html/marginal/intercept.json} from {/workspaces/pipeline_repo/.dvc/cache/11/74a612c1ad23a0e29ef06f7f81c566} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/11/74a612c1ad23a0e29ef06f7f81c566'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/11/74a612c1ad23a0e29ef06f7f81c566'

2023-06-26 09:53:11,806 DEBUG: failed to create {/workspaces/pipeline_repo/report/f/vega_html/overview/quantile_plot.json} from {/workspaces/pipeline_repo/.dvc/cache/49/18fff6aaf81bc0ae4993a2c714b59a} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/49/18fff6aaf81bc0ae4993a2c714b59a'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/49/18fff6aaf81bc0ae4993a2c714b59a'

2023-06-26 09:53:11,806 DEBUG: failed to create {/workspaces/pipeline_repo/report/f/vega_html/overview/total_level.json} from {/workspaces/pipeline_repo/.dvc/cache/2e/2a51c6ed94c6e3e7c5be4432daf07d} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/2e/2a51c6ed94c6e3e7c5be4432daf07d'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/2e/2a51c6ed94c6e3e7c5be4432daf07d'

2023-06-26 09:53:11,808 DEBUG: failed to create {/workspaces/pipeline_repo/report/f/vega_html/overview/predictions_distribution.json} from {/workspaces/pipeline_repo/.dvc/cache/41/22359850d63d8912098d245ecefd58} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/41/22359850d63d8912098d245ecefd58'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/41/22359850d63d8912098d245ecefd58'

2023-06-26 09:53:11,809 DEBUG: failed to create {/workspaces/pipeline_repo/report/f/vega_html/analysis/spline__var1.json} from {/workspaces/pipeline_repo/.dvc/cache/96/1aaa80c588cc7c3732f62ef49c0d63} - [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/96/1aaa80c588cc7c3732f62ef49c0d63'
Traceback (most recent call last):
  File "dvc_objects/fs/generic.py", line 306, in transfer
  File "dvc_objects/fs/generic.py", line 250, in _try_links
  File "dvc_objects/fs/generic.py", line 62, in _link
  File "dvc_objects/fs/base.py", line 389, in reflink
  File "dvc_objects/fs/local.py", line 169, in reflink
  File "dvc_objects/fs/system.py", line 105, in reflink
  File "dvc_objects/fs/system.py", line 90, in _reflink_linux
FileNotFoundError: [Errno 2] No such file or directory: '/workspaces/pipeline_repo/.dvc/cache/96/1aaa80c588cc7c3732f62ef49c0d63'

2023-06-26 09:53:11,810 DEBUG: Removing '/workspaces/pipeline_repo/report/f'
2023-06-26 09:53:11,855 DEBUG: Removing '/workspaces/pipeline_repo/report/report_f.html'
2023-06-26 09:53:11,855 DEBUG: Removing '/workspaces/pipeline_repo/data/datafile1.csv'
2023-06-26 09:53:11,855 DEBUG: Removing '/workspaces/pipeline_repo/data/datafile2.csv'
2023-06-26 09:53:11,855 DEBUG: Removing '/workspaces/pipeline_repo/data/datafile3.csv'
2023-06-26 09:53:11,856 DEBUG: Removing '/workspaces/pipeline_repo/data/datafile4.csv'
2023-06-26 09:53:11,856 DEBUG: Removing '/workspaces/pipeline_repo/data/datafile6.csv'
2023-06-26 09:53:11,856 DEBUG: Removing '/workspaces/pipeline_repo/data/datafile5.csv'
2023-06-26 09:53:11,856 DEBUG: Removing '/workspaces/pipeline_repo/data/datafile7.csv'
Everything is up to date.
2023-06-26 09:53:11,856 ERROR: failed to pull data from the cloud - Checkout failed for following targets:
report/report_f.html
data/datafile7.csv
report/f
data/datafile4.csv
data/datafile1.csv
data/datafile5.csv
data/datafile2.csv
data/datafile6.csv
data/datafile3.csv
Is your cache up to date?
<https://error.dvc.org/missing-files>
Traceback (most recent call last):
  File "dvc/commands/data_sync.py", line 31, in run
  File "dvc/repo/__init__.py", line 64, in wrapper
  File "dvc/repo/pull.py", line 41, in pull
  File "dvc/repo/__init__.py", line 64, in wrapper
  File "dvc/repo/checkout.py", line 204, in checkout
dvc.exceptions.CheckoutError: Checkout failed for following targets:
report/report_f.html
data/datafile7.csv
report/f
data/datafile4.csv
data/datafile1.csv
data/datafile5.csv
data/datafile2.csv
data/datafile6.csv
data/datafile3.csv
Is your cache up to date?
<https://error.dvc.org/missing-files>

2023-06-26 09:53:11,861 DEBUG: Analytics is enabled.
2023-06-26 09:53:11,862 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmphjl8og_6']'
2023-06-26 09:53:11,864 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmphjl8og_6']'
```

**Comment by bakaleks** [comment]
`rm -rf /var/tmp/dvc/repo` did the trick! Thanks!

**Comment by vbeutner** [comment]
On my mac, this was the equivalent:
`rm -rf /Library/Caches/dvc/repo` 

I hope this helps someone

**Comment by hoangphucITJP** [comment]
This issue is still present in `3.67.1`
`rm -rf /var/tmp/dvc/repo` fixed it, but could you check it again?
