### ISSUE TITLE
`exp push`: https fails

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9743]
# Bug Report

## Description

Unable to exp push to https git remote

### Reproduce

```console
$ git clone https://github.com/iterative/example-get-started-experiments-non-demo.git
$ cd example-get-started-experiments-non-demo
$ dvc exp run --pull
$ dvc exp push -v --no-cache origin
2023-07-18 11:18:28,971 DEBUG: v3.5.1 (pip), CPython 3.11.4 on macOS-13.4.1-arm64-arm-64bit
2023-07-18 11:18:28,971 DEBUG: command: /Users/dave/micromamba/envs/example-get-started-experiments/bin/dvc exp push -v --no-cache origin
2023-07-18 11:18:29,137 DEBUG: git push experiment ['refs/exps/49/f1dcff62757de0ca1ccba55e0b3b9b79fdce5d/natal-bots:refs/exps/49/f1dcff62757de0ca1ccba55e0b3b9b79fdce5d/natal-bots'] -> 'origin'
Pushing git refs|                                            |0.00/? [00:00,      ?obj/s]Username for 'https://github.com': dberenbaum
Password for 'https://dberenbaum@github.com':
2023-07-18 11:18:33,273 ERROR: unexpected error - HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /iterative/example-get-started-experiments-non-demo.git/git-receive-pack (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2423)')))
Traceback (most recent call last):
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/http/client.py", line 1080, in _send_output
    self.send(chunk)
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/http/client.py", line 1002, in send
    self.sock.sendall(data)
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/ssl.py", line 1241, in sendall
    v = self.send(byte_view[count:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/ssl.py", line 1210, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2423)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/dvc/cli/__init__.py", line 209, in main
    ret = cmd.do_run()
          ^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
           ^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/dvc/commands/experiments/push.py", line 55, in run
    result = self.repo.experiments.push(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/dvc/repo/experiments/__init__.py", line 389, in push
    return push(self.repo, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/dvc/repo/__init__.py", line 64, in wrapper
    return f(repo, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/dvc/repo/scm_context.py", line 151, in run
    return method(repo, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/dvc/repo/experiments/push.py", line 120, in push
    push_result = _push(repo, git_remote, exp_ref_set, force)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/dvc/repo/experiments/push.py", line 162, in _push
    results: Mapping[str, SyncStatus] = repo.scm.push_refspecs(
                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/scmrepo/git/__init__.py", line 286, in _backend_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 580, in push_refspecs
    result = client.send_pack(
             ^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/dulwich/client.py", line 2048, in send_pack
    resp, read = self._smart_request(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/dulwich/client.py", line 1988, in _smart_request
    resp, read = self._http_request(url, headers, data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/scmrepo/git/backend/dulwich/client.py", line 49, in _http_request
    result = super()._http_request(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/dulwich/client.py", line 2211, in _http_request
    resp = self.pool_manager.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/urllib3/connectionpool.py", line 826, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/urllib3/connectionpool.py", line 826, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/urllib3/connectionpool.py", line 826, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started-experiments/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /iterative/example-get-started-experiments-non-demo.git/git-receive-pack (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2423)')))

2023-07-18 11:18:33,303 DEBUG: Removing '/private/tmp/.SNv8fX8x3vBLJGm7CyVXFZ.tmp'
2023-07-18 11:18:33,304 DEBUG: Removing '/private/tmp/.SNv8fX8x3vBLJGm7CyVXFZ.tmp'
2023-07-18 11:18:33,304 DEBUG: Removing '/private/tmp/.SNv8fX8x3vBLJGm7CyVXFZ.tmp'
2023-07-18 11:18:33,304 DEBUG: Removing '/private/tmp/example-get-started-experiments-non-demo/.dvc/cache/files/md5/.bFc97uwWMMPqFiP9gJcwnu.tmp'
2023-07-18 11:18:37,342 DEBUG: Version info for developers:
DVC version: 3.5.1 (pip)
------------------------
Platform: Python 3.11.4 on macOS-13.4.1-arm64-arm-64bit
Subprojects:
        dvc_data = 2.5.0
        dvc_objects = 0.23.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.0.4
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.6.0, boto3 = 1.26.161)
Config:
        Global: /Users/dave/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/b1fc49d4408cca5f1e780cdbe0783d09

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-07-18 11:18:37,346 DEBUG: Analytics is disabled.

```

**Comment by pmrowla** [comment]
I can't reproduce this, it looks like it was probably a github issue: https://www.githubstatus.com/incidents/shbq71s0g00z

**Comment by dberenbaum** [comment]
@pmrowla Are you manually entering credentials or using a helper? I am still able to consistently reproduce when manually entering credentials despite being able to push regular commits the same way (I have seen it on 3 or 4 different days and on both my laptop and in sagemaker). With a credential helper it works for me. `dvc exp push` to gitlab and dagshub also works, so it look specific to github.

**Comment by pmrowla** [comment]
@dberenbaum it works for me with or without a credential manager.

```
dvc exp push origin --no-cache
Pushing git refs|                                                                                                                                       |0.00/? [00:00,      ?obj/s]Username for 'https://github.com': pmrowla
Password for 'https://pmrowla@github.com':
Experiment sappy-mush is up to date on Git remote 'origin'.
To push cached outputs for this experiment to DVC remote storage,re-run this command without '--no-cache'.
```

You're trying to login with your username + personal access token (and not your GH password) right? (You can't push to github over https with your regular password)

**Comment by dberenbaum** [comment]
Yes, I have tried creating a new token, using a classic token, and using a fine-grained token. I'm able to push regular commits, and if I don't use a valid token, `dvc exp push` gives a different auth error. I will close and come back if I can narrow it down further.
