### ISSUE TITLE
unexpected error - Forbidden: An error occurred (403) when calling the HeadObject operation: Forbidden

### ISSUE THREAD

**Issue by yang0369** [iterative/dvc#9759]
# Bug Report

when I was trying to clean my local workspace by "dvc gc -w", I got this unexpected error msg: "unexpected error - Forbidden: An error occurred (403) when calling the HeadObject operation: Forbidden"

I have followed some online suggestions to run "dvc push-vv", the returns shown below:

```
2023-07-25 12:03:02,761 ERROR: unexpected error - Forbidden: An error occurred (403) when calling the HeadObject operation: Forbidden  
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/s3fs/core.py", line 111, in _error_wrapper
    return await func(*args, **kwargs)
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/aiobotocore/client.py", line 358, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc/commands/data_sync.py", line 59, in run
    processed_files_count = self.repo.push(
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc/repo/push.py", line 84, in push
    used = self.used_objs(
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc/repo/__init__.py", line 431, in used_objs
    for odb, objs in self.index.used_objs(
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc/repo/index.py", line 274, in used_objs
    for odb, objs in stage.get_used_objs(
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc/stage/__init__.py", line 697, in get_used_objs
    for odb, objs in out.get_used_objs(*args, **kwargs).items():
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc/output.py", line 1066, in get_used_objs
    obj = self._collect_used_dir_cache(**kwargs)
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc/output.py", line 1005, in _collect_used_dir_cache
    self.get_dir_cache(jobs=jobs, remote=remote)
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc/output.py", line 987, in get_dir_cache
    self.repo.cloud.pull([obj.hash_info], **kwargs)
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc/data_cloud.py", line 159, in pull
    return self.transfer(
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc/data_cloud.py", line 113, in transfer
    return transfer(src_odb, dest_odb, objs, **kwargs)
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc_data/hashfile/transfer.py", line 190, in transfer
    status = compare_status(
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc_data/hashfile/status.py", line 185, in compare_status
    src_exists, src_missing = status(
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc_data/hashfile/status.py", line 136, in status
    exists = hashes.intersection(
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc_data/hashfile/status.py", line 56, in _indexed_dir_hashes
    dir_exists.update(
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc_objects/db.py", line 300, in list_oids_exists
    yield from itertools.compress(oids, in_remote)
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/dvc_objects/fs/base.py", line 308, in exists
    return self.fs.exists(path)
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/fsspec/asyn.py", line 111, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/fsspec/asyn.py", line 96, in sync
    raise return_result
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/s3fs/core.py", line 929, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/s3fs/core.py", line 1193, in _info
    out = await self._call_s3(
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/s3fs/core.py", line 338, in _call_s3
    return await _error_wrapper(
  File "/home/kewen_yang/anaconda3/envs/xtract/lib/python3.8/site-packages/s3fs/core.py", line 138, in _error_wrapper
    raise err
PermissionError: Forbidden
------------------------------------------------------------
2023-07-25 12:03:02,876 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-07-25 12:03:02,876 DEBUG: Removing '/home/kewen_yang/.ZGK5yurdGHjT728aGCLj2L.tmp'
2023-07-25 12:03:02,877 DEBUG: Removing '/home/kewen_yang/.ZGK5yurdGHjT728aGCLj2L.tmp'
2023-07-25 12:03:02,877 DEBUG: Removing '/home/kewen_yang/.ZGK5yurdGHjT728aGCLj2L.tmp'
2023-07-25 12:03:02,877 DEBUG: Removing '/home/kewen_yang/xtract/.dvc/cache/.b3YDxwcsyv9J8imwmWirwd.tmp'
2023-07-25 12:03:02,887 DEBUG: Version info for developers:
DVC version: 2.31.0 (pip)
---------------------------------
Platform: Python 3.8.13 on Linux-5.4.0-153-generic-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 0.22.0
        dvc_objects = 0.11.0
        dvc_render = 0.0.12
        dvc_task = 0.1.4
        dvclive = 0.12.1
        scmrepo = 0.1.2
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2022.10.0, boto3 = 1.24.59)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: s3, s3, s3, s3, s3, s3, s3, s3, s3, s3, s3
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git
```

So far, I have tried a few solutions online, but nothing helped, appreciate if anyone can help here, thanks!

**Comment by pmrowla** [comment]
2.31 is a fairly outdated DVC release. Can you try updating with
```
pip install dvc[s3]==2.58.2
```
and then retry

**Comment by yang0369** [comment]
> 2.31 is a fairly outdated DVC release. Can you try updating with
> 
> ```
> pip install dvc[s3]==2.58.2
> ```
> 
> and then retry

yup, it worked, thank you so much!
