### ISSUE TITLE
repro: External outputs with persist: true and cache: false raise AssertionError

### ISSUE THREAD

**Issue by jonnyli1125** [iterative/dvc#9811]
# Bug Report

repro: External outputs with `persist: true` and `cache: false` raise AssertionError

## Description

When setting `persist: true` and `cache: false` to an external output (e.g. `webhdfs://user@example.com/file.txt`), `dvc repro` will halt with no descriptive error message:
```
ERROR: failed to reproduce 'hdfs_upload': 
```
The command for this stage is not executed.

If you look closer with `dvc repro -v`, then you see there is an assertion error:
```
2023-08-05 13:28:13,926 ERROR: failed to reproduce 'hdfs_upload': 
Traceback (most recent call last):
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/repo/reproduce.py", line 199, in _reproduce
    ret = repro_fn(stage, upstream=upstream, force=force_stage, **kwargs)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/repo/reproduce.py", line 129, in _reproduce_stage
    ret = stage.reproduce(**kwargs)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/stage/__init__.py", line 433, in reproduce
    self.run(**kwargs)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/stage/__init__.py", line 592, in run
    self.remove_outs(ignore_remove=False, force=False)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/stage/__init__.py", line 376, in remove_outs
    out.unprotect()
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/output.py", line 1079, in unprotect
    self.cache.unprotect(self.fs_path)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/output.py", line 534, in cache
    assert self.is_in_repo
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/cli/__init__.py", line 209, in main
    ret = cmd.do_run()
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/commands/repro.py", line 13, in run
    stages = self.repo.reproduce(**self._common_kwargs, **self._repro_kwargs)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/repo/__init__.py", line 64, in wrapper
    return f(repo, *args, **kwargs)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/repo/scm_context.py", line 151, in run
    return method(repo, *args, **kw)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/repo/reproduce.py", line 260, in reproduce
    return _reproduce(steps, graph=graph, on_error=on_error or "fail", **kwargs)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/repo/reproduce.py", line 203, in _reproduce
    _raise_error(exc, stage)
  File "/disk1/pampa/jli/dvc-test/.venv/lib64/python3.8/site-packages/dvc/repo/reproduce.py", line 167, in _raise_error
    raise ReproductionError(f"failed to reproduce{segment} {names}") from exc
dvc.exceptions.ReproductionError: failed to reproduce 'hdfs_upload'
```

If we follow the stack trace, [`dvc/stage/__init__.py:376`](https://github.com/iterative/dvc/blob/main/dvc/stage/__init__.py#L376) calls `out.unprotect()` for all persisted outputs:
```py
for out in self.outs:
    if out.persist and not force:
        out.unprotect()
        continue
```
Then [`out.unprotect()`](https://github.com/iterative/dvc/blob/main/dvc/output.py#L1092) calls:
```
if self.exists:
    self.cache.unprotect(self.fs_path)
```
Then [`self.cache`](https://github.com/iterative/dvc/blob/main/dvc/output.py#L534) calls:
```
assert self.is_in_repo
```
And [`self.is_in_repo`](https://github.com/iterative/dvc/blob/main/dvc/output.py#L518-L521) is always false for an external output because `self.repo.root_dir` is the local repo directory and `self.fs_path` is an external path, so `self.fs.path.isin` returns false.
```py
return self.repo and self.fs.path.isin(
    self.fs_path,
    self.repo.root_dir,
)
```

### Reproduce

1. `pip install dvc dvc-webhdfs`
2. `dvc init --no-scm`
3. `dvc stage add -n hdfs_upload --outs-persist-no-cache webhdfs://user@example.com/file.txt echo foobar`
4. `dvc repro -v`

Note: I only tried this for webhdfs since that's all I have access to, so I'm not sure if it applies to all other types of external outputs.

### Expected

Don't raise an AssertionError for outputs with `persist: true` and `cache: false`. If this is intended behaviour, I think there should at least be a more descriptive error message displayed to the user on how to fix it.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.12.0 (pip)
-------------------------
Platform: Python 3.8.13 on Linux-3.10.0-1160.53.1.el7.x86_64-x86_64-with-glibc2.2.5
Subprojects:
	dvc_data = 2.11.0
	dvc_objects = 0.24.1
	dvc_render = 0.5.3
	dvc_task = 0.3.0
	scmrepo = 1.1.0
Supports:
	http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
	webhdfs (fsspec = 2023.6.0)
Config:
	Global: /afs/melodis.com/home/jli/.config/dvc
	System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: xfs on /dev/md4
Caches: local
Remotes: webhdfs
Workspace directory: xfs on /dev/md4
Repo: dvc (no_scm)
Repo.site_cache_dir: /var/tmp/dvc/repo/2b0fe4fc2ece2dbe9bf10114e51dd1b6
```

**Additional Information (if any):**

**Comment by efiop** [comment]
Cached external outputs are not supported since 3.0, we should give a better error here.

**Comment by dberenbaum** [comment]
Hi @jonnyli1125! There is a fix in the PR linked above that should be available in the next release. 

Would you mind giving some more insight into how you use dvc and external outputs?

**Comment by jonnyli1125** [comment]
Thanks @dberenbaum.

I'm using DVC for ETL pipelines on HDFS + Apache Spark. We want to move/copy the existing files to another folder before recomputing stages in order to preserve old versions of the data, so we would need `persist: true`.

The best solution would be to have caching for external outputs, but it seems like that isn't supported yet.
