### ISSUE TITLE
Path with `~` in config breaks repo parsing

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#9822]
An entry like this:

```ini
[cache]
    dir = ~/Projects
```

Breaks DVC into a weird error (and breaks at the moment Studio parsing, which is a separate issue a bit - we need to make resilient to this, but changes here would help us): 

<details>
</summary>DVC verbose output</summary>

```python
2023-08-08 16:51:26,958 DEBUG: command: /Users/ivan/Projects/test-cache/.venv/bin/dvc status -v
2023-08-08 16:51:27,100 ERROR: unexpected error - [Errno 2] No such file or directory: '/Users/ivan/Projects/test-cache/.dvc/~/.gitignore'
Traceback (most recent call last):
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/cli/__init__.py", line 208, in main
    cmd = args.func(args)
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/cli/command.py", line 20, in __init__
    self.repo: "Repo" = Repo(uninitialized=self.UNINITIALIZED)
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/repo/__init__.py", line 226, in __init__
    self._ignore()
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/repo/__init__.py", line 473, in _ignore
    self.scm_context.ignore(file)
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/repo/scm_context.py", line 77, in ignore
    gitignore_file = self.scm.ignore(path)
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 196, in ignore
    self._add_entry_to_gitignore(entry, gitignore)
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 202, in _add_entry_to_gitignore
    with open(gitignore, "a+", encoding="utf-8") as fobj:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ivan/Projects/test-cache/.dvc/~/.gitignore'

Traceback (most recent call last):
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/cli/__init__.py", line 208, in main
    cmd = args.func(args)
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/cli/command.py", line 20, in __init__
    self.repo: "Repo" = Repo(uninitialized=self.UNINITIALIZED)
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/repo/__init__.py", line 226, in __init__
    self._ignore()
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/repo/__init__.py", line 473, in _ignore
    self.scm_context.ignore(file)
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/repo/scm_context.py", line 77, in ignore
    gitignore_file = self.scm.ignore(path)
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 196, in ignore
    self._add_entry_to_gitignore(entry, gitignore)
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 202, in _add_entry_to_gitignore
    with open(gitignore, "a+", encoding="utf-8") as fobj:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ivan/Projects/test-cache/.dvc/~/.gitignore'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ivan/Projects/test-cache/.venv/bin/dvc", line 8, in <module>
    sys.exit(main())
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/cli/__init__.py", line 235, in main
    ret = _log_exceptions(exc) or 255
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/cli/__init__.py", line 72, in _log_exceptions
    _log_unknown_exceptions()
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/cli/__init__.py", line 47, in _log_unknown_exceptions
    logger.debug("Version info for developers:\n%s", get_dvc_info())
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/info.py", line 38, in get_dvc_info
    with Repo() as repo:
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/repo/__init__.py", line 226, in __init__
    self._ignore()
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/repo/__init__.py", line 473, in _ignore
    self.scm_context.ignore(file)
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/dvc/repo/scm_context.py", line 77, in ignore
    gitignore_file = self.scm.ignore(path)
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 196, in ignore
    self._add_entry_to_gitignore(entry, gitignore)
  File "/Users/ivan/Projects/test-cache/.venv/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 202, in _add_entry_to_gitignore
    with open(gitignore, "a+", encoding="utf-8") as fobj:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ivan/Projects/test-cache/.dvc/~/.gitignore'
```

</details>

There are two options:

- We can allow those paths (why not?) and run `expanduser` somewhere [here](https://github.com/iterative/dvc/blob/main/dvc/config.py#L253)
- We can at least detect better that path is wrong / not accessible and throw some config error in the CacheManager init, or even better in the the same load paths

Wdyt folks?

## DVC Version

```
DVC version: 3.13.3 (pip)
-------------------------
Platform: Python 3.10.12 on macOS-13.3.1-arm64-arm-64bit
Subprojects:
	dvc_data = 2.12.1
	dvc_objects = 0.24.1
	dvc_render = 0.5.3
	dvc_task = 0.3.0
	scmrepo = 1.1.0
Supports:
	azure (adlfs = 2023.8.0, knack = 0.11.0, azure-identity = 1.13.0),
	gdrive (pydrive2 = 1.16.1),
	gs (gcsfs = 2023.6.0),
	hdfs (fsspec = 2023.6.0, pyarrow = 12.0.1),
	http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
	oss (ossfs = 2021.8.0),
	s3 (s3fs = 2023.6.0, boto3 = 1.28.17),
	ssh (sshfs = 2023.7.0),
	webdav (webdav4 = 0.9.8),
	webdavs (webdav4 = 0.9.8),
	webhdfs (fsspec = 2023.6.0)
Config:
	Global: /Users/ivan/Library/Application Support/dvc
	System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/11499c8ab0f5f08a05c96a47c40c1627
```

**Comment by efiop** [comment]
Just missing an expanduser somewhere around https://github.com/iterative/dvc/blob/c71b07b99622ab37138d6d63f611a532c1dda142/dvc/config.py#L259

Will take a look.

Thanks for the report.

**Comment by efiop** [comment]
@shcheklein Thanks for the report. You are spot on, we are using `isabs` there, but we really just need to do an expanduser somewhere there.

Will take a look.
