### ISSUE TITLE
dvc fetch does not fetch

### ISSUE THREAD

**Issue by radomsak** [iterative/dvc#9824]
# Bug Report

`dvc fetch` does not fetch the changes from S3 bucket.

## Description

We have a remote setup on S3 bucket. When one developer adds and pushes new data files, another one does the following:

```
dvc fetch 
# output: 
# everything up to date (data is not fetched, even though there are changes in the remote)

dvc pull
# output:
# dvc.exceptions.CheckoutError: Checkout failed for following targets:
# data/xxxxxxxxxx
# Is your cache up to date?
# <https://error.dvc.org/missing-files>
```

But then when I do:
```
touch data/deleteme
dvc add data/deleteme
dvc fetch # success!
```
Everything works as expected

### Reproduce

This is difficult to reproduce because we use a remote with an S3 bucket. In general the steps are like this:

Machine 1:
```
dvc add xxx
dvc push
```

Machine 1, clean clone of the repository
```
dvc fetch # fetches correctly
dvc pull # success
```

Machine 2:
```
dvc fetch # does not fetch
dvc pull # fails
touch data/deleteme
dvc add data/deleteme
dvc fetch # success
```

### Expected

dvc fetch should work without having to add a file.

### Environment information

**Output of `dvc doctor` on both machines is the same:**

```console
$ dvc doctor
DVC version: 3.13.3 (pip)                                                                                                                                                
-------------------------                                                                                                                                                
Platform: Python 3.10.12 on Linux-5.15.0-78-generic-x86_64-with-glibc2.31                                                                                                
Subprojects:                                                                                                                                                             
        dvc_data = 2.12.1                                                                                                                                                
        dvc_objects = 0.24.1                                                                                                                                             
        dvc_render = 0.5.3                                                                                                                                               
        dvc_task = 0.3.0                                                                                                                                                 
        scmrepo = 1.1.0                                                                                                                                                  
Supports:                                                                                                                                                                
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),                                                                                                                   
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),                                                                                                                  
        s3 (s3fs = 2023.6.0, boto3 = 1.28.17)                                                                                                                            
Config:                                                                                                                                                                  
        Global: /home/xxxx/.config/dvc                                                                                                                              
	System: /etc/xdg/xdg-ubuntu/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/vgubuntu-root
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/mapper/vgubuntu-root
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/1535e60ae0c1c76198d142daac58ff68

```

**Additional Information (if any):**

Failing `dvc fetch -v` command:
```
2023-08-09 13:32:33,083 DEBUG: v3.13.3 (pip), CPython 3.10.12 on Linux-5.15.0-78-generic-x86_64-with-glibc2.31
2023-08-09 13:32:33,083 DEBUG: command: /home/xxxxxxxxx/miniconda3/envs/xxxxxxx/bin/dvc fetch -v
2023-08-09 13:32:33,363 DEBUG: Preparing to transfer data from 's3://xxxxxxxxxxxx/dvc/files/md5' to '/home/xxxx/workspace/xxxx/xxxxxxxx/.dvc/cache/files/md5'
2023-08-09 13:32:33,363 DEBUG: Preparing to collect status from '/home/xxxxxxx/workspace/xxxx/xxxxxx/.dvc/cache/files/md5'
2023-08-09 13:32:33,363 DEBUG: Collecting status from '/home/xxxx/workspace/xxxx/xxxxx/.dvc/cache/files/md5'
2023-08-09 13:32:33,365 DEBUG: Preparing to collect status from 'xxxxxx/dvc/files/md5'                                                                  
2023-08-09 13:32:33,365 DEBUG: Collecting status from 'xxxxxx/dvc/files/md5'
2023-08-09 13:32:33,380 DEBUG: Querying 2 oids via object_exists                                                                                                         
2023-08-09 13:32:34,539 DEBUG: Querying 0 oids via object_exists                                                                                                         
2023-08-09 13:32:35,194 DEBUG: transfer dir: md5: dea817ef564598538aa68ebf501e52b1.dir with 0 files                                                                      
2023-08-09 13:32:35,453 DEBUG: transfer dir: md5: 66d9d5357614a7963f8e6d997f4d4491.dir with 68 files                                                                     
70 files fetched                                                                                                                                                         
2023-08-09 13:34:21,013 DEBUG: Analytics is enabled.                                                                                                                     
2023-08-09 13:34:21,039 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmphsao0ndc']'                                                                       
2023-08-09 13:34:21,040 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmphsao0ndc']' 
```

Failing `dvc pull -v` command:

```
2023-08-09 13:31:22,845 DEBUG: failed to create '/home/xxxx/workspace/xxxx/xxxx/data/raw/2023-08-08-xxxx-spr/3584_e4bb48fd-b484-4311-97cc-ee32c729d01d/e4bb48fd-b484-4311-97cc-ee32c729d01d_point_cloud.actdat' from '/home/xxxx/workspace/xxxx/xxxx/.dvc/cache/files/md5/0c/aba4b940e9ccf4ce3e1375672ea067' - [Errno 2] No such file or directory: '/home/xxxx/workspace/xxxx/xxxx/.dvc/cache/files/md5/0c/aba4b940e9ccf4ce3e1375672ea067'
Traceback (most recent call last):
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/dvc_objects/fs/generic.py", line 308, in transfer
    _try_links(
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/dvc_objects/fs/generic.py", line 250, in _try_links
    _link(link, from_fs, from_path, to_fs, to_path)
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/dvc_objects/fs/generic.py", line 62, in _link
    func(from_path, to_path)
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 389, in reflink
    return self.fs.reflink(from_info, to_info)
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/dvc_objects/fs/local.py", line 169, in reflink
    return system.reflink(path1, path2)
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/dvc_objects/fs/system.py", line 105, in reflink
    _reflink_linux(source, link_name)
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/dvc_objects/fs/system.py", line 90, in _reflink_linux
    with open(src, "rb") as s, open(dst, "wb+") as d:
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxxx/workspace/xxxx/xxxx/.dvc/cache/files/md5/0c/aba4b940e9ccf4ce3e1375672ea067'

2023-08-09 13:31:22,856 DEBUG: Removing '/home/xxxx/workspace/xxxx/xxxx/data/raw/2023-08-08-xxxx-spr'                                                 
Everything is up to date.
2023-08-09 13:31:22,865 ERROR: failed to pull data from the cloud - Checkout failed for following targets:
data/raw/2023-08-08-xxxx-spr
Is your cache up to date?
<https://error.dvc.org/missing-files>
Traceback (most recent call last):
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/dvc/commands/data_sync.py", line 31, in run
    stats = self.repo.pull(
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/dvc/repo/__init__.py", line 64, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/dvc/repo/pull.py", line 43, in pull
    stats = self.checkout(
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/dvc/repo/__init__.py", line 64, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/dvc/repo/checkout.py", line 208, in checkout
    raise CheckoutError([relpath(out_path) for out_path in failed], stats)
dvc.exceptions.CheckoutError: Checkout failed for following targets:
data/raw/2023-08-08-xxxx-spr
Is your cache up to date?
<https://error.dvc.org/missing-files>

2023-08-09 13:31:22,866 DEBUG: Analytics is enabled.
2023-08-09 13:31:22,889 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpdx6virc2']'
2023-08-09 13:31:22,890 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpdx6virc2']'

```

**Comment by pmrowla** [comment]
On the machine where the fetch/pull fails, can you try removing the `Repo.site_cache_dir` folder and then re-run the fetch/pull:

(make sure you run `dvc doctor` on that machine to get the correct folder path for that machine)
```
rm -r /var/tmp/dvc/repo/...
dvc pull
```

**Comment by radomsak** [comment]
I removed the site_cache_dir as you suggested and it fixed the problem.

Is it something that a user needs to do from time to time? Or some kind of a bug on dvc side?

Please let me know if there is anything else I could do to help you fix/document this

**Comment by efiop** [comment]
@radomsak It is a bug in previous dvc versions, should not happen anymore with the newest versions. Sorry for the inconvenience.

**Comment by dberenbaum** [comment]
@efiop @iterative/dvc Should we add something to the docs to suggest this as a possible fix to similar issues?
