### ISSUE TITLE
ERROR: failed to reproduce 'data_ingestion': failed to run: python src/CoccidiosisClassifier/pipeline/stage_01_data_ingestion.py, exited with 1

### ISSUE THREAD

**Issue by Killpit** [iterative/dvc#9865]
# Bug Report

```
(venv) atatekeli:coccidiosis-classifier atatekeli$ dvc repro
Running stage 'data_ingestion':                                                                                          
> python src/CoccidiosisClassifier/pipeline/stage_01_data_ingestion.py
Traceback (most recent call last):
  File "/Users/atatekeli/PycharmProjects/coccidiosis-classifier/src/CoccidiosisClassifier/pipeline/stage_01_data_ingestion.py", line 1, in <module>
    from src.CoccidiosisClassifier.config.configuration import ConfigurationManager
ModuleNotFoundError: No module named 'src'
ERROR: failed to reproduce 'data_ingestion': failed to run: python src/CoccidiosisClassifier/pipeline/stage_01_data_ingestion.py, exited with 1
(venv) atatekeli:coccidiosis-classifier atatekeli$ dvc repro
Running stage 'data_ingestion':                                                                                          
> python src/CoccidiosisClassifier/pipeline/stage_01_data_ingestion.py
Traceback (most recent call last):
  File "/Users/atatekeli/PycharmProjects/coccidiosis-classifier/src/CoccidiosisClassifier/pipeline/stage_01_data_ingestion.py", line 1, in <module>
    from src.CoccidiosisClassifier.config.configuration import ConfigurationManager
ModuleNotFoundError: No module named 'src'
ERROR: failed to reproduce 'data_ingestion': failed to run: python src/CoccidiosisClassifier/pipeline/stage_01_data_ingestion.py, exited with 1
```

### Reproduce

```
(venv) atatekeli:coccidiosis-classifier atatekeli$ dvc doctor
DVC version: 3.15.1 (pip)
-------------------------
Platform: Python 3.10.10 on macOS-13.5-arm64-arm-64bit
Subprojects:
        dvc_data = 2.13.1
        dvc_objects = 0.25.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.2.1
Supports:
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3)
Config:
        Global: /Users/atatekeli/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/ffe5f51d5fb770accac94a95e340c5f2

```

### Expected

Python venv 3.10

### Environment information

**Output of `dvc doctor`:**

```(venv) atatekeli:coccidiosis-classifier atatekeli$ dvc doctor
DVC version: 3.15.1 (pip)
-------------------------
Platform: Python 3.10.10 on macOS-13.5-arm64-arm-64bit
Subprojects:
        dvc_data = 2.13.1
        dvc_objects = 0.25.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.2.1
Supports:
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3)
Config:
        Global: /Users/atatekeli/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/ffe5f51d5fb770accac94a95e340c5f2
```

**Comment by pmrowla** [comment]
Addressed in discord, not a DVC issue
