### ISSUE TITLE
`dvc exp run`: fails and `dvc.yaml` silently removed from workspace if files are not yet tracked.

### ISSUE THREAD

**Issue by xnhp** [iterative/dvc#9885]
# Bug Report

## Description

`dvc exp run` fails and removes some local files.

### Reproduce

1. Create a folder with a `dvc.yaml` and `params.yaml` (Do not commit the files).
2. Switch to the folder in a terminal
3. Run `dvc exp run`

If I commit the files to `git` first, things seem to work well. One might argue that this is not an issue then. However, I still think the error message is not very helpful and silently having a local file removed can become quite confusing.

### Expected

An experiment is run.

### Actual:
The ´dvc.yaml` file is being removed and the following is printed to the terminal:
```
(venv) PS C:\Users\Ben\PycharmProjects\Decompose\dvc-experiments\classification\zero-one> dvc exp run
ERROR: unexpected error - could not rmdir 'C:/Users/Ben/PycharmProjects/Decompose/dvc-experiments/classification/zero-one/': The process cannot access the file because it is being used by another process.
```

### Environment information

**Output of `dvc doctor`:**

```console
(venv) PS C:\Users\Ben\PycharmProjects\Decompose\dvc-experiments\classification\zero-one> dvc doctor
DVC version: 3.16.0 (pip)
-------------------------
Platform: Python 3.9.5 on Windows-10-10.0.19045-SP0
Subprojects:
        dvc_data = 2.15.4
        dvc_objects = 1.0.1
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.3.1
Supports:
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3)
Config:
        Global: C:\Users\Ben\AppData\Local\iterative\dvc
        System: C:\ProgramData\iterative\dvc
Cache types: hardlink, symlink
Cache directory: NTFS on C:\
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git
Repo.site_cache_dir: C:\ProgramData\iterative\dvc\Cache\repo\802cb8f124e7063a13c191c201d9e22e
```

**Additional Information (if any):**

- Note that this is *not* due to PyCharm running.

Verbose output:
```
(venv) PS C:\Users\Ben\PycharmProjects\Decompose\dvc-experiments\classification\zero-one> dvc exp run --verbose
2023-08-29 16:01:15,218 DEBUG: v3.16.0 (pip), CPython 3.9.5 on Windows-10-10.0.19045-SP0
2023-08-29 16:01:15,219 DEBUG: command: C:\Users\Ben\PycharmProjects\Decompose\venv\Scripts\dvc exp run --verbose
2023-08-29 16:01:16,211 ERROR: unexpected error - could not rmdir 'C:/Users/Ben/PycharmProjects/Decompose/dvc-experiments/classification/zero-one/': The process cannot access the file because it is being used by another process.
Traceback (most recent call last):
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\dvc\cli\__init__.py", line 209, in main
    ret = cmd.do_run()
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\dvc\cli\command.py", line 26, in do_run
    return self.run()
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\dvc\commands\experiments\run.py", line 13, in run
    self.repo.experiments.run(
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\dvc\repo\experiments\__init__.py", line 371, in run
    return run(self.repo, *args, **kwargs)
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\dvc\repo\__init__.py", line 62, in wrapper
    return f(repo, *args, **kwargs)
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\dvc\repo\experiments\run.py", line 73, in run
    return repo.experiments.reproduce_one(
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\dvc\repo\experiments\__init__.py", line 124, in reproduce_one
    self.queue_one(exp_queue, **kwargs)
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\dvc\repo\experiments\__init__.py", line 139, in queue_one
    return self.new(
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\dvc\repo\experiments\__init__.py", line 235, in new
    return queue.put(*args, **kwargs)
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\dvc\repo\experiments\queue\workspace.py", line 37, in put
    return self._stash_exp(*args, **kwargs)
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\dvc\repo\experiments\queue\base.py", line 326, in _stash_exp
    with self.scm.stash_workspace(reinstate_index=True) as workspace:
  File "C:\Users\Ben\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\scmrepo\git\__init__.py", line 453, in stash_workspace
    rev = self.stash.push(**kwargs)
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\scmrepo\git\stash.py", line 36, in push
    rev, reset = self.scm._stash_push(  # pylint: disable=protected-access
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\scmrepo\git\__init__.py", line 292, in _backend_func
    result = func(*args, **kwargs)
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\scmrepo\git\backend\pygit2\__init__.py", line 648, in _stash_push
    oid = self.repo.stash(
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\pygit2\repository.py", line 1198, in stash
    check_error(err)
  File "C:\Users\Ben\PycharmProjects\Decompose\venv\lib\site-packages\pygit2\errors.py", line 65, in check_error
    raise GitError(message)
_pygit2.GitError: could not rmdir 'C:/Users/Ben/PycharmProjects/Decompose/dvc-experiments/classification/zero-one/': The process cannot access the file because it is being used by another process.


2023-08-29 16:01:16,330 DEBUG: link type reflink is not available ([Errno 129] no more link types left to try out)
2023-08-29 16:01:16,331 DEBUG: Removing 'C:\Users\Ben\PycharmProjects\.kDMzAHrWLteNjrBDN9pC3f.tmp'
2023-08-29 16:01:16,333 DEBUG: Removing 'C:\Users\Ben\PycharmProjects\.kDMzAHrWLteNjrBDN9pC3f.tmp'
2023-08-29 16:01:16,335 DEBUG: Removing 'C:\Users\Ben\PycharmProjects\.kDMzAHrWLteNjrBDN9pC3f.tmp'
2023-08-29 16:01:16,336 DEBUG: Removing 'C:\Users\Ben\PycharmProjects\Decompose\.dvc\cache\files\md5\.i9iizV9G9u37rVCmjT8dBr.tmp'
2023-08-29 16:01:16,348 DEBUG: Version info for developers:
DVC version: 3.16.0 (pip)
-------------------------
Platform: Python 3.9.5 on Windows-10-10.0.19045-SP0
Subprojects:
        dvc_data = 2.15.4
        dvc_objects = 1.0.1
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.3.1
Supports:
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3)
Config:
        Global: C:\Users\Ben\AppData\Local\iterative\dvc
        System: C:\ProgramData\iterative\dvc
Cache types: hardlink, symlink
Cache directory: NTFS on C:\
Caches: local
Remotes: None
Workspace directory: NTFS on C:\
Repo: dvc, git
Repo.site_cache_dir: C:\ProgramData\iterative\dvc\Cache\repo\802cb8f124e7063a13c191c201d9e22e

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-08-29 16:01:16,355 DEBUG: Analytics is enabled.
2023-08-29 16:01:16,525 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\Ben\\AppData\\Local\\Temp\\tmp8r2nm4t_']'
2023-08-29 16:01:16,530 DEBUG: Spawned '['daemon', '-q', 'analytics', 'C:\\Users\\Ben\\AppData\\Local\\Temp\\tmp8r2nm4t_']'
```

**Comment by dberenbaum** [comment]
Thanks for reporting @xnhp! I tried to make a simple example to reproduce it but so far am not able to. Does it work for you with this simple `params.yaml` and `dvc.yaml`?

```yaml
# params.yaml
foo: 1
```

```yaml
# dvc.yaml
stages:
  test:
    cmd: echo ${foo} > out
    outs:
      - out
```

**Comment by xnhp** [comment]
Hi @dberenbaum, thanks for getting back to me. I'll try to construct a minimal example to reproduce this but am not sure when I'll have the time. Feel free to ping me again if I don't reply until end of next week.

**Comment by skshetry** [comment]
Closing due to lack of response.
