### ISSUE TITLE
exp show: unexpected error - 'checkpoint_tip' when using -A option

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/dvc#9899]
# Bug Report

## Description

Command `dvc exp show -A` raises the following error without any output:

```
ERROR: unexpected error - 'checkpoint_tip'
```

### Reproduce

Not sure what is causing this issue. Could it be related to breaking changes moving from DVC 2 to 3?

### Expected

The command should show me an overview of all experiments I ran in the DVC project folder of the Git repository.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.17.0 (conda)
---------------------------
Platform: Python 3.10.6 on Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 2.15.4
        dvc_objects = 1.0.1
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.3.1
Supports:
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.6.0, boto3 = 1.26.76)
Config:
        Global: /home/aschuh/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: xfs on /dev/sda1
Caches: local
Remotes: s3, s3
Workspace directory: xfs on /dev/sda1
Repo: dvc (subdir), git
Repo.site_cache_dir: /var/tmp/dvc/repo/8d2f5d68bb223da9776a9d6301681efd
```

**Additional Information (if any):**

`dvc exp list -A` works and does not cause this issue.

**Comment by shcheklein** [comment]
@aschuh-hf could you please run it with `-v`?

**Comment by aschuh-hf** [comment]
Using some of the baseline commit SHAs from the `dvc exp list -A` output, I was able to pinpoint a baseline rev which, when included in the list of `--rev` arguments of `dvc exp show` (without `-A`), would cause this issue. If I only list other baseline revs, the experiments table shows as expected.

```
2023-08-31 22:52:38,067 DEBUG: v3.17.0 (conda), CPython 3.10.6 on Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-glibc2.17
2023-08-31 22:52:38,067 DEBUG: command: /opt/conda/envs/venv/bin/dvc exp show --rev 5162b9a -v
2023-08-31 22:52:43,437 ERROR: unexpected error - 'checkpoint_tip'
Traceback (most recent call last):
  File "/opt/conda/envs/venv/lib/python3.10/site-packages/dvc/cli/__init__.py", line 209, in main
    ret = cmd.do_run()
  File "/opt/conda/envs/venv/lib/python3.10/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/opt/conda/envs/venv/lib/python3.10/site-packages/dvc/commands/experiments/show.py", line 179, in run
    show_experiments(
  File "/opt/conda/envs/venv/lib/python3.10/site-packages/dvc/commands/experiments/show.py", line 80, in show_experiments
    td.column("Experiment")[:] = map(prepare_exp_id, td.as_dict(merge_headers))
  File "/opt/conda/envs/venv/lib/python3.10/site-packages/dvc/commands/experiments/show.py", line 48, in prepare_exp_id
    tree = experiment_types[typ]
KeyError: 'checkpoint_tip'
```

**Comment by pmrowla** [comment]
This is probably an `exp show` bug, but can you also try doing
```
rm -r .dvc/tmp/exps/cache
```
and then retry `dvc exp show` with the flags that give you the error

**Comment by aschuh-hf** [comment]
After doing this, the `dvc exp show`  command from above displays a number of "Removing '*/.dvc/tmp/exps/cache/??/*' messages, but then I get the same error as before.

**Comment by pmrowla** [comment]
@aschuh-hf can you please try the linked PR and confirm that it resolves your issue (with `-A`)

```
pip install 'dvc @ git+https://github.com/iterative/dvc.git@refs/pull/9906/head'
```

Just note that checkpoints support was dropped in 3.x, so for legacy checkpoint experiments `exp show` will now only display the tip (latest checkpoint) from those existing exps

**Comment by aschuh-hf** [comment]
Yes, this patch resolves the issue for me.

```
$ dvc exp show --rev 5162b9a -v
2023-09-04 21:02:47,495 DEBUG: v3.17.1.dev5+g8044fc96, CPython 3.10.6 on Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-glibc2.17
2023-09-04 21:02:47,495 DEBUG: command: /opt/conda/envs/venv/bin/dvc exp show --rev 5162b9a -v
2023-09-04 21:02:52,959 DEBUG: Returning tip commit for legacy checkpoint exp
2023-09-04 21:02:52,960 DEBUG: Returning tip commit for legacy checkpoint exp
2023-09-04 21:02:52,961 DEBUG: Returning tip commit for legacy checkpoint exp
# Experiments table is shown in console
```

> for legacy checkpoint experiments exp show will now only display the tip (latest checkpoint) from those existing exps

Sounds reasonable.
