### ISSUE TITLE
`exp run --allow-missing`: runs stage unexpectedly

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9915]
# Bug Report

## Description

`dvc exp run --allow-missing` runs stages even though they are unchanged other than missing files.

### Reproduce

```console
$ git clone git@github.com:iterative/example-get-started.git
$ cd example-get-started
$ dvc exp run --allow-missing -S train.min_split=0.005
Reproducing experiment 'plump-leak'
'data/data.xml.dvc' didn't change, skipping
Stage 'prepare' didn't change, skipping
WARNING: 'data/prepared' is empty.
WARNING: 'data/prepared' is empty.
Running stage 'featurize':
> python src/featurization.py data/prepared data/features
Traceback (most recent call last):
  File "/private/tmp/example-get-started/src/featurization.py", line 136, in <module>
    main()
  File "/private/tmp/example-get-started/src/featurization.py", line 120, in main
    generate_and_save_train_features(
  File "/private/tmp/example-get-started/src/featurization.py", line 58, in generate_and_save_train_features
    df_train = get_df(train_input)
               ^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/example-get-started/src/featurization.py", line 14, in get_df
    df = pd.read_csv(
         ^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/Users/dave/micromamba/envs/example-get-started/lib/python3.11/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/prepared/train.tsv'
ERROR: failed to reproduce 'featurize': failed to run: python src/featurization.py data/prepared data/features, exited with 1
```

### Expected

DVC should be skipping `featurize` since nothing changed in this stage.

DVC generates empty `data/prepared` and `data/features` dirs, which might be part of the problem?

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.17.1.dev6+ge2aedb7e9
-----------------------------------
Platform: Python 3.11.4 on macOS-13.5-arm64-arm-64bit
Subprojects:
        dvc_data = 2.8.1
        dvc_objects = 0.24.1
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.0.4
Supports:
        azure (adlfs = 2023.4.0, knack = 0.11.0, azure-identity = 1.13.0),
        gdrive (pydrive2 = 1.16.1),
        gs (gcsfs = 2023.6.0),
        hdfs (fsspec = 2023.6.0, pyarrow = 12.0.1),
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2023.6.0, boto3 = 1.26.161),
        ssh (sshfs = 2023.7.0),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2023.6.0)
Config:
        Global: /Users/dave/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/d009e3e973ba4fa60c5080b78a58592a
```

**Comment by pmrowla** [comment]
This looks like expected behavior to me. In this case we allow the missing files when checking out the dependencies, and then dvc runs the stages with whatever the state of the workspace is.

Even if we adjust the behavior to make DVC treat the dependencies for `featurize` as unchanged (since the only change is a missing file), we cannot generate an output for `featurize` since there is no run cache to checkout. `evaluate` depends on the `featurize` output so it's not clear what should happen at that point.

Is the expectation here just to run `train` and then fail on `evaluate`? Or should it succeed since `evaluate` depends on missing data, in which case the resulting experiment would only contain `dvc.lock` entries for `train`?

**Comment by dberenbaum** [comment]
I think I had outdated packages (see dvc-data version above for example). Not able to reproduce once those are updated. Now I get the expected behavior:

```console
$ dvc exp run --allow-missing -S train.min_split=0.005
Reproducing experiment 'suave-hobo'
'data/data.xml.dvc' didn't change, skipping
Stage 'prepare' didn't change, skipping
Stage 'featurize' didn't change, skipping
ERROR: failed to reproduce 'train': [Errno 2] No such file or directory: '/private/tmp/example-get-started/data/features'
```

> This looks like expected behavior to me. In this case we allow the missing files when checking out the dependencies, and then dvc runs the stages with whatever the state of the workspace is.

@pmrowla To clarify, I think this is a misunderstanding because `repro/exp run --allow-missing` is poorly named. It's not the same as `dvc checkout/pull/fetch --allow-missing`. It doesn't checkout anything. It just assumes that deps and outs that are missing but otherwise unmodified are unchanged. So in this example:
* `data/data.xml.dvc` is missing, so it is considered unchanged and the stage is skipped
* `prepare` is unchanged other than missing files so the stage is skipped
* `featurize` is unchanged other than missing files so the stage is skipped
* `train` has a modified param so we run it and fail because the files are missing
