### ISSUE TITLE
dvc import: fails to import - SCM Error

### ISSUE THREAD

**Issue by mohitanchlia** [iterative/dvc#9944]
## Description

We receive the following error when importing from an existing dvc repo:

`
dvc import git@github.com:csdisco/matter-reviews-datasets.git datasets -v
2023-09-14 16:18:30,306 DEBUG: v3.5.1 (pip), CPython 3.10.12 on Linux-5.15.0-1021-aws-x86_64-with-glibc2.31
2023-09-14 16:18:30,306 DEBUG: command: /home/ubuntu/.pyenv/versions/3.10.12/bin/dvc import git@github.com:csdisco/abc-def-datasets.git datasets -v
2023-09-14 16:18:30,680 DEBUG: Removing output 'datasets' of stage: 'datasets.dvc'.
2023-09-14 16:18:30,680 DEBUG: Removing '/home/ubuntu/dvc_dataset_import/datasets'
Importing 'datasets (git@github.com:csdisco/matter-reviews-datasets.git)' -> 'datasets'
2023-09-14 16:18:30,682 DEBUG: Computed stage: 'datasets.dvc' md5: 'add6b69bcd15fef5a8197976b38b1180'
2023-09-14 16:18:30,682 DEBUG: 'md5' of stage: 'datasets.dvc' changed.
2023-09-14 16:18:30,683 DEBUG: Creating external repo git@github.com:csdisco/matter-reviews-datasets.git@None
2023-09-14 16:18:30,683 DEBUG: erepo: git clone 'git@github.com:xyz/matter-reviews-datasets.git' to a temporary dir
2023-09-14 16:18:32,072 ERROR: failed to import 'datasets' - SCM error: Failed to clone repo 'git@github.com:xyz/matter-reviews-datasets.git' to '/tmp/tmpwhwqlq0cdvc-clone': b'Mohit Anchlia <anchlia@xyz.com\n>'
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 220, in clone
    repo = clone_from()
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dulwich/porcelain.py", line 514, in clone
    return client.clone(
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dulwich/client.py", line 704, in clone
    _import_remote_refs(
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dulwich/refs.py", line 1260, in _import_remote_refs
    refs_container.import_refs(
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dulwich/refs.py", line 191, in import_refs
    self.set_if_equals(
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dulwich/refs.py", line 914, in set_if_equals
    self._log(
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dulwich/refs.py", line 123, in _log
    self._logger(ref, old_sha, new_sha, committer, timestamp, timezone, message)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dulwich/repo.py", line 1178, in _write_reflog
    check_user_identity(committer)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dulwich/repo.py", line 197, in check_user_identity
    raise InvalidUserIdentity(identity)
dulwich.repo.InvalidUserIdentity: b'Mohit Anchlia <anchlia@xyz.com\n>'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/scm.py", line 160, in clone
    git = Git.clone(url, to_path, progress=pbar.update_git, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 142, in clone
    backend.clone(url, to_path, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 225, in clone
    raise CloneError(url, to_path) from exc
scmrepo.exceptions.CloneError: Failed to clone repo 'git@github.com:csdisco/matter-reviews-datasets.git' to '/tmp/tmpwhwqlq0cdvc-clone'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/commands/imp.py", line 17, in run
    self.repo.imp(
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/repo/imp.py", line 6, in imp
    return self.imp_url(path, out=out, erepo=erepo, frozen=True, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/repo/__init__.py", line 64, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/repo/scm_context.py", line 151, in run
    return method(repo, *args, **kw)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/repo/imp_url.py", line 85, in imp_url
    stage.run(jobs=jobs, no_download=no_download)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/stage/__init__.py", line 600, in run
    self._sync_import(dry, force, kwargs.get("jobs", None), no_download)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/stage/decorators.py", line 43, in rwlocked
    return call()
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/stage/__init__.py", line 637, in _sync_import
    sync_import(self, dry, force, jobs, no_download)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/stage/imports.py", line 57, in sync_import
    stage.save_deps()
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/stage/__init__.py", line 491, in save_deps
    dep.save()
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/dependency/repo.py", line 58, in save
    rev = self.fs.repo.get_rev()
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/fs/dvc.py", line 427, in repo
    return self.fs.repo
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/fs/dvc.py", line 416, in fs
    return _DVCFileSystem(**self.fs_args)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/fsspec/spec.py", line 79, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/fs/dvc.py", line 128, in __init__
    repo = self._make_repo(url=url, rev=rev, subrepos=subrepos, **repo_kwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/fs/dvc.py", line 188, in _make_repo
    with Repo.open(uninitialized=True, **kwargs) as repo:
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/repo/open_repo.py", line 30, in _external_repo
    path = _cached_clone(url, rev, for_write=for_write)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/repo/open_repo.py", line 154, in _cached_clone
    clone_path, shallow = _clone_default_branch(url, rev, for_write=for_write)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/funcy/decorators.py", line 47, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/funcy/flow.py", line 246, in wrap_with
    return call()
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/funcy/decorators.py", line 68, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/repo/open_repo.py", line 222, in _clone_default_branch
    git = clone(url, clone_path)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/dvc/scm.py", line 165, in clone
    raise CloneError("SCM error") from exc
dvc.scm.CloneError: SCM error
`

### Reproduce

`dvc import git@github.com:xyz/abc-def-datasets.git datasets -v`

### Expected

DVC data is imported and cached

### Environment information

Ubuntu - dvc 3.5.1

**Output of `dvc doctor`:**

```console
dvc doctor
DVC version: 3.5.1 (pip)
------------------------
Platform: Python 3.10.12 on Linux-5.15.0-1021-aws-x86_64-with-glibc2.31
Subprojects:
	dvc_data = 2.5.0
	dvc_objects = 0.23.0
	dvc_render = 0.5.3
	dvc_task = 0.3.0
	scmrepo = 1.0.4
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2023.6.0, boto3 = 1.26.161)
Config:
	Global: /home/ubuntu/.config/dvc
	System: /etc/xdg/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/nvme0n1p1
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/45ea7f3a61a7c15c6377cd56220c0328```

**Comment by mohitanchlia** [comment]
I corrected git username and email
