### ISSUE TITLE
add: Fails on datetime strings in params.yaml

### ISSUE THREAD

**Issue by igordertigor** [iterative/dvc#9957]
## Description

I'm trying to add data to dvc and dvc complains about a datetime string in my `params.yaml` file:
```
ERROR: unexpected error - Unsupported value of type 'datetime' in 'params.yaml:start_date'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```
Of course, the data is not added after this.

### Reproduce

Unfortunately, I can't easily reproduce this in an isolated environment. However, with `-v`, I get the following output:
```
2023-09-18 12:06:52,650 DEBUG: v3.21.1 (pip), CPython 3.11.4 on Linux-5.15.0-10075-tuxedo-x86_64-with-glibc2.31
2023-09-18 12:06:52,650 DEBUG: command: /home/xxx/.venv/bin/dvc add data/ -v
2023-09-18 12:06:52,817 ERROR: unexpected error - Unsupported value of type 'datetime' in 'params.yaml:start_date'
Traceback (most recent call last):
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/cli/__init__.py", line 209, in main
    ret = cmd.do_run()
          ^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
           ^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/commands/add.py", line 47, in run
    self.repo.add(
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/repo/__init__.py", line 61, in wrapper
    return f(repo, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/repo/scm_context.py", line 151, in run
    return method(repo, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/repo/add.py", line 211, in add
    stages_with_targets = {
                          ^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/repo/add.py", line 212, in <dictcomp>
    target: get_or_create_stage(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/repo/add.py", line 66, in get_or_create_stage
    (out_obj,) = repo.find_outs_by_path(target, strict=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/repo/__init__.py", line 539, in find_outs_by_path
    outs = outs or self.index.outs_graph
                   ^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/funcy/objects.py", line 25, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
                                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/repo/__init__.py", line 290, in index
    return Index.from_repo(self)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/repo/index.py", line 242, in from_repo
    for _, idx in collect_files(repo, onerror=onerror):
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/repo/index.py", line 100, in collect_files
    index = Index.from_file(repo, file_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/repo/index.py", line 265, in from_file
    stages=list(dvcfile.stages.values()),
                ^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/funcy/objects.py", line 25, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
                                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/dvcfile.py", line 306, in stages
    return self.LOADER(self, self.contents, self.lockfile_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/stage/loader.py", line 33, in __init__
    self.resolver = self.dvcfile.resolver
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/funcy/objects.py", line 25, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
                                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/dvcfile.py", line 302, in resolver
    return DataResolver(self.repo, wdir, self.contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/parsing/__init__.py", line 157, in __init__
    self.context.load_from_vars(*args, default=DEFAULT_PARAMS_FILE)
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/parsing/context.py", line 436, in load_from_vars
    self.merge_from(fs, default, wdir)
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/parsing/context.py", line 397, in merge_from
    ctx = Context.load_from(fs, path, select_keys)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/parsing/context.py", line 377, in load_from
    ctx = cls(data, meta=meta)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/parsing/context.py", line 298, in __init__
    super().__init__(*args, **kwargs)
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/parsing/context.py", line 267, in __init__
    self.update(mapping)
  File "<frozen _collections_abc>", line 949, in update
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/parsing/context.py", line 275, in __setitem__
    return super().__setitem__(key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/parsing/context.py", line 191, in __setitem__
    self.data[key] = self._convert(key, value)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/parsing/context.py", line 168, in _convert
    return self._convert_with_meta(value, meta)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.venv/lib/python3.11/site-packages/dvc/parsing/context.py", line 182, in _convert_with_meta
    raise TypeError(msg)
TypeError: Unsupported value of type 'datetime' in 'params.yaml:start_date'

2023-09-18 12:06:52,845 DEBUG: Version info for developers:
DVC version: 3.21.1 (pip)
-------------------------
Platform: Python 3.11.4 on Linux-5.15.0-10075-tuxedo-x86_64-with-glibc2.31
Subprojects:
	dvc_data = 2.16.1
	dvc_objects = 1.0.1
	dvc_render = 0.6.0
	dvc_task = 0.3.0
	scmrepo = 1.3.1
Supports:
	gs (gcsfs = 2023.9.1),
	http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3)
Config:
	Global: /home/ingo/.config/dvc
	System: /etc/xdg/xdg-i3/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: gs
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/79075d1605214348e379b68f02493ff5

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-09-18 12:06:52,847 DEBUG: Analytics is enabled.
2023-09-18 12:06:52,859 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmporfbyhbp']'
2023-09-18 12:06:52,860 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmporfbyhbp']'
```

### Expected

I expected the data to be added without any error messages.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.21.1 (pip)
-------------------------
Platform: Python 3.11.4 on Linux-5.15.0-10075-tuxedo-x86_64-with-glibc2.31
Subprojects:
	dvc_data = 2.16.1
	dvc_objects = 1.0.1
	dvc_render = 0.6.0
	dvc_task = 0.3.0
	scmrepo = 1.3.1
Supports:
	gs (gcsfs = 2023.9.1),
	http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3)
Config:
	Global: /home/xxx/.config/dvc
	System: /etc/xdg/xdg-i3/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: gs
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/79075d1605214348e379b68f02493ff5
```

**Additional Information (if any):**

It is possible to work around this by using quoted dates in the yaml file, i.e. 
```yaml
this_fails: 2023-09-18T14:25:00.000
this_is_ok: "2023-09-18T14:25:00.000
```
This somewhat suggests that this is related to the notorious `datetime` handling in python's `json` stdlib module.

**Comment by dberenbaum** [comment]
Hi @igordertigor! I think this is a duplicate of #5868, and I see you already found the workaround, which is to quote the datetime and treat it as a string. Closing this one but comment in the other issue if you have more to add.
