### ISSUE TITLE
`dvc pull`: no exit error code provided when network is down

### ISSUE THREAD

**Issue by federico-gelmo** [iterative/dvc#9961]
# Bug Report

## no exit error code provided when network is down

I expect the dvc process to return an error exit code when the model pulling fails due to a network connectivity error. Instead the exit code provided is 0

### Reproduce

Example:

```
Pulling model mymodel.dvc
_request non-retriable exception: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb083c949a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Traceback (most recent call last):
  File "urllib3/connection.py", line 174, in _new_conn
  File "urllib3/util/connection.py", line 72, in create_connection
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 703, in urlopen
  File "urllib3/connectionpool.py", line 386, in _make_request
  File "urllib3/connectionpool.py", line 1042, in _validate_conn
  File "urllib3/connection.py", line 358, in connect
  File "urllib3/connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fb083c949a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 489, in send
  File "urllib3/connectionpool.py", line 787, in urlopen
  File "urllib3/util/retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb083c949a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "google/auth/transport/requests.py", line 193, in __call__
  File "requests/sessions.py", line 587, in request
  File "requests/sessions.py", line 701, in send
  File "requests/adapters.py", line 565, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb083c949a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gcsfs/retry.py", line 115, in retry_request
  File "gcsfs/core.py", line 405, in _request
  File "gcsfs/core.py", line 384, in _get_headers
  File "gcsfs/credentials.py", line 185, in apply
  File "gcsfs/credentials.py", line 180, in maybe_refresh
  File "google/oauth2/service_account.py", line 429, in refresh
  File "google/oauth2/_client.py", line 294, in jwt_grant
  File "google/oauth2/_client.py", line 255, in _token_endpoint_request
  File "google/oauth2/_client.py", line 204, in _token_endpoint_request_no_throw
  File "google/oauth2/_client.py", line 180, in _perform_request
  File "google/auth/transport/requests.py", line 199, in __call__
  File "<string>", line 3, in raise_from
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb083c949a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
ERROR: unexpected error - HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb083c949a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')): HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb083c949a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

### Expected

A returned process exit code different than 0

### Environment information

running the command from a script, inside a `debian:buster` docker image

**Output of `dvc doctor`:**

```console
DVC version: 2.51.0 (pip)
-------------------------
Platform: Python 3.10.12 on Linux-6.2.0-10022-tuxedo-x86_64-with-glibc2.35
Subprojects:
        dvc_data = 0.44.1
        dvc_objects = 0.21.1
        dvc_render = 0.3.1
        dvc_task = 0.2.0
        scmrepo = 0.1.16
Supports:
        gs (gcsfs = 2023.4.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)

```

**Comment by skshetry** [comment]
Closing as stale.
