### ISSUE TITLE
dvcfs: Can't `copyfile` when `fsspec` passes a non-DVC callback

### ISSUE THREAD

**Issue by bilelomrani1** [iterative/dvc#9984]
# Bug Report

I'm using HuggingFace `datasets` to load a dataset directly from a DVC repo using 

```python
import datasets

datasets.load_dataset("json", data_files="dvc://...", storage_options={"dvc": {"url": ..., "rev": ...}})
```

I encounter a `AttributeError: __enter__` from [this line](https://github.com/iterative/dvc-objects/blob/1b0eb142168cb53180549317f591745a727eee98/src/dvc_objects/fs/utils.py#L167). Unrolling the stacktrace, I realized that `datasets` passes a callback to `fs.get_file` ([here](https://github.com/huggingface/datasets/blob/faedc670ca896584d0f8edcb1fd9c13d1d6cc903/src/datasets/utils/file_utils.py#L367)) and that this callback is of type `datasets.utils.file_utils.TqdmCallback` which does not implement the context manager API `__enter__` and `__exit__`. However it is still propagated to `Callback.as_tqdm_callback` where it is expected that the wrapped callback is of type [`dvc_objects.fs.callbacks.Callback`](https://github.com/iterative/dvc-objects/blob/1b0eb142168cb53180549317f591745a727eee98/src/dvc_objects/fs/callbacks.py#L20). 

A possible fix is to change the `as_tqdm_callback` method to expect an optional generic `fsspec.callbacks.Callback` object:

```python
    @classmethod
    def as_tqdm_callback(
        cls,
        callback: Optional[fsspec.callbacks.Callback] = None,
        **tqdm_kwargs: Any,
    ) -> "Callback":
        return callback if isinstance(callback, cls) else TqdmCallback(**tqdm_kwargs)
```

EDIT: Looking at the API, it seems that all callbacks in `dvc-objects` are expected to derive from `dvc_objects.fs.callbacks.Callback` and thus are expected to implement `__enter__` and `__exit__` but it is not the case for a generic `fsspec.callbacks.Callback` so the classes in `dvc-objects` do not play very nicely with the rest of the `fsspec` ecosystem.

**Comment by bilelomrani1** [comment]
Thank you for the quick answer, sure, there it is

```
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/dvc_objects/fs/utils.py", line 162, in copyfile
    system.reflink(src, dest)
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/dvc_objects/fs/system.py", line 103, in reflink
    _reflink_darwin(source, link_name)
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/dvc_objects/fs/system.py", line 77, in _reflink_darwin
    raise OSError(err, msg)
FileExistsError: [Errno 17] File exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/bin/llm-core-cli", line 8, in <module>
    sys.exit(entrypoint())
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/llm_core/cli/__main__.py", line 23, in entrypoint
    CLI.run()
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/llm_core/cli/command_registry.py", line 122, in run
    command.run()
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/llm_core/cli/commands/sft.py", line 221, in run
    self.trainer.fit(
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 932, in _run
    self._data_connector.prepare_data()
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 94, in prepare_data
    call._call_lightning_datamodule_hook(trainer, "prepare_data")
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 166, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/llm_core/sft/data_module.py", line 115, in prepare_data
    builder.download_and_prepare()
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/datasets/builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/datasets/builder.py", line 1027, in _download_and_prepare
    split_generators = self._split_generators(dl_manager, **split_generators_kwargs)
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/datasets/packaged_modules/json/json.py", line 51, in _split_generators
    data_files = dl_manager.download_and_extract(self.config.data_files)
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/datasets/download/download_manager.py", line 565, in download_and_extract
    return self.extract(self.download(url_or_urls))
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/datasets/download/download_manager.py", line 428, in download
    downloaded_path_or_paths = map_nested(
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 464, in map_nested
    mapped = [
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 465, in <listcomp>
    _single_map_nested((function, obj, types, None, True, None))
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 384, in _single_map_nested
    mapped = [_single_map_nested((function, v, types, None, True, None)) for v in pbar]
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 384, in <listcomp>
    mapped = [_single_map_nested((function, v, types, None, True, None)) for v in pbar]
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 367, in _single_map_nested
    return function(data_struct)
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/datasets/download/download_manager.py", line 454, in _download
    return cached_path(url_or_filename, download_config=download_config)
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/datasets/utils/file_utils.py", line 182, in cached_path
    output_path = get_from_cache(
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/datasets/utils/file_utils.py", line 642, in get_from_cache
    fsspec_get(url, temp_file, storage_options=storage_options, desc=download_desc)
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/datasets/utils/file_utils.py", line 367, in fsspec_get
    fs.get_file(paths[0], temp_file.name, callback=callback)
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/dvc/fs/dvc.py", line 422, in get_file
    return self.repo.fs.get_file(fs_path, lpath, **kwargs)
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 556, in get_file
    self.fs.get_file(from_info, to_info, callback=callback, **kwargs)
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/dvc_objects/fs/local.py", line 105, in get_file
    copyfile(rpath, lpath, callback=callback)
  File "/Users/bilelomrani/Documents/ILLUIN.nosync/multi-task-models/.venv/lib/python3.10/site-packages/dvc_objects/fs/utils.py", line 167, in copyfile
    with Callback.as_tqdm_callback(
AttributeError: __enter__
Downloading data:   0%|                                                                       | 0.00/1.42M [00:00<?, ?B/s]
Downloading data files:   0%|                                                                       | 0/2 [00:00<?, ?it/s]
```

**Comment by dberenbaum** [comment]
@pmrowla Could you take a look?

**Comment by pmrowla** [comment]
@bilelomrani1 can you try installing the upstream patch and verify that it fixes the issue for you when using huggingface `datasets`

(in your DVC/datasets virtualenv)
```
pip install 'dvc-objects @ git+https://github.com/iterative/dvc-objects.git@refs/pull/227/head'
```

**Comment by bilelomrani1** [comment]
Hi @pmrowla, I can confirm that the upstream patch fixes the issue, thank you for your help.
